cluster-autoscaler/README.md
Kubernets changed to Kubernetes
=> Minor Typo Change

cluster-autoscaler/README.md
Also removed trailing whitespace
=> fix a link in readme

cluster-autoscaler/FAQ.md
Random readability edits & grammar fixes.
=> Clean up some grammar and punctuation.

cluster-autoscaler/main.go, cluster-autoscaler/simulator/predicates.go
Fix for https://github.com/kubernetes/contrib/issues/2507
=> Fix PVC informer issue

cluster-autoscaler/FAQ.md, cluster-autoscaler/update_toc.py
=> Table of contents for FAQ

cluster-autoscaler/core/static_autoscaler.go
Previously we were ignoring potential error in ClusterStateRegistry.UpdateNodes (which actually hits cloud provider internally and so may actually fail, leaving ClusterStateRegistry reflecting old state).
=> Fix error handling for updating node status

cluster-autoscaler/README.md
=> Update readme for CA 0.5.2

cluster-autoscaler/core/scale_down.go
If a pod is ignoring SIGTERMs and a bad timing happens we may give up waiting for the pod to be killed by Kubelet after MaxGracefulTermination before this timeout actually happen. This PR adds an additional time to the pod checking routine that should get ensure that we catch the pod deletion by SIGKILL and correctly proceed with node drain.
cc: @MaciekPytel @andrewsykim 
ref: #32
=> Add deletion safety margin to node drain

cluster-autoscaler/README.md
=> Readme update for 0.5.4

cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
Step 2 for scale to/from 0.
Ref: #43
cc @MaciekPytel @fgrzadkowski
=> Build node template in GCE cloud provider

cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
So that the readiness checking code work properly.
cc: @MaciekPytel 
Ref: #43
=> Set ready status in gce node template

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/metrics/metrics.go
Part 1 of implementation of #59  - "Cluster state" metrics
=> Added CA metrics related to cluster state

cluster-autoscaler/utils/daemonset/daemonset.go, cluster-autoscaler/utils/daemonset/daemonset_test.go
=> Daemonset helper function that returns pods that DaemonSet controller would start on the given node.

cluster-autoscaler/core/dynamic_autoscaler.go, cluster-autoscaler/core/polling_autoscaler.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go
Part 2 of implementation of #59 - "CA execution" metrics
=> Added CA metrics related to autoscaler execution

README.md
To promote weekly sig meetings and boost autoscaling slack channel.
cc: @MaciekPytel @mumoshu  @fgrzadkowski @andrewsykim
=> Contact information in the main README.md

README.md
=> Whats inside - summary of projects available in the repository

cluster-autoscaler/core/utils.go
=> Prefer using ready nodes and cloudprovider template nodes over unready/unschedulable nodes in scale-up

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/config/dynamic/node_group_spec.go
=> Enable min size 0 in gce

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
=> Handle custom machine types in GCE cloud provider

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go
Previously we were treating empty groups as unready and is scaling up could be incorrect.
Ref: #43
=> Handle empty node groups in cluster state

cluster-autoscaler/main.go, cluster-autoscaler/metrics/liveness.go, cluster-autoscaler/metrics/liveness_test.go
Basic health check to use with liveness probe.
=> Add health check

cluster-autoscaler/FAQ.md
Currently we don't have any standard process for testing Cluster Autoscaler, other than passing travis (which only run unittests, etc). Ideally we should setup automatic e2e run on presubmit, but I don't think we'll manage to do it before k8s 1.7.
So in the meantime I propose the following process for more complicated pull requests. What do you think?
=> Add description of testing PR to CA FAQ

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
=> Pricing model interface for CA

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go, cluster-autoscaler/utils/test/test_utils.go
=> GCE pricing model

cluster-autoscaler/proposals/pricing.md
=> Price-based node group ranking function proposal

cluster-autoscaler/expander/price/price.go, cluster-autoscaler/expander/price/price_test.go
ref: #82 
design: #87 
Missing: Preferred node part.
=> Price-preferred node expander - part 1

cluster-autoscaler/expander/price/preferred.go, cluster-autoscaler/expander/price/preferred_test.go, cluster-autoscaler/expander/price/types.go, cluster-autoscaler/utils/kubernetes/listers.go
=> Preferred node in price-preferred expander

cluster-autoscaler/proposals/balance_similar.md
Ref: #47 
@mumoshu - does that look good to you?
=> Proposal for balancing node groups for multizone

cluster-autoscaler/simulator/drain.go
=> Add checking namespace to matching pods with PDBs

cluster-autoscaler/FAQ.md
To make them more discoverable.
=> Proposals in FAQ

cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go, cluster-autoscaler/utils/nodegroupset/compare_nodegroups_test.go, cluster-autoscaler/utils/test/test_utils.go
=> Function to compare nodeinfos to find similar nodegroups

cluster-autoscaler/expander/price/price.go, cluster-autoscaler/expander/price/price_test.go
Ref: #82 
The tests will be rewritten to be specified in a table-like form in the next PR.
=> Combine price and preferred node in price expander

cluster-autoscaler/utils/nodegroupset/node_group_set.go, cluster-autoscaler/utils/nodegroupset/node_group_set_test.go
=> Function to find similar nodegroups

.travis.yml, cluster-autoscaler/Godeps/Godeps.json, cluster-autoscaler/builder/Dockerfile, hack/verify-gofmt.sh
Same version as k8s. Full godeps update will go out
in separate commit.
=> Update to go1.8.3

cluster-autoscaler/utils/nodegroupset/scale_up.go, cluster-autoscaler/utils/nodegroupset/scale_up_test.go
=> Function to balance scale-up between node groups

cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/main.go
=> Balance sizes of similar nodegroups in scale-up

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/autoscaler_builder.go, cluster-autoscaler/core/autoscaler_test.go, cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/dynamic_autoscaler.go, cluster-autoscaler/core/dynamic_autoscaler_test.go, cluster-autoscaler/core/polling_autoscaler.go, cluster-autoscaler/core/polling_autoscaler_test.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/expander/expander.go, cluster-autoscaler/expander/factory/expander_factory.go, cluster-autoscaler/expander/price/preferred.go, cluster-autoscaler/expander/price/preferred_test.go, cluster-autoscaler/expander/price/price_test.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/nodes.go, cluster-autoscaler/utils/errors/errors.go, cluster-autoscaler/utils/nodegroupset/node_group_set.go, cluster-autoscaler/utils/nodegroupset/scale_up.go
=> Enable pricing in expander factory

cluster-autoscaler/FAQ.md
Added questions about new features coming in 0.6: metrics / livenessProbe and balancing node groups.
=> CA 0.6 FAQ update

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go
=> Don't calculate utilisation and run scale down simulations for unmanaged nodes

cluster-autoscaler/simulator/drain.go
cc: @MaciekPytel 
Fixes: https://github.com/kubernetes/contrib/issues/1998
=> Fix comments in simulator/drain.go

cluster-autoscaler/FAQ.md
Add info about draining nodes with system pods.
=> Update docs regarding system pods eviction

cluster-autoscaler/update_toc.py
This fixes generating broken links for sections with dashes in title
=> Fix removing dash in section title

cluster-autoscaler/README.md
cc: @MaciekPytel @aleksandra-malinowska @mumoshu
=> Release notes for CA 0.6

cluster-autoscaler/FAQ.md, cluster-autoscaler/README.md
cc: @aleksandra-malinowska @MaciekPytel
=> FAQ-ReleaseNotes cross links

cluster-autoscaler/proposals/kubemark_integration.md
Proposal for running Cluster Autoscaler on [kubemark](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubemark.md). This will be useful in scalability tests of Cluster Autoscaler.
@mwielgus 
@MaciekPytel
@aleksandra-malinowska
=> Kubemark integration proposal.

vertical-pod-autoscaler/updater/updater.go
including:
- import cleanup
- logging cleanup
- minor code cleanup
=> updater: cleanup updater.go

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/polling_autoscaler_test.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/utils_test.go, cluster-autoscaler/expander/price/price_test.go, cluster-autoscaler/utils/nodegroupset/node_group_set_test.go, cluster-autoscaler/utils/nodegroupset/scale_up_test.go
Renaming to maintain consistent package and directory names
=> Rename testprovider package

cluster-autoscaler/core/static_autoscaler.go
Move collecting data after API call.
=> Change scope of scaleUp metric

addon-resizer/Dockerfile, addon-resizer/Makefile
This PR is for creating multi architecture image for addon-resizer
=> Mutiarch addon-resizer image

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
As discussed in #166 part of #43
cc @MaciekPytel @mumoshu  @justinsb
=> Add taints to AWS node template

cluster-autoscaler/core/static_autoscaler.go
Temporary change to unblock @aleksandra-malinowska and @bskiba who are running performance tests. Pod condition restets proved to be a big bottleneck. We need more time to provide a good replacement for pod condition reset and within that time we will allow to turn off reseting to find other performance problems.  
cc: @aleksandra-malinowska @bskiba @MaciekPytel
=> Add a flag to turn off pod status condition reseting for performance tests

cluster-autoscaler/clusterstate/clusterstate.go
Currently we log 2 warnings per node group with 0 size per loop.
=> Stop spamming warnings for every 0 size nodegroup

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go
=> Cherry-pick: Fix getEmptyNodes function in CA

cluster-autoscaler/version.go
cc: @MaciekPytel @bskiba @aleksandra-malinowska
=> Set CA version to 0.6.1 in 0.6 release branch

cluster-autoscaler/proposals/node_autoprovisioning.md
cc: @MaciekPytel @aleksandra-malinowska @bskiba @mumoshu @kubernetes/sig-autoscaling-feature-requests
=> Node Auto-provisioning proposal doc

cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/main.go
Ref: #187 (includes my long comment explaining this change).
cc: @aleksandra-malinowska @bskiba
=> Remove PodScheduled filter

cluster-autoscaler/utils/labels/labels.go, cluster-autoscaler/utils/labels/labels_test.go
=> NAP - pick best labels for pods

cluster-autoscaler/FAQ.md
cc: @MaciekPytel @bskiba @aleksandra-malinowska @wasylkowski
=> Godep update in FAQ

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/expander/waste/waste_test.go
=> Node Autoprovisioning expansion of CloudProvider api

cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go
This should help performance problems in FilterOutSchedulable if there are thousands of pending pods, provided they were created by a smaller set of controllers.
=> Re-use results for similar pods in FilterOutSchedulable

vertical-pod-autoscaler/updater/priority/update_priority_calculator.go
=> Fix minor typo

cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/main.go
This allows to run Custer Autoscaler on Kubemark.
See autoscaler/cluster-autoscaler/proposals/kubemark_integration.md
for more details.
=> Cloud Provider Interface for Kubemark

cluster-autoscaler/simulator/predicates.go
Previously CA run predicates in random order, this change makes it
run them starting with relatively cheap and most likely to fail
predicates, to avoid running more complex ones if they're not required.
=> Run basic predicates first in every check

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/predicates.go, cluster-autoscaler/simulator/predicates_test.go, cluster-autoscaler/utils/daemonset/daemonset.go
Turns out all this string formatting is pretty damn expensive.
=> Don't create verbose errors in predicates if we ignore them

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/expander/waste/waste_test.go
* compilation fixes in kubemark
* autoprovisioned() bool function in NodeGroup
* minor refactoring in GCE cloud provider
=> NAP interface implementation - part 1

addon-resizer/Makefile
Fix addon_resizer clean target for backward image.
/cc @mwielgus @bskiba
=> fix addon_resizer backword image deletion

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go
=> Skip node in scale-down if it was recently found unremovable

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
* NAP machine list
* NAP machine template
* minor modifications to MIG
=> Node autoprovisioning - CP interface impl - part 2

cluster-autoscaler/main.go
Add kubeconfig flag to create kube-client.
@MaciekPytel  Please review this.Thanks.
#223
=> add kubeconfig flag to create kube-client

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/predicates.go, cluster-autoscaler/simulator/predicates_test.go, cluster-autoscaler/utils/daemonset/daemonset.go
=> precompute predicateMetadata in scale-down

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go
=> Create and delete node pool operations for gce_manager

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/expander/price/price.go, cluster-autoscaler/main.go
=> Node autoprovisioning in scale up

cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/main.go
=> Keep maximum 30 candidates for scale down with drain

cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go, cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/kubernetes/factory.go, cluster-autoscaler/utils/nodegroupset/scale_up.go
=> Set verbosity for each of the glog.Info logs

cluster-autoscaler/main.go
The lock type parameter was being ignored. Use the new factory method to
instantiate the lock type.
=> Support resource-lock type configmap for leader election

cluster-autoscaler/cloudprovider/aws/README.md
**What?**
Information on running CA in master node in aws. 
This PR updates the documentation for it.
=> Run CA in master node - aws

cluster-autoscaler/version.go
So that we can release a test version and push to official CI.
=> Bump CA version to 0.7.0-alpha2

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
To allow ScaleUp/ScaleDown unit test for Node Autoprovisioning.
=> Expand test cloud provider with autoprovisioning options

cluster-autoscaler/simulator/cluster_test.go
Refactored for easier maintenance (reduces repetitive code).
=> Refactor FindNodesToRemove test

cluster-autoscaler/FAQ.md
=> Describe scale down disabled annotation in Cluster Autoscaler FAQ

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go
Regardless of the limits we have for scale down candidates, always mark all empty nodes as unneeded.
https://github.com/kubernetes/autoscaler/issues/314
=> Always add empty nodes to unneeded nodes

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go
=> Remove nodes that are not in the cluster from unremovableNodes

cluster-autoscaler/core/scale_down.go
Mark empty nodes to be deleted with the same taint that is used for node drain.
=> Taint empty nodes to be deleted

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/utils.go
This function talks to cloud provider api and can be throttled (especially on AWS).
cc: @mtcode
=> Remove TargetSize() from loops iterating over nodes

README.md
cc: @DirectXMan12 @MaciekPytel @aleksandra-malinowska @bskiba
=> Move sig vc call to Monday

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/metrics/metrics.go
A minor refactor was required to avoid cyclic imports
=> Add metric counting failed scale-ups

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go
In case when node was successfully drained, but cloud provider error prevented its deletion, ToBeDeleted taint remains on the node. It happened in this test run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-migs/6052
=> Fix leaking taints in case of cloud provider error on node deletion

cluster-autoscaler/metrics/metrics.go
For now it's just a placeholder, will add proper logic
for next release
=> Add reason field to faied_scale_ups_total metric

cluster-autoscaler/proposals/scalability_tests.md
This report will be linked to from CA release notes.
=> Cluster Autoscaler scalability testing report

hack/scripts/break_mig.py
Added option for only breaking a few nodes not all of them.
=> Update script for testing broken nodes in CA

vertical-pod-autoscaler/recommender/model/types.go
to be used by both metrics client and histogram aggregator
@mwielgus @kgrygiel - please reveiw
=> Internal data model for recommender

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/metrics/metrics.go
Cherry-pick of #375 to 1.0 branch
=> Add failed scale-up reason in metric

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/core/static_autoscaler_test.go
https://github.com/kubernetes/autoscaler/pull/374
=> Fix setting target size for group in core/static_autoscaler_test.go.

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/utils/test/test_utils.go
Cherry-pick of #379 to release 1.0
=> Keep track of nodes that failed to register for a long time

cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
Ref: https://github.com/kubernetes/autoscaler/pull/377
=> Cherrypick Compute allocatable for auto-provisioned migs

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go
Ref: https://github.com/kubernetes/autoscaler/pull/395 (one of 2 commits in this PR)
=> Cherrypick Fix some bugs in GKE cloudprovider

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
fixes gpu issue in #321 and #346
=> update aws instance types

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/autoscaling_context_test.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-api.json, cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-gen.go
Cherrypick various fixes for node autoprovisioning on GKE.
=> Fixes for GKE cloudprovider and autoprovisioning

README.md
Updating README with the new zoom link based on the previous meeting.
=> Updating zoom meeting link

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-api.json, cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-gen.go
Do not merge: not tested [enough] yet
=> update GKE cloudprovider to match changes in GKE API

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go
=> Cherrypick metrics for autoprovisioning

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-api.json, cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-gen.go
=> Cherrypick update GKE cloudprovider on release 1.0

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/core/polling_autoscaler.go, cluster-autoscaler/core/polling_autoscaler_test.go
Cherry-pick https://github.com/kubernetes/autoscaler/pull/422
=> Cherry-pick AWS DescribeAutoScalingGroups requests too aggressive to 1.0

addon-resizer/nanny/nanny_lib.go, cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/clusterstate/utils/status.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/expander/price/price.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/predicates.go, cluster-autoscaler/utils/errors/errors.go, cluster-autoscaler/utils/labels/labels.go, vertical-pod-autoscaler/initializer/core/initializer.go, vertical-pod-autoscaler/recommender/model/cluster_test.go, vertical-pod-autoscaler/recommender/model/types.go, vertical-pod-autoscaler/updater/updater.go
=> fix spelling for issue 443

cluster-autoscaler/FAQ.md
Adds KUBE_AUTOSCALER_ENABLE_SCALE_DOWN export to e2e test question in CA FAQ.
=> Adds KUBE_AUTOSCALER_ENABLE_SCALE_DOWN export to FAQ

cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
=> Cherry-pick safe-to-evict annotation to 1.0.3

cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/utils/gpu/gpu.go, cluster-autoscaler/utils/gpu/gpu_test.go
=> Cherry-pick "Consider GPU nodes unready until allocatable GPU is > 0"

cluster-autoscaler/FAQ.md, cluster-autoscaler/README.md, cluster-autoscaler/proposals/metrics.md
Cherry-pick of #425, #452, #455, #456, and #459.
=> Cherry-pick doc updates

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/core/static_autoscaler_test.go
=> Cherry-pick "Fix unit static autoscaler unit tests."

cluster-autoscaler/FAQ.md, cluster-autoscaler/README.md
Release notes for Cluster Autoscaler 1.0.3
=> Release notes for Cluster Autoscaler 1.0.3

cluster-autoscaler/Makefile, cluster-autoscaler/push_image.sh
Adds:
* Confirmation of pushed image.
* Check whether the image is already there.
=> Extra checks when pushing an image to gcr repository

vertical-pod-autoscaler/recommender/model/aggregations_config.go, vertical-pod-autoscaler/recommender/model/cluster.go, vertical-pod-autoscaler/recommender/model/container.go, vertical-pod-autoscaler/recommender/model/types.go, vertical-pod-autoscaler/recommender/util/histogram.go, vertical-pod-autoscaler/recommender/util/histogram_mock.go, vertical-pod-autoscaler/recommender/util/histogram_test.go
Small preparatory changes necessary before adding the recommender logic.
=> A few small improvements to the model types.

cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go
=> Don't register metrics unless on leading master

cluster-autoscaler/cloudprovider/azure/azure_manager.go
Cleanup comments and format error message.
=> Cleanup comments in azure provider

cluster-autoscaler/FAQ.md, cluster-autoscaler/simulator/cluster.go
=> Use allocatable instead of capacity to calculate node utilization

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go
=> Skip iteration if pending pods are too new

cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml
Continue of #522. Add operator and value to pod tolerations in azure example yaml.
/assign @mwielgus
=> Add operator and pod tolerations

vertical-pod-autoscaler/recommender/logic/estimator.go, vertical-pod-autoscaler/recommender/logic/estimator_test.go, vertical-pod-autoscaler/recommender/logic/recommender.go, vertical-pod-autoscaler/recommender/logic/recommender_test.go
Provide a simple implementation of the recommender that calculates
recommended resources based on provided percentiles of the CPU usage
and memory peaks distributions.
=> Introduce the PodResourceRecommender type.

addon-resizer/README.md
=> Version info in README

addon-resizer/Makefile, addon-resizer/README.md, addon-resizer/nanny/apis/nannyconfig/v1alpha1/defaults.go, addon-resizer/nanny/main/pod_nanny.go
Fast-forward release-1.8 branch to release-1 branch (release 1.8.1 was created from release-1 branch).
=> Addon resizer release 1.8

vertical-pod-autoscaler/deploy/metrics-reader.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/recommender/Dockerfile, vertical-pod-autoscaler/recommender/Makefile, vertical-pod-autoscaler/recommender/cluster/spec_client.go, vertical-pod-autoscaler/recommender/cluster/spec_client_test.go, vertical-pod-autoscaler/recommender/cluster/spec_client_test_util.go, vertical-pod-autoscaler/recommender/main.go, vertical-pod-autoscaler/recommender/model/types.go, vertical-pod-autoscaler/recommender/recommender.go
+ recommender containerization and deployment
Currently it just prints out specification to the logs.
@mwielgus 
@kgrygiel
=> spec client for VPA recommender 

vertical-pod-autoscaler/api/example.yaml, vertical-pod-autoscaler/api/vpa-crd.yaml
=> CustomResourceDefinition for vpa

vertical-pod-autoscaler/recommender/logic/recommender_test.go, vertical-pod-autoscaler/recommender/model/cluster_test.go, vertical-pod-autoscaler/recommender/model/container.go, vertical-pod-autoscaler/recommender/model/container_test.go, vertical-pod-autoscaler/recommender/recommender.go
=> Split ContainerUsageSample to per resource

vertical-pod-autoscaler/initializer/core/initializer_test.go, vertical-pod-autoscaler/pkg/utils/test/test_utils.go, vertical-pod-autoscaler/pkg/utils/test_utils.go, vertical-pod-autoscaler/recommender_mock/caching_recommender_test.go, vertical-pod-autoscaler/updater/eviction/pods_eviction_restriction_test.go, vertical-pod-autoscaler/updater/priority/update_priority_calculator_test.go, vertical-pod-autoscaler/updater/updater_test.go
=> Move test/test_utils to pkg/utils

addon-resizer/README.md
fix addon-resizer help info.
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
=> fix addon-resizer help info.

vertical-pod-autoscaler/recommender/model/types.go, vertical-pod-autoscaler/recommender/recommender.go
minimal change needed to load metrics into clusterState
follow-up refactorings will follow in separate PRs
@mwielgus @kgrygiel please review
=> [VPA recommender] Loading metrics to clusterState

vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/hack/vpa-down.sh, vertical-pod-autoscaler/hack/vpa-process-yamls.sh, vertical-pod-autoscaler/hack/vpa-up.sh, vertical-pod-autoscaler/updater/Makefile
Also unify default registries and tags in all vpa components.
=> Improvements to deploy scripts

vertical-pod-autoscaler/examples/hamster.yaml, vertical-pod-autoscaler/examples/redis.yaml, vertical-pod-autoscaler/samples/redis-vpa.yaml
+ change the number of hamster replicas to 2 so that VPA updater can actually update it.
=> Merge examples into one directory.

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/admission-controller/README.md, vertical-pod-autoscaler/recommender/README.md, vertical-pod-autoscaler/recommender/signals/history_provider.go, vertical-pod-autoscaler/recommender/signals/history_provider_test.go
=> Write some READMEs for VPA

cluster-autoscaler/core/static_autoscaler.go
=> Remove old unregistered nodes before checking cluster healthiness

vertical-pod-autoscaler/e2e/vertical_pod_autoscaling.go, vertical-pod-autoscaler/hack/run-e2e.sh
- e2e test to verify that recommender publishes recommendation.
- Script for running VPA e2e tests.
=> VPA e2e contribution

cluster-autoscaler/main.go
=> fix typo in main file

cluster-autoscaler/cloudprovider/azure/README.md
Fix typos paramters -> [parameters]  multipe -> [multiple]
=> Fix typos paramters -> [parameters]  multipe -> [multiple]

cluster-autoscaler/estimator/estimator.go, cluster-autoscaler/simulator/predicates.go
likekly -> likely
intialize -> initialize
ppod -> pod
=> Fix typo in code comment

cluster-autoscaler/README.md
=> Add release notes for 1.1.0 and 1.1.1 to readme

cluster-autoscaler/cloudprovider/aws/README.md
=> Update documentation: AWS now supports ARNs for autoscaling groups

builder/Dockerfile, cluster-autoscaler/Dockerfile
Use Debian base to build Cluster Autoscaler image.
=> Use Debian base to build Cluster Autoscaler image

cluster-autoscaler/OWNERS, cluster-autoscaler/cloudprovider/azure/OWNERS
Add me to cluster-autoscaler reviewers.
/assign @mwielgus @MaciekPytel
=> Add reviewers

builder/Dockerfile, cluster-autoscaler/Dockerfile
=> Use Debian image

cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go
Add disabling inter pod affinity predicate if only preferred / node affinity used.
=> Disable checking inter pod affinity predicate if not necessary

builder/Dockerfile
=> Add installing libseccomp-devel to builder

vertical-pod-autoscaler/hack/deploy-for-e2e.sh, vertical-pod-autoscaler/hack/run-e2e.sh
+ VPA creation and listing for debugging test-infra.
=>  Refine support for VPA e2e test suites.

vertical-pod-autoscaler/admission-controller/logic/recommendation_provider.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go, vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go, vertical-pod-autoscaler/updater/priority/update_priority_calculator.go, vertical-pod-autoscaler/updater/priority/update_priority_calculator_test.go
This also extracts common code from updater & admission controller to a library.
=> Make requests smaller or equal to limits

vertical-pod-autoscaler/e2e/admission_controller.go
=> VPA AC e2e tests - change min/max recommended to resource policy

addon-resizer/README.md
Preview available at https://github.com/kawych/autoscaler/tree/master/addon-resizer#addon-resizer-configuration
=> Document Addon Resizer configuration

cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/main.go
Use flag to identify regional clusters iinstead of relying on multi-zone property.
=> Add regional flag

cluster-autoscaler/utils/errors/errors.go
line 31 and line 82: "the typ of AutoscalerError"
here shoule be type
=> Typo fix "typ"->"type"

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/node_group_discovery_options.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/api/types.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/config/dynamic/config.go, cluster-autoscaler/core/autoscaling_context.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go, cluster-autoscaler/expander/price/price_test.go, cluster-autoscaler/simulator/nodes.go, cluster-autoscaler/simulator/predicates.go, cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go
=> Run spellchecker

vertical-pod-autoscaler/admission-controller/logic/recommendation_provider.go, vertical-pod-autoscaler/admission-controller/logic/recommendation_provider_test.go, vertical-pod-autoscaler/admission-controller/server.go, vertical-pod-autoscaler/pkg/common/consts.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go, vertical-pod-autoscaler/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/recommender/model/container.go
+ admission-controller sets limits
+ hooking up oom info in cluster feeder
=> VPA OOM support in admission controller

cluster-autoscaler/README.md
Add Cluster Autoscaler 1.2 as recommended version with Kubernetes 1.10
=> Add Cluster Autoscaler 1.2 as recommended version with Kubernetes 1.10

cluster-autoscaler/utils/drain/drain.go
=> Fix method name

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
=> Ensure azure reference non-empty

vertical-pod-autoscaler/e2e/common.go, vertical-pod-autoscaler/e2e/full_vpa.go, vertical-pod-autoscaler/hack/run-e2e.sh
=> Fix full-vpa e2e test: add missing assertions, increase timeouts

vertical-pod-autoscaler/e2e/full_vpa.go
@bskiba: sorry, I made a typo in the previous one and it seems test code is not unit tested... ;)
=> Fix a typo

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/hack/vpa-process-yaml.sh
=> Version update in vpa deployments

vertical-pod-autoscaler/README.md
=> More introduction in VPA readme

cluster-autoscaler/cloudprovider/aws/README.md, hack/verify-spelling.sh, vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/admission-controller/certs.go, vertical-pod-autoscaler/e2e/recommender.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go, vertical-pod-autoscaler/recommender/input/metrics/metrics_client.go, vertical-pod-autoscaler/recommender/input/oom/observer.go, vertical-pod-autoscaler/recommender/model/cluster.go, vertical-pod-autoscaler/recommender/model/container.go, vertical-pod-autoscaler/recommender/util/histogram.go
Add simple spellchecking script based on https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh
Unfortunately, it doesn't seem to catch all typos (e.g. didn't find #780). Patches welcome!
=> Add spellchecking script & batch fix typos

vertical-pod-autoscaler/recommender/output/checkpoint_writer.go
Line 55: glog.Errorf("Cannot serialize checkpotint for vpa %v container %v. Reason: %+v", vpa.ID.VpaName, container, err)
checkpotint->checkpoint
=> Fix retured err message

vertical-pod-autoscaler/recommender/model/aggregate_container_state.go
Line 107: Unssuported->Unsupported
=> correct the returned error message in aggregate_container_state.go

cluster-autoscaler/Godeps/Godeps.json, cluster-autoscaler/kubernetes.sync, cluster-autoscaler/vendor/k8s.io/client-go/discovery/discovery_client.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_backoff.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_standard.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/scheduler_binder.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/scheduler_binder_fake.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/features/kube_features.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/kubelet/container/runtime.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/printers/humanreadable.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/printers/interface.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/printers/versioned.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/factory/factory.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/volumebinder/volume_binder.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/volume/local/local.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go, cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
Update Cluster Autoscaler  dependencies before 1.2.2 release
=> Update Cluster Autoscaler dependencies

vertical-pod-autoscaler/README.md
Fixed architecture doc link
Added command to see current VPA recommendations
=> VPA readme update.

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_client.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-msi.yaml
This PR adds support for Azure Managed Service Identity (MSI). It also updates azure compute client to api version 2017-12-01, which is required to set ipforwarding for virtual machines. 
Fixes #711.
=> Add support for Azure Managed Service Identity (MSI)

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_client.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-msi.yaml
Cherry-pick of #805: Add support for Azure Managed Service Identity (MSI)
=> Cherry-pick of #805: Add support for Azure Managed Service Identity (MSI)

vertical-pod-autoscaler/recommender/model/container.go
=> Typo fix: memeory->memory

cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-containerservice.yaml
There is an indent error in AKS manifest file.
/cc @kkmsft @mwielgus
=> Fix autoscaler manifests yaml for AKS

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/utils/deletetaint/delete.go
=> Cherry pick stateful set drain 1.0

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/utils/deletetaint/delete.go
=> Cherry pick stateful set drain 1.1

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/utils/deletetaint/delete.go
=> Cherry pick stateful set drain 1.2

vertical-pod-autoscaler/admission-controller/logic/recommendation_provider.go, vertical-pod-autoscaler/admission-controller/logic/recommendation_provider_test.go, vertical-pod-autoscaler/admission-controller/main.go, vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/pkg/utils/test/test_utils.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go, vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go, vertical-pod-autoscaler/pkg/utils/vpa/recommendation_processor.go, vertical-pod-autoscaler/updater/main.go, vertical-pod-autoscaler/updater/priority/update_priority_calculator.go, vertical-pod-autoscaler/updater/priority/update_priority_calculator_test.go, vertical-pod-autoscaler/updater/updater.go, vertical-pod-autoscaler/updater/updater_test.go
- RecommendationProcessor interface - all modifications to recommendations should be done by RecommendationProcessor objects
- Refactoring of resource request capping code : use RecommendationProcessor interface
cc/ @mwielgus
=> Refactor recommendation post processing.

cluster-autoscaler/FAQ.md
Update instructions for adding dependencies to Cluster Autoscaler.
=> Update Godeps FAQ

cluster-autoscaler/FAQ.md, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/main.go
Update max unready nodes to 45%
=> Update max unready nodes to 45%

cluster-autoscaler/version.go
=> Cluster Autoscaler 1.2.2

cluster-autoscaler/version.go
=> Cluster Autoscaler 1.1.3

cluster-autoscaler/version.go
Update version to  version 1.0.6
=> Cluster Autoscaler 1.0.6

vertical-pod-autoscaler/admission-controller/logic/server.go, vertical-pod-autoscaler/admission-controller/main.go, vertical-pod-autoscaler/updater/logic/updater.go, vertical-pod-autoscaler/updater/logic/updater_test.go, vertical-pod-autoscaler/updater/main.go
Moved admission server and updater from main to importable packages.
=> Make admission controller server and updater importable

cluster-autoscaler/core/static_autoscaler.go
For a code review I suggest looking at the commits separately, the intent should be more visible then.
=> Reorder & extract initial parts of RunOnce

vertical-pod-autoscaler/admission-controller/logic/recommendation_provider.go, vertical-pod-autoscaler/admission-controller/logic/recommendation_provider_test.go, vertical-pod-autoscaler/admission-controller/logic/server.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
Add annotation to pods modified by VPA.
=> Pod vpa annotation

vertical-pod-autoscaler/pkg/utils/vpa/sequential_processor.go, vertical-pod-autoscaler/pkg/utils/vpa/sequential_processor_test.go
RecommendationProcessor that uses provided RecommendationProcessors in sequence provided on construction
=> Sequential recommendation processor

cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
Signature changed, linux code was changed.
=> Kubemark cloud provider doesn't compile on Mac

cluster-autoscaler/clusterstate/utils/status.go
Use explicit timestamp formatting in ClusterAutoscaler ConfigMap last update annotation.
=> Fix timestamp format in ClusterAutoscaler ConfigMap

vertical-pod-autoscaler/admission-controller/logic/server.go
=> VPA fix for handling empty resources section in container spec.

cluster-autoscaler/processors/status/scale_up_status_processor.go
This will be useful for the purposes of testing.
Also fix naming of Process() parameter.
=> Add NoOpScaleUpStatusProcessor

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/config/const.go, cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/units/units.go
=> Use bytes instead of MB for memory limits

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/cloud_provider_test.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go
This is preparatory work before introducing gpu limits to the codebase
=> Resource limits refactor in scale_down

cluster-autoscaler/version.go
Cluster Autoscaler 1.3.0-beta.1
=> Cluster Autoscaler 1.3.0-beta.1

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go
Preparatory work for before introducing GPU limits
=> Restructure checking resource limits in scale_up.go

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/hack/vpa-process-yamls.sh, vertical-pod-autoscaler/pkg/admission-controller/delete-webhook.sh
Add information on how to tear down vpa.
Add script deleting webhook on teardown.
=> Proper cleanup for vpa.

cluster-autoscaler/version.go
Cluster Autoscaler 1.3.0-beta.2
=> Cluster Autoscaler 1.3.0-beta.2

cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/main.go
Hi this is my first PR against the main(ish) parts of k8s, and I am unsure even how to run tests.
I'm hoping to add the feature requested in https://github.com/kubernetes/autoscaler/issues/933
=> issues/933 Consider making UnremovableNodeRecheckTimeout configurable

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.0
=> Cluster Autoscaler 1.3.0

vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/main.go, vertical-pod-autoscaler/pkg/updater/priority/pod_eviction_admission.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go
PodEvicitonAdmission adds ability to controll pod evicion based on pod
recommendation.
=> Add PodEvictionAdmission interface

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/processors/nodegroups/autoprovisioning_nodegroup_manager.go, cluster-autoscaler/processors/nodegroups/autoprovisioning_nodegroup_manager_test.go, cluster-autoscaler/processors/nodegroups/nodegroup_manager.go
=> Cherry-pick of Move removing unneeded autoprovisioned node groups to node group manager #1008

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
=> Cherry-pick of Validate taint key with regex #1005

cluster-autoscaler/cloudprovider/gce/gce_manager.go
=> Cherry-pick of Use Warningf instead Warning #1010

cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gpu.go
=> Cherry-pick of Add gpus to supportedResources map in GCE cloud provider #1011

addon-resizer/nanny/main/pod_nanny.go
=> Use protobufs in pod-nanny

addon-resizer/nanny/main/pod_nanny.go
/assign @piosz @x13n @MaciekPytel
=> Cherrypick: "Use protobufs in pod-nanny" to 1.8 branch of addon-resizer

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/utils/gpu/gpu.go
=> Cherry-pick of Add GPU-related scaled_up & scaled_down metrics #974

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/utils/gpu/gpu.go
Refactor and extend GPU metrics error types to better track missing GPUs.
=> Refactor and extend GPU metrics error types

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/proposals/metrics.md, cluster-autoscaler/utils/gpu/gpu.go
Cherry pick of #1017 and #1043
=> Cherry pick of GPU metrics fixes in #1017 and #1043

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go, vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go
Signed-off-by: Slawomir Chylek <schylek@google.com>
=> VPA treat pod evictions due to low memory at node as OOMs.

addon-resizer/Makefile
=> Build 1.8.2 image od addon resizer

cluster-autoscaler/FAQ.md
Small fix for spelling and indentation
=> fix spelling and indentation

cluster-autoscaler/FAQ.md, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
Cherry pick PR #1054 for release 1.1.
=> Cherry pick pod unsafe annotations for 1.1

cluster-autoscaler/FAQ.md, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
Cherry pick PR #1054 for release 1.2.
=> Cherry pick pod unsafe annotations for 1.2

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.1
=> Cluster Autoscaler 1.3.1

addon-resizer/nanny/estimator.go, addon-resizer/nanny/estimator_test.go, addon-resizer/nanny/main/pod_nanny.go
Add a command line flag allowing the use of an ExponentialEstimator with
a custom minimum cluster size. The default minimum cluster size is 16 to
retain compatibility with existing behaviour. Also tweak some unit test
error logging to make it easier to diagnose failures.
=> Add support for custom min cluster sizes

cluster-autoscaler/FAQ.md, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
Cherry pick PR #1054 for release 1.3.
=> Cherry pick pod unsafe annotations for 1.3

cluster-autoscaler/FAQ.md
Add updating kubernetes.sync to Godeps update instructions following discussion in #1053
=> Add updating kubernetes.sync to Godeps update instructions

addon-resizer/Makefile
=> bump addon resizer tag to 1.8.3

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
Fixes: https://github.com/kubernetes/autoscaler/issues/1103
=> VPA: don't overwrite existing annotations when patching pod

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go, vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/model/vpa.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/main.go, vertical-pod-autoscaler/pkg/utils/metrics/admission/admission.go, vertical-pod-autoscaler/pkg/utils/metrics/metrics.go, vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go
Added some basic metrics to all 3 VPA components.
@bskiba , please have a look.
=> Add metrics to VPA

vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/admission/admission.go, vertical-pod-autoscaler/pkg/utils/metrics/metrics.go, vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go
Covers Recommender's and Updater's RunOnce.
@bskiba, please have a look.
=> Add metrics for execution time of RunOnce

cluster-autoscaler/cloudprovider/gce/autoscaling_gke_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gke_client_v1.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gke_client_v1beta1.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gke_client_v1beta1_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
Extract autoscaling GKE client from GceManager.
=> Extract autoscaling GKE client

vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go
=> Fix label names to be in line with Prometheus conventions

vertical-pod-autoscaler/e2e/e2e.go
=> Add authorization to vpa e2e tests.

cluster-autoscaler/utils/tpu/tpu.go, cluster-autoscaler/utils/tpu/tpu_test.go
Cherry-pick of #1168: Ignore resources with Cloud TPU prefix
cc @yguo0905
=> Cherry-pick of #1168: Ignore resources with Cloud TPU prefix

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/utils/tpu/tpu.go, cluster-autoscaler/utils/tpu/tpu_test.go
Cherry-pick of #791: Ignore TPU resource in simulations
=> Cherry-pick of #791: Ignore TPU resource in simulations

cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-containerservice.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-master.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss.yaml
Jobs and CronJobs were both missing so far which makes the cluster-autoscaler complain that it doesn't have access to "batch".
=> Add batch jobs and cronjobs to Azure cluster-autoscaler

cluster-autoscaler/FAQ.md
Replace duplicated doc to a link
=> [doc] Replace to link

vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/priority/pod_eviction_admission.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go
Additionally, remove failed and succeeded pods from live pods list.
=> Initialize eviction restriction with pods controlled by VPA.

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/processors/status/eventing_scale_up_processor.go, cluster-autoscaler/processors/status/eventing_scale_up_processor_test.go, cluster-autoscaler/processors/status/scale_up_status_processor.go
=> Pass NoScaleUpInfo to ScaleUpStatus processor

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/utils/test/test_utils.go
Check for ready condition not true instead of just false.
/cc @losipiuk
=> Check for ready condition not true

vertical-pod-autoscaler/pkg/recommender/main.go
For a cluster with a large number of vpa objects, the default qps is too low (5 I believe) for it to finish processing quickly and you end up getting a lot of noise related to throttling.
This PR adds basic support for specifying and customizing qps and burst, and will be applied the setting to both checkpoint writer and vpcClient.
=> Add support for customizing qps and burst for recommender via --kubeapi-qps and --kube-api-burst

vertical-pod-autoscaler/pkg/utils/vpa/api.go
Line 179: checkpotint->checkpoint
=> Correct the returned message

cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-containerservice.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-master.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss.yaml
=> update resource version

vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
=> Fix setting last GC time

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.2
=> Cluster Autoscaler 1.3.2

vertical-pod-autoscaler/README.md
Add info on possible use with HPA on custom metrics.
Fix some nits.
=> Updates to VPA readme

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
Add a method for inserting real node group to test cloud provider.
=> Add a method for inserting custom test node group to test cloud provider

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/logic/updater_test.go, vertical-pod-autoscaler/pkg/utils/test/test_utils.go
The newEventRecorder function is based on CA code.
/assign @bskiba , please have a look.
=> Create an Event when Pod is evicted by VPA Updater

cluster-autoscaler/FAQ.md, vertical-pod-autoscaler/README.md
maybe I'm too boring this weekend :)
=> fix 3 spell

vertical-pod-autoscaler/pkg/recommender/main.go
Should not import one package twice.
=> Use the same package name in main.go

cluster-autoscaler/cloudprovider/azure/azure_util.go
=> Warning instead Warningf

cluster-autoscaler/README.md
Update Cluster Autoscaler releases recommendation with 1.12.
=> Update Cluster Autoscaler releases recommendation

cluster-autoscaler/utils/errors/errors.go
Cherry pick of #1076. Another thing that would've prevented #1270.
=> Cherry pick of #1076: Fix potential panic

cluster-autoscaler/FAQ.md
This PR adds an entry in FAQ.md with all current commandline parameters, description and default value
Fixes #918
=> Adds a FAQ entry with all commandline parameters

OWNERS
=> Create OWNERS on 1.2 branch

cluster-autoscaler/cloudprovider/aws/auto_scaling.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/node_group_discovery_options.go, cluster-autoscaler/cloudprovider/node_group_discovery_options_test.go
Fixes #1280
I've pushed a built docker container here under the v1.2-1280fix tag: https://hub.docker.com/r/cablespaghetti/cluster-autoscaler/tags/
@ReillyProcentive can you verify that this fixes your problem?
=> AWS: Support selecting ASG by values - 1.2 Branch

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/main.go
This includes SatefulSets, Replicasets and ReplicationContollers.
=> Updater uses informers to fetch pod controllers.

cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/deletetaint/delete_test.go
Node objects are frequently updated, and the taint/untaint code doesn't handle conflicts at all, simply returning an error. This causes the rest of the scaling code to abort the downscaling and wait for 15 minutes, only to most likely fail again on the next try. We've observed it multiple times in clusters that needed to be downscaled by 10-20 nodes, and in some situations had to intervene manually because CA couldn't do anything for hours.
Fix by simply retrying the taint/untaint operation until it either succeeds or the number of retries exceeds 50.
=> deletetaint: retry on conflicts

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/updater/main.go
=> VPA recommender/updater main loop fixed.

vertical-pod-autoscaler/e2e/actuation.go, vertical-pod-autoscaler/e2e/admission_controller.go, vertical-pod-autoscaler/e2e/common.go, vertical-pod-autoscaler/e2e/full_vpa.go, vertical-pod-autoscaler/e2e/recommender.go, vertical-pod-autoscaler/e2e/updater.go
=> Open up common utility functions for VPA e2e tests

vertical-pod-autoscaler/hack/deploy-for-e2e.sh, vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
Also adds one change to script that was missed in #1327
=> Switch admission controller to v1beta1

hack/update-gofmt.sh
[WIP]Adding update-gofmt script as part of go format tools
=> Adding  update_gofmt.sh

cluster-autoscaler/FAQ.md
This kubernetes feature has since been released. I also added node group setup suggestions based on my experiences with AWS ASGs but i believe it applies to other cloud providers as well.
=> Update volume topological scheduling FAQ

vertical-pod-autoscaler/pkg/updater/main.go
The error argument was omitted.
=> Fix Fatalf format string

cluster-autoscaler/README.md
add alibaba cloud provider doc link in readme.
=> add alibaba cloud doc link

cluster-autoscaler/cloudprovider/gce/cache.go
Signed-off-by: mooncake <xcoder@tenxcloud.com>
Fix typos: alredy -> already
=> Fix typos: alredy -> already

cluster-autoscaler/cloudprovider/gke/gke_manager.go
Export and include in interface only methods used in gke_cloud_provider.go. Add comments to exported methods.
=> Clean up GkeManager interface

vertical-pod-autoscaler/builder/Dockerfile, vertical-pod-autoscaler/builder/README.md, vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
=> Build VPA releases in docker

vertical-pod-autoscaler/e2e/actuation.go, vertical-pod-autoscaler/e2e/common.go, vertical-pod-autoscaler/e2e/updater.go
Extract some common functionality
=> Add test checking Initial and Off are handled correctly

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
Fix typos: checkponits -> checkpoints
=> Fix typos: checkponits -> checkpoints

cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go, cluster-autoscaler/utils/tpu/tpu_test.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go
Fix typos: reqest->request, approporiate->appropriate
=> Fix typos: reqest->request, approporiate->appropriate

vertical-pod-autoscaler/README.md
Wasn't clear by initially reading the readme.
I'd also like to add specifics on the time intervals (configurable or not? etc), please let me know how that works.
=> Clarify down-scale capabilities

cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-containerservice.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-master.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss.yaml
This is required for kubernetes v1.12.x.
=> Add replicasets in the apps apigroup

cluster-autoscaler/FAQ.md
Link AWS kops setup instructions from #1410
=> Update overprovisioning setup

cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
Line 128: unmarshaling -> unmarshalling
=> Fix klog.Warningf error message in gen.go

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go
Backport https://github.com/kubernetes/autoscaler/pull/1378 to 1.12.x
=> 1.12: Backport AWS: Improved balancing

vertical-pod-autoscaler/hack/convert-alpha-objects.sh
Based on bskiba:to-beta-docs so @bskiba , please have a look.
=> Add a tool to convert alpha VPA objects to beta API

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Maybe this could help with https://github.com/kubernetes/autoscaler/issues/1500
=> Azure: Generate meaningful failure-domain.beta.kubernetes.io/zone

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> Cherry-pick of #1499 to 1.12: Add cache for resource IDs of vmss instances

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> Cherry-pick of #1499 to 1.13: Add cache for resource IDs of vmss instances

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> Cherry-pick of #1499 to 1.2: Add cache for resource IDs of vmss instances

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> Cherry-pick of #1499 to 1.3: Add cache for resource IDs of vmss instances

cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go
Fix a small typo in [alicloud_auto_scaling.go](https://github.com/kubernetes/autoscaler/compare/master...JoeWrightss:patch-6?expand=1#diff-a325b69429b1a9ce1fcd7afa381803ed) at line 168.
=> Fix klog.Errorf() error message

cluster-autoscaler/core/utils.go
Signed-off-by: Zhenhai Gao <gaozh1988@live.com>
=> update log output detailed warning info

cluster-autoscaler/core/scale_down.go
=> refactor(*): fix golint warning

vertical-pod-autoscaler/e2e/common.go, vertical-pod-autoscaler/e2e/full_vpa.go, vertical-pod-autoscaler/e2e/recommender.go
Introduced to facilitate waiting for VPA object changes.
=> Expose WaitForRecommendationPresent method and extract WaitForVPAMatch.

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gke/gke_manager.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/clusterstate/clusterstate.go
fix some golint warning.
- add some export function/type comment
- replace some increment with ++
- omit some will be inferred type name
=> refactor(*): fix some golint warning

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/nodes.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
I'll migrate scale-up in follow up PR
=> Use listers in scale-down

vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go
=> OOM observer implements ResourceEventHandler

cluster-autoscaler/cloudprovider/baiducloud/README.md
**What this PR does / why we need it:**
Add some contact details for Baiducloud.
=> Add some contact details for Baiducloud cluster-autoscaler

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.12.2
=> Cluster Autoscaler 1.12.2

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/main.go
=> VPA: Use downward API to set namespace for webhook service reference

cluster-autoscaler/FAQ.md
/assign MaciekPytel
/assign aleksandra-malinowska
=> Update default priority cutoff value in FAQ.md

cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/deletetaint/delete_test.go
Depends on https://github.com/kubernetes/autoscaler/pull/1598
/assign @aleksandra-malinowska
Please review only last commit but do not merge as it depend on other PR
/hold
=> Refactor tests of tainting

vertical-pod-autoscaler/FAQ.md
Added how to set prometheus as the history provider to the FAQ. 
@bskiba
=> add prometheus as history provider to FAQ

cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/deletetaint/delete_test.go
=> Cherrypick of #1293: deletetaint retry on conflicts 1.3

cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/deletetaint/delete_test.go
=> Cherry-pick of #1293: deletetaint: retry on conflicts

cluster-autoscaler/core/static_autoscaler.go
=> Cherry-pick of #1474: Fix logged error in static autoscaler

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.6.
=> Cluster Autoscaler 1.3.6

vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go, vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go, vertical-pod-autoscaler/pkg/recommender/input/spec/spec_client_test_util.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go, vertical-pod-autoscaler/pkg/updater/logic/updater_test.go, vertical-pod-autoscaler/pkg/utils/test/test_pod.go
* SelfLink was unused
* Build Schemas as needed
* Repoint imports to k8s.io/api
=> Remove vertical-pod-autoscaler dependencies on k/k

cluster-autoscaler/FAQ.md
scheduling.k8s.io/v1beta -> scheduling.k8s.io/v1beta1
=> Correct apiVersion in dynamic provisionning 1.11

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml, cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
=> Cherry-pick of #1288: Read AWS Region from EC2 Metadata

vertical-pod-autoscaler/deploy/vpa-rbac.yaml
=> VPA - Introduce scale reader role

vertical-pod-autoscaler/deploy/vpa-beta2-crd.yaml, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/register.go
=> VPA beta2 CRD - version that supports v1beta1 too.

cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go, cluster-autoscaler/cloudprovider/gce/reserved.go, cluster-autoscaler/cloudprovider/gce/reserved_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go, cluster-autoscaler/estimator/binpacking_estimator_test.go, cluster-autoscaler/estimator/estimator_test.go, cluster-autoscaler/expander/price/preferred.go, cluster-autoscaler/expander/price/price.go, cluster-autoscaler/expander/price/price_test.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/units/units.go
Cherry-pick of #1643
with dependency on #1550
/cc aleksandra-malinowska
/cc MaciekPytel
/cc losipiuk
/hold
=> Cherry-pick of #1643: Capacity prediction based on physical memory

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/pkg/target/fetcher.go
(partial contribution from kgolab)
=> VPA - Implement obtaining selector from well known controllers

cluster-autoscaler/version.go
/cc aleksandra-malinowska
/cc MaciekPytel
/cc losipiuk
=> Cluster Autoscaler 1.3.7

addon-resizer/README.md
Updated readme.md to reflect latest parameters from addon-resizer 2.1. Also added references to the images pushed into the registry.
=> Fix readme to reflect addon-resizer version 2.1.

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
Added migTargetSizeCache in GceCache to cache TargetSize calls for
each GKEMig for each loop of the CA. The cache is invalidated during
refresh that occurs during the start of each loop and during
CreateNodeGroup and DeleteNodeGroup.
=> Added target size cache to gceCache for GKEMig

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go
Cluster Autoscaler 1.12 : cherry pick of #1738: add GetInstanceID() for cloudprovider interface
=> Cluster Autoscaler 1.12 : cherry pick of #1738

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go
Cluster Autoscaler 1.3 : cherry pick of #1738: add GetInstanceID() for cloudprovider interface
=> Cluster Autoscaler 1.3 : cherry pick of #1738

cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go
Cluster Autoscaler 1.13 : cherry pick of #1738: add GetInstanceID() for cloudprovider interface
=> Cluster Autoscaler 1.13 : cherry pick of #1738

cluster-autoscaler/core/static_autoscaler.go
We need to call refresh before getNodeInfosForGroups. If we have
stale state getNodeInfosForGroups may fail and we will end up in infinite crash looping.
=> Call CloudProvider.Refresh before getNodeInfosForGroups

addon-resizer/nanny/main/pod_nanny.go
=> don't log before parsing flags in nanny

vertical-pod-autoscaler/hack/run-e2e-tests.sh
=> Disable running beta1 e2e tests

cluster-autoscaler/Godeps/Godeps.json
=> Fix Godeps.json

cluster-autoscaler/Dockerfile
Change-Id: I08d18627dd2a033f34cc6376d7c740299dac9dcb
=> Use debian-base-amd64:v1.0.0

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/fix_gopath.sh
* Cleaning up the `fix_gopath.sh` with shellcheck
* Cleaning up `cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml` with yamllint
=> Cleaning up the fix_gopath.sh

cluster-autoscaler/cloudprovider/aws/aws_manager.go
For #1803 
Increase RefreshInterval to reduce API calls.  Don't see any downside and 1 min update is acceptable.
=> Update aws RefreshInterval to 1 minute

vertical-pod-autoscaler/README.md
=> Add a note for 0.5.0 release.

cluster-autoscaler/cloudprovider/aws/README.md
Resolve #1798 
User runs cluster autoscaler in on premise cluster and cluster autoscaler uses AWS cloud provider to scale up/down.
Rather than using IAM policy for autoscaler to get access to AWS services, they should use AWS credentials in Env to get AWS SDK authenticated and authorized.
=> Add steps to use AWS Credentials for on premise case

cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-containerservice.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-master.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml
=> YAML linting Azure examples

cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-one-asg.yaml
Yaml linting baiducloud examples
=> Yaml linting baiducloud examples

cluster-autoscaler/fix_gopath.sh
Bug fix reported in https://github.com/kubernetes/autoscaler/issues/1862
=> Bug fix - #1837

cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment-master.yaml, cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment.yaml, cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-secret.yaml, cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-svcaccount.yaml
=> Yaml linting magnum examples

vertical-pod-autoscaler/examples/hamster-deprecated.yaml, vertical-pod-autoscaler/examples/hamster.yaml, vertical-pod-autoscaler/examples/redis-deprecated.yaml, vertical-pod-autoscaler/examples/redis.yaml
Linting vertical-pod-autoscaler examples
=> Linting vertical-pod-autoscaler examples

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
/assign @aleksandra-malinowska
=> Add logging for errors on adding samples.

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/deploy/vpa-beta-crd.yaml, vertical-pod-autoscaler/deploy/vpa-beta2-crd.yaml, vertical-pod-autoscaler/deploy/vpa-crd.yaml, vertical-pod-autoscaler/deploy/vpa-rbac.yaml
Yaml linting vertical-pod-autoscaler deploy files
=> Yaml linting vertical-pod-autoscaler deploy files

cluster-autoscaler/Makefile
=> Enable race detection in CA test-in-docker make target

builder/Dockerfile
Change-Id: Ibfb0aeeb6e70ca0aba44b192f67470aec31cef04
=> Update go to 1.12.1

cluster-autoscaler/Makefile, hack/for-go-proj.sh
/cc maciekpytel
/cc losipiuk
/cc mwielgus
=> Enable race detection in unit tests (CA 1.12)

cluster-autoscaler/Makefile, hack/for-go-proj.sh
/cc maciekpytel
/cc losipiuk
/cc mwielgus
=> Enable race detection in unit tests (CA 1.3)

cluster-autoscaler/Makefile, hack/for-go-proj.sh
/cc maciekpytel
/cc losipiuk
/cc mwielgus
=> Enable race detection in unit tests (CA 1.13)

hack/for-go-proj.sh
/cc MaciekPytel
/cc losipiuk
/cc aleksandra-malinowska
/cc mwielgus
/cc bskiba
=> Enable race detection in Travis tests

cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_provider.go
Change the available GPU types in Alibaba Cloud.
=> change the available GPU types in alibaba cloud

cluster-autoscaler/cloudprovider/azure/README.md
VMSS names and resource group aren't clear from the docs so try ad improve
=> Add notes about aks vmss to azure readme.

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go, vertical-pod-autoscaler/pkg/target/fetcher.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
ControllerFetcher and its tests written by @schylek.
=> Validate that targetRef if set is a top level controller

vertical-pod-autoscaler/pkg/recommender/model/vpa.go, vertical-pod-autoscaler/pkg/recommender/model/vpa_test.go, vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go
=> [cherry-pick] VPA - addmonitoring of VPA object with unsupported config condition.

cluster-autoscaler/cloudprovider/aws/aws_manager.go
=> Cherry-pick of #1841: Update aws RefreshInterval to 1 minute

cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Cluster autoscaler 1.12: cherry pick of #1777: Fix AKS scaling issues for bulk deletion
=> Cluster autoscaler 1.12: cherry pick of #1777

cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Cluster autoscaler 1.3: cherry pick of #1777: Fix AKS scaling issues for bulk deletion
=> Cluster autoscaler 1.3: cherry pick of #1777

cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Cluster autoscaler 1.13: cherry pick of #1777: Fix AKS scaling issues for bulk deletion
=> Cluster autoscaler 1.13: cherry pick of #1777

cluster-autoscaler/OWNERS
Help address and resolve cluster autoscaler issues for a while and understand major logics pretty well now. I hope to apply reviewer and help look at more PRs as I can.
=> Add Jiaxin Shan(Jeffwan@) as reviewer

cluster-autoscaler/FAQ.md
Clarification to text raised off the back of discussion in SIG Autoscaling Slack: https://kubernetes.slack.com/archives/C09R1LV8S/p1555945612041900
=> CA FAQs - Clarify error situations support

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
=> Break getPatchesForPodResourceRequest into smaller functions

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer_test.go
"k8s.io/api/core/v1" is imported twice
=> Code Cleanup

vertical-pod-autoscaler/pkg/recommender/model/cluster.go
=> delete vpaID from all maps in Cluster State

vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider_test.go
- Name test cases,
- Drop duplicated test case,
- Format code more in line with other tests.
=> Clean up VPA recommendation provider unit tests

vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/updater/main.go
=> Initialize klog.

vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider_test.go
@kgolab pointed out that when container has limit and no request it's treated as if it had request equal to limit.
=> When limit is set but request is not treat them as matching

cluster-autoscaler/cloudprovider/aws/MixedInstancePolicy.md, cluster-autoscaler/cloudprovider/aws/README.md
Ref https://github.com/kubernetes/autoscaler/pull/1886
=> Added documentation about AWS ASG MixedInstancesPolicy

cluster-autoscaler/simulator/predicates.go
=> Optimize PredicateChecker for dedicated workloads

cluster-autoscaler/cloudprovider/aws/MixedInstancePolicy.md, cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
Hello! I would like this feature to be included in the 1.14 release.
This is a cherrypick of the two PR. Code and documentation from @drewhemm 
https://github.com/kubernetes/autoscaler/pull/1886
https://github.com/kubernetes/autoscaler/pull/1983
@drewhemm I am taking the liberty to propose your change. If you prefer to do it your self, please let me know and I will close this PR. Thanks!
=> [cherry-pick] Add ASG MixedInstancesPolicy Support

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go, cluster-autoscaler/main.go
=> add --ignore-taint flag and ignore taints added by TaintNodesByCondition

cluster-autoscaler/cloudprovider/magnum/OWNERS
cc: @tghartland 
cc: @MaciekPytel 
cc: @mwielgus
=> Add tghartland as an approver for magnum cloud provider

cluster-autoscaler/cloudprovider/alicloud/OWNERS
cc: @ringtail 
cc: @MaciekPytel
=> Add ringtail as approver for alicloud cloud provider

cluster-autoscaler/cloudprovider/aws/OWNERS
=> Add Jeffwan as approver for aws cloud provider

cluster-autoscaler/cloudprovider/baiducloud/OWNERS
cc: @hello2mao 
cc: @MaciekPytel 
cc: @mwielgus
=> Add hello2mao as an approver for baidu cloud provider

vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go, vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/model/container.go, vertical-pod-autoscaler/pkg/recommender/model/vpa.go, vertical-pod-autoscaler/pkg/recommender/model/vpa_test.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/utils/metrics/quality/quality.go, vertical-pod-autoscaler/pkg/utils/test/test_recommendation.go
For missing recommendations (diff = Inf) we add a separate counter.
=> [cherry pick] Monitor relative diffs between usage and recommendation.

cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> [cherry pick] Look up Azure instance types case-insensitively 1.13

cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> [cherry pick] Look up Azure instance types case-insensitively 1.14

cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> [cherry pick] Look up Azure instance types case-insensitively 1.12

cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
=> [cherry pick] Look up Azure instance types case-insensitively 1.3

cluster-autoscaler/cloudprovider/azure/README.md
Builds on #2052 to further improve the Azure README documentation:
- Note that the ACS service is deprecated
- Remove mention of the unsupported AKS/VMAS CA option
- Make each `vmType` option section more self-contained
- Tell user to copy the manifests rather than edit the `examples/` directory in-place
- Add a few helpful hyperlinks
- Add some emphasis to **NOTE** and **WARNING** with blockquotes
- Minor grammar cleanup
- Put most markdown hyperlink references at the bottom
=> docs: more improvements to CA on Azure README

addon-resizer/Dockerfile
=> Rebase addon-resizer to distroless

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go
Delete zero values from deletionsInProgress map in NodeDeletionTracker.
=> Delete zero values from deletionsInProgress map in NodeDeletionTracker.

cluster-autoscaler/utils/kubernetes/listers.go
Use `cache.NewNamespaceKeyedIndexerAndReflector` to create stores and reflectors.
The `Resync` does nothing without informers, so I set resyncPeriod 0.
https://github.com/kubernetes/autoscaler/blob/5c743c1ffefbfba36326cf2e4bfd67c4443e41a1/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/thread_safe_store.go#L300-L303
=> Create stores and reflectors with a simpler way

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/utils/node_instances_cache.go, cluster-autoscaler/clusterstate/utils/node_instances_cache_test.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go
Cache cloud provider node instances in cluster state.
=> Cache cloud provider node instances in cluster state.

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.12.6
=> Update Cluster Autoscaler version to 1.12.6

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.13.5
=> Cluster Autoscaler 1.13.5

cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.14.2
=> Cluster Autoscaler 1.14.2

cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/simulator/nodes.go, cluster-autoscaler/simulator/nodes_test.go
Optimize building node infos by using map with pods for nodes.
=> Optimize building node infos by using map with pods for nodes.

vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go, vertical-pod-autoscaler/e2e/v1beta2/updater.go
Min from limit range applies to both limit and request, adjust e2e tests
to work with that.
=> Fix e2e testing min from limit range

cluster-autoscaler/FAQ.md
cluster-proportional-autoscaler run command had the . missing
=> update cluster-proportional-autoscaler running command

cluster-autoscaler/hack/update-vendor.sh
A script for automatic vendor directory update in world when
k8s.io/kubernets uses go modules.
=> Add update-vendor.sh

vertical-pod-autoscaler/OWNERS
So that I can not only LGTM but also approve VPA PRs that I review.
=> Add @jbartosik to kubernetes/autoscaler OWNERS

cluster-autoscaler/core/static_autoscaler.go
Fix logging error avoid panic
nodeGroup may be nil
=> Fix logging error

cluster-autoscaler/utils/kubernetes/factory.go
CA Scalability improvement by throttling number of events
fired in the case where there are a lot of unschedulable
pods.
=> Adding config for event filtering

cluster-autoscaler/cloudprovider/alicloud/alicloud_manager.go
=> change fmt.Errorf to klog.Errorf

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go, cluster-autoscaler/core/scale_up.go
#2151: Fix Azure client requests stuck issues on http.StatusTooManyRequests
#2152: Allow scaling multiple Azure vmss synchronously 
=> CA 1.15: cherry pick of  #2151 and #2152

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go, cluster-autoscaler/core/scale_up.go
#2151: Fix Azure client requests stuck issues on http.StatusTooManyRequests
#2152: Allow scaling multiple Azure vmss synchronously 
=> CA 1.12: cherry pick of  #2151 and #2152

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go, cluster-autoscaler/core/scale_up.go
#2151: Fix Azure client requests stuck issues on http.StatusTooManyRequests
#2152: Allow scaling multiple Azure vmss synchronously 
=> CA 1.13: cherry pick of  #2151 and #2152

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go, cluster-autoscaler/core/scale_up.go
#2151: Fix Azure client requests stuck issues on http.StatusTooManyRequests
#2152: Allow scaling multiple Azure vmss synchronously 
=> CA 1.14: cherry pick of  #2151 and #2152

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Fix race conditions when checking the VMSS size.
=> Fix race conditions when checking the VMSS size

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Address issue https://github.com/kubernetes/autoscaler/issues/2179
=> Update c5,i3en,m5,r5 instance types

cluster-autoscaler/cloudprovider/azure/README.md
Add the usage of config `balance-similar-node-groups` to azure README file.
=> Add multinode config in readme.

vertical-pod-autoscaler/e2e/v1beta1/admission_controller.go, vertical-pod-autoscaler/e2e/v1beta1/common.go, vertical-pod-autoscaler/e2e/v1beta1/updater.go
I forgot to update them when fixing v1beta2 tests
=> Fix v1beta1 VPA limit range e2e tests

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/processors/status/scale_up_status_processor.go
Add info about considered and created nodegroups to
ScaleUpStatusProcessor
=> Provide more info to ScaleUpStatusProcessor

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
This way we don't have to specify all the versions we are interested in.
Versioning is then controlled only at the crd level.
=> Look at all versions of VPA objects. [cherry-pick of #2261]

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/core/static_autoscaler.go
#2235 - Correctly handle lack of capacity of AWS spot ASGs
=> CA 1.13: cherry pick of #2235

cluster-autoscaler/cloudprovider/azure/README.md
Update the docs to explain the scaling boundary in detail.
/sig azure
=> Update the docs to explain the scaling boundary in detail.

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/core/static_autoscaler.go
#2235 - Correctly handle lack of capacity of AWS spot ASGs
=> CA 1.14: cherry pick of #2235

cluster-autoscaler/version/version.go
=> Bump Cluster Autoscaler version to 1.16

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/core/static_autoscaler.go
When an instance is detached from a managed instance group in GCP, the cluster-autoscaler return fast [here](https://github.com/kubernetes/autoscaler/blob/5a5845737328f03b4c1353988aded36fa17cc2ea/cluster-autoscaler/core/static_autoscaler.go#L219) and increase the metric `cluster_autoscaler_errors_total{type:cloudprovidererror}`.
I had some trouble to troubleshoot what caused this issue: I had to patch it to add new logs otherwise it was not possible to understand why the cluster autoscaler was stuck.
Terminating the instance from GCP fixed the issue and unstuck the cluster autoscaler.
As we heavily rely on this component, the current cluster autoscaler behaviour could cause us some issues because it prevents the entire cluster from scaling up/down.
The instance detach use case could …
=> cluster-autoscaler: blocked if an instance is detached from MIG

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml
=> Switch deployment to 0.6.1 version

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Cherry-pick of #2296: AWS: Decrease current size only once
=> CA 1.14 #2296 Cherry-pick 

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Cherry-pick of #2296: AWS: Decrease current size only once
=> CA 1.15 #2296 Cherry-pick

cluster-autoscaler/version/version.go
=> Bump cluster-autoscaler version to 1.16.1

cluster-autoscaler/cloudprovider/baiducloud/baiducloud_auto_scaling_groups.go, cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_config.go, cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider.go, cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider_test.go, cluster-autoscaler/cloudprovider/baiducloud/baiducloud_manager.go, cluster-autoscaler/cloudprovider/baiducloud/baiducloud_manager_test.go
/kind cleanup
add comments and unit test
None
Does this PR introduce a user-facing change?:
None
=> add comments and unit test

addon-resizer/Makefile, addon-resizer/nanny/main/pod_nanny.go
=> Use protobufs for communication with apiserver in addon-resizer 1.8

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
add prometheus scrape annotations for metrics gathering
/assign @jeffwan
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
=> add prom scrap annotations

cluster-autoscaler/main.go
fixes https://github.com/kubernetes/autoscaler/issues/944
=> Switch leader election mechanism to use lease objects

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/ec2.go
Add MixedInstancesPolicy struct to better handle instance type (#2248)
=> CA 1.15 cherry-pick #2248

vertical-pod-autoscaler/common/version.go
=> VPA version 0.6.2

vertical-pod-autoscaler/pkg/admission-controller/Dockerfile, vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Dockerfile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Dockerfile, vertical-pod-autoscaler/pkg/updater/Makefile
=> Rebase VPA to distroless

vertical-pod-autoscaler/common/version.go
=> VPA release 0.6.3

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/ec2.go
Add MixedInstancesPolicy struct to better handle instance type (#2248)
=> CA 1.14 cherry-pick #2248

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
=> aws: examples: Delete trailing whitespace

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
#2401 Add g4dn instance type for AWS
=> Cherry pick #2401 to 1.13

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/static_autoscaler.go
=> Rename GetCreatedNodesWithOutOfResourcesErrors to GetCreatedNodesWithErrors

cluster-autoscaler/cloudprovider/aws/aws_manager.go
#2428 AWS – use session.NewSession instead of session.New to
=> Cherry pick #2428 to 1.13

cluster-autoscaler/cloudprovider/baiducloud/baiducloud_manager.go, cluster-autoscaler/cloudprovider/digitalocean/digitalocean_cloud_provider.go, cluster-autoscaler/cloudprovider/digitalocean/godo/doc.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/doc.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/requests.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/networking/v2/extensions/security/rules/results.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/pagination/pager.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/utils.go
I found some typos while surfing across the code to understand what it does each component.
=> cluster-autoscaler: fix some typos in the code

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
Should not create new config var
=> Fix config assignment issue

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
Should not create new config var.
=> Cherry pick 2494 to 1.14: Fix config assignment issue

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
Should not create new config var.
=> Cherry pick 2494 to 1.16: Fix config assignment issue

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
Should not create new config var.
=> Cherry pick 2494 to 1.13: Fix config assignment issue

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
Should not create new config var.
=> Cherry pick 2494 to 1.15: Fix config assignment issue

cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
This PR follows #2281 
@losipiuk I created the test in `gce_manager_test.go` instead of `gce_cloud_provider_test.go` because there is no coverage of this file because of the mocks.
Would you prefer a dedicated test for this ?
=> cluster-autoscaler/gce: create a test for an instance with unknown mig

vertical-pod-autoscaler/e2e/v1/admission_controller.go, vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
On top of #2496 to avoid merge conflict.
=> Deflake vpa ac e2e

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go, cluster-autoscaler/main.go
Add an `--ignore-taint` flag and ignore taints added by TaintNodesByCondition
=> Cherry pick #1963 to 1.14: add --ignore-taint flag and ignore taints added by TaintNodesByCondition

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils.go, cluster-autoscaler/core/utils_test.go, cluster-autoscaler/main.go
Add an `--ignore-taint` flag and ignore taints added by TaintNodesByCondition
=> Cherry pick #1963 to 1.13: add --ignore-taint flag and ignore taints added by TaintNodesByCondition

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This cherry picks a PR that improves performance of the azure provider for the cluster autoscaler.
=> This commit improves the performance of the azure cloud provider.

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
List instances requests weren't registered.
=> Fix metrics for list and delete instances

vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
=> Remove godeps usage from Makefile

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
Provide examples for new lease election objects rbac, related k8s issue #70778.
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
=> Add lease election object rbac rules

cluster-autoscaler/cloudprovider/baiducloud/README.md, cluster-autoscaler/cloudprovider/baiducloud/baiducloud-sdk-go/cce/cluster.go, cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider.go, cluster-autoscaler/cloudprovider/baiducloud/baiducloud_manager.go, cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-multiple-asgs.yaml
**What type of PR is this?**
```
/kind feature
```
```
support multiple groups and GPU group for baiduCloud
```
**Which issue(s) this PR fixes**:
```
NONE
```
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```
=> support multiple groups and GPU group for baiduCloud

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-autodiscover.yaml
Based on these merged changes https://github.com/kubernetes/autoscaler/commit/88d93a9f16af89ba8a6e91a98e5269d879ee277d#diff-53c78a7c9667d245784c77b58fe5902dR660, I'm trying to improve the docs a little bit
=> Improve docs on azure autodiscover installation

cluster-autoscaler/cloudprovider/azure/OWNERS
Add @nilo19 to cluster autoscaler azure owners list.
=> Add nilo19 to cluster autoscaler azure owners list.

vertical-pod-autoscaler/hack/run-e2e-tests.sh
=> Remove timeout when running VPA e2e

cluster-autoscaler/FAQ.md
The url "https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md " has been changed to "https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md"
=> Update URL in FAQ.md

addon-resizer/README.md, cluster-autoscaler/cloudprovider/alicloud/README.md, cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-containerservice.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-master.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml, cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-svcaccount.yaml, cluster-autoscaler/cloudprovider/packet/examples/cluster-autoscaler-svcaccount.yaml, vertical-pod-autoscaler/MIGRATE.md, vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go, vertical-pod-autoscaler/e2e/v1/common.go, vertical-pod-autoscaler/e2e/v1/full_vpa.go, vertical-pod-autoscaler/e2e/v1beta2/autoscaling_utils.go, vertical-pod-autoscaler/e2e/v1beta2/common.go, vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go, vertical-pod-autoscaler/examples/redis-deprecated.yaml, vertical-pod-autoscaler/examples/redis.yaml
xref https://github.com/kubernetes/autoscaler/issues/2473
=> Switch to GA types for workloads, rbac

cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-containerservice.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-master.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml
=> Update rbac settings.

vertical-pod-autoscaler/e2e/v1/common.go, vertical-pod-autoscaler/e2e/v1beta2/common.go
Should fix issue https://github.com/kubernetes/autoscaler/issues/2626.
=> Fix accessing empty array in e2e tests

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_manager.go
Read subscription ID from instance metadata
=> Cherry pick #2545 to 1.17: Read subscription ID from instance metadata

cluster-autoscaler/core/utils/taint_key_set.go
Ignore node termination taint in scale up.
=> Ignore node termination taint in scale up

cluster-autoscaler/cloudprovider/aws/CA_with_AWS_IAM_OIDC.md
From #2514 
Squashing multiple commits into a single commit.
=> Documentation for OIDC with CA on an EKS cluster

vertical-pod-autoscaler/e2e/v1/admission_controller.go, vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
"Fixing" admission controller test race condition.
ref #2631
=> Deflaking admission controller e2e test

vertical-pod-autoscaler/e2e/v1/common.go, vertical-pod-autoscaler/e2e/v1/updater.go, vertical-pod-autoscaler/e2e/v1beta2/common.go, vertical-pod-autoscaler/e2e/v1beta2/updater.go
- refactoring SetupVPAForTwoHamsters
- adding NewNHamstersDeployment
- changing *vpa_clientset.Clientset to vpa_clientset.Interface
=> VPA - e2e common refactor

cluster-autoscaler/cloudprovider/azure/README.md
=> Fix the typo.

vertical-pod-autoscaler/e2e/v1/admission_controller.go, vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
Fixes the issue when we wait for old replicas number instead the new one.
/fixes #2649
=> VPA e2e test - wait for scaling fix

vertical-pod-autoscaler/e2e/v1/recommender.go, vertical-pod-autoscaler/e2e/v1beta2/recommender.go
Adding e2e test for ContainerScalingMode options:
- ContainerScalingModeAuto
There should recommendations for two containers (one ContainerScalingModeAuto and one not set).
- ContainerScalingModeOff
There should recommendations only for one container (one ContainerScalingModeOff and one not set).
=> VPA - ContainerScalingMode e2e test

addon-resizer/main.go, addon-resizer/nanny/nanny_lib.go, addon-resizer/nanny/nanny_lib_test.go
Fix for #2597 for master
@bskiba
=> Add support for scale up/down delay
