kubernetes/autoscaler

- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/simulator/cluster_test.go
- cluster-autoscaler/simulator/drain_test.go
- cluster-autoscaler/utils/test/test_utils.go
This was one major function in simulator, that wasn't covered. A few remaining uncovered methods have little custom logic and are just functions for fetching stuff from API server - testing them would require a lot of mocking for little real value.
This brings simulator coverage to 79.4%, which I'm willing to call close enough to target of 80% stated in https://github.com/kubernetes/autoscaler/issues/6.
> Added UT for cluster_autoscaler/simulator/cluster/FindNodesToRemove

- cluster-autoscaler/README.md
1. grammar error fix
2. replace GCE link with final page that the original link will redirect to
> fix grammar error and links

- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
Existing hostname may interfere with pod affinity/antiaffinity.
cc: @MaciekPytel @wojtek-t
> Override hostname label when building a template node

- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
To keep labels, nodename and pods more consistent in template nodes.
> Overwrite pod.spec.nodename and node.name in template nodes for scale up

- cluster-autoscaler/version.go
Fixes  drain timeouts when pods are ignoring SIGTERM.
> Bump CA version to 0.5.4

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/expander/waste/waste_test.go
... that can be used in scale-ups in case of no live node example.
Part of #43.
cc: @MaciekPytel @fgrzadkowski
> Add a method to NodeGroup for providing a template NodeInfo

- cluster-autoscaler/Dockerfile
This commit is manually tested by running `TAG=add-ca-certificates REGISTRY=mydockerrepo make release` and running it inside author's k8s cluster
The docker image is available at https://hub.docker.com/r/mumoshu/cluster-autoscaler
Looking into the various tags in the repo, you'll see that the image size is increased by 2MB, which is acceptable IMHO
No errors seem to be occurring while accessing AWS API with the ca-certificates bundled in the image hence I assume it is working as expected:
```
I0509 05:07:58.029029       1 aws_manager.go:187] Regenerating ASG information for kube4-Asg1-5GX1OEW9YLPA-Workers-1WBDQUOBGXA6A
I0509 05:07:58.083395       1 aws_manager.go:187] Regenerating ASG information for kube4-Asg3-1QWZDGNI50QW-Workers-1OD7QVXAHMALV
I0509 05:07:58.125027       1 …
```
> cluster-autoscaler: Add ca-certificates to the docker image

- cluster-autoscaler/simulator/cluster.go
The message has been always `<evaluation type>: node <node name> is not suitable for removal nil`.
It should be `<evaluation type>: node <node name> is not suitable for removal: failed to find place for <pod key>`
> cluster-autoscaler: Fix an incorrect message when CA failed to find a place for a to-be-removed pod

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
- cluster-autoscaler/cloudprovider/node_group_discovery_options.go
- cluster-autoscaler/cloudprovider/node_group_discovery_options_test.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/polling_autoscaler.go
- cluster-autoscaler/core/polling_autoscaler_test.go
- cluster-autoscaler/main.go
A redo of https://github.com/kubernetes/contrib/pull/2549
---
This is an alternative implementation of https://github.com/kubernetes/contrib/pull/1982
Notable differences from the original PR are:
* A new flag named `--node-group-auto-discovery` is introduced for opting in to enable the auto-discovery feature.
* For example, specifying `--cloud-provider aws --node-group-auto-discovery asg:tag=k8s.io/cluster-autoscaler/enabled` instructs CA to auto-discover ASGs tagged with `k8s.io/cluster-autoscaler/enabled` to be used as target node groups
* The new code path introduced by this PR is executed only when `node-group-auto-discovery` is specified. There is relatively less chance to break existing features by introducing this change
Resolves https://github.com/kubernetes/contrib/issues/1956 …
> cluster-autoscaler: Re: AWS Autoscaler autodiscover ASG names and sizes

- cluster-autoscaler/core/autoscaler_test.go
- cluster-autoscaler/utils/kubernetes/listers.go
> Daemonset lister

- cluster-autoscaler/proposals/min_at_zero_gcp.md
> Min at zero - design doc

- cluster-autoscaler/simulator/predicates.go
- cluster-autoscaler/simulator/predicates_test.go
Previously, on predicate checker errors, the failure reasons were improperly printed and predicate name was missing. This PR fixes both issues.
cc: @MaciekPytel
> Fix predicate error messages

- cluster-autoscaler/Makefile
- cluster-autoscaler/builder/Dockerfile
Our current build process is prone for gopath pollution and embeds homedir paths in binaries. With this PR the build will be done in a dedicated Docker container with empty gopath and correct golang binary.  
cc: @MaciekPytel @mumoshu @andrewsykim @fgrzadkowski
> Docker builder for cluster autoscaler

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/metrics/metrics.go
Part 3 of implementation of #59 - "CA operations" metrics, except for 'errors_total'
> Add metrics counting CA operations

- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
> Use TemplateNodeInfo in scale up

- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
By default in 1.6 GCE runs kube-proxy from manifest and fluentd as daemonset. Cloud provider is expected to set only the manifest run pods. DS are added in scale-up.
ref: #43
> Add manifest-run kube-proxy to GCE template node

- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/dynamic_autoscaler.go
- cluster-autoscaler/core/dynamic_autoscaler_test.go
- cluster-autoscaler/core/polling_autoscaler.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/main.go
- cluster-autoscaler/metrics/metrics.go
- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/nodes.go
- cluster-autoscaler/utils/errors/errors.go
Ref: https://github.com/kubernetes/autoscaler/issues/59
> Add typed errors, add errors_total metric

- cluster-autoscaler/main.go
- cluster-autoscaler/metrics/liveness.go
- cluster-autoscaler/metrics/liveness_test.go
Extend HealthCheck to verify that a successful run of autoscaler loop occured within given (configurable by setting --max-failing-time flag) time.
> Add failing health check if autoscaler loop consistently returns error

- cluster-autoscaler/simulator/drain.go
- cluster-autoscaler/simulator/nodes.go
- cluster-autoscaler/utils/drain/drain.go
- cluster-autoscaler/utils/drain/drain_test.go
This addresses #64 on CA side by allowing it to drain nodes with kube-system pods running if these pods match a PodDistrubutionBudget with allowed-disruptions > 0.
> Add allowing eviction of kube-system pods with PDB

- cluster-autoscaler/version.go
cc: @MaciekPytel @aleksandra-malinowska
> Bump cluster autoscaler version to 0.6-alpha1

- cluster-autoscaler/config/kubernetes.go
The problems started after godeps update - we don't use groupversion field anymore.
> Fix NPE in kubernetes config

- cluster-autoscaler/clusterstate/utils/status.go
- cluster-autoscaler/clusterstate/utils/status_test.go
- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
Ref: #106 #108 
This fixes the following issues:
- No longer discards original error when failing to read/write status configmap
- No longer panics if a configmap already exists, but has no annotations on it
- Write status configmap in namespace specified by --namespace flag
> Status configmap fixes

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/update_toc.py
As the CA FAQ is growing it was getting hard to navigate. This
will make FAQ table of contents reflect different sections to make
it easier to navigate.
> Divide CA's FAQ TOC to sections

- cluster-autoscaler/cloudprovider/aws/README.md
https://github.com/kubernetes/contrib/pull/1552#r75532949 seems to explain the reasoning behind multiple ASGs much better then the previous link target.
> AWS: Fixed link to the detailed explanation

- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/dynamic_autoscaler.go
- cluster-autoscaler/core/dynamic_autoscaler_test.go
- cluster-autoscaler/core/polling_autoscaler.go
- cluster-autoscaler/core/polling_autoscaler_test.go
- cluster-autoscaler/core/static_autoscaler.go
By fixing CA not to reset states of `StaticAutoscaler` and `ScaleDown` before each iteration.
Resolves #85 
This is how I'm going to test it:
- `kubectl scale deployment php-apache --replicas 1` and wait for the default scale-down-delay - 10 minutes
* It turned out that e2e for CA doesn't work on AWS, probably due to e2e's inability to determine original cluster size which is required in order to reset the cluster size after each test. [Revelant log can be seen in my gist](https://gist.github.com/mumoshu/f73d2bbf45f82d732cc577524e7ca2f7)
cc @MaciekPytel
> cluster-autoscaler: Fix scale-down when the node group auto-discovery feature is enabled

- cluster-autoscaler/metrics/metrics.go
- cluster-autoscaler/proposals/metrics.md
Many functions take an order of magnitude more time
if they actually decide to take an action (like deleting
node in scale-down) and it's ok if executing action is
slow. That makes summary less useful, as we expect to
have large outliers on some percentile, depending on
churn in cluster. Instead having a histogram gives
us the fuller picture of how the distribution of
function runtimes look like.
> Change function duration metric to histogram

- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
This is a temporary taint added by rescheduler, we shouldn't assume it will be present on all nodes in node group.
> Strip rescheduler taint from node templates

- vertical-pod-autoscaler/recommender/model/aggregations_config.go
- vertical-pod-autoscaler/recommender/model/container.go
- vertical-pod-autoscaler/recommender/model/container_test.go
- vertical-pod-autoscaler/recommender/util/histogram_mock.go
- vertical-pod-autoscaler/recommender/util/slidingwindow.go
Introducing ContainerStats, a type which stores the aggregated usage history for a single container (CPU histogram + a sliding window with daily memory peaks from the last week). The history stored in this object will be populated from usage samples fetched from the real time usage data source with the AddSample() method.
The ContainerStats objects will be the main input for the Recommender to produce a recommendation for a container.
> Add a class to aggregate container usage samples.

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
This addresses #164. Tested manually that CA doesn't touch nodes with this annotation. Removing it or setting a different value allows CA to resume scaling down the node.
PR with FAQ update coming.
> Add respecting scale down disabled annotation

- cluster-autoscaler/core/static_autoscaler.go
Excluding API call from "findUnneeded" duration metric (intended to measure CA performance.)
> Change scope of findUnneeded metric

- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
- cluster-autoscaler/core/utils.go
This addresses #168.
Tested manually in the following steps:
1. Deploy new image of CA
2. Create an empty node group with NODE_TAINTS set in kube-env
3. Taint any other nodes in the cluster
4. Create pod with tolerations matching taints of empty node group, but not those of other nodes
5. Verify CA increased this node group
> add taints to GCE node template

- cluster-autoscaler/cloudprovider/aws/README.md
The code used to scale node groups from 0 requires the `DescribeLaunchConfigurations` permission.
> Update readme with permissions for scaling node groups from 0

- cluster-autoscaler/core/scale_down.go
Node name wasn't logged due to typo
> fix some logs in scale down

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
- vertical-pod-autoscaler/updater/main.go
Corrected 'kuberentes' -> 'Kubernetes' in some log messages and CLI help message.
> Fixed typoes of name 'Kubernetes'

- cluster-autoscaler/FAQ.md
I see some entry end up with ".", but some others don't. So I fix it.
> fix: add . to end of entry in FAQ.md

- hack/scripts/break_mig.py
I needed to simulate some scale up failures for testing #185. Since I've already done it multiple times manually I decided to write a script for automatically breaking new nodes as they come up. I think it may be useful for other people testing CA, so upstreaming it.
> Utility script for testing CA cloudprovider failure handling

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
Previously only one node could be deleted at a time.
> Fix getEmptyNodes function in CA

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/deploy/deploy.sh
I don't see any docs as to a release process, but ideally this process should be added to such a thing if it exists.
> bump container image version to 0.6.0

- cluster-autoscaler/utils/kubernetes/listers.go
After the update listers don't automatically start in separate goroutines.
> Fix listers in CA after godep update

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
In azure cloudprovider some log lines use fmt and others use glog.
I think this should be consistent.
> Use glog to replace fmt in azure cloudprovider

- builder/Dockerfile
Needed by updated godeps - followup of #232.
> Add libseccomp-dev to dockerbuilder

- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
Kubemark cloud provider dependencies require some constants that are only available on linux, forcing to compile CA using docker even for development. As docker compilation on macos is much much longer and cpu-intensive this PR splits kubemark implementation to 2 files - one with the real implementation that is used on linux and one with fake/mock that is used everywhere else.
> Split kubemark cloud provider implementation to linux and non-linux

- cluster-autoscaler/core/static_autoscaler.go
#261 puts "on hold" unremovable nodes.
> Dont block scale downs if no nodes can be removed

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
* Increases maxGracefulTerminationTime to 10 min.
* Allows scale ups and unneeded node calculations while the node deletion is in progress.
fixes: #147
> Run node drain/delete in a separate goroutine

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
Currently we track if those nodes can be removed and only
skip them at the execution step. Since checking if node is
unneeded is pretty expensive it's better to filter them out
early.
> Skip nodes in min-sized groups in scale-down simulation

- cluster-autoscaler/cloudprovider/gce/gce_manager.go
Basename was set on miginfo copy, not on the original.
> Fix basename population in gce manager

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
Fixes #278 
I have built and tested this on one of our clusters. 
If no autoscaling group matches both tags, the autoscaler exits and is restarted by kubernetes.
As soon as one ASG matches both tags, CA will stay up and run as designed. If this group is then removed (by changing the tags as described in the issue), then CA will also exit and get into a restart loop as above.
I considered returning an empty list of ASGs, but I believe this isn't the correct approach. If you return an empty list of ASGs then CA will continue through it's working process and only when it gets to the point where it wants to scale up or scale down will it fail. I feel users would prefer to know CA can't do anything earlier than this.
I also considered the fact that maybe CA should just emit a message and keep …
> Check ASG name list not empty

- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/simulator/predicates.go
> Disable MatchInterPodAffinity if there are no pods using affinity

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/expander/price/price.go
- cluster-autoscaler/expander/waste/waste_test.go
We should not invoke any remote calls for exist. Node groups are not expected to go away. This function is to check whether the group has been created or not, not to do a health-check ping.
Following the pattern as we have in func autoprovisioned().
> Do not return error from exist

- cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
Fixes issues hit while trying to test the autoscaler outside of a GCE cluster.
On the node template check, we warn, but I'm wondering whether we should fail harder. If the template can't be loaded is that a permanent blocker to autoscaling, or does it just make estimation less efficient?
> Allow testing against GCE without running on GCE

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/config/dynamic/config_fetcher.go
- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/estimator/binpacking_estimator.go
- cluster-autoscaler/estimator/estimator.go
- cluster-autoscaler/main.go
- cluster-autoscaler/proposals/node_autoprovisioning.md
- cluster-autoscaler/simulator/nodes.go
- cluster-autoscaler/utils/deletetaint/delete.go
- cluster-autoscaler/utils/drain/drain.go
- cluster-autoscaler/utils/kubernetes/factory.go
- cluster-autoscaler/utils/kubernetes/listers.go
1. Change from deprecated Core to CoreV1 for kube client
2. Fix typo GetAvilableMachineTypes() => GetAvailableMachineTypes() 
3. Fix small typos 
4. Small optimize code
> Small optimize code and fix typos

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
Function AwsRefFromProviderId call many times. If scale down enable this call default every 10 seconds per each node.
regexp.MustCompile it very heavy function and not need call each time
> Move regexp.MustCompile in AWS provider to global variable

- cluster-autoscaler/FAQ.md
Some web pages (like https://cloud.google.com/container-engine/docs/cluster-autoscaler) link directly to FAQ and the compatibility/used-version information is not visible to the users.
> Version information also in FAQ

- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/main.go
When looking for non empty candidates for scale down limit the size of the pool from which additional candidates (not found in previous iteration) are taken.
Intended to increase performance of CA scale down.
Issue https://github.com/kubernetes/autoscaler/issues/247
> Only consider up to 10% of the nodes as additional candidates for scale down

- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/main.go
- cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go
CPU and memory limits for the entire cluster are configurable by setting --cores-total and --memory-total flags. For now, only the upper limit is respected, during scale up. PR with scale down respecting lower limit coming soon.
> Limit total cluster resources during scale up

- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
This results in the simulator being unable to place candidate pods because the taint blocks all scheduling.  The taint could be on the node because it's transitioning to unready and no other nodes are available to extract a template from.
> Do not include ToBeDeleted taint when constructing a template

- cluster-autoscaler/core/scale_down.go
Addresses #313 by checking for error. 
This has been tested manually by deleting a pod after an eviction was scheduled, but before it was attempted (using modified version of CA which introduced sufficient delay.)
> Add checking for pod not found error on eviction

- cluster-autoscaler/config/const.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
- cluster-autoscaler/main.go
Follow up to #295, adding support for lower limits of total cluster cores/memory.
> Respect minimum cores/memory limit during scale down

- cluster-autoscaler/core/static_autoscaler.go
This fix moves the calculateUnneededOnly check after expensive unneeded calculations, to avoid a scenario where the scale down goroutine is still running when the next main loop starts. This could cause a scale down to be skipped because scale down was still in progress at the beginning of the main loop, but is no longer after calculating unneeded.
The new log message is also intentional; to make it clear when the next main loop iteration starts, even when another goroutine may still be writing log messages.
> Move calculateUnneededOnly check after unneeded calculations

- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/main.go
Added scale-down-delay-after-delete to control delay after deleting a node.
Renamed scale-down-trial-interval to scale-down-delay-after-failure and fixed comments to reflect its actual intent per @mwielgus
Renamed scale-down-delay to scale-down-delay-after-add
Updated some logging and comments
> Introduce new flags to control scale down behavior

- cluster-autoscaler/utils/drain/drain.go
After increasing max graceful termination timeout to 10 minutes when evicting pods, we should probably also increase the time we allow other pods to terminate before disregarding them in simulation.
> Keep graceful termination timeout consistent

- cluster-autoscaler/simulator/cluster.go
This logs can sometimes be useful for debugging, but with more than a few hundred pods generate massive amount of spam in logs.
> Move spammy logs to V(5)

- cluster-autoscaler/proposals/kubemark_integration.md
The design proposals were organized according to SIGs in kubernetes/community#1010. This led to a broken link.
> Fix link after design proposal move

- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
Compute allocatable for auto-provisioned mig templates. Reserved is calculated as a ratio of capacity. Allocatable is capacity - reserved.
> Compute allocatable for auto-provisioned migs

- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/clusterstate/clusterstate_test.go
- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/utils/test/test_utils.go
Fix: #369 
Previously a node that failed to register and couldn't be deleted basically broke CA. Now we will keep track of it in clusterstate and continue operating mostly normally.
> Keep track of nodes that failed to register for a long time

- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
When updating mig config (min/max nodes) we were not refreshing mig cache, meaning some methods would still return old version of a given mig. This lead to inconsistent state, where different parts of CA code used different min/max size constraints for the same mig.
Also updated the code to only build test node template when the mig config has changed in anyway, not every time we poll GKE API.
Finally updated unittests to work with this changes, decoupling some unittests from fetchAllNodePools() call they were using for test setup and not as a part of actual test.
> Refresh mig cache if node pool config has changed

- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
- cluster-autoscaler/core/scale_up.go
Fixed some issues related to NAP on GKE: 
* Make autoprovisioned node pools names shorter (previously it
was exceeding max name length).
* Set autoscaling fields when creating node pool.
* Handle NodeGroup id changing when NG is created.
Fixes in this PR are enough for CA to create and delete autoprovisioned nodepool, though there are some smaller issues remaining (new node group is reported as unhealthy when it's created, errors in logs, missing events). I'll fix those issues in follow-up PR.
> NAP bugfixes

- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/core/scale_up.go
This stops CA from considering newly created node group as unhealthy and prevents error messages showing in log when NAP is enabled. Also previously status configmap would only inform about scale-up after next loop has completed (10+s delay), now it does it immediately.
> Update clusterstate after scale-up

- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
When scaling up from 0, read information about GPUs from instance template. This allows us to support scaling up a relevant NodeGroup from 0 when we have a pending pod that needs GPUs.
> Support GPUs in scale from 0

- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
The v1.resourceNvidiaGPU resource name will soon no longer be valid. The correct resource name to use is "nvidia.com/gpu"
> Fix GPU resource name.

- cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-api.json
- cluster-autoscaler/vendor/google.golang.org/api/container/v1alpha1/container-gen.go
Use v1alpha1 API if autoprovisioning is enabled. This is a temporary solution until NAP fields are available in normal client.
This is likely my ugliest PR in kubernetes to date :(
> Use GKE alpha client when autoprovisioning is enabled

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/core/static_autoscaler.go
This can be used to dynamically update cloud provider
config (in particular list of managed NodeGroups and their
min/max constraints).
Add GKE implementation.
> Add Refresh method to cloud provider

- cluster-autoscaler/utils/drain/drain.go
- cluster-autoscaler/utils/drain/drain_test.go
If a pod is not replicated, the auto-scaler doesn't drain the node it is in. This PR enables to do it if the pods have an annotation.
> If correct annotation on pod, drain node even if not replicated

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/core/polling_autoscaler.go
- cluster-autoscaler/core/polling_autoscaler_test.go
Fix for issue 252 where excessive API calls to AWS are the result of leaking go routines from the Polling auto scaler.
> AWS DescribeAutoScalingGroups requests too aggressive - API limits reached

- cluster-autoscaler/cloudprovider/gce/gce_price_model.go
- cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go
- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/utils/gpu/gpu.go
- cluster-autoscaler/utils/gpu/gpu_test.go
Fix for https://github.com/kubernetes/kubernetes/issues/54959.
The idea is to internally override status of nodes which should have GPUs to unready until they actually have allocatable GPU. That way our normal logic for handling long starting up nodes kicks in and counts those nodes in simulations.
The downside is we have to use the same timeout for GPU node start-up + driver installation as for normal nodes (defaults to 15 minutes, which may not be enough - we may need to temporarily increase this for 1.8).
Also fixes the issue where GCP pricing model was using old GPU resource name and not taking GPU into account when calculating node cost (leading to very sad scale-up decisions in my test...).
> Consider GPU nodes unready until allocatable GPU is > 0

- cluster-autoscaler/FAQ.md
Simple observation about the new annotation from commit 56135db3b01c379b6fbb65e9d23d75e1a5c90130. 
@MaciekPytel Would it be better to have a separate question? Or is this enough?
> Observation about safe-to-evict annotation on FAQ

- cluster-autoscaler/core/autoscaling_context.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
- cluster-autoscaler/main.go
Fixes #466 by removing one of the flags. Left --max-node-provision-time as the name is more precise.
> Remove --unregistered-node-removal-time flag

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
C5 instances: https://www.ec2instances.info/?filter=c5
Added new instances types to aws provider, otherwise we have exception everytime:
```
I1122 07:03:30.997937       1 scale_up.go:54] Pod bi/presto.worker-59788c9f65-565tx is unschedulable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x145189d]
goroutine 76 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).buildNodeFromTemplate(0xc420b1c040, 0xc421bcc000, 0xc421e0c900, 0xc421e0c900, 0x0, 0x0)
/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:252 +0x48d
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*Asg).TemplateNodeInfo(0xc421bcc000, 0xc421dd3b00, 0xc421a2f380, 0x20) …
```
> Added aws c5 instance types.

- cluster-autoscaler/cloudprovider/azure/README.md
The official image name sould be used instead of a pernal one.
> Fix image name for azure

- addon-resizer/README.md
- addon-resizer/nanny/apis/nannyconfig/v1alpha1/defaults.go
- addon-resizer/nanny/main/pod_nanny.go
This introduces following logic:
- By default, the hardcoded values will be used.
- If flags are specified, they will overwrite defaults in code.
- If config map is specified, any parameters present there will overwrite both flags and defaults from the code.
This covers following scenario:
- Customer wants to overwrite resources requirements for some addon with config map.
- In next kubernetes version, addon resources are adjusted.
- The customer upgrades his cluster. If he has overwritten resource requirements, the values he specified still apply. If he hasn't, addon resource requirements are updated correctly.
> Re-introduce flags that are used to configure Addon Resizer resources if not specified by config map

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Regenerated `ec2_instance_types.go` by running `make generate`. This adds support for the new AWS h1 and m5 instance types as in https://github.com/kubernetes/autoscaler/pull/483.
> Add h1 and m5 AWS instance types

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gpu.go
- cluster-autoscaler/cloudprovider/gce/gpu_test.go
- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/expander/price/price_test.go
- cluster-autoscaler/utils/gpu/gpu.go
- cluster-autoscaler/utils/gpu/gpu_test.go
The user experience will be as follows:
- If there is a pending pod with GPU request NAP will create a node pool with nvidia P80 for it
- If the pod uses nodeSelector on `cloud.google.com/gke-accelerator` label NAP will use the value of node selector to determine GPU type (you can get nvidia P100 by setting nodeSelector `cloud.google.com/gke-accelerator: nvidia-tesla-p100`).
- New node pools with gpu will come with taint `gke-accelerator: <gpu_type>` with no schedule effect (to mitigate the risk of pods not requiring GPU landing on expensive node with GPU, there is no way user can do it themselves in NAP)
- We validate if a node pool with GPU can be created against criteria specified in https://cloud.google.com/compute/docs/gpus/ (zone with GPU enabled, maximum CPU/GPU ratio, number of …
> Add support for GPU for NAP

- hack/verify-gofmt.sh
We should support go1.9 when verifying gofmt.
> Support go1.9 when verifying gofmt

- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-master.yaml
I created an acs-engine k8s cluster and tried to deploy 
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml
but got:
```
Warning  FailedScheduling  1s (x6 over 16s)  default-scheduler  No nodes are available that match all of the predicates: MatchNodeSelector (2), PodToleratesNodeTaints (1).
```
With this small fix pod got scheduled.
> Add operator and value to pod tolerations in azure example yaml

- cluster-autoscaler/push_image.sh
For images not hosted on gcr.io, we should use `docker push` instead of `gcloud docker -- push`.
> Use docker push for non-gcr images

- vertical-pod-autoscaler/updater/updater.go
bugfix after recent godep update
- without it, updater would just hang on running reflector.
> running updater podLister in a separate go routine

- vertical-pod-autoscaler/api/types.go
As agreed in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md (almost - notable change - VPAStatusCondion, just like in HPA).
cc: @tkulczynski @kgrygiel
> VPA api definition

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
Trim spaces for user-specified Azure configs.
Fix #533.
> Trim spaces for user-specified configs

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
- cluster-autoscaler/cloudprovider/node_group_discovery_options.go
Continue of #449. This PR adds support of multiple node groups on Azure.
It also improve code organization by wrapping clients, config validation.
> Support multiple node groups on Azure

- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/metrics/metrics.go
This PR somehow improves monitoring (metrics, events and configmap status) in the following cases:
- nodes unregistered for a long time,
- cluster is empty,
- cluster not healthy enough to autoscale.
This is intended as a temporary solution. We should probably process empty cluster in ClusterStateRegistry to cover following cases:
- accurately report unregistered nodes when there are no ready nodes,
- attempt to remove unregistered nodes while cluster is unhealthy,
- (feature) scale from 0 nodes in the cluster.
> Better reporting of cluster state

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
Continue of #449. Reduce API calls and avoid touching Azure rate limits.
> Reduce API calls and avoid touching Azure rate limits

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-master.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss.yaml
acs-engine [v0.12.0](https://github.com/Azure/acs-engine/releases/tag/v0.12.0) adds a breaking change of etcd TLS. It introduces two extra etcd private keys: EtcdClientPrivateKey and EtcdServerPrivateKey.
This PR adds the configuration for them and updates the deploy documentation.
> Add support for configuring etcd private keys

- cluster-autoscaler/cloudprovider/aws/README.md
- Clarify that the only the tag key is used for auto-discovery
- Remove some obsolete information on how to obtain the code with this
feature.
> CA AWS: Clarify that auto-discovery configuration

- addon-resizer/nanny/main/pod_nanny.go
Cpu and memory arguments from command line are not read at all, leaving them empty. ```nannyConfigurationFromFlags``` sets default values to argument values. In ```loadNannyConfiguration``` it attempts to read from config, but if config is not set it just creates an empty ```configMapConfig```. Since this is empty calling ```nannyconfigalpha.FillInDefaults_NannyConfiguration``` doesn't actually do anything as it compares the values against default values, so when all values are empty this does nothing. In the end function just returns empty values for everything and never uses command line arguments.
Starting container in acs-engine leads to these errors now:
```
ERROR: logging before flag.Parse: I0118 13:57:09.157760       1 pod_nanny.go:64] Invoked by [/pod_nanny --cpu=80m …
```
> Bug fix for auto-resizer 1.8.1 not reading command arguments

- vertical-pod-autoscaler/recommender/Dockerfile
- vertical-pod-autoscaler/recommender/main.go
- vertical-pod-autoscaler/recommender/recommender.go
- vertical-pod-autoscaler/recommender/signals/history_provider.go
- vertical-pod-autoscaler/recommender/signals/history_provider_test.go
- vertical-pod-autoscaler/recommender/signals/prometheus_client.go
This also refactors out history provider from recommender.go (as you originally requested) and fixes issues with the recommender flags, client queries etc. I now tested it e2e in my cluster and it pushes some samples and labels to clusterState.
> Get CPU, memory and labels history from Prometheus

- vertical-pod-autoscaler/recommender/recommender.go
State Unknown is may happen due to transient error (https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase), so it shouldn't be deleted from the Cluster State.
> Select all pods, so pods in state Unknown are not deleted from the Cluster State.

- vertical-pod-autoscaler/recommender/cluster/metrics_client.go
- vertical-pod-autoscaler/recommender/cluster/metrics_client_test_util.go
- vertical-pod-autoscaler/recommender/cluster/spec_client.go
- vertical-pod-autoscaler/recommender/cluster/spec_client_test_util.go
- vertical-pod-autoscaler/recommender/logic/recommender_test.go
- vertical-pod-autoscaler/recommender/model/container.go
- vertical-pod-autoscaler/recommender/model/container_test.go
- vertical-pod-autoscaler/recommender/model/types.go
- vertical-pod-autoscaler/recommender/recommender.go
- vertical-pod-autoscaler/recommender/signals/history_provider.go
- vertical-pod-autoscaler/recommender/signals/history_provider_test.go
* Change float64 to ResourceAmount in cotainer samples
* Rename MetricName to ResourceName to better reflect what it is and improve consistence with core API
* Move struct that are not used for storage from model package to where they are used (cluster package)
> Cleanup model atoms

- vertical-pod-autoscaler/recommender/input/history/history_provider.go
- vertical-pod-autoscaler/recommender/input/history/history_provider_test.go
- vertical-pod-autoscaler/recommender/input/history/prometheus_client.go
- vertical-pod-autoscaler/recommender/input/history/prometheus_client_test.go
- vertical-pod-autoscaler/recommender/input/history/prometheus_util.go
- vertical-pod-autoscaler/recommender/input/history/prometheus_util_test.go
- vertical-pod-autoscaler/recommender/input/history/types.go
- vertical-pod-autoscaler/recommender/input/metrics/metrics_client.go
- vertical-pod-autoscaler/recommender/input/metrics/metrics_client_test.go
- vertical-pod-autoscaler/recommender/input/metrics/metrics_client_test_util.go
- vertical-pod-autoscaler/recommender/input/spec/spec_client.go
- vertical-pod-autoscaler/recommender/input/spec/spec_client_test.go
- vertical-pod-autoscaler/recommender/input/spec/spec_client_test_util.go
- vertical-pod-autoscaler/recommender/main.go
- vertical-pod-autoscaler/recommender/recommender.go
Proposal of a simple refactoring.
I'm not 100% sure about repeating package name in Interface name like: `spec.SpecClient`, however having two different `Client` interfaces imported in a single file also seemed a little confusing.
Let me know if it seems good to you or if you suggest a different approach.
CC: @kgrygiel @mwielgus
> metrics and specs clients package refactoring

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-master.yaml
Addresses #383 by creating both a ClusterRole (for cluster administration tasks) and a Role (for updating the `kube-system` namespace ConfigMap.)
> update docs with RBAC info

- addon-resizer/Dockerfile
As Dockerfile `MAINTAINER` instruction has been deprecated, we should use `LABEL maintainer=xxx` to replace original `MAINTAINER`. 
/cc @bskiba @mwielgus
> replace deprecated maintainer instruction with label

- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
Getting this permission error on deployment
```
Listing and watching *v1.StorageClass from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:86
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list storageclasses.storage.k8s.io at the cluster scope
```
> storageclasses permission is required

- cluster-autoscaler/cloudprovider/azure/README.md
useInstanceMetadata should be set to false. Or else, node's providerID will be in `azure://uuid` format and autoscaler won't be able to recognize it. 
In the future kubernetes releases, node's providerID will be updated to correct version (https://github.com/kubernetes/kubernetes/pull/59539).
> Document useInstanceMetadata settings for Azure standard vmType

- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss-master.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-vmss.yaml
Without this, cluster-autoscaler would report errors:
```
Listing and watching *v1.StorageClass from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:86
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list storageclasses.storage.k8s.io at the cluster scope
```
> storageclass permission is required

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
These are two somewhat separate changes, so let me know if I should split this PR:
1) Rename gpu resource name, the same as #407 but for AWS
2) Set scaleToZero = true. It looks like this was changed (by accident?) in #462
I've tested the changes manually and scaling to and from 0 works on my cluster with the nvidia k8s device plugin.
> AWS: Fix nvidia gpu resource name, re-enable ScaleToZero

- builder/Dockerfile
Add installing libseccomp-devel to builder.
> Add installing libseccomp-devel to builder

- cluster-autoscaler/cloudbuild.yaml
Enables building of the cluster-autoscaler container using Google
Container Builder.  This is part of a larger effort to automate and
establish provenance for Kubernetes add-on images.
> Add GCB config for cluster-autoscaler

- vertical-pod-autoscaler/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/recommender/recommender.go
Comming back with the idea of "ClusterStateFeeder", now in a different form. 
The goal of this refactoring is to:
1. encapsulate logic which loads data into clusterState
2. limit the number of Recommender dependencies
@kgrygiel for a while, I was playing around with the idea of making feeder stateless, but then Recommender would stay with a number of dependencies, which would be only passed as parameters to external functions.
@kgrygiel @mwielgus - please review!
(Please merge https://github.com/kubernetes/autoscaler/pull/596 before review, as this PR depends on it)
> Refactoring: loading ClusterState

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard.yaml
This PR makes deployment parameters robust for various acs-engine versions by
-  reading deployment parameters from acs-engine generated `azuredeploy.parameters.json` file
- simplifier deployment secrets
/kind bug
Fixes #644 and #642
> Make deployment parameters robust for various acs-engine versions

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
This PR improves azure node's providerID handling by:
- Avoid converting cases for azure node's providerID 
- Use GET API to fetch node's ID for vmss virtual machines. This is because the virtual machines ID format in LIST is not consistent with GET results. We use GET here because azure cloud provider also uses GET API.
> Improve azure node's providerID handling

- vertical-pod-autoscaler/recommender/logic/estimator.go
- vertical-pod-autoscaler/recommender/logic/estimator_test.go
- vertical-pod-autoscaler/recommender/logic/recommender.go
- vertical-pod-autoscaler/recommender/model/cluster_test.go
- vertical-pod-autoscaler/recommender/model/container.go
- vertical-pod-autoscaler/recommender/model/container_test.go
- vertical-pod-autoscaler/recommender/model/types.go
- vertical-pod-autoscaler/recommender/recommender.go
The confidence grows with the amount of aggregated utilization history.
The recommender multiplies MaxRecommendation by the factor of (1+1/confidence) and divides MinRecommendation by the same factor. This means that the [Min..Max] range is very wide when there is small amount of available history (either the VPA recommender has just started and didn't have access to the historical data or all pods matched by the VPA are new). The [Min..Max] range gets more narrow as the history accumulates.
As the effect, the Updater will be less likely to evict a pod when the confidence of the recommendation is low.
> Introduce recommendation confidence.

- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/expander/price/price.go
- cluster-autoscaler/utils/gpu/gpu.go
- cluster-autoscaler/utils/gpu/gpu_test.go
Use constant, very high unfitness for nodes with GPU to make them very unattractive for any pod that doesn't require GPU and to avoid situation where CA values CPU usage efficiency over GPU price optimization.
Also additionally delay scale-up if there are very new pods requesting GPU. We lose a bit of latency for pods requesting GPU, but we can pack them more densely that way.
> Better GPU handling in price expander

- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
- cluster-autoscaler/expander/price/price.go
- cluster-autoscaler/utils/gpu/gpu.go
- cluster-autoscaler/utils/gpu/gpu_test.go
Cherry-pick https://github.com/kubernetes/autoscaler/pull/688 on CA 1.1 branch. Additionally includes https://github.com/kubernetes/autoscaler/pull/508 as the additional wait in #688 depends on it.
> Cherrypick gpu expander fix on CA 1.1 branch

- vertical-pod-autoscaler/admission-controller/logic/recommendation_provider.go
- vertical-pod-autoscaler/pkg/utils/test/test_utils.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
- vertical-pod-autoscaler/updater/priority/update_priority_calculator.go
- vertical-pod-autoscaler/updater/priority/update_priority_calculator_test.go
- vertical-pod-autoscaler/updater/updater.go
1. Update priority is calculated based on the ratio between the total request and total recommended target for all containers, as opposed to sum of ratio for each container (previous policy favored many small containers).
2. Pods with a container that needs to grow get higher priority.
3. Pods with any request outside the [MinRecommended...MaxRecommended] range can be updated regardless of the relative diff between request and target.
4. Pods with all requests within the [MinRecommended...MaxRecommended] range can be updated if they live for at least 12h and the relative diff exceeds the threshold.
> Extend the Updater policy with new rules

- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
Fixes typo of Kubernetes in comment
> fix misspelling of Kubernetes

- cluster-autoscaler/FAQ.md
The semantics of -v flag changed - it is currently used to controll log
output for glog. The -v flag for kubetest has been replaced by
--verbose-commands.
See https://github.com/kubernetes/test-infra/pull/7073
> Fix command for e2e tests after changes in test infra

- cluster-autoscaler/clusterstate/utils/status.go
"record" should be replaced with "records" in line 48 and line 55.
> Typo fix "record"->"records"

- cluster-autoscaler/config/kubernetes.go
line 31: a spell err  "structur" should be "structure"
> Typo fix in kubernetes.go

- vertical-pod-autoscaler/recommender/input/cluster_feeder.go
We can enable deleting terminated pods once we start collecting
aggregated history of usage in another object, otherwise history
of usage is lost once the pod is removed.
> Do not delete terminated pods from the model.

- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
This is the second part of the fix in https://github.com/kubernetes/kubernetes/pull/61119
This provides a temporary way for the cluster autoscaler to get at
values that were removed from kube-env in https://github.com/kubernetes/kubernetes/pull/60020.
Ideally this information will eventually be available via e.g. the Cluster API,
because kube-env is an internal interface that carries no stability
guarantees.
/cc @roberthbailey @bskiba @mwielgus
> Extend cluster autoscaler to check AUTOSCALER_ENV_VARS in kube-env

- cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/features/kube_features.go
Disable VolumeScheduling predicate (which breaks scale-up) until there's a workaround.
> Disable VolumeScheduling predicate

- vertical-pod-autoscaler/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/recommender/logic/estimator_test.go
- vertical-pod-autoscaler/recommender/logic/recommender.go
- vertical-pod-autoscaler/recommender/model/aggregate_container_state_test.go
- vertical-pod-autoscaler/recommender/model/cluster.go
- vertical-pod-autoscaler/recommender/model/cluster_test.go
- vertical-pod-autoscaler/recommender/model/container.go
- vertical-pod-autoscaler/recommender/model/container_test.go
Tune the recommender to converge faster for workloads that need a lot of CPU.
(1) Use CPU request as the weight in the CPU histogram, so that low usage caused by CPU starvation is forgotten faster.
(2) Increase the CPU safety margin.
> Improve reaction time for CPU starved workloads

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Automatically cherry-pick #757: Ensure azure reference non-empty
Fix #756
> Ensure azure reference non-empty

- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
Use the yaml-parsing library to parse KUBE_ENV in gce instance templates to deal with possible multi line values.
Fixes #745
> Fix parsing kube-env

- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Disabling the test as it's causing presubmits to fail on unrelated PRs (for example, #780.)  Progress on fixing it tracked in #516.
> Disable flaky AWS test

- cluster-autoscaler/utils/kubernetes/ready.go
> correct the returned message in ready.go

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/node_group_discovery_options.go
- cluster-autoscaler/cloudprovider/node_group_discovery_options_test.go
So far aws asg discovery only works by matching on tag keys, not values.
But I have a tag "KubernetesCluster" with a value to identify the cluster, so this isn't working for me.
This PR (should) adds support for filtering the ASG by key *and* value, e.g:
```
--node-group-auto-discovery=asg:tag=KubernetesCluster=my-cluster
```
Not working since something appears to modify the flag value before reaching the cloudprovider stuff. Will pick this up next week but though some early feedback would be useful.
> AWS: Support selecting ASG by values

- cluster-autoscaler/FAQ.md
In the main text of this doc, mostly Kubernetes is capitalized, while line 430 not.
It's better to be same.
> Typo fix in FAQ.md

- addon-resizer/README.md
Since addon-resizer does not have the tag `1.8`, this patch updates README to use `1.8.1`.
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/addon-resizer?gcrImageListsize=50
> Fix absent image tag version in README

- cluster-autoscaler/core/scale_down.go
If there were just one unremovable node, 'were' would be grating:
`scale_down.go:175] Scale-down calculation: ignoring 1 nodes, that were unremovable in the last 5m0s`
> Rephrase unremovable node warning

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/fix_gopath.sh
* Fix the fix_gopath name in FAQ.
* Fix the fix_gopath.sh to create the v1alpha1 directory for cases where the k8s did not have v1alpha dependency.
> FAQ and fix_gopath.sh fixes

- vertical-pod-autoscaler/README.md
- vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
- vertical-pod-autoscaler/deploy/recommender-deployment.yaml
- vertical-pod-autoscaler/deploy/updater-deployment.yaml
- vertical-pod-autoscaler/examples/hamster.yaml
- vertical-pod-autoscaler/recommender/logic/recommender.go
Change the hamster deployment to use 0.5 CPU / pod, so that the example
can be used on a small cluster. Update README.
Make safety margin flag controllable.
Change the default of safety-margin-min-cpu from 300 to 200 millicores.
Change the CPU request of VPA components to 50 millicores.
> Updates to VPA example deployment & README + adjust resources

- vertical-pod-autoscaler/README.md
In this doc, "pod" and "Pod" are mixed. For the proper noun like "Vertical Pod Autoscaler", it's in capital. That's OK.
But in other situations, it's mixed in capital and lowercase. It's better to use same format.
> "pod" and "Pod" are mixed except that in proper noun

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
This PR adds zero nodes support for Azure VMSS.
Fixes #796.
Note that: Azure VMAS (vmType: standard) doesn't support this feature.
> Add zero nodes support for Azure VMSS

- cluster-autoscaler/FAQ.md
> Typo fix in FAQ.md : kubernets->kubernetes

- vertical-pod-autoscaler/recommender/logic/estimator_test.go
- vertical-pod-autoscaler/recommender/logic/recommender.go
- vertical-pod-autoscaler/recommender/model/aggregate_container_state.go
- vertical-pod-autoscaler/recommender/model/aggregate_container_state_test.go
- vertical-pod-autoscaler/recommender/model/cluster.go
- vertical-pod-autoscaler/recommender/model/cluster_test.go
- vertical-pod-autoscaler/recommender/model/container.go
- vertical-pod-autoscaler/recommender/model/container_test.go
- vertical-pod-autoscaler/recommender/model/types.go
- vertical-pod-autoscaler/recommender/model/vpa.go
- vertical-pod-autoscaler/recommender/output/checkpoint_writer.go
- vertical-pod-autoscaler/recommender/output/checkpoint_writer_test.go
* Usage samples are no longer aggregated per pod (which prevented from garbage collecting terminated pods and could lead to very large number of aggregations, when many pods with different names were created in the cluster).
* We introduce a new concept of the AggregateStateKey, which determines the set of containers
for which usage samples are aggregated. In the current implementation the AggregateStateKey
consists of { namespace, containerName, label set }, however it can be easily changed/extended in future, if necessary.
* Each container holds a pointer to the AggregateContainerState to which it contributes usage samples.
* Each VPA holds a set of all AggregateContainerStates which it matches.
* Pod no longer keeps links to the VPAs that match it. VPA no longer keeps links to Pods it …
> Switch from per-pod aggregations to per-labelset aggregations.

- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/dynamic_autoscaler.go
- cluster-autoscaler/core/dynamic_autoscaler_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/main.go
The CleanUp method is instead called directly from the implementation,
when required.
Test updated in a quick way since the mock we're using does not support
AtLeast(1) - thus Times(2).
> Remove implementation details (CleanUp) from the interface.

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/utils/deletetaint/delete.go
Add support for rescheduled pods with the same name in drain.
> Add support for rescheduled pods with the same name in drain

- cluster-autoscaler/core/static_autoscaler.go
Both are used simply to prevent scale-down and, moreover, I'd like to abstract "scale-down forbidden" logic even more in the future refactoring(s).
> Merge two variables into one.

- cluster-autoscaler/core/static_autoscaler.go
The ScaleDownError check was ureachable
> Set lastScaleDownFailTime properly

- cluster-autoscaler/cloudprovider/azure/README.md
Fix couple of typos and clarify the documentation about the NodeResourceGroup. 
Better documentation from the feedback in: https://github.com/kubernetes/autoscaler/issues/884
> Minor typos and NodeResourceGroup clarification

- cluster-autoscaler/cloudprovider/azure/README.md
The deployment parameter is not used in aks manifests.
cc @kkmsft
> Remove deployment parameter from AKS docs

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups_test.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Instead of doing auto-discovery, nodes per ASG and target size per ASG separately, fetch all
of those ASG details in a single request on each `Refresh()` with maximum 10 seconds granularity.
This reduced the amount of DescribeAutoScalingGroups API calls for our setup (3 ASGs / one per AZ) from ~55 calls / min to ~5 calls / min.
As the DescribeAutoScalingGroups supports up to 1600 members per call, this approach should be fairly scalable https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeAutoScalingGroups.html and work for more complicated setups.
I'm still testing this PR with our clusters, but I can't see any major downsides in requesting an up-to-date status only every 10s vs. on-demand as the main loop isn't executed more frequently and its unlikely that ASG API is …
> AWS: Reduce amount of API calls significantly 

- cluster-autoscaler/proposals/scalability_tests.md
Line 14: 
"it's reaction time is short"->"its reaction time is short"
> Typo fix: "it's reaction time is short"->"its reaction time is short"

- cluster-autoscaler/context/autoscaling_context.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
AutoscalingContext is basically a configuration and few static helpers and API handles.
ClusterStateRegistry is a state and thus moved closer to other state-keeping objects.
> Move ClusterStateRegistry to StaticAutoscaler

- cluster-autoscaler/utils/drain/drain.go
- cluster-autoscaler/utils/drain/drain_test.go
Terminal pods (Succeeded or Failed phase) are drained by kubectl drain,
and autoscaler should also drain them.
I hit this while testing a cluster that created lots of
1. directly created pods with restartPolicy=Never
2. using a custom controller that creates restartPolicy=Never pods as "jobs"
In both cases, the autoscaler left those nodes up, even though all the pods on the node were terminated, with the "is not replicated" error. The autoscaler should not consider terminal pods as blockers for drain.
> Autoscaler doesn't drain nodes that have terminal pods

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
Updating the AWS auto-discovery documentation to make the actual behavior
Modify the tag names to be naming convention consistent with other areas of the documentation
Updated examples to use a newer version of the autoscaler
> Update auto-discovery docs to match actual behavior

- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/processors/processors.go
- cluster-autoscaler/processors/status/eventing_scale_up_processor.go
- cluster-autoscaler/processors/status/eventing_scale_up_processor_test.go
- cluster-autoscaler/processors/status/scale_up_status_processor.go
After a scale up, process the state. This is currently implemented as and eventing processor, that emits appropriate events for pods in different states. The processor is wrapped in a chaning processor for easy extensibility.
> Add post scale up status processor.

- cluster-autoscaler/cloudprovider/gce/gpu.go
Updated the settings according to https://cloud.google.com/compute/docs/gpus/#gpus-list, with a simplification about CPU range for 4-P100 machines.
Reordered existing list to match ordering from the web page, just to make the comparison of code & web page easier.
> Update GPU lists & settings according to June 2018 GCE/GKE offering

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.0-beta.0
> Cluster Autoscaler 1.3.0-beta.0

- builder/Dockerfile
Update Go version to 1.10.2 (required by k8s.io/kubelet)
> Update Go version to 1.10.2

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
#790 
I've experienced the same problem "autoscaler failing with Wrong id: expected format aws:///<zone>/<name>"  described in #790. This small patched resolved it, as it turned out that some node might not have providerId sometimes, returning an error in this case will result GetNodeInfosForGroups returning an empty map, even if other nodes have correct providerId.
> #790 - aws - autoscaler failing with Wrong id

- vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go
- vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer_test.go
- vertical-pod-autoscaler/pkg/recommender/initialization/recommender.go
- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
1. Fill the VerticalPodAutoscalerCheckpointStatus.Version field.
2. Do not load checkpoint with incompatible version.
>  Add checkpoint versioning

- vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go
- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
This was added by mistake. The checkpoint versioning was implemented in
a layer below (in the aggregate_container_state).
This reverts commit 1a120bb803feb71d62237bf2c00447cfc257a26a.
> Revert "Add checkpoint versioning."

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.1-alpha
> Update Cluster Autoscaler version to 1.3.1-alpha

- vertical-pod-autoscaler/pkg/recommender/logic/estimator_test.go
- vertical-pod-autoscaler/pkg/recommender/model/aggregations_config.go
- vertical-pod-autoscaler/pkg/recommender/util/histogram_options.go
- vertical-pod-autoscaler/pkg/recommender/util/histogram_options_test.go
Currently the bucket boundaries are calculated as: FirstBucketSize * ExpFactor^n.
For example for FirstBucketSize=100M and ExpFactor=1.05, the bucket boundaries will be:
0:  [0...100M)
1:  [100M...105M)
2:  [105M...110.25M)
etc..
Natural and more reasonable boundaries would instead be such that the second bucket is 5% larger than the first bucket, so:
0:  [0...100M)
1:  [100M...205M)
2:  [205M...315.25M)
etc.
> Improve histogram exponential buckets.

- addon-resizer/nanny/main/pod_nanny.go
The construction of the pollPeriod duration was done in a manner that
did not use the unit of the poll-period flag correctly.
> Fix construction of the pollPeriod duration

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Before attempting to perform a split on the tag value, validate it
matches the format <tag>:NoSchedule
This should prevent invalid tag keys from causing the autoscaler to
panic and crash
Fixes #998
> Validate taint key with regex

- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
Virtual machines not managed by AKS may have no tags. In such case, CA will panic.
Fixes #919 
Note: there's no such issue for 1.3 because its Azure client has been upgraded and `map[string]*string` is used there (instead of `*map[string]*string`).
> Fix potential panic for aks

- README.md
This removes the meeting information from the README, in favor of
pointing at the community repo.  Among other things, pointing at the
community repo makes it easier to update meeting information in one
place, instead of multiple.
> Remove the meeting information from the README

- cluster-autoscaler/main.go
Lower default expendable pod priority cutoff to -10. 
With pod priority and preemption enabled, users may want to create pause pods for overprovisioning with priority lower than default (0 for pods with unspecified priority), but high enough that they still trigger scale-up. 
```release-note:
Default value for expendable pod priority cutoff changed from 0 to -10.
action required: users deploying workloads with priority lower than 0 may want to use priority lower than -10 to avoid triggering scale-up.
```
> Lower default expendable pod priority cutoff to -10

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/metrics/metrics.go
- cluster-autoscaler/proposals/metrics.md
- cluster-autoscaler/utils/gpu/gpu.go
As discussed I've made GetGpuTypeForMetrics more in line with GetNodeTargetGpus - but looking at the amount of plumbing needed I'm no longer fully convinced it's really worth the effort.
Updated metrics.md for a good measure.
> Make GetGpuTypeForMetrics more robust

- addon-resizer/nanny/estimator.go
- addon-resizer/nanny/estimator_test.go
When parsing a resource value such as "0.5m" the unit information was
being extracted as "00u" instead of "u".
> Fix the parsing of resource values

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_up.go
CA current only events after scale-up or before scale-down.
This PR add a event before scale-up and event after scale-down, so that we could track the scaling status from events.
> Add more events for CA

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/utils/drain/drain.go
- cluster-autoscaler/utils/drain/drain_test.go
Allow using the cluster-autoscaler.kubernetes.io/safe-to-evict annotation also to mark the pod as not safe to evict, this fixes issue #510.
> Add annotation to mark pods as unsafe to evict

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.2-alpha.0
> Cluster Autoscaler 1.3.2-alpha.0

- cluster-autoscaler/utils/errors/errors.go
err may be nil some cases, so err.Error() would panic CA.
Fix https://github.com/kubernetes/autoscaler/issues/863#issuecomment-406857408
> Fix potential panic

- cluster-autoscaler/core/scale_up.go
Instead of using unrelated (and always nil) error variable, create a new error from scratch. Fixes potential cases for #1076
> Fix error on node info not found for group

- cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/config/static/autoscaling_options.go
- cluster-autoscaler/context/autoscaling_context.go
- cluster-autoscaler/context/autoscaling_context_test.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/core/utils_test.go
- cluster-autoscaler/main.go
- cluster-autoscaler/main_test.go
- cluster-autoscaler/processors/nodegroups/autoprovisioning_nodegroup_manager_test.go
- cluster-autoscaler/processors/nodegroups/autoprovisioning_processor.go
- cluster-autoscaler/processors/nodegroups/autoprovisioning_processor_test.go
Pass the entire options object to build cloud provider.
Remove no longer necessary builder pattern for cloud provider (it's never re-constructed after initialization.)
> Simplify building cloud provider

- cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
- cluster-autoscaler/context/autoscaling_context.go
- cluster-autoscaler/context/autoscaling_context_test.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
Move creating cloud provider out of context.
Move creating helper structs with dynamic config into cloud provider constructor.
> Move creating cloud provider out of context

- cluster-autoscaler/context/autoscaling_context.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/processors/nodegroups/autoprovisioning_nodegroup_manager_test.go
- cluster-autoscaler/processors/status/eventing_scale_up_processor_test.go
Move all clients used for communicating with Kubernetes API server to a separate struct within context. This doesn't affect current usage as the struct is embedded, the only benefit is cleaner structs and logically divided responsibility. Before, most clients lived in AutoscalingContext, except for ListerRegistry, which was embedded directly in StaticAutoscaler.
Delta except for tests is 32 lines. The rest is reducing test setup verbosity.
> Group all Kubernetes API clients

- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go
When a ContainerAggregatedState of a live container is garbage collected due to lack of samples, is will be recreated once the samples start appearing again. This prevents us from not providing recommendations for containers that are live but didn't get samples for 8 days.
> Use proxy for container state aggregator.

- cluster-autoscaler/context/autoscaling_context.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
Move initializing defaults out of main. Extract building autoscaler from run(). Extract constructing auxiliary kube clients to a separate function.
> Move initializing defaults out of main

- cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
- cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
- cluster-autoscaler/cloudprovider/gce/gce_url.go
Extract GCE calls and hide them behind a new interface. This will allow for easier mocking (and getting rid of jsons from gke_manager_test.go) in the near future.
> Extract autoscaling GCE client

- vertical-pod-autoscaler/deploy/vpa-crd.yaml
The CRD creation doesn't work at the moment. Validation fails for enums and lists. This should fix e2e tests for now. 
Will add validation to admission webhook in a followup pr.
> Remove faulty validation for VPA

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
cherry pick of:
https://github.com/kubernetes/autoscaler/pull/648
> cherry pick: "Fix nvidia gpu resource name on AWS" to 1.1

- vertical-pod-autoscaler/pkg/updater/logic/updater.go
- vertical-pod-autoscaler/pkg/updater/priority/pod_eviction_admission.go
- vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
- vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go
Adds sequentialPodEvictionAdmission for chaining a number of PEAs.
Also fixes a typo, in a separate commit not to pollute the diff of the real change.
@bskiba , please have a look
>  Add a sequential implementation of PodEvictionAdmission

- cluster-autoscaler/cloudprovider/gce/autoscaling_gke_client.go
- cluster-autoscaler/cloudprovider/gce/autoscaling_gke_client_v1.go
- cluster-autoscaler/cloudprovider/gce/autoscaling_gke_client_v1beta1.go
- cluster-autoscaler/cloudprovider/gce/cache.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
This extracts cache management part of GCE manager in order to make it:
1) easier to understand and verify it is used correctly,
2) reusable for separating GKE cloud provider.
> Extract cache from GCE manager

- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gke/gke_manager.go
- cluster-autoscaler/cloudprovider/gke/gke_manager_test.go
Export and include in interface only methods used in gce_cloud_provider.go. Add comments to exported methods.
> Clean up GceManager interface

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.2.3-beta.1
> Cluster Autoscaler 1.2.3-beta.1

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.2 beta.1
> Cluster Autoscaler 1.3.2 beta.1

- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider.go
Currently in getMatchingVPA, it can generate a lot of lines of "Let's choose from x configs" without any context if you set v=1.  This PR sets the logging level to be identical to surrounding logging level, as well as add pod name to the log line for clarity.
> Improve getMatchingVPA logging to be more clear (with pod name) and using logging level

- cluster-autoscaler/Dockerfile
Update Cluster Autoscaler base image to debian-base-amd:0.3.2
> Update Cluster Autoscaler base image

- cluster-autoscaler/Dockerfile
Cherry pick of #1155: Update Cluster Autoscaler base image to debian-base-amd:0.3.2
> Cherry pick of #1155: Update Cluster Autoscaler base image

- cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go
- cluster-autoscaler/cloudprovider/gke/gke_manager.go
Remove discoveryOptions from GKE manager constructor
> Remove discoveryOptions from GKE manager constructor

- vertical-pod-autoscaler/pkg/admission-controller/Dockerfile
- vertical-pod-autoscaler/pkg/recommender/Dockerfile
- vertical-pod-autoscaler/pkg/updater/Dockerfile
Following #1155 to update base image to address CVEs, but only for VPA.
> Update vertical-pod-autoscaler base image to debian-base-amd:0.3.2

- vertical-pod-autoscaler/pkg/admission-controller/config.go
I might be wrong, but it is my understanding that pod Update review has no impact through VPA admission controller.   It would be doing work that will have no effect at the end.
There can be a lot of pod updates events, for example, updating pod annotations, and would be creating a lot of unnecessary work.  I'd like to propose we remove the review of pod Update.
> VPA admission controller should stop review Pod Update event

- cluster-autoscaler/utils/tpu/tpu.go
- cluster-autoscaler/utils/tpu/tpu_test.go
In this way, we don't need to change this code to support
1. Preemptible Cloud TPU (e.g., `cloud-tpus.google.com/preemptible-v2`).
2. New TPU generations (e.g., `cloud-tpus.google.com/v3`).
> Ignore resources with Cloud TPU prefix

- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client.go
Accidentally used GCE timeout for GKE operations.
> Fix GKE operation wait timeout

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.3.2-beta.2
> Cluster Autoscaler 1.3.2-beta.2

- OWNERS
- addon-resizer/OWNERS
- cluster-autoscaler/OWNERS
- vertical-pod-autoscaler/OWNERS
> Update owners files for autoscaling

- builder/Dockerfile
Use Go 1.10.3 as older version causes test-in-docker to fail.
> Use Go 1.10.3

- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1beta1.go
- cluster-autoscaler/cloudprovider/gke/gke_manager.go
Add checking limiter is not nil. Log warnings and errors if it is.
> Fix fetching resource limits on GKE

- cluster-autoscaler/utils/tpu/tpu.go
- cluster-autoscaler/utils/tpu/tpu_test.go
Cherry-pick of #1168: Ignore resources with Cloud TPU prefix
> Cherry-pick of #1168: Ignore resources with Cloud TPU prefix

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
Issue: After ~30 minutes pod eviction event watch channel is closed. We are reading from a closed channel in an infinite loop that burns cpu. Causes recommender to start eating way too much cpu ~30 mins after start.
Fix: Watch for channel closure and restart the watch.
> Handle channel closes from pod event watcher

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.2.3-beta.2
> Cluster Autoscaler 1.2.3-beta.2

- vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
This also allows using math.MaxInt64 as "no upper bound".
> Compare in overflow-safe way

- cluster-autoscaler/clusterstate/clusterstate.go
It returned the number of registered nodes, but should return the number
of provisioned nodes instead.
> Fix GetClusterSize to return actual size in line with the rest of CSR

- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
- cluster-autoscaler/estimator/binpacking_estimator.go
- cluster-autoscaler/processors/status/eventing_scale_up_processor.go
- cluster-autoscaler/processors/status/eventing_scale_up_processor_test.go
- cluster-autoscaler/processors/status/scale_up_status_processor.go
- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/predicates.go
- cluster-autoscaler/simulator/predicates_test.go
- cluster-autoscaler/utils/daemonset/daemonset.go
Report reason why pod didn't trigger scale-up in NotTriggeredScaleUp event. Format is similar to FailedScheduling, i.e. list of "\<failure reason\> (\<number of affected node groups\>)".
This can be further improved by:
- detailing reason why node group was skipped (e.g. max size reached, not healthy),
- communicating why NAP couldn't create a node group,
- passing raw predicate errors plus the above information to scale up status processor, so it can decide the message format.
> Report reason why pod didn't trigger scale-up

- vertical-pod-autoscaler/pkg/recommender/input/history/prometheus_util.go
This PR fixes bad syntax for struct tag value in prometheus_util.go.
> Fix bad syntax for struct tag value in prometheus_util.go

- vertical-pod-autoscaler/pkg/updater/logic/updater.go
- vertical-pod-autoscaler/pkg/updater/priority/pod_eviction_admission.go
- vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go
We need to make sure, that even if there are no VPAs, Eviction Admission will correctly initialize its state.
> Clean up eviction admission no VPAs in the cluster 

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster.go
- vertical-pod-autoscaler/pkg/recommender/model/vpa.go
- vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
- vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
- vertical-pod-autoscaler/pkg/utils/vpa/api.go
- vertical-pod-autoscaler/pkg/utils/vpa/api_test.go
Adds ObservedVpas to cluster state as a baseline for status comparison.
Removes some excessive logging (Each VPA per loop, each Pod per loop).
> Update VPA status only when needed.

- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gke/gke_manager.go
Refresh node locations when refreshing other GKE resources. Add a method for getting it from cloud provider. Use zone from system labels when constructing new node group in GKE cloud provider.
> Add caching node locations in GKE cloud provider

- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client.go
- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1.go
- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1beta1.go
- cluster-autoscaler/cloudprovider/gke/gke_manager.go
- cluster-autoscaler/cloudprovider/gke/gke_manager_test.go
Replace 2 GET cluster and 1 LIST node pools call with a single GET cluster on forceRefresh().
This also changes LIST node pools call to GET cluster call after creating/deleting node pool. I don't think it should have much performance impact - the object is larger, but it counts as a full refresh, so it reduces the total number of calls. @MaciekPytel WDYT?
> Reduce GKE API calls

- hack/verify-spelling.sh
Previously if script was not run from root repository directory it
was failing with following error:
```
can't load package: package k8s.io/github.com/client9/misspell/cmd/misspell: cannot find package "k8s.io/github.com/client9/misspell/cmd/misspell" in any of:
...GPATH ENTRIES...
```
> Allow running hack/verify-spelling.sh from any directory

- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client.go
- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1.go
- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1beta1.go
- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1beta1_test.go
- cluster-autoscaler/cloudprovider/gke/gke_manager_test.go
Temporary workaround for issues with testing setup in GKE.
> Export GKE API endpoint flag

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
- This is intended to address the issue described in https://github.com/kubernetes/autoscaler/issues/923
- the delay is configurable via a CLI option
- in production (on AWS) we set this to a value of 2m
- the delay could possibly be set as low as 30s and still be effective depending on your workload and environment
- the default of 0 for the CLI option results in no change to the CA's behavior from defaults.
> Add configurable delay for pod age before considering for scale-up

- vertical-pod-autoscaler/pkg/admission-controller/main.go
- vertical-pod-autoscaler/pkg/recommender/main.go
- vertical-pod-autoscaler/pkg/updater/main.go
- vertical-pod-autoscaler/pkg/utils/metrics/healthcheck.go
- vertical-pod-autoscaler/pkg/utils/metrics/metrics.go
For updater & recommender we stop returning "healthy" if more than five loops passed without an update (process stuck somewhere).
For admission controller we always return "healthy".
@bskiba please decide whether you want to have this configurable or report "unhealthy" in some other situations.
> Add simple health-check to all VPA components.

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
Fixes https://github.com/kubernetes/autoscaler/issues/1228
While https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeAutoScalingGroups.html reports a `maximum length of 1600`, it seems that only max. 50 names are allowed as input https://github.com/cristim/autospotting/issues/199#issuecomment-355764282
> Fetch ASG names in chunks of 50

- addon-resizer/README.md
Can we add kube-state-metrics which also use addon-resizer to improve its performance:
https://github.com/kubernetes/kube-state-metrics/blob/master/kubernetes/kube-state-metrics-deployment.yaml#L34
> Add kube-state-metrics which uses addon-resizer

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
Tackles kubernetes/autoscaler#1208. EC2 Metadata helpfully supplies AWS
Region info, so rather than _requiring_ an environment variable, this
patch enables `aws_manager.go` to retrieve that information from EC2
itself.
Example YAMLs no longer reference the vestigial `AWS_REGION` environment
variable, but supplying it to `cluster-autoscaler` still relays it to
the AWS SDK like before.
> Read AWS Region from EC2 Metadata

- vertical-pod-autoscaler/pkg/recommender/util/histogram.go
- vertical-pod-autoscaler/pkg/recommender/util/histogram_test.go
The first commit partially fixes a problem with "zero recommendation" appearing in some new clusters.
The next ones are unrelated minor clean-ups.
The rest of the "zero recommendation" fix will be part of another PR.
/assign @bskiba
> Don't move min/max bucket on sub-epsilon samples

- cluster-autoscaler/cloudprovider/azure/azure_util.go
- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
Fix typos issues in below files:
1. cluster-autoscaler/cloudprovider/azure/azure_util.go
2. vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
> Fix typos issues

- cluster-autoscaler/cloudprovider/builder/builder_all.go
From #1319, CA binary size depending on build:
- all (default): 166MB
- AWS: 65MB
- Azure: 56MB
- GCE: 75MB
- Kubemark: 164MB
Removing Kubemark from all (default) build reduces it to ~98 MB. Given that it's only useful specifically for scalability testing, we can probably remove it from default image altogether.
> Remove Kubemark cloud provider from default build

- cluster-autoscaler/FAQ.md
The `--unregistered-node-removal-time` was removed in https://github.com/kubernetes/autoscaler/pull/469 but it is still mentioned in FAQ.
> Update FAQ: remove info on not existent flag --unregistered-node-removal-time

- .travis.yml
- hack/install-verify-tools.sh
- hack/verify-gofmt.sh
- hack/verify-golint.sh
Presubmits are broken because of golint (e.g. seen on #1337)
> Fix Go tools on Cluster Autoscaler 1.2 branch

- cluster-autoscaler/FAQ.md
Simply adds 2 CA flags that are defined but not documented outside of the code currently to the relevant FAQ docs.
Maintained the ordering from `main.go`'s parsing
> Add 2 missing CA flags to param docs

- cluster-autoscaler/FAQ.md
In k8s 1.11, pod priority, and preemption is enabled by default.
The API is under `v1beta`, and they do not need to be enabled.
> Update FAQ on overprovisioning to account for k8s 1.11

- cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_group.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/expander/waste/waste_test.go
This is preparatory work for handling resource related
(stockout/quota-exceeded) error conditions in CA.
> NodeGroup.Nodes() return Instance struct instead instance name

- cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
On local hardware I have not seen this test fail using the current
50ms timeout. On AWS/CI I see this fail occasionally; I built and
copied this test to an AWS node and run it repeatedly for ~1 hour. The
min was 5ms and the max was 268ms, so bumping the timeout to 500ms.
Signed-off-by: Andrew McDermott <amcdermo@redhat.com>
> gce: increase test timeout in TestWaitForOp

- vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go
Can be seen as a continuation of #1335 - now using buffered channel in OnEvent too.
> Pass on-event oomInfo without creating a new goroutine.

- vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go
- vertical-pod-autoscaler/pkg/recommender/model/container.go
- vertical-pod-autoscaler/pkg/recommender/model/container_test.go
Use real-usage sample (exclude previous OOMs) to estimate memory usage after OOM.
This should fix the problem reported by @davidquarles under #1182 - but *not* the initial issue reported by @bskiba there.
Note for a reviewer: I've unexported memoryPeak & oomPeak to decrease chance of invalid usage.
> Use real-usage sample to estimate memory usage after OOM

- hack/verify-all.sh
A missing negation made that scripts output less stuff if we pass -v (i.e. verbose).
> hack/verify-all.sh: missing negation

- hack/verify-all.sh
https://github.com/kubernetes/autoscaler/pull/1365 fixed a missing negation in `hack/verify-all.sh` so we now get proper headers when `-v` is passed, but it forgot to also change whether or not the verifier script output was suppressed or not depending on `-v` -- that setting was correct before https://github.com/kubernetes/autoscaler/pull/1365 and is now wrong (so the PR was sort of a disimprovement). This PR fixes that.
Sorry for the confusion.
> hack/verify-all.sh -v output corrected

- cluster-autoscaler/context/autoscaling_context.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/estimator/basic_estimator.go
- cluster-autoscaler/estimator/basic_estimator_test.go
- cluster-autoscaler/estimator/binpacking_estimator.go
- cluster-autoscaler/estimator/estimator.go
- cluster-autoscaler/main.go
Hide estimators behind interface. Check flag only once, during initialization. Deprecate BasicEstimator.
> Clean up estimators

- cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_group.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/core/scale_up.go
Go 1.11.1 complains about malformatted log messages:
```
cloudprovider/azure/azure_agent_pool.go:213: Verbose.Infof format %s has arg newDeployment of wrong type k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources.Deployment
cloudprovider/azure/azure_client.go:122: Verbose.Infof format %q reads arg #2, but call has 1 arg
cloudprovider/azure/azure_client.go:124: Verbose.Infof format %q reads arg #2, but call has 1 arg
cloudprovider/azure/azure_client.go:145: Verbose.Infof format %q has arg vmInstanceIDs of wrong type k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-04-01/compute.VirtualMachineScaleSetVMInstanceRequiredIDs
cloudprovider/azure/azure_client.go:147: …
```
> Fix formatted log messages

- cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_metrics.go
- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1.go
- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1beta1.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go
- cluster-autoscaler/cloudprovider/gke/gke_metrics.go
Request counter for now (split by resource & verb).
```
cluster_autoscaler_gce_request_count{resource="instance_group_managers",verb="get"} 35
cluster_autoscaler_gce_request_count{resource="instance_group_managers",verb="list_managed_instances"} 18
cluster_autoscaler_gce_request_count{resource="instance_templates",verb="get"} 1
cluster_autoscaler_gce_request_count{resource="machine_types",verb="get"} 1
cluster_autoscaler_gce_request_count{resource="machine_types",verb="list"} 1
cluster_autoscaler_gke_request_count{resource="clusters",verb="get"} 3
```
> Add metrics for GCP API usage

- cluster-autoscaler/cloudprovider/aws/README.md
This fixes the `--node-group-auto-discovery` flag in the aws README.
> Correct flag for node group auto-discovery

- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
This is needed as of Kubernetes 1.12
> Update RBAC example to include replicasets in the apps apigroup

- .travis.yml
- cluster-autoscaler/simulator/cluster.go
- hack/install-verify-tools.sh
- hack/verify-gofmt.sh
- hack/verify-golint.sh
- vertical-pod-autoscaler/updater/recommender/caching_recommender.go
Go 1.8 is no longer supported and travis is not able to run presubmit with it.
> Migrate to go1.10

- cluster-autoscaler/Godeps/Godeps.json
- cluster-autoscaler/_override/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
- cluster-autoscaler/_override/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/models.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
- cluster-autoscaler/vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/models.go
Without this change, CA would report following errors when using on AKS clusters:
```
containerservice.Managed
ClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedCluste
rProperties.AadProfile.ServerAppSecret constraint=Null value=(*string)(nil) details: value can not be null; required parameter`
```
Fixes #1369 #1105 #1304
> Cluster Autoscaler 1.3: fix ServerAppSecret issues for AKS clusters

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
Various ClusterAutoscaler components like the BalancingProcessor act based on the current `TargetSize` of a `NodeGroup`. https://github.com/kubernetes/autoscaler/blob/f341d8a68a6aad996964cda5db67e2f254b71c8d/cluster-autoscaler/processors/nodegroupset/balancing_processor.go#L89
As the current AWS implementation only updates `TargetSize` when refreshing the ASG list every minutes (less when being rate-limited), the cached `TargetSize` might quickly mismatch the actual value.
While each ASG change could trigger a cache refresh, I don't think this is optimal as it introduces again further requests.
Instead I decided to pre-calculate the `TargetSize` change for AWS on AutoScalingGroup changes and Node deletion to make better balancing decisions.
Any wrongly pre-calculated `TargetSize` will be …
> AWS: Improved balancing

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Run _make generate_ to pull and translate a fresh catalog of [AWS's available EC2 instance types](https://aws.amazon.com/ec2/instance-types/) used by the cluster autoscaler.
This addresses #1411 but isn't a complete solution, as [we should also trap these instance type lookup failures](https://github.com/kubernetes/autoscaler/issues/1411#issuecomment-439999208).
> Update AWS EC2 instance type catalog

- cluster-autoscaler/Godeps/Godeps.json
- cluster-autoscaler/_override/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
- cluster-autoscaler/_override/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/models.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
- cluster-autoscaler/vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice/models.go
Without this change, CA would report following errors when using on AKS clusters:
```
containerservice.Managed
ClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedCluste
rProperties.AadProfile.ServerAppSecret constraint=Null value=(*string)(nil) details: value can not be null; required parameter`
```
Fixes #1369 #1105 #1304
> Cluster Autoscaler 1.12: fix ServerAppSecret issues for AKS clusters

- vertical-pod-autoscaler/pkg/admission-controller/certs.go
We don't use it for anything.
Cherrypick 057743565cf88bfe58af2d4f284cf81a789c49f1 tovpa-release-0.3 branch
> Don't load CA key.

- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/main.go
- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/cluster_test.go
Adds the flag `--ignore-daemon-set-pods-in-utilization` (defaults to false) and when enabled, factors DaemonSet pods out when calculating the resource utilization of a node. This is useful when there are only system or metrics DaemonSets on the node that are not user workloads.
Not sure how to test this as there don't seem to be any other existing tests that test the functionality of the flags.
> add flag to ignore daemonsets when calculating resource utilization of a node

- builder/OWNERS
Builder is used only for Cluster Autoscaler. It'll be useful if more maintainers can e.g. update Go version there. Long-term, we should probably move it to /cluster-autoscaler though.
> Add OWNERS to /builder

- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1beta1_test.go
This is the same change as was done in https://github.com/kubernetes/autoscaler/pull/1356 where I see
intermittent CI failures on AWS CI instances.
Signed-off-by: Andrew McDermott <amcdermo@redhat.com>
> gce: increase test timeout in TestWaitForGkeOp

- cluster-autoscaler/processors/nodegroups/nodegroup_list_processor.go
- cluster-autoscaler/processors/pods/pod_list_processor.go
Fix some typos: "sheduled" -> "scheduled" in nodegroup_list_processor.go and pod_list_processor.go.
> Fix some typos

- hack/scripts/ca_metrics_parser.py
> Typo fixed: "Merics" -> "Metrics"

- cluster-autoscaler/core/scale_down.go
Explicitly handle nil as a return value for nodeGroup in
`calculateScaleDownGpusTotal()` when `NodeGroupForNode()` is called
for GPU nodes that don't exist. The current logic generates a runtime
exception:
"reflect: call of reflect.Value.IsNil on zero Value"
Looking through the rest of the tree all the other places that use
this pattern additionally and explicitly check whether `nodeGroup ==
nil` first.
This change now completes the pattern in
`calculateScaleDownGpusTotal()`.
Looking at the other occurrences of this pattern we see:
```
File: clusterstate/clusterstate.go
488:26:		if nodeGroup == nil || reflect.ValueOf(nodeGroup).IsNil() {
File: core/utils.go
231:26:		if nodeGroup == nil || reflect.ValueOf(nodeGroup).IsNil() {
322:26:		if nodeGroup == nil || …
```
> handle nil nodeGroup in calculateScaleDownGpusTotal

- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Looks like  this Unit Test blocks several tasks. I notice someone comment this test and I think we can use `MatchedBy` to customize comparison logic.
This will resolve #1346 and other dependent issues for 1.2
~~I run hack/verify-gofmt.sh and found several files are not formatted and then run `gofmt -s -w ${filename}` Not sure if that's needed. if not, I will remove second commit~~
> Fix aws flaking Unit Tests

- cluster-autoscaler/proposals/balance_similar.md
Fixs some small typos in [balance_similar.md](https://github.com/kubernetes/autoscaler/compare/master...JoeWrightss:patch-5#diff-e17723f54b49a53ce2943f71ef4ea0d1).
1. "labalSelector" to "labelSelector".
2. "antiaffinity" to "anti-affinity".
> Fix some spelling errors

- vertical-pod-autoscaler/examples/hamster.yaml
Very minor change, but in order to ensure that the vpa ends up in the same namespace as the deployment, the default namespace needs to be removed here. This fixes any issues with the current context have a default namespace that is not named "default".
> Remove namespace from hamster example.

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This PR adds caches for resource IDs of vmss instances. Those IDs won't change after creation, so it's safe for CA to keep them in memory.
Without this, cluster-autoscaler would be Throttled by Azure API: 
```json
"details": [
{
"code": "TooManyRequests",
"message": "{\"operationGroup\":\"GetVMScaleSetVM30Min\",\"startTime\":\"2018-11-29T20:49:14.3565951+00:00\",\"endTime\":\"2018-11-29T21:04:14.3565951+00:00\",\"allowedRequestCount\":2500,\"measuredRequestCount\":2596}",
"target": "GetVMScaleSetVM30Min"
}
],
"innererror": {
"internalErrorCode": "TooManyRequestsReceived"
},
"code": "OperationNotAllowed",
"message": "The server rejected the request because too many requests have been received for this subscription."
}
```
cc @kkmsft
> Add cache for resource IDs of vmss instances

- cluster-autoscaler/README.md
- cluster-autoscaler/cloudprovider/alicloud/README.md
- cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml
Hi guys,
Thanks for this awesome work!
I noticed in the documentation the use of the `scheduler.alpha.kubernetes.io/critical-pod` annotation that has been deprecated as of version 1.13 and will be removed in 1.14.
So this PR changes the doc to use `priorityClassName: system-cluster-critical`.
Let me know  if I need to change some wording.
Thanks for your help,
Joseph
> Doc: scheduler.alpha.kubernetes.io/critical-pod annotations are deprecated. Use priorityClassName instead.

- cluster-autoscaler/FAQ.md
Since it is easy to get to the part referencing PDB through a link from "Troubleshooting" without reading the entire document, reference PDB by full name and link to an explanation of what it is in "What types of pods can prevent CA from removing a node?"
> Less technical, more verbose PDB reference in FAQ

- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
- cluster-autoscaler/utils/daemonset/daemonset.go
- cluster-autoscaler/utils/daemonset/daemonset_test.go
- cluster-autoscaler/utils/kubernetes/listers.go
Currently we call the API many times per loop to get various controllers. Turns out it impacts CA performance quite a bit in large clusters (and it puts an extra load on API server). 
This is preparatory work for migrating those API calls to use watch cache instead.
I decided to use upstream listers directly, rather than wrap them in our own interface. Partly because we will actually need to replace Get() calls which the upstream lister already provides (and our interfaces don't), partly because all we did in our interface was forward the call to upstream interface anyway and using upstream interface feels more consistent with k8s ecosystem.
I've migrated existing daemonSetLister to use upstream interface as well to be consistent with other controllers (and migrated it to use …
> Add listers for more controllers

- cluster-autoscaler/core/scale_up.go
When scaling up, the calculation for the maximum size of the cluster
based on `--max-nodes-total` doesn't take into account any nodes that
are in the process of coming up. This allows the cluster to grow
beyond the size specified.
With this change I now see:
scale_up.go:266] 21 other pods are also unschedulable
scale_up.go:423] Best option to resize: openshift-cluster-api/amcdermo-ca-worker-us-east-2b
scale_up.go:427] Estimated 18 nodes needed in openshift-cluster-api/amcdermo-ca-worker-us-east-2b
scale_up.go:432] Capping size to max cluster total size (23)
static_autoscaler.go:275] Failed to scale up: max node total count already reached
> fix calculation of max cluster size

- cluster-autoscaler/version.go
Update Cluster Autoscaler version to 1.2.4
> Cluster Autoscaler 1.2.4

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
This patch sets and then resets the `AWS_REGION` environment variable in
tests that call `createAWSManagerInternal`, which calls `getRegion`.
`getRegion` introduced `AWS_REGION` lookup at runtime, but tests that
don't (a) run inside AWS or (b) set `AWS_REGION` environment variable
encountered AWS SDK's EC2 Metadata lookup timeout. Tests that indirectly
invoked `getRegion`, e.g., via `createAWSManagerInternal`, saw at least
a 5-second timeout per invocation, ballooning test times.
> Set AWS_REGION so tests don't wait for SDK timeout #1449

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
As per the Azure GO SDK docs `WaitForCompletion` is deprecated. This should be safe since `WaitForCompletion` calls `WaitForCompletionRef` anyway
> Replace the deprecated function calls of go-autorest

- cluster-autoscaler/cloudprovider/azure/README.md
Amending docs as per the thread in #884 . For Cluster-Autoscaler to work, we need to ensure that resource groups match by case when provided in the secret.
> Azure: update docs to ensure aks/aks-engine autoscaler users provide the resource group name correctly

- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/utils/deletetaint/delete.go
- cluster-autoscaler/utils/deletetaint/delete_test.go
Depend on https://github.com/kubernetes/autoscaler/pull/1587
> Tainting nodes - update first, refresh on conflict

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Resolve #1592 by omitting the Identities property from the VirtualMachineScaleSet object when sending the scale request. If set, Azure will return 400 BadRequest.
> Remove identity from Azure VMSS scale request as it is not allowed to be set

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/azure/azure_util_test.go
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-containerservice.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml
The PR fixes windows name parsing for Azure VMAS nodes. It also moves yaml to examples and add missing daemonsets.
Fixes #1593
>  Fix windows name parsing for Azure VMAS nodes

- cluster-autoscaler/cloudprovider/baiducloud/baiducloud-sdk-go/util/util.go
**What this PR does / why we need it:**
Use klog instead of log for BaiduCloud debug mode log.
> Use klog instead of log

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
Cluster Autoscaler crashes if there are some AWS ASG that use instances
types and was not updated in the build.
Update tests for case when there is unknown instance type and return
error if there is one.
Sample of excepttion:  #483
Covers changes for 1.3 branch only
> Don't panic on unknown aws instance type

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Sync instance type for aws via `make generate`
> Updated aws instance types actual for 2019.02.10

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
> Adding ability to override allocatable resources via ASG tags. 

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
1. v1.10 is going to sunset, upgrade to 1.3.6 which is compatible with v1.11 in examples.
2. Remind users to replace config in examples. #1669
3. Make clarification on min/max settings for one/multiple node groups. #1559 #1555 #1640
4. Recommend users to adopt Auto-Discovery option. #1640
> Update AWS documentation and CA version in examples

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
> Cherry-pick of #1490: Set AWS_REGION so tests don't wait for SDK timeout #1449

- cluster-autoscaler/expander/mostpods/mostpods_test.go
- cluster-autoscaler/expander/random/random.go
- cluster-autoscaler/expander/random/random_test.go
when the random-expander is used, if the options length is zero there will be a panic cause. this pr try to fix it.
> fix(expander): avoid panic when random expander

- vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
- vertical-pod-autoscaler/deploy/recommender-deployment.yaml
- vertical-pod-autoscaler/deploy/updater-deployment.yaml
- vertical-pod-autoscaler/deploy/vpa-beta-crd.yaml
- vertical-pod-autoscaler/deploy/vpa-beta2-crd.yaml
- vertical-pod-autoscaler/deploy/vpa-crd.yaml
- vertical-pod-autoscaler/deploy/vpa-rbac.yaml
Some workflows assume concatenated YAML to be as valid & applicable as a bunch of separate YAML files.
This commit make make it safe & valid to merge all VPA files in deploy/ prior to execution.
Fixes syntax error resulting from merging VPA files without explicit initial start-of-a-document marks:
`error: error validating "vpa.yaml": error validating data: ValidationError(ServiceAccount): unknown field "spec" in io.k8s.api.core.v1.ServiceAccount; if you choose to ignore these errors, turn validation off with --validate=false`
> VPA: add YAML start of a document marks

- vertical-pod-autoscaler/pkg/target/fetcher.go
- vertical-pod-autoscaler/pkg/target/mock/fetcher_mock.go
- vertical-pod-autoscaler/pkg/target/v1beta1_fetcher.go
- vertical-pod-autoscaler/pkg/target/v1beta1_fetcher_test.go
Following implementations are provided:
- one for v1beta1 VPAs that fetches label selector
- one for v1beta2 that fetches from targetRef (contributed by kgolab)
- mock
> VPA - Introduce VpaTargetSelectorFetcher

- vertical-pod-autoscaler/hack/run-e2e-tests.sh
- vertical-pod-autoscaler/hack/run-e2e.sh
Since we want to run 2 e2e test scripts we don't want to exit on failure of the first one.
> VPA - disable errexit in run e2e scripts

- vertical-pod-autoscaler/deploy/vpa-beta2-crd.yaml
According to [this document](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#overview) we should also set `version` field.
Without doing this, it is impossible to deploy VPA on Kubernetes 1.10.
Before:
```
./hack/vpa-up.sh
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "verticalpodautoscalers.autoscaling.k8s.io" is invalid: spec.version: Required value
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "verticalpodautoscalercheckpoints.autoscaling.k8s.io" is invalid: spec.version: Required value
clusterrole.rbac.authorization.k8s.io/system:metrics-reader created
clusterrole.rbac.authorization.k8s.io/system:vpa-actor …
```
> Add version field to spec

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/azure/azure_util_test.go
Get HTTP responses together with error, so that we could get full error
messages. It also fixes some edge cases for success responses.
Fix #1661.
> Fix error message for long-waiting operations

- vertical-pod-autoscaler/pkg/admission-controller/Dockerfile
- vertical-pod-autoscaler/pkg/recommender/Dockerfile
- vertical-pod-autoscaler/pkg/updater/Dockerfile
> Add the ability to better pass additional arguments to containers

- vertical-pod-autoscaler/pkg/admission-controller/config.go
Actual verification was turned off from the initial commit and is still [not enabled](../blob/6b1a97c16001a98607424568faf7239b5c364d11/vertical-pod-autoscaler/pkg/admission-controller/config.go#L79), so the whole construct does not add value.
Also depending on `requestheader-client-ca-file` by itself renders VPA incompatible with apiserver installations which does not use such certificate with VPA Admission Controller crash-looping with:
`vpa-admission-controller-X-Y:admission-controller F0214 18:15:09.448204       9 config.go:60] cannot find the ca.crt in the configmap, configMap.Data is map[string]string{"client-ca-file":"...skipped..."}`
In addition to the above it worth noting that `requestheader-client-ca-file` appears to be just a wrong place to look for _possible_ apiserver client …
> VPA: Remove TLS client cert lookup logic

- vertical-pod-autoscaler/deploy/vpa-rbac.yaml
This looks like unintended effect of renaming VPA ClusterRole `scale-reader` to `vpa-target-reader` in 0bc25d5.
Repetitive `vpa-vpa-` while being technically correct and in accordance with naming convention in a surrounding blocks just looks wrong.
> Rename vpa-target-reader ClusterRoleBinding name

- cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go
- cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types.go
- cluster-autoscaler/cloudprovider/alicloud/alicloud_manager.go
- cluster-autoscaler/cloudprovider/alicloud/alicloud_manager_test.go
link to the pr (https://github.com/kubernetes/autoscaler/pull/1719) . @lookstar Hi, If you use autoscaler in Alibaba Cloud Kubernetes,it has supported labels right now. And I am sorry to forget merge these code from internal branch. The difference is we will attach every ess label as node label instead of the value under a specific key. because the other node labels are also plain tag.
> Add labels support for Alibaba Cloud Provider

- vertical-pod-autoscaler/pkg/admission-controller/main.go
- vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
- vertical-pod-autoscaler/pkg/recommender/input/history/history_provider_test.go
- vertical-pod-autoscaler/pkg/recommender/main.go
To use VPA on AWS EKS I needed to change the port for the admission controller webhook, so I would propose to have a flag for it.
For the recommender to be able to get historical metrics from prometheus I need to tune the metrics and labels to query prometheus properly, so I would add a bunch of flags for that.
This PR is just to share the ideas.
> Some configurable parameters

- cluster-autoscaler/core/static_autoscaler.go
Soft tainting nodes when there are nodes we can delete immediately uses up quota, increasing the chance of delete failure. Moving it to trigger only as "best effort" - i.e. when there's nothing else to do and no errors.
cc @jkaniuk
> Only soft taint nodes if there's no scale down to do

- cluster-autoscaler/context/autoscaling_context.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/main.go
Using separate Kubernetes client for events is recommended practice. Also, throttling is especially painful with bulk scale down of empty nodes.
> Use separate client for events

- vertical-pod-autoscaler/pkg/admission-controller/config.go
- vertical-pod-autoscaler/pkg/admission-controller/main.go
> Allow vpa-admission-controler to installl on specific path

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Originally I found that the g3s.xlarge instance type was not reporting a GPU so after much back and forth I finally got AWS to add it to the metadata endpoint.
The changes were generated by running `gen.go`, it looks to have fixed up the g3s.xlarge instance but also added a bunch of new instance types, if I ran it wrong let me know.
> Regenerate the ec2 instance types using latest metadata

- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
The AWS examples appear to be missing the daemonsets resource under the apps apiGroup, looks like this was updated for the Azure examples recently so adding the same to the AWS examples.
> Add missing daemonsets to AWS example cluster role

- cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
- cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/mocks/CloudProvider.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/clusterstate/clusterstate.go
This PR adds a new `GetInstanceID()` for cloud provider interface, which is required for fixing the VMSS cases different issues.
For VMSS node's providerIDs, they may be in different cases depending user's PUT requests to the resources. This would cause autoscaler to delete all newly provisioned nodes. And more seriously, CA would scale up/down again and again.
This PR adds a workaround for this issue, so that they are handled in lower cases in CA.
/assign @mwielgus  @losipiuk
cc @andyzhangx @ritazh
> Cluster Autoscaler:  add GetInstanceID() for cloudprovider interface

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_manager.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/clusterstate/clusterstate.go
Cluster Autoscaler 1.2 : cherry pick of #1738: add GetInstanceID() for cloudprovider interface
> Cluster Autoscaler 1.2 : cherry pick of #1738

- hack/verify-gofmt.sh
gofmt changes between golang versions.
That PR ensures that we validate accordingly to golang version used for particular release.
> Use docker in gofmt verification

- cluster-autoscaler/core/static_autoscaler.go
The previous code was checking an invalid error condition that no longer is valid in the statement's scope.
> Fixing minor error handling bug in static autoscaler

- cluster-autoscaler/core/scale_up.go
When scaling up the calculation for computing the maximum cluster size
does not take into account the number of any upcoming nodes and it is
possible to grow the cluster beyond the cluster
size (--max-nodes-total).
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1670695
See also: 5bc77f051cbce1fbe77d99cc6b0670128f330585
> UPSTREAM: <carry>: fix max cluster size calculation on scale up

- cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/azure/azure_util_test.go
- cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/gke/gke_cloud_provider.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/mocks/CloudProvider.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/clusterstate/clusterstate.go
Follow up of https://github.com/kubernetes/autoscaler/pull/1738.
As we agreed, #1738 is a temporary workaround for fixing the isues in stable releases. For the following v1.14, https://github.com/kubernetes/kubernetes/pull/74882 has made a change in kubernetes repo, so that resourceGroupName in providerID would be always in lower cases.
This PR reverts the changes in #1738 and also aligned the providerID in same format from #74882.
Note that with this change, because the providerID is in different format, master branch (or following v1.14 release) of CA won't work again with kubernetes <=1.14.0-beta.1. This is ok because beta version won't be run in production and CA should always be used with matched version of kubernetes according to the [version matrix …
> Cluster Autoscaler: Cleanup GetInstanceID() interface

- cluster-autoscaler/core/static_autoscaler.go
Quick fix for not applying soft taints when nodes haven't been unneeded for long enough. Long-term, I really think we should reconsider scale down statuses and what they mean (not unneeded for long enough != no unneeded)
> Soft taint when there are no candidates

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go
Fix bulk removal issues of AKS scaling:
> When scaling down we observe unexpected behaviors in the cluster autoscaler, where initially nodes are removed quickly but then mysteriously are added back a few minutes later.
The issue happens because after the virtual machines are removed, CA would also tries to correct the node count by invoking the AKS PUT API. Unfortunately, for bulk removal, multiple virtual machines are deleted in different Go routines, and hence their calculated new counts are wrong.
This PR fixed this issue by adding a lock for ContainerServiceAgentPool. It also adds a cache for getting current node count, so as to reduce the API calls.
Fix #1597
> Fix bulk removal issues of AKS scaling

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
This makes v1beta1 objects handled via ConfigUnsupported condition, sample status of an v1beta1 object after the change:
```
status:
conditions:
- lastTransitionTime: 2019-03-12T13:13:01Z
message: Label selector is no longer supported, please migrate to targetRef
status: "True"
type: ConfigUnsupported
- lastTransitionTime: 2019-03-12T13:13:01Z
status: "False"
type: RecommendationProvided
recommendation: {}
```
**NOTE:** This change is not flag-guarded since it didn't make sense to reuse `beta1-api-deprecated` flag and I didn't wanted to introduce another one. Please let me know if you want this otherwise.
PS. I haven't touched validation in this PR so one can still create v1beta1 objects. This will be part of a separate PR.
> Delete support for v1beta1 API w/o deleting the API itself.

- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
Follow-up to #1783 .
It's a bit of a poor man's solution since we don't have the version nor v1beta1 fields at hand so I've used (lack of) TargetRef for validation.
Moreover, the validation can be by-passed by updating the object but I guess at that point the user has been already warned.
An attempt to create v1beta1 object (or simply v1beta2 w/o TargetRef) ends up with:
```
Error from server (InternalError): error when creating "b1.yaml": Internal error occurred: admission webhook "vpa.k8s.io" denied the request: TargetRef is required
```
> Forbid creating VPA objects without targetRef

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Replicated changes from kubernetes "Add AWS Custom Endpoint capability #70588" into cluster-autoscaler:
- Modified aws_manager similar to kubernetes aws.
- Modified kubernetes aws exposing type/methods used by cluster-autoscaler aws_manager.
Closes #1707
Fixes #1707
> Allow custom AWS region overrides #1707

- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
AWS example yaml files were shipped with image k8s.gcr.io/cluster-autoscaler:v1.2.2 which does not support autodiscovery in cluster-autoscale 1.13 release.
> Update cluster-autoscaler image to 1.13.2 in yaml files

- cluster-autoscaler/version.go
Initial (non-beta) release of CA 1.14.0. No changes since 1.14.0-beta.2
> Cluster Autoscaler 1.14.0

- cluster-autoscaler/FAQ.md
I noticed that information about node affinity support is pretty hard to obtain. I found it eventually on Slack and have seen others looking for the information. See https://kubernetes.slack.com/messages/C09R1LV8S
So, I'm adding a Q to the FAQ with this information.
> Add information about node affinity to the FAQ

- cluster-autoscaler/.gitignore
- cluster-autoscaler/FAQ.md
- cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-containerservice.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml
- cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/expander/expander.go
- cluster-autoscaler/expander/factory/expander_factory.go
- cluster-autoscaler/expander/priority/configmap_handler.go
- cluster-autoscaler/expander/priority/priority-expander-configmap.yaml
- cluster-autoscaler/expander/priority/priority.go
- cluster-autoscaler/expander/priority/priority_test.go
- cluster-autoscaler/expander/priority/readme.md
This commit introduces code, tests and docs for a new expander called 'priority'. The motivation is placed in [this proposal](proposals/priority_expander.md). Docs are updated as well in [FAQ](FAQ.md#what-are-expanders).
Full autoamted kubernetes e2e tests were not done. The testing procedure was as follows:
1. Unit tests
`go test ./expander/priority/...`
1. Manual e2e tests
- I started a test cluster and connected the new cluster-autoscaler binary to it
- checked for selection of the correct node group
- check for handling of ConfigMap reloads
> New expander: priority expander

- .gitignore
- cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
- cluster-autoscaler/cloudprovider/mocks/CloudProvider.go
- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/expander/factory/expander_factory.go
- cluster-autoscaler/expander/price/price.go
- cluster-autoscaler/expander/price/price_test.go
- cluster-autoscaler/utils/gpu/gpu.go
- cluster-autoscaler/utils/gpu/gpu_test.go
This PR is to address #1135 
1. Add GPULabel() and GetAvailableGPUTypes() in cloudprodiver interface 
2. Caller will pass GPULabel to methods in gpu.go which original relies on GPULabel
3. Pass cloud.CloudProvider to methods in scale_up.go and scale_down.go that don't use GPULabel directly. 
Please don't merge this PR until I confirm with all cloud provider owners and check if they're ok about labels and supported GPU types.
> Move GPULabel and GPUTypes to cloud provider

- vertical-pod-autoscaler/README.md
Fixes a number of broken anchor links with the VPA Readme and adds one to final section (`Related Links`)
> Correct VPA Readme anchor links

- cluster-autoscaler/main.go
It defaulted to default value for --scan-interval (10s), not actual value passed to this flag. Setting it to 0 means it'll effectively be limited only be --scan-interval anyway.
> Fix default scale down delay after delete

- cluster-autoscaler/FAQ.md
Initial documentation for the handling of min_nodes and max_nodes parameters. These are currently not publicly documented and have caused some confusion.
Fixes #1849
> Document behavior of min_nodes and max_nodes

- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/main.go
- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/cluster_test.go
- cluster-autoscaler/utils/test/test_utils.go
Address #1367 
1. Consider GPU resource in utilization calculation. 
2. Add separate flag for GPU Utilization Threshold. 
3. Add UTs and also cover the case that annotate GPU pods to prevent eviction. (Training use case)
> Consider GPU utilization in scaling down

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Switch formatting directive to `%v` when logging `instances`. This
allows `go test ./...` to work in `autoscaler/cluster-autoscaler`.
Without this running the tests currently fail with:
```console
cloudprovider/azure/azure_scale_set.go:282:2: Infof format %q has arg instances of wrong type []*k8s.io/autoscaler/cluster-autoscaler/cloudprovider/azure.azureRef
FAIL	k8s.io/autoscaler/cluster-autoscaler/cloudprovider/azure [build failed]
```
As this is trying to print `[]*azureRef` I added a `String()` method
to `azureRef` which returns `Name`. Without that it will print pointer
values which is unlikely to be useful as a default.
> cloudprovider/azure: fix formatting directive

- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state_test.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go
Fixes the issue that we never removed aggregate container states for pods that lived too short too get any samples (common with short-lived cronjobs).
Adds garbage collection of old empty containers. Also removes aggregate container states that are empty and inactive - there are no live pods that can contribute metric samples.
/assign @jbartosik 
FYI @kgolab @schylek
> Fix garbage collection for empty aggregate container states.

- cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
- cluster-autoscaler/cloudprovider/magnum/magnum_manager.go
- cluster-autoscaler/cloudprovider/magnum/magnum_manager_heat.go
- cluster-autoscaler/cloudprovider/magnum/magnum_manager_heat_test.go
This PR has 3 separate commits
* One which renames things that were overlooked when the cloud provider name was changed from openstack to magnum.
* One which excludes the master node from being considered as a part of the nodegroup (fixes #1870)
* One which converts machine UUIDs from a format without dashes which kubernetes stores, to a format with dashes which openstack uses. Needed for looking up minion stack indices when deleting them.
Regarding the second commit, is there a utility function somewhere in the kubernetes codebase for checking if a role exists on a node, or is this the best way to do it?
```go
if _, found := node.ObjectMeta.Labels["node-role.kubernetes.io/master"]; found {
```
> Fixes for CA Magnum cloud provider

- cluster-autoscaler/Makefile
- hack/for-go-proj.sh
/cc maciekpytel
/cc losipiuk
/cc mwielgus
> Enable race detection in unit tests (CA 1.14)

- addon-resizer/Makefile
This is part of the effort described in KEP kubernetes/enhancements#900
This mitigates the affect of GVE issues.
> Rebase addon-resizer to distroless

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster.go
- vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
- vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go
This PR adds a flag which indicates that the VPA recommender will onlty track pods and containers which have an associated VPA. Fixes #1548
> Added memory saver mode for VPA recommender

- cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-containerservice.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml
- cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-svcaccount.yaml
@MaciekPytel 
Related to: https://github.com/kubernetes/autoscaler/pull/1843
Priority expander needs now wider permissions, so I updated deployment examples.
> priority expander based on client-go for cluster autoscaler is missing permissions

- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
Adding rules needed of the Jobs on file to work.
> Fix: failed forbidden Jobs

- vertical-pod-autoscaler/FAQ.md
* Add anchor links to the VPA FAQs
* Minor grammatical changes
I think this makes the FAQs a bit more navigable, and matches up with the anchor linking in `README.md` for the VPA
> Add VPA FAQs anchor links

- vertical-pod-autoscaler/pkg/admission-controller/certs.go
I've deployed vertical-pod-autoscaler:0.5.0 with custom certificates. After that, logs of the vpa-admission-controller show the following error: `tls: bad certificate`. The provided fix helped me to address that issue.
> Return read bytes while reading certs

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Add cache to `getInstanceTypeByLCName`.
**Special notes for your reviewer**:
If you have a launch configuration that can't bootstrap a valid Kubernetes node (in our case, a bug on user-data), the cluster-autoscaler try to execute a lot of `DescribeLaunchConfigurations` making the Auto Scaling Group and Launch Configurations aws console unresponsive due  to rate limit. 
Launch configuration is immutable, so add a cache by LC name seems safe.
> Add cache to getInstanceTypeByLCName for avoid aws rate limit

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Cherry pick of #1935 on cluster-autoscaler-release-1.14
#1935: Add cache to getInstanceTypeByLCName for avoid aws rate limit
> Cherry pick of #1935 on cluster-autoscaler-release-1.14: Add cache to getInstanceTypeByLCName for avoid aws rate limit

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Cherry pick of #1935 on cluster-autoscaler-release-1.13
#1935: Add cache to getInstanceTypeByLCName for avoid aws rate limit
> Cherry pick of #1935 on cluster-autoscaler-release-1.13: Add cache to getInstanceTypeByLCName for avoid aws rate limit

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Cherry pick of #1935 on cluster-autoscaler-release-1.12
#1935: Add cache to getInstanceTypeByLCName for avoid aws rate limit
> Cherry pick of #1935 on cluster-autoscaler-release-1.12: Add cache to getInstanceTypeByLCName for avoid aws rate limit

- vertical-pod-autoscaler/e2e/v1beta1/full_vpa.go
- vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go
Check that initial recommendation is provided for both CPU & memory and only then await for an updated recommendation on resource increase.
Also fixes expected value for CPU since the minimal recommendation is nowadays 25mCPU.
Uses large range for minimal memory recommendation to be future-proof in case we lower the default from current 250 MiB.
> Make "Full VPA" E2E tests stricter

- cluster-autoscaler/cloudprovider/magnum/magnum_manager_heat.go
- cluster-autoscaler/main.go
- cluster-autoscaler/version/version.go
Moving the version string into its own package lets it be imported from other packages, which can be useful in the cloud providers.
The second commit in this PR uses the version string to set the user-agent for gophercloud in the magnum cloud provider, to provide more information in request logs. This is a goal of the OpenStack K8s SIG: https://etherpad.openstack.org/p/k8s-sig-ptg-train
```
- Enhancement User agent header patch - gopher cloud
- append to the user agent the particular project you're working on
- this is useful for logging and tracing and telemetry
```
The user-agent then looks like
```
cluster/20000bea-83fd-4e21-b6cd-1cd0ea07c157 cluster-autoscaler/1.14.0-beta.2 gophercloud/2.0.0
```
instead of just `gophercloud/2.0.0`.
> Move CA version string to own package, for use by cloud providers

- cluster-autoscaler/cloudprovider/aws/README.md
Hi,
I rant into the following error when starting with an empty ASG on AWS:
```
Failed LaunchConfiguration info request for ASG_NAME: AccessDenied: User: arn:aws:sts::1234567890:assumed-role/ROLE_NAME/INSTANCE_ID is not authorized to perform: autoscaling:DescribeLaunchConfigurations
```
Reference: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/auto_scaling.go#L51-L55
The issue was resolved after adding the `autoscaling:DescribeLaunchConfigurations` action to the IAM policy.
> Add required IAM action 'autoscaling:DescribeLaunchConfigurations' to AWS readme

- vertical-pod-autoscaler/e2e/v1beta1/admission_controller.go
- vertical-pod-autoscaler/e2e/v1beta1/common.go
- vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider_test.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
The test was failing because it recommendation was higher than the limit so it got capped. With changes I'm making to how VPA handles limits capping to limit doesn't make much sense.
> Preserve limit / request ratio, don't cap recommendations to limit

- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Fixes #1608 
I verified that the new test case fails without the case-insensitive lookup.
> Look up Azure instance types case-insensitively

- vertical-pod-autoscaler/pkg/recommender/main.go
- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster.go
- vertical-pod-autoscaler/pkg/recommender/model/container.go
- vertical-pod-autoscaler/pkg/recommender/model/vpa.go
- vertical-pod-autoscaler/pkg/recommender/model/vpa_test.go
- vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
- vertical-pod-autoscaler/pkg/utils/metrics/quality/quality.go
- vertical-pod-autoscaler/pkg/utils/test/test_recommendation.go
Initial stab at monitoring diffs between recommendation and actual usage. Putting this up for discussion.
This has some drawbacks:
- pollutes the ContainerState interface
- When no recommendation is provided, we don't notice (I will work on fixing this one later)
However thanks to this approach we record diff on every usage sample we get (including OOMs).
@kgolab @schylek let me know what you think.
> Monitor diffs between usage and recommendation.

- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/expander/price/preferred_test.go
- cluster-autoscaler/main.go
- cluster-autoscaler/utils/kubernetes/listers.go
Implement functionality which delays node deletion when node has annotation with  prefix
'delay-deletion.cluster-autoscaler.kubernetes.io/'. Functionality will be used by ingress controller to drain connections to the node before it is deleted. It also can be used by other components.
> Add functionality which delays node deletion to let other components prepare for deletion.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- Change all `acs-engine` references to `aks-engine`
- Change references of`Kubernetes` and `Azure` to start with an upper case  
- Some small grammar fixes
- Markdown formatting fixes
> Improve autoscaler on Azure README

- cluster-autoscaler/simulator/predicates.go
Having call to algorithmprovider.ApplyFeatureGates() in module init
function was problematic as the mathod calls out to klog.Infof().
The call to klog.Infof() was then happening before klog related
application flags were parsed which resulted in klog misbehavior.
See https://github.com/kubernetes/klog/issues/67.
> Move static scheduler initialization out of module init()

- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider_test.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
- vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go
- vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling_test.go
Refactoring to make the code consistent.
Removed applying to upper and lower bound - I was mistaken that
it was needed >.<.
Note that since the recommendation is already capped
to max/min limit, there is no additional need for capping
in the GetContainerResources method.
> Account for min Limit from LimitRange.

- vertical-pod-autoscaler/pkg/admission-controller/main.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
This should result in `Admission-controller caps request according to max limit set in LimitRange` test being able to create pods request capped to min (fixing tests expectation in a separate PR).
> Minimums of limit range apply also to requests

- vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
This fixed failing e2e locally except `raises request according to pod min limit set in LimitRange` which fails because pods don't start because `"pods \\\"hamster-deployment-699575768d-rbj24\\\" is forbidden: minimum memory usage per Pod is 500Mi, but request is 419430400.\"`
> Fix limit support

- vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
Admisson controller was crashing because it was tryig to divide by 0 so
it dind't make any changes to pod.
Adter I fixed that only 1 pod would fit in the cluster so I lowered
recommendation.
> Fix raises request according to pod min limit set in LimitRange test

- vertical-pod-autoscaler/e2e/v1beta1/admission_controller.go
- vertical-pod-autoscaler/e2e/v1beta1/common.go
- vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
- vertical-pod-autoscaler/e2e/v1beta2/common.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider_test.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go
- vertical-pod-autoscaler/pkg/utils/test/test_container.go
- vertical-pod-autoscaler/pkg/utils/test/test_pod.go
- vertical-pod-autoscaler/pkg/utils/test/test_utils.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
Cherry pick:
* PRs preparing VPA for limit and limit range support:
* https://github.com/kubernetes/autoscaler/pull/1879
* https://github.com/kubernetes/autoscaler/pull/1880
* https://github.com/kubernetes/autoscaler/pull/1950
* https://github.com/kubernetes/autoscaler/pull/1990
* PRs implementing support for limits:
* https://github.com/kubernetes/autoscaler/pull/1993
* https://github.com/kubernetes/autoscaler/pull/1997
* https://github.com/kubernetes/autoscaler/pull/1998
* https://github.com/kubernetes/autoscaler/pull/2005
> Cherry limit 05

- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/clusterstate/clusterstate_test.go
- cluster-autoscaler/core/static_autoscaler.go
This will provide the AutoscalingStatusProcessor with information
about failed scale-ups.
> Retain information about scale-up failures in CSR

- vertical-pod-autoscaler/e2e/v1beta1/admission_controller.go
- vertical-pod-autoscaler/e2e/v1beta1/common.go
- vertical-pod-autoscaler/e2e/v1beta2/admission_controller.go
- vertical-pod-autoscaler/e2e/v1beta2/common.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider_test.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go
- vertical-pod-autoscaler/pkg/utils/test/test_container.go
- vertical-pod-autoscaler/pkg/utils/test/test_pod.go
- vertical-pod-autoscaler/pkg/utils/test/test_utils.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
Cherry pick:
PRs preparing VPA for limit and limit range support:
#1879
#1880
#1950
#1990
PRs implementing support for limits:
#1993
#1997
#1998
#2005
This is analogous to #2105 but this one had conflicts (mostly import changes, one in unit tests)
> Cherry limits to 04

- cluster-autoscaler/clusterstate/clusterstate.go
Calling cloudprovider.NodeGroupForNode(unregistered.Node) can result
in a nil result for the nodegroup - handle that case.
> Fix potential SEGV in updateReadinessStats

- cluster-autoscaler/README.md
Updates the Cluster Autoscaler's version compatibility matrix up to v.1.15.X
> Update CA version compatibility matrix

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/core/static_autoscaler.go
This PR allows scaling multiple Azure vmss synchronously by delaying the vmss capacity updates in different goroutines.
To make it work, the upcoming nodes from `getUpcomingNodeInfos()` are also changed to different names, so that multiple nodes won't be merged as one node in `filterOutSchedulableByPacking()`.
Partially fix #2044 (similar node issues are tracked at #2094)
Fix #1984
/cc @andyzhangx @nilo19
> Allow scaling multiple Azure vmss synchronously

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/azure/azure_util_test.go
In go-autorest SDK https://github.com/Azure/go-autorest/blob/master/autorest/sender.go#L242,
if ARM returns http.StatusTooManyRequests, the sender doesn't increase the retry attempt count,
hence the Azure clients will keep retrying forever until it gets a status code other than 429.
```go
// don't count a 429 against the number of attempts
// so that we continue to retry until it succeeds
if resp == nil || resp.StatusCode != http.StatusTooManyRequests {
attempt++
}
```
So this PR explicitly remove `http.StatusTooManyRequests` from `autorest.StatusCodesForRetry`. To reduce the API throttling issues, it also adds caches for vmss instances.
Fix #2124.
/cc @andyzhangx @nilo19
> Fix Azure client requests stuck issues on http.StatusTooManyRequests

- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
Resource limit message was indistinguishable from resource limits message. This change adds the type of resource on which limit would be exceeded.
Had to refactor scale up tests a bit in order to add a unit test without duplicating the entire test setup.
> Add resource limit type to NotTriggerScaleUp event

- vertical-pod-autoscaler/pkg/recommender/Dockerfile
PR addresses a recent issue brought up in #2162 
This change will still keep the default behavior of the recommender container the same - if the user does not specify anything the entrypoint and default commands will be executed as before. If the user does specify additional commands to the recommender container when running it those arguments will override the existing defaults.
> tweak: add CMD options to recommender Dockerfile Entrypoint

- vertical-pod-autoscaler/pkg/admission-controller/Dockerfile
- vertical-pod-autoscaler/pkg/updater/Dockerfile
PR updates VPA updater and admission-controller Dockerfiles to use CMD
Conversation tracked in previously merged PR (which updated the Dockerfile for the recommender). 
https://github.com/kubernetes/autoscaler/pull/2166#issuecomment-509225247
This change will still keep the default behavior of the updater and admission-controller containers the same - if the user does not specify anything the entrypoint and default commands will be executed as before. If the user does specify additional commands to the container when running it those arguments will override the existing defaults.
> tweak: add CMD to updater and admission-controller Dockerfile Entrypoint

- hack/scripts/break_mig.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
> Use print() function in both Python 2 and Python 3

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
- vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go
to raise code coverage of controller_fetcher and cluster_feeder.
> add test case for controller_fetcher and cluster_feeder

- vertical-pod-autoscaler/pkg/admission-controller/certs.go
Currently we read certificate files into a buffer of 5000 bytes. This sets a max size for our certificates; above this max, we will get invalid certs, most likely, leading to runtime bad certificate errors.
> Use ioutil for certificate file reading.

- vertical-pod-autoscaler/deploy/vpa-rbac.yaml
- vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go
- vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go
- vertical-pod-autoscaler/pkg/target/fetcher.go
> Add support for cronjobs in VPA

- hack/scripts/break_mig.py
- hack/scripts/ca_metrics_parser.py
This PR ensures equivalent functionality in both Python 2 and Python 3.
> xrange() was removed in Python 3 in favor of range()

- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml
- SubscriptionID placeholder does not match documentation or surrounding placeholders
> Fix typo in autoscaler azure example

- cluster-autoscaler/clusterstate/clusterstate.go
nodeGroup judy IsNil to avoid crashed
> nodeGroup judy IsNil to avoid crashed

- cluster-autoscaler/FAQ.md
Heapster is deprecated and retired now:
https://github.com/kubernetes-retired/heapster/
The Metrics Server should be used now, so let's mention that on the FAQ
to avoid confusions.
> Use Metrics Server instead of Heapster in the FAQ

- cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider.go
- cluster-autoscaler/cloudprovider/baiducloud/baiducloud_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/builder/builder_alicloud.go
- cluster-autoscaler/cloudprovider/builder/builder_all.go
- cluster-autoscaler/cloudprovider/builder/builder_aws.go
- cluster-autoscaler/cloudprovider/builder/builder_azure.go
- cluster-autoscaler/cloudprovider/builder/builder_baiducloud.go
- cluster-autoscaler/cloudprovider/builder/builder_gce.go
- cluster-autoscaler/cloudprovider/builder/builder_kubemark.go
- cluster-autoscaler/cloudprovider/builder/builder_magnum.go
- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
- cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
- cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
- cluster-autoscaler/core/autoscaler.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
- cluster-autoscaler/processors/nodegroupset/azure_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/azure_nodegroups_test.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Related to issue https://github.com/kubernetes/autoscaler/issues/2044 and pull request https://github.com/kubernetes/autoscaler/pull/2094
Refact the corresponding code in https://github.com/kubernetes/autoscaler/pull/2094.
The instance of cloudprovider.interface can only be obtained after the cluster autoscaler is built. Therefore, we let each cloud provider implement their own node comparator function, which will later be built in autoscaler in main.go.
> fix: ignore agentpool label when looking for similar node groups with Azure provider

- vertical-pod-autoscaler/examples/hamster-deprecated.yaml
- vertical-pod-autoscaler/examples/hamster.yaml
The VPA example deployments were recently switched to apps/v1. [#2209 ]
While attempting `kubectl create -f examples/hamster.yaml` the following error was revealed:
`error: error validating "examples/hamster.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec`
I found this was due to `apps/v1` requiring that .spec.selector and .metadata.labels be explicitly set:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector
This PR updates the examples to conform to `apps/v1`
> Add required selector to VPA deployment examples for apps/v1

- cluster-autoscaler/processors/nodegroupset/balancing_processor.go
- cluster-autoscaler/processors/nodegroupset/balancing_processor_test.go
Cluster Autoscaler was stopping scaling up when there was a multizonal node pool pool with number of nodes exceeding limit for one zone. For example if we have multizonal node pool with 2 zones with max set to 3. Node pools have sizes of 2 and 4 then Cluster Autoscaler gets stuck as it tries to scale only this node pool and balancing processor prevents it as total size is already 6.
> Fix bug in balancing processor. 

- cluster-autoscaler/FAQ.md
I was trying to debug why, in our (custom) clusters, nodes continue to exist (with status NotReady) when the cluster-autoscaler _deletes_ them.
"delete node" has a specific meaning in the context of the Kubernetes
API: deleting the node object.
In the end, I found that it is not actually expected to do that: kube-controller-manager (or cloud-controller-manager) is. The repeated use of "delete(ing/s) node" in the FAQ obscured this.
I am proposing to
* change the FAQ to say "terminate"
* it may make sense to change the flags later as well?
* add an FAQ entry that makes this relationship clear
> cluster-autoscaler FAQ: clarify what "deleting nodes" means in this context

- vertical-pod-autoscaler/pkg/recommender/model/vpa.go
- vertical-pod-autoscaler/pkg/recommender/model/vpa_test.go
I saw VPA failing in that MarkNotAutoscaled because it was accessing nil.I think it's when it tires to clean up aggregation from key for which there is no aggregation yet.
> Don't attempt to delete aggregation from VPA if it doesn't exist

- hack/for-go-proj.sh
cluster-autoscaler switched from godeps to go mod, resulting in this
script being broken. This should fix #2251.
> Fix the script used by CI to run unit tests after go mod changes

- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
This way we don't have to specify all the versions we are interested in.
Versioning is then controlled only at the crd level.
> Look at all versions of VPA objects.

- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
This way we don't have to specify all the versions we are interested in.
Versioning is then controlled only at the crd level.
> Look at all versions of VPA objects. [cherry-pick of #2261]

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Resolve #2161 
When CA scales down node, node is still in cache. aws manager return `nil, nil` for node doesn't belong to existing node group. 
@jaypipes
> Return error if aws fail to find nodegroup for node

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
I propose having the > 50 asgs code in the 1.12 release which I'm copying from master
> CA 1.12: cherry pick of #1261

- cluster-autoscaler/README.md
This was mentioned in the sig-autoscaling slack.
Maybe some others need adding as well?
> Add magnum to list of supported cloud providers

- cluster-autoscaler/utils/backoff/exponential_backoff.go
- cluster-autoscaler/utils/backoff/exponential_backoff_test.go
PR addresses issue raised in https://github.com/kubernetes/autoscaler/issues/2225.
Backoff duration was not being exponentially increased for cases where the node group was already in a backoff state, instead setting the duration to the initial default duration. This could cause the cluster autoscaler to be in a locked state, where the scale-down-after-scale-up cooldown would always be greater than the duration between scale up attempts. So as scale-up attempts successively failed within the window of cooldown, no scale down could take place. 
The solution is to not set `duration=initialDuration` if `found=true`, instead setting it to the existing`backoffInfo.duration`, which allows for the duration to increase beyond initial.
> fix: increase exponential backoff duration regardless of backoff status

- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/processors/status/eventing_scale_up_processor.go
- cluster-autoscaler/processors/status/eventing_scale_up_processor_test.go
Previously, it had info only about the ones that actually exist.
The changes to the eventing processor are done to keep its previous
behavior the same.
> Provide ScaleUpStatusProcessor with info about all rejected node groups

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/clusterstate/utils/node_instances_cache.go
- cluster-autoscaler/core/static_autoscaler.go
This is a direct continuation of the https://github.com/kubernetes/autoscaler/pull/2008 PR. I had to switch the source repo.
Please read the PR linked above to get the full context and history. From the last state in that PR I did the changes mentioned by @losipiuk and @gjtempleton.
Please also note, that I no longer have easy access to a spot based EKS cluster on AWS. @seh would you be so kind as to test it?
> correctly handle lack of capacity of AWS spot ASGs

- vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
- vertical-pod-autoscaler/pkg/recommender/input/history/history_provider_test.go
Currently, VPA Recommender uses `container_memory_usage_bytes` cAdvisor metric from Prometheus history provider.
This metric includes page cache into container memory usage total.
As a result, cache-heavy workloads keep getting larger and larger memory recommendation.
This change takes memory held for page cache out of VPA's calculation removing the primary driver behind memory over-requesting.
A similar suggestion was mentioned twice ([[1]](https://github.com/kubernetes/autoscaler/issues/1551#issuecomment-456386360), [[2]](https://github.com/kubernetes/autoscaler/pull/1613#issuecomment-458918134)), but no PRs / issues were raised to discuss it.
This change harmonizes the metric which VPA Recommender Prometheus history provider uses with that of …
> VPA Recommender: Use WSS from Prometheus provider

- cluster-autoscaler/Makefile
Fixes #2239 
Linker flags are moved to their own variable `LDFLAGS`, and `LDFLAGS_FLAG` is constructed to pass to `go build`.
Default is `-s` as intended with the original change. Also works with multiple flags:
```
$ LDFLAGS="-s -w" make build-binary 
rm -f cluster-autoscaler
CGO_ENABLED=0 GOOS=linux go build -o cluster-autoscaler --ldflags "-s -w"
```
```
$ LDFLAGS="-s -w" make build-in-docker
.....
.....
docker run -v `pwd`:/gopath/src/k8s.io/autoscaler/cluster-autoscaler/ autoscaling-builder:latest bash -c 'cd /gopath/src/k8s.io/autoscaler/cluster-autoscaler && BUILD_TAGS= LDFLAGS="-s -w" make build-binary'
rm -f cluster-autoscaler
CGO_ENABLED=0 GOOS=linux go build -o cluster-autoscaler --ldflags "-s -w"
```
> Fix linker flags in CA Makefile

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
Signed-off-by: Masaki Muranaka <monaka@monami-ya.com>
fixes #2236.
> [CA][Azure] Ignore nodes that have no ProviderID. (kubernetes#2236)

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/cloudprovider/aws/ec2.go
Fix issue that user can not build instance type using MixedInstanceType. 
https://github.com/kubernetes/autoscaler/issues/2246
@jaypipes
> Add MixedInstancesPolicy struct to better handle instance type

- cluster-autoscaler/metrics/metrics.go
The purpose of this metric is to provide quantiles directly in the exporter.
As the cluster autoscaler is leader election based, there is only one instance reporting these quantiles at a time so we have a limited risk of aggregating this aggregation.
> cluster-autoscaler/metrics: add a summary for function duration

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/core/static_autoscaler.go
#2235 - Correctly handle lack of capacity of AWS spot ASGs.
Changes `klog` statements from original PR to `glog` as it's still the logging solution in 1.12.
> CA 1.12: cherry pick of #2235

- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/main.go
> Stop disabling Cluster Autoscaler when there is no ready nodes.

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go
The current comparator expects memory capacity values to be identical.
However across AWS, Azure and GCP I quite often see very small
differences in capacity, typically 8-16Ki. When this occurs the
nodegroups are considered not equal when balancing is in effect which
is unfortunate because, in reality, they are identical.
This change will now tolerate a 128Ki difference before memory
capacity values are considered unequal.
> compare_nodegroups: Tolerate small differences in memory capacity

- cluster-autoscaler/cloudprovider/packet/README.md
The token must be base64 encoded, otherwise provisioning fails with a
message like:
invalid header field value "BROKEN_ENCODED_MESSSAGE" for key X-Auth-Token
> cloudprovider/packet: clarify encoding of API token in README

- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_manager.go
- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_manager_test.go
- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_node_group.go
- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_node_group_test.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/CHANGELOG.md
- cluster-autoscaler/cloudprovider/digitalocean/godo/README.md
- cluster-autoscaler/cloudprovider/digitalocean/godo/databases.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/databases_test.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/firewalls_test.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/godo.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/godo_test.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/kubernetes.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/kubernetes_test.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/load_balancers_test.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/util/droplet.go
- cluster-autoscaler/cloudprovider/digitalocean/godo/util/droplet_test.go
Previously this was implemented to use tags to maintain the autoscale config/state (enabled, min, max). This PR switches it to use the proper DO API for managing this config.
> Use DO node pool autoscale API integration

- cluster-autoscaler/hack/update-vendor.sh
Running this script as-is fails as `git ci` is not a recognised
command. Fixed by referencing `git commit` explicitly; I guess it
works form some people as it may be aliased.
> cluster-autoscaler/hack/update-vendor.sh: fix invocation of git commit

- cluster-autoscaler/cloudprovider/azure/azure_instance_types.go
PR adds an instance type to the `azure_instance_type.go` map to potentially solve #2327
> feat: add NV6Promo instance type to CA

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Deleting a placeholder instance introduced in https://github.com/kubernetes/autoscaler/pull/2235 seems to decrease the in-memory ASG size twice, once in the deletion loop itself and once in `decreaseAsgSizeByOneNoLock`, which calls `setAsgSizeNoLock` and also updates the `curSize`
This is actually not causing issues yet, as the ASG cache is force refreshed after a deletion now https://github.com/kubernetes/autoscaler/blob/c3c9fc153c663089c1b02bcd3e788b46a9762d1f/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L283-L284.
I still added a test to confirm that deleting placeholders actually works as expected.
//cc @piontec
> AWS: Decrease current size only once

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Revert "Return error if aws fail to find nodegroup for node" (from #2247)
This reverts commit f65e47a4c4b207625f67cc20ad56971d876a2e71.
The cluster autoscaler periodically looks for associations between Kubernetes node objects and cloud provider-known records for instances in node groups managed by the autoscaler. When the autoscaler considers a Kubernetes node that is not a member of any of these managed node groups, the cloud provider has no such record in its cache. When some callers assumed that these queries would yield either a node or an error, an earlier fix reported this lack of a cached record as an error. However, callers responding to such an error caused the autoscaler to forgo most of its usual pod maintenance responsibilities.
At this point, these callers now expect that …
> Don't treat lack of queried Kubernetes node in AWS cloud provider cache as error

- cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
Increase default GCE operation wait timeout to 20s.
> Increase default GCE operation wait timeout to 20s

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/clusterstate/utils/node_instances_cache.go
- cluster-autoscaler/core/static_autoscaler.go
#2235 - Correctly handle lack of capacity of AWS spot ASGs
Follow up to the Cherry-picks into 1.12 - 1.14 performed by #2289 #2290 and #2291 - managed to miss 1.15 somehow at the time.
> CA 1.15: Cherry-pick of #2235

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Cherry-pick of #2296: AWS: Decrease current size only once
Think it's only worth cherry-picking back as far as this, as due to the forced resync mentioned in the original PR it's not actually causing issues in the behaviour.
> CA 1.13 #2296 Cherry-pick

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Revert "Return error if aws fail to find nodegroup for node"
This reverts commit f65e47a4c4b207625f67cc20ad56971d876a2e71.
The cluster autoscaler periodically looks for associations between
Kubernetes node objects and cloud provider-known records for instances
in node groups managed by the autoscaler. When the autoscaler
considers a Kubernetes node that is not a member of any of these
managed node groups, the cloud provider has no such record in its
cache. When some callers assumed that these queries would yield either
a node or an error, an earlier fix reported this lack of a cached
record as an error. However, callers responding to such an error
caused the autoscaler to forgo most of its usual pod maintenance
responsibilities.
At this point, these callers now expect that the query can …
> Don't treat lack of queried node in cache as error (cherry-pick to 1.16)

- vertical-pod-autoscaler/deploy/vpa-rbac.yaml
- vertical-pod-autoscaler/hack/vpa-down.sh
- vertical-pod-autoscaler/hack/warn-obsolete-vpa-objects.sh
As discussed in #2334, this PR rename the ambiguous clusterrole (also the clusterrolebinding's name).
> rename clusterrole system:admission-controller to system:vpa-admission-controller

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Resolves #2378
Pulls in the `placeholderInstanceNamePrefix` to allow for arbitrary naming of ASGs
> Bugfix - Allow arbitrary placeholder AWS instance names

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Cherry pick of #2379 to CA 1.16 release branch
> CA 1.16 Cherry-Pick - Bugfix - Allow arbitrary placeholder AWS instance names

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Cherry pick of #2379 to CA 1.15 release branch
> CA 1.15 Cherry-Pick - Bugfix - Allow arbitrary placeholder AWS instance names

- vertical-pod-autoscaler/pkg/admission-controller/config.go
This closes #2278.
I believe that there are no SideEffects of the `vpa.k8s.io` controller, so I am setting that explicitly, instead of taking the default of `None`.
> Explicitly set SideEffects=None for mutating webhook

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups_test.go
The LaunchTemplateSpecification.Version is a pointer to
string. When the pointer is nil, EC2 AutoScaling API considers the value
to be "$Default", however aws.StringValue(ltSpec.Version) will return an
empty string (which is not considered the same as "$Default" or a nil
string pointer. So, in order to not pass an empty string as the version
for the launch template when we communicate with the EC2 AutoScaling API
using the information in the launchTemplate, we store the string
"$Default" when the ltSpec.Version is a nil pointer.
Fixes #1728
> ensure valid AWS LaunchTemplate version

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Cherry pick of #2379 into 1.13 release branch
Not sure if we're cherry-picking back this far any more so feel free to close if not.
> CA 1.13 Cherry-Pick - Bugfix - Allow arbitrary placeholder AWS instance names

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Cherry-pick of #2379 to CA 1.14 release branch
> CA 1.14 Cherry-Pick - Bugfix - Allow arbitrary placeholder AWS instance names

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
For kops-built clusters, an instance label added by that tooling will prevent the balance-similar-nodegroups feature from working as intended.
This patch simply adds the kops instance group label to the ignored list.
It looks like this should apply cleanly as far back as the release 1.13 branch, and I have a PR for the 1.12 branch ready to make as well since it's still in common use. (And in fact the most recent version released for kops)
Signed-off-by: Joe Hohertz <joe@viafoura.com>
> add kops instance group label to ignore list for similar node group identification.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
Add the functionality to the Azure cloud provider to enable scaling up and down from 0 with tainted and labeled VMSS
Closes #1452 
Closes #1748
> Allow Azure VMSS to scale from 0 with taints and labels

- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/utils.go
- cluster-autoscaler/core/utils_test.go
Fixes #2386 
The node instances cache is invalidated for node groups which delete failed/unregistered nodes, to prevent the nodes being deleted multiple times if the cache is not refreshed.
The cache is invalidated even if `DeleteNodes` returns an error.
The only call to `DeleteNodes` other than the two covered here is the one for an actual scale down. I haven't seen any issues with this when removing proper nodes, so I didn't change anything in that code.
Since the set of nodes to be deleted is fetched before the start of the delete loops, this shouldn't ever cause the cache to be refreshed immediately after each iteration of the node deletion loop. It should wait until the next CA main loop.
> CA: Invalidate node instances cache after deleting failed/unregistered nodes

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Just added newly created AWS g4dn EC2 instances type on EC2 catalog
> Add g4dn instance type for AWS

- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
Fixes #2324 
Because of the scheduler changes introduced in #2305 we need this permission.
> Update RBAC in examples to include csinodes permission

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
add kops/eksctl instance group label to ignore list for similar node group identification.
Signed-off-by: Joe Hohertz <joe@viafoura.com>
> backport of PR #2207 to 1.15

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
add kops/eksctl instance group label to ignore list for similar node group identification.
Signed-off-by: Joe Hohertz <joe@viafoura.com>
> backport of PR #2207 to 1.14

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
add kops/eksctl instance group label to ignore list for similar node group identification.
Signed-off-by: Joe Hohertz <joe@viafoura.com>
> backport of PR #2207 to 1.13

- builder/Dockerfile
More context:
https://groups.google.com/forum/m/#!topic/kubernetes-security-announce/wlHLHit1BqA
> Bump go to 1.12.10 to mitigate security issues

- builder/Dockerfile
More context:
https://groups.google.com/forum/m/#!topic/kubernetes-security-announce/wlHLHit1BqA
> Bump go to 1.11.13 to mitigate security issues

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
`session.New` is deprecated and requires the `AWS_SDK_LOAD_CONFIG`
environment variable to be set in order to automatically call
`AssumeRoleWithWebIdentity` when `AWS_WEB_IDENTITY_TOKEN_FILE` is set
(which is not documented and most likely unintended).
> AWS – use `session.NewSession` instead of `session.New` to

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
#2385 Ensure valid AWS LaunchTemplate version
#2401 Add g4dn instance type for AWS
#2428 AWS – use `session.NewSession` instead of `session.New` to
> Cherry pick  #2385 #2401 #2428 to 1.16

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
#2385 Ensure valid AWS LaunchTemplate version
#2401 Add g4dn instance type for AWS
#2428 AWS – use `session.NewSession` instead of `session.New` to
> Cherry pick #2385 #2401 #2428 to 1.15

- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
#2385 Ensure valid AWS LaunchTemplate version
#2401 Add g4dn instance type for AWS
#2428 AWS – use session.NewSession instead of session.New to
> Cherry pick #2385 #2401 #2428 to 1.14

- cluster-autoscaler/expander/priority/readme.md
This contains a few updates to the priority expander docs:
- Document random fallback behavior if no priority specs match.
- Document group skipping behavior when group name doesn't match any priorities.
- Use the `kube-system` namespace in the ConfigMap example.
> priority expander: Documentation updates

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/cloudprovider/aws/aws_util.go
- cluster-autoscaler/cloudprovider/aws/aws_util_test.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/main.go
https://github.com/kubernetes/autoscaler/issues/2240
We have some discussion here. https://github.com/kubernetes/autoscaler/pull/2231
Consider the case not all k8s clusters has network to aws pricing API, I still keep the static instance type list. If network is not accessible, it will fall back to static dict. 
dynamic loading will reuse code snippet from gen.go
I am trying reach out to folks who worked on this, not sure if we have any internal IP like EC2 metadata service. If so, we can use that and assume it can always get updated list in the same network. 
@jaypipes
> Generate EC2 Instance Type list in runtime

- cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment-master.yaml
- cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment.yaml
We're now building the cluster autoscaler binary with the build tag for just the magnum provider as part of our CI, and pushing to dockerhub/openstackmagnum [1].
The example deployments no longer need to use the image from my personal dockerhub.
[1] https://review.opendev.org/#/c/688648/
> Update magnum example deployment with image built by magnum CI

- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_node_group.go
- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_node_group_test.go
Fixes `size increase is too large` issue when `targetSize == n.MaxSize()`, where we were incorrectly checking for `targetSize >= n.MaxSize()` instead of `targetSize > n.MaxSize()`.
@timoreimann @andrewsykim
> doks: fix max size check, support increase to max

- cluster-autoscaler/cloudprovider/aws/README.md
A few minor fixes for the AWS cloud provider documentation:
* corrects a mistake in where the mixed instance policy example section appears
* rework the docs around IAM policy to simplify and clean it up
> [aws] minor documentation fixes

- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-containerservice.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-master.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml
- cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml
This PR fixes the Azure examples to include csinodes permission - same as what #2404 did for AWS. The issued faced is as follows:
Component: cluster-autoscaler
Version: v1.16.1
Upon deploying cluster-autoscaler in Azure, I started receiving these errors every second: 
`E1025 08:23:39.529366       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: csinodes.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "csinodes" in API group "storage.k8s.io" at the cluster scope`
Include `csinodes` in the list of resources under apiGroup `storage.k8s.io` of ClusterRole `cluster-autoscaler`:
```yaml
- apiGroups: ["storage.k8s.io"]
resources: ["storageclasses", "csinodes"]
```
PR #2404 fixed the …
> Update RBAC in Azure examples to include csinodes permission

- vertical-pod-autoscaler/pkg/updater/logic/updater.go
- vertical-pod-autoscaler/pkg/updater/logic/updater_test.go
- vertical-pod-autoscaler/pkg/updater/main.go
This patch adds a rate limiter to the vertical pod autoscaler updater.
It adds two flags
- eviction-rate-limit to control the number of pods that can be evicted
every seconds.
- eviction-rate-limit-burst to control the burst of that can be evicted
immediately.
fixes #2178
> Add rate limiter to the Vertical Pod autoscaler updater component

- cluster-autoscaler/main.go
- cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
AWS M5 instance types may differ in memory capacity by more than 128MB.
Whitelist additional node labels for AWS CNI custom networking and
EC2 lifecycle.
As I documented in https://github.com/kubernetes/autoscaler/issues/2020, the m5 instance type memory varies by more that 128MB .  I'm not sure what the basis of the max memory capacity difference is.  There are quite a few options if there are good reasons not to touch it.  Perhaps making it modifiable through a command argument.
> Add AWS ignore labels and increase max memory difference.

- cluster-autoscaler/clusterstate/clusterstate.go
Calling cloudprovider.NodeGroupForNode(unregistered.Node) can result
in a nil result for the nodegroup - handle that case.
> cherry-pick 2096 to 1.15 - Fix SEGV in updateReadinessStats

- cluster-autoscaler/core/scale_down.go
In the error branch below it simply prints the namespace/name of the pod.
If there's a good reason to log the actual returned pod I can put it back in as well. At the very least since the returned object could be nil in this branch, the namespace/name of the pod should also be logged.
> CA: Make error message in scale down node draining consistent

- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/cluster_test.go
- cluster-autoscaler/simulator/drain.go
- cluster-autoscaler/simulator/nodes.go
- cluster-autoscaler/simulator/nodes_test.go
- cluster-autoscaler/utils/drain/drain.go
- cluster-autoscaler/utils/drain/drain_test.go
- cluster-autoscaler/utils/pod/pod.go
- cluster-autoscaler/utils/pod/pod_test.go
Fixes: #2453
* Create `utils/pod` package: pod kind detection functions.
* Update DaemonSet Pod detection logic: introduce the annotation
`cluster-autoscaler.kubernetes.io/daemonset-pod` to declare a Pod as a
DaemonSet Pod.
* Update `simulator` package to use the new `utils/pod` package functions.
* Cleanup `getRequiredPodsForNode()` function.
Signed-off-by: cedric lamoriniere <cedric.lamoriniere@datadoghq.com>
> [cluster-autoscaler] Allow “custom” DaemonSet pods

- cluster-autoscaler/cloudprovider/aws/README.md
- Fix the link to ASG allocation strategies in AWS CA README.
> Doc: fix the Allocation Strategies link in AWS CA README

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Previously, the cloud provider called Get to obtain the status for each node pool.  When running with a large number of node pools, e.g. 10+, these will cause Azure to throttle, not only the autoscaler, but all services operating under the same identity.
This commit replaces the Get call for each node pool with a List call which obtains the status for all the node pools at once.  The frequency of these calls is set with the vmssSizeRefreshPeriod constant.
> Improve performance of the Azure cloud provider

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This cherry picks a PR that improves the performance of the azure provider for the cluster autoscaler.
> This commit improves the performance of the azure cloud provider.

- cluster-autoscaler/README.md
`| 1.16.X | 1.16.X  |`
added to the compatibility chart in the readme. 
is my assumption correct?
> updated cluster-autoscaler readme - compatibility chart

- cluster-autoscaler/clusterstate/clusterstate.go
- cluster-autoscaler/clusterstate/clusterstate_test.go
Currently, GetClusterSize reports the target number for all autoscaled
node groups, but the actual number for _all_ node groups, even those
that are not autoscaled. This commit fixes that behavior so that both
target and actual size reported are from autoscaled node groups only.
> CSR: fix a bug in GetClusterSize

- cluster-autoscaler/cloudprovider/azure/azure_util.go
When using Managed Identity we still need to validate other parameters, instead of just returning. So I moved the deployment validation upwards.
> Validate all parameters even when using managed identity

- cluster-autoscaler/cloudprovider/azure/azure_util.go
Use the one specified in the cluster-autoscaler package instead of client-go.
Fixes #2213
> fix: cluster-autoscaler version in Azure autorest user agent

- cluster-autoscaler/simulator/predicates.go
By default scheduler now returns plugins instead of predicates.
However, plugins are not yet supported by CA, so we need to make
scheduler return predicates.
> Fix a bug in initializing scheduler

- cluster-autoscaler/hack/update-vendor.sh
The `git restore` command was introduced in Git version 2.23.0, which
was released in August 2019. Even late Linux distributions do not
include this modern of a Git binary. For example, Ubuntu 19.10 as of Nov
26, 2019 only includes Git 2.20.1.
In order to run hack/update-vendor.sh on machines with Git <2.23.0, I've
modified the script to use `git reset .` instead of `git restore
--staged`.
Issue #2560
> Use git reset instead of git restore

- vertical-pod-autoscaler/e2e/v1/e2e_test.go
- vertical-pod-autoscaler/e2e/v1beta2/e2e_test.go
- vertical-pod-autoscaler/hack/run-e2e-tests.sh
Without this change test flags are not registered and this fails with go1.13
Also reinstate the timeout
> Sync e2e_test file with k/k master

- cluster-autoscaler/cloudprovider/azure/azure_util.go
use version from cluster autoscaler package instead of client-go for azure autorest
> Cherry pick #2555 to 1.15: use version from cluster autoscaler package instead of client-go for azure autorest

- cluster-autoscaler/cloudprovider/azure/azure_util.go
use version from cluster autoscaler package instead of client-go for azure autorest
> Cherry pick #2555 to 1.16: use version from cluster autoscaler package instead of client-go for azure autorest

- addon-resizer/nanny/kubernetes_client.go
Switch to using the apps/v1 API for compatibility with 1.16 (works with Kubernetes 1.9+)
cc @wojtek-t
> [addon-resizer 1.8] Switch to apps/v1 deployments APIs

- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/main.go
- cluster-autoscaler/version/version.go
use version from cluster autoscaler package instead of client-go for azure autorest
> Cherry pick #2555 to 1.13: use version from cluster autoscaler package instead of client-go for azure autorest

- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/main.go
- cluster-autoscaler/version/version.go
use version from cluster autoscaler package instead of client-go for azure autorest
> Cherry pick #2555 to 1.14: use version from cluster autoscaler package instead of client-go for azure autorest

- addon-resizer/Makefile
- addon-resizer/nanny/main/pod_nanny.go
- addon-resizer/nanny/version.go
1.8 pick of https://github.com/kubernetes/autoscaler/pull/2577
This adds the tagged version to the build, and includes it in the client user-agent (currently, the user agent appears as pod_nanny/v0.0.0)
> [addon-resizer 1.8] Add version to user agent

- addon-resizer/Makefile
- addon-resizer/main.go
- addon-resizer/nanny/version.go
This adds the tagged version to the build, and includes it in the client user-agent (currently, the user agent appears as `pod_nanny/v0.0.0`)
> Add version to user agent

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
The same way that we don't have to explicitly pass credentials as arguments when using managed identity extension, we could allow people to avoid passing the `subscriptionID` if they don't want to, and fetch it from the instance metadata.
> Read subscription ID from instance metadata

- vertical-pod-autoscaler/e2e/v1/full_vpa.go
- vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go
Using the same deployment kinds in creation deployment function and in waiting for pod function.
This fixes potential type mismatches.
/fixes #2608
> Fixing KindDeployment in full vpa e2e test

- cluster-autoscaler/cloudprovider/azure/README.md
The existing text is not how auto-discovery works, it detects the pre-existing tags for min/max and sets those to the parsed values. This is the same as GCE, while AWS uses ASG scaling policies and respects the external min/max. 
https://github.com/kubernetes/autoscaler/blob/50840bf43f681871465a2a4d3d6eeba9056463c4/cluster-autoscaler/cloudprovider/gce/gce_manager.go#L566-L577
https://github.com/kubernetes/autoscaler/blob/50840bf43f681871465a2a4d3d6eeba9056463c4/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L410-L440
Seems like the text is a copy paste from AWS, it's not correct for azure.
> fix: doc inaccuracy for azure auto-discovery

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
In an earlier PR #1868 I added a memory saver mode which stores only pod info and container metrics for those pods which have a VPA. In later PR some logging was added when container metrics could not be stored regardless of the mode. This causes a lot of false error logs when the memory saver mode is on. So I've added a similar skip condition when the container does not have a matching VPA.
Also there are a couple of places where errors are not logged when the pod and container states cannot be added/updated. So I have added appropriate warnings in those places.
> Improved logging for errors during updating state

- cluster-autoscaler/clusterstate/clusterstate.go
Resolve #2250 
https://github.com/kubernetes/autoscaler/blob/a258103f8ec9c24a333338468fa51262df0ef24a/cluster-autoscaler/clusterstate/clusterstate.go#L307-L326
`csr.getCloudProviderNodeInstances()` is called before `updateAcceptableRanges`  and at that time, acceptable range doesn't have any data, current error message is misleading. 
Please have a check and let me know if it makes sense.
> Skip acceptable range check before it has data

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
In Issue #2285, there are log lines demonstrating that the
`AwsRefFromProviderId()` function in the AWS cloud provider was
returning an error from the provider ID string:
```
W0829 14:14:00.250136       1 utils.go:494] Failed to get node group for aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14: wrong id: expected format aws:///<zone>/<name>, got aws:///eu-central-1c/i-placeholder-K3-EKS-spotr5xlasgsubnet02af43b02922e710f-10QH9H0C8PG7O-14
```
So I've added a unit test that uses this exact value and verifies that
the AwsRefFromProviderId function indeed returns the
appropriately-filled-in AwsInstanceRef object correctly.
> add unit tests validating AwsRefFromProviderId

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Fix: https://github.com/kubernetes/autoscaler/issues/2594 
Fix: https://github.com/kubernetes/autoscaler/issues/2538
Fix: https://github.com/kubernetes/autoscaler/issues/2620
Fix Azure VMSS scale down issues when updating target sizes.
The root cause of the bug is because of the wrong logic of asg cache. In the current version of code, the vmss.FindForInstance checks if the input node is in the cache. However, there's a time when a node has been created while the corresponding VMSS instance hasn't. This will lead to the node being put in `asgCache.notInRegisteredAsg` and thus returns early before the cache is refreshed. After passing the `MaxCloudProviderNodeDeletionTime` and `MaxNodeProvisionTime`, the error of wrong `delta` appears because the readiness count will be smaller that the …
> Fix Azure VMSS scale down issues when updating target sizes.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
The root cause of the bug is because of the wrong logic of asg cache. In the current version of code, the vmss.FindForInstance checks if the input node is in the cache. However, there's a time when a node has been created while the corresponding VMSS instance hasn't. This will lead to the node being put in `asgCache.notInRegisteredAsg` and thus returns early before the cache is refreshed. After passing the `MaxCloudProviderNodeDeletionTime` and `MaxNodeProvisionTime`, the error of wrong `delta` appears because the readiness count will be smaller that the current size.
In the revised code, the node won't be put into the asgCache.notInRegisteredAsg and the refresh operation will be performed, ensuring the cache is up-to-date and the readiness count is good.
> Cherry pick #2613 to 1.15: Fix Azure VMSS scale down issues when updating target sizes.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
The root cause of the bug is because of the wrong logic of asg cache. In the current version of code, the vmss.FindForInstance checks if the input node is in the cache. However, there's a time when a node has been created while the corresponding VMSS instance hasn't. This will lead to the node being put in `asgCache.notInRegisteredAsg` and thus returns early before the cache is refreshed. After passing the `MaxCloudProviderNodeDeletionTime` and `MaxNodeProvisionTime`, the error of wrong `delta` appears because the readiness count will be smaller that the current size.
In the revised code, the node won't be put into the asgCache.notInRegisteredAsg and the refresh operation will be performed, ensuring the cache is up-to-date and the readiness count is good.
> Cherry pick #2613 to 1.14: Fix Azure VMSS scale down issues when updating target sizes.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
The root cause of the bug is because of the wrong logic of asg cache. In the current version of code, the vmss.FindForInstance checks if the input node is in the cache. However, there's a time when a node has been created while the corresponding VMSS instance hasn't. This will lead to the node being put in `asgCache.notInRegisteredAsg` and thus returns early before the cache is refreshed. After passing the `MaxCloudProviderNodeDeletionTime` and `MaxNodeProvisionTime`, the error of wrong `delta` appears because the readiness count will be smaller that the current size.
In the revised code, the node won't be put into the asgCache.notInRegisteredAsg and the refresh operation will be performed, ensuring the cache is up-to-date and the readiness count is good.
> Cherry pick #2613 to 1.17: Fix Azure VMSS scale down issues when updating target sizes.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
The root cause of the bug is because of the wrong logic of asg cache. In the current version of code, the vmss.FindForInstance checks if the input node is in the cache. However, there's a time when a node has been created while the corresponding VMSS instance hasn't. This will lead to the node being put in `asgCache.notInRegisteredAsg` and thus returns early before the cache is refreshed. After passing the `MaxCloudProviderNodeDeletionTime` and `MaxNodeProvisionTime`, the error of wrong `delta` appears because the readiness count will be smaller that the current size.
In the revised code, the node won't be put into the asgCache.notInRegisteredAsg and the refresh operation will be performed, ensuring the cache is up-to-date and the readiness count is good.
> Cherry pick #2613 to 1.16: Fix Azure VMSS scale down issues when updating target sizes.

- addon-resizer/nanny/main/pod_nanny.go
- addon-resizer/nanny/nanny_lib.go
- addon-resizer/nanny/nanny_lib_test.go
> Add support for scale up/down delay

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
> fix: properly parse azure cloud provider config

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
> Cherry pick #2661 to 1.15: fix: properly parse azure cloud provider config #2662

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
> Cherry pick #2661 to 1.16: fix: properly parse azure cloud provider config #2662

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
> Cherry pick #2661 to 1.14: fix: properly parse azure cloud provider config

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
> Cherry pick #2661 to 1.17: fix: properly parse azure cloud provider config #2662

- cluster-autoscaler/cloudprovider/azure/azure_util.go
> fix: add missing prefix in azure user-agent

- vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
Considering that this has never been reported it might have never been used. We can safely change the name given the project is still in beta and the updater will crash with unknown flag and not just silently ignore the name. Also the `misspell` spell checker used in this project seems to be an abandoned project now :(
> Fix typo in flag for OOM threshold

- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> Fix panic when the vmss doesn't exist

- cluster-autoscaler/cloudprovider/azure/azure_util.go
> Cherry pick #2671 to 1.16: fix: add missing prefix in azure user-agent

- cluster-autoscaler/cloudprovider/azure/azure_util.go
> Cherry pick #2671 to 1.17: fix: add missing prefix in azure user-agent

- cluster-autoscaler/cloudprovider/azure/azure_util.go
> Cherry pick #2671 to 1.15: fix: add missing prefix in azure user-agent

- cluster-autoscaler/cloudprovider/azure/azure_util.go
> Cherry pick #2671 to 1.14: fix: add missing prefix in azure user-agent

- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> Cherry pick #2674 to 1.14: Fix panic when the vmss doesn't exist

- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> Cherry pick #2674 to 1.15: Fix panic when the vmss doesn't exist

- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> Cherry pick #2674 to 1.17: Fix panic when the vmss doesn't exist

- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> Cherry pick #2674 to 1.16: Fix panic when the vmss doesn't exist

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
> Provider/Azure: Add VM cache.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
> Cherry pick of #2683 to 1.14: Add VM cache.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
> Cherry pick of #2683 to 1.15: Add VM cache.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
> Cherry pick of #2683 to 1.16: Add VM cache.

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
> Cherry pick of #2683 to 1.17: Add VM cache.

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_agent_pool_test.go
- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
Fixes: #2154 
To prevent the potential `DeploymentQuotaExceeded` error, we keep the latest 10 cluster autoscaler deployments and delete others.
/kind bug
> Delete outdated deployments.

- cluster-autoscaler/core/static_autoscaler.go
Just remove one duplicate comments !
// Removes unregistered nodes if needed. Returns true if anything was removed and error if such occurred.
> Remove duplicate comments

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Mostly important due to existing Memory figures for some C5d instances being incorrect.
Despite the ability for the CA to dynamically generate this list added by #2240 users can still use this list and the memory figures for some of the C5d family currently are incorrect. These new generated figures match the published figures: https://aws.amazon.com/ec2/instance-types/c5/
This also pulls in the figures for the new super high memory instances: https://aws.amazon.com/blogs/aws/ec2-high-memory-update-new-18-tb-and-24-tb-instances/
> CA: Update AWS instance type list

- vertical-pod-autoscaler/hack/update-kubernetes-deps-in-e2e.sh
The `set` in `hack/update-kubernetes-deps-in-e2e.sh` contains redundant options:
* `errexit` equals `-e`
* `nounset` equals `-u`
Also, I have misunderstood how to correctly set options in https://github.com/kubernetes/autoscaler/pull/2531, the `-o` can take only one argument and `pipefail` doesn't have short variant so it has to remain long.
Resource: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
ptal @bskiba
> VPA: fix bash set options

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
Cherry pick #2699 to 1.17: dont return error for nodes without providerId
/kind bug
> Cherry pick #2699 to 1.17: dont return error for nodes without providerId

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
Cherry pick #2699 to 1.15: dont return error for nodes without providerId
/kind bug
> Cherry pick #2699 to 1.15: dont return error for nodes without providerId

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
Cherry pick #2699 to 1.16: dont return error for nodes without providerId
/kind bug
> Cherry pick #2699 to 1.16: dont return error for nodes without providerId

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
Cherry pick #2699 to 1.14: dont return error for nodes without providerId
/kind bug
> Cherry pick #2699 to 1.14: dont return error for nodes without providerId

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
- vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go
- vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go
- vertical-pod-autoscaler/vendor/k8s.io/client-go/scale/fake/client.go
- vertical-pod-autoscaler/vendor/modules.txt
Not all CRDs implement scale sub resource.
Previous logic lead to VPA failing with top-level resource which did not implement scale subresource.
This change ensures that we are walking up the controllers' chain to the last valid (i. e. well-known or scalable) controller.
Resolves #2159.
> VPA: find topmost well-known or scalable controller

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
This PR adds Azure user assigned identity support to cluster-autoscaler.
/kind feature
> Support Azure user assigned identity

- cluster-autoscaler/FAQ.md
Adds a quick stanza on overriding the node skipping behaviour for local storage and kube-system pods.
Also adds these flags to the table of CLI flags for the CA as they were previously missing.
> CA: Add Simulator related flags to FAQ

- cluster-autoscaler/FAQ.md
kubectl requires to use a ':' (colon) character to separate keys from values.
> Use correct key/value separator in kubectl PDB create command

- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go
Adding vpa observed containers to pods handled by Admission Controller.
ref #2726
> Vpa - Observed containers admission controller annotation

- cluster-autoscaler/core/utils/utils.go
- cluster-autoscaler/core/utils/utils_test.go
This is the same functionality as what you get with --ignore-taint
flag, but it doesn't require updating CA config to add a new taint
to ignore.
> Remove taints with specific prefix from template node

- vertical-pod-autoscaler/pkg/utils/annotations/vpa_observed_containers.go
- vertical-pod-autoscaler/pkg/utils/annotations/vpa_observed_containers_test.go
Empty string should be a correct case of VpaObservedContainers annotation.
> VPA - Handling empty vpa observed containers annotation

- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
`FindForInstance` is called every autoscaler loop (default 10s). In the case of a large volume scale down, you end up with a bunch of nodes in `NotReady` state until they get cleaned up by cloud-provider. This would lead to several cache misses and a call to `asgCache. regenerate()` which could possibly lead to a VMSS List for every registered node group. This would be multiplied by the number of not ready nodes (cache misses) in the worst case, O(numberOfNodes). This should be O(numberOfVmss).
Move the cache regeneration to `forceRefresh()` which gets called at the start of the autoscaler loop so that the virtual machine details get fetched with one List call for every VMSS. The frequency is now once per VMSS/registered ASG, instead of the node multiplier. This would match the …
> Decrease the number of calls to VMSS API

- cluster-autoscaler/cloudprovider/gce/templates.go
Side note: we really should improve our error handling - this bug
completely crashes CA if at least a single node group is at 0 nodes.
> Fix a bug in GCE scale-from-0 template construction

- cluster-autoscaler/core/equivalence_groups.go
- cluster-autoscaler/core/equivalence_groups_test.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/utils/pod_schedulable.go
- cluster-autoscaler/core/utils/pod_schedulable_test.go
- cluster-autoscaler/core/utils/utils.go
Minor refactor to separate pod equivalence computation from running predicates.
Possible TODO for improving messages in events: pass equivalence groups to scale up status processor, rather than build a full NoScaleUpInfo per pod.
> Simplify building equivalence groups in scale up

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
EKS now supports pods running on Fargate. The providerID has a different format:
"aws:///eu-west-1b/120328e333-369fe1b7ba8b4416ab87216be91dc4f1/fargate-ip-192-168-159-181.eu-west-1.compute.internal"
I just adapted the regex to match both patterns. Without this, the autoscaler will not work if you have one node (one pod) running on Fargate.
Issue: https://github.com/kubernetes/autoscaler/issues/2637
> Change the regex to match the providerID used by Fargate on EKS.

- vertical-pod-autoscaler/pkg/utils/status/status_object.go
- vertical-pod-autoscaler/pkg/utils/status/status_object_test.go
Adding component status implementation based on Leases.
> Vpa - Component status

- vertical-pod-autoscaler/deploy/vpa-rbac.yaml
- vertical-pod-autoscaler/pkg/admission-controller/logic/status_updater.go
- vertical-pod-autoscaler/pkg/admission-controller/main.go
Adding status object (Lease) to Admission Controller.
Adding rbac entries for Leases manipulation.
ref #2738
> VPA -  Adding status to Admission Controller

- vertical-pod-autoscaler/pkg/updater/logic/updater.go
Simplifying `ObserveTotal` logic. It will be called always when existing Updater's `RunOnce` method.
> VPA - Updater timer ObserveTotal cleanup

- cluster-autoscaler/simulator/cluster.go
Previously, the shuffling was biased
> Uniformize node shuffling when finding nodes to remove

- vertical-pod-autoscaler/deploy/vpa-rbac.yaml
- vertical-pod-autoscaler/pkg/updater/logic/updater.go
- vertical-pod-autoscaler/pkg/updater/logic/updater_test.go
- vertical-pod-autoscaler/pkg/updater/main.go
Update check if there is valid Admission Controller status.
If not, eviction loop will be skipped.
> VPA - Checking Admission Controller status

- cluster-autoscaler/cloudprovider/test/test_cloud_provider.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/scale_up_test.go
- cluster-autoscaler/core/static_autoscaler_test.go
Compute expansion options for additional created groups.
(I'm working on a test that would have caught the bug, TBA in another commit to this PR.)
> Compute expansion options for additional created groups

- vertical-pod-autoscaler/hack/run-e2e-tests.sh
- vertical-pod-autoscaler/hack/run-e2e.sh
Updater e2e tests are part of actuation tests now.
Updater tests should be removed from run-e2e scripts.
> VPA - Removing updater e2e test from scripts

- vertical-pod-autoscaler/pkg/updater/logic/updater_test.go
> VPA - Reducing copy-pasted code in updater tests

- vertical-pod-autoscaler/e2e/go.mod
- vertical-pod-autoscaler/e2e/v1/updater.go
- vertical-pod-autoscaler/e2e/v1beta2/updater.go
- vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/status/status_object.go
- vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/status/status_updater.go
- vertical-pod-autoscaler/e2e/vendor/modules.txt
Adding e2e tests for updater. The tests cover the Updater behavior regarding the Admission Controller status availability.
ref #2738
> VPA - Status e2e test

- vertical-pod-autoscaler/hack/run-e2e-tests.sh
- vertical-pod-autoscaler/hack/run-e2e.sh
Reverts kubernetes/autoscaler#2792
With [status e2e test being added](https://github.com/kubernetes/autoscaler/pull/2808), we need to support updater e2e tests.
> Revert "VPA - Removing updater e2e test from scripts"

- cluster-autoscaler/cloudprovider/cloud_provider.go
`Nodes()` is ambiguous since might cause the impression that is expected to return only the list of instances for the node group which also have a kubernetes node associated already. This tries to clarify that expectation.
> Clarify Nodes() expectation

- vertical-pod-autoscaler/pkg/admission-controller/config.go
- vertical-pod-autoscaler/pkg/admission-controller/main.go
Hello, 
I am currently writing a Helm chart for the vertical pod autoscaler. During development I noticed that the webhook service name for the `WebhookClientConfig` is currently hardcoded to `vpa-webhook`.
As using the alternative webhook url is not recommended for in-cluster components, see https://github.com/kubernetes/api/blob/master/admissionregistration/v1beta1/types.go#L501, this PR adds a cli flag for specifying the service name.
The default value of this cli flag matches the current `vpa-webhook` setting, so this is a non breaking change.
Let me know if you have further questions or recommendations.
Thanks for your help!
> add VPA cli flag for specifying the name of the webhook service

- cluster-autoscaler/core/utils.go
- cluster-autoscaler/simulator/predicates.go
- cluster-autoscaler/simulator/predicates_test.go
Useful for debugging, doesn't change scale-up behavior (except for GKE-specific taint that should be ignored).
> Cherry-pick #2638, #2717, and #2719 to 1.15: Log taint preventing scale-up

- cluster-autoscaler/core/utils.go
- cluster-autoscaler/simulator/predicates.go
- cluster-autoscaler/simulator/predicates_test.go
Useful for debugging, doesn't change scale-up behavior (except for GKE-specific taint that should be ignored).
> Cherry-pick #2638, #2717, and #2719 to 1.16: Log taint preventing scale-up

- cluster-autoscaler/core/utils/taint_key_set.go
- cluster-autoscaler/simulator/predicates.go
- cluster-autoscaler/simulator/predicates_test.go
Useful for debugging, doesn't change scale-up behavior (except for GKE-specific taint that should be ignored).
> Cherry-pick #2638, #2717, and #2719 to 1.17: Log taint preventing scale-up

- cluster-autoscaler/version/version.go
Update Cluster Autoscaler version to 1.17.1.
> Cluster Autoscaler 1.17.1

- cluster-autoscaler/core/filter_out_schedulable.go
- cluster-autoscaler/core/filter_out_schedulable_test.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/simulator/basic_cluster_snapshot.go
- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/cluster_snapshot.go
- cluster-autoscaler/simulator/cluster_snapshot_benchmark_test.go
- cluster-autoscaler/simulator/cluster_snapshot_test.go
- cluster-autoscaler/simulator/delta_cluster_snapshot.go
- cluster-autoscaler/simulator/scheduler_based_predicates_checker.go
- cluster-autoscaler/simulator/test_utils.go
Delta snapshot stores a chain of changes-since-last-fork (although forking more than once is illegal for now, following basic snapshot's implementation). It's optimized for frequent fork-add a bit of stuff-run lots of predicates-revert flow by:
1) copy-on-write - Fork() and Revert() are O(1), at cost of O(n) Commit() and copying NodeInfo objects on some add/remove operations. In the pessimistic case where all the original nodes are modified (e.g. by AddPod()) after Fork(), total copying cost reaches that of basic snapshot's O(n) Fork().
2) caching of frequently obtained lists of all nodes and pods.
> Add delta snapshot implementation

- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
- cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
The cluster-autoscaler-autodiscover YAML file in the AWS cloud provider
examples referenced a very old image for CAS. This simply updates the
image to the latest supported version on EKS, which is 1.14.7.
Ref: awsdocs/amazon-eks-user-guide#76
> Update referenced CAS image in aws YAML example

- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Resolves part of #2797 
Updates the AWS-Manager test for Region fetching due to changes in the SDK in how this is done due to aws/aws-sdk-go#2969
> CA - Resolve AWS TestGetRegion failure post 1.18 vendoring

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> Make VMSS info cache TTL configurable

- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
For the unit tests, we create the scale set object directly and not through the `NewScaleSet()` call so we don't populate the size refresh properly and this lead to a flaky test failure.
https://travis-ci.org/kubernetes/autoscaler/jobs/652299234?utm_medium=notification&utm_source=github_status
> fix case that became flaky after scale set refresh interval change

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
The `AZURE_ASG_CACHE_TTL` used in the goroutine was effectively useless because this cache is already invalidated every azure manager loop (1 minute) and the result of invalidation indirectly depends on the decision the `Nodes()` call makes.
- If scaleset or agentpool, the TTL of the instances cache is 5 minutes so the TTL of the ASG cache becomes 5 minutes and you only do an API call every 5 minute.
- If AKS pool, `Nodes()` would return fresh data so your ASG cache TTL is 1 minute.
> Remove unused asg cache TTL

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
> Cherry pick #2842 to 1.16: Make VMSS info cache TTL configurable

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
> Cherry pick #2842 to 1.14: Make VMSS info cache TTL configurable

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
> Cherry pick #2842 to 1.15: Make VMSS info cache TTL configurable

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Without this, the autoscaler were using the labels in `compareLabels` and failing to match similar node groups in different zones. Starting in kube 1.17 `failure-domain.beta.kubernetes.io/*` are deprecated in favour of `topology.kubernetes.io/* ` https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone
> Add topology.kubernetes.io labels to be ignored when comparing similar node groups.

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
> Cherry pick #2842 to 1.17: Make VMSS info cache TTL configurable

- cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go
Adding `eks.amazonaws.com/nodegroup` to the AWS list of ignored labels since it added automatically by AWS and confuse CA.
> Add eks.amazonaws.com/nodegroup label to awsIgnoredLabels

- cluster-autoscaler/core/static_autoscaler.go
Separate PR to avoid drive-by refactors in scheduler framework migration follow-ups.
> Cleanup ifs in static autoscaler

- cluster-autoscaler/main.go
- cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
This PR is about backporting changes from master to 1.16. This is required when using EKS 1.14 with node groups because:
- EKS 1.14 (which is currently the latest version) does not work with CA 1.17
- Sometimes the memory capacity between instances within worker groups can differ quite a lot
- EKS add a label that confused CA 
I was able to test this against a 3 AZs group set which now spread the instances across all AZs.
Finally, I would like to get a new release of 1.16, can you guide me through the process of doing that? (or is it just something that happens by itself periodically?)
> Backporting AWS ignored labels and capacity memory changes to 1.16

- cluster-autoscaler/core/filter_out_schedulable.go
- cluster-autoscaler/simulator/predicates_checker_interface.go
- cluster-autoscaler/simulator/scheduler_based_predicates_checker.go
- cluster-autoscaler/simulator/scheduler_based_predicates_checker_test.go
This parameter is no longer used. 
Follow-up from #2797.
> Don't pass node infos to FitsAnyNode

- cluster-autoscaler/core/static_autoscaler.go
We've always used the same state for scale down, changing it doesn't seem related to scheduler migration.
> Cleanup todo

- hack/for-go-proj.sh
It happens that vpa e2e tests are broken after merging a PR to autoscaler repo.
This PR adds check if e2e tests build.
> VPA - Adding e2e build check

- cluster-autoscaler/core/filter_out_schedulable.go
- cluster-autoscaler/core/filter_out_schedulable_test.go
- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/core/static_autoscaler_test.go
Simpler than filtering them out at every step.
> Filter out expendable pods before initializing snapshot

- cluster-autoscaler/version/version.go
Update Cluster Autoscaler version to 1.18.0-beta.0.
> Cluster Autoscaler 1.18.0-beta.0

- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/scale_test_common.go
Using snapshot, we will no longer always choose the first 10 empty nodes to remove. Fix test to account for it. (This is probably a good thing, there is no reason to remove the oldest nodes first, and in other places we even shuffle nodes explicitly.)
> Allow any subset of nodes to be deleted in test

- vertical-pod-autoscaler/pkg/updater/logic/updater.go
- vertical-pod-autoscaler/pkg/updater/logic/updater_test.go
- vertical-pod-autoscaler/pkg/updater/main.go
- vertical-pod-autoscaler/pkg/updater/priority/priority_processor.go
- vertical-pod-autoscaler/pkg/updater/priority/priority_processor_test.go
- vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
- vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go
- vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
I believe this makes the code both more extensible and infinitely more testable.
- I moved the getPodPriority function to the priorityProcessor.GetPodPriority 1:1 
- I moved the getPodPrioriry tests to priorityProcessor's tests 1:1
- I converted some of the AddPod tests to priorityProcessor's (the ones that were only testing that we are calculating priority correctly and the sorting was actually secondary)
There's still room for improvement in the AddPod tests (hence the TODO to refactor them), but I didn't want to make this review gigantic
> refactor updater for a better structured update priority processing

- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
This PR improve our caching strategy of the launch configuration name to instance type.
It adds a TTL and batch the query to populate this cache.
It happens that users change the instance type of an already running ASG and that become an issue forcing to restart the cluster-autoscaler.
Note that it's also an issue to have nodes compared to a template of nodes but that's an another topic I'd like to open in a dedicated thread.
In a cluster with more than 1300 ASGs, the query to the launch configuration API done one by one become a throttling situation.
Doing that by batching these call by page of 50 elements solved our throttling issue.
> cluster-autoscaler/aws: batch launch config query and ttl cache

- vertical-pod-autoscaler/pkg/admission-controller/Makefile
- vertical-pod-autoscaler/pkg/recommender/Makefile
- vertical-pod-autoscaler/pkg/updater/Makefile
`admission-controller` and `updater` were still using `godep` and they
didn't work. `recommender` tried to run tests with `-race` flag, wich
failed with
`go test: -race requires cgo; enable cgo by setting CGO_ENABLED=1`
> Fix `test-unit` make targets for VPA

- vertical-pod-autoscaler/deploy/vpa-beta-crd.yaml
- vertical-pod-autoscaler/deploy/vpa-beta2-crd.yaml
- vertical-pod-autoscaler/deploy/vpa-crd.yaml
- vertical-pod-autoscaler/deploy/vpa-v1-crd.yaml
Resolves issue #2859 
Make CRDS compliant with OpenAPIV3 so it won't get NonStructuralSchema Validation Error
> Make VPA Crds compliant with OpenAPIV3

- vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go
It seems that order of CPU and unobtanium is somewhat random, which was
causing flaky tests:
fixes #2886
> Fix VPA admission controller server test

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/cluster_test.go
Follow-up from #2797. Small refactors are only in the code already affected by this change.
> Use nodes and pods from snapshot in scale-down

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
Fix the bug of vm cache that multiple agentpools share the same cache.
/kind bug
> Cherry pick of #2908 to 1.14: Provider/Azure: Fix the bug of vm cache that multiple agentpools share the same cache.

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
Fix the bug of vm cache that multiple agentpools share the same cache.
/kind bug
> Cherry pick of #2908 to 1.15: Provider/Azure: Fix the bug of vm cache that multiple agentpools share the same cache.

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
Fix the bug of vm cache that multiple agentpools share the same cache.
/kind bug
> Cherry pick of #2908 to 1.16: Provider/Azure: Fix the bug of vm cache that multiple agentpools share the same cache.

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
Fix the bug of vm cache that multiple agentpools share the same cache.
/kind bug
> Cherry pick of #2908 to 1.17: Provider/Azure: Fix the bug of vm cache that multiple agentpools share the same cache.

- vertical-pod-autoscaler/pkg/admission-controller/logic/pod_resource_handler.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/pod_resource_handler_test.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/resource_handler.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/vpa_resource_handler.go
- vertical-pod-autoscaler/pkg/admission-controller/logic/vpa_resource_handler_test.go
This PR refactors AdmissionController and decouples its core logic from logic responsible for handling resources. Handlers for already supported resources are registered via the new mechanism.
> Add ability to add handlers for new resources to AdmissionController via RegisterHandler()

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_kubernetes_service_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/azure/azure_util_test.go
This PR updates the rest of the azure clients to the latest version in cloud provider azure after https://github.com/kubernetes/autoscaler/pull/2902.
Fixes #2898.
/kind feature
> Provider/Azure: Update vm, storageaccount, interface and disk client.

- cluster-autoscaler/cloudprovider/aws/README.md
Hi,
I experienced some confusion when trying to use the Cluster Autoscaler and so I've tried to document some of the things I ran into to help others in the future.
> Add some more documentation to clarify how labels and GPUs work with the

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
Add the ability to override CAPI group via env variable and discovers the API version.
This change adds detection for an environment variable to specify the group for the clusterapi resources. If the environment variable `CAPI_GROUP` is specified, then it will be used instead of the default. This also decouples the API group from the version and let the latter to be discovered dynamically.
Fixes https://github.com/kubernetes/autoscaler/issues/2932
> Fixes 2932: let the capi version to be discovered

- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/core/scale_test_common.go
- cluster-autoscaler/main.go
- cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/azure_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/azure_nodegroups_test.go
- cluster-autoscaler/processors/nodegroupset/balancing_processor.go
- cluster-autoscaler/processors/nodegroupset/balancing_processor_test.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go
- cluster-autoscaler/processors/nodegroupset/nodegroup_set_processor.go
- cluster-autoscaler/processors/processors.go
Add support for passing custom ignored labels to the node group set comparator. This way end-users can add labels that they would like the autoscaler to ignore when considering two node groups the same for balancing between as a command line option, for example if they have their own readiness labels or other markings that should not affect balancing behaviour.
> Add support for passing custom ignored labels

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
Stop panicking in newMachineController
> CAPI: Stop panicking in newMachineController

- cluster-autoscaler/cloudprovider/gce/templates.go
- cluster-autoscaler/cloudprovider/gce/templates_test.go
CSI drivers use their own topology keys instead of Kubernetes labels, and the corresponding Node and PV.Spec.NodeAffinity will use the CSI labels.
> Add GCE PD CSI zone topology key to node template

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
The following splits the scale-up operation into two parts:
- Synchronous short lived call that returns a future. This allows capturing quota failures and other early failures and properly propagate those tocore autoscaler so that the nodegroup can be backed-off. Otherwise, in the case of quota failures for example, retries will occur in every autoscaler loop leading to throttling.
- Asynchronous part that waits on the future and logs those failures.
> Properly propagate scale-up failures in scale sets

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
The following splits the scale-up operation into two parts:
Synchronous short lived call that returns a future. This allows capturing quota failures and other early failures and properly propagate those tocore autoscaler so that the nodegroup can be backed-off. Otherwise, in the case of quota failures for example, retries will occur in every autoscaler loop leading to throttling.
Asynchronous part that waits on the future and logs those failures.
> Cherry pick #2944 to 1.16: Properly propagate scale-up failures in scale sets

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
The following splits the scale-up operation into two parts:
Synchronous short lived call that returns a future. This allows capturing quota failures and other early failures and properly propagate those tocore autoscaler so that the nodegroup can be backed-off. Otherwise, in the case of quota failures for example, retries will occur in every autoscaler loop leading to throttling.
Asynchronous part that waits on the future and logs those failures.
> Cherry pick #2944 to 1.14: Properly propagate scale-up failures in scale sets

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
The following splits the scale-up operation into two parts:
Synchronous short lived call that returns a future. This allows capturing quota failures and other early failures and properly propagate those tocore autoscaler so that the nodegroup can be backed-off. Otherwise, in the case of quota failures for example, retries will occur in every autoscaler loop leading to throttling.
Asynchronous part that waits on the future and logs those failures.
> Cherry pick #2944 to 1.15: Properly propagate scale-up failures in scale sets

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
CA should only submit capacity change instead of the whole VMSS model.
Fixes #2958
> Ensure only capacity is changed when PUT Azure VMSS

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> 1.17: Ensure only capacity is changed when PUT Azure VMSS

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
> 1.18: Ensure only capacity is changed when PUT Azure VMSS

- vertical-pod-autoscaler/pkg/admission-controller/main.go
This allows users to create custom MutatingWebhookConfiguration objects, allowing users to edit fields like `objectSelector` or `namespaceSelector`.
> Allow disabling webhook self registration

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
There might be adhoc environments where machineDeployments might not necessarily be available. This let the controller to remain functional for such scenarios.
/area provider/cluster-api
> Let the controller move on if machineDeployments are not available

- vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
- vertical-pod-autoscaler/pkg/admission-controller/main.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler_test.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/calculator.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/observed_containers.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/util.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go
Only actual change that happens here is that empty annotations patch comes before any other patch.
Other than that, this only moves code around. 
I'm doing a restructuring of tests in followup PR.
> Refactor admission controller patch logic

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Scale from 0 need to build node template from ASG tags. Currently, we only support `ephemeral -storage`. We'd like to extend to arbitrary custom resources. 
Resolves 
#2927 -> node level devices
#2888 -> EKS Windows IP resource. 
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
> Support arbitrary custom resource building template

- cluster-autoscaler/cloudprovider/aws/README.md
We have the feature but lack of docs. Add some instructions to make it clear for scale from 0 case. 
Address issue. #2927 #2888
> Add instructions to tag resource for scale from 0 case

- cluster-autoscaler/clusterstate/clusterstate.go
This change was merged and not cherry-picked to 1.14. 
Is it possible to get this merged and cut a final release for 1.14 due to the nature of the fix?
> Cherry-pick #2096: Fix potential SEGV in updateReadinessStat

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/clients/vmssclient/azure_vmssclient.go
- cluster-autoscaler/cloudprovider/azure/clients/vmssclient/interface.go
Properly propagate scale-up failures in scale sets and update the corresponding vendors.
Ref: https://github.com/kubernetes/autoscaler/pull/2944/files
/kind bug
> Properly propagate scale-up failures in scale sets.

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/cloudprovider/aws/aws_util.go
- cluster-autoscaler/cloudprovider/aws/aws_util_test.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/main.go
Part of #2988 
#2249 Load AWS EC2 Instance Types dynamically
#2737 Change the regex to match the providerID used by Fargate on EKS.
#2929 Add instructions to tag resource for scale from 0 case
#2931 Support arbitrary custom resource building template
> Cherry pick  #2249  #2737 #2931 #2929 to 1.16

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
- cluster-autoscaler/cloudprovider/aws/aws_util.go
- cluster-autoscaler/cloudprovider/aws/aws_util_test.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
- cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
- cluster-autoscaler/config/autoscaling_options.go
- cluster-autoscaler/main.go
part of #2988
#2249 Load AWS EC2 Instance Types dynamically
#2737 Change the regex to match the providerID used by Fargate on EKS
#2929 Add instructions to tag resource for scale from 0 case
#2931 Support arbitrary custom resource building template
> Cherry pick #2249 #2737 #2929 #2931  to 1.15

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Part of #2988
#2737 Change the regex to match the providerID used by Fargate on EKS.
#2929 Add instructions to tag resource for scale from 0 case
#2931 Support arbitrary custom resource building template
> Cherry pick #2737 #2929 #2931 to 1.14

- cluster-autoscaler/cloudprovider/aws/README.md
- cluster-autoscaler/cloudprovider/aws/auto_scaling.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
- cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Part of #2988 
#2737  Change the regex to match the providerID used by Fargate on EKS.
#2840 cluster-autoscaler/aws: batch launch config query and ttl cache
#2929   Add instructions to tag resource for scale from 0 case
#2931  Support arbitrary custom resource building template
> Cherry pick #2737 #2840 #2929 #2931 # to 1.17

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
The node with GPU is started with the following gpu label:
```
accelerator=nvidia
```
However, [the gpu label of azure in CA](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go#L33) is ```"cloud.google.com/gke-accelerator"```.
> Correct cloudprovider/azure's GPULabel to "accelerator"

- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Because of various reasons, the VM provisioning may need a long period and hence VMSS scaling requests would time out.
On such cases, the following scaling requests should check the provisioning state and only continue to scale after it has been finished. If the VMSS is still under updating, then CA should log an error and abort the current scaling step.
Fix #3018 
/kind bug
> Ensure VMSS is not under updating before scaling out

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Refer https://github.com/kubernetes/autoscaler/pull/3023/files#r403743863, Caches should be updated after async PUT succeeds.
/kind bug
/cc @nilo19 @marwanad
> Caches should be updated after async PUT succeeds

- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Cherry-pick #3023  and #3024 to CA 1.18: 
* Ensure VMSS is not under updating before scaling out
* caches should be updated after async PUT succeeds
/kind bug
/cc @nilo19 @marwanad
> CA 1.18: Ensure VMSS is not under updating before scaling out

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
cherry pick #3037 to CA 1.18: Remove checking for VMSS provisioningState before scaling.
/kind bug
/cc @marwanad
> CA 1.18: Remove checking for VMSS provisioningState before scaling

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Fixes #3031 
This is to avoid stale cache reads which might deem a node deletable and cause the scale-down operation to below minimum node count.
/kind bug
> Proactively decrement scale set count during deletion operations 

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This is to avoid stale cache reads which might deem a node deletable and cause the scale-down operation to below minimum node count.
/kind bug
> Cherry-pick #3036: Proactively decrement scale set count during deletion operations

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This is to avoid stale cache reads which might deem a node deletable and cause the scale-down operation to below minimum node count.
/kind bug
> Cherry-pick #3036: Proactively decrement scale set count during deletion operations 

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
> Cherry-pick #3019: Correct cloudprovider/azure's GPULabel to "accelerator"

- cluster-autoscaler/utils/kubernetes/event_sink_logging_wrapper.go
- cluster-autoscaler/utils/kubernetes/factory.go
Previously, eventRecorder would throttle the actual events, but not
the information about them logged via klog.
> Fix eventRecorder throttling to include log lines

- cluster-autoscaler/cloudprovider/aws/README.md
1. with https://github.com/kubernetes/autoscaler/issues/2829 regional STS endpoints can be used since
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.6
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.18.1
2. recommend attaching IAM roles directly to the cluster-autoscaler pod instead of the node-group
> Update aws readme for IAM roles & sts regional endpoints

- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
Handling case when one of the container states has FirstSampleStart not set.
> VPA - Fixing container state merge

- cluster-autoscaler/main.go
This massively speeds up checking predicates.
> Scalability: Switch to deltaClusterSnapshot

- vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
- vertical-pod-autoscaler/deploy/recommender-deployment.yaml
- vertical-pod-autoscaler/deploy/updater-deployment.yaml
- vertical-pod-autoscaler/hack/vpa-process-yaml.sh
- vertical-pod-autoscaler/hack/vpa-process-yamls.sh
Includes a change to the new image repository as per k8s vanity domain flip (https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md)
> Switch VPA default deployment to 0.8.0

- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_node_group.go
- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_node_group_test.go
Previously we were rejecting decreases down to the min size due to a logic error -- use of `<=` where we should have been using `<`.
> digitalocean: fix min size bug

- vertical-pod-autoscaler/pkg/recommender/model/container.go
Disabling "outdated" samples filter when processing OOM samples.
/fixes #3078
> VPA - Always process OOM samples

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
The max size should allow to be zero when min size is zero too.
> Allow max size to be zero when fetching from VMSS tags

- vertical-pod-autoscaler/deploy/vpa-v1-crd.yaml
Resources are part of verticalpodautoscalers.autoscaling.k8s.io
- VerticalPodAutoscaler is an api resource for configuring vertical autoscaling for pods.
- VerticalPodAutoscalerCheckpoint is an API resource used internally by the Vertical Pod Autoscaler to store its additional state.
The API was discussed and approved in https://github.com/kubernetes/kubernetes/pull/63797
The design itself was discussed and approved in https://github.com/kubernetes/community/pull/338
Fixes #3069
> Add api-approved label to the Vertical Pod Autoscaler API

- cluster-autoscaler/cloudprovider/clusterapi/README.md
This change adds a readme which describes the basic operation of the
cluster-api provider.
Fixes: #2933
> add readme file for cluster-api provider

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
This PR proposes to cherry-pick #2934 to the `cluster-autoscaler-release-1.18` branch.
With Cluster Autoscaler v1.18.0, it's possible to use the Cluster-API provider. However, there is a bug that makes the provider unusable for some users.
The provider supports all Cluster-API groups and versions, but in the original PR, the group and version are hardcoded. Users that are not using v1alpha2 have two options, which are not optimal:
* Wait for Cluster Autoscaler v1.19.0, which will come up with K8s 1.19.0. The problem is that it's somewhere in August, so that could be a bit long to wait
* Build the image which includes the fix manually, which is not the greatest approach.
The PR (#2934) that fixes this could be looked at as a bugfix and it doesn't introduce any behavior changes (the default …
> [CA-1.18] #2934 cherry-pick: Fixes 2932: let the capi version to be discovered

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
Add the functionality to the Azure cloud provider to enable scaling up and down from 0 with tainted and labeled VMSS
Cherry-pick #1982 
> Cherry-pick #1982: Allow Azure VMSS to scale from 0 with taints and labels

- vertical-pod-autoscaler/pkg/recommender/routines/vpa.go
This is needed for map containerName: aggregatedState to contain
complete information (not only samples, but also resource policy), which
can be later processed downstream. In particular, it is needed for VPA
controlled resources.
> Update aggregatedContainerState from containerResourcePolicy

- vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
- vertical-pod-autoscaler/deploy/recommender-deployment.yaml
- vertical-pod-autoscaler/deploy/updater-deployment.yaml
- vertical-pod-autoscaler/examples/hamster.yaml
Thanks for your works !
Error with a rootless PSP 
```
Type     Reason     Age                    From                  Message
----     ------     ----                   ----                  -------
Normal   Scheduled  6m43s                  default-scheduler     Successfully assigned kube-system/vpa-recommender-654ddbd47b-xsmhw to k8s-xxx
Normal   Pulled     5m17s (x8 over 6m40s)  kubelet, k8s-xxx  Successfully pulled image "k8s.gcr.io/vpa-recommender:0.6.3"
Warning  Failed     5m17s (x8 over 6m40s)  kubelet, k8s-xxx  Error: container has runAsNonRoot and image will run as root
Normal   Pulling    101s (x24 over 6m42s)  kubelet, k8s-xxx  Pulling image "k8s.gcr.io/vpa-recommender:0.6.3"
```
> Run as non-root for kubernetes on VPA

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
If you're using environment variables to configure the Cluster Autoscaler, you're unable to set the Azure cloud provider's rate limit QPS or bucket size and must switch your configuration to file based to do so. This PR enables the setting of 4 environment variables which allow for the rate limit QPS or bucket size to be configured without needing to switch to file based configuration 
Signed-off-by: Marc Sensenich <sensenichm91@gmail.com>
> cluster-autoscaler: Allow Azure Rate Limit Defaults to be set from the environment

- vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer_test.go
- vertical-pod-autoscaler/pkg/recommender/logic/estimator_test.go
- vertical-pod-autoscaler/pkg/recommender/main.go
- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
- vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state_test.go
- vertical-pod-autoscaler/pkg/recommender/model/aggregations_config.go
- vertical-pod-autoscaler/pkg/recommender/model/container.go
- vertical-pod-autoscaler/pkg/recommender/model/container_test.go
This PR exposes some of the aggregations configuration of VPA recommender as command-line flags in the VPA recommender. This can help change the default behaviour of the VPA recommender for different workload use-cases. The pre-existing constant values have been retained as the default values.
> CLI flags for VPA recommender aggregations config.

- cluster-autoscaler/core/scale_up.go
This change adds a warning event to signal when a planned scale up
operation would go over the maximum total nodes. This is being proposed
for two primary reasons: as an event that can be watched during
end-to-end testing, and as a signal to users when this condition is
occurring.
> report MaxNodesTotal count during scale up

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
When #1866 introduced the CAPI provider, all Provider IDs from nodes were being normalized so that internally, there were no differences (eg some places using normalized, some not)
However, the clusterstateregistry and anything outside of the CPAI provider does not expect the instance IDs to be normalized, and so nodes were being marked as unregistered due to the normalized ID not matching the non-normalized ID coming from the Nodes on the cluster.
This PR makes it so that Instance IDs fetched and passed externally are not normalized, fixing the unregistered node logic in the clusterstateregistry when using the CAPI provider.
/cc @enxebre @elmiko
> CAPI: Do not normalize Node IDs outside of CAPI provider

- vertical-pod-autoscaler/pkg/recommender/model/cluster.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go
- vertical-pod-autoscaler/pkg/recommender/model/vpa.go
- vertical-pod-autoscaler/pkg/recommender/model/vpa_test.go
- vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
Replaces a map of bools which were computed based on aggregated states with a map of ints, computed based on raw data.
One potentially heavy operation is a full scan of Pods whenever new VPA object is created, apart from that I don't see any major performance impact.
The full scan is in-memory only, we have all the necessary data already fetched.
> Count live Pods per VPA

- vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
I deleted job label to my prometheus metrics to reduce resource usage and had to set CadvisorMetricsJobName to empty string. I have to send this to make recommender work.
> Fix if job label is empty

- vertical-pod-autoscaler/pkg/updater/README.md
- vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go
- vertical-pod-autoscaler/pkg/updater/logic/updater.go
- vertical-pod-autoscaler/pkg/utils/metrics/metrics.go
- vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go
New metrics to measure how VPA Updater impacts workloads controlled by VPA:
* number of Pods that are considered by the Updater,
* number of Pods that can be evicted,
* number of VPA objects with at least one Pod that can be evicted,
* number of VPA objects with at least one evicted Pod.
Additionally changes the existing metric (number of evicted Pods) by adding a label.
TODO: Manual testing.
> Add bunch of metrics to monitor VPA Updater impact in a cluster

- addon-resizer/Makefile
Having interactive tty flag breaks non-interactive CI builds, as they will error out with `the input device is not a TTY`
> Remove docker -it flag from addon-resizer Makefile

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go
This backports the changes in #2171 to 1.15 so that balancing nodegroups works properly. It's not a clean cherry-pick because the PR introduces nodegroupsets per cloud-provider where this ignored label logic lives. 
I've noticed the label for eksctl added so wondering if we could do the same for 1.15.
> backport #2171: ignore azure agentpool label when comparing nodegroups for similarity

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This utilizes the `cloudprovider.InstanceStatus` struct to prevent sending another deletion call for the cases that exceed the `MaxCloudProviderNodeDeletionTime` of 5 minutes (large SKUs) for instance.
Those calls are rejected with 409s but we should prevent sending those in the first place.
> Avoid sending extra deletion calls for in-progress deletions

- vertical-pod-autoscaler/pkg/recommender/model/cluster.go
- vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go
- vertical-pod-autoscaler/pkg/recommender/model/vpa.go
- vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
- vertical-pod-autoscaler/pkg/utils/metrics/quality/quality.go
The relative_recommendation_changes metric reports changes seen on any given recommendation.
This allows to observe stability vs noisiness of recommendations. Ideally the metric should report mostly zeros as we expect the recommendations to diverge with time and change only rarely.
> Add a metric for observing recommendation stability & changes.

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This utilizes the cloudprovider.InstanceStatus struct to prevent sending another deletion call for the cases that exceed the MaxCloudProviderNodeDeletionTime of 5 minutes (large SKUs) for instance.
Those calls are rejected with 409s but we should prevent sending those in the first place.
> Cherry-pick #3141: Avoid sending extra deletion calls for in-progress deletions

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This utilizes the cloudprovider.InstanceStatus struct to prevent sending another deletion call for the cases that exceed the MaxCloudProviderNodeDeletionTime of 5 minutes (large SKUs) for instance.
Those calls are rejected with 409s but we should prevent sending those in the first place.
> Cherry-pick #3141: Avoid sending extra deletion calls for in-progress deletions 

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
- cluster-autoscaler/cloudprovider/clusterapi/machinedeployment_types.go
- cluster-autoscaler/cloudprovider/clusterapi/machineset_types.go
This change brings in a series of patches to remediate the issues with MachineSet and MachineDeployment replicas becoming stale. These changes add protection around the deletion mechanisms by adding a mutex to this operation and also changing the check versus 0 to use the minimum size for that group. Additionally, the operations to get the replicas are now using API server calls to ensure that the freshest information is available during replica count checks. Lastly, a minor change to the unit tests is added to address the underlying changes with respect to API server queries for replicas.
fixes: #3104 
/area provider/cluster-api
> Fix stale replicas issue with cluster-autoscaler CAPI provider

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
1.17 and below are using the old clients not vendored from cloud-provider which don't have that error type
> Fix bad cherry pick #3141 for 1.17

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
1.17 and below are using the old clients not vendored from cloud-provider
> 1.15: Fix bad cherry-pick from #3141

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
1.17 and below are using the old clients not vendored from cloud-provider which don't have that error type
> 1.16: Fix bad cherry pick from #3141

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
his PR proposes to backport #3057 to the `cluster-autoscaler-release-1.18` branch.
From original PR:
> When #1866 introduced the CAPI provider, all Provider IDs from nodes were being normalized so that internally, there were no differences (eg some places using normalized, some not)
> 
> However, the clusterstateregistry and anything outside of the CPAI provider does not expect the instance IDs to be normalized, and so nodes were being marked as unregistered due to the normalized ID not matching the non-normalized ID coming from the Nodes on the cluster.
> 
> This PR makes it so that Instance IDs fetched and passed externally are not normalized, fixing the unregistered node logic in the clusterstateregistry when using the CAPI provider.
> [CA-1.18] #3057 cherry-pick: CAPI: Do not normalize Node IDs outside of CAPI provider

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
This change is being proposed to improve the mechanism for applying and removing deletion annotations. In some situations it is possible for the CAPI provider to leave unwanted deletion annotations after a scale down to the minimum size. The two commits in this patch add a mechanism for unmarking scalable resources and an additional check for reducing a node group below minimum size.
/area provider/cluster-api
> Improve delete node mechanisms for cluster-api autoscaler provider

- addon-resizer/Makefile
More aggressive GC should help with memory usage
/cc wojtek-t bskiba
> Use golang1.14.4 to compile AddonResizer

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
- cluster-autoscaler/cloudprovider/gce/cache.go
- cluster-autoscaler/cloudprovider/gce/cache_test.go
- cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
- vertical-pod-autoscaler/pkg/utils/metrics/metrics.go
Seems like CI status isn't reported on PRs anymore. This fixes gofmt and lint issues.
> fix gofmt and lint issues

- cluster-autoscaler/cloudprovider/clusterapi/README.md
This change adds a section to the cluster-autoscaler CAPI provider
README which details the required prerequisites for using the
autoscaler. It is being added to help inform users about the
restrictions that are currently in place with regards to using this
provider.
/area provider/cluster-api
> add CAPI prerequisites section to cluster-autoscaler README

- cluster-autoscaler/cloudprovider/digitalocean/digitalocean_node_group.go
The DO API requires the proper node ID and otherwise returns an error. Thus, we can localize the error.
> DigitalOcean: do not use provider ID for node ID

- vertical-pod-autoscaler/pkg/utils/metrics/quality/quality.go
Fix use of log2 label value in vpa_quality_relative_recommendation_changes metric
> Fix use of log2 label value

- vertical-pod-autoscaler/e2e/v1/common.go
- vertical-pod-autoscaler/e2e/v1/recommender.go
- vertical-pod-autoscaler/e2e/v1beta2/common.go
- vertical-pod-autoscaler/e2e/v1beta2/recommender.go
Current implementation assumes that regardless of the workload behavior we are guaranteed to receive a recommendation that is >10mCPU.
> VPA min allowed test should not rely on artificial minimal recommendation

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
I refactored the way we use the generated instance types.
From what I understood in the code, we can, behind an option:
* use a generated list of instance types with a http query to the pricing endpoint `https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/${region}/index.json`
* use the statically generated map in `cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go.
` which is a templated go files from the process just described above.
I didn't see in the code where we actually uses the generated instance types as we still use the global and static map regardless if we set to `--aws-use-static-instance-list=false` (which is also the default).
So I moved the instance types where it seems more convenient to use, in the `AwsManager`.
This component is documented …
> cluster-autoscaler: use generated instance types

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Updates the AWS Cloudprovider tests to match the updates to call signatures from #3185 
Renamed a couple of variables for instance type overrides to be more explicitly named in the tests at the same time.
> Fix AWS CA tests for InstanceType generation changes

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Splits `DeleteInstances` into an operation call + async wait so we don't block main thread when the main loop is deleting unregistered instances.
> switch scalesets to delete asynchronously without waiting on future

- cluster-autoscaler/cloudprovider/azure/azure_client.go
Delete containerServicesClient in provider azure since it is useless.
/kind cleanup
> Azure: Delete containerServicesClient in provider azure.

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
In the scale-down success case, there's no point in invalidating the cache since the node will be `NotReady` and will eventually be deleted.
For the failure case, the next refresh guided by the cache TTL will obtain the refresh data.
This is to reduce the volume of calls during large scale down ops.
> no need to invalidate scale-set caches on scale-down

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Disable increaseSize when the node group is under initialilzation.
fixes: #3240
/kind bug
> Disable increaseSize when the node group is under initialilzation.

- cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Disable increaseSize when the node group is under initialilzation.
fixes: #3240
/kind bug
> Cherry-pick #3242: Disable increaseSize when the node group is under initialilzation.

- cluster-autoscaler/cloudprovider/aws/README.md
Update AWS README document for:
1. Clarity
2. Document fully the use of tags on Auto Scaling Groups to advertise resources to Cluster Autoscaler
3. Emphasize the use of IAM Roles for Service accounts where available for security
4. Fix some grammatical/spelling errors
5. Wrap lines
> AWS: Update documentation

- vertical-pod-autoscaler/e2e/v1/full_vpa.go
- vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go
Bumping up upper limit for cpu recommendation in "Pods under VPA have cpu requests growing with usage" test case.
/fixes #3249
> full vpa e2e - bumping up cpu request tolerance

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Cherry-pick #3261
Currently, DeleteInstances can take a lock on instanceMutex and get blocked on GetAsgForInstance if a manager.regenerate call happens and grab the azure_cache mutex lock. Both DeleteInstances and Nodes will then be deadlocked.
> Cherry-pick #3261: Reduce instance lock scope in scale sets

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Currently, `DeleteInstances` can take a lock on `instanceMutex` and get blocked on `GetAsgForInstance` if a `manager.regenerate` call happens and grab the `azure_cache` mutex lock. Both `DeleteInstances` and `Nodes` will then be deadlocked.
> Reduce instance lock scope in scale sets

- cluster-autoscaler/cloudprovider/azure/README.md
- cluster-autoscaler/cloudprovider/azure/azure_cache.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
The cache TTL isn't really applicable because the core CA call to Nodes() takes precedence in updating the caching and the goroutine running can do more harm than good in some cases given the lock it acquires.
Cherry-pick #2841
> Cherry-pick #2841: remove unused asg cache TTL

- builder/Dockerfile
This is a minor cleanup after https://github.com/kubernetes/autoscaler/pull/3267 to fix building in docker.
> Update golang version used in docker builds

- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
DeleteInstances can take in an array of instances to delete so we should decrement by the length of instances to be deleted.
Note: It's not really an issue now because all code paths used in CA send a single instance to Delete (except `deleteCreatedNodesWithErrors` which isn't used by the Azure provider) but just in case the signatures change in the future
> Decrement curSize by the number of instances to be deleted

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
We don't set any timeouts on the contexts used with the azure clients. In some cases, this can be dangerous because we can block the autoscaler main loop in the paths that depend on `cloudprovider.Nodes()` call. This can possibly lead to lock contention and halting the entire progress.
Here's an example of a List VMs call that blocked the main loop for 10 minutes:
```
I0703 06:38:34.812256       1 azure_client.go:202] azVirtualMachineScaleSetVMsClient.List("mc_","aks-nodepool1-11559524-vmss",""): start
I0703 06:48:04.815605       1 azure_client.go:204] azVirtualMachineScaleSetVMsClient.List("mc_","aks-nodepool1-11559524-vmss",""): end
E0703 06:48:04.815662       1 azure_scale_set.go:349] VirtualMachineScaleSetVMsClient.List failed for aks-nodepool1-11559524-vmss: …
```
> use contexts with timeouts in scale set GET calls

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
> Cherry-pick #3278: use contexts with timeouts in scale set GET calls

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Cherry-pick #3221 - Async deletions without waiting on future
Cherry-pick #3284 - Synchronize deletions to avoid 409 Conflict errors
Rename method for consistency with the vendored azure clients
> Cherry-pick #3221, #3284 - Async Deletions and 409 Conflicts 

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/azure/azure_fakes.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
- cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Cherry-pick #3221 - Async deletions without waiting on future
Cherry-pick #3284 - Synchronize deletions to avoid 409 Conflict errors
Rename method for consistency with the vendored azure clients
> Cherry-pick #3221, #3284 - Async Deletions and 409 Conflicts

- cluster-autoscaler/utils/taints/taints.go
The `NodeWithImpairedVolumes` taint is applied to node on AWS when a volume is stuck in attaching state for too long.
The taint was introduced in k8s a while ago https://github.com/kubernetes/kubernetes/pull/55558
Add it to the ignored node condition taints.
> Ignore AWS NodeWithImpairedVolumes taint

- addon-resizer/Makefile
This is required due to #3294
This reverts commit 0410b57dd0e556581d91d1685ae0e2e8331257a6.
> Revert "Use golang1.14.3 to compile AddonResizer"

- addon-resizer/Makefile
This is to roll-out https://github.com/kubernetes/autoscaler/pull/3298 - reverting golang version to 1.12.1
> Bump addon-resizer to 1.8.11

- cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
This adds a context timeout for queuing the long running operations for `DeleteInstances` and `updateCapacity` to guard against the very rare cases where it can take long to get a response back.
It also fixes a potential issue where the mutex won't get released if the `DeleteInstanceAsync` call fails.
> Fix possible lock issue and add timeouts for queuing of long running operations

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
- cluster-autoscaler/cloudprovider/azure/clients/diskclient/azure_diskclient.go
- cluster-autoscaler/cloudprovider/azure/clients/diskclient/interface.go
- cluster-autoscaler/cloudprovider/azure/clients/interfaceclient/azure_interfaceclient.go
- cluster-autoscaler/cloudprovider/azure/clients/interfaceclient/interface.go
- cluster-autoscaler/cloudprovider/azure/clients/storageaccountclient/azure_storageaccountclient.go
- cluster-autoscaler/cloudprovider/azure/clients/storageaccountclient/interface.go
- cluster-autoscaler/cloudprovider/azure/clients/vmclient/azure_vmclient.go
- cluster-autoscaler/cloudprovider/azure/clients/vmclient/interface.go
- cluster-autoscaler/cloudprovider/azure/clients/vmssclient/azure_vmssclient.go
- cluster-autoscaler/cloudprovider/azure/clients/vmssvmclient/azure_vmssvmclient.go
- cluster-autoscaler/cloudprovider/azure/clients/vmssvmclient/interface.go
This fixes the userAgent string which used to be 
```
Go/go1.13.5 (amd64-linux) go-autorest/v13.0.0; kubernetes-cloudprovider/v0.0.0-master+$Format:%h$
```
to
```
Go/go1.13.8 (amd64-linux) go-autorest/v13.0.0 cluster-autoscaler/v{{CA_VERSION}}
```
^ There's no semicolon above - this just lets autorest handle the spacing and extension.
Had to vendor the clients in directly to avoid the need for a cherry-pick in k/k + vendor update in 1.18.
/kind bug
> Fix user-agent string in azure clients

- vertical-pod-autoscaler/e2e/go.mod
- vertical-pod-autoscaler/e2e/go.sum
- vertical-pod-autoscaler/e2e/v1/admission_controller.go
- vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
- vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/zz_generated.deepcopy.go
- vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/zz_generated.deepcopy.go
- vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/zz_generated.deepcopy.go
- vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/zz_generated.deepcopy.go
- vertical-pod-autoscaler/e2e/vendor/modules.txt
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go
- vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler_test.go
- vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
- vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/zz_generated.deepcopy.go
- vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping.go
- vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
Make the proportional limit scaling configurable.
Follow up of https://github.com/kubernetes/autoscaler/issues/2359, https://github.com/kubernetes/autoscaler/pull/2362 and https://github.com/kubernetes/autoscaler/issues/2387
I'm happy to update the generated files and add tests if the approach looks acceptable.
//cc @Avanpourm @bskiba
> VPA: Configurable container limit scaling

- cluster-autoscaler/cloudprovider/azure/azure_client.go
- cluster-autoscaler/cloudprovider/azure/azure_util.go
Since the clients are using the vendored cloud-provider ones - we need to configure the user agent to not use the cloud-provider one.
> Configure user agent properly for azure clients

- vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go
If you have a pod with no Limits for either CPU or Memory and no Default Limits you get a panic in the `updater` when it's calculating the boundary.
e.g
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1269d03]
goroutine 1 [running]:
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa.getBoundaryRecommendation(0xc0018af8c0, 0xc001822aa0, 0x12, 0xc002f5f4d0, 0x25, 0xc008bd3c00, 0x11, 0x20, 0x0, 0x0, ...)
/gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/capping.go:317 +0x8f3
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa.getMinAllowedRecommendation(0xc0018af8c0, 0xc001822aa0, 0x12, 0xc002f5f4d0, 0x25, 0xc008bd3c00, 0x11, 0x20, 0x0, 0x0, ...) …
```
> VPA: fix nil pointer in getBoundaryRecommendation when no limits set

- cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Adds a number of new instance types/families to the static list
Doesn't include the `c5a` family as #3259 already exists, however does include the `r6g` family as #3250 seems to miss the smaller instance types in this family.
Also brings in the new `c6g` family [announced last month](https://aws.amazon.com/ec2/instance-types/c6/).
> CA - AWS CloudProvider - Static Instance List update

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Cherry pick of #3185 #3222 on cluster-autoscaler-release-1.17.
#3185: cluster-autoscaler: use generated instance types
#3222: Fix AWS CA tests for InstanceType generation changes
> Automated cherry pick of #3185: cluster-autoscaler: use generated instance types #3222: Fix AWS CA tests for InstanceType generation changes

- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Cherry pick of #3185 #3222 on cluster-autoscaler-release-1.15.
#3185: cluster-autoscaler: use generated instance types
#3222: Fix AWS CA tests for InstanceType generation change
> Automated cherry pick of #3185: cluster-autoscaler: use generated instance types #3222: Fix AWS CA tests for InstanceType generation change

- cluster-autoscaler/FAQ.md
- cluster-autoscaler/hack/update-vendor.sh
This is required because Kubernetes 1.17 lists go1.12 in go.mod,
but it doesn't actually compile using go1.12.
> Allow overriding go version when updating vendor

- vertical-pod-autoscaler/pkg/admission-controller/main.go
- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
- vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
- vertical-pod-autoscaler/pkg/recommender/input/history/history_provider_test.go
- vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go
- vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client_test_util.go
- vertical-pod-autoscaler/pkg/recommender/main.go
- vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
- vertical-pod-autoscaler/pkg/updater/logic/updater.go
- vertical-pod-autoscaler/pkg/updater/main.go
- vertical-pod-autoscaler/pkg/utils/vpa/api.go
Allows running multiple VPA deployments, each deployment looking at only it's namespace, update it's lease in that namespace, etc.
Also for Prometheus it would limit queries to that namespace.
Fixes #3010
We are currently running this and it works great!
docker images available:
```
- name: vpa-updater
newName: quay.io/utilitywarehouse/vpa-updater
newTag: dev
- name: vpa-admission-controller
newName: quay.io/utilitywarehouse/vpa-admission-controller
newTag: dev
- name: vpa-recommender
newName: quay.io/utilitywarehouse/vpa-recommender
newTag: dev
```
Role bindings:
<details>
<pre>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: vpa-actor
namespace: telecom
rules:
- apiGroups:
- ""
resources:
- pods
- limitranges
verbs:
- get
- list
- watch
- apiGroups:
- "" …
> VPA: Allow limiting VPA deployment to a namespace

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go
This cherry-picks #3124 into the 1.17 release branch as discussed in #3248
> [CA-1.17] Cherry-pick #3124: Allow small tolerance on memory capacity when comparing nodegroups

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go
This cherry-picks #3124 into the 1.18 release branch as discussed in #3248
> [CA-1.18] Cherry-pick #3124: Allow small tolerance on memory capacity when comparing nodegroups

- cluster-autoscaler/utils/taints/taints.go
Cherry pick of #3040 on cluster-autoscaler-release-1.18.
#3040: Ignore AWS NodeWithImpairedVolumes taint
> Automated cherry pick of #3040: Ignore AWS NodeWithImpairedVolumes taint

- cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
- Correctly sets providerID
- Enables Kubemark to run in the same cluster as CA.
> [cluster-autoscaler] Fixes to Kubemark integration.

- cluster-autoscaler/cloudprovider/azure/azure_manager.go
- cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
While using Azure vmss, we discovered if we just have a single vmss missing the min/max tag on it, it failed to build the entire nodegroup cache.
The autoscaler is running without any potential candidates and the cluster can't be scaled at all.
I just added some warning logs, let me know if you want me to do differently and if the logic is fine like this.
> cluster-autoscaler: ignore nodegroups with min/max tag issues

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
Backports #3034 to cluster-autoscaler-release-1.18:
From the original PR:
> This change is being proposed to improve the mechanism for applying and removing deletion annotations. In some situations it is possible for the CAPI provider to leave unwanted deletion annotations after a scale down to the minimum size. The two commits in this patch add a mechanism for unmarking scalable resources and an additional check for reducing a node group below minimum size.
> [CA-1.18] #3034 cherry-pick: Improve delete node mechanisms for cluster-api autoscaler provider #3034

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
- cluster-autoscaler/cloudprovider/clusterapi/machinedeployment_types.go
- cluster-autoscaler/cloudprovider/clusterapi/machineset_types.go
Backports #3177 to cluster-autoscaler-release-1.18:
From the original PR:
> This change brings in a series of patches to remediate the issues with MachineSet and MachineDeployment replicas becoming stale. These changes add protection around the deletion mechanisms by adding a mutex to this operation and also changing the check versus 0 to use the minimum size for that group. Additionally, the operations to get the replicas are now using API server calls to ensure that the freshest information is available during replica count checks. Lastly, a minor change to the unit tests is added to address the underlying changes with respect to API server queries for replicas.
> [CA-1.18] #3177 cherry-pick: Fix stale replicas issue with cluster-autoscaler CAPI provider

- vertical-pod-autoscaler/e2e/utils/certs.go
/fixes #3377
Adds now-required altName to e2e webhook certificate.
> VPA - Adding altName to e2e webhook cert

- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Resolves failing tests from faulty cherry-pick #3335 - restores to previous args to creation of `autoScalingWrapper` in AWS manager tests
> Cluster-Autoscaler - Resolve failing tests

- vertical-pod-autoscaler/deploy/vpa-v1-crd.yaml
This was missed in https://github.com/kubernetes/autoscaler/pull/3028.
I updated the CRD definition manually, not sure whether there is a better way.
> VPA Add controlledValues to CRD

- .github/workflows/pr.yaml
- .github/workflows/release.yaml
- .pre-commit-config.yaml
- README.md
- charts/OWNERS
- charts/README.md
- charts/cluster-autoscaler/.helmignore
- charts/cluster-autoscaler/Chart.yaml
- charts/cluster-autoscaler/README.md
- charts/cluster-autoscaler/README.md.gotmpl
- charts/cluster-autoscaler/templates/NOTES.txt
- charts/cluster-autoscaler/templates/_helpers.tpl
- charts/cluster-autoscaler/templates/clusterrole.yaml
- charts/cluster-autoscaler/templates/clusterrolebinding.yaml
- charts/cluster-autoscaler/templates/deployment.yaml
- charts/cluster-autoscaler/templates/pdb.yaml
- charts/cluster-autoscaler/templates/podsecuritypolicy.yaml
- charts/cluster-autoscaler/templates/priority-expander-configmap.yaml
- charts/cluster-autoscaler/templates/role.yaml
- charts/cluster-autoscaler/templates/rolebinding.yaml
- charts/cluster-autoscaler/templates/secret.yaml
- charts/cluster-autoscaler/templates/service.yaml
- charts/cluster-autoscaler/templates/serviceaccount.yaml
- charts/cluster-autoscaler/templates/servicemonitor.yaml
- charts/cluster-autoscaler/values.yaml
Adopts the [stable/cluster-autoscaler](https://hub.helm.sh/charts/stable/cluster-autoscaler) chart, making this repository the official home for the chart moving forward. Only minor changes have been made to the chart itself; most of it is original from the `stable` channel.
Solves https://github.com/kubernetes/autoscaler/issues/3318.
Helm chart deprecation PR: https://github.com/helm/charts/pull/23305
As mentioned, this PR adopts the `cluster-autoscaler` chart officially into this repository. The following changes were made.
- Helm 3
- The version of the chart that will be maintained in this repo moving forward will be for Helm 3+ only. The `apiVersion` on this chart has been changed to `v2` reflect this change.
- Helm-docs for generation of README
- The …
> [charts] Adopt Cluster Autoscaler chart
