cluster-autoscaler/proposals/balance_similar.md

repair url in balance_similar.md

repair url in balance_similar.md

---

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go

dont return error for nodes without providerId

---

cluster-autoscaler/utils/kubernetes/listers.go

Change-Id: I707d51712281b86d8dd32105dc284359c1c09e53

Remove extra slice copy

---

cluster-autoscaler/cloudprovider/azure/azure_fakes.go
cluster-autoscaler/cloudprovider/azure/azure_manager.go
cluster-autoscaler/cloudprovider/azure/azure_manager_test.go

Fix azure autodiscovery when max tags aren't specified

---

vertical-pod-autoscaler/pkg/target/fetcher.go

Ensure that the label selector in the scale subresource is not empty

---

addon-resizer/Makefile

Addon resizer release 1.8.8

---

cluster-autoscaler/cloudprovider/azure/azure_fakes.go
cluster-autoscaler/cloudprovider/azure/azure_manager.go
cluster-autoscaler/cloudprovider/azure/azure_manager_test.go

Cherry pick #2714 to 1.17: Fix panic when the vmss doesn't exist

---

cluster-autoscaler/simulator/predicates.go
cluster-autoscaler/simulator/predicates_test.go

Add logging taints on template node on PodToleratesNodeTaints failure.

Add logging taints on template node on PodToleratesNodeTaints failure

---

cluster-autoscaler/simulator/predicates.go

Lazy debug info message evaluation

---

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go

Only evict quick oomed pods when resource will change

---

cluster-autoscaler/cloudprovider/azure/README.md

Add helm deployment support in doc.

Add helm deployment support in doc.

---

vertical-pod-autoscaler/pkg/utils/annotations/vpa_observed_containers.go
vertical-pod-autoscaler/pkg/utils/annotations/vpa_observed_containers_test.go

Adding module for creating and parsing vpa blessing annotation.
ref #2726

Adding vpa blessing annotation

---

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go
vertical-pod-autoscaler/pkg/utils/test/test_pod.go

- adding annotation setter to PodBuilder
- handling vpaObservedContatiners annotation in updater
ref #2726

VPA - Vpa observed containers annotation handling in updater

---

vertical-pod-autoscaler/go.mod
vertical-pod-autoscaler/go.sum
vertical-pod-autoscaler/vendor/k8s.io/utils/pointer/pointer.go
vertical-pod-autoscaler/vendor/k8s.io/utils/pointer/pointer_test.go

Adding k8s.io/utils/pointer to the vendor dir.

VPA - vendor update

---

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go

- handling quick OOM for more than 1 containers.
- only containers with scaling policies should be consider for quick OOM.
- quick OOM doesn't apply to injected sidecars.
/fixes #2739

VPA - Quick OOM for all containers

---

cluster-autoscaler/README.md

Adds entry and link to README.md for DigitalOcean as a supported cloud provider

Add DigitalOcean as supported cloudprovider

---

cluster-autoscaler/core/filter_out_schedulable.go

Do not compare StartTime for unschedulable pods
Using standard MostImportantPod function for pods which do not have
Status.StartTime set result in Error log message which kills
scalability.

Do not compare StartTime for unschedulable pods

---

vertical-pod-autoscaler/pkg/utils/status/status_object.go
vertical-pod-autoscaler/pkg/utils/status/status_object_test.go

RenewTime is optional Lease field. Requires not-nil check.

VPA - Optional RenewTime fix

---

vertical-pod-autoscaler/pkg/utils/status/status_object.go
vertical-pod-autoscaler/pkg/utils/status/status_object_test.go

Adding Validator interface that will be used by status readers.

VPA - Adding status object validator

---

vertical-pod-autoscaler/pkg/admission-controller/main.go
vertical-pod-autoscaler/pkg/utils/status/status_updater.go

Moving status_updater to utils/.
This is a setup for e2e tests.
ref #2738

VPA - Moving status updater to utils

---

vertical-pod-autoscaler/e2e/v1/recommender.go
vertical-pod-autoscaler/e2e/v1beta2/recommender.go

Using functions from common.go.

VPA - Recommender e2e test cleanup

---

vertical-pod-autoscaler/e2e/v1/recommender.go
vertical-pod-autoscaler/e2e/v1beta2/recommender.go

VPA - Adding min and max resource allowed e2e tests

---

vertical-pod-autoscaler/pkg/admission-controller/config.go
vertical-pod-autoscaler/pkg/admission-controller/main.go

VPA - Removing string pointer

---

cluster-autoscaler/version/version.go

Update Cluster Autoscaler version to 1.15.5.

Cluster Autoscaler 1.15.5

---

cluster-autoscaler/version/version.go

Update Cluster Autoscaler version to 1.16.4.

Cluster Autoscaler 1.16.4

---

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go

Adding overriding  VpaObservedContainers annotation instead of all annotations.

VPA - Fixing vpaObservedContainers annotation

---

cluster-autoscaler/core/scale_up.go
cluster-autoscaler/estimator/binpacking_estimator.go
cluster-autoscaler/simulator/cluster.go
cluster-autoscaler/simulator/predicates_checker_interface.go
cluster-autoscaler/simulator/scheduler_based_predicates_checker.go
cluster-autoscaler/simulator/scheduler_based_predicates_checker_test.go
cluster-autoscaler/utils/daemonset/daemonset.go

Forget FakeNodeInfoForNodeName ever existed

---

cluster-autoscaler/core/static_autoscaler.go

Add pods from upcoming nodes to snapshot

---

cluster-autoscaler/utils/daemonset/daemonset.go

Resolve todo in GetDaemonSetPodsForNode

---

cluster-autoscaler/core/scale_test_common.go

Increase fake event recorder buffer.

Increase fake event recorder buffer

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

Currently, if a VMSS is created with a Promo instance type that's not contained in the static type list the autoscaler fails to manage it with the following errors:
```
Failed to get node infos for groups: instance type "<redacted>_Promo" not supported 
Unable to build proper template node for <redacted>: instance type "<redacted>_Promo" not supported
```
This error is invalid as there are no differences between standard and _Promo instance types outside of pricing.  In order to allow users to take advantage of Promo instances as they are made available without relying on new autoscaler images, this change will attempt to match a `_Promo` instance type against the non-promo types contained in the static Azure type list if an exact match is not found.
The change here is already realized in …

[Azure] Add fallback check for 'Promo' instance types

---

cluster-autoscaler/FAQ.md

Add missing syntax highlight

---

cluster-autoscaler/simulator/cluster_snapshot_test.go

Also refactor test cases a bit to make test easier to read.

Add test case for caching & commit

---

cluster-autoscaler/simulator/scheduler_based_predicates_checker.go

Note: I'd prefer to get rid of this error by adding error-free method to snapshot.

Rephrase impossible snapshot error todo

---

vertical-pod-autoscaler/pkg/updater/priority/priority_processor.go
vertical-pod-autoscaler/pkg/updater/priority/priority_processor_test.go
vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go

Make PriorityProcessor useful by changing return value to public

---

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go

Add tests. Make ordering in updatePriorityCalculator explicit.

Correct Less function for priority.

---

vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go

This assertion is flaky:
https://github.com/kubernetes/autoscaler/issues/2886
Make it log more useful message when it fails. Also clean it up (an
asserion above makes sure the second half of the or is never true).

Make flaky assertion more verbose

---

cluster-autoscaler/cloudprovider/azure/README.md
cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
cluster-autoscaler/cloudprovider/azure/azure_client.go
cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
cluster-autoscaler/cloudprovider/azure/azure_fakes.go
cluster-autoscaler/cloudprovider/azure/azure_manager.go
cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
cluster-autoscaler/cloudprovider/azure/azure_util.go
cluster-autoscaler/cloudprovider/azure/azure_util_test.go

Update vmss and vmss vm client to the new version in cloud provider azure.
Partly solves #2898.

Provider/Azure: Update vmss and vmss vm client.

---

cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go
cluster-autoscaler/cloudprovider/azure/azure_cache.go

Fix the bug of vm cache that multiple agentpools share one cache.
/kind bug

Provider/Azure: Fix the bug of vm cache that multiple agentpools share one cache.

---

vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider.go
vertical-pod-autoscaler/pkg/admission-controller/logic/recommendation_provider_test.go
vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go
vertical-pod-autoscaler/pkg/admission-controller/logic/vpa_matcher.go
vertical-pod-autoscaler/pkg/admission-controller/logic/vpa_matcher_test.go
vertical-pod-autoscaler/pkg/admission-controller/main.go

Separate out a component for fetching matching VPA objects.

Refactor admission controller.

---

cluster-autoscaler/core/scale_down.go
cluster-autoscaler/core/scale_down_test.go
cluster-autoscaler/core/static_autoscaler.go
cluster-autoscaler/simulator/cluster.go

Follow-up to #2890, rebased now.

Minor cleanups in scale-down 

---

cluster-autoscaler/core/scale_down.go

Separate PR to avoid drive-by refactors related to #2890.

More clean-ups in scale-down

---

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
vertical-pod-autoscaler/pkg/admission-controller/main.go
vertical-pod-autoscaler/pkg/admission-controller/resource/handler.go
vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler.go
vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler_test.go
vertical-pod-autoscaler/pkg/admission-controller/resource/pod/pre_processor.go
vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation_provider.go
vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation_provider_test.go
vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go
vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler_test.go
vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go
vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher_test.go
vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/pre_processor.go

No logic changes, just restructuring the code.

Separate admission controller logic for pods and vpas

---

cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go

Sometimes the size of vm cache doesn't match it of cloud provider side. This pr add several invalidating operation to forcibly refresh the cache.
/kind bug

Provider/Azure: Invalidating vm cache when the size is incorrect.

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

1.15: Ensure only capacity is changed when PUT Azure VMSS

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

1.14: Ensure only capacity is changed when PUT Azure VMSS

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

1.16: Ensure only capacity is changed when PUT Azure VMSS

---

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go

Adresses https://github.com/kubernetes/autoscaler/pull/2968/files#r396542312

Return provider interface

---

cluster-autoscaler/hack/update-vendor.sh

For some reason it was not present on cluster-autoscaler-release-1.15 branch

Add hack/update-vendor.sh script

---

cluster-autoscaler/cloudprovider/aws/OWNERS

We need more AWS contributors to review/approve PR. 
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

Add jaypipes to aws cloud provider OWNERS

---

cluster-autoscaler/cloudprovider/digitalocean/OWNERS

This PR adds me to the list of reviewers for the DigitalOcean cloud provider.

Add MorrisLaw to the list of reviewers for DigitalOcean

---

cluster-autoscaler/cloudprovider/aws/README.md
cluster-autoscaler/cloudprovider/aws/aws_manager.go
cluster-autoscaler/cloudprovider/aws/aws_manager_test.go

part of #2988 
#2929  Add instructions to tag resource for scale from 0 case
#2931  Support arbitrary custom resource building template

Cherry pick #2929 #2931 to 1.18

---

cluster-autoscaler/version/version.go

Update Cluster Autoscaler version to 1.14.8.

Cluster Autoscaler 1.14.8

---

cluster-autoscaler/version/version.go

Update Cluster Autoscaler version to 1.15.6.

Cluster Autoscaler 1.15.6

---

cluster-autoscaler/version/version.go

Update Cluster Autoscaler version to 1.16.5.

Cluster Autoscaler 1.16.5

---

cluster-autoscaler/version/version.go

Update Cluster Autoscaler version to 1.17.2.

Cluster Autoscaler 1.17.2

---

cluster-autoscaler/version/version.go

Update Cluster Autoscaler version to 1.18.1.

Cluster Autoscaler 1.18.1

---

vertical-pod-autoscaler/e2e/v1/full_vpa.go
vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go

I accidentally included returning early from those tests in #2952

Enable tests for pods under VPA

---

vertical-pod-autoscaler/e2e/utils/ooming_resource_consumer/Dockerfile
vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go
vertical-pod-autoscaler/e2e/v1/common.go
vertical-pod-autoscaler/e2e/v1/full_vpa.go
vertical-pod-autoscaler/e2e/v1beta2/autoscaling_utils.go
vertical-pod-autoscaler/e2e/v1beta2/common.go
vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go

Tests I added in #2952 are failing when running on prow because pods are stuck pending. Roll back the change

Rollback OOM tests

---

vertical-pod-autoscaler/e2e/utils/ooming_resource_consumer/Dockerfile
vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go
vertical-pod-autoscaler/e2e/v1/common.go
vertical-pod-autoscaler/e2e/v1/full_vpa.go
vertical-pod-autoscaler/e2e/v1beta2/autoscaling_utils.go
vertical-pod-autoscaler/e2e/v1beta2/common.go
vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go

Includes #3017 and one a commit increasing timeout for the OOM test

Enable and deflake oom test

---

vertical-pod-autoscaler/deploy/vpa-v1-crd.yaml
vertical-pod-autoscaler/examples/hamster.yaml
vertical-pod-autoscaler/hack/boilerplate.go.txt
vertical-pod-autoscaler/hack/update-codegen.sh
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/zz_generated.deepcopy.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/zz_generated.deepcopy.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/zz_generated.deepcopy.go
vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/zz_generated.deepcopy.go

This field will allow to specify resources for which VPA generates recommendations.

Add ControlledResources to VPA v1 API

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go

Remove checking for VMSS provisioningState before scaling, because it would make the scaling much slower. And VMSS would actually reset their goal state whenever a new target is PUT, hence it should still scale to expected nodes even the original request hasn't been finished yet.
/kind bug
/cc @marwanad

Remove checking for VMSS provisioningState before scaling

---

vertical-pod-autoscaler/pkg/recommender/logic/recommender.go
vertical-pod-autoscaler/pkg/recommender/logic/recommender_test.go
vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state_test.go
vertical-pod-autoscaler/pkg/recommender/model/types.go

This implements functionality which allows specifying resources for which VPA generates recommendations.
API changes: https://github.com/kubernetes/autoscaler/commit/2cfdb76281bed5bcd4afccfde91ba379dbb9ab10

Implement ControlledResources

---

vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
vertical-pod-autoscaler/pkg/recommender/input/history/history_provider_test.go

Issue https://github.com/kubernetes/autoscaler/issues/2508
Previously we did `rate(container_cpu_usage_seconds_total{%s}[8d])`, which returns you a per-second average rate of increase, which would be a single number per container. And I believe it isn't very useful as averaging out over 8days, won't account for for spikes.
The fix uses Prometheus subqueries (https://prometheus.io/blog/2019/01/28/subquery-support/), which calculates a same rate over 5 minutes over last 8 days with default step ( in my case it was 1min)
So result of executing that query for one container is:
```
0.08135529095444262 @1585684200
0.04520008871193183 @1585684260
0.04030128808668913 @1585684320
0.038564872259585437 @1585684380
0.037179121655268745 @1585684440
0.001468363844192067 @1585684500 …
```

Fix Prometheus CPU query

---

vertical-pod-autoscaler/pkg/recommender/logic/recommender.go
vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
vertical-pod-autoscaler/pkg/recommender/model/types.go

Thanks to that they will be able to be referenced by downstream projects.

Export symbols related to VPA ControlledResources

---

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go

Fix comment typo

---

vertical-pod-autoscaler/pkg/recommender/model/container.go

[Cherry-pick] Always processing OOM samples

---

vertical-pod-autoscaler/pkg/recommender/model/container.go

VPA - Always processing OOM samples

---

cluster-autoscaler/cloudprovider/baiducloud/baiducloud-sdk-go/cce/cluster.go
cluster-autoscaler/cloudprovider/baiducloud/baiducloud_manager.go

**What type of PR is this?**
```
/kind feature
```
```
add EphemeralStorage in group template
```
**Which issue(s) this PR fixes**:
```
NONE
```
**Special notes for your reviewer**:
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```

add EphemeralStorage in group template

---

addon-resizer/Dockerfile
addon-resizer/Makefile

Fixes: https://github.com/kubernetes/autoscaler/issues/2870

Backport Mutiarch addon-resizer image

---

vertical-pod-autoscaler/deploy/vpa-rbac.yaml

Needed to allow VPA to scale custom controllers.
#3060

Allow VPA to read scale subresource

---

addon-resizer/Makefile

Change staging repo for addon-resizer to autoscaling

---

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go

This PR proposes to backport #2940 to the `cluster-autoscaler-release-1.18` branch.

[CA-1.18] #2940 cherry-pick CAPI: Stop panicking in newMachineController

---

addon-resizer/nanny/kubernetes_client.go

Minor optimization to addon-resizer

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

return correct error type for GetScaleSetVms

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

Fixes a bad cherry-pick for #3141 

1.18: fix bad cherry-pick for #3141

---

addon-resizer/Makefile

/assign @bskiba 
@jkaniuk - FYI

Bump addon-resizer image to 1.8.10

---

vertical-pod-autoscaler/e2e/v1/full_vpa.go
vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go

The minimal values that were checked before are implementaion detail.

VPA e2e tests check for non-0 minimal recommendation

---

vertical-pod-autoscaler/README.md

Bring VPA readme up to date.

---

cluster-autoscaler/cloudprovider/azure/azure_cache_test.go

Azure: Add test cases for azure_cache.go.
/kind cleanup

Azure: Add test cases for azure_cache.go.

---

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go

Improves unit test code coverage for azure_manager.go
/kind cleanup
/sig cloud-provider
/priority important-soon

Improves unit test code coverage for azure_manager.go

---

cluster-autoscaler/cloudprovider/azure/README.md

Update document to add a section on throttling and document `AZURE_VMSS_CACHE_TTL` variable.

update azure throttling README

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

The real reason for getting 409s is not sending requests for in progress deletions for the same VM but rather concurrent deletion requests (possibly for different VMs) because on the VMSS side each will attempt to decrement the capacity. And since CA calls `DeleteNodes()` in parallel for empty nodes - you can hit this issue if two or more go routines send the delete request at the same time.
This attempts to synchronize the delete calls using the `instanceMutex` to avoid getting those 409 errors. There's no risk of contention since `DeleteInstancesAsync` doesn't wait on the future.

synchronize scale set instance deletions to avoid 409 conflict errors

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

Cherry pick #3277: Decrement curSize by the number of instances to be deleted

---

cluster-autoscaler/cloudprovider/digitalocean/OWNERS

This PR adds me to the list of approvers for the DigitalOcean cloud provider.

Add MorrisLaw to list of approvers for DigitalOcean

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

Cherry-pick #3296: Fix possible lock issue and add timeouts for queuing of long running operations

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

Cherry-pick #3296: Fix possible lock issue and add timeouts for queuing of long running operationspic

---

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go

Mirror: https://github.com/kubernetes/autoscaler/pull/3258
/priority important-soon
/kind cleanup

Azure: Enrich unit tests for azure_cloud_provider

---

cluster-autoscaler/cloudprovider/clusterapi/README.md
cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml

Based on https://notes.elmiko.dev/2020/05/22/kubernetes-autoscaler-capd.html
@detiber @elmiko

Add sample deployment/service account manifest for CAPI

---

cluster-autoscaler/hack/update-vendor.sh

Allow overriding go version when updating vendor

---

vertical-pod-autoscaler/pkg/admission-controller/config.go

Switch VPA admission controller to v1 admissionregistration API

---

vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh

Add subjectAltName to VPA webhook cert

---

cluster-autoscaler/cloudprovider/aws/aws_manager_test.go

Resolve failing tests post merging of #3336 for CA 1.15 release branch

Cluster-Autoscaler - Resolve Failing AWS tests

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

Fixes the cherry-pick in #3112 

fix setting labels and taints in autodiscovery

---

vertical-pod-autoscaler/README.md

Answers #3388 and #3379
I will also add the information in the script when encountering error on certificate generation

Add -addext error to VPA readme

---

cluster-autoscaler/OWNERS

I'd like to co-maintain the autoscaler and ensure PRs won't block too long to get approved.
/assign @mwielgus @maciekpytel @bskiba

Add myself to owners

---

cluster-autoscaler/cloudprovider/aws/README.md

For those that read the README and look through the examples directory but don't look directly below. Hopefully this can save some time for others.

Add link to AWS IAM OIDC example in README.md

---

vertical-pod-autoscaler/FAQ.md

Fix YAML indents in FAQ document

---

vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh

Descriptive error on failed cert generation

---

cluster-autoscaler/main.go
cluster-autoscaler/metrics/metrics.go

Expose max-nodes-total as a metric

---

index.yaml

* Manual addition of the CA Chart 1.0.2 release to the index
Fixes #3471

CA-Chart - 1.0.2 Release

---

charts/cluster-autoscaler-chart/Chart.yaml
charts/cluster-autoscaler-chart/values.yaml

This PR addresses the issue: https://github.com/kubernetes/autoscaler/issues/3481

remove duplicated values

---

cluster-autoscaler/cloudprovider/aws/README.md

I fix markdown style link in README.

Fix markdown style link in README

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

Sometimes VMSS new goal capacity isn't reflected after delete calls so in an unlucky case, a cache refresh can invalidate the proactively decremented capacity and can possibly put the nodegroup below its minimum if nodes are empty and eligible for deletion.

dont update capacity if VMSS provisioning state is updating

---

cluster-autoscaler/cloudprovider/azure/azure_util.go
cluster-autoscaler/cloudprovider/azure/azure_util_test.go

Cherry pick #3484 onto 1.18: Serve stale on ongoing throttling 

---

vertical-pod-autoscaler/pkg/utils/vpa/capping.go
vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go

Fix limit rounding

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
cluster-autoscaler/cloudprovider/azure/azure_template.go
cluster-autoscaler/cloudprovider/azure/azure_template_test.go

Cherry pick #3558 - Add missing stable labels in the azure template

Cherry pick #3558 onto 1.16 - Add missing stable labels in the azure template

---

index.yaml

Publish release of CA Chart version 1.0.3 to include changes from #3575

CA-Chart - 1.0.4 Release

---

vertical-pod-autoscaler/README.md

Add openssl version requirement

---

vertical-pod-autoscaler/common/version.go

Vertical Pod Autoscaler release 0.9.0

---

cluster-autoscaler/FAQ.md

This documents a flag that previously had no documentation. Fixes #3515

Add documentation for balancing-ignore-label flag

---

index.yaml

New CA Chart releases for #3587 and #3424

CA-Chart - 1.1.0 Release

---

cluster-autoscaler/simulator/cluster.go

In findPlaceFor method, the nodes passed aren't taken into account.

Ensure CA simulator takes existing nodes into account

---

vertical-pod-autoscaler/README.md

Add minimum k8s version for VPA 0.9.0

---

cluster-autoscaler/core/utils/utils.go

Exclude the virtual node from nodes not created by auto scaling group

---

cluster-autoscaler/simulator/cluster.go
cluster-autoscaler/simulator/cluster_test.go

Subtract DaemonSet utilization from node allocatable when calculating utilization of node.

change how DaemonSet utilization is calculated

---

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go

This PR provided a way to increase AS group size.

[CA] implements node group increase size

---

charts/cluster-autoscaler-chart/Chart.yaml
charts/cluster-autoscaler-chart/README.md
charts/cluster-autoscaler-chart/values.yaml

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

charts/cluster-autoscaler-chart: fix typos

---

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_auto_scaling_group.go
cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go

Fixed after scaling down spefic numbers of node, the auto scaling group will automatically create corresponding amount of nodes issue.

fixed scaledown issue

---

cluster-autoscaler/README.md
cluster-autoscaler/cloudprovider/builder/builder_all.go
cluster-autoscaler/cloudprovider/builder/builder_cloudstack.go
cluster-autoscaler/cloudprovider/cloud_provider.go
cluster-autoscaler/cloudprovider/cloudstack/OWNERS
cluster-autoscaler/cloudprovider/cloudstack/README.md
cluster-autoscaler/cloudprovider/cloudstack/cloudstack_cloud_provider.go
cluster-autoscaler/cloudprovider/cloudstack/cloudstack_cloud_provider_test.go
cluster-autoscaler/cloudprovider/cloudstack/cloudstack_manager.go
cluster-autoscaler/cloudprovider/cloudstack/cloudstack_manager_test.go
cluster-autoscaler/cloudprovider/cloudstack/cloudstack_node_group.go
cluster-autoscaler/cloudprovider/cloudstack/cloudstack_node_group_test.go
cluster-autoscaler/cloudprovider/cloudstack/cloudstack_option.go
cluster-autoscaler/cloudprovider/cloudstack/examples/cluster-autoscaler-standard.yaml
cluster-autoscaler/cloudprovider/cloudstack/service/cks.go
cluster-autoscaler/cloudprovider/cloudstack/service/cks_test.go
cluster-autoscaler/cloudprovider/cloudstack/service/client.go
cluster-autoscaler/cloudprovider/cloudstack/service/client_test.go
cluster-autoscaler/cloudprovider/cloudstack/testdata/invalid-config
cluster-autoscaler/cloudprovider/cloudstack/testdata/valid-config

Adding support for [Apache CloudStack](https://github.com/apache/cloudstack) as a cloudprovider for the cluster-autoscaler
Link to the CloudStack PR for this - https://github.com/apache/cloudstack/pull/4329

Adding support for Apache CloudStack as a cloudprovider

---

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_auto_scaling_groups.go
cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_cloud_provider.go
cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go

This PR,
1. Added cache for all nodes to reduce API call.
2. Initialize node group from config file, instead of just get all node groups.

added cache for instances

---

cluster-autoscaler/cloudprovider/aws/aws_util.go

cherry-pick #3528 to cluster-autoscaler-release-1.18

Fix pricing endpoint in AWS China Region

---

cluster-autoscaler/cloudprovider/huaweicloud/README.md

This Pr updated README.md for Huawei cloud provider. Describes the installation and deployment process of Cluster Autoscaler in detail.

update readme file

---

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_cache_storage.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_cache_storage_test.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go

Cache controllers 09

---

index.yaml

CA-Chart - 9.3.0 Release

---

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go

Cherry pick #3744 into vpa-release-0.9 branch

Watch only pods in state Running and Unknown

---

cluster-autoscaler/cloudprovider/packet/examples/cluster-autoscaler-deployment.yaml
cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go
cluster-autoscaler/cloudprovider/packet/packet_manager_rest_test.go
cluster-autoscaler/cloudprovider/packet/packet_node_group_test.go
cluster-autoscaler/utils/test/test_utils.go

- Also handle errors that were previously ignored
Fixes: #3461

[cluster-autoscaler][packet] Do not panic on api errors

---

vertical-pod-autoscaler/common/version.go

Vertical Pod Autoscaler release 0.9.1

---

cluster-autoscaler/OWNERS

Self-nominating for a cluster-autoscaler reviewer.
Requirements:
* Member for at least 3 months: I've been a member for over 8 months.
* Primary reviewer for at least 5 PRs to the codebase:
* https://github.com/kubernetes/autoscaler/pull/3701
* https://github.com/kubernetes/autoscaler/pull/3749
* https://github.com/kubernetes/autoscaler/pull/3722
* https://github.com/kubernetes/autoscaler/pull/3321
* https://github.com/kubernetes/autoscaler/pull/3566
* https://github.com/kubernetes/autoscaler/pull/3545
* Reviewed or merged at least 20 substantial PRs to the codebase
* Reviewed the PRs listed above
* Authored these PRs to the codebase: https://github.com/kubernetes/autoscaler/pulls?page=1&q=is%3Apr+author%3Atowca
* Sponsored by a subproject approver: @MaciekPytel

Add towca to cluster-autoscaler Reviewers

---

cluster-autoscaler/README.md
cluster-autoscaler/cloudprovider/builder/builder_all.go
cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go
cluster-autoscaler/cloudprovider/cloud_provider.go
cluster-autoscaler/cloudprovider/ovhcloud/README.md
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_manager.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group_test.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_provider.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_provider_test.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/configuration.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/consumer_key.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/error.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/flavor.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/logger.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/mock.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/node.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/nodepool.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/openstack.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/ovh.go

Hello CA team,
I have added OVHcloud as a provider for your autoscaler.
There is one specific particularity on this, we (at OVHcloud) will be hosting the CA for free on the cluster control-plane, instead of charging the user for it, like other cloud providers 🥳
Feel free to comment any improvements

feature(provider): Add OVHcloud provider

---

cluster-autoscaler/cloudprovider/gce/templates.go
cluster-autoscaler/cloudprovider/gce/templates_test.go

Cherry-pick #3722: update generic labels for GCE

Cherry-pick #3722: update generic labels for GCE

---

cluster-autoscaler/cloudprovider/azure/azure_instance_types.go

Primarily for adding T4 series

Regenerate Azure instances list

---

cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml

This PR fixes sample manifest of cluster-autoscaler clusterapi provider.
Fixes: #3804

Fix cluster-autoscaler clusterapi sample manifest

---

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go

Cherry pick #3807 into VPA 0.9

Wait with jitter between attempts to start watching pod evictions

---

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go

Cherry pick #3806 into VPA 0.9

Revert 3744

---

cluster-autoscaler/cloudprovider/builder/builder_all.go
cluster-autoscaler/cloudprovider/builder/builder_clusterapi.go
cluster-autoscaler/cloudprovider/cloud_provider.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider_test.go

Define clusterapi in cloudprovider layer

---

index.yaml

New chart releases for 9.3.1 and 9.3.2:
* 9.3.1: #3782 
* 9.3.2: #3777

CA Chart Releases - 9.3.1 and 9.3.2

---

cluster-autoscaler/simulator/scheduler_based_predicates_checker.go

Removal of randomness in 1.18 resulted in many pods using the same destination nodes during scaleDown. That in turn caused major regression in scaleDown velocity, decreasing the number of under-utilised nodes removal drastically. Former solution used shuffle to guarantee better variety of destination nodes, this implementation uses deterministic round-robin for the same purpose.

Implement round-robin for SchedulerBasedPredicateChecker

---

cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml

Add services into role of example file

---

index.yaml

* CA Chart release 9.4.0, includes:
* #3725

CA-Chart - 9.4.0 Release

---

cluster-autoscaler/README.md
cluster-autoscaler/cloudprovider/builder/builder_all.go
cluster-autoscaler/cloudprovider/builder/builder_linode.go
cluster-autoscaler/cloudprovider/cloud_provider.go
cluster-autoscaler/cloudprovider/linode/README.md
cluster-autoscaler/cloudprovider/linode/examples/cluster-autoscale-pdb.yaml
cluster-autoscaler/cloudprovider/linode/examples/cluster-autoscaler-autodiscover.yaml
cluster-autoscaler/cloudprovider/linode/examples/cluster-autoscaler-secret.yaml
cluster-autoscaler/cloudprovider/linode/linode_api_client.go
cluster-autoscaler/cloudprovider/linode/linode_cloud_config.go
cluster-autoscaler/cloudprovider/linode/linode_cloud_config_test.go
cluster-autoscaler/cloudprovider/linode/linode_cloud_provider.go
cluster-autoscaler/cloudprovider/linode/linode_cloud_provider_test.go
cluster-autoscaler/cloudprovider/linode/linode_manager.go
cluster-autoscaler/cloudprovider/linode/linode_manager_test.go
cluster-autoscaler/cloudprovider/linode/linode_node_group.go
cluster-autoscaler/cloudprovider/linode/linode_node_group_test.go
cluster-autoscaler/cloudprovider/linode/linode_utils_test.go
cluster-autoscaler/cloudprovider/linode/linodego/README.md
cluster-autoscaler/cloudprovider/linode/linodego/linode_api_client_rest.go
cluster-autoscaler/cloudprovider/linode/linodego/linode_api_client_rest_test.go

This PR add the linode cloud provider for the cluster autoscaler.
I tagged it as WIP because I would like to involve someone from linode to test it more deeply than I could.

cloudprovider: linode cloud provider

---

cluster-autoscaler/cloudprovider/linode/linode_node_group.go

implement new GetOptions method for linode provider

---

.github/workflows/ci.yaml

As Travis or is about to shut down, we are migrating to some alternative. 
Fixes #3825

Test and verify using Git Actions

---

cluster-autoscaler/cloudprovider/aws/OWNERS

Adding myself to the approvers list for the AWS cloud provider in the CA

Add gjtempleton to CA AWS cloud provider OWNERS approvers

---

index.yaml

CA Chart 9.5.0 release, publishes changes made by #3880

CA-Chart - 9.5.0 Release

---

index.yaml

* 9.7.0 Release of Cluster Autoscaler Chart - Changes from #3912

CA-Chart - 9.7.0 Release

---

cluster-autoscaler/expander/priority/priority.go

Bugfix: Expander Priority warns misleading log.

---

cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group_test.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/nodepool.go

Adding the new Autoscaling Opts per node group configuration to OVHcloud provider

feat(ovhcloud): add node group autoscaling options

---

index.yaml

* Pulls in changes from #3932 and #3907
* Fixes #3938

CA-Chart - 9.8.0 and 9.9.0 Release

---

index.yaml

* Brings in changes from #3960 and #3954

CA-Chart - 9.9.1 and 9.9.2 Release

---

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
cluster-autoscaler/cloudprovider/gce/gce_manager.go
cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
cluster-autoscaler/cloudprovider/linode/linodego/linode_api_client_rest_test.go
cluster-autoscaler/cloudprovider/packet/packet_manager_rest_test.go
cluster-autoscaler/cloudprovider/packet/packet_node_group_test.go
cluster-autoscaler/config/autoscaling_options.go
cluster-autoscaler/main.go
cluster-autoscaler/utils/test/test_utils.go

Refactored mocks to remove redundancy.

Set cluster autoscaler-specific user agent.

---

cluster-autoscaler/cloudprovider/azure/azure_template.go

add stable zone labels in template regions

add stable zone labels in azure template generation

---

cluster-autoscaler/clusterstate/clusterstate.go

Log the names of longUnregistered Nodes to make it easier to debug issues where new Nodes are unable to join the cluster.
Resolves https://github.com/kubernetes/autoscaler/issues/4001

Log names of longUnregistered Nodes

---

cluster-autoscaler/estimator/binpacking_estimator.go

This cherry-picks #3429 onto the 1.19 release

Cherry-pick #3429 onto the 1.19 release - Use FitsAnyNode in binpacking

---

cluster-autoscaler/estimator/binpacking_estimator.go
cluster-autoscaler/simulator/predicates_checker_interface.go
cluster-autoscaler/simulator/scheduler_based_predicates_checker.go

This cherry-pick #3429  onto the 1.18 release

Cherry pick #3429 onto 1.18 - Use FitsAnyNode in binpacking

---

addon-resizer/deploy/example.yaml

Add patch deployment permission to example addon resizer deployment

---

cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_manager.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group_test.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/nodepool.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/openstack.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/ovh.go

This MR enables OVHcloud provider to be used for our new product launch at the US

feat(ovh): enable OVHcloud provider for US side

---

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go

Changing a logs line from Info to Warning

Adding support for PERMISSIONS_ERROR in gce cloud provider

---

cluster-autoscaler/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go

Add support for AWS Osaka region

---

cluster-autoscaler/FAQ.md

/hold until https://github.com/kubernetes/autoscaler/pull/4172 is merged

Document DaemonSet eviction opt in/out behavior

---

charts/cluster-autoscaler/README.md

Mandatory awsRegion and optional awsAccessKeyID and awsSecretAccessKey

docs: Install parameters

---

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
cluster-autoscaler/cloudprovider/gce/gce_manager.go

The new `CreateInstances()` upscale method replacing `Resize()` API
calls generates new instances names based on the MIG's name (from
`mig.GceRef()`).
Before that change, `Resize()`-initiated upscales were prompting MIGs to
spawn instances named after MIG's `BaseInstanceName` attribute.
Accordingly, `GetMigForInstance()` still uses MIG's `BaseInstanceName`
to map instances to their parent MIG and discover which MIGs needs an
immediate refresh.
Down the line the `clusterstate.updateReadinessStats()` periodic
goroutines won't be able to map new ready nodes to their parent MIGs
(until the cache is backfilled upward from k8s node's providerid, ie.
from an hourly goroutine), and those MIGs will be considered non-ready
(because MIG's size>0 while the MIG has no known ready instances).
So after …

GCE: CreateInstances() should use BaseInstanceName

---

cluster-autoscaler/core/utils/utils.go
cluster-autoscaler/utils/labels/labels.go

This is a useful function, we will benefit from having it more accessible than it is currently.

Move UpdateDeprecatedTemplateLabels function

---

cluster-autoscaler/cloudprovider/aws/aws_manager.go

Fix #4045
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>

Improve misleading log

---

cluster-autoscaler/cloudprovider/azure/README.md

presources → resources

---

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go

Now the test fails, it will pass after #4102 merges

Add a test for clusterStateFeeder.InitFromHistoryProvider

---

cluster-autoscaler/cloudprovider/packet/README.md
cluster-autoscaler/cloudprovider/packet/packet_cloud_provider.go
cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go

As per this [comment](https://github.com/kubernetes/autoscaler/pull/4274#issuecomment-902146894)
Backporting the fix to upstream/cluster-autoscaler-release-1.21

Backport Merge pull request #4274 to upstream/cluster-autoscaler-release-1.21

---

cluster-autoscaler/cloudprovider/packet/README.md
cluster-autoscaler/cloudprovider/packet/packet_cloud_provider.go
cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go

As per this [comment](https://github.com/kubernetes/autoscaler/pull/4274#issuecomment-902146894)
Backporting the fix to upstream/cluster-autoscaler-release-1.22

Backport Merge pull request #4274 to upstream/cluster-autoscaler-release-1.22

---

cluster-autoscaler/cloudprovider/packet/README.md
cluster-autoscaler/cloudprovider/packet/packet_cloud_provider.go
cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go

As per this [comment](https://github.com/kubernetes/autoscaler/pull/4274#issuecomment-902146894)
Backporting the fix to upstream/cluster-autoscaler-release-1.19

Backport Merge pull request #4274 to upstream/cluster-autoscaler-release-1.19

---

charts/cluster-autoscaler/Chart.yaml
charts/cluster-autoscaler/templates/deployment.yaml

[CA][HELM]fix not being able to set args without value

---

cluster-autoscaler/cloudprovider/aws/README.md

Fixes https://github.com/kubernetes/autoscaler/issues/4189.

[ca] Update AWS docs for ASG tags

---

cluster-autoscaler/cloudprovider/azure/azure_instance_types.go

Addressing issue https://github.com/kubernetes/autoscaler/issues/4336

Add Standard_ND96asr_v4

---

cluster-autoscaler/cloudprovider/cloudstack/examples/cluster-autoscaler-standard.yaml

Updates the image with the official one from the apache repo

Update image for cloudstack cluster-autoscaler

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go

Cherry-pick #4130: dont proactively decrement azure cache for unregistered nodes

---

cluster-autoscaler/cloudprovider/aws/aws_manager.go
cluster-autoscaler/cloudprovider/aws/aws_manager_test.go

This change is the first change for the AWS EKS Managed Nodegroups support for scale-to-0 changes in the cluster autoscaler. It checks for the AWS EKS specific tags that we automaticaly add for Managed Nodegroups.
This change also adds unit tests for the new tag labels.
Example of the "Nodegroup %s is an EKS managed nodegroup." log line being shown with a log verbosity of --v=5
```
I0903 00:10:06.770366       1 filter_out_schedulable.go:157] Pod default.static-web marked as unschedulable can be scheduled on node template-node-for-eks-test-cas-ng-gpu-d8bdd47d-8232-234e-0544-7d7b3f16519d-8999011805617471788-upcoming-0. Ignoring in scale up.
I0903 00:10:06.770378       1 filter_out_schedulable.go:170] 0 pods were kept as unschedulable based on caching
I0903 00:10:06.770383       1 …
```

[AWS EKS - Scale-to-0] Add check for the AWS EKS tags on the ASG

---

cluster-autoscaler/cloudprovider/gce/templates.go

Sorry, didn't re-run verify after I addressed this comment: https://github.com/kubernetes/autoscaler/pull/4318#discussion_r716558463

exported const LocalSSDDiskSizeInGiB should have comment

---

addon-resizer/OWNERS

Add jbartosik to addon-resizer OWNERS

---

OWNERS

Add gjtempleton to top level OWNERS

---

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go

This PR resolves the issue #4453.
It removes deprecated CAPI annotations.

Fixes issue #4453 Removes Deprecated CAPI Annotations

---

cluster-autoscaler/cloudprovider/builder/builder_all.go
cluster-autoscaler/cloudprovider/cloud_provider.go

This adds packet provider in the Available cloud provider list.

Register packet provider in all builder

---

cluster-autoscaler/core/scale_up.go

Closes https://github.com/kubernetes/autoscaler/issues/4007

Improve ScaledUpGroup event info to include current & max nodes

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go

fix scale set log formatter

---

vertical-pod-autoscaler/e2e/utils/ooming_resource_consumer/Dockerfile
vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go
vertical-pod-autoscaler/e2e/v1beta2/autoscaling_utils.go

Switch VPA OOM E2E tests from custom image to upstream image

---

cluster-autoscaler/cloudprovider/azure/azure_util_test.go

/kind cleanup
chore: remove a time-consuming unit test in provider azure
Fixes #4551
```release-note
NONE
```
```docs
```

chore: remove a time consuming unit test in provider azure

---

cluster-autoscaler/cloudprovider/azure/azure_util_test.go

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>
Fixes #
```release-note
NONE
```
```docs
```

Remove TestDeleteBlob UT

---

cluster-autoscaler/cloudprovider/azure/azure_util_test.go

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>
Fixes #
```release-note
```
```docs
```

[Cherry pick 1.21] Remove TestDeleteBlob UT

---

cluster-autoscaler/cloudprovider/azure/azure_util_test.go

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>
Fixes #
```release-note
```
```docs
```

Remove variables not used in azure_util_test

---

cluster-autoscaler/cloudprovider/azure/azure_util_test.go

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>
Cherry-picked from https://github.com/kubernetes/autoscaler/pull/4626
Fixes #
```release-note
```
```docs
```

[Cherry pick1.23] Remove TestDeleteBlob UT

---

vertical-pod-autoscaler/common/version.go

VPA release 0.10.0

---

cluster-autoscaler/cloudprovider/azure/azure_instance_types.go
cluster-autoscaler/cloudprovider/azure/azure_template.go

Add NP-series and handle the SKU API information correctly

update azure instances and template with np-series SKU

---

cluster-autoscaler/debuggingsnapshot/debugging_snapshotter.go

Cluster autoscaler
/kind feature
Fixes #
```release-note
```
```docs
```

CA: Debugging snapshotter locking optimisation for better transactions

---

vertical-pod-autoscaler/hack/run-e2e-tests.sh

Increase `--test.timeout` for e2e tests

---

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

Minor update of bundled config fallback - updates the bundled hardcoded AWS instance type data to today, including the new c6a instance family.
N/A
```release-note
NONE
```
```docs
```

CA - AWS - Instance List Update 16-02-22

---

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates_test.go
vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler_test.go
vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer_test.go
vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_cache_storage_test.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go
vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
vertical-pod-autoscaler/pkg/recommender/input/history/history_provider_test.go
vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go
vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go
vertical-pod-autoscaler/pkg/recommender/input/spec/spec_client_test_util.go
vertical-pod-autoscaler/pkg/recommender/logic/estimator_test.go
vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state_test.go
vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go
vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
vertical-pod-autoscaler/pkg/recommender/util/decaying_histogram_test.go
vertical-pod-autoscaler/pkg/target/fetcher.go
vertical-pod-autoscaler/pkg/updater/main.go
vertical-pod-autoscaler/pkg/utils/metrics/admission/admission.go
vertical-pod-autoscaler/pkg/utils/metrics/healthcheck.go
vertical-pod-autoscaler/pkg/utils/metrics/metrics.go
vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go
vertical-pod-autoscaler/pkg/utils/test/test_pod.go
vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
vertical-pod-autoscaler/pkg/utils/vpa/api_test.go
vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go

/kind cleanup
This is a code refactoring for vertical pod autoscaler aimed to meet current golang code formatting requirements.
No
```release-note
None
```

Fix lint issues in vertical pod autoscaller

---

cluster-autoscaler/update_toc.py
hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/scripts/break_mig.py
hack/scripts/ca_metrics_parser.py

Cluster-Autoscaler
Cleanup
This PR makes Autoscaler compatible with Python3, since python2 is deprecated.
Fixes #
```release-note
```
```docs
```

Migrate CA off python2 to python3

---

cluster-autoscaler/FAQ.md

Signed-off-by: Sergey Shevchenko <sergeyshevchdevelop@gmail.com>
Update API version of PriorityClass in overprovisioning example
Fixes #4643 
```release-note
NONE
```
```docs
```

[ca]: Upgrade PriorityClass api version in FAQ.md

---

vertical-pod-autoscaler/hack/run-e2e-tests.sh

/kind bug
Workaround for #4764

Work around VPA e2e test failures

---

addon-resizer/Makefile

Addon Resizer
/kind cleanup
Bump Addon Resizer version so we can release it with support for more archs.

Addon resizer 1.18.5

---

builder/Dockerfile

/kind feature
Fixes #
```release-note
```
```docs
```

Update golang to go1.18

---

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml

cluster-autoscaler 
/kind feature
This PR upgrades the Cluster Autoscaler images in aws example. 
Fixes #4879
```
NONE
```
```
NONE
```

Upgrade CA images to v1.22.2 in aws example.

---

cluster-autoscaler/cloudprovider/gce/gce_reserved.go
cluster-autoscaler/cloudprovider/gce/gce_reserved_test.go

/kind feature
Fixes #
```release-note
```
```docs
```

Offset Reserved memory and ephemeral storage for ARM arch in GCE

---

cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go
cluster-autoscaler/cloudprovider/gce/templates.go
cluster-autoscaler/cloudprovider/gce/templates_test.go

/kind feature
Fixes #
```release-note
```
```docs
```

Setting Arch Label in GCE node

---

cluster-autoscaler/cloudprovider/oci/oci_instance_pool_manager.go
cluster-autoscaler/cloudprovider/oci/oci_ref.go

cluster-autoscaler (OCI provider code)
/kind cleanup
/kind feature
This PR adds a couple _incremental_ updates to the OCI (Instance-Pool) cloud provider including:
- Avoiding searching for node if it has annotations indicating its ID
- Checking for both deprecated and non-deprecated well known Kubernetes label keys
Fixes #
I am the original author of the provider code in question and listed in the [OWNERS](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/oci/OWNERS) file  (although I am temporarily commented out until I complete the [Kubernetes Community Membership process](https://github.com/kubernetes/community/blob/master/community-membership.md#member)).
```release-note
Minor updates and improvements. 
```
```docs
```

Minor updates and improvements to the OCI (Instance-Pool) cloud provider

---

cluster-autoscaler/core/scaledown/actuation/actuator_test.go

The issue could be reproduced by:
```
go test ./core/scaledown/actuation -run TestStartDeletion -race -count=1000 | tee test.log
```

CA: fix a data race in actuation.TestStartDeletion

---

cluster-autoscaler/core/scaledown/actuation/actuator_test.go

Part of the test verifies if all taint updates happened as expected.
The taints are verified asynchronously, and the test waits for exactly
as many taint updates as defined in the test case. A couple of test
cases were missing some expected updates (clearing the taint if
drain/deletion fails). The test could randomly fail if one of the
missing updates happened to apear before one of the expected updates.
This commit adds the missing expected updates, all should be accounted
for now.
This commit also adds a sync point to wait for all expected node
deletion results before asserting them. Without it, the test would
sometimes move to the assertion before the results were actually
reported.

CA: fix flakiness in actuation.TestStartDeletion

---

cluster-autoscaler/version/version.go

Cluster-autoscaler
/kind feature
Increments version for 1.23.1 patch release of the CA.
Fixes #
```release-note
```
```docs
```

Cluster Autoscaler - 1.23.1 release

---

cluster-autoscaler/version/version.go

Cluster-autoscaler
/kind feature
Increments version for 1.20.3 patch release of the CA.
Fixes #
```release-note
```
```docs
```

Cluster Autoscaler - 1.20.3 release

---

cluster-autoscaler/version/version.go

Cluster-autoscaler
/kind feature
Increments version for 1.22.3 patch release of the CA.
Fixes #
```release-note
```
```docs
```

Cluster Autoscaler - 1.22.3 release

---

cluster-autoscaler/push_image.sh

Cluster-autoscaler
/kind feature
Adds branching logic for the image push command to run based on the version of Docker being used to push the images as per: https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker
N/A
Open question: Do we even need to continue support for the `gcloud docker --` command given the age of the docker version this requires?
```release-note
```
```docs
```

CA - Push Image script - Support newer docker versions

---

charts/cluster-autoscaler/Chart.yaml

CA Helm Chart.
/kind cleanup
Removes old maintainers from the Chart.
Fixes #
cc: @yurrriq @sc250024 @mgoodness  please let me know if any of you actually still want to be involved in maintaining this, however figured best to remove the risk of any of you being pestered to support something you're no longer actively involved with.
```release-note
```
```docs
```

CA Chart - Cleanup Chart Maintainers

---

vertical-pod-autoscaler/README.md

/kind bug
This PR fixed the Hyperlinks of HPA for `Resource metrics` and `Custom and external metrics`
Fixes #5026
```
NONE
```

Fixed the Hyperlinks of HPA.

---

cluster-autoscaler/cloudprovider/aws/OWNERS

Cluster-autoscaler AWS cloudprovider.
/kind cleanup
Moves @Jeffwan to emeritus approver status after discussion with them as they're no longer active in this area. Thanks for all your work to this point!
Fixes #
```release-note
```
```docs
```

CA - AWS - Move Jeffwan to emeritus approvers

---

vertical-pod-autoscaler/README.md

/kind bug
This PR updates the Compatibility section under README of VPA. 
Fixes #4897
```
NONE
```

Corrected the VPA Compatibility.

---

cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment-control-plane.yaml
cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment.yaml
cluster-autoscaler/cloudprovider/magnum/examples/values-autodiscovery.yaml
cluster-autoscaler/cloudprovider/magnum/examples/values-example.yaml

cluster-autoscaler/Openstack magnum
/kind feature
This PR upgraded openstackmagnum/cluster-autoscaler image version to the latest release version of it. 
Fixes #5066
```
NONE
```

Bump openstackmagnum/cluster-autoscaler image version.

---

vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go

VPA recommender
/kind feature
Make it easier to detect when VPA is not working because it can't get
metrics. Currently one can check logs to do that but having a metric makes the
information easier to use.
Metric reports only error / no error because parsing error messages for more
detailed info would easily break / be more work to maintain than I think it's
worth and we don't have access to structured details.
<!--
```release-note
Added metric_server_responses metric
```
```docs
```

Export metric about result of queried VPA makes to metrics server

---

vertical-pod-autoscaler/pkg/recommender/main.go

This should be part of #5100
VPA
/kind bug
/kind cleanup
```release-note
NONE
```
```docs
```

Register VPA metrics client metrics

---

cluster-autoscaler/core/scale_up.go

/kind cleanup
The loop jumping made this code hard to understand for me, so trying to make it clearer.
```release-note
NONE
```

cluster-autoscaler: avoid goto in filterNodeGroupsByPods

---

cluster-autoscaler/cloudprovider/clusterapi/README.md

/kind cleanup
to be more accurate about scale from zero support.
Fixes #
```release-note
```
```docs
```

update clusterapi readme

---

cluster-autoscaler/cloudprovider/kamatera/kamatera_node_group_test.go

/kind bug
fixes a non-determinstic unit test
Fixes #5134
```release-note
NONE
```

cluster-autoscaler: fix non-deterministic kamatera cloudprovider unit test

---

charts/cluster-autoscaler/Chart.yaml
charts/cluster-autoscaler/README.md
charts/cluster-autoscaler/templates/podsecuritypolicy.yaml
charts/cluster-autoscaler/values.yaml

cluster-autoscaler helm chart
/kind bug
Remove leftovers after [#3907](https://github.com/kubernetes/autoscaler/pull/3907)
Fixes #5128 
```release-note
NONE
```
```docs
```

helm chart - remove obsolete GCE cloudConfigPath usage

---

cluster-autoscaler/core/scaledown/pdb/pdb.go
cluster-autoscaler/core/scaledown/pdb/pdb_test.go

/kind feature
A part of Scale Down in Parallel implementation

Add PdbRemainingDisruptions struct

---

cluster-autoscaler/cloudprovider/gce/OWNERS

Fixes #
```release-note
```
```docs
```

Create GCE CloudProvider Owners file

---

cluster-autoscaler/core/scaledown/legacy/legacy.go
cluster-autoscaler/core/scaledown/legacy/legacy_test.go

/kind bug
/kind cleanup
This filtering was used for two purposes:
- Excluding masters from destination candidates
- Excluding masters from calculating cluster resources
Excluding from destination candidates isn't useful: if pods can schedule
there, they will, so removing them from CA simulation doesn't change
anything.
Excluding from calculating cluster resources actually matches scale up
behavior, where master nodes are treated the same way as regular nodes.
Fixes #
This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5131. Only the last commit should be reviewed as a part of this PR. It will be on hold until the previous one is merged.
/hold
```release-note
Nodes hosting kube-apiserver are no longer treated differently in scale-down logic. The special …
```

Stop treating masters differently in scale down

---

cluster-autoscaler/cloudprovider/civo/examples/cluster-autoscaler-standard.yaml

Signed-off-by: Vishal Anarse <vishalanarse11@gmail.com>
/kind cleanup
It fixes the example spec of `civo` cloude provider
Fixes #5225
Cleaning up the example spec 
```release-note
NONE
```
```docs
```

Update the example spec of civo cloudprovider

---

vertical-pod-autoscaler/README.md
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml

Adds documentation for https://github.com/kubernetes/autoscaler/pull/4799
Fixes #
```release-note
```
```docs
```

add example for multiple recommenders

---

cluster-autoscaler/cloudprovider/aws/aws-sdk-go/service/auditmanager/api.go
cluster-autoscaler/cloudprovider/aws/aws-sdk-go/service/chimesdkmessaging/api.go
cluster-autoscaler/cloudprovider/aws/aws-sdk-go/service/clouddirectory/api.go
cluster-autoscaler/cloudprovider/aws/aws-sdk-go/service/kms/api.go

/kind bug
This PR fixed the `fmt` error by running `./hack/update-gofmt.sh`

Fixed gofmt error.

---

vertical-pod-autoscaler/README.md

VPA
Fixes #
```release-note
NONE
```

Update VPA compatibility for 0.12 release

---

vertical-pod-autoscaler/README.md

VPA
Fixes #
```release-note
NONE
```

Update VPA compatibility for 0.12 release (release branch)

---

cluster-autoscaler/cloudprovider/azure/OWNERS

Updates owners list in azure-cluster autoscaler
Fixes #
```release-note
NONE
```
```docs
```

update owners list for cluster autoscaler azure

---

balancer/proposals/balancer.md

Balancer - a new autoscaling component.
Initial proposal.
This is SIG-Autoscaling internal KEP.

Balancer KEP

---

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go

Signed-off-by: jwcesign <jiangwei115@huawei.com>
/kind feature
* If there are more than 20 ecs instances, the original logic only get first page(one page contains 20), will cause waiting until timeout. So we change the logic to get all page list.
* ecs creation is quite slow,  make timeout  longer.
Fixes none
none
```release-note
none
```
```docs
none
```

huawei-cloudprovider: enable retrieve scaling group instances by pages

---

cluster-autoscaler/core/scaledown/actuation/actuator.go
cluster-autoscaler/core/scaledown/actuation/drain.go
cluster-autoscaler/core/scaledown/actuation/drain_test.go

/kind feature
Part of parallel scale down implementation.

[CA] Register recently evicted pods in NodeDeletionTracker.

---

balancer/proposals/balancer.md
vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/types.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/types.go

addon-resizer,vertical-pod-autoscaler
The link to api-conventions markdown file has been changed, but many of the code comments in the repo have not been updated, which can cause inconsistencies.
Fixes #
NONE
```release-note
```
```docs
```

Update the hyperlinks of api-conventions.md file in comments

---

addon-resizer/Makefile

Addon Resizer
/kind release
Release to provide health-check / livenessProbe for Addon Resizer (release #5234).

Addon Resizer version 1.8.16

---

cluster-autoscaler/core/filteroutschedulable/filter_out_schedulable_test.go
cluster-autoscaler/core/scale_up.go
cluster-autoscaler/core/scaledown/planner/planner.go
cluster-autoscaler/estimator/binpacking_estimator.go
cluster-autoscaler/simulator/cluster.go
cluster-autoscaler/simulator/clustersnapshot/basic.go
cluster-autoscaler/simulator/clustersnapshot/clustersnapshot.go
cluster-autoscaler/simulator/clustersnapshot/clustersnapshot_benchmark_test.go
cluster-autoscaler/simulator/clustersnapshot/clustersnapshot_test.go
cluster-autoscaler/simulator/clustersnapshot/delta.go

/kind feature
Forking twice is needed for parallel scale down implementation.

Allow forking snapshot more than 1 time

---

cluster-autoscaler/cloudprovider/hetzner/OWNERS

cluster-autoscaler Hetzner Provider
Add myself as an approver and reviewer for the directory `cluster-autoscaler/cloudprovider/hetzner`. I am employed at Hetzner Cloud and work on our Open Source Integrations, including the `cluster-autoscaler` provider.
As I am a member of the k8s org, I removed the comments so the bot can automatically assign me to new PRs.
Fixes #
```release-note
```
```docs
```

chore(cluster-autoscaler/hetzner): add myself to OWNERS file

---

cluster-autoscaler/config/autoscaling_options.go
cluster-autoscaler/core/scaledown/planner/planner.go
cluster-autoscaler/core/static_autoscaler.go
cluster-autoscaler/main.go

/kind feature
part of parallel scale down implementation

Create a Planner object if  --parallel-drain=true 

---

charts/OWNERS

helm charts
Automates labelling of Helm Chart related PRs with the appropriate label. Idea stolen shamelessly from #5348 .
Fixes #
```release-note
NONE
```
```docs
```

Auto Label Helm Chart PRs

---

cluster-autoscaler/cloudprovider/cherryservers/cherry_manager_rest.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
cluster-autoscaler/cloudprovider/oci/oci_instance_pool_manager.go
cluster-autoscaler/cloudprovider/oci/oci_shape_test.go
cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go
cluster-autoscaler/proposals/min_at_zero_gcp.md
cluster-autoscaler/utils/labels/labels.go

/kind cleanup
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.
```release-note
Stop applying the beta.kubernetes.io/os and arch
```

Stop applying the beta.kubernetes.io/os and arch

---

cluster-autoscaler/processors/nodegroupset/balancing_processor.go

/kind cleanup
Was getting confused when reading the code, I think this expresses the intent better.

cluster-autoscaler: refactor BalanceScaleUpBetweenGroups

---

cluster-autoscaler/cloudprovider/oci/OWNERS

cluster-autoscaler Oracle Cloud Provider
other
After becoming a Kubernetes org member (thanks @MaciekPytel and @gjtempleton), this PR un-comments my username as an approver and reviewer for the cluster-autoscaler Oracle Cloud provider (`cluster-autoscaler/cloudprovider/oci`). 
I am employed by Oracle and the original author of the implementation. 
Fixes #
```release-note
```
```docs
```

uncomment myself in Oracle Cloud OWNERS file (after joining Kubernetes org)

---

.github/PULL_REQUEST_TEMPLATE.md
addon-resizer/OWNERS
vertical-pod-autoscaler/OWNERS

Rely on labels instead.
Stop asking humans for work robots can do.
Fixes #
```release-note
NONE
```
```docs
```

Stop asking PR creators to name modified components

---

cluster-autoscaler/FAQ.md

cluster-autoscaler FAQ documentation
fix typo in FAQ documentation
```release-note
NONE
```
```docs
```

fix typo in FAQ

---

cluster-autoscaler/cloudprovider/POLICY.md

Clarifying the policy after discussion on last SIG meeting.
Fixes #
```release-note
NONE
```
```docs
```

State expectations around cloudprovider OWNERS

---

addon-resizer/README.md

Update addon-resizer README regerding estimator flag.

---

cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml

Fixes #
```release-note
```
```docs
```

fix: alicloud provider example yaml

---

cluster-autoscaler/expander/grpcplugin/grpc_client.go

Expander requests' payloads can be rather heavy under upscale pressure, as they're compounding all candidates options and unschedulable pods that could fit each options. Expander responses are a subset of the requests' payload items.
We're allowing ourself to send arbitrary payload sizes (gRPC `defaultClientMaxSendMessageSize` is `math.MaxInt32`), but we're prone to drop expander servers responses to the floor, due to the `4MiB` `defaultClientMaxReceiveMessageSize`.
The arbitrary 128MiB value is meant to be huge (enough to support eg. several dozen fat 1MiB pods) but not unlimited. Let me know if you'd rather see that turned to be a command line flag, or an other value.
Also logging the possible gRPC call errors, as that of great help to diagnose that kind of issues.
/kind bug

gRPC expander: allow realistic server responses, and log errors

---

cluster-autoscaler/cloudprovider/clusterapi/README.md

/kind cleanup
this change adds a little more detail to ensure that users understand how to use the GPU label feature.
Fixes #
```release-note
```
```docs
```

add an extra note to clusterapi readme about gpus

---

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go
cluster-autoscaler/cloudprovider/gce/gce_manager.go
cluster-autoscaler/cloudprovider/gce/gce_reserved.go
cluster-autoscaler/cloudprovider/gce/gce_reserved_test.go
cluster-autoscaler/cloudprovider/gce/os_reserved.go
cluster-autoscaler/cloudprovider/gce/templates.go
cluster-autoscaler/cloudprovider/gce/templates_test.go

GCE: Add os parameters to MigOsInfo interface

---

charts/cluster-autoscaler/Chart.yaml
charts/cluster-autoscaler/README.md
charts/cluster-autoscaler/README.md.gotmpl
charts/cluster-autoscaler/templates/deployment.yaml
charts/cluster-autoscaler/values.yaml

Adds support for helm chart to work on OCI OKE

Helm chart OCI-OKE support

---

vertical-pod-autoscaler/RELEASE.md

Add step-by-step instructions for VPA release process.

Add instructions for VPA release

---

vertical-pod-autoscaler/README.md
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml

Update default versions in recommender high and low deployments

---

.github/ISSUE_TEMPLATE/vpa_release.md
vertical-pod-autoscaler/RELEASE.md

Update vpa release docs

---

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go

The CreateInstances is passed a list of provider ids, which is not the same as the list of names: provider id includes zone and project information as well. This can cause scale ups in large clusters to occassionally fail.
/kind bug
Fixes a bug affecting scale up performance.
Fixes #
```release-note
Fixed a bug in GCE cloud provider causing large scale ups to occasionally fail.
```
```docs
```

Fix MEMBER_ALREADY_EXISTS errors in GCE cloudprovider

---

cluster-autoscaler/OWNERS

Self-nominating for a cluster-autoscaler reviewer.
Requirements:
- Member for at least 3 months: satisfied, I've been a memeber for ~11 months. https://github.com/kubernetes/org/issues/3303
- Primary reviewer for at least 5 PRs to the codebase:
- https://github.com/kubernetes/autoscaler/pull/5459
- https://github.com/kubernetes/autoscaler/pull/5439
- https://github.com/kubernetes/autoscaler/pull/4993
- https://github.com/kubernetes/autoscaler/pull/4660
- https://github.com/kubernetes/autoscaler/pull/3636
- Reviewed or merged at least 20 substantial PRs to the codebase
- Reviewed the 5 PRs above
- Merged a total of 25 PRs: https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+author%3ABigDarkClown
- Sponsored by a subproject approver: @towca

Add BigDarkClown to cluster-autoscaler Reviewers

---

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

/kind feature
Fixes #
AWs announced m7g instance types yesterday
https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-ec2-m7g-r7g-instances/
```release-note
support new ec2 instance types: m7g/r7g
```
```docs
```

regenerate the ec2 instance types using latest metadata to fetch m7g/r7g instances

---

vertical-pod-autoscaler/go.mod
vertical-pod-autoscaler/go.sum
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/CHANGES.md
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/README.md
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/constants.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/filter_adapter.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/parameter.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/request.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/response.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/route.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/route_builder.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/web_service.go
vertical-pod-autoscaler/vendor/modules.txt

/kind cleanup
To pull in a fix for vulnerability in the dependency
#5455

Update VPA dependency github.com/emicklei/go-restful/v3

---

vertical-pod-autoscaler/builder/Dockerfile
vertical-pod-autoscaler/go.mod
vertical-pod-autoscaler/go.sum
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/CHANGES.md
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/README.md
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/constants.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/filter_adapter.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/parameter.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/request.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/response.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/route.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/route_builder.go
vertical-pod-autoscaler/vendor/github.com/emicklei/go-restful/v3/web_service.go
vertical-pod-autoscaler/vendor/modules.txt

Cherry pick #5482 and #5484 to VPA release 0.13 branch
/kind bug
#5455 
```docs
Update dependencies with known security vulnerabilities
```

Cherry pick #5482 and #5484 to VPA release 0.13 branch

---

cluster-autoscaler/expander/mostpods/mostpods.go

/kind cleanup
Fix a minor typo
NONE

Fix a minor typo

---

addon-resizer/enhancements/README.md

I noticed the directory is missing

Create enhancements directory for Addon Resizer

---

cluster-autoscaler/cloudprovider/ovhcloud/sdk/error.go
cluster-autoscaler/cloudprovider/ovhcloud/sdk/ovh.go

/kind bug
Should cover the cases where a Canadian project has been freshly created and OVHCloud Canadian authentication API has not yet synced with EU authentication API.
Retrying the same call on the Canadian API should successfully authenticate and succeed. This is a temporary fix until the issue is correctly handled.
This fix has already been released in production for the cluster-autoscaler instances running on the OVHcloud Managed Kubernetes product.
NONE

ovhcloud: For any call to api.ovh.com returning a 500 error, retry call on ca.api.ovh.com

---

vertical-pod-autoscaler/hack/generate-crd-yaml.sh

/kind bug
Seems like I got the version wrong when switching from `@latest` to `@v0.9.2` in https://github.com/kubernetes/autoscaler/pull/5178. This came in [via a comment in PR review](https://github.com/kubernetes/autoscaler/pull/5178#discussion_r970559779) and it seems I never re-validated after changing the version ;(
Fixes errors like this
```
./vertical-pod-autoscaler/hack/generate-crd-yaml.sh
go: sigs.k8s.io/controller-tools/cmd/controller-gen@0.9.2: sigs.k8s.io/controller-tools/cmd/controller-gen@0.9.2: invalid version: unknown revision 0.9.2
```
```release-note
NONE
```
```docs
```

Fix controller-gen version in automatic download

---

vertical-pod-autoscaler/MIGRATE.md
vertical-pod-autoscaler/README.md
vertical-pod-autoscaler/enhancements/4902-delete-oom-pods/README.md
vertical-pod-autoscaler/pkg/admission-controller/README.md
vertical-pod-autoscaler/pkg/admission-controller/certs.go
vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh
vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/types.go
vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/types.go
vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go
vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go
vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go
vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go
vertical-pod-autoscaler/pkg/recommender/model/container.go
vertical-pod-autoscaler/pkg/recommender/model/vpa_test.go
vertical-pod-autoscaler/pkg/target/mock/fetcher_mock.go
vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go
vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go
vertical-pod-autoscaler/pkg/updater/logic/updater.go
vertical-pod-autoscaler/pkg/updater/priority/priority_processor_test.go
vertical-pod-autoscaler/pkg/utils/metrics/admission/admission.go
vertical-pod-autoscaler/pkg/utils/status/status_object.go
vertical-pod-autoscaler/pkg/utils/vpa/capping.go
vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go

/kind cleanup
1. fix typo
2. replace deprecated functions
3. add some constants in tests and replace literals with them
Fixes #
```release-note
NONE
```
```docs
NONE
```

Fix typo & replace deprecated functions & replace literals with constants

---

vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go

Fixes test broken by #5621 by allowing a broken Deployment to be accepted by the test.
I know that accepting a broken Deployment is ugly but we do need such a deployment to be relatively sure that no regular metrics can be detected by VPA - we want to test  #5326 which accepts OOMs w/o regular samples.
I am sorry for breaking it in the first place.
Logs from one of the multiple test runs I did with this PR:
```
STEP: Building a namespace api object, basename vertical-pod-autoscaling 03/27/23 15:47:32.55
STEP: Waiting for a default service account to be provisioned in namespace 03/27/23 15:47:32.939
STEP: Waiting for kube-root-ca.crt to be provisioned in namespace 03/27/23 15:47:33.193
STEP: Setting up a hamster deployment 03/27/23 15:47:33.446
STEP: Running OOMing RC …
```

Fix the setup for allow containers to fail (they should be OOM-killed)

---

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go

/kind cleanup
This is a final follow-up to [PR ](https://github.com/kubernetes/autoscaler/pull/5627), which makes some of the common orchestrator functions public.
No, some functions of scaleup orchestrator are available for power users to use.
/assign @mwielgus

CA orchestrator exports new methods/functions

---

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go

This simplifies the 'ComputeExpansionOption' and allows us to use defer
to revert the ClusterSnapshot rather than calling it explicitly on each exit from the method.
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```

Extract 'SchedulablePods' method in orchestrator.

---

cluster-autoscaler/cloudprovider/gce/gce_price_info.go

/kind feature
Add pricing for G2 machines.
Fixes # N/A
NONE
```release-note
```
```docs
```

Cluster Autoscaler: GCE: add pricing info for G2

---

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml
cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml
cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml
cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml

Fixes #
```release-note
```
```docs
```

feat: upgrade latest version cluster-autoscaler on cluster-autoscaler-autodiscover.yaml

---

cluster-autoscaler/cloudprovider/alicloud/README.md

/kind bug
The deploy spec in README is incorret.
Fixes #
```release-note
NONE
```
```docs
```

fix ca deploy spec

---

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

🍒 from 1.24 branch
/kind feature
Fixes #
```release-note
NONE
```
```docs
```

Added support for the AWS Trainium instance types

---

cluster-autoscaler/utils/taints/taints.go
cluster-autoscaler/utils/taints/taints_test.go

/kind feature
Fixes #
```release-note
```
```docs
```

Refactor taints.go to support taint values

---

cluster-autoscaler/cloudprovider/aws/aws_manager_test.go

/kind bug
Brings in tests for #5737
Fixes #5164
Special notes for your reviewer:
NONE

tests for asg resource tags fix 1.24

---

cluster-autoscaler/cloudprovider/aws/aws_manager_test.go

/kind bug
Brings in tests for #5722
Fixes #5164
Special notes for your reviewer:
NONE

tests for asg resource tags fix 1.26

---

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go

/kind fix
This change fixes an issue introduced in #5750. For non-existing node groups we do not calculate `schedulablePods` for the main node group returned from the `CreateNodeGroup` call. This breaks the node group balancing if the selected scale-up included non-existing node group.

Fix similar node group calculation for non-existing node groups

---

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

/kind feature
Fixes #
```release-note
NONE
```
```docs
```

Add preview EC2 instance type p4de.24xlarge

---

cluster-autoscaler/cloudprovider/alicloud/README.md

Fixes #5765
```NONE
```
```docs
```

Update ACK help doc link in  README.md

---

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/credentials/oidc_credential.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signer.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signers/signer_oidc.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client_test.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ecs/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/client.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types_test.go
cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-rrsa-standard.yaml

/kind feature
Fixes #
```release-note
None
```
```docs
```

Cluster autoscaler release 1.24 - Support RRSA auth in AliCloud

---

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/credentials/oidc_credential.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signer.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signers/signer_oidc.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client_test.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ecs/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/client.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types_test.go
cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-rrsa-standard.yaml

/kind feature
Fixes #
```release-note
None
```
```docs
```

Cluster autoscaler release 1.25 - Support RRSA auth in AliCloud

---

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/credentials/oidc_credential.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signer.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signers/signer_oidc.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client_test.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ecs/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/client.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types_test.go
cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-rrsa-standard.yaml

/kind feature
Fixes #
```release-note
None
```
```docs
```

Cluster autoscaler release 1.26 - Support RRSA auth in AliCloud

---

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/credentials/oidc_credential.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signer.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signers/signer_oidc.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/client_test.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ecs/client.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/client.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_instance_types_test.go
cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-rrsa-standard.yaml

/kind feature
Fixes #
```release-note
None
```
```docs
```

Cluster autoscaler release 1.27 - Support RRSA auth in AliCloud

---

cluster-autoscaler/README.md

This PR updated the version compatibility for CA under the[ Release table](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/README.md#releases) in README.md
```release-note
NONE
```
```docs
```

Update version compatibility for CA.

---

cluster-autoscaler/FAQ.md

Include some examples of what is considered a local volume, following [this Slack-thread](https://kubernetes.slack.com/archives/C09R1LV8S/p1684847335912849).
```release-note
NONE
```
```docs
```

docs(ca/faq): Include examples of local volumes and volumes not considered local

---

cluster-autoscaler/cloudprovider/alicloud/OWNERS
cluster-autoscaler/cloudprovider/aws/OWNERS
cluster-autoscaler/cloudprovider/azure/OWNERS
cluster-autoscaler/cloudprovider/baiducloud/OWNERS
cluster-autoscaler/cloudprovider/bizflycloud/OWNERS
cluster-autoscaler/cloudprovider/brightbox/OWNERS
cluster-autoscaler/cloudprovider/cherryservers/OWNERS
cluster-autoscaler/cloudprovider/civo/OWNERS
cluster-autoscaler/cloudprovider/cloudstack/OWNERS
cluster-autoscaler/cloudprovider/clusterapi/OWNERS
cluster-autoscaler/cloudprovider/digitalocean/OWNERS
cluster-autoscaler/cloudprovider/exoscale/OWNERS
cluster-autoscaler/cloudprovider/externalgrpc/OWNERS
cluster-autoscaler/cloudprovider/gce/OWNERS
cluster-autoscaler/cloudprovider/hetzner/OWNERS
cluster-autoscaler/cloudprovider/huaweicloud/OWNERS
cluster-autoscaler/cloudprovider/ionoscloud/OWNERS
cluster-autoscaler/cloudprovider/kamatera/OWNERS
cluster-autoscaler/cloudprovider/kubemark/OWNERS
cluster-autoscaler/cloudprovider/linode/OWNERS
cluster-autoscaler/cloudprovider/magnum/OWNERS
cluster-autoscaler/cloudprovider/oci/OWNERS
cluster-autoscaler/cloudprovider/ovhcloud/OWNERS
cluster-autoscaler/cloudprovider/packet/OWNERS
cluster-autoscaler/cloudprovider/rancher/OWNERS
cluster-autoscaler/cloudprovider/scaleway/OWNERS
cluster-autoscaler/cloudprovider/tencentcloud/OWNERS
cluster-autoscaler/cloudprovider/vultr/OWNERS

Adds labelling to PRs touching all cloudprovider implementations for easier triaging/visualisation of PRs.
N/A
```release-note
NONE
```
```docs
NONE
```

CA - Label Cloudprovider implementation PRs

---

cluster-autoscaler/cloudprovider/civo/civo_manager.go
cluster-autoscaler/cloudprovider/civo/civo_manager_test.go
cluster-autoscaler/cloudprovider/civo/examples/cluster-autoscaler-node-pool.yaml

/kind feature
This PR allows civo customer to configure node pool wise config.
Fixes https://github.com/kubernetes/autoscaler/issues/5742

[civo] Support pool wise config

---

cluster-autoscaler/cloudprovider/alicloud/OWNERS
cluster-autoscaler/cloudprovider/aws/OWNERS
cluster-autoscaler/cloudprovider/azure/OWNERS
cluster-autoscaler/cloudprovider/baiducloud/OWNERS
cluster-autoscaler/cloudprovider/bizflycloud/OWNERS
cluster-autoscaler/cloudprovider/brightbox/OWNERS
cluster-autoscaler/cloudprovider/cherryservers/OWNERS
cluster-autoscaler/cloudprovider/civo/OWNERS
cluster-autoscaler/cloudprovider/cloudstack/OWNERS
cluster-autoscaler/cloudprovider/clusterapi/OWNERS
cluster-autoscaler/cloudprovider/digitalocean/OWNERS
cluster-autoscaler/cloudprovider/exoscale/OWNERS
cluster-autoscaler/cloudprovider/externalgrpc/OWNERS
cluster-autoscaler/cloudprovider/gce/OWNERS
cluster-autoscaler/cloudprovider/hetzner/OWNERS
cluster-autoscaler/cloudprovider/huaweicloud/OWNERS
cluster-autoscaler/cloudprovider/ionoscloud/OWNERS
cluster-autoscaler/cloudprovider/kamatera/OWNERS
cluster-autoscaler/cloudprovider/kubemark/OWNERS
cluster-autoscaler/cloudprovider/linode/OWNERS
cluster-autoscaler/cloudprovider/magnum/OWNERS
cluster-autoscaler/cloudprovider/oci/OWNERS
cluster-autoscaler/cloudprovider/ovhcloud/OWNERS
cluster-autoscaler/cloudprovider/packet/OWNERS
cluster-autoscaler/cloudprovider/rancher/OWNERS
cluster-autoscaler/cloudprovider/scaleway/OWNERS
cluster-autoscaler/cloudprovider/tencentcloud/OWNERS
cluster-autoscaler/cloudprovider/volcengine/OWNERS
cluster-autoscaler/cloudprovider/vultr/OWNERS

/kind bug
Follow up to #5745 - corrects labels to standardise with existing labels in the repo (e.g. https://github.com/kubernetes/autoscaler/issues/labels ), and the permissions of Prow to add `area/* labels` by default.
Fixes #
```release-note
NONE
```
```docs
```

CA - Correct Cloudprovider PR labelling to area/provider/<provider name>

---

addon-resizer/enhancements/5546-scaling-based-on-container-count/README.md

KEP for allowing Addon Resizer 1.8 to scale based on container count

---

cluster-autoscaler/cloudprovider/gce/templates.go
cluster-autoscaler/go.mod
cluster-autoscaler/go.sum

/kind cleanup
The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`.
Fixes #
```release-note
NONE
```
```docs
```

chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

---

cluster-autoscaler/cloudprovider/aws/OWNERS

As discussed with @jaypipes via Slack, moving Jay to emeritus approver status given change in focus. Marking as WIP for now pending discussions on potentially adding in new reviewers.
Fixes #
```release-note
NONE
```
```docs
```

CA - AWS Cloudprovider OWNERS Update

---

cluster-autoscaler/README.md

Add BigDarkClown to patch releases schedule

---

cluster-autoscaler/Dockerfile.s390x
cluster-autoscaler/Makefile

This PR adds docker file for s390x arch
This PR can help build s390x auto scalar image
Fixes # NA
None
None

Added s390x support

---

cluster-autoscaler/cloudprovider/externalgrpc/README.md

Just Fix the Doc.
Fixes #
NONE
```release-note
```
```docs
```

Fix Doc with External gRPC

---

addon-resizer/enhancements/5700-nanny-configuration-reload/README.md

[addon-resizer] docs: add KEP to add nanny configuration automatic reload.

---

cluster-autoscaler/.gitignore

/kind cleanup
Cherry-pick of #6059 onto 1.28 release branch as it builds s390x binaries
Ensures we don't accidentally commit an s390x binary of the CA.
Fixes #
```release-note
NONE
```
```docs
```

CA - Gitignore s390x binary

---

cluster-autoscaler/README.md

Add 1.28 to CA version compatibility matrix.
None
```release-note
NONE
```
```docs
```

CA - Add 1.28 to version compatibility matrix

---

vertical-pod-autoscaler/README.md
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml

/kind bug
This PR is cherry-picked, which backports #6081 into VPA 0.13 release branch
Part of ##5451
```release-note
None
```
```docs
```

Cherry pick #6081 to VPA release 0.13 branch

---

vertical-pod-autoscaler/README.md
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml

/kind bug
This PR is cherry-picked, which backports #6081 into VPA 0.14 release branch
Part of #5451
```release-note
None
```
```docs
```

Cherry pick #6081 to VPA release 0.14 branch

---

cluster-autoscaler/context/autoscaling_context.go
cluster-autoscaler/core/autoscaler.go
cluster-autoscaler/main.go
cluster-autoscaler/simulator/predicatechecker/schedulerbased.go
cluster-autoscaler/simulator/predicatechecker/testchecker.go
cluster-autoscaler/utils/kubernetes/listers.go

/kind cleanup
Optimize memory efficiency
Fixes #6109
```release-note
NONE
```

Use informer factory to reuse listers

---

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

/kind feature
Enables the use of p5.48xlarge instances in node groups
Fixes #
```release-note
```
```docs
```

Add EC2 instance type p5.48xlarge

---

cluster-autoscaler/cloudprovider/clusterapi/OWNERS

/kind cleanup
There is an [existing area/provider/cluster-api label](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+label%3Aarea%2Fprovider%2Fcluster-api+is%3Aclosed), we should use this for auto PR labelling for consistency rather than creating a new one.
N/A
```release-note
NONE
```
```docs
NONE
```

CA - Update CAPI Cloudprovider PR labeling to existing label

---

cluster-autoscaler/main.go

/kind cleanup
Improve memory efficiency. 
Fixes #
See prior work in k8s https://github.com/kubernetes/kubernetes/pull/118455
```release-note
NONE
```
```docs
```

Trim managedFields in shared informer factory

---

cluster-autoscaler/cloudprovider/aws/README.md

This PR is cherry-picked, which backports #5373 into CA1.24
Part of #6138
```release-note
None
```
```docs
```

Backport #5373 [CA] AWS - Update Docs all actions IAM policy into CA1.24

---

cluster-autoscaler/core/autoscaler.go
cluster-autoscaler/main.go

/kind bug
Default drainability rules should be set on create.
```release-note
NONE
```

Initialize default drainability rules

---

cluster-autoscaler/FAQ.md

Documents startup/status node taints and deprecates ignore node taints.

Documents startup/status/ignore node taints.

---

cluster-autoscaler/cloudprovider/exoscale/README.md

https://portal.exoscale.com/account/limits has been deprecated in favor of https://portal.exoscale.com/organization/quotas. Update README accordingly.
Fixes #
```release-note
NONE
```
```docs
```

cloudprovider/exoscale: update limits/quotas URL

---

cluster-autoscaler/cloudprovider/cherryservers/cherry_manager_rest.go
cluster-autoscaler/cloudprovider/civo/civo_node_group.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
cluster-autoscaler/cloudprovider/gce/gce_manager.go
cluster-autoscaler/cloudprovider/gce/templates.go
cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
cluster-autoscaler/cloudprovider/oci/common/oci_cloud_config.go
cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_provider.go
cluster-autoscaler/cloudprovider/tencentcloud/tencentcloud_service.go
cluster-autoscaler/clusterstate/clusterstate.go
cluster-autoscaler/core/scaledown/eligibility/eligibility.go
cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
cluster-autoscaler/debuggingsnapshot/debugging_snapshot.go
cluster-autoscaler/estimator/sng_capacity_threshold.go
cluster-autoscaler/expander/grpcplugin/grpc_client.go

/kind cleanup
Fixes klog formating directives. In newest version of klog those type of issues are checked at compile time, so it would result in compile failures if left as is.
No
```release-note
```
```docs
```

Fix klog formating directives in cluster-autoscaler package.

---

charts/cluster-autoscaler/Chart.yaml
charts/cluster-autoscaler/README.md
charts/cluster-autoscaler/README.md.gotmpl
charts/cluster-autoscaler/templates/deployment.yaml

/kind feature
- adds support for exoscale cloudprovider in cluster-autoscaler helm chart
```release-note
```
```docs
```

feat(helm): add support for exoscale provider

---

vertical-pod-autoscaler/README.md

Adding a TOC link in the README for the chapter we added in #5599

Add TOC link in README for EvictionRequirement example

---

cluster-autoscaler/cloudprovider/azure/OWNERS

/kind cleanup
add jackfrancis as owner
Fixes #
```release-note
No
```
```docs
```

azure: add owner-jackfrancis

---

addon-resizer/OWNERS

/kind cleanup
This PR updates addon-resizer OWNERS file in `addon-resizer-release-1.8` branch to match the one in the `master` branch.

Update OWNERS file in addon-resizer-release-1.8 branch

---

cluster-autoscaler/cloudprovider/civo/civo-cloud-sdk-go/kubernetes.go
cluster-autoscaler/cloudprovider/civo/civo-cloud-sdk-go/pool.go
cluster-autoscaler/cloudprovider/civo/civo-cloud-sdk-go/size.go
cluster-autoscaler/cloudprovider/civo/civo_cloud_provider_test.go
cluster-autoscaler/cloudprovider/civo/civo_manager.go
cluster-autoscaler/cloudprovider/civo/civo_manager_test.go
cluster-autoscaler/cloudprovider/civo/civo_node_group.go
cluster-autoscaler/cloudprovider/civo/civo_node_group_test.go

/kind bug
Calculate the real value for template using node group
Calculate the real value for template using node group
NONE

[civo] Calculate real value for template using node group

---

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go

/kind bug
Backport of #6364 to `v1.28`.
```release-note
Fixed a bug where failed servers are kept for longer than necessary
```
```docs
```

[v1.28] fix(hetzner): insufficient nodes when boot fails

---

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go

/kind bug
Backport of https://github.com/kubernetes/autoscaler/pull/6364 to `v1.27`.
Fixes #
```release-note
Fixed a bug where failed servers are kept for longer than necessary
```
```docs
```

[v1.27] fix(hetzner): insufficient nodes when boot fails

---

.gitignore

/kind feature
Fixes #
```release-note
NONE
```
```docs
```

Add VSCode workspace files to .gitignore

---

.github/dependabot.yml

/kind feature
Enable Dependabot for go.mod updates for addon-resizer
Fixes # N/A
N/A
```release-note
NONE
```
```docs
N/A
```

Update dependabot.yml to include addon-resizer

---

cluster-autoscaler/cloudprovider/civo/civo_manager.go
cluster-autoscaler/cloudprovider/civo/civo_node_group.go
cluster-autoscaler/cloudprovider/civo/civo_node_group_test.go

Signed-off-by: Vishal Anarase <vishalanarse11@gmail.com>
(cherry picked from commit 8703ff98ce8f6a571be218fdcb5c698e60951d29)
Backport of #6390

Backport of #6390

---

cluster-autoscaler/cloudprovider/civo/civo_manager.go
cluster-autoscaler/cloudprovider/civo/civo_node_group.go
cluster-autoscaler/cloudprovider/civo/civo_node_group_test.go

Signed-off-by: Vishal Anarase <vishalanarse11@gmail.com>
(cherry picked from commit 8703ff98ce8f6a571be218fdcb5c698e60951d29)
Backport changes from the master

[civo] Add Gpu count to node template

---

vertical-pod-autoscaler/README.md

/kind bug
Update the VPA version to v1.0.0 (as it is the default and current version) under the [README.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#installation) docs.
Fixes #
```release-note
NONE
```
```docs
```

Update the VPA Version to v1.0.0

---

addon-resizer/OWNERS
balancer/OWNERS
charts/OWNERS
cluster-autoscaler/OWNERS
vertical-pod-autoscaler/OWNERS

/kind cleanup
Updates the auto-labelling of PRs to subprojects to standardise on `area/<x>` labels to allow for easier contributor driven labelling going forward.
Fixes #5872
```release-note
```
```docs
```

Update Auto Labels of Subprojects

---

cluster-autoscaler/core/static_autoscaler.go

/kind cleanup
Streamline the code
Fixes #
```release-note
NONE
```
```docs
```

chore: remove unused arg from StaticAutoScaler

---

cluster-autoscaler/core/utils/expendable.go
cluster-autoscaler/core/utils/expendable_test.go

/kind bug
Consider preemption policy when determining the expandable pods. The pods with preemption policy set to never should never be considered as expandable pods.
Fixes #6227

Consider preemption policy for expandable pods

---

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go

/kind bug
Errors should be checked
Fixes #
```release-note
NONE
```
```docs
```

clusterapi: add missing error check

---

cluster-autoscaler/.gitignore

/kind cleanup
Ignores s390x CA binary to avoid accidental commit.
N/A
```release-note
NONE
```
```docs
```

CA 1.27 Release Branch: GitIgnore s390x binaries

---

cluster-autoscaler/cloudprovider/clusterapi/README.md

Add a link to the sample manifest and update the image used in the example.
Fixes #
```release-note
NONE
```
```docs
```

Update CAPI docs

---

cluster-autoscaler/README.md

Fix the broken link to internal cloud provider autoscaler readme

Fix broken link in README.md to point to equinixmetal readme

---

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

/kind feature
Enables the use of g6 families instances in node groups
Fixes #
```release-note
NONE
```
```docs
```

Add g6 EC2 instance type for AWS

---

cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1beta1/types.go

Update ProvisioningClass API Group

---

vertical-pod-autoscaler/pkg/recommender/model/cluster.go
vertical-pod-autoscaler/pkg/recommender/model/vpa.go
vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
vertical-pod-autoscaler/pkg/recommender/util/histogram.go

/kind cleanup
fix some typo and error print
Fixes #
```release-note
None
```
```docs
None
```

fix fmt errorf and typo

---

cluster-autoscaler/simulator/scheduling/hinting_simulator.go

Remove unnecessary return value. `findNode` can never return a non-nil error, but it's not immediately clear looking at the code using it. Making it explicit improves code readability.
/kind cleanup
/cc @yaroslava-serdiuk 
```release-note
NONE
```

Refactor out unnecessary return value; it's always nil

---

cluster-autoscaler/cloudprovider/brightbox/gobrightbox/server_groups.go
cluster-autoscaler/cloudprovider/brightbox/k8ssdk/util.go

fix function names in comment
```release-note
No
```
```docs
```

chore: fix function names in comment

---

vertical-pod-autoscaler/common/version.go

Bump vpa to 1.1.2

---

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/hack/vpa-process-yaml.sh

Part of https://github.com/kubernetes/autoscaler/issues/6836

Update vpa deployments to 1.1.2

---

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/hack/vpa-process-yaml.sh

Part of https://github.com/kubernetes/autoscaler/issues/6836

[main] Update vpa deployments to 1.1.2

---

cluster-autoscaler/provisioningrequest/provreqclient/client.go

AddDeleteProvisioningRequest method to ProvRec client

---

cluster-autoscaler/cloudprovider/POLICY.md
cluster-autoscaler/cloudprovider/cloud_provider.go

Documentation and Code comment typo fixes.
Fixes typos in readme and code comment.
```release-note
NONE
```

Minor documentation and comment typo fixes

---

cluster-autoscaler/main.go
cluster-autoscaler/provisioningrequest/orchestrator/orchestrator.go
cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go

/kind feature
Make ProvisioningClass interface as public to customise provreqOrchestrator

Public ProvisioningClass interface

---

vertical-pod-autoscaler/OWNERS

Owners file maintenance
Adds @voelzmo to approvers for the VPA
N/A
```release-note
NONE
```
```docs
NONE
```

VPA - Add voelzmo to approvers

---

cluster-autoscaler/processors/provreq/injector_test.go
cluster-autoscaler/provisioningrequest/provreqclient/testutils.go

Add ProvisioningRequestNoCache method to test client

---

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go

Orchestrator.New() return struct

---

cluster-autoscaler/cloudprovider/gce/cache.go
cluster-autoscaler/cloudprovider/gce/gce_manager_test.go
cluster-autoscaler/cloudprovider/gce/mig_info_provider.go
cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go

This PR adds the number of instances of a MIG in creating and deleting states to gce cache.
/kind feature
This PR adds ```migInstancesCreatingCount``` and ```migInstancesDeletingCount``` to gce cache.
Number of instances of MIGs in creating and deleting states are cached when calling ```gce.fillMigInfoCache()```
Fixes #
NONE
```release-note
```
```docs
```

Add number of Instances in creating and deleting states to gce cache

---

cluster-autoscaler/processors/provreq/injector.go
cluster-autoscaler/processors/provreq/injector_test.go

Add ProvisioningClass validation to Provisioning pods injector

---

cluster-autoscaler/cloudprovider/aws/README.md

Remove unnecessary permission from README
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.25.0
Fixes #6129
```release-note
NONE
```
```docs
```

Update recommended IAM policy

---

vertical-pod-autoscaler/RELEASE.md

Fix broken link in the VPA release instructions.
Fix broken link in release instructions.
N/A
N/A
NONE
N/A

Update RELEASE.md with new location of images.yaml file

---

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go

/kind feature
Add new gpu type for auto scaling.
For GPU auto-scaling - https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#special-note-on-gpu-instances

CA: AWS add support for Nvidia L4 GPU instances

---

cluster-autoscaler/cloudprovider/azure/OWNERS

This PR adds me as an approver to cluster autoscaler
Fixes #
```release-note
```
```docs
```

feat: add bryce-soghigian to the list of azure owners

---

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/hack/vpa-process-yaml.sh

Bump VPA version to 1.2.0 in main branch

---

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/hack/vpa-process-yaml.sh

Bump VPA version to 1.2.0 in vpa-release-1.2 branch

---

cluster-autoscaler/cloudprovider/azure/OWNERS

https://github.com/kubernetes/autoscaler/pull/7100/commits
Fixes #
```release-note
```
```docs
```

cherry-pick: adding bryce soghigian to owners for azure (1.29)

---

cluster-autoscaler/cloudprovider/azure/OWNERS

https://github.com/kubernetes/autoscaler/pull/7100/commits
Fixes #
```release-note
```
```docs
```

cherry-pick: adding bryce soghigian to owners for azure (1.30)

---

cluster-autoscaler/cloudprovider/azure/OWNERS

Fixes #
https://github.com/kubernetes/autoscaler/pull/7100/commits
```release-note
```
```docs
```

cherry-pick: adding bryce soghigian to owners for azure (1.27)

---

vertical-pod-autoscaler/hack/vpa-up.sh

Update vpa-up.sh to 1.2.0 in main branch

---

vertical-pod-autoscaler/hack/vpa-up.sh

Update vpa-up.sh to 1.2.0 in 1.2 release branch

---

cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set_test.go
cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache_test.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go

/kind cleanup
"Refactor" as a part of fork-upstream (managed-selfhosted) realignment. Should not have any breaking changes.
This codebases realignment will simplify the logistics between the two, cutting a significant portion of maintenance cost.
This PR specifically focus on instance caching.
There will be a separate effort focusing on improve code quality, rather than realigning codebase.
Fixes #
Most changes are merely refactor. Also include small fixes to refresh instance cache in more cases that should be required. Also include support for currently managed-exclusive flags (e.g., `EnableDetailedCSEMessage`).
There are similar PRs out on master and other version release branches as well. Should be near identical.
```release-note
- Azure: fix some cases where instance cache is outdated …
```

refactor: upstream Azure managed instance cache refactor for 1.30

---

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set_test.go
cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache_test.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
cluster-autoscaler/cloudprovider/azure/azure_util.go

/kind cleanup
"Refactor" as a part of fork-upstream (managed-selfhosted) realignment. Should not have any breaking changes.
This codebases realignment will simplify the logistics between the two, cutting a significant portion of maintenance cost.
This PR specifically focus on instance caching.
There will be a separate effort focusing on improve code quality, rather than realigning codebase.
Fixes #
Most changes are merely refactor. Also include small fixes to refresh instance cache in more cases that should be required. Also include support for currently managed-exclusive flags (e.g., `EnableDetailedCSEMessage`).
There are similar PRs out on master and other version release branches as well. Should be near identical.
```release-note
- Azure: fix some cases where instance cache is outdated …
```

refactor: upstream Azure managed instance cache refactor for 1.27

---

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set_test.go
cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache_test.go
cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
cluster-autoscaler/cloudprovider/azure/azure_util.go

/kind cleanup
"Refactor" as a part of fork-upstream (managed-selfhosted) realignment. Should not have any breaking changes.
This codebases realignment will simplify the logistics between the two, cutting a significant portion of maintenance cost.
This PR specifically focus on instance caching.
There will be a separate effort focusing on improve code quality, rather than realigning codebase.
Fixes #
Most changes are merely refactor. Also include small fixes to refresh instance cache in more cases that should be required. Also include support for currently managed-exclusive flags (e.g., `EnableDetailedCSEMessage`).
There are similar PRs out on master and other version release branches as well. Should be near identical.
```release-note
- Azure: fix some cases where instance cache is outdated …
```

refactor: upstream Azure managed instance cache refactor for 1.28

---

vertical-pod-autoscaler/RELEASE.md

Update VPA RELEASE.md with instructions to update vpa-up.sh.

---

vertical-pod-autoscaler/README.md

Add one of the following kinds:
/kind cleanup
This PR updates the VPA version and compatibility table under README.md file for `vpa-release-1.2` release branch.
Part of #7140
```release-note
NONE
```
```docs
```

[vpa-release-1.2] Update VPA version to 1.2.0 under README.md

---

vertical-pod-autoscaler/common/version.go

Bump VPA version to 1.2.1

---

vertical-pod-autoscaler/README.md
vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/hack/vpa-process-yaml.sh
vertical-pod-autoscaler/hack/vpa-up.sh

Update vpa versions in 1.2 branch to 1.2.1

---

vertical-pod-autoscaler/README.md
vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/hack/vpa-process-yaml.sh
vertical-pod-autoscaler/hack/vpa-up.sh

Update VPA to 1.2.1 in main branch

---

cluster-autoscaler/main.go

/kind feature
Allows lease resource name used during leader election to be customized by passing a flag
Fixes #
```release-note
Enables ability to set custom lease resource name using flag
```
```docs
```

Add lease resource name customization using flag

---

cluster-autoscaler/processors/provreq/injector.go

/kind feature /kind api-change
Atomize the functionality of the process method of the injector pod list processor so that they can be individually used in other parts of cluster autoscaler.
Fixes #
```release-note
```
```docs
```
cc: @aleksandra-malinowska @yaroslava-serdiuk

Subdivide injector pod list processor logic

---

cluster-autoscaler/processors/provreq/processor.go
cluster-autoscaler/processors/provreq/processor_test.go

Delete old ProvReqs

---

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

/kind feature
Enables the use of g6e families instances in node groups
Fixes #
```release-note
None
```
```docs
```

Add g6e EC2 instance type for AWS

---

charts/OWNERS

N/A
Adding @jackfrancis to chart reviewers as discussed on SIG calls.
N/A
N/A
```release-note
NONE
```
```docs
NONE
```

Charts - Add JackFrancis to reviewers

---

cluster-autoscaler/processors/podinjection/enforce_injected_pods_limit_processor.go

/kind feature
Adds metrics for injected pods from `PodInjectionPodListProcessor`.
Mainly updates `unschedulable_pods_count` metric with labels `injected` & `skipped_injection` for injected pods and pods that were removed due to limit.
Fixes #
```release-note
NONE
```
```docs
```

Adds injection metrics for fake pod injection

---

cluster-autoscaler/clusterstate/clusterstate.go
cluster-autoscaler/core/podlistprocessor/filter_out_daemon_sets.go
cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
cluster-autoscaler/processors/nodes/pre_filtering_processor.go

/kind cleanup
This PR removes some unnecessary logs in `compare_nodegroups.go` and `filter_out_daemon_sets.go`
And also change some Warnings to v5 Info in `clusterstate.go` and `pre_filtering_processor.go`
Fixes #
Some CA logs are removed and updated the level and type.
```release-note
```
```docs
```

Remove/update spamming logs 

---

vertical-pod-autoscaler/common/kubeconfig.go
vertical-pod-autoscaler/e2e/v1/admission_controller.go
vertical-pod-autoscaler/e2e/v1/e2e.go
vertical-pod-autoscaler/e2e/v1/recommender.go
vertical-pod-autoscaler/e2e/v1beta2/e2e.go
vertical-pod-autoscaler/e2e/v1beta2/recommender.go

Transition to structural logging in compliance with [Kubernetes logging guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md).
/kind cleanup
As part of #6905, I'm splitting this into multiple PRs rather than submitting a single large PR.
I didn't change `klog.Fatalf` because I'm uncertain if or how it should be modified.
```release-note
NONE
```
```docs
NONE
```

Refactor logging statements in common,e2e test files

---

cluster-autoscaler/context/autoscaling_context.go
cluster-autoscaler/provisioningrequest/orchestrator/wrapper_orchestrator.go
cluster-autoscaler/provisioningrequest/orchestrator/wrapper_orchestrator_test.go

/kind feature
```release-note
None
```

Move ProvisioningRequestScaleUpMode to AutoscalingContext

---

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
vertical-pod-autoscaler/pkg/admission-controller/main.go
vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go
vertical-pod-autoscaler/pkg/target/fetcher.go

/kind cleanup
Fixes #6905
```release-note
NONE
```
```docs
NONE
```

Refactor logging statements

---

cluster-autoscaler/context/autoscaling_context.go
cluster-autoscaler/provisioningrequest/orchestrator/wrapper_orchestrator.go
cluster-autoscaler/provisioningrequest/orchestrator/wrapper_orchestrator_test.go

Fix typo in ProvisioningRequestScaleUpMode

---

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/describe_scaling_groups.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/scale_with_adjustment.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/struct_scaling_group.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/services/ess/struct_scaling_groups.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_manager.go

/kind feature
add support to scaling group desired size for alicloud
Fixes #6659 
```release-note
```
```docs
```

add support to scaling group desired size for alicloud

---

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/endpoints/location_resolver.go

Which component this PR applies to?
/kind bug
This PR improves error handling in the Cluster Autoscaler by adding logging for endpoint resolution failures on Alibaba Cloud. Currently, errors such as missing permissions are silently ignored, making it difficult to diagnose scaling issues. With this update, endpoint resolution (e.g., due to permissions) will be logged, enabling easier troubleshooting and faster resolution of configuration issues. This enhancement ensures better visibility into the cause of failures, ultimately improving reliability and supportability.
Fixes #7437
no
```release-note
NONE
```

7437 Add logging for endpoint resolving errors

---

vertical-pod-autoscaler/hack/e2e/k8s-metrics-server.yaml

/kind cleanup
Bump metrics server in e2e tests to version 0.7.2
Related to #7455
```release-note
NONE
```
```docs
NONE
```

VPA: e2e Update metrics-server version to 0.7.2

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go

/kind cleanup
Fixes #
```release-note
```
```docs
```

[release-1.31] Set node state to InstanceCreating to delete on CSE error

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go

/kind cleanup
Fixes #
```release-note
```
```docs
```

[release-1.30] Set node state to InstanceCreating to delete on CSE error

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go

/kind cleanup
Fixes #
```release-note
```
```docs
```

[release-1.29] Set node state to InstanceCreating to delete on CSE error

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go

/kind cleanup
Fixes #
```release-note
```
```docs
```

[release-1.28] Set node state to InstanceCreating to delete on CSE error

---

cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go

/kind cleanup
Fixes #
```release-note
```
```docs
```

Set node state to InstanceCreating to delete on CSE error

---

vertical-pod-autoscaler/docs/features.md

Add docs for humanize-memory feature
Fixes #7539
```release-note
NONE
```
```docs
NONE
```

Add Memory Value Humanization docs

---

vertical-pod-autoscaler/OWNERS

I have met all requirements to join as reviewer:
- Member since [7 September 2024](https://github.com/kubernetes/org/issues/5133)
- [17 PRs authored and merged](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+author%3Aadrianmoisey+is%3Amerged)
- [27 PRs reviewed and merged](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+assignee%3Aadrianmoisey+is%3Amerged)
- Familiar with codebase 
- Also active on Slack answering questions and in SIG meetings.

Add adrianmoisey as VPA reviewer

---

charts/OWNERS

Requirements:
As per: https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer
- member for at least 3 months - **Yes, I have been an active member of the Kubernetes community for more than two years. ([Member Request](https://github.com/kubernetes/org/issues/3604))**
- Primary reviewer for at least 5 PRs to the codebase - **Yes, Reviewd [264](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Ashubham82) PR so far(Open: [9](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Ashubham82+is%3Aopen) and closed: [255](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Ashubham82+is%3Aclosed), merged: …

Add Shubham82 to the reviewers

---

vertical-pod-autoscaler/docs/faq.md

Document controlledResources
Fixes #7597
```release-note
NONE
```
```docs
NONE
```

VPA: document controlledResources

---

addon-resizer/RELEASE.md

Ref #7615
Sending this out for review early to trigger the automatic build process that happens upon submission that was added as part of #7615.
```release-note
NONE
```

Preliminary release instructions for Addon resizer

---

vertical-pod-autoscaler/docs/components.md
vertical-pod-autoscaler/docs/flags.md

Add flags to the docs
Fixes #
```release-note
```
```docs
```

VPA: add flags to docs

---

.github/workflows/ci.yaml
.github/workflows/pr.yaml
.github/workflows/release.yaml

/kind cleanup
Some actions are using outdated versions. This PR updates them to the latest versions.
Fixes #
```release-note
NONE
```
```docs
NONE
```

Update GitHub Actions versions

---

cluster-autoscaler/cloudprovider/huaweicloud/README.md

Remove contact information.
Fixes #
```release-note
NONE
```
```docs
```

remove  contact information for huaweicloud cluster autoscaler provider

---

vertical-pod-autoscaler/pkg/recommender/model/types.go
vertical-pod-autoscaler/pkg/recommender/model/types_test.go

/kind cleanup
```release-note
NONE
```

Remove an unused function and fix a comment

---

vertical-pod-autoscaler/hack/run-e2e-locally.sh

/kind cleanup
Updates kind cluster version.
Enhances kind cluster creation by implementing proper error handling and version checking. Previously, the script would continue execution even if cluster creation failed. This PR addresses that issue by adding appropriate error handling.
Fixes #7662
```release-note
NONE
```
```docs
NONE
```

Improve kind cluster creation with proper error handling and version check

---

vertical-pod-autoscaler/common/version.go

/kind feature
Release covered by #7691.
```release-note
NONE
```

Update version.go to 1.2.2

---

cluster-autoscaler/simulator/clustersnapshot/store/delta.go

/kind bug
Clearing caches while adding a pod was causing data race. This step is redundant when setting cluster state, as cache is empty anyway.
See #7695
```release-note
NONE
```
```docs
```

Fix data race while setting delta cluster state in parallel

---

vertical-pod-autoscaler/common/version.go

/kind feature
Associated 1.3.0 release bug: https://github.com/kubernetes/autoscaler/issues/7731
No.

Update version.go for VPA 1.3.0 release

---

vertical-pod-autoscaler/RELEASE.md

/kind cleanup
Small tweaks to release instructions to make them compatible with latest changes.
```release-note
NONE
```

Tweaks to VPA release instructions.

---

addon-resizer/Makefile

/kind cleanup
Cutting new release to address #7658.
```release-note
NONE
```

Bump addon-resizer to 1.8.23

---

vertical-pod-autoscaler/RELEASE.md

Fix the command line describing how to deploy a VPA following a variable name update.

Fix RELEASE.md VPA deployment command line.

---

vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go

/kind cleanup
The `GetContainersMetrics` function retrieves the podMetricsList using a straightforward List command: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go#L69.
This PR resolves a logging issue by ensuring that when the List command is scoped to a specific namespace, the log output reflects this correctly.
Fixes #
```release-note
NONE
```
```docs
NONE
```

chore: fix metricsClient logs

---

charts/OWNERS

/kind cleanup
Adds @jackfrancis to approvers for helm charts.
N/A
N/A
```release-note
NONE
```
N/A

Charts - Add jackfrancis to Approvers

---

vertical-pod-autoscaler/pkg/admission-controller/certs_test.go

/kind cleanup
This PR comments out a test that is currently flaking, as it causes PRs to get stuck and makes it unreliable. Since the test is inconsistent, it's unclear whether failures are due to the code being tested or the test itself.
Fixes #
Once @adrianmoisey identifies the root cause, we can revert this change. This is particularly important for PRs like Dependabot updates, where we can't manually retrigger GitHub Actions CI.
```release-note
NONE
```
```docs
NONE
```
cc @voelzmo @raywainman

comment out TestUnchangedCAReloader test (flake)

---

cluster-autoscaler/core/scaledown/actuation/actuator_test.go

/kind bug
After https://github.com/kubernetes/autoscaler/pull/7820, running actuation tests with `-race` started failing because race detector detects data race between `cmp.Diff` and `GroupDeletionScheduler`, since both access node's `Spec.Taints`. Production code is not affected, so it's enough to wrap `cmp.Diff` in a mutex, so it doesn't race with `GroupDeletionScheduler`.
```release-note
NONE
```
```docs
```

Lock deletion scheduler so race detector does not complain

---

cluster-autoscaler/core/static_autoscaler.go
cluster-autoscaler/core/static_autoscaler_test.go

/kind cleanup
Fix error logging & add missing tests
```release-note
NONE
```

Fix log for node filtering in static autoscaler

---

addon-resizer/Dockerfile

/kind bug
- Build is broken.
Fixes #7980
```release-note
NONE
```

[addon-resizer] fix typo in Dockerfile that is breaking build

---

charts/cluster-autoscaler/Chart.yaml
charts/cluster-autoscaler/README.md
charts/cluster-autoscaler/README.md.gotmpl

/kind cleanup
This PR changes the way we refer to go templating handlebar usage in the helm readme template for helm-docs input.
Ref:
- https://github.com/norwoodj/helm-docs/issues/164#issuecomment-1275956044
Fixes #
```release-note
NONE
```
```docs
```

helm: backtick to escape braces

---

OWNERS
OWNERS_ALIASES

/kind cleanup
Update OWNERS to reflect https://github.com/kubernetes/community/pull/8403, via a more idiomatic OWNERS_ALIASES file.
Fixes #
```release-note
NONE
```
```docs
```

update OWNERS, add OWNERS_ALIASES

---

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go

/kind bug
Scaling up can sometimes fail in CAPI clusters with a lot of activity, due to modification conflicts (`the object has been modified; please apply your changes to the latest version and try again`). This leads to (when using the priority expander) other nodepools with a lower priority being chosen to scale up instead.
Using `.Patch()` instead of `.Update()` seemingly fixed this issue for my cluster.
Fixes https://github.com/kubernetes/autoscaler/issues/7872
I'm not sure if I handled the changes for the test correctly. They pass though.
```release-note
NONE
```
```docs
- [client-go Scales Patch godoc]: https://pkg.go.dev/k8s.io/client-go@v0.32.3/scale#ScaleInterface
```

CA: Use Patch to Scale clusterapi nodepools

---

vertical-pod-autoscaler/pkg/admission-controller/Makefile
vertical-pod-autoscaler/pkg/recommender/Makefile
vertical-pod-autoscaler/pkg/updater/Makefile

/kind bug
Fixes automated VPA builds that are currently broken. Part of #7902.
```release-note
NONE
```

Fix default registry in VPA makefiles

---

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/hack/vpa-process-yaml.sh
vertical-pod-autoscaler/hack/vpa-up.sh

/kind feature
VPA 1.3.1 release: #8073
```release-note
NONE
```

Update default version in VPA 1.3 branch to 1.3.1

---

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/docs/flags.md
vertical-pod-autoscaler/docs/installation.md
vertical-pod-autoscaler/hack/generate-flags.sh
vertical-pod-autoscaler/hack/vpa-process-yaml.sh
vertical-pod-autoscaler/hack/vpa-up.sh

/kind feature
Part of VPA 1.3.1 release: #8073.
```release-note
NONE
```

Update default version of VPA to 1.3.1 in main branch

---

vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go
vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go

/kind feature
This PR introduces two additional metrics measuring `count` and `duration` of requests from a `vpa-recommender` to a `Prometheus` instance. 
The main motivation behind this enhancement is to allow a more precise observation of the `recommender` operations when using `Prometheus` as a history storage provider.
The following snippet showcases the additional entries in the `/metrics` response:
```
vpa_recommender_prometheus_client_api_requests_duration_seconds_bucket{code="200",method="post",le="0.01"} 2
vpa_recommender_prometheus_client_api_requests_duration_seconds_bucket{code="200",method="post",le="0.02"} 3
vpa_recommender_prometheus_client_api_requests_duration_seconds_bucket{code="200",method="post",le="0.05"} 3
vpa_recommender_prometheus_client_api_requests_duration_secon …
```

metrics(recommender): Add `RoundTripper` metrics to Prometheus API client

---

cluster-autoscaler/estimator/binpacking_estimator.go
cluster-autoscaler/metrics/metrics.go

Binpacking estimator has optimizations to allow homogeneous workloads to be efficiently processed together. Measuring heterogeneity is required to gain insight into cases when these optimizations matter and when they don't.
Fixes #
```release-note
NONE
```
```docs
```

Introduce a metric measuring heterogeneity of binpacking

---

cluster-autoscaler/core/static_autoscaler_test.go

This is a manual cherry-pick of #7995

Add unit test for cleaning deletion soft taints in scale down cool down

---

vertical-pod-autoscaler/docs/features.md

Add docs for in place
Fixes #
```release-note
NONE
```
```docs
Add docs for in place
```

Add docs for in-place updates

---

vertical-pod-autoscaler/RELEASE.md

Found a bug in the release instructions as part of #8118.
```release-note
NONE
```

Update VPA release instructions with correct tag command

---

cluster-autoscaler/core/scaledown/status/status.go
cluster-autoscaler/core/static_autoscaler.go
cluster-autoscaler/core/static_autoscaler_test.go

/kind bug
This is a manual cherry-pick of the following PRs:
- https://github.com/kubernetes/autoscaler/pull/7954
- https://github.com/kubernetes/autoscaler/pull/7995
- https://github.com/kubernetes/autoscaler/pull/7997
- https://github.com/kubernetes/autoscaler/pull/8034
Fixes #
```release-note
Fix cool down status condition to trigger scale down
```
```docs
```

[cluster-autoscaler-release-1.31] Fix cool down status condition to trigger scale down

---

cluster-autoscaler/estimator/binpacking_estimator.go

/kind bug
Before this change the binpacking estimator when reaching the maxnodes would skip only a single pod and keep iterating on the pods checking again and again on the same limitation. With this change we will not retry to add any new nodes and will only try to binpack the remaining pods on the nodes that are already added.
Fixes #
```release-note
NONE
```
```docs
```

Prevent the binpacking estimator from retrying to add additional nodes

---

vertical-pod-autoscaler/RELEASE.md

Updating the release instructions with proper sequencing.
This is important because our scripts rely on the generated tag during a release.

Update VPA release instructions with correct sequencing for tags

---

vertical-pod-autoscaler/pkg/admission-controller/main.go
vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_source.go
vertical-pod-autoscaler/pkg/recommender/main.go
vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go
vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go
vertical-pod-autoscaler/pkg/target/fetcher.go
vertical-pod-autoscaler/pkg/updater/logic/updater.go
vertical-pod-autoscaler/pkg/updater/main.go
vertical-pod-autoscaler/pkg/utils/metrics/healthcheck.go
vertical-pod-autoscaler/pkg/utils/server/server.go
vertical-pod-autoscaler/pkg/utils/vpa/api.go

kind cleanup
migrate os.Exit(255) to klog.FlushAndExit
Fixes #8146
```release-note
NONE
```
```docs
NONE
```

migrate os.Exit(255) to klog.FlushAndExit

---

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
vertical-pod-autoscaler/deploy/recommender-deployment.yaml
vertical-pod-autoscaler/deploy/updater-deployment.yaml
vertical-pod-autoscaler/docs/flags.md
vertical-pod-autoscaler/hack/generate-flags.sh
vertical-pod-autoscaler/hack/vpa-process-yaml.sh
vertical-pod-autoscaler/hack/vpa-up.sh

/kind feature
VPA 1.4.1 release (see https://github.com/kubernetes/autoscaler/issues/8189)
```release-note
NONE
```

Update VPA default version to 1.4.1

---

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signers/signer_oidc.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/utils/utils.go
cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/utils/utils_test.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config.go
cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config_test.go

/kind bug
Fixes #8170
Fixing a bug that support for both the old "ALICLOUD_OIDC_TOKEN_FILE_PATH" and the new "ALIBABA_CLOUD_OIDC_TOKEN_FILE" env variables for RRSA isn't working.
no
-->
```release-note
NONE
```

fix bug 8170 to support old env var

---

cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-aks.yaml
cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-autodiscover.yaml
cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml
cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml
cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-control-plane.yaml
cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml
cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml

/kind cleanup
When unsure what example to use for debugging, it helps to have clean diffs.
n/a
n/a
```release-note
NONE
```
```docs
```

azure: Make it easier to compare examples

---

cluster-autoscaler/Makefile

/kind cleanup
This PR makes cutting a release easier, and less error prone. Specifically:
- We automatically ingest the appropriate `TAG` runtime variable from `version/version.go`.
- We ensure that there is a git tag that correlates with the commit that we are building and releasing from
- We ensure that the git tag and the version string in `version/version.go` agree
Fixes #
```release-note
NONE
```
```docs
```

CA: add release automation validation

---

cluster-autoscaler/OWNERS

/kind cleanup
This PR officially gives @elmiko the ability to review and approve Cluster Autoscaler changes, which recognizes his existing contributions and will help project velocity.
He has landed over 40 PRs over the last 5+ years and is a consistent fixture in the SIG:
- https://github.com/kubernetes/autoscaler/pulls?page=1&q=is%3Apr+author%3Aelmiko+is%3Aclosed
Fixes #
```release-note
NONE
```
```docs
```

CA: add elmiko as maintainer

---

cluster-autoscaler/config/autoscaling_options.go
cluster-autoscaler/config/flags/flags.go
cluster-autoscaler/core/static_autoscaler.go
cluster-autoscaler/core/static_autoscaler_test.go

b/434959283
/kind bug
Force delete nodes with errors. Otherwise, if a scale up fails when the node group size is below its min size, CA ends up in an error loop:
```
Deleting 2 from <redacted> node group because of create errors
Error while trying to delete nodes from <redacted>: min size reached, nodes will not be deleted
Decreasing size of <redacted>, expected=23 current=21 delta=-2
Failed to fix node group sizes: failed to decrease <redacted>: attempt to delete existing nodes targetSize:23 delta:-2 existingNodes: 23
```
```release-note
Ensure created nodes with errors are deleted
```
```docs
```

Force delete nodes with errors

---

vertical-pod-autoscaler/e2e/v1/admission_controller.go

/kind cleanup
https://github.com/kubernetes/autoscaler/pull/8423/files#r2268378014
Fixes #
```release-note
NONE
```
```docs
```

Combine in-place and regular e2e tests

---

OWNERS_ALIASES
charts/vertical-pod-autoscaler/.helmignore
charts/vertical-pod-autoscaler/Chart.yaml
charts/vertical-pod-autoscaler/OWNERS
charts/vertical-pod-autoscaler/README.md
charts/vertical-pod-autoscaler/README.md.gotmpl
charts/vertical-pod-autoscaler/templates/_helpers.tpl
charts/vertical-pod-autoscaler/templates/admission-contoller-serviceaccount.yaml
charts/vertical-pod-autoscaler/templates/admission-controller-clusterrole.yaml
charts/vertical-pod-autoscaler/templates/admission-controller-clusterrolebinding.yaml
charts/vertical-pod-autoscaler/templates/admission-controller-deployment.yaml
charts/vertical-pod-autoscaler/templates/admission-controller-service.yaml
charts/vertical-pod-autoscaler/templates/admission-controller-tls-secret.yaml
charts/vertical-pod-autoscaler/values.yaml

/kind cleanup
Add vpa chart 
Fixes #
As discussed in the sig-autoscaling meetings, this PR introduces a Helm chart for the VPA. This is an initial starting point, as there’s still more work ahead. I’ve included a minimal admission controller template for now.
Also, added the VPA folks to be able to approve helm chart PRs.
```release-note
NONE
```
```docs
NONE
```

Add helm chart for VPA

---

.github/workflows/pr.yaml
charts/vertical-pod-autoscaler/Chart.yaml
charts/vertical-pod-autoscaler/README.md

/kind feature
Upgrades helm-docs from v1.3.0 to v1.14.2 to fix ARM64 compatibility and improves error output to show diffs when documentation is out of date.
Fixes https://github.com/kubernetes/autoscaler/issues/8575
```release-note
NONE
```
```docs
```

Update helm-docs & improve output
