cluster-autoscaler/cloudprovider/azure/azure_agent_pool_test.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/mockstorageaccountclient/BUILD, cluster-autoscaler/vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/mockstorageaccountclient/doc.go, cluster-autoscaler/vendor/k8s.io/legacy-cloud-providers/azure/clients/storageaccountclient/mockstorageaccountclient/interface.go
Add test cases for azure_agent_pool.go. We update the vendor because we need packages that don't exist in `vendor/`.
/kind cleanup
=> Azure: Add test cases for azure_agent_pool.go.

cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go
For clusters with both real and hollow nodes, CA fails at static_autoscaler.go:268: "core_utils.GetNodeInfosForGroups(" since the Kubemark Cloud Provider doesn't know how to find pods for real nodes. This change will simply skip nodes that are not Kubemark nodes, as they cannot be scaled by CA's Kubemark implementation anyways.
=> [cluster-autoscaler] Skip nodes that are not Kubemark nodes

cluster-autoscaler/FAQ.md
=> Fix wrong default value for expendable-pods-priority-cutoff in FAQ

cluster-autoscaler/cloudprovider/huaweicloud/README.md
The README.md file under huaweicloud folder is updated with minor changes of some details.
=> update README file

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
Address https://github.com/kubernetes/autoscaler/issues/3239
Didn't do a great job on version upgrade. I think there're still group of users use master examples.
=> Upgrade images in aws examples to v1.17.3

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go
When an option matches in a low priority together with another option both get added to the `best` list where the random expander fallback strategy finally selects one option randomly although one of the options also matches in a higher priority.
This PR ensures all priorities are evaluated for an option and higher ones take precedence by removing the `break` in the loop. The root cause is that the map of priorities is unordered and therefore we have to walk to the end
=> Fix priority expander falling back to random although higher priority matches

charts/cluster-autoscaler-chart/Chart.yaml, charts/cluster-autoscaler-chart/templates/NOTES.txt
Fixes the label selectors in the `kubectl get pods` command printed by the post-install notes.
The `app` and `release` labels were replaced by this commit https://github.com/helm/charts/commit/5e4e493bbb27037c54fdeeab7397de2452310d52 in the old chart location. The new labels come from
https://github.com/kubernetes/autoscaler/blob/852ea800914cae101824687a71236f7688ee653d/charts/cluster-autoscaler-chart/templates/_helpers.tpl#L36-L39
which have the same values as the old `app` and `release` labels.
=> Fix label selector in chart post-install notes

cluster-autoscaler/cloudprovider/magnum/gophercloud/.zuul.yaml, cluster-autoscaler/cloudprovider/magnum/gophercloud/CHANGELOG.md, cluster-autoscaler/cloudprovider/magnum/gophercloud/errors.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/go.mod, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/client.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/identity/v3/extensions/trusts/doc.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/identity/v3/extensions/trusts/requests.go
Fixes #3414
This path was missed in go.mod when replacing
import paths because it was filtering for *.go files.
This commit also changes the gophercloud version to
exactly v0.8.0, instead of being vendored immediately
after nodegroup support was added.
=> Fix module path in local gophercloud copy

cluster-autoscaler/estimator/binpacking_estimator.go
This means that PreFilters are run once per pod in binpacking
instead of #pods*#nodes times. This makes a huge performance
difference in very large clusters.
=> Use FitsAnyNode in binpacking

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
Re-generate list of available EC2 instances from available metadata. This primarily pulls in support for `c5ad` & various `xxgd` instances.
=> Regenerate list of EC2 instances

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
`fetchAutoAsgs()` is called at regular intervals, fetches a list of VMSS, then call `Register()` to cache each of those. That registration function will tell the caller wether that vmss' cache is outdated (when the provided VMSS, supposedly fresh, is different than the one held in cache) and will replace existing cache entry by the provided VMSS (which in effect will require a forced refresh since that ScaleSet struct is passed by fetchAutoAsgs with a nil lastRefresh time and an empty instanceCache).
To detect changes, `Register()` uses an `reflect.DeepEqual()` between the provided and the cached VMSS. Which does always find them different: cached VMSS were enriched with instances lists (while the provided one is blank, fresh from a simple vmss.list call). That DeepEqual is also fragile …
=> Avoid unwanted VMSS VMs caches invalidations

cluster-autoscaler/hack/update-vendor.sh
Pulling the complete kubernetes/kubernetes repo can take a while especially on a slow connection.
Instead of pulling everything, this change pulls only the tip of the master branch and then fetches the single revision that is requested, checking it out using `FETCH_HEAD`.
It works with `--k8srev=branch-name`, `--k8srev=tags/tag-name` and `--k8srev=commit-sha`, which should be all the ways this could already be used.
The total download size is reduced from ~750MB to ~50MB. The disk space used by the cloned kubernetes repo is also reduced from 950MB to 250MB.
=> Use shallow clone in update-vendor.sh

vertical-pod-autoscaler/deploy/kustomization.yaml
This will allow the use of kustomizes [base](https://kubectl.docs.kubernetes.io/pages/app_customization/bases_and_variants.html) feature.
This will allow to retrieve and update manifest like so:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
bases:
- github.com/estahn/autoscaler//vertical-pod-autoscaler/deploy/?ref=patch-1
commonLabels:
app.kubernetes.io/name: vertical-pod-autoscaler
patchesStrategicMerge:
- patches.yaml
```
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: vpa-recommender
namespace: kube-system
spec:
template:
spec:
containers:
- name: recommender
command: ['./recommender']
args:
- --v=4
- --stderrthreshold=info
- --storage=prometheus
- --prometheus-address=http://prometheus-operator-prometheus.devops.svc:9090
- …
```
=> chore: add kustomize support

cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Currently, aws eks version is 1.14. 
We configured 3 nodegroups those have same instance type but different AZs. And we enabled `balance-similar-node-groups` option. 
However, when CA is auto-scaling, the desired counts of nodegroups are not similar. We found the reason is that CA did not ignore the `alpha.eksctl.io/instance-id` label on the node when comparing similar nodegroups
=> Ignore the label of aws instance id when comparing nodegroups

cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml
**What type of PR is this?**
/kind feature
**What this PR does / why we need it:**
The ALI examples appear to be missing the daemonsets and replicasets resource under the apps apiGroups 
**Which issue(s) this PR fixes:**
#3085
=> Add missing daemonsets and replicasets to ALI example cluster role

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
This makes Cluster API provider tests for Cluster Autoscaler more resilient when running in resource constrained environments. Previously the tests were replicating operations on the informer cache stores and the fake clients, which led to duplicated resources being present in the informer cache store depending on racy behavior that manifests with increased parallelism or in resource constrained environments. With this change, rather than trying to replicate operations the test helpers poll the informer cache store for the changes to be propagated before continuing test assertions.
/assign @elmiko
=> Improve Cluster API tests to work better with constrained resources

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
On (re)start, cluster-autoscaler will refresh all VMSS instances caches at once, and set those cache TTL to 5mn. All VMSS VM List calls (for VMSS discovered at boot) will then continuously hit ARM API at the same time, potentially causing regular throttling bursts.
Exposing an optional jitter subtracted from the initial first scheduled refresh delay will splay those calls (except for the first one, at start), while keeping the predictable (max. 5mn, unless the VMSS changed) refresh interval after the first refresh.
While at it, also expose an option to configure that VMSS cache TTL.
=> Azure: optional jitter on initial VMSS VM cache refresh

vertical-pod-autoscaler/builder/Dockerfile, vertical-pod-autoscaler/pkg/admission-controller/.gitignore, vertical-pod-autoscaler/pkg/admission-controller/Dockerfile, vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/.gitignore, vertical-pod-autoscaler/pkg/recommender/Dockerfile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/recommender/input/spec/spec_client_test_util.go, vertical-pod-autoscaler/pkg/updater/.gitignore, vertical-pod-autoscaler/pkg/updater/Dockerfile, vertical-pod-autoscaler/pkg/updater/Makefile
Fixes: https://github.com/kubernetes/autoscaler/issues/3074
Had to change a test function's parameter from int to int64 as it was overflowing in 32bit version of arm -> https://github.com/kubernetes/autoscaler/compare/master...povilasv:multiarch?expand=1#diff-246f689f90fe5dd9dec48e0c8af223bcR126
Example images:
https://quay.io/repository/povilasv/vpa-admission-controller?tab=tags
https://quay.io/repository/povilasv/vpa-updater?tab=tags
https://quay.io/repository/povilasv/vpa-recommender?tab=tags
For example:
https://quay.io/repository/povilasv/vpa-recommender
is made from:
https://quay.io/repository/povilasv/vpa-recommender-amd64
https://quay.io/repository/povilasv/vpa-recommender-arm64
https://quay.io/repository/povilasv/vpa-recommender-arm …
=> vpa: add multiarch builds

OWNERS, index.yaml
Manual creation of index.yaml for 1.0.0 and 1.0.1 releases of Cluster-autoscaler Helm chart
This manually addresses the number of people running into 404s trying to use the repository for now (see #3318 comments for some of these) #3403 is an attempt to move to an automated process for this in the future
Also removes @mgoodness from the `OWNERS` file in `gh-pages` branch as per #3405 - adds in same approvers and reviewers from repo's default branch to prevent dropping to one person.
=> CA-Chart Manual Release

vertical-pod-autoscaler/pkg/admission-controller/config.go
When switching the VPA admission controller to the v1 admissionregistration API, the FailurePolicy was changed from Ignore to Fail.
[v1beta1 type](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/admissionregistration/v1beta1/types.go#L212-L215) vs [v1 type](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/admissionregistration/v1/types.go#L194-L197) (the change is the "Defaults to")
Using Fail makes pod creation depend on VPA and can cause a deadlock when the admission controller pod itself can't be scheduled again.
=> VPA: Ignore admission hook failures

charts/cluster-autoscaler-chart/Chart.yaml, charts/cluster-autoscaler-chart/README.md, charts/cluster-autoscaler-chart/README.md.gotmpl
Correct CA Helm chart instructions chart name
Corrects the instructions to reference the correct chart name as per https://github.com/kubernetes/autoscaler/pull/3413#issuecomment-679173770
=> CA - Update Helm chart instructions

cluster-autoscaler/cloudprovider/azure/azure_cache.go
Previously, it would assume every ASG is of `ScaleSet` and this would possibly for panic for the `vmType` that's not VMSS.
=> Call nodeGroup API to avoid type assertion errors

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signers/signer_ecs_ram_role.go, cluster-autoscaler/cloudprovider/huaweicloud/huawei-cloud-sdk-go/errors.go
Fixes bug reported by go vet check stringintconv. In go casting an
integer to string does not result in the string representation of
the number, instead the result is a rune representing
the codepoint of that number.
Fixes #3472
=> CA: fix integer to string conversion

cluster-autoscaler/simulator/cluster.go
This is the scale-down equivalent of #3429 and it speeds-up
findUnneeded by 5x+ in very large clusters (by reducing the
number of expensive PreFilter calls #nodes times).
A side effect of this change is removing
"Simulating scheduling of <pod> to <node> return error <error>"
logs. Using FitsAny we no longer have per-node scheduler errors
that we could log. I think that's actually a good thing - even
with klogx this log was incredibly spammy in cluster with >100
nodes and its practical value was questionable.
=> Use FitsAny in drain simulation

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_autodiscovery.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_autodiscovery_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
=> [cluster-autoscaler][clusterapi] Add support for node autodiscovery to clusterapi provider

cluster-autoscaler/cloudprovider/packet/OWNERS
Adds several engineers from Packet and long-standing contributors involved in Kubernetes tooling to the Autoscaler OWNERS file for the Packet cloud-provider.
Questions:
* What requirements are there beyond what is defined in https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md?
* Is there interest in having a bot subscribe these OWNERS based on Issue title or keywords? (There must be examples of this in other kubernetes/ repos).
=> add Packet cloudprovider owners

index.yaml
Manual release of CA Chart version 1.0.3 to include changes from #3487 
Fixes #3488
=> CA-Chart - 1.0.3 Release

cluster-autoscaler/README.md
Add HuaweiCloud info link to FAQ/Documentation section in CA main readme. It is currently missing the link and prevent from navigating to Huawei cloud provider readme.md from the main page.
=> Add HuaweiCloud info link to FAQ/Documentation section in CA main readme

cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go
k8s Azure clients keeps track of previous HTTP 429 and Retry-After cool
down periods. On subsequent calls, they will notice the ongoing throttling
window and will return a synthetic errors (_without HTTPStatusCode_) rather
than submitting a throttled request to the ARM API:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/vendor/k8s.io/legacy-cloud-providers/azure/clients/vmssvmclient/azure_vmssvmclient.go#L154-L158
https://github.com/kubernetes/autoscaler/blob/a5ed2cc3fe0aabd92c7758e39f1a9c9fe3bd6505/cluster-autoscaler/vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_error.go#L118-L123
Some CA components can cope with a temporarily outdated object view
when throttled. They call in to `isAzureRequestsThrottled()` on API clients
errors to return stale objects …
=> Azure: serve stale on ongoing throttling

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
This change should substantially decrease the number of GCE Read Requests when Node Deletion takes place. As Read Requests take place for each node, for large node cluster this is impact-ful.
=> Decrease the number of GCE Read Requests when node deletion.

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
=> Cherry pick #3437 onto 1.19 - Avoid unwanted VMSS VMs caches invalidations 

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
=> Cherry pick #3437 onto 1.18 - Avoid unwanted VMSS VMs caches invalidation

cluster-autoscaler/cloudprovider/azure/azure_util.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go
=> Cherry pick #3484 onto 1.19: Serve stale on ongoing throttling

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
=> Cherry pick #3440 onto 1.19 - optional jitter on initial VMSS VM cache refresh

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
=> Cherry-pick #3440 onto 1.18 - optional jitter on initial VMSS VM cache refresh

charts/cluster-autoscaler-chart/README.md
The documentation on using IRSA on AWS had an incorrect command to use to set the ARN of the IAM role. Fixed to match what is in values.yaml
=> Fix typo in chart README

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/metrics/metrics.go
Errors due to `IncreaseSize` should be of type "cloudProviderError" and not "apiError".
=> correctly label failed scale ups error

cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Cherry-picking ignored labels that were lost from [1.15.5 to 1.16](https://github.com/kubernetes/autoscaler/blob/c6929a2fa9632eb10eaad71621096f35eee7a736/cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go#L100). 
The MaxCapacityMemoryDifferenceRatio changes were needed to correct balance-similar-node-groups behavior on AWS but the removal of the labels prevents it working properly with kops. I don't think BalancingExtraIgnoredLabels is available into 1.19 so we are stuck with this unless that gets backported.
I didn't add tests for the labels to keep this as just a cherry-pick of existing commits.
=> Cherry-pick #2207 add kops instance group label to ignore list for similar node group identification.

vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go
I see pods that have Nodes as their owners in K8s `1.17` and `1.18`. We shouldn't try to fetch nodes, we know it's not a controller
=> Don't fetch nodes

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
This allows specifying effective nodes resources capacities using Scale
Sets tags, preventing wrong CA decisions and infinite upscale when pods
requests are within instance type capacity but over k8s nodes allocatable
(which might comprise system and kubelet's reservations), and when using
node-infos inferred from instances templates (ie. scaling from 0).
This is similar to what AWS (with launch configuration tags) and
GCP (with instances templates metadata) cloud providers offers,
ensuring the tags format is similar to AWS' for consistency.
See also:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/min_at_zero_gcp.md
=> Azure: support allocatable resources overrides via VMSS tags

cluster-autoscaler/cloudprovider/aws/aws_util.go
=> Fix pricing endpoint in AWS China Region

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go
Includes some minor clean-up in test of the public interface.
=> Extend GetContainersResources with an option to emit all containers.

cluster-autoscaler/cloudprovider/huaweicloud/OWNERS
This PR just added the OWNERS file under HUAWEICLOUD autoscaler directory.
I'm the maintainer of [cloud-provider-huaweicloud](github.com/kubernetes-sigs/cloud-provider-huaweicloud), and I'll take the responsibility of autoscaler in the future.
/cc @feiskyer
=> Add huaweicloud autoscaler owners file.

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go
This refactors all the template-related login separately and adds the missing stable labels for for os and arch
=> Add missing stable labels in the azure template

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_auto_scaling_group.go, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go
This PR just added support for auto scaling group  which can be used to implement node pool.
**Special notes for your reviewer**:
=> Add auto scaling group support for huaweicloud

vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/main.go
Because webhooks add to API request latency, they should evaluate as
quickly as possible. timeoutSeconds allows configuring how long the
API server should wait for a webhook to respond before treating the call
as a failure.
The default values from Kubernetes are, however, too large. For
admissionregistration.k8s.io/v1 the default value is 10 seconds while
for admissionregistration.k8s.io/v1beta1 is 30 seconds!
This custom/default value of 5 seconds should be more than enough for
standard installs.
=> Allow custom timeout value for webhook calls

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/mig_target_sizes_provider.go, cluster-autoscaler/utils/errors/errors.go, cluster-autoscaler/utils/test/test_utils.go
This is to support no nodepool exists conditions, which crashes Autoscaler
=> added a new NodeGroupDoesNotExistError in errors.go

charts/cluster-autoscaler-chart/Chart.yaml, charts/cluster-autoscaler-chart/README.md, charts/cluster-autoscaler-chart/templates/service.yaml, charts/cluster-autoscaler-chart/values.yaml
This PR adds support to configure additional service labels on the Helm chart.
=> [Helm Chart] Add support to configure custom service labels

index.yaml
I believe the URL was wrong on the previously merged PR here https://github.com/kubernetes/autoscaler/pull/3576.
This is a fix for the 1.0.4 release.
=> [Autoscaler Helm Chart] Fix wrong URL for the chart release 1.0.4

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go
=> Cherry pick #3308 onto 1.16 -Fix priority expander falling back to random although higher priority matches #3308

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go
=> Cherry pick #3308 onto 1.17 - Fix priority expander falling back to random although higher priority matches

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go
=> Cherry pick 3308 onto 1.18 - Fix priority expander falling back to random although higher priority matches

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go
=> Cherry pick #3308 onto 1.15 - Fix priority expander falling back to random although higher priority matches

vertical-pod-autoscaler/hack/deploy-for-e2e.sh, vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
Currently, images for 5 architectures are released for e2e, but only the ones for amd64 are actually used.
Building 5 versions of images takes quite a lot of time.
=> Only release one arch for tests

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go, cluster-autoscaler/version/version.go
=> Cherry pick 3308 onto 1.19 - Fix priority expander falling back to random although higher priority matches

.github/workflows/pr.yaml, .pre-commit-config.yaml, charts/README.md, charts/cluster-autoscaler-chart/Chart.yaml, charts/cluster-autoscaler-chart/README.md, charts/cluster-autoscaler-chart/README.md.gotmpl
As per discussion in https://github.com/kubernetes/autoscaler/pull/3424#issuecomment-704809247
* Adds a new step to the PR workflow to ensure that the docs have been generated by `helm-docs` and are up to date (enforced via `git diff --quiet`)
* Validated both successful and failing runs:
- Success: https://github.com/gjtempleton/autoscaler/runs/1223133897?check_suite_focus=true
- Failure: https://github.com/gjtempleton/autoscaler/runs/1223139683?check_suite_focus=true
* Updates the version of pre-commit hook of `helm-docs` used to update the files matcher pattern to include the `README.go.tmpl` ([this was added here](https://github.com/norwoodj/helm-docs/pull/50))
* Bumps the chart version by a minor bump
=> [Helm chart] Update helm-docs version and add PR action to ensure docs are updated

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_cloud_provider.go, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_node_group.go, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_node_group_test.go
Previously, two mutexes are used in the logic of removing a node from a node pool. Now only one mutex is used to simplify the logic and the time for removing a node can be shortened with this logic since it doesn't always have to wait for a certain time length before being deleted.
=> simplify DeleteNode logic by removing an extra Mutex

cluster-autoscaler/Makefile
This change adds an option to the `build-in-docker` and
`test-in-docker` make targets which allows usage on linux systems with
selinux enabled.  Currently these make targets use a volume mount to the
local directory for creating the binary output. On systems which have
selinux enforcing, the container runtime will disallow the mount to
occur. This change enables these make targets for selinux systems by
adding the `:Z` option to the volume flags.
On systems which do not have selinux enforcing this change will not have
any effect.
=> add volume mount label option to cluster-autoscaler makefile

cluster-autoscaler/main.go, cluster-autoscaler/processors/nodegroupset/gce_nodegroups.go
Commit bb2eed1cff introduced a new `topology.gke.io/zone` label to
GCE nodes templates, for CSI needs.
That label holds zone name, making nodeInfo templates dissimilar
for groups belonging to different zones. The CA otherwise tries to
ignore those zonal labels (ie. it ignores the standards LabelZoneRegion
and LabelZoneFailureDomain) when it looks for nodegroups similarities.
=> Ignore topology.gke.io/zone when comparing groups

vertical-pod-autoscaler/examples/hamster.yaml
hamster-vpa.yaml has a `.spec.resourcePolicy.containerPolicies` field, 
but that field has been supported from v1.
=> Fix VerticalPodAutoscaler version of hamster-vpa sample

cluster-autoscaler/README.md
This PR adds links to the Packet provider README.md to the root README.md.  It is otherwise not obvious that Packet support is included.
The Packet provider will need to be renamed to Equinix Metal in the future. I'm using the existing naming in this PR.
=> add Packet provider links to the root README.md

charts/cluster-autoscaler-chart/Chart.yaml, charts/cluster-autoscaler-chart/README.md, charts/cluster-autoscaler-chart/README.md.gotmpl, charts/cluster-autoscaler-chart/templates/deployment.yaml, charts/cluster-autoscaler-chart/values.yaml, cluster-autoscaler/cloudprovider/magnum/README.md, cluster-autoscaler/cloudprovider/magnum/examples/values-autodiscovery.yaml, cluster-autoscaler/cloudprovider/magnum/examples/values-example.yaml, cluster-autoscaler/cloudprovider/magnum/examples/values-minimal.yaml
Fixes #3399
@gjtempleton This is everything that I think needs to be changed, but I've marked this as WIP to discuss a few things. Mostly things where I'm assuming that other providers will also want to add to the chart.
First, I added
```yaml
autoDiscovery:
roles: []
```
for configuring `--node-group-auto-discovery` based on group roles. It serves the same purpose as the existing `autoDiscovery.tags` that AWS uses, but for keeping naming consistency within each provider I think it makes sense.
It would be possible to separate it as
```yaml
autoDiscovery:
magnum:
roles: []
```
and this might keep things more organised if there are going to be other providers adding to `autoDiscovery`.
Second, where I have this `or`
```
{{- if or (eq .Values.cloudProvider "gce") (eq .Values.cloudProvider …
```
=> Add magnum support in cluster autoscaler helm chart 

vertical-pod-autoscaler/pkg/utils/vpa/api.go
LastUpdateTime no longer exists and it is not used by this function.
The field was removed in API v1beta2 for scaling issue.
ref: https://github.com/kubernetes/autoscaler/pull/968
=> Remove obsolete comments

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
To help in cases where the VMSSVM cache TTL is set for too long and avoid unnecessary deletion calls
=> proactively set instance status to deleting on deletions

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
Cherry-pick #3532 onto 1.18: Azure: support allocatable resources overrides via VMSS tags.
=> Cherry-pick #3532 onto 1.18: Azure: support allocatable resources overrides via VMSS tags

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
Cherry-pick #3532 onto 1.17: Azure: support allocatable resources overrides via VMSS tags.
=> Cherry-pick #3532 onto 1.17: Azure: support allocatable resources overrides via VMSS tags

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
Cherry-pick #3532 onto 1.19: Azure: support allocatable resources overrides via VMSS tags.
=> Cherry-pick #3532 onto 1.19: Azure: support allocatable resources overrides via VMSS tags

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
Cherry-pick #3532 onto 1.16: Azure: support allocatable resources overrides via VMSS tags.
=> Cherry-pick #3532 onto 1.16: Azure: support allocatable resources overrides via VMSS tags

cluster-autoscaler/cloudprovider/gce/templates.go
The removed log lines had a very misleading ERROR severity, which
caused confusion. Furthermore, they were completely redundant when
no error happens - the same information can be deduced from the log
line at the end of extractAutoscalerVarFromKubeEnv.
Not finding a value in kubeEnv having a WARNING severity also seems
like too much.
=> Remove redundant log lines and reduce severity around parsing kubeEnv

cluster-autoscaler/cloudprovider/gce/gce_price_model.go
It turns out changing those values has unexpected impact on
the results of pricing expander. I think that a different base
value implicitly changes the weight of pricing to the
other parts of expander formula which is some cases changes CA
scaling decisions.
While not necessarilly wrong we shouldn't make changes like this
without analyzing implications and testing, hence the revert
of this part.
=> Revert base price changes from PR #3603

cluster-autoscaler/core/scale_down.go
I noticed this log message on a cluster with a large amount of nodes and many scale events. Especially in cases where a node isNodeBelowUtilizationThreshold() this reduces the number of lines logged. This log message is redundant since the same information is found in the isNodeBelowUtilizationThreshold check, so moving this log after it reduces the total number of messages 
Since this function is called for each node, reducing the number of logs in total is desired
=> Reduce logging in scale calculation

cluster-autoscaler/Makefile
The value of `DOCKER_NETWORK` is used for `--network` during `docker build`, default is `default`.
Setting `DOCKER_RM` to any non-empty value adds `--rm` for `docker run`.
=> Configurable --network and --rm flags for docker

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go
This PR implemented the `GetDesireInstanceNumber` interface of the cloud service manager.
=> [CA]Implementes get desire instance number of node group.

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/utils/kubernetes/ready.go
Conditions and their corresponding taints can sometimes skew, which
can cause unnecessary scale-up. CA thinks nodes are ready because it
looks only at the conditions, but scheduler predicates fail because they
consider the taints as well. CA adds nodes, even though the existing
nodes are still starting. This commit brings CA behavior in line
with scheduler predicates behavior, eliminating the unnecessary
scale-up.
NOTE: NoSchedule taints don't have TimeAdded set, which is why I
implemented `isNodeStillStarting` this way.
=> Include taints by condition when determining if a node is unready/still starting

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
This change removes the `PollImmediateInfinite` calls in the cluster-api
controller unit tests in favor of `PollImmediate`. It is being proposed
to prevent an edge case where the polling calls would become blocked
indefinitely. As we are using fake clients within the unit tests there
should be no delay getting a return value, but just in case there is a
miss on the poll function the new `PollImmediate` will timeout after 15
seconds.
=> refactor CAPI controller unit test to use PollImmediate

cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_auto_scaling_group.go, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go
Implemented TemplateNodeInfo function. TemplateNodeInfo returns a schedulerframework.NodeInfo structure of an empty
(as if just started) node. This will be used in scale-up simulations to predict what would a new node look like if a node group was expanded. The returned NodeInfo is expected to have a fully populated Node object, with all of the labels, capacity and allocatable information as well as all pods that are started on the node by default, using manifest (most likely only kube-proxy).
=> implemented TemplateNodeInfo function

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml
To support deploying CA on AWS EKS, we would need to update the volume mount path to '/etc/ssl/certs/ca-bundle.crt'
As the current volume mount path which is /etc/ssl/certs/ca-certificates.crt is not found on AWS EKS worker nodes with the error below:
=> Update Cluster Autoscaler (CA) volume mount path to /etc/ssl/certs/ca-bundle.crt

cluster-autoscaler/cloudprovider/huaweicloud/examples/cluster-autoscaler-svcaccount.yaml, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_auto_scaling_group.go
This PR :
- make sure all nodes belong to the specific node group before scale down.
- remove nodes from cluster after scale down.
- update example service account, CA requires node delete.
some logs from local testing:
```
I1110 05:03:59.033880       1 delete.go:103] Successfully added ToBeDeletedTaint on node k8s-node-components-1ney296p
I1110 05:03:59.158326       1 huaweicloud_auto_scaling_group.go:123] going to remove node from scaling group. group: e7c3f6ff-d6b3-4b22-b809-47a22c180276, node: eb81661f-ad84-4f8e-8a19-c31b514e3d12
I1110 05:03:59.372705       1 huaweicloud_auto_scaling_group.go:250] deleted one node from cluster. node name: k8s-node-components-1ney296p
```
=> [CA]delete nodes from cluster after scale down

index.yaml
* Release of version 1.1.1 of the cluster autoscaler chart
Includes changes from #3672
=> CA-Chart - 1.1.1 Release

cluster-autoscaler/hack/update-vendor.sh
The update-vendor.sh script needed some fixes to work with zsh on OSX.
Various binaries are expected to be GNU utils, which are not installed by default on OSX. I've added suggestions to install ported binaries using homebrew if they are not found in PATH.
Skip `shopt -s lastpipe` when `$BASH` is not defined.
=> Fixes for update-vendor.sh on OSX and zsh

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
There already is `envFromSecret` and `extraEnvSecrets`, so I made `envFromConfigMap` behave like `envFromSecret` and added `extraEnvConfigMaps` to replace it.
This pattern should make the intended use of the values clearer.
=> Add `extraEnvConfigMaps` and document some values

index.yaml
* Includes changes from:
* #3679 - Renames chart to `cluster-autoscaler` and associated version bump to `9.0.0`
* #3691  - Adds extra config map injection functionality and documents existing options - bump to `9.1.0`
=> CA-Chart - 9.0.0 & 9.1.0 Release

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml
Noticed the container port wasn't actually being listened to, and found out that metrics were running on a different port. Updates the deployment manifests to match the defaults.
=> Update vertical-pod-autoscaler containerPorts to reflect default ports

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_cache_storage.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_cache_storage_test.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher_test.go
Cache results of attempting to determine the parent a controller.
This is to improve VPAs performance in big clusters, where we need to throttle queries we're making.
How caching is supposed to work:
* When we first try to determine parent of a controller try to get it (and cache the result).
* This should happen rarely (when new controllers appear and when VPA starts). So it shouldn't affect VPAs performance heavily
* It let's us avoid incorrect state
* On consequent attempts to get parent of a controller return the cached result
* We do this frequently, so this should significantly improve our performance
* Refresh content of cache and remove unused entries in parallel
=> Cache controllers

cluster-autoscaler/processors/status/eventing_scale_up_processor.go
If we try to deploy a pod that is bigger than the node itself, currently we get an error message like this one:
**cluster-autoscaler pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 Insufficient cpu**
the problem is when the error is due to another reason. For example:
**cluster-autoscaler pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 in backoff after failed scale-up**
In that case, the problem has nothing to do with _"it wouldn't fit if a new node is added"_, so I think that only the second part of the error message is relevant in such cases, and the first brings some confusion.
The proposed change for the same case is :
**pod didn't trigger scale-up: 1 in backoff after failed scale-up**
=> Improve error message: Not all error are due to "it wouldn't fit if a new node is added"

cluster-autoscaler/Dockerfile.amd64, cluster-autoscaler/Dockerfile.arm64, cluster-autoscaler/Makefile
I tried to keep existing target names to be as close as possible to existing ones and to build only AMD64 by default.
Similar targets with the **-arch-%** suffix were added and allow specifying the architecture, for example `build-arch-amd64` and `build-arch-arm64`.
A new Dockerfile had to be added for ARM64 support and also a target named `push-manifest` for generating the multi-arch manifest *after* both AMD64 and ARM64 images are pushed.
Releasing both AMD64 and ARM64 is a bit awkward due to the **About to push image/manifest. Are you sure? [y/N]** input in `push_image.sh`.
The only major change is that both the binaries and the images are now suffixed with the arch name.
Fixes: #3419 
/cc @MaciekPytel @gjtempleton
=> [cluster-autoscaler] Add build support for ARM64

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
This value can be used to render `volumes` and `volumeMounts`.
=> Add extraVolumeSecrets chart value

index.yaml
* Brings in new functionality from #3692 
Addition/re-organisation of `type: application` labels on all previous charts due to update of local helm version being used to generate the `index.yaml`
=> CA-Chart - 9.2.0 Release

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/_helpers.tpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
Allows adding arbitrary labels to manifests deployed by the chart.
My use case is for anti-affinity rules with other deployments: I want to define a label across all relevant deployments, then an antiAffinity rule on all of them.
Even though it could work through `podLabels`, I don't find that field great for this use case: it doesn't make much sense to add it to the deployment selector.
=> Add additionalLabels chart value

cluster-autoscaler/cloudprovider/cloud_provider.go
As described in #3731, this commit fixes a copy / paste error in a comment.
=> Fixes copy / past error in comment

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
Stop watching pods in `Succeeded` and `Failed` states. I ran `full-vpa` e2e tests on this and they passed (including the OOM test).
I grabbed VPA logs about OOMs and one was discarded.  But it was because the OOM was too old, not because we removed the container (which was my worry about the change):
```
$ kubectl logs -n kube-system vpa-recommender-f7c794c46-swx8l|grep -i oom
I1204 14:57:45.110882       1 cluster_feeder.go:419] OOM detected {Timestamp:2020-12-04 14:57:35 +0000 UTC Memory:1073741824 ContainerID:{PodID:{Namespace:vertical-pod-autoscaling-7787 PodName:hamster-69d67ccbd4-lghrd} ContainerName:hamster}}
I1204 14:57:45.110956       1 cluster_feeder.go:419] OOM detected {Timestamp:2020-12-04 14:57:37 +0000 UTC Memory:1073741824 …
```
=> Watch only pods in state Running and Unknown

vertical-pod-autoscaler/deploy/kustomization.yaml, vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/hack/deploy-for-e2e.sh, vertical-pod-autoscaler/hack/generate-crd-yaml.sh, vertical-pod-autoscaler/hack/vpa-process-yamls.sh, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/doc.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/doc.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/doc.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go, vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/doc.go
ref: https://github.com/kubernetes/autoscaler/issues/3508
In this PR, I generate CRD v1 from types.go using `controller-gen@v0.4.0`.
Here are some things to note:
- Generates only the API version that was served in the previous manifest.
- The not recommended float64 is used as the CRD value, so `allowDangerousType` option is enabled. (ref: https://github.com/kubernetes-sigs/controller-tools/issues/245#issuecomment-518465214)
- `viacheckpoint` have int map key that is not supported in JSON, so disable validation only for that field. Along with this, generation script ignores error returned by controller-gen. (ref: https://github.com/kubernetes/autoscaler/issues/3574)
- `metav1.ObjectMeta` does not accept optional tags, so remove it from types.go.
=> Generate VPA CRD v1 from types.go

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
As discussed on weekly meeting, the first cut of suggested issue templates. Based off the main k/k repo's [issue templates](https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE).
I think I've covered all of the details we generally want to gather for either bug reports or feature requests.
=> Initial Issue Templates

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go, cluster-autoscaler/cloudprovider/azure/azure_agent_pool_test.go, cluster-autoscaler/cloudprovider/azure/azure_autodiscovery.go, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cache_test.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This PR cleans up the Azure cloud provider cache to optimize API calls and facilitate further improvements.
Currently, multiple Azure VMSS List calls are made throughout the code, such as [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L267) and [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_scale_set.go#L188). In addition, [agent_pools](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go#L374) and [aks](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_kubernetes_service_pool.go#L173) providers both have their own code to list VMs.
This centralizes all VM …
=> cleanup: refactor Azure cache and remove redundant API calls

cluster-autoscaler/cloudprovider/gce/reserved.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go, cluster-autoscaler/simulator/delegating_shared_lister.go
This change will allow us to scale from zero nodepools for pods requiring ephemeral storage
=> Ephemeral Storage support for BuildNodeFromTemplate in GCE

cluster-autoscaler/Makefile
This seems to be the current convention in k8s.
=> Make arch-specific releases use separate images instead of tags on the same image

cluster-autoscaler/Dockerfile.amd64, cluster-autoscaler/Dockerfile.arm64, cluster-autoscaler/Makefile
Cherry pick of #3714 on cluster-autoscaler-release-1.19.
#3714: Add build support for ARM64
=> Automated cherry pick of #3714: Add build support for ARM64

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
=> ignoring terminated pods in scaledown

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml
Because of incorrect casing (.values instead of .Values), the Deployment template fails when the additionalLabels block is defined.
=> chart: fix reference to additionalLabels in deployment template

cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
This will allow ephemeral storage from boot disk to be skipped and not picked when BuildNodeFromTemplate is used to create a node.
=> adding support to block ephemeral storage from boot disk

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
If for some reason we can't create the watch we shouldn't retry too
quickly. This may break VPA in a cluester when everything seem otherwise
healthy.
=> Wait with jitter between attempts to start watching pod evictions

cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml
This PR fixes sample manifest of cluster-autoscaler clusterapi provider.
(cherry picked from commit a5fee21a6889c39ab3bab384f74e72b18b891659)
=> Backport of #3805: Fix cluster-autoscaler clusterapi sample manifest

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/deletetaint/delete_test.go
This helps load balancer to remove the node from healthy hosts (ALB does have this support).
This won't fix the issue of 502 completely as there is some time node to live even after cordoning as to serve In-Flight request.
Shamelessly copied from https://github.com/kubernetes/autoscaler/pull/3014/files
=> Adding functionality to cordon the node before destroying it. 

vertical-pod-autoscaler/common/version.go
`full-vpa` tests passed, I'm running other test suits now
=> Vertical Pod Autoscaler release 0.9.2

cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml
when apply those rbac file, it mentioned 
```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
```
=> Switch from v1beta1 to v1 for rbac

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/cache_test.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_instance_templates_provider.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go
With 1.5k MIGs attached to a cluster, cluster-autoscaler needs about
40mn to start. Refreshing MIGs+ITs concurrently brings that down to
about 5mn.
While bulk GCE API calls (triggered at startup and on Refresh() calls)
and a few stateless functions (called by GetMigInstanceTemplate) become
concurrent, cache accesses remains lock protected. To that effect:
* Set RegenerateInstancesCache to run parallels RegenerateInstanceCacheForMig
(slightly adapted so the slow GceService.FetchMigInstances call isn't locked)
* Set fetchAutoMigs to run parallels registerMig: rework GetMigInstanceTemplate
so the slow InstanceGroupManagers.Get+InstanceTemplates.Get calls aren't locked
Tested on a large k8s cluster (> 1k MIGs) with intense scaling activity,
and tested on live clusters with "go build -race" …
=> gcp: faster startup and refreshes with many MIGs

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
Conventionally, commented out values in the values.yaml file should match the default values for the commented out parameters. Some of the parameters here didn't match, so I've corrected them, as per the documented defaults in [the FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md).
It's likely worth discussing whether this section should either be supplemented to include all of the defaults, or whether it should just link to the documentation of the flags in the FAQ. However for now, the defaults listed match their real default values.
=> Update values.yaml defaults to match real default values

addon-resizer/nanny/kubernetes_client.go
Node calculation should fail when there is a problem with decoding metrics. Addon Resizer will retry querying metrics after a few second (main loop).
=> Addon Resizer - Handling decoding error

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/main.go
We consider a node to be empty if it doesn’t run any regular pod, i.e. node runs only Mirror and DaemonSet pods.
Cluster Autoscaler checks for empty nodes in the cluster and deletes them if they exist. The process deletes a chunk of empty nodes concurrently without DaemonSet pods eviction (meaning those pods have no chance to cleanly exit)
This PR is aimed to add DaemonSet eviction functionality for empty nodes.
More info in the discussion: #1578
=> add DaemonSet eviction option for empty nodes

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
With the recent switch to generated CRD definition, we also stopped saving unknown fields. Since v1beta2 does not contain some fields that v1 does, the fields get dropped silently on object creation. 
Switching to v1  as storage version solves that problem.
fixes #3800
=> Change VPA storage version from v1beta2 to v1

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/templates/role.yaml, charts/cluster-autoscaler/values.yaml
Partially resolves: https://github.com/kubernetes/autoscaler/issues/3724
Following lint error is well known issue:
```
templates/: template: cluster-autoscaler/templates/role.yaml:15:7: executing "cluster-autoscaler/templates/role.yaml" at <eq (default .Values.extraArgs.expander "") "priority">: error calling eq: invalid type for comparison
```
https://github.com/helm/helm/issues/6376
The workaround doesn't seem to work.
=> Fix cluster-autoscaler chart to match with the examples

cluster-autoscaler/main.go
This is the start to allow for multiple deployments of the Cluster Autoscaler to be running in the same Namespace
=> Allow for the leader election resourcelock to have a configurable name

cluster-autoscaler/cloudprovider/clusterapi/README.md
not only for currency, but also for not able to scale up issue
exactly same env using 18.1 see 
```
Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-deployment-779b9ccfcb-ghhpv", UID:"4b3c8da3-0d61-41cb-8f72-b26565be42e4", APIVersion:"v1", ResourceVersion:"720250", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```
but 1.20.0 can successfully scale up node
=> bump clusterapi sample suggested version from 1.18.1 to 1.20.0

cluster-autoscaler/cloudprovider/azure/azure_config_test.go
The test assumption "metadataURL in azure_manager.go is not available for our tests" is not correct, let's remove this test case.
closes #3861
=> Azure: Cleanup test

charts/cluster-autoscaler-chart/.helmignore, charts/cluster-autoscaler-chart/Chart.yaml, charts/cluster-autoscaler-chart/README.md, charts/cluster-autoscaler-chart/README.md.gotmpl, charts/cluster-autoscaler-chart/templates/NOTES.txt, charts/cluster-autoscaler-chart/templates/_helpers.tpl, charts/cluster-autoscaler-chart/templates/clusterrole.yaml, charts/cluster-autoscaler-chart/templates/clusterrolebinding.yaml, charts/cluster-autoscaler-chart/templates/deployment.yaml, charts/cluster-autoscaler-chart/templates/pdb.yaml, charts/cluster-autoscaler-chart/templates/podsecuritypolicy.yaml, charts/cluster-autoscaler-chart/templates/priority-expander-configmap.yaml, charts/cluster-autoscaler-chart/templates/role.yaml, charts/cluster-autoscaler-chart/templates/rolebinding.yaml, charts/cluster-autoscaler-chart/templates/secret.yaml, charts/cluster-autoscaler-chart/templates/service.yaml, charts/cluster-autoscaler-chart/templates/serviceaccount.yaml, charts/cluster-autoscaler-chart/templates/servicemonitor.yaml, charts/cluster-autoscaler-chart/values.yaml
**There will be a follow-up PR to remove these files as only one release marked as deprecated is required.**
This diff looks very big, however this is due to copying back in the files for the `cluster-autoscaler-chart` Helm chart as it was pre the renaming to `cluster-autoscaler` performed by #3679 .
The actual changes performed by this PR to the last previous release of the `cluster-autoscaler-chart` chart marked by https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-chart-1.1.1 can be seen by running 
```bash
git diff cluster-autoscaler-chart-1.1.1 charts/cluster-autoscaler-chart/
diff --git a/charts/cluster-autoscaler-chart/Chart.yaml b/charts/cluster-autoscaler-chart/Chart.yaml
index 4f86dcc4d..b288ae4a8 100644
--- a/charts/cluster-autoscaler-chart/Chart.yaml
+++ …
```
=> CA-Chart - Mark Cluster-Autoscaler-Chart as Deprecated

index.yaml
* Pushes the release caused by #3719 to the index.yaml for indexing by artifact hub to complete marking of prior chart release name as deprecated
=> CA-Chart - Update index with final ca-chart chart release

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/utils/scheduler/scheduler.go
Function copying template node to use for upcoming nodes was
not chaning hostname label, meaning that features relying on
this label (ex. pod antiaffinity on hostname topology) would
treat all upcoming nodes as a single node.
This resulted in triggering too many scale-ups for pods
using such features. Analogous function in binpacking didn't
have the same bug (but it didn't set unique UID or pod names).
I extracted the functionality to a util function used in both
places to avoid the two functions getting out of sync again.
I suspect this may have also been the root cause for #3721.
=> Set different hostname label for upcoming nodes

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/metrics/metrics.go
I want to set up alerting for cases where nodes are unremovable due to user errors, like lack of "safe to deschedule" annotation, and so this Pull Requests adds a Gauge sliced by `fmt.Sprintf("%s", simulator.UnremovableReason)`.
I wasn't sure if there is any concurrent access involved, so added a mutex for the counter map, please let me know if it is unnecessary.
I also wasn't sure how to test this, any suggestions are welcome.
=> Add unremovable_nodes_count metric

cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
The "gen" tool used to generate ec2_instance_types.go creates the file without a comment for the exported type InstanceType so golint complains in the CI, this patch adds the same comment that currently is in ec2_instance_types.go in the template too.
=> Add comment for exported type InstanceType in gen template

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
On clusters with large pools this log line is extremely excessive. The message can be printed once and the names of the created nodes can be inferred if desired
=> Reduce logging when creating placeholder instances

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
This PR updates the default image tag in the Helm Chart, from v1.18.1 to v1.20.0.
The reason for the default tag change is to enable the fixes contained in [Cluster Autoscaler 1.20.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.20.0) by default for all future Helm installation of the cluster autoscaler.
=> Helm Chart Image Update (v1.18.1 → v1.20.0)

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/prometheusrule.yaml, charts/cluster-autoscaler/values.yaml
This PR adds prometheus rule support.
It is complementary with `serviceMonitor`.
=> feat: add prometheus rule support

index.yaml
* Publish 9.6.0 of the Cluster Autoscaler chart, includes changes from #3900
=> CA-Chart - 9.6.0 Release

cluster-autoscaler/.gitignore
adding entries for the amd64 and arm64 targets.
=> add arch specific cluster-autoscaler targets to gitignore

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
ref: https://github.com/kubernetes/autoscaler/issues/3917
Support additional-print-columns to make it easier to understand the status of VPA resources. 
NOTE: YAML is generated by `hack / generate-crd-yaml.sh`.
=> Support additional-print-columns for VPA CR

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/proposals/metrics.md
This change adds a new metric which counts the number of nodes removed
by the cluster autoscaler due to being unregistered with kubernetes.
User Story
As a cluster-autoscaler user, I would like to know when the autoscaler
is cleaning up nodes that have failed to register with kubernetes. I
would like to monitor the rate at which failed nodes are being removed
so that I can better alert on infrastructure issues which may go
unnoticed elsewhere.
=> add a metric for unregistered nodes removed by cluster autoscaler

cluster-autoscaler/cloudprovider/aws/aws_util.go
Add the output of the error to the log so users can identify why the autoscaler was unable to fetch the url.
See https://github.com/kubernetes/autoscaler/issues/3891
=> Add Fetch Error Output to Warning Log

.github/workflows/pr.yaml, charts/README.md, charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/values.yaml
* Fixes #3899 by clarifying Helm chart versioning confusion, hides details under an expandable section and makes strong recommendation to use supported version
* Updates the image for the repo to point at the raw kubernetes logo, for [Artifact hub](https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler) purposes, the current URL 404s
* Updates the default Cluster-autoscaler image repository to the full vanity URL rather than the US endpoint, this should provide some speed benefits for non US based users
* Fixes the helm testing and linting actions run on PRs, as per [discussion on a previous PR](https://github.com/kubernetes/autoscaler/pull/3880#issuecomment-778280580) this should have been caught by the action but due to the [major version …
=> CA-Chart Readme Updates & Fix Chart Lint and Test Actions

cluster-autoscaler/FAQ.md, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/clusterstate/utils/status.go, cluster-autoscaler/clusterstate/utils/status_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go
Adds `--status-config-map-name`, which defaults to the original value of `cluster-autoscaler-status`.
This allows us to run two instances of cluster-autoscaler in our cluster, targeting two different types of autoscaling groups that require different command-line settings to be passed.
Do you foresee this causing any issues with the cluster-wide portion of the configmap status?
=> Allow name of cluster-autoscaler status ConfigMap to be specificed

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
AWS introduced EC2 G4 instances that run up to
4 NVIDIA T4 GPUs.
See https://docs.aws.amazon.com/dlami/latest/devguide/gpu.html
for more info on the new instance type.
Signed-off-by: Raymond Etornam <retornam@users.noreply.github.com>
=> Support AWS new GPU type - T4

cluster-autoscaler/Makefile
This change removes an extra build command from the `build-arch-%`
target. The extra build command has been in the Makefile since the
beginning but doesn't seem to be needed any more.
This was referenced in a comment on slack[0], and it doesn't seem to affect the binary building inside or outside of a container build.
[0] https://kubernetes.slack.com/archives/C09R1LV8S/p1612003154063600
=> remove extra build command from cluster-autoscaler

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/utils/utils.go, cluster-autoscaler/utils/kubernetes/ready_test.go, cluster-autoscaler/utils/test/test_utils.go
Fix bug where a node that becomes ready after 2
mins can be treated as unready. Deprecated LongNotStarted
In cases where node n1 would:
1) Be created at t=0min
2) Ready condition is true at t=2.5min
3) Not ready taint is removed at t=3min
the ready node is counted as unready
Tested cases after fix:
1) Case described above
2) Nodes not starting even after 15mins still
treated as unready
3) Nodes created long ago that suddenly become unready are
counted as unready.
=> Fix bug where a node that becomes ready after 2

cluster-autoscaler/cloudprovider/aws/aws_manager.go
This simple patch allowed me to scaled ASG from 0 to X for a deployment having a NodeSelector label which is part of the ones `buildGenericLabels()` sets.
In my case it was `beta.kubernetes.io/arch`.
=> Allow generic labels to be overwritten by tags coming from the ASG

vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go, vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling_test.go
In this PR changed not to set a limit when a recommendation is empty. This solves #3902 issue of sending patches for the not-controlled resource by VPA when Pod has resource limits.
=> Do not set limits when recommendation is 0

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml
GCE doesn't require loading /etc/gce.conf from a hostpath. In-fact this file isn't available at all on GCE nodes nor on GKE nodes. This was a left-over from the way GKE bundled autoscaler seems to work. There have been multiple reports of GCE deployment being broken due to this. For example see: helm/charts#10292 and helm/charts#15509
Another example of people not being able to deploy GCE because the README points to no longer existing docs: https://github.com/kubernetes/autoscaler/issues/3798
After the PR is merged this blog post will work: https://samos-it.com/posts/gke-custom-oss-cluster-autoscaler.html however if you try to run the blogpost steps today it would fail because it tries to mount /etc/gce.conf with no way of disabling that behaviour.
=> Fix GCE where no cloud-config-path is required

README.md
Just mentioning AWS, Azure and GCP makes it sounds like only those are supported.
Now however, many more platforms are supported.
=> Update description of CA in main README

vertical-pod-autoscaler/README.md
In c2d24bd716da4428e29b34a3d3bb2623902181cd the default
version of VPA was updated to 0.9.2
This patch reflects the change in the README, as well.
=> Update VPA README with current default version

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/values.yaml
Supplementary documentation to help anyone using the #3888 functionality
=> adds status-config-map-name to values.yaml of helm chart

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/values.yaml
Incredibly minor, but there's a typo in the Charts default values; the field for volume mounts when mounted read only is `readOnly`, not `readonly`, so if you directly uncomment it, `helm install` will fail. This fixes that.
=> Fix typo in values.yaml example for extraVolumeMounts

cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go
Add information about A2 machine family pricing to GCE. This family contains only predefined machines, each with a fixed number of `nvidia-tesla-a100` GPUs. As these GPUs cannot be created outside of A2 family, their price is counted into A2 machine price.
https://cloud.google.com/compute/vm-instance-pricing#accelerator-optimized
=> Add A2 machine family pricing for GCE

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
The refactor in https://github.com/kubernetes/autoscaler/pull/3717 missed adding this method to fetch and register auto-discovered groups.
=> fix: add missing call to fetch autodiscovered nodegroups

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
Allow users to change thresholds for evicting pods that use resources lower that recomended. Some pods needs to lower their request less than 12h.
This changes only allow users to change hardcoded values
New flags that will added with this PR
| Name | Default | Usage |
| --- | --- | --- |
| `pod-update-threshold` | 0.1 | Ignore updates that have priority lower than the value of this flag |
| `in-recommendation-bounds-eviction-lifetime-threshold` | 12h | Pods that live for at least that long can be evicted even if their request is within the [MinRecommended...MaxRecommended] range |
=> Allow users to change thresholds for evicting pods in VPA

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/processors/customresources/custom_resources_processor.go, cluster-autoscaler/processors/customresources/gpu_processor.go, cluster-autoscaler/processors/customresources/gpu_processor_test.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/utils/gpu/gpu.go, cluster-autoscaler/utils/gpu/gpu_test.go
Currently the logic regarding custom resources (other than cpu and memory) in Cluster Autoscaler is limited to GPU resources. Because nodes need to install GPU drivers, the GPU resources may not become allocatable immediately after the node creation. This required implementing  additional functionality (GPU hack) to better handle this case, predicting the type/count of GPUs in case the drivers were not yet installed.
The refactor was suggested because:
1. This logic is dependent on the underlying implementation of driver installation in the cluster, so it would be useful to have it fine-tunable for specific cases. This was done by creating a separate processor and moving the current implementation there.
2. In the future it may be applied for other custom resources, thus we would greatly …
=> Separate and refactor custom resources logic

cluster-autoscaler/proposals/circumvent-tag-limit-aws.md
This proposal is related to this issue that AWS EKS has open: https://github.com/aws/containers-roadmap/issues/724
The proposal was originally in kubernetes/enhancements. See the previous feedback cycle here: https://github.com/kubernetes/enhancements/pull/2561
@gjtempleton 
@jaypipes
=> Proposal to circumvent 50 tag ASG limit for EKS ManagedNodegroups

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_autodiscovery.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_autodiscovery_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml
This PR updates managementInformerFactory to watch only the namespace specified in auto discovery specs. This is useful to limit rbac permissions for management cluster role. Right now we use `ClusterRole` for accessing scalable resources in management cluster. With this change, we can limit it to a single namespace where the scalable resources are to be watched.
Fixes #3870
=> CAPI Management cluster informer to watch single namespce

cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_clusterapi.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider_test.go
This is a housekeeping PR that updates the cluster-api provider const reference to `ClusterAPIProviderName` (from `ClusterAPIProiverName`).
No functional change should be observed as a result of updating this const.
=> cloudprovider: ClusterAPIProviderName spelling

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml
This PR updates capi namespace in autoscaler deployment in cluster api examples. This is needed since #4012 introduced changes to use `Role` rbac instead of `ClusterRole` for watching capi scalable resources
=> Fix CAPI example

cluster-autoscaler/cloudprovider/gce/gce_url.go, cluster-autoscaler/cloudprovider/gce/gce_url_test.go
The current implementation assumes MIG ids have the
"https://content.googleapis.com" prefix, while the
canonical id format seems to begin with "https://www.googleapis.com".
Both formats work while talking to the GCE API, but
the API returns the latter and other GCP services seem to
assume it as well.
=> Cluster Autoscaler GCE: change the format of MIG id

cluster-autoscaler/OWNERS
[Approver requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#approver) for @towca:
* Reviewer of the codebase for over 4 months (#3774)
* Primary reviewer for at least 10 substantial PRs to the codebase
* #3545
* #3566
* #3690
* #3701
* #3749
* #3789
* #3929
* #3321
* #3722
* #3350
* Reviewed or merged at least 30 PRs to the codebase
* Reviewed the PRs listed above.
* Authored these 37 PRs to the codebase: https://github.com/kubernetes/autoscaler/pulls?page=1&q=is%3Apr+author%3Atowca.
* Nominated by a subproject owner: @MaciekPytel
=> Remove vivekbagade, add towca as an approver in cluster-autoscaler/OWNERS

cluster-autoscaler/cloudprovider/magnum/magnum_util.go
Fixes #3928
Now supported by magnum.
https://review.opendev.org/c/openstack/magnum/+/737580/
If using node group autodiscovery, older versions
of magnum will still forbid scaling to zero or
setting the minimum node count to zero.
=> Enable magnum provider scale to zero

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go
Force refreshing everything at every `DeleteNodes` calls causes slow down
and throttling on large clusters with lots of ASGs and activity.
That function might be called many times in a row during scale-down.
Each time the forced refresh will re-discover all ASGs, all LaunchConfigurations,
then re-list all instances from discovered ASGs.
That immediate refresh isn't required anyway, as the cache's DeleteInstances
concrete implementation will decrement the nodegroup size, and we can
schedule a grouped refresh for the next loop iteration.
As a later step, we can consider splitting the asgCache.generate() function
to support per ASG refreshes (and maybe per ASG caches TTLs + jitter, to
spread API calls). But that should address the current issue for now.
=> aws: Don't pile up successive full refreshes during AWS scaledowns

cluster-autoscaler/main.go
```go
// ReleaseOnCancel should be set true if the lock should be released
// when the run context is cancelled. If you set this to true, you must
// ensure all code guarded by this lease has successfully completed
// prior to cancelling the context, or you may have two processes
// simultaneously acting on the critical path.
```
=> Release leader election lock on shutdown

cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go
similar to how we support setting labels with an underscore _ instead of the "/" separator blocked by Azure tags
=> support "/"separators in custom allocatable overrides via vmss tags

addon-resizer/nanny/kubernetes_client.go, addon-resizer/nanny/kubernetes_client_test.go
This is a permanent fix for addon resizer removing field values in deployments that it does not know about due to using an old Kubernetes client library. Only appropriate resource requests and limits should be changed.
Fixes #3567
=> Addon resizer uses patch for deployment update

cluster-autoscaler/FAQ.md
Resolves #4065. Kubernetes extensively documents what needs to happen for a Kubelet to register with the apiserver, so linking to the main doc is the simplest resolution.
=> Document that TLS bootstrapping may be necessary for scale-up

cluster-autoscaler/FAQ.md, cluster-autoscaler/hack/submodule-k8s.sh, cluster-autoscaler/hack/update-vendor.sh
`update-vendor.sh` was using hardcoded open-source Kubernetes repository, which made it impossible to update vendor dependencies based on a Kubernetes fork, which was the case prior to the refactor of `update-vendor.sh`. This PR implements that by moving from `curl` command to `git` based solution which works also in closed source repositories.
=> Enable custom k8s fork in update-vendor.sh

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/proposals/metrics.md
This change adds 4 new metrics to the cluster autoscaler that help a user to determine the CPU cores and memory usage in their cluster.
There are 2 metrics devoted to the limits for cores and memory, with labels for maximum and minimum.
* `cluster_autoscaler_cpu_limits_cores`
* `cluster_autoscaler_memory_limits_bytes`
There are also 2 metrics devoted to the current count of cores and memory in bytes.
* `cluster_autoscaler_cluster_cpu_current_cores`
* `cluster_autoscaler_cluster_memory_current_bytes`
Sample scrape of new metrics on a running cluster:
```
cluster_autoscaler_cpu_limits_cores{direction="maximum"} 320000
cluster_autoscaler_cpu_limits_cores{direction="minimum"} 0
cluster_autoscaler_memory_limits_bytes{direction="maximum"} 6.8719476736e+15 …
```
=> Cluster resource consumption metrics

cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml
Hello, this is a little fix for ClusterRole of hetzner cluster-autoscaler example
=> add required api resources to hetzner cluster-autoscaler example

cluster-autoscaler/cloudprovider/ionoscloud/client.go, cluster-autoscaler/cloudprovider/ionoscloud/client_test.go, cluster-autoscaler/cloudprovider/ionoscloud/ionoscloud_manager.go, cluster-autoscaler/cloudprovider/ionoscloud/ionoscloud_manager_test.go, cluster-autoscaler/cloudprovider/ionoscloud/utils.go, cluster-autoscaler/go.mod, cluster-autoscaler/go.sum, cluster-autoscaler/vendor/modules.txt
Fixes #4068  for ionoscloud provider.
=> Replace package satori/go.uuid for cloudprovider ionoscloud

addon-resizer/Makefile
Looks like 1.8.12 was already released:
https://github.com/kubernetes/autoscaler/releases/tag/addon-resizer-1.8.12
=> Addon resizer version 1.8.13

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
This is a backport of the changes in #3545 to release 1.18 to ignore terminated pods from scaledown calculation.
This is not a direct cherry-pick, mainly addressing the change in https://github.com/kubernetes/autoscaler/pull/3083
=> [cluster-autoscaler] Backporting #3545 to release 1.18

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
This is a backport of the changes in #3545 to release 1.19 to ignore terminated pods from scaledown calculation.
This is not a direct cherry-pick, mainly addressing the minor change in https://github.com/DataDog/autoscaler/commit/8a94cec938f5337eef58e333ad3945cff6e5df5f#diff-bf6e7c08974eb5a11d1c1e00d19b7a0143e7be31e596a01a301739a2ba184fc8L69
=> [cluster-autoscaler] Backporting #3545 to release 1.19

cluster-autoscaler/cloudprovider/azure/azure_client.go
https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md#v4700 seems to have switched that API to preview for whatever reason.
=> update storage API version

cluster-autoscaler/FAQ.md
Resolves #4065. **Sincere** thanks for trying to resolve it with #4067, but I do not think it helped, so instead of explaining it again, I created a PR.
I took the wording from https://github.com/kubernetes/autoscaler/issues/3953#issuecomment-804426721
I hope this will help with issues like #3953 as I was expecting the CA to magically register nodes as well.
=> Document that CA is not responsible for registering new nodes

cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/mig_target_sizes_provider.go
FetchAllMigs (unfiltered InstanceGroupManagers.List) is costly as it's not
bounded to MIGs attached to the current cluster, but rather lists all MIGs
in the project/zone, and therefore equally affects all clusters in that
project/zone. Running the calls concurrently over the region's zones (so at
most, 4 concurrent API calls, about once per minute) contains that impact.
findMigsInRegion might be scoped to the current cluster (name pattern),
but also benefits from the same improvement, as it's also costly and
called at each refreshInterval (1mn).
Also: we're calling out GCE mig.Get() API again for each MIG (at ~300ms per
API call, in my tests), sequentially and with the global cache lock held
(when updateClusterState -> ...-> GetMigForInstance kicks in). Yet we
already get that bit of …
=>  gce: concurrent zonal List()s + opportunistic basename fill

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/utils/scheduler/scheduler.go
Since a couple of months, both upscale's `getUpcomingNodeInfos` and the
binpacking estimator uses the same shared `DeepCopyTemplateNode` function
and inherits its naming pattern, which is great and fixes a long standing bug.
`getUpcomingNodeInfos` will now enrich the cluster snapshots with
generated nodeinfos and nodes having predictable names (using the nodegroup's
template name, and an incremental ordinal starting at 0) for upcoming nodes.
Later, when it looks for fitting nodes for unschedulable pods, the binpacking
estimator will also build virtual nodes and place them in a snapshot fork to
evaluate scheduler predicates.
Those temporary virtual nodes are built using the same pattern (template name
and an index ordinal also starting at 0) as the one previously used by …
=> Fix templated nodeinfo names collisions in BinpackingNodeEstimator

cluster-autoscaler/hack/update-vendor.sh
Use shell syntax instead of pipe so error messages are printed out. Before
this change, if it could not download a module, it would just exit without
printing an error message due to the pipe. With this change it now prints
out the error message(unable to download) from the underlying process.
=> Print out error when unable to download module

cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/simulator/cluster_test.go
A few of the unit test structures did not have field name keys when
using literal structs. This change adds the fields to make this code a
little more future-proof.
=> add field keys to cluster autoscaler unit test structs

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/metrics/metrics.go
This function can take an variable amount of time due to various
conditions (ie. many nodegroups changes causing forced refreshes,
caches time to live expiries, ...).
Monitoring that duration is useful to diagnose those variations,
and to uncover external issues (ie. throttling from cloud provider)
affecting cluster-autoscaler.
=> Metric for CloudProvider.Refresh() duration

addon-resizer/nanny/main/pod_nanny.go
In Addon-resizer 1.8.13 or earlier, pod_nanny has a problem that `--poll-period` flag does not change the poll period.
This is caused by a bug while parsing the flag: pollPeriod value from `flag.Int` is dereferenced too early (before `flag.Parse()`)
and it always be assigned the default value.
This commit resolves this issue by getting the pollPeriod value after `flag.Parse()`.
```
$ ./pod_nanny --poll-period 300000 --cpu ...
```
pod_nanny should crawl Pod state every 300 seconds but it now does every 10 seconds.
=> addon-resizer: Fix --poll-period is not working in 1.8.13

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go
This adds an annotation to the "fakeNode" used by CA for unregistered node. This can be useful for cloudproviders in the `DeleteNode()` method to have some custom error handling logic and also identify the reason for the `fakeNode`. (For now, it seems only GCE would make use of the nodes created with error path)
An example of how we want to leverage that: we don't want to decrement the cached NodeGroup capacity in Azure because the capacity reported by APIs won't include Failed instances so the cache will end up drifting unnecessarily from the real capacity and can inadvertently lead to a scale down if some conditions align. 
I've noticed the packet provider tries to identify some via providerId but I don't think this is a reliable way. Similar with the magnum provider via the object UID. …
=> annotate fakeNodes so that cloudprovider implementations can identify them

vertical-pod-autoscaler/e2e/utils/webhook.go
Changing API version to V1. admissionregistration.k8s.io/v1beta1 is not supported since K8S 1.22.
/fixes #4121
=> Changing injection test webhook API from V1Beta1 to V1

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This is because for unregistered failed nodes, the capacity field on the VMSS already excludes and so this avoids a scenario where the cached capacity drifts significantly from the VMSS one (if cache TTL is long) and inadvertently lead to a scale down on the next scale up operation.
=> dont proactively decrement azure cache for unregistered nodes

addon-resizer/deploy/example.yaml
This fixes the comment at the beginning of the addon-resizer deployment example
so that it describes the correct key names to use for configuring the cpu
and memory parameters.
=> improve addon-resizer deployment example

cluster-autoscaler/cloudprovider/digitalocean/digitalocean_cloud_provider.go, cluster-autoscaler/cloudprovider/digitalocean/digitalocean_cloud_provider_test.go
If the API is temporarily unavailable, cluster-autoscaler will be crash-looping on startup during the initial call to `Refresh()`. This makes for a bad user/operator experience since it aggravates differentiating between API and cluster/workload problems.
Let autoscaler start up and retry fetching node pool information from the API as part of the pre-existing, periodic sync. This should be no different to experiencing transient API problems during runtime.
=> digitalocean: do not Refresh() on startup

cluster-autoscaler/cloudprovider/digitalocean/README.md
An initial version of the DigitalOcean cloud provider implementation relied on tags to define the behavior but has since been transitioned to using the public DOKS API. Update the README accordingly.
=> digitalocean: remove tag references from README

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
In case of stockout or quota issue CA will watch for nodes with create errors and [delete them](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler.go#L638). After deletion it will continue the loop normally. However, it will not trigger any sort of clusterstate recalculation and the deleted nodes will still be [counted as upcoming](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler.go#L789) and the rest of CA logic will continue expecting them to come up. 
Similar logic that handles nodes that timed out will [break CA loop](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler.go#L338) instead. This seems like a more correct behaviour.
=> Skip iteration loop if node creation failed

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
We have recevied an issue from one of our customers that their
autoscaler pod regularly crashes due to a nil pointer dereference panic.
Analyzing the code we found out that the autoscaler polls the server
status to find out if a server is running.
The Hetzner Cloud Go client is implemented in such a way that it does
not return an error if a resource could not be found. Instead it returns
nil for the error and the resource. Ususally this is not an issue.
However, in case the server creation fails the server gets deleted from
Hetzner Cloud. This in turn leads to nil being returned and the
abovementioned panic.
The Hetzner Cloud API implements a concept called Actions. Whenever a
long running process is triggered we return an object which can
be used to get information about the progress of …
=> Watch Action instead of polling Server Status

cluster-autoscaler/cloudprovider/hetzner/README.md, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
This comes in handy when using tools such as Packer to generate customized images.
I have a working docker image built off this feature and I've not run into issues thus far. The image below is linked from my `autoscaler` fork.
```bash
docker pull ghcr.io/marvinpinto/autoscaler:ba42c328
```
=> Add the ability to spin up Hetzner servers from custom snapshots

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/utils/daemonset/daemonset.go, cluster-autoscaler/utils/daemonset/daemonset_test.go
Changes to documentation will be done in a follow-up PR.
=> Allow DaemonSet pods to opt in/out from eviction

cluster-autoscaler/FAQ.md, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/metrics/metrics_test.go
This change publishes the node groups min and max count set on the cluster autoscaler. The current use case that these metrics are needed for is to create alerts when the number of nodes in the cluster reach a certain percentage of the max allowed nodes for example.
=> [cluster-autoscaler] Publish node group min/max metrics

addon-resizer/nanny/kubernetes_client.go, addon-resizer/nanny/kubernetes_client_test.go
Addon Resizer will use available metric for node count
Kubernetes 1.21 and newer have `apiserver_storage_objects` (1.20 and older don't have the metric).
Kubernetes 1.21 and older have `etcd_object_counts` (1.22 and newer won't have the metric).
To let addon resizer work with all K8s versions use whichever metric is available, if both are available then prefer the newer metric.
See also https://github.com/kubernetes/autoscaler/issues/3979
Fix a small bug where we were checking if unsigned int is less than 0.
=> Fix addon resizer node metric

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/clusterrole.yaml
Fixes #4114 
Added RBAC permissions to watch, list and get `csidrivers` and `csistoragecapacities`
=> fix: add missing RBAC permissions to autoscaler chart

cluster-autoscaler/metrics/metrics_test.go
Each test works in isolation, but they cause panic when the entire
suite is run (ex. make test-in-docker), because the underlying
metrics library panics when the same metric is registered twice.
=> Skipping metrics tests added in #4022

README.md
Relatively self-explanatory, though more than happy to adjust the badges we display to the most relevant ones!
Part of #4194.
=> docs: replaces Travis CI badge with GitHub Actions badges

cluster-autoscaler/FAQ.md
Signed-off-by: Ritikaa96 <ritika@india.nec.com>
There are incorrect link addresses in the FAQ for cluster-autoscaler FAQ.md : https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md
* Correcting minAvailable address from https://kubernetes.io/docs/api-reference/v1.7/#poddisruptionbudgetspec-v1beta1-policy to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#poddisruptionbudget-v1-policy
* Correcting Cloud-controller-manager link address from https://kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/ to https://v1-19.docs.kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/
/kind bug
=> Cluster-autoscaler-FAQ: Updating link addresses for MinAvailable and Cloud-controller-manager

cluster-autoscaler/cloudprovider/clusterapi/OWNERS
This change is adding github users arunmk, mrajashree, jackfrancis, and shysank
to the reviews for the cluster-api provider. It also removes frobware
from the approvers and reviewers.
=> update cluster-autoscaler CAPI provider owners

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml
This change updates the AWS examples to have 600Mi of memory because CAS downloads a pricing file that contains EC2 instance info at startup which grows each time there's new EC2 instance information available. Currently the largest region is hitting the 300Mi limit when downloading that file, so we are increasing the memory limit in our examples for customers.
=> [Examples] Update the AWS examples to have 600Mi of memory

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/aws_util.go
This fixes #3592.
We use the aws sdk to fetch the metadata. The endpoint explicitly set to `"http://169.254.169.254"` so that tests don't fail.
We tested it by applying these [changes](https://github.com/kubernetes/autoscaler/compare/cluster-autoscaler-1.18.3...shreyas-srinivas:imdsv2-1.18.3?expand=1) in 1.18.3 and it worked fine. tested both scale up and scale down.
This was tested in instances with IMDsV1 enabled and disabled.
=> Fix: CA does not work properly while using AWS EC2 IMDSv2

.github/workflows/ci.yaml, builder/Dockerfile
Updating the builder in Dockerfile to use go version 1.16, since vendoring to k8s v1.23.0-alpha.0 uses go1.16 packages which will fail otherwise.
GO111MODULE has to turned to `auto` due to the default being changed to `on` in go1.16:
https://golang.org/doc/go1.16#go-command
https://blog.golang.org/go116-module-changes
=> Update go version to 1.16 in Dockerfile and Github Tests

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/NOTES.txt, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
Enable `extraArgs` to contain multi-string arguments via an ignored `_x` suffix.
Fixes #3673.
=> [chart] Add multi string arg support

index.yaml
* Release of Cluster Autoscaler chart's 9.10.0, 9.10.1, 9.10.2 and 9.10.3 releases:
* #4175 - Update default CA image tag to v1.21.0
* #4154 - Additional RBAC permissions
* #4183 - Bump chart to valid SemVer
* #4226 - Add multi-string arg support
=> CA-Chart - 9.10.0, 9.10.1, 9.10.2 and 9.10.3 Releases

index.yaml
Follow-up to #4180 - correct the link for the 9.10.3 release.
=> Correct link for CA 9.10.3 release

cluster-autoscaler/cloudprovider/alicloud/alicloud_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go, cluster-autoscaler/core/utils/utils.go
This fixes issues when an ASG has 0 nodes yet and node labels are built
using buildGenericLabels and the node-template labels.
Issues include (anti-)affinity and nodeSelectors for the given labels,
giving false-negative results for candidate nodes, which leads to ASGs
never scaling up.
=> Also set new (non-beta/non-deprecated) labels in buildGenericLabels

cluster-autoscaler/cloudprovider/alicloud/alicloud_manager_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
Recent changes configured providers to set stable nodes labels names
exclusively (ie. LabelTopologyZone and not LabelZoneFailureDomain, etc),
with older labels names backfilled at nodeInfos templates generation time
(from GetNodeInfoFromTemplate), which isn't invoked from most tests cases.
GCE NodePirce() might have been dereferencing potentially missing labels.
And run hack/update-gofmt.sh where hack/verify-all.sh fails, to pass CI.
=> cluster-autoscaler: fix unit tests

cluster-autoscaler/cloudprovider/aws/README.md
/area provider/aws
Maybe helps https://github.com/kubernetes/autoscaler/issues/2434 - TBD in the issue
=> Add example to AWS readme if taint has value

cluster-autoscaler/cloudprovider/aws/auto_scaling.go, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_metrics.go, cluster-autoscaler/cloudprovider/aws/ec2.go
Provide metrics for AWS API calls; helps identifying slowness, throttling causes, and errors bursts.
That's similar to what [GCE provider does](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/gce/gce_metrics.go).
=> Metrics for AWS API calls

cluster-autoscaler/hack/update-vendor.sh
Since Cluster Autoscaler versioning should be in sync with Kubernetes,
update-vendor.sh can simply set the version after a successful
dependency update.
When CA 1.21 was released, the version was bumped only on the release branch, but not on the master branch. This should help with keeping them in sync.
@bpineau FYI
=> Update Cluster Autoscaler version with vendor

cluster-autoscaler/version/version.go
Note: This should automatically get synced in the future.
=> Make CA version on HEAD match k8s version in go.mod

vertical-pod-autoscaler/deploy/updater-deployment.yaml
Hello! I noticed that although we set the default value of `namespace` using the environment variable `NAMESPACE` [here](https://github.com/kubernetes/autoscaler/blob/vpa-release-0.9/vertical-pod-autoscaler/pkg/updater/main.go#L64), the current updater deployment configuration does not set the environment variable. This change will allow us to deploy the VPA components outside of the `kube-system` namespace without any issues. 
The changes I have made are taken from the admission controller deployment configuration [here](https://github.com/kubernetes/autoscaler/blob/vpa-release-0.9/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml#L25-L29). It is important that these two components are deployed in the same namespace.
This PR should also resolve #3736.
=> Add NAMESPACE as an environment variable to the updater deployment config

cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go
While this was previously effectively limited to 50, `DescribeAutoScalingGroups` now supports
fetching 100 ASG per calls on all regions, matching what's documented:
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeAutoScalingGroups.html
```
AutoScalingGroupNames.member.N
The names of the Auto Scaling groups.
By default, you can only specify up to 50 names.
You can optionally increase this limit using the MaxRecords parameter.
MaxRecords
The maximum number of items to return with this call.
The default value is 50 and the maximum value is 100.
```
Doubling this halves API calls on large clusters, which should help to prevent throttling.
Example effect on a real cluster (DescribeAutoScalingGroups calls in light blue):
The initial 50 value was set over two years ago due …
=> aws: Set maxAsgNamesPerDescribe to the new maximum value

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml
csidrivers.storage.k8s.io and csistoragecpacities.storage.k8s.io are available on EKS
1.21. Adding permissions to the ClusterRole in the example to avoid the error
messages.
Have been observing the following errors in my EKS pod logs and these additions clean it up:
E0808 15:34:14.726965       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: csistoragecapacities.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "csistoragecapacities" in API group "storage.k8s.io" at the cluster scope
E0808 15:34:16.225887       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list …
=> Fix: Adding additional storage APIs discovered but unable to be watched on EKS

cluster-autoscaler/cloudprovider/aws/aws_util.go, cluster-autoscaler/cloudprovider/aws/aws_util_test.go
The pricing json for us-east-1 is currently 129MB. Currently fetching
this into memory and parsing results in a large memory footprint on
startup, and can lead to the autoscaler being OOMKilled.
Change the ReadAll/Unmarshal logic to a stream decoder to significantly
reduce the memory use.
Should hopefully address #3506
=> Optimise generate ec2

cluster-autoscaler/cloudprovider/magnum/README.md, cluster-autoscaler/cloudprovider/magnum/magnum_manager.go
Fixes #4254 
When I enabled scale to 0 for the magnum provider, I was looking at this patch which allows node groups of size 0 with a new microversion, but did not require the microversion for making resize requests.
https://opendev.org/openstack/magnum/commit/f46923cc5ea74da663640bb0c470a4b1039c777e
The microversion requirement for resizing to 0 was added separately, later on.
https://opendev.org/openstack/magnum/commit/0e6d178939647e61fee1485e7b3611f093adb7c6
This patch makes the magnum client send "latest" as its microversion request, and on the server side magnum will replace it with the highest microversion that it supports.
When microversion 1.10 (or higher) is available, it will be used which allows the autoscaler to scale node groups to 0.
On magnum versions older than Wallaby, …
=> Use highest available magnum microversion

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/deletetaint/delete_test.go
cherry pick #3649 (Adding functionality to cordon the node before destroying it) to 1.20
=> cherry pick #3649 - Adding functionality to cordon the node before destroying it. 

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/deletetaint/delete.go, cluster-autoscaler/utils/deletetaint/delete_test.go
cherry pick #3649 (Adding functionality to cordon the node before destroying it) to 1.19
=> cherry pick #3649 - Adding functionality to cordon the node before destroying it.

cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_util.go, cluster-autoscaler/cloudprovider/aws/aws_util_test.go
AWS related cherry-picks of #3999 and #4199 to CA's 1.22 release branch as per #4251
=> Automated cherry pick of #3999 #4199 upstream cluster autoscaler release 1.22

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_util.go, cluster-autoscaler/cloudprovider/aws/aws_util_test.go
AWS related cherry-picks of #3999, #4127 and #4199 to CA's 1.19 release branch as per #4251
=> Automated cherry pick of #3999 #4127 #4199 upstream cluster autoscaler release 1.19

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_util.go, cluster-autoscaler/cloudprovider/aws/aws_util_test.go
AWS related cherry-picks of #3999, #4127 and #4199 to CA's 1.20 release branch as per #4251
=> Automated cherry pick of #3999 #4127 #4199 upstream cluster autoscaler release 1.20

cluster-autoscaler/cloudprovider/aws/auto_scaling_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_util.go, cluster-autoscaler/cloudprovider/aws/aws_util_test.go
AWS related cherry-picks of #3999, #4127 and #4199 to CA's 1.21 release branch as per #4251
=> Automated cherry pick of #3999 #4127 #4199 upstream cluster autoscaler release 1.21

cluster-autoscaler/FAQ.md
`<min>:<max>` not showing correctly
See fix below
=> Fix markdown code not showing correctly

cluster-autoscaler/cloudprovider/packet/README.md, cluster-autoscaler/cloudprovider/packet/packet_cloud_provider.go, cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go
This PR address certain issues found when deploying Cluster Autoscaler on Equinix Metal, formerly Packet.
1. fix panic on entry in nil map
In the latest version of cluster-autoscaler (cloudprovider: packet), the
code panics and the pods go into CrashLoopBackoff due to an entry
assignment on a nil map.
2. Consider the string prefix `equinixmetal://`
When K8s API is queried to get providerID from Node Spec, some machines
return `packet://<uuid>`, whereas some return `equinixmetal://`, this
creates error as the string is not trimmed properly and hence results in
a  404 when an untrimmed string is queried to Equinix Metal API for
device information.
3. Make controller node label configurable
Currently the label to identify controller/master node is hard coded to …
=> Cloud provider[Packet] fixes

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go, cluster-autoscaler/config/const.go
Support per-MIG (scaledown) settings as permited by the
cloudprovider's interface `GetOptions()` method.
=> implement GetOptions for GCE

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/clusterrole.yaml
Fixes problem when using v1.22.0 of autoscaler with the chart  as shown in https://github.com/kubernetes/autoscaler/issues/4256.
From logs we can see that it is requiring permission to list namespaces:
```
I0811 23:49:55.792818       1 request.go:597] Waited for 361.356292ms due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0
E0811 23:49:55.794467       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler-aws-cluster-autoscaler" cannot list resource "namespaces" in API group "" at the cluster scope
...
E0812 00:02:42.414760       1 plugin.go:138] …
```
=> fix 4256 autoscaler permit

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
Support per-VMSS (scaledown) settings as exposed by the cloudprovider's interface `GetOptions()` method.
For ref, providing similar GetOptions support for other providers:
* [GCE version](https://github.com/kubernetes/autoscaler/pull/4236)
* [AWS version](https://github.com/kubernetes/autoscaler/pull/4238/)
=> implement GetOptions for Azure

cluster-autoscaler/cloudprovider/magnum/README.md, cluster-autoscaler/cloudprovider/magnum/magnum_manager.go
Issue #4254
PR #4261
Fix the magnum API microversion used, to enable scaling node groups to size 0.
=> Cherry pick #4261 (magnum microversion) to cluster-autoscaler-release-1.22

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
We are using vertical-pod-autoscaler for autoscaler. We use **prometheus** as history data provider. 
Got  Error adding metric sample for container
There are two related issues found:
https://github.com/kubernetes/autoscaler/issues/2010
https://github.com/kubernetes/autoscaler/issues/2512
After checking, we found the ContainerState is not initialized before LoadPods of RunOnce method. 
Due to InitFromHistoryProvider is before RunOnce in main loop, the feeder.clusterState.AddSample will always got fail.  The history data will not be added to the ClusterState.
The solution is init container in InitFromHistoryProvider after init pod in ClusterState. Since the request of container is unknown, give a nil as param. The resource request will be updated to right value in the LoadPods in RunOnce …
=> add init container when vpa recommender init from history provider

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/role.yaml, charts/cluster-autoscaler/values.yaml
cluster-autoscaler has an argument:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca
| Parameter | Description | Default |
| --- | --- | --- |
| `leader-elect-resource-lock` | The type of resource object that is used for locking during leader election.<br>Supported options are `endpoints` (default) and `configmaps` | "endpoints"
This adds the chart support to have the appropriate permissions to get/update the configmap that's being used for leader tracking (by default `configmap/cluster-autoscaler`)
Fixes bug #4275
=> fix(leader-elect-resource-lock-role): Add permissions to role if leader election is based off configmaps

cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-aks.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml, cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-multiple-asgs.yaml, cluster-autoscaler/cloudprovider/baiducloud/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/bizflycloud/manifest/rbac.yaml, cluster-autoscaler/cloudprovider/cloudstack/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml, cluster-autoscaler/cloudprovider/exoscale/examples/cluster-autoscaler-run-on-control-plane.yaml, cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml, cluster-autoscaler/cloudprovider/huaweicloud/examples/cluster-autoscaler-svcaccount.yaml, cluster-autoscaler/cloudprovider/ionoscloud/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/linode/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-svcaccount.yaml, cluster-autoscaler/cloudprovider/packet/examples/cluster-autoscaler-svcaccount.yaml
As of the 1.22 release of k8s, the scheduler now requires the ability to list namespaces.
This PR is complementary to #4277 - adding the `namespaces` resource to the list of read only resources under the `""` group for each cloud provider example manifest.
See #4256
=> CA - Cloud Provider Examples - add ability to list/watch/get namespaces

cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml
Similar change was done in https://github.com/kubernetes/autoscaler/pull/4154
Without these RBAC permissions seeing below in the pod logs:
```
I0817 17:35:12.084244       1 reflector.go:255] Listing and watching *v1.CSIDriver from k8s.io/client-go/informers/factory.go:134
E0817 17:35:12.086678       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
I0817 17:35:12.684613       1 reflector.go:255] Listing and watching *v1beta1.CSIStorageCapacity from k8s.io/client-go/informers/factory.go:134
E0817 17:35:12.687383       1 …
```
=> fix: add missing RBAC permissions to example spec

cluster-autoscaler/cloudprovider/packet/README.md, cluster-autoscaler/cloudprovider/packet/packet_cloud_provider.go, cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go
As per this [comment](https://github.com/kubernetes/autoscaler/pull/4274#issuecomment-902146894)
Backporting the fix to upstream/cluster-autoscaler-release-1.20
=> Backport Merge pull request #4274 to upstream/cluster-autoscaler-release-1.20

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/utils/scheduler/scheduler.go
Original PR: #4089, merged after 1.21 was cut. This is a fix for a bug introduced in #3883, which was merged after 1.20 was cut. So the backport only needs to go to 1.21.
=> Cluster Autoscaler: Backport #4089 to 1.21

cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/utils/utils.go, cluster-autoscaler/core/utils/utils_test.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/processors/nodeinfosprovider/node_info_provider_processor.go, cluster-autoscaler/processors/processors.go
Supports providing different NodeInfos sources (either upstream or in
local forks, eg. to properly implement variants like in #4000).
The already existing NodeInfosProcessor doesn't cover that use case: it's
actually a "post processor", and processes the provided nodeInfos set.
This also moves a large and specialized code chunk out of core, and removes
the need to maintain and pass the GetNodeInfosForGroups() cache from the side,
as processors can hold their states themselves.
No functional changes to GetNodeInfosForGroups(), outside mechanical changes
due to the move: remotely call a few utils functions in core/utils package,
pick context attributes (the processor takes the context as arg rather than
ListerRegistry + PredicateChecker + CloudProvider), and use the builtin cache
rather …
=> Move GetNodeInfosForGroups to it's own processor

cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/processors/nodeinfosprovider/node_info_provider_processor.go
Every other processors (and, I think, function in CA?) that takes
AutoscalingContext has it as first parameter. Changing the new processor
for consistency.
=> Change parameter order of TemplateNodeInfoProvider

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer_test.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state_test.go, vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
It looks like it belongs inside the class, not with code using it.
=> Rate limit garbage collection inside `ClusterState`

cluster-autoscaler/cloudprovider/aws/aws_manager.go
Cherry picks https://github.com/kubernetes/autoscaler/commit/535a21263e77d92778043cd39d1c4f2845748424 so that we have an appropriate log level
Used commands:
```
git clone nitrag/autoscaler
git checkout -b backport-535a212-1.20 upstream/cluster-autoscaler-release-1.20
git cherry-pick 535a21263e77d92778043cd39d1c4f2845748424 
git push --set-upstream origin backport-535a212-1.20
```
=> Cherry pick 535a212 onto 1.20 - Fix logging level

cluster-autoscaler/cloudprovider/aws/aws_manager.go
cherry picks https://github.com/kubernetes/autoscaler/commit/535a21263e77d92778043cd39d1c4f2845748424 so that we have an appropriate logging level
=> Cherry pick 535a212 onto 1.21 - Fix logging level

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
I didn't update one call to `model.NewClusterState` in #4308. Fix it.
I wonder why presubmit didn't complain on the PR which introduced the problem
=> Fix cluster feeder test

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml
Hello, some improvements on AWS examples.
To ensure the pod is scheduled
```
priorityClassName: system-cluster-critical
```
To run pod as non-root (security best practice)
```
securityContext:
runAsNonRoot: true
runAsUser: 65534
```
And use the last image (1.22.0).
=> [CA] [AWS examples] Add priorityClassName & securityContext & upgrade image

cluster-autoscaler/FAQ.md, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/expander/expander.go, cluster-autoscaler/expander/factory/chain.go, cluster-autoscaler/expander/factory/chain_test.go, cluster-autoscaler/expander/factory/expander_factory.go, cluster-autoscaler/expander/mostpods/mostpods.go, cluster-autoscaler/expander/price/price.go, cluster-autoscaler/expander/price/price_test.go, cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go, cluster-autoscaler/expander/random/random.go, cluster-autoscaler/expander/waste/waste.go, cluster-autoscaler/expander/waste/waste_test.go, cluster-autoscaler/main.go
Multiple expanders can now be specified, expanders now "filter to the
tied for best" instead of "selecting the best" so the output of one
expander is now fed to the input of the next. Each expander may only
be used once to disallow bad configuration. This should not be a change
in functionality as in the event of a tie the random expander is still
used.
=> Allow specification of multiple expanders

addon-resizer/Makefile
Creates and pushes a docker manifest list when using `make all-push` that includes all architectures. This will make it so users can always use the non-architecture-specific version of the image and get the correct version for their architecture.
=> Create and push multi-architecture manifest

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
Cherry-pick #4130 -  don't proactively decrement azure cache for unregistered nodes
=> Cherry-pick #4130: dont proactively decrement azure cache for unregistered nodes

cluster-autoscaler/expander/mostpods/mostpods_test.go, cluster-autoscaler/expander/price/price_test.go, cluster-autoscaler/expander/priority/priority_test.go, cluster-autoscaler/expander/waste/waste_test.go
The github action hooks didn't run the unit tests on the expanders
update in #4233 (likely the known "tests don't run automatically for
new contributor" limitation).
NewStrategy became NewFilter, with a BestOptions (plural) method,
and returns an Option slice instead of a single Option.
=> fix expanders unit tests

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/utils/utils.go, cluster-autoscaler/utils/kubernetes/ready_test.go, cluster-autoscaler/utils/test/test_utils.go
Cherry pick of #3924 on cluster-autoscaler-release-1.20.
#3924: Fix bug where a node that becomes ready after 2 mins can be 
=> Automated cherry pick of #3924: Fix bug where a node that becomes ready after 2 mins can be

cluster-autoscaler/clusterstate/clusterstate_test.go
The backport included unit tests using a function that changed signature
after 1.20. This was not detected before merging because CI is not
running correctly on 1.20.
=> Cluster Autoscaler: fix unit tests after #3924 was backported to 1.20 in #4319

cluster-autoscaler/cloudprovider/aws/aws_manager.go
Cherry picks https://github.com/kubernetes/autoscaler/commit/535a21263e77d92778043cd39d1c4f2845748424 so that we have an appropriate logging level
=> Cherry pick 535a212 onto 1.22 - Fix logging level

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go
=> Fix 1.19 after cherry-picking Azure change

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go
=> Cherry-pick #4130 onto 1.21: dont proactively decrement azure cache for unregistered nodes 

cluster-autoscaler/.gitignore, cluster-autoscaler/Makefile
Make arch-specific releases use separate images instead of tags on the same image
=> Cluster Autoscaler: backport #3768 to 1.20

cluster-autoscaler/.gitignore, cluster-autoscaler/Makefile
Make arch-specific releases use separate images instead of tags on the same image
=> Cluster Autoscaler: backport #3768 to 1.19

vertical-pod-autoscaler/enhancements/3919-customized-recommender-vpa/README.md
Use a list of structs instead of a list of strings to choose
recommenders.
This will allow us to pass parameters to recommenders (if we decide we
want to allow that).
Related to #3913
=> Adjust KEP for customized recommender

cluster-autoscaler/cloudprovider/aws/README.md
=> [AWS EKS - Scale-to-0] Update README to include warning about eks:nodegroup-name tag

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/processors/status/scale_up_status_processor.go
Add information about Node Groups that failed creation and/or resize to ScaleUpStatus structure.
=> Extend ScaleUpStatus with node groups that failed scale up.

cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/processors/actionablecluster/actionable_cluster_processor.go, cluster-autoscaler/processors/callbacks/processor_callbacks.go, cluster-autoscaler/processors/callbacks/test_utils.go, cluster-autoscaler/processors/processors.go
This refactors the handling of cases when the cluster is empty/not ready by CA into a processors in empty_cluster_processor.go
=> Introduce Empty Cluster Processor

cluster-autoscaler/cloudprovider/gce/reserved.go, cluster-autoscaler/cloudprovider/gce/reserved_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
If EPH_STORAGE_LOCAL_SSD_COUNT=N is specified in kube-env (in AUTOSCALER_ENV_VARS), physical ephemeral storage is N*375GiB instead of the boot disk size, and only the variable part of OS reserved (filesystem overhead vs. fixed OS partition) is subtracted to compute capacity.
The existing BLOCK_EPH_STORAGE_BOOT_DISK is ignored if EPH_STORAGE_LOCAL_SSD_COUNT>0.
fixes #4281 and #1869
=> GCE ephemeral storage on local SSDs

addon-resizer/deploy/example.yaml
* Follow least privilege principle: nanny does not need to be able to patch all deployments, only its own. Remove superfluous permissions
* Add comment about alternative RBAC for `--use-metrics=true`
* Update image repository and tag
=> addon-resizer: Restrict example RBAC to minimum

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
Because version 1.21.1 has been [released](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.21.1) it would be nice to update helm chart
=> Upgrade image tag version for helm chart

vertical-pod-autoscaler/pkg/admission-controller/certs.go, vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/logic/server.go, vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go, vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_cache_storage.go, vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go, vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go, vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/model/container.go, vertical-pod-autoscaler/pkg/recommender/model/types.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/target/fetcher.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/priority/priority_processor.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go, vertical-pod-autoscaler/pkg/utils/metrics/metrics.go, vertical-pod-autoscaler/pkg/utils/metrics/quality/quality.go, vertical-pod-autoscaler/pkg/utils/status/status_updater.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go
Issue: #4340
Part 1: update go.mod file (https://github.com/kubernetes/autoscaler/pull/4361, merged)
This PR is updating those files that are using klog v1 to v2.
=> Issue#4340-Migrate vertical-pod-autoscaler to k8s.io/klog/v2 --Part2

cluster-autoscaler/FAQ.md
Packet also supports price expander
See https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/packet#autoscaler-deployment  and https://github.com/kubernetes/autoscaler/blob/1c8efe4640040d1ee0fbc6460d56f13562a44f67/cluster-autoscaler/cloudprovider/packet/packet_price_model.go#L58
=> Mention Packet for supporting price expander

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
This change updates the logic for the clusterapi autoscaler provider so
that the `CAPI_GROUP` environment variable will also affect the
annotations keys for minimum and maximum node group size, the machine
annotation, machine deletion, and the cluster name label. It also addes
unit tests and an update to the readme.
=> expand CAPI_GROUP usage to cover other capi group variables

cluster-autoscaler/main.go, cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go, cluster-autoscaler/processors/nodegroupset/aws_nodegroups_test.go, cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups.go, cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups_test.go
This change adds 2 commits that will allow the AWS and ClusterAPI providers to ignore the `topology.ebs.csi.aws.com/zone` label. This label is used by the AWS EBS CSI driver, and will cause the `--balance-similar-node-groups` flag to fail on these platforms when comparing node groups that are in different availability zones. It adds the label to the existing AWS nodegroupset processor and creates a new processor for ClusterAPI. Also adds unit tests to exercise the processors.
fixes: #3230
=> Allow AWS and ClusterAPI providers to ignore topology.ebs.csi.aws.com/zone label

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
Resolves a gofmt error introduced by merging of #4463 currently blocking other PRs (see e.g. #4411 )
(Side note, I've now loosened the restrictions on auto running the GH actions to hopefully prevent this from happening in the future.)
=> CA - Update gofmt of CAPI_nodegroup.go

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Support per-ASG (scaledown) settings as specified by the cloudprovider's interface GetOptions() method.
For ref, merged PRs providing similar GetOptions support for other providers:
* [GCE version](https://github.com/kubernetes/autoscaler/pull/4236)
* [Azure version](https://github.com/kubernetes/autoscaler/pull/4237)
=> implement GetOptions for AWS

vertical-pod-autoscaler/e2e/v1/full_vpa.go, vertical-pod-autoscaler/e2e/v1beta2/full_vpa.go
Tests are flaky with VPA sometimes generating recommendations higher
than 1000 mCPU.
I think this is a reasonable behavior - we're asking resoirce consumer
to use 1800 mCPU between 3 pods, if it gets unevenly distributed we can
end up with some pods using 1000 mCPU.
=> Increase upper bound for expected VPA CPU recommendations

addon-resizer/Makefile
currently, we can build image with the same arch as the host node, for cross-arch building, we need `docker buildx`
The following image is build by `ARCH=arm64 make container` on a amd64-based host and pushed into ACR, manifest inspect shows it still uses amd64 even though we build the image specifying `ARCH=arm64`
```
➜  addon-resizer git:(master) docker manifest inspect qingchuanhao.azurecr.io/addon-resizer-arm64:2.3 --verbose
{
"Ref": "qingchuanhao.azurecr.io/addon-resizer-arm64:2.3",
"Descriptor": {
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"digest": "sha256:52bd42707a470ad5fc8e3b07e35e82654d3005966c3bf97a1f39fea654be23dc",
"size": 738,
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
"SchemaV2Manifest": {
"schemaVersion": 2,
"mediaType": …
```
=> use docker buildx to buld multi-arch image

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go, vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go, vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go, vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling_test.go
See the [comment](https://github.com/kubernetes/autoscaler/issues/3965#issuecomment-851024267) I made for issue #3965
When the ratio between the original memory requests/limits on the Deployment is a floating point number instead of an integer, the calculated limit is expressed in millivalues, (https://play.golang.org/p/dR4SaXRBGmB) which is valid for CPU values, but not necessarily for memory values.
The purpose of this PR is to ensure it is expressed as bytes.
=> Separate limits scaling between CPU & memory

cluster-autoscaler/cloudprovider/clusterapi/README.md
This change adds ascii diagrams to help illustrate the differences
between the various authentication configurations for the clusterapi
provider. Due to the distributed nature of Cluster API and its ability
to have several Kubernetes clusters managed from a central location, the
kubeconfig authentication options for it are slightly more complex than
other providers.
=> add configuration diagrams to clusterapi readme

cluster-autoscaler/cloudprovider/gce/templates.go
Changed the logging level for `extractAutoscalerVarFromKubeEnv` not found in gce cloud provider
=> Changed the logging level in gce cloud provider

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
Adds a100 to the list of azure available gpu types
=> add a100 gpu type

vertical-pod-autoscaler/go.mod, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/updater/main.go, vertical-pod-autoscaler/vendor/modules.txt
Issue: https://github.com/kubernetes/autoscaler/issues/4340
This PR is to update klog version to v2 for the following files:
```
./pkg/updater/main.go:	"k8s.io/klog"
./pkg/recommender/model/cluster_test.go:	"k8s.io/klog"
./pkg/recommender/main.go:	"k8s.io/klog"
```
The only part left is files in e2e, however, it will make the PR big, we need to break them into smaller scope.
=> Issue#4340 -- Update klog version to v2 --part3

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_util.go, cluster-autoscaler/cloudprovider/aws/aws_util_test.go, cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
This change addresses #4436 by replacing the existing pricing API call used to resolve instance types with EC2's DescribeInstanceTypes API. It also adds unit tests and updates the readme.
=> Use DescribeInstanceTypes API to get EC2 instance type details

cluster-autoscaler/main.go
https://github.com/kubernetes/autoscaler/pull/4233  introduced the possibility to add multiple expanders but removed the default definition so now it must be explicitly defined otherwise a user gets the not user-friendly error:
```
F1209 16:45:32.229497       1 main.go:350] Failed to create autoscaler: Expander  not supported
```
This PR reintroduces a default expander, with value "random" as it was before, so that the `--expander` flag does not need to be explicitly defined if a user does not care about it.
=> Re-add default expander

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/priority-expander-configmap.yaml
This should fix an error with Helm when passing expanderPriorities:
```
Error: template: cluster-autoscaler/templates/priority-expander-configmap.yaml:11:39: executing "cluster-autoscaler/templates/priority-expander-configmap.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}
```
=> [HELM] Fix missing yaml conversion for expander priorities

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
Instead of retrieving it each time from k8s, which easily causes client-side
throttling, which in turn causes each autoscaler run to take multiple
seconds even if only a small number of NodeGroups is involved and nothing
is to do.
=> [clusterapi] Rely on replica count found in unstructuredScalableResource

vertical-pod-autoscaler/e2e/go.mod, vertical-pod-autoscaler/e2e/go.sum, vertical-pod-autoscaler/e2e/v1/e2e.go, vertical-pod-autoscaler/e2e/v1/recommender.go, vertical-pod-autoscaler/e2e/v1beta2/e2e.go, vertical-pod-autoscaler/e2e/v1beta2/recommender.go, vertical-pod-autoscaler/e2e/vendor/modules.txt
Issue: https://github.com/kubernetes/autoscaler/issues/4340
This is the last part needs to be updated in VPA:
```
./e2e/v1/e2e.go:	"k8s.io/klog"
./e2e/v1/recommender.go:	"k8s.io/klog"
./e2e/v1beta2/e2e.go:	"k8s.io/klog"
./e2e/v1beta2/recommender.go:	"k8s.io/klog"
```
=> Issue 4340 -- Update the klog version to v2 in e2e --last part

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/cache_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
Refreshing `GceCache` should be done by other components, similarly to how the basenames are refreshed by `MigInfoProvider` or how `Migs` are registered by `GceManager`. This provides additional level of isolation in the code, cleans up dependencies and simplifies reasoning.
Currently instances to `Migs` cache is being refreshed by `GceCache` itself. This introduces unnecessary dependancy on the `GceClient`. This change moves that refreshing logic to `MigInfoProvider`, simplifying the resulting dependency network.
The changes are aimed to maintain the same functionality as the current one. The only significant difference is checking all the Migs in `RefillAllMigInstances` and `fillCandidateMigInstances` functions in `MigInfoProvider`. Thanks to that the CA should be able to handle fetches …
=> Refresh instances to mig cache in MigInfoProvider

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
Based on https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#response, the `AdmissionReview` response stanza must contain, at a minimum, the following fields:
- `uid`, copied from the `request.uid` sent to the webhook
- `allowed`, either set to true or false
This PR populates UID field into the response returned by the VPA admission controller.
By setting `register-webhook=false` and using a  `MutatingWebhookConfiguration` like
```
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
name: vpa-webhook-config
webhooks:
- name: vpa.k8s.io
rules:
- apiGroups:
- ""
apiVersions:
- v1
resources:
- pods
operations:
- CREATE
scope: '*'
- apiGroups:
- autoscaling.k8s.io
apiVersions:
- '*'
operations:
- CREATE
- UPDATE …
```
=> Send UID too in AdmissionReview response

cluster-autoscaler/FAQ.md, cluster-autoscaler/main.go
/kind bug
/sig autoscaling
/sig storage
This PRs adds a `--feature-gates` flag to the cluster-autoscaler. For more details on why this is needed see https://github.com/kubernetes/autoscaler/issues/4517.
Fixes https://github.com/kubernetes/autoscaler/issues/4517
This approach has the small drawback that it adds all [K8s feature gates](https://github.com/kubernetes/kubernetes/blob/v1.23.0/pkg/features/kube_features.go) as known ones (which makes the `--help` output verbose and misleading).
On the other side, with this approach we receive the list of known feature gates and their default values from the upstream (by vendoring clster-autoscaler) -> no need to manually maintain out custom list with upstream feature gates and their defaults. 
```release-note
The cluster-autoscaler now supports …
```
=> Add `--feature-gates` flag to support scale up on volume limits (CSI migration enabled)

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This adds logging around previous + refreshed VMSS size and lowers the verbosity for one other log.
It also removes some fields that are no longer used after #3717 move to global azure_manager cache
=> improve logging for scale set size changes

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
I've added caching of the Mig instances to the `GceCache` + utilised the existing logic from `MigInfoProvider` to update and refresh this cache. This way we pass all the Mig info-related data from `GceClient` to `GceManager` exclusively via `MigInfoProvider`. This gives us better control over the client and cache, while also improving the separation of these components.
Additionally we may utilise the Mig instance cache in the future. It is refreshed once per loop, so any new functionalities that would require fetching instances will now no longer increase the QPS.
It is worth noting that we do not guarantee that `instances` and `instanceToMig` caches are in sync. They are modified independently and at different times, so it is possible that they get out of sync for a couple loops. This …
=> Cache Mig instances in GceCache

cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go, cluster-autoscaler/cloudprovider/gce/mig_lister.go
`MigLister` is an interface handling issues with Migs and wrapping the `GetMigs` method of `GceCache`. It can be used to detect problematic Migs which could potentially break the CA behaviour if they were not filtered out from the `GceCloudProvider.NodeGroups()` call result.
=> Add MigLister interface with default no-op implementation

cluster-autoscaler/FAQ.md, cluster-autoscaler/main.go
Cherry pick of #4539 on cluster-autoscaler-release-1.21.
#4539: Add `--feature-gates` flag to support scale up on volume
=> [release-1.21] Automated cherry pick of #4539: Add `--feature-gates` flag to support scale up on volume

cluster-autoscaler/FAQ.md, cluster-autoscaler/main.go
Cherry pick of #4539 on cluster-autoscaler-release-1.22.
#4539: Add `--feature-gates` flag to support scale up on volume
=> [release-1.22] Automated cherry pick of #4539: Add `--feature-gates` flag to support scale up on volume

cluster-autoscaler/FAQ.md, cluster-autoscaler/main.go
Cherry pick of #4539 on cluster-autoscaler-release-1.20.
#4539: Add `--feature-gates` flag to support scale up on volume
=> [release-1.20] Automated cherry pick of #4539: Add `--feature-gates` flag to support scale up on volume

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
Sets the default priority class of the CA to `system-cluster-critical`. We should default to safe behaviour, and risking the CA being deployed by default without a priority class risks users having their CAs be evicted and not being able to be rescheduled, thus losing scaling in their clusters is not a safe default.
This matches the examples for a number of cloud providers already in this repo, e.g. [AWS](https://github.com/kubernetes/autoscaler/blob/9e63892f86a389b337dc77558df433921237254c/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml#L140) and [AliCloud](https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/cluster-autoscaler/cloudprovider/alicloud/README.md).
=> Charts - CA - Default to system-cluster-critical priority class

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
The Hetzner Cloud heeds more time to create instance from snapshot. 
Increase serverCreateTimeout to 5 minutes.
=> Increase server create timeout

vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
Introduce the notion of contributive Pods - such that the Pod is either active or as an existing associated controller.
Remove only AggregateCollectionStates which don't have any contributive Pod.
=> Change the behaviour of Garbage Collector of AggregateCollectionStates

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go
Admission controller responses are rejected with
```
failed calling webhook "vpa.k8s.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
```
Fix this by setting fields API server expects us to set.
Fixes #4557
=> Fix admission controller

cluster-autoscaler/core/scale_up.go
#3950 ended up double wrapping the scale-up errors
=> fix: avoid double wrapping scale up error

cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/processors/nodegroupset/azure_nodegroups.go
For balancing similar nodegroups, this label should be ignored when comparing nodegroups that may be in different zones.
This also adds the label to the set of zonal labels predicted by azure template for the scale from zero case.
=> ignore azure csi topology label for similarity checks and populate it for scale from zero

cluster-autoscaler/core/equivalence_groups.go, cluster-autoscaler/core/equivalence_groups_test.go, cluster-autoscaler/core/utils/pod_schedulable.go, cluster-autoscaler/core/utils/pod_schedulable_test.go, cluster-autoscaler/utils/test/test_utils.go, cluster-autoscaler/utils/utils.go, cluster-autoscaler/utils/utils_test.go
With the `BoundServiceAccountTokenVolume` feature being GA, the SA admission controller uses volume projection to add a new volume to the pod, rather than the old method with a secret based volume. This means that two replicas of the same pod will have a different PodSpec because the volume added by the plugin will have a different random-suffix.
```
E1103 21:20:54.328103 1 equivalence_groups.go:81] mismatch (-want +got):
v1.PodSpec{
Volumes: []v1.Volume{
{
-  Name: "kube-api-access-8n6v5",
+  Name: "kube-api-access-7pnsd",
},
},
InitContainers: nil,
Containers: []v1.Container{
{
... // 7 identical fields
Env: nil,
Resources: v1.ResourceRequirements{Limits: v1.ResourceList{s"cpu": {i: resource.int64Amount{value: 500, scale: -3}, s: "500m", Format: "DecimalSI"}}, Requests: …
```
=> fix pod equivalency checks for pods with projected volumes

cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/filter_out_schedulable.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/debuggingsnapshot/debugging_snapshot.go, cluster-autoscaler/debuggingsnapshot/debugging_snapshot_test.go, cluster-autoscaler/debuggingsnapshot/debugging_snapshotter.go, cluster-autoscaler/debuggingsnapshot/debugging_snapshotter_test.go, cluster-autoscaler/main.go
Cluster-Autoscaler
/kind feature
This PR introduces a new Debugging Tool, which would make it easier to analyse larger clusters.
Fixes #4346
NONE
```release-note
```
```docs
```
=> Adding support for Debugging Snapshot

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
This PR doesn't change or adds any functionality, it's a pure visual change.
Node names with the Hetzner Cloud Provider used to have a long name of random numbers. To shorten those names this PR aims to change the random number to a hex representation.
=> Shorten Hetzners node names with hex repr

vertical-pod-autoscaler/enhancements/4566-min-replicas/README.md
vertical-pod-autoscaler (VPA API)
/kind feature
To allow for API review before merging (or rejecting) #4560.
=> Enhancement proposal to add minReplicas per VPA Object (see #4560)

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_util_test.go
/kind bug
In CA version 1.21, on Azure, it was possible to omit the Subscription ID completely.
On startup, cluster autoscaler used to detect it using [Azure Instance Metadata Service (IMDS)](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=linux).
It used to do so using a service in `legacy-cloud-providers`.
The [initialization code](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.22/cluster-autoscaler/cloudprovider/azure/azure_config.go#L463) for such service is as follows:
```
metadataService, err := providerazure.NewInstanceMetadataService(metadataURL)
```
In 1.21 this worked just fine.
In 1.22 the meaning of the metadataURL parameter was changed in the service code.
What used to be a full URL …
=> Fix Azure IMDS Url in InstanceMetadataService initialization

addon-resizer/Makefile
addon-resizer
/feature
The docker images published for addon-resizer releases are not multi arch images (docker images that support multiple CPU architectures). Right now, we publish a separate image tag for each architecture. The image `us.gcr.io/k8s-artifacts-prod/addon-resizer:{verison}` is built using the `amd64` format, and in addition, there are image for for each supported CPU architecture using the format `addon-resizer-{arch}` for example `us.gcr.io/k8s-artifacts-prod/addon-resizer-amd64:2.3` and `us.gcr.io/k8s-artifacts-prod/addon-resizer-arm64:2.3`. The target CPU architectures are specified in the [addon-resizer Makefile](https://github.com/kubernetes/autoscaler/blob/addon-resizer-2.3/addon-resizer/Makefile#L20).
The manifest for the [1.8.14 release …
=> Create a multi-architecture manifest when pushing image to registry

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
Suppose the instance group update mode is not `Opportunistic`. In that case, the operation ends without error; the GCP console shows no increase in the number of nodes (but it shows the updating clock image) and tries to repeat the operation multiple times.
If the operation is `DONE` but contains an error, return it.
Note: I am aware this is not an error in the autoscaler but the only place to find the reason why the scale-up operation is not being done is in the console https://console.cloud.google.com/compute/operations (even there, the operation appears as OK)
=> Cluster Autoscaler: GCE: check the result of the operation

cluster-autoscaler/cloudprovider/clusterapi/OWNERS
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>
/kind cleanup
I'm stepping away form Cluster API, so need to remove myself from the owners file.
Fixes #
```release-note
NONE
```
```docs
```
=> Cluster API OWNERS: Remove randomvariable

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/core/scale_down_test.go, cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/processors/nodes/post_filtering_processor.go, cluster-autoscaler/processors/nodes/types.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go
This PR introduces a new processor (proposed name is: `ScaleDownSetProcessor`), that is used at ScaleDown operations to pick a final set of candidates (after sanity checks size, pods etc.).
This may be useful to implement a variety of features, for example, users can introduce a processor that has a specific priorities for which node group to scale down first.
In this PR I also simplified the `FindNodesToRemove` function to not include the `maxCount` and `fastCheck` parameters.
The latter one is no longer needed due to the Fast and Detailed functions being backed by the same checks.
Rather than return a limited number of candidates the function returns a slice with all possible (so that the processor can pick a best suited one).
The PR also includes a default implementation of the …
=> Introduce the scale down processor that picks the final scale down candidates

cluster-autoscaler/cloudprovider/azure/azure_util_test.go
It seems that test gets varying error messages which prompted
Bartłomiej previous fix, but I'm now seeing the original error
message string back ("Server failed to authenticate [...]"),
so that `TestDeleteBlob` test is failing again (other PRs' tests
failures suggest that's not just my laptop).
Let's assume this was meant to check for an error, until someone
can confirm, that might be better than potentially hidding other
PRs real tests failures.
Azure cloud provider.
/kind flake
Please let us know if that was really meant to catch specific error messages, and if so, which message.
=> azure: change a flacky test

.github/workflows/ci.yaml, builder/Dockerfile, cluster-autoscaler/FAQ.md, cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go, cluster-autoscaler/cloudprovider/azure/azure_instance_types/gen.go, cluster-autoscaler/cloudprovider/builder/builder_alicloud.go, cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_aws.go, cluster-autoscaler/cloudprovider/builder/builder_azure.go, cluster-autoscaler/cloudprovider/builder/builder_baiducloud.go, cluster-autoscaler/cloudprovider/builder/builder_bizflycloud.go, cluster-autoscaler/cloudprovider/builder/builder_brightbox.go, cluster-autoscaler/cloudprovider/builder/builder_cloudstack.go, cluster-autoscaler/cloudprovider/builder/builder_clusterapi.go, cluster-autoscaler/cloudprovider/builder/builder_digitalocean.go, cluster-autoscaler/cloudprovider/builder/builder_exoscale.go, cluster-autoscaler/cloudprovider/builder/builder_gce.go, cluster-autoscaler/cloudprovider/builder/builder_hetzner.go, cluster-autoscaler/cloudprovider/builder/builder_huaweicloud.go, cluster-autoscaler/cloudprovider/builder/builder_ionoscloud.go, cluster-autoscaler/cloudprovider/builder/builder_kubemark.go, cluster-autoscaler/cloudprovider/builder/builder_linode.go, cluster-autoscaler/cloudprovider/builder/builder_magnum.go, cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go, cluster-autoscaler/cloudprovider/builder/builder_packet.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_linux.go, cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go, hack/boilerplate/boilerplate.py, hack/verify-gofmt.sh
This is a partial cherry-pick of a #4567. 
Kubernetes has moved to go 1.17 and no longer compiles on go 1.16 (currently used by CA). This bumps CA to go1.17 and is a prerequisite to updating deps (which I'll do in a follow-up PR).
Some gotchas:
* Go version tag in go.mod is purposefully left at go1.16. This is needed, because go1.17 changes how go.mod work and the upstream kubernetes haven't transitioned to the new go.mod yet (they misrepresent go version in go.mod exactly the same way). https://github.com/kubernetes/kubernetes/pull/105563#issuecomment-960915506
* Added go:build tags matching existing +build tags for all cluster-autoscaler files across different providers. This should have no effect, but it is a part of golang migration to new syntax and both tags is expected by go fmt in …
=> Update Cluster Autoscaler to go 1.17

cluster-autoscaler/core/scale_down.go, cluster-autoscaler/processors/nodes/post_filtering_processor.go, cluster-autoscaler/processors/nodes/types.go
This is a followup PR to #4519 that extends the `ScaleDownSetProcessor` to include the `context.AutoscalingContext` parameter in the `GetNodesToRemove` function.
Edit: unlike the https://github.com/kubernetes/autoscaler/pull/4519#issuecomment-1012967211 suggested I propose we use the context that is already part of `ScaleDown`
=> Add AutoscalingContext to the scale-down post-processor

cluster-autoscaler/cloudprovider/gce/gce_reserved.go, cluster-autoscaler/cloudprovider/gce/gce_reserved_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
/kind cleanup
*_containerd os distributions weren't used and made a confusions with image types.
Gce cos_containerd and ubuntu_containerd os distributions are deprecated.
=> Introduce gce image types and remove *_containerd gce os distributions

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR allows the use of colon (`:`) in AWS ASG autodiscovery tag keys.
Our cluster ASGs are tagged like `<namespace>:cluster = <clustername>` and `<namespace>:nodegroup = <nodegroup>`. 
The existing code for tag-based autodiscovery would attempt to further split the tag, and this has been fixed to limit the amount of splitting that is done.
We have ensured the tests pass and updated the documentation to demonstrate that the ASG tag discovery code supports tag values as well.
```release-note
Added support for colon (`:`) in the AWS ASG discovery tag keys
```
=> Allow colon in AWS ASG autodiscovery tag keys

cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/processors/nodeinfosprovider/node_info_provider_processor.go
/kind bug
There's a race condition between DaemonSet pods getting scheduled to a
new node and Cluster Autoscaler caching that node for the sake of
predicting future nodes in a given node group. We can reduce the risk of
missing some DaemonSet by providing a grace period before accepting nodes in the
cache. 1 minute should be more than enough, except for some pathological
edge cases.
Fixes #
```release-note
NONE
```
```docs
```
=> Don't cache NodeInfo for recently Ready nodes

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
Enables AZURE_CLUSTER_NAME even if .Values.azureUseManagedIdentityExtension is "true".
Which autoscaling component hosted in this repository (cluster-autoscaler, vertical-pod-autoscaler, addon-resizer, 
helm charts
/kind bug
The Helm chart doesn't work in case azureUseManagedIdentiryExtension="true".
As suggested kubernetes/autoscaler#4323, the environment variable `AZURE_CLUSTER_NAME` seems to be required.
Fixes #4323
This PR is just stopping a CrashLoopBackoff.
It might be some more patches required for working cluster-autoscaler perfect.
```release-note
`azureClusterName` must be set if they set `azureUseManagedIdentityExtension="true"`.
```
none.
=> Enables AZURE_CLUSTER_NAME even if .Values.azureUseManagedIdentityExtension is "true".

vertical-pod-autoscaler/pkg/utils/metrics/admission/admission.go
I want more resolution in [0.2, 1]s range. [K8s Pod Creation Latency
SLO](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md) has a target of 5s so it makes a difference for the SLO how the
delay we introduce is distributed. Right now I think buckets are too
wide in the [0.1, 1]s range.
/kind feature
```release-note
NONE
```
=> Add more buckets to admission_latency_seconds metric

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
This PR applies to helm chart. It adds the possibility to use topologySpreadConstraints in the helm chart.
Tested one two EKS with k8s 1.21. 
/kind feature
topologySpreadConstraints is not supported yet by the helm chart, but we need it to spread pods over Zones.
Fixes #4577
```release-note
NONE
```
Added a line in README.MD and also an example in the values.yaml.
=> Add topology spread constraints to control how Pods are spread

vertical-pod-autoscaler/builder/Dockerfile, vertical-pod-autoscaler/go.mod, vertical-pod-autoscaler/go.sum
Created with
go mod edit -go=1.16
go mod tidy
vi builder/Dockerfile
/kind cleanup
```release-note
NONE
```
=> Update VPA to go1.16

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/values.yaml
Which component this PR applies to?
This PR applies to the helm chart. It modifies the example how to use the topologySpreadConstraints in the helm chart.
Noticed today that the terraform helm provider doesn't accept the code for topologySpreadConstraint if it start with "- labelSelector"
```yaml
topologySpreadConstraints:
- labelSelector:
matchLabels:
app.kubernetes.io/name: aws-cluster-autoscaler
maxSkew: 1
topologyKey: topology.kubernetes.io/zone
whenUnsatisfiable: DoNotSchedule
```
It end's with the following error. 
```sh
Error: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.topologySpreadConstraints[0]): unknown field "matchLabels" in io.k8s.api.core.v1.TopologySpreadConstraint
```
To prevent issues with that, I changed the example Code and …
=> Fix example in values file for topologySpreadConstraint

cluster-autoscaler/cloudprovider/exoscale/OWNERS
Cluster-autoscaler - Exoscale Cloud Provider
Adds an OWNERS file for the Exoscale cloud provider as per discussion here: https://github.com/kubernetes/autoscaler/pull/4247#issuecomment-999456948
Note: None of the users being added are currently members of the Kubernetes org, which is [viewed as bad practice](https://www.kubernetes.dev/docs/guide/owners/#maintaining-owners-files), however, none of the maintainers of the wider CA code have experience on Exoscale. We should instead work to enable the owners of this code to gain membership of the Kubernetes org.
```release-note
NONE
```
```docs
```
=> CA - Exoscale Provider - Add owners file

cluster-autoscaler/core/scale_test_common.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/processors/nodeinfosprovider/node_info_provider_processor.go, cluster-autoscaler/processors/processors.go
/kind bug
Adding expire time for nodeInfo cache items. Expire time could be set via flag `--node-info-cache-expire-time`, by default there is no expire time (old behavior).
Currently, item in the node info cache is updated only if there are any nodes in the node group. If node group is scaled down to 0, node info cache will store last node and use it in scale up algorithm. Thus if the last node is a wrong representative of the node group (for example it has custom taints), then Cluster Autoscaler may struggle to scale up this node group.
```release-note
Added `--node-info-cache-expire-time` flag for Cluster Autoscaler to specify the time to store node info cache items.
```
=> Add expire time for nodeInfo cache items

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/_helpers.tpl, charts/cluster-autoscaler/templates/clusterrole.yaml, charts/cluster-autoscaler/templates/clusterrolebinding.yaml, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/templates/role.yaml, charts/cluster-autoscaler/values.yaml
This PR add CAPI as a supported provider to the helm chart and orients itself on the existing config parameters.
It also adds an mode for running in a non-clusterscoped mode.
=> [CA][Helm] Add ClusterAPI as supported Provider to the helm chart

cluster-autoscaler/cloudprovider/azure/azure_kubernetes_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_kubernetes_service_pool_test.go
/kind bug
Fixes a bug 
Fixes # Azure AKS cluster-autoscaler non-functional duo to recently added tag-prefix #4666
```release-note NONE
```
```docs
```
=> fix autoscaling due to VMSS tag prefix issue

vertical-pod-autoscaler/pkg/recommender/README.md
vertical-pod-autoscaler docs.
The anchor link for section "implementation" is incorrect, this PR fixes it.
N/A
NONE
```release-note
Fixes vertical-pod-autoscaler documentations with a correct anchor link.
```
N/A
=> Fixed anchor link for section "implementation"

cluster-autoscaler/FAQ.md
Makes clear when multiple expander support was added to reduce user confusion when attempting to use it on unsupported versions of the autoscaler.
Fixes #4504 
```release-note
NONE
```
```docs
```
=> CA - Docs - Clarify when multi expander support introduced

cluster-autoscaler/cloudprovider/aws/CA_with_AWS_IAM_OIDC.md, cluster-autoscaler/cloudprovider/aws/README.md
Cluster Autoscaler - AWS cloud provider docs.
Follows up on a number of PRs we've seen from users in the recent past being confused by the existing IAM docs for using the CA in AWS (e.g. #4586 and #4465) as well as strengthening recommendations that users restrict the IAM roles provided via Resources of Conditionals as suggested by #4403.
Does this in part by explicitly providing two IAM policies rather than one minimal set with recommended additions hidden in a later sentence and making explicit the options blocked off by the use of the more limited policy. It also moves the recommendation to lock down IAM permissions to before the policy snippets rather than after to increase the likelihood of users reading it.
Fixes #
```release-note
NONE
```
```docs
```
=> CA - AWS - Rework IAM Docs/Snippets

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
/kind feature
This change introduces an environment variable, `CAPI_VERSION`, through
which a user can set the API version for the group they are using. This
change is being added to address situations where a user might have
multiple API versions for the cluster api group and wishes to be
explicit about which version is selected.
Also adds unit tests and documentation for the new behavior. This change
does not break the existing behavior.
n/a
```release-note
Users can now specify the Cluster API group version by setting the `CAPI_VERSION` environment variable to the desired version string.
```
Updated the README file to include usage documentation
=> add user configurable cluster api version

vertical-pod-autoscaler/pkg/admission-controller/main.go
Signed-off-by: sedflix <sedflix@gmail.com>
vertical-pod-autoscaler, admission controller 
/kind cleanup
This PR adds feature to log failure of HTTPS Server Startup
It will help in debugging #4695 
I'm not sure about the best practices to follow here.
```release-note
NONE
```
=> vpa: admission-controller: add logs for failure to start webhook server

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
The VPA updater
/kind cleanup
This reduces the verbosity of logs for the VPA updater with "not updating" log messages to a debug level. The VPA updater logs are clogged up with a lot of messages like this and it makes it difficult to find valuable information.
example:
```go
I0218 21:36:49.818992       1 update_priority_calculator.go:133] not updating a short-lived pod kube-system/etcd-0, request within recommended range
I0218 21:36:49.819061       1 update_priority_calculator.go:137] not updating pod kube-system/ccm-86f5f869b6-fs9n8, resource diff too low: {false false 0}
```
Fixes # https://github.com/kubernetes/autoscaler/issues/4692
```release-note
Lower the verbosity for "not updating" log messages for the VPA updater to debug level
```
```docs
```
=> Turn VPA Logging Level to V4 for Not Updating Messages

cluster-autoscaler/FAQ.md, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/processors/customresources/gpu_processor.go, cluster-autoscaler/utils/kubernetes/ready.go, cluster-autoscaler/utils/taints/taints.go
/kind feature
This change simplifies debugging GPU issues: without it, all nodes can
be Ready as far as Kubernetes API is concerned, but CA will still report
some of them as unready if they are missing e.g. GPU resource. Explicitly calling
them out in the status ConfigMap will point into the right direction.
Fixes #
```release-note
Status ConfigMap now contains additional information about nodes with unready resources.
```
```docs
```
=> Expose nodes with unready GPU in CA status

cluster-autoscaler/cloudprovider/aws/CA_with_AWS_IAM_OIDC.md, cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/auto_scaling_groups_test.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/aws/instance_type_cache.go, cluster-autoscaler/cloudprovider/aws/instance_type_cache_test.go
This change makes it so that Cluster Autoscaler will early-abort if AWS does not have any capacity available (e.g., it is a spot node group, and there are no spot instances available).  It works by polling the `DescribeScalingActivities` AWS EC2 endpoint, and setting the node group status to an error if the `DescribeScalingActivities` call returns "Failed".  This short-circuits the 15-minute waiting period for nodes to join the cluster before the node group is added to the backoff list, which allows Cluster Autoscaler to more rapidly try a different node group that is more likely to succeed.
* Recommend reviewing the commits separately
* All existing tests pass
* New unit tests for the new behaviour
* Tested in a test cluster at Airbnb (see below for details)
I created 3 `c5ad.16xlarge` …
=> Early abort if AWS node group has no capacity

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/role.yaml
Cluster Autoscaler helm chart
Cluster
/kind bug
This fixed the RBAC for namespaced mode of the cluster autoscaler
```release-note
fix RBAC for namespaced mode of cluster autoscaler helm chart
```
=> [CA Helm] fix RBAC for namespaced mode

cluster-autoscaler/core/equivalence_groups.go, cluster-autoscaler/core/equivalence_groups_test.go, cluster-autoscaler/core/filter_out_schedulable.go, cluster-autoscaler/core/utils/pod_schedulable.go, cluster-autoscaler/core/utils/pod_schedulable_test.go, cluster-autoscaler/metrics/metrics.go
/kind bug
This limits the number of pods that are searched in O(N) time per owner reference to a small fixed constant (10), to avoid future regressions when PodSpec is extended with new fields that differ between pods owned by the same controller. I added a new metric for tracking this, so that we can monitor & fix cases when that happens. This should keep the caching optimization maintainable in the future.
Fixes #4724
```release-note
NONE
```
```docs
```
=> Limit caching pods per owner reference

cluster-autoscaler/utils/utils.go, cluster-autoscaler/utils/utils_test.go
Hostname doesn't affect scheduling and different hostnames prevent
caching of similar pods in CA.
/kind bug
This improves CA performance when handling IndexedJobs (see #4724).
Fixes #4724
```release-note
NONE
```
```docs
```
=> Skip pod hostname when comparing PodSpecs

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl
helm-charts - Cluster Autoscaler
Addresses the fact we currently specify the AWS IAM permissions required by the CA running in AWS in both the chart's README and the cloudprovider implementation's docs, making it easy for the two to fall out of sync (as seen by the multiple comments on issue #3216. Just updating the README in the chart wouldn't fully address this, as users could use an old version of the chart, but update the CA's image tag to one requiring new IAM permissions. This addresses this by removing the duplication, and instead linking to the README of the AWS cloudprovider implementation as a single source of truth.
None
N/A
```release-note
NONE
```
```docs
```
=> Charts - CA - Remove AWS IAM Docs - Replace With Link

cluster-autoscaler/cloudprovider/cloudstack/cloudstack_cloud_provider_test.go, cluster-autoscaler/cloudprovider/cloudstack/cloudstack_manager.go, cluster-autoscaler/cloudprovider/cloudstack/cloudstack_manager_test.go, cluster-autoscaler/cloudprovider/cloudstack/cloudstack_node_group.go, cluster-autoscaler/cloudprovider/cloudstack/cloudstack_node_group_test.go, cluster-autoscaler/cloudprovider/cloudstack/service/cks.go
cluster-autoscaler / cloudprovider / cloudstack
/kind feature
Previously, nodes were identified by their system UUID. This sometimes causes issues as the hypervisor has a VM UUID, which differs from the one CloudStack uses. In such a case, identify the node by name
=> cluster-autoscaler/cloudstack: Identify node by name and id

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
We've had this logic for a while now. If the VMSS is updating state, return the in-memory size for a nodegroup/scale-set.
This was trying to guard from a scenario like below:
1. Autoscaler scales up to 4 instances
2. We get hit by a cache refresh
3. ARM hasn't registered our new capacity goal so we get stale data and we end up updating the in-memory cache to a lower value.
We've recently guarded against this case by [this](https://github.com/kubernetes/autoscaler/pull/4685) PR, where we extend our in-memory TTL so we should never hit that scenario.
For cases where the TTL is long, I believe this "Updating" logic can lead to a bad scenario where we take very long to reconcile with the real IaaS capacity goal if you for example get hit by multiple scale ups and it takes VMSS too long to …
=> remove check for returning in-memory size when VMSS is in updating state

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
Cherry-picks #4685 and #47874 onto 1.23
Both include improvements for the azure vmss cache 
=> Cherry-pick #4685, #47874 - Azure vmss cache improvements

cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/processors/nodegroupset/azure_nodegroups.go, cluster-autoscaler/processors/nodegroupset/azure_nodegroups_test.go
Cherry-picks #4421 and #4550 onto 1.22
Both include fixes to scaling from zero
=> Cherry-pick #4421, #4550 - Azure scale from zero improvements

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/servicemonitor.yaml
cluster-autoscaler helm chart
/kind bug
This PR fixes the service monitor manifest in the chat. Labels have wrong indentation that breaks the yaml file
NONE
=> Fix label indentation for the service monitor manifest

cluster-autoscaler/cloudprovider/azure/azure_kubernetes_service_pool.go, cluster-autoscaler/cloudprovider/azure/azure_kubernetes_service_pool_test.go
corrected the azure_kubernetes_ercice_pool_test unit test cases involving the changed tag prefix
added const aksManagedPoolName attribute to the top of the code and fixed file name sercice -> service
added logic for old clusters that still have poolName
added legacy tag for poolName
Fixed Autoscaling due to VMSS tag prefix issue, added tags for legacy poolName and aksManagedPoolName, and corrected file name sercice->service
/cherry-pick off an already approved PR https://github.com/kubernetes/autoscaler/commit/d2216e020fcddb1325a921b1a421bdb30dab7bf4
Fixes #
```release-note
```
```docs
```
=> fix autoscaling due to VMSS tag prefix issue - Cherry Pick into release 1.22

cluster-autoscaler/cloudprovider/packet/OWNERS
/kind cleanup
Update owners for cluster-autoscaler Equnix Metal provider
- Add cprivite, as he'll be taking over primary support responsibility for the Equinix Metal provider for cluster-autoscaler
- Remove gianrb and rawkode, since they are no longer active contributors.
```release-note
NONE
```
Pending org membership for @cprivite here: https://github.com/kubernetes/org/issues/3355
=> Update owners for cluster-autoscaler Equnix Metal provider

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Cluster Autoscaler
Add one of the following kinds:
/kind bug
If LongUnregistered nodes are present and couldn't be removed for long time they block Cluster Autoscaler. 
Basic Scale Up and Scale Down are tested with current change. 
```release-note
LongUnregistered nodes don't block Cluster Autoscaler. 
```
=> Continue CA loop when unregistered nodes were removed

cluster-autoscaler/cloudprovider/gce/gce_reserved.go, cluster-autoscaler/cloudprovider/gce/gce_reserved_test.go, cluster-autoscaler/cloudprovider/gce/os_reserved.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
Introduce extraction of System Architecture from AutoscalerVars  in GCE cloud-provider
/kind feature
Fixes #
None
```release-note
```
```docs
```
/assign @x13n
=> Introduce extraction of System Architecture from AutoscalerVars 

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
helm charts
/kind feature
Due to this issue https://github.com/kubernetes/autoscaler/issues/4784, we need access to annotations on the Deployment so we can reload the pod every time the workload cluster kubeconfig updates.
```release-note
new property in values: added 'annotations' property to allow setting annotations on the Deployment
```
=> feat: add support for deployment annotations to helm chart

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache_test.go
Related to https://github.com/kubernetes/autoscaler/pull/3968
This change adds a Managed Nodegroup cache that will hold labels and taints from the AWS EKS DescribeNodegroup API output. It will be used to get more information for EKS managed nodegroups that are scaled to 0 nodes. Currently this code will only run when the managed nodegroup has 0 nodes and CAS doesn't have a node info object cached already.
To use this new functionality, users will need to add `"eks:DescribeNodegroup"` to their IAM policy. If they don't add the permissions, the AWS EKS DescribeNodegroup API call will fail and the error will be logged, but CAS will not be killed. A managed nodegroup cache object with nil list & nil map will be saved even if permissions are missing to stop CAS from causing throttling from …
=> [AWS EKS - Scale-to-0] Add Managed Nodegroup Cache

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml
/kind bug
The `extraVolumeMounts` section of the deployment template currently adds an unnecessary blank line (whitespace) in the rendered yaml output 
Current rendered output example:
```yaml
volumeMounts:
- mountPath: /etc/ssl/certs/ca-certificates.crt
name: ssl-certs
readOnly: true
```
Rendered output example with this fix applied:
```yaml
volumeMounts:
- mountPath: /etc/ssl/certs/ca-certificates.crt
name: ssl-certs
readOnly: true
```
Fixes #
```release-note
Removes whitespace from the templated deployment output when the `extraVolumeMounts` option is used.
```
```docs
```
=> Remove newline indentation from CA deployment 

cluster-autoscaler/hack/update-vendor.sh
Cluster Autoscaler
/kind bug
Previously we would run `go mod vendor` before `go mod tidy`, meaning
that we were snapshotting dependencies before we were really finished
updating them.
=> Minor bugfix to update-vendor script

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml
/kind bug
This fixes an issue where a malformed template is generated when setting extraVolumeMounts in a values.yaml file.
When values.yaml contains:
```yaml
extraVolumeMounts:
- name: ssl-certs
mountPath: /etc/ssl/certs/ca-certificates.crt
readOnly: true
```
Generated output is:
```yaml
volumeMounts:
- mountPath: /etc/ssl/certs/ca-certificates.crt
name: ssl-certs
readOnly: true
```
Error message is:
```
Error: YAML parse error on cluster-autoscaler/templates/deployment.yaml:
error converting YAML to JSON: yaml: line 50: did not find expected key
```
NONE
```release-note
NONE
```
```docs
```
=> Fix indentation

vertical-pod-autoscaler/pkg/updater/main.go
/kind bug
This should fix at least some e2e test failures, maybe all of them (#4764)
#4723 moved context creation from inside loop (correct) to doing it once, before loop starts (incorrect, context will be done in all loop iterations after the first one).
Fix a bug we had in the old version (using `defer` in a loop would call the deferred function only after we exit `main` not as expected on each loop iteration). Thanks @krzysied for pointing out the bug
@Fedosin FYI
=> Fix updater main

cluster-autoscaler/proposals/parallel_drain.md
/kind feature
This is a proposal for draining multiple nodes in parallel, which will improve scale down performance in large clusters.
n/a
```release-note
NONE
```
```docs
```
=> Design proposal for parallel drain

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/templates/pdb.yaml, charts/cluster-autoscaler/templates/priority-expander-configmap.yaml, charts/cluster-autoscaler/templates/role.yaml, charts/cluster-autoscaler/templates/rolebinding.yaml, charts/cluster-autoscaler/templates/secret.yaml, charts/cluster-autoscaler/templates/service.yaml, charts/cluster-autoscaler/templates/serviceaccount.yaml
Signed-off-by: cw-sakamoto <sakamoto@chatwork.com>
helm charts
/kind feature
When `helm template` is used to generate manifests, `namespace:` is specified in manifests.
FYI: https://github.com/DataDog/helm-charts/commit/f74f7b00ae52103fcfe5b2a1c432749274e28460
Fixes #
```release-note
```
```docs
```
=> [CA][Helm]Add .Release.Namespace to each template

vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler_test.go
/kind bug
Add Validation for VPA
Fixes #4790
```release-note
None
```
```docs
None
```
=> Add resource validation

cluster-autoscaler/core/scale_down.go
/kind cleanup
the log seems not error
NONE
```release-note
NONE
```
```docs
```
=> fix: log level

hack/for-go-proj.sh
The cluster-autoscaler use godep, and the  cluster-autoscaler vertical-pod-autoscaler use gomod.
So should we set GO111MODULE=auto as default. and GO111MODULE=off only for the  cluster-autoscaler project.
Signed-off-by: Kay Yan <kay.yan@daocloud.io>
=> Fix CI script to use GO111MODULE auto as default

cluster-autoscaler/core/scale_down.go
Fix a typo in error message.
"ScaleDownUnnreadyTime"-> "ScaleDownUnreadyTime"
/kind cleanup
This PR fixes a typo in error message.
NONE
Good morning.
```release-note
NONE
```
```docs
```
=> Fix a typo in scale_down.go

cluster-autoscaler/core/scaledown/deletiontracker/nodedeletiontracker.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/legacy/wrapper.go, cluster-autoscaler/core/scaledown/scaledown.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/processors/status/scale_down_status_processor.go, cluster-autoscaler/utils/expiring/list.go, cluster-autoscaler/utils/expiring/list_test.go
/kind feature
This is a step towards implementing parallel drain logic. The refactor in https://github.com/kubernetes/autoscaler/pull/4806 splitted ScaleDown logic into separate Planner and Actuator objects. NodeDeletionTracker represents the ActuationStatus, which is used to feed back information about actuation progress into the planning logic.
Fixes #
Since https://github.com/kubernetes/autoscaler/pull/4806 didn't merge yet, this PR is quite large, but in reality it is only the last commit that is different. Once the other PR merges, I will rebase this one. 
```release-note
NONE
```
```docs
https://github.com/kubernetes/autoscaler/blob/48273b7affaa9463b37c72146a3b3de2ac06fc06/cluster-autoscaler/proposals/parallel_drain.md
```
/cc @MaciekPytel @towca
=> Make NodeDeletionTracker implement ActuationStatus interface

cluster-autoscaler/FAQ.md
Signed-off-by: yogeek <gdupin@gmail.com>
The flags added in #1407 were missing from the documentation. This PR adds them.
```release-note
NONE
```
=> add cluster-autoscaler missing flags in documentation

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/main.go
Signed-off-by: Grigoris Thanasoulas <gregth@arrikto.com>
/kind feature
This PR introduces a  `--max-pod-eviction-time` flag that allows the user to configure the `MaxPodEvictionTime`, which is currently hard coded and set to `2m`. There are cases when a pod may take (by design) more than 2 minutes to be evicted, and the user may wish to configure the autoscaler to wait for more time for the eviction to complete.
Fixes #4841.
```release-note
Introduce a `--max-pod-eviction-time` flag to allow configuration of `MaxPodEvictionTime`, i.e., the maximum time the cluster autoscaler tries to evict a pod.
```
```docs
```
=> cluster-autoscaler: Add --max-pod-eviction-time flag to configure MaxPodEvictionTime

cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/static_autoscaler.go
/kind cleanup
Step towards preparing the code for another ScaleDown implementation.
Fixes #
```release-note
NONE
```
```docs
https://github.com/kubernetes/autoscaler/blob/48273b7affaa9463b37c72146a3b3de2ac06fc06/cluster-autoscaler/proposals/parallel_drain.md
```
/assign @towca
=> Move the condition for ScaleDownInProgress to legacy scaledown code

cluster-autoscaler/cloudprovider/clusterapi/README.md
Fixing typo in Specifying a Custom Resource Group section in annotation examples.
This PR is a simple documentation typo fix.
Fixes #
```release-note
NONE
```
```docs
```
=> cluster-autoscaler/cloudprovider/clusterapi/README.md - simple typo fix

cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go
Wraps simulator functions into an object, so that there's no need to
pass around parametrs that are not changing between CA loop iterations.
/kind cleanup
Required for parallel scale down implementation.
Fixes #
```release-note
NONE
```
```docs
https://github.com/kubernetes/autoscaler/blob/48273b7affaa9463b37c72146a3b3de2ac06fc06/cluster-autoscaler/proposals/parallel_drain.md
```
/assign @towca
=> Allow checking specific nodes removal in simulator

cluster-autoscaler/simulator/predicate_error.go, cluster-autoscaler/simulator/scheduler_based_predicates_checker.go
/kind feature
Use the node names given in the new `PreFilterResult` to skip nodes in `FitsAnyNode`.
It did not seem ideal to also use the result in `CheckPredicates`. The pre-filter result does not include a message or reason like the filter result, so it would provide less information to the caller to return a generic pre-filter error. Let me know if the intent was to modify this as well.
Fixes #4745
```release-note
NONE
```
```docs
```
=> use the PreFilterResult in SchedulerBasedPredicateChecker

vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
/kind cleanup
Previously, GetMatchingPods was executed even if the log statement was never printed. Given that this is a costly operation which traverses all known Pods, we only want to do this if it is actually useful.
We are using VPA in big clusters with ~4000 VPA objects. Because of automatic downscaling of the workload running in there, it happens that most of the time ~1000 VPA objects don't match any Pods.[ If workload is scaled down for longer than 30 minutes](https://github.com/kubernetes/autoscaler/blob/3cc40495c9aea057c1fda5a1fd8d60880fe3d650/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L115), the `UpdateVPAs` step will for each of these non-matching VPAs [will execute `GetMatchingPods`](https://github.com/kubernetes/autoscaler/blob/3cc …
=> Move GetMatchingPods into block guarded by klog.V(4)

vertical-pod-autoscaler/common/version.go
Increase VPA version, first step to cutting a new release.
Previous version is [0.10.0](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.10.0), released on 2022-01-26.
K8s 1.24 [has been release on 2022-05-03](https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/) so I want to release a new version of VPA too.
=> VPA release 0.11.0

cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_manager.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_manager_test.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group_test.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_provider.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_provider_test.go, cluster-autoscaler/cloudprovider/ovhcloud/sdk/consumer_key.go, cluster-autoscaler/cloudprovider/ovhcloud/sdk/flavor.go, cluster-autoscaler/cloudprovider/ovhcloud/sdk/mock.go, cluster-autoscaler/cloudprovider/ovhcloud/sdk/nodepool.go, cluster-autoscaler/cloudprovider/ovhcloud/sdk/ovh.go
Various bug fixes to the OVHcloud provider:
- Fix silent failure of upscale/downscale due to the node group status being not READY
- Fix Instance.ID to the actual value of Node.Spec.ProviderID
- Fix infinite looping when DecreaseTargetSize is called
- Fix the way we determine to which node group a node belongs to
- Fix handling of non-autoscaled nodepools (now considered as autoscaled nodepools with no margin of action)
- Fix TemplateNodeInfo with correct allocatable resources from the instance flavor specs
Signed-off-by: Xavier Duthil <xavier.duthil@ovhcloud.com>
/kind bug
Various fixes to the OVHcloud provider (see top of description for the list of fixes).
Those fixes have already been released in production on the OVHcloud Managed Kubernetes product.
This PR is also …
=> Various fixes to the OVHcloud provider

cluster-autoscaler/cloudprovider/oci/README.md, cluster-autoscaler/cloudprovider/oci/oci_cloud_provider.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool_cache.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool_manager.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool_manager_test.go
This feature can be turned on by setting environment variable _**OCI_USE_NON_MEMBER_ANNOTATION**_ to true.
For example, if a node is not belong to any instance pool,  during the very first GetInstancePoolForInstance call, the node will be annotated with _**oci.oraclecloud.com/instancepool-id: non_pool_member**_.
After new annotation is added to the node, all future GetInstancePoolForInstance calls related to the non-pool-member node will skip the time-consuming findInstanceByDetails API call.
Minor refactoring - when retrieving pool size from instancePoolCache object, use the pool size defined inside the poolCache map instead.
=> OCI cloud provider : Optional Feature - Skip time-consuming findInstanceByDetails API call by adding non_pool_member annotation to the node

cluster-autoscaler/cloudprovider/cherryservers/examples/cluster-autoscaler-secret.yaml
Signed-off-by: Avi Deitcher <avi@deitcher.net>
/kind bug
The cherry cluster-autoscaler had named the example secret `bootstrap-token-cluster-autoscaler-cherry`. This is fine, except that the cloud-node controller and bootstrap-signer won't JWS sign the cluster-info configmap unless it is named `bootstrap-token-<TOKEN_ID>`.
=> properly name secret

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go
```
InitialNodeGroupBackoffDuration
MaxNodeGroupBackoffDuration
NodeGroupBackoffResetTimeout
```
are hard codes now, maybe not reasonable for all cloud providers. 
we need expose these backoff time parameters
=> Expose backoff time parameters

vertical-pod-autoscaler/e2e/v1/actuation.go, vertical-pod-autoscaler/e2e/v1beta2/actuation.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go
v1beta1 is deprecated in 1.25
#4886
This will make remaining tests green.
v1 and v1beta1 `Actuation observes pod disruption budget` tests passed with this change.
=> Switch to using policy v1 API

vertical-pod-autoscaler/README.md
Documentation
As seen [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L126-L143) there are four modes in which VPA operates, updating the readme to reflect that change.
NONE
NONE
=> Update the README to show correct number of modes

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/_helpers.tpl, charts/cluster-autoscaler/templates/pdb.yaml
`helm-charts`
/kind feature
Remove warning of policy/v1beta1 deprecation
```
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```
n/a
n/a
- https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
```docs
Migrate manifests and API clients to use the policy/v1 API version, available since v1.21.
```
Fixes: #4285
=> [Helm] Support policy/v1 for PodDisruptionBudget for v1.21+

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
AWS introduced G5 instances with NVIDIA A10g GPUs. The scale up metric
will now match and label the GPU type correctly.
See the following link for details on the instance type:
https://aws.amazon.com/ec2/instance-types/g5
/kind feature
The scale up metric does not support the GPU type NVIDIA A10G GPUs used by AWS EC2 G5 instances.
Fixes #
```release-note
Added support for NVIDIA A10G GPU type in the AWS cloud provider.
```
```docs
```
=> Add new AWS GPU type NVIDIA A10g

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
/kind feature
/area provider/aws
Two new instance families were introduced in the last few days since #4917:
https://aws.amazon.com/about-aws/whats-new/2022/05/introducing-amazon-ec2-c6id-instances/
https://aws.amazon.com/about-aws/whats-new/2022/05/introducing-amazon-ec2-m6id-instances/
/cc @gjtempleton 
```release-note
Updated AWS instance types, including c6id and m6id families.
```
=> CA - AWS - Instance List Update 2022-05-30

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Various cloudproviders' `NodeGroupForNode()` implementations (including [aws](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L114), [azure](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go#L98), and [gce](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/gce/mig_info_provider.go#L99)) can returns a `nil` error _and_ a `nil` nodegroup. For instance we're seeing AWS returning that on failed upscales on live clusters, with a recent cluster-autoscaler build.
So checking that `deleteCreatedNodesWithErrors` doesn't return an error is not enough to safely dereference the nodegroup (as returned by `NodeGroupForNode()`) by calling …
=> Don't deref nil nodegroup in deleteCreatedNodesWithErrors

cluster-autoscaler/FAQ.md
Available here https://github.com/kubernetes/autoscaler/blob/572d1997570117d7c5e515cc01ffad7151b44a95/cluster-autoscaler/main.go#L187 but missing from the FAQ
No issue(s) found
```release-note
NONE
```
=> Add cordon-node-before-terminating to FAQ

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
Fixes https://github.com/kubernetes/autoscaler/issues/4927
=> Drop deprecated CAPI annotations

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/service.yaml, charts/cluster-autoscaler/values.yaml
helm charts
/kind feature
The service is the only resource that can't be disabled. As I see it its only purpose is to expose metrics and some optional things like profiling and snapshots. If none of these are used a service shouldn't be required.
```release-note
Optionally exclude service from templated resources
```
=> [CA][Helm] Allow skipping service creation

cluster-autoscaler/core/scaledown/legacy/wrapper.go
Previously it'd only return nodeDeleteResults if a subsequent
scale-down attempt was made, which is sub-optimal, and doesn't
match legacy behavior.
=> CA: make legacy SD wrapper always return nodeDeleteResults

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go
/kind bug
If instance type listing fails, the autoscaler would fail to work.  This change modifies behavior so that it falls back
to the static list of instance types.
Fixes #
```release-note
```
```docs
```
=> Fix fallback for aws cloudprovider

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go, cluster-autoscaler/cloudprovider/gce/gce_price_info.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodeinfosprovider/annotation_node_info_provider.go, cluster-autoscaler/utils/test/test_utils.go
/kind feature
Improve scale-up decisions
=> Add ephemeral storage pricing to GCE expander

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
/kind bug
Backports #4873 
Instead of logging a fatal error, log a standard error and fall back to
loading instance types from the static list.
Fixes #
```release-note
NONE
```
```docs
```
=> CA - AWS Cloud Provider - 1.21 - fix instance type fallback

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
/kind bug
Backports #4873 
Instead of logging a fatal error, log a standard error and fall back to
loading instance types from the static list.
Fixes #
```release-note
NONE
```
```docs
```
=> CA - AWS Cloud Provider - 1.22 - fix instance type fallback 

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
/kind bug
Backports #4873 
Instead of logging a fatal error, log a standard error and fall back to
loading instance types from the static list.
Fixes #
```release-note
NONE
```
```docs
```
=>   CA - AWS Cloud Provider - 1.23 - fix instance type fallback

cluster-autoscaler/FAQ.md, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/deletetaint/delete_test.go, cluster-autoscaler/utils/kubernetes/factory.go
/kind feature
this change brings in a new command line flag,
`--enable-event-duplication`, which allows a user to enable the
duplication of events bypassing the 5 minute de-duplication window.
Fixes #2495
```release-note
Add enable-event-duplication flag to allow the cluster autoscaler to log duplicate events within a 5 minute window.
```
```docs
```
=> add a flag to allow event duplication

cluster-autoscaler/cloudprovider/aws/aws_wrapper.go
/kind bug
This PR fixed the typo i.e. `tempate` to the `template` in aws_wrapper.go.
Fixes #4903
```
NONE
```
```
NONE
```
=> Fixed Typo in aws_wrapper.go

vertical-pod-autoscaler/README.md
Adapt links to original design-proposal in README. Design proposals have been archived and are no longer available in the community repo.
```release-note
NONE
```
=> Adapt links to original design-proposal in README

cluster-autoscaler/cloudprovider/cherryservers/README.md, cluster-autoscaler/cloudprovider/cherryservers/cherry_manager_rest.go, cluster-autoscaler/cloudprovider/cherryservers/cherry_types.go
/kind feature
Set OS partition size for nodes 
```release-note
```
```docs
```
=> Add support for passing os partition size when creating nodes

cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
/kind bug
It prevents error in cluster-autoscaler in case empty arch is provided in kube env.
=> Handle gracefully empty arch in kube env.

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
/kind cleanup
Add a level-guard to the Recommender's selector log statement, as this creates a log line for every VPA object every 60 seconds and isn't very essential information.
Fixes #4869
```release-note
Guards the Recommender's 'Using selector x for y' log statements with V(3). If you need these to be present, adjust your log level to be `>=3`.
```
/cc @aeimer
=> Add level-guard to Recommender selector log statement

cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
PR #4973 changed ToSystemArchitecture behavior to return DefaultArch
instead of UnknownArch for invalid architectures. This kind of defaulting
makes sense while parsing KUBE_ENV, but prevents using the function
in contexts where an invalid architecture should result in an error.
This commit reverts ToSystemArchitecture to previous behavior, and
moves defaulting to the callsite.
=> CA: GCE: Return UnknownArch from ToSystemArchitecture for invalid architectures

vertical-pod-autoscaler/README.md
/kind bug
This PR fixed the Hyperlink of the Design proposal in README.
Fixes #4986
```
NONE
```
```docs
```
=> Correct the Hyperlink of VPA design-proposal in README.

cluster-autoscaler/README.md
The cluster-autoscaler readme.txt has been outdated,this pr  update the documentation for cluster-autoscaler supported cloud providers
Fixes #
```release-note
```
```docs
```
=> Update documentation for cluster-autoscaler supported cloud providers

cluster-autoscaler/core/scaledown/actuation/drain.go, cluster-autoscaler/core/scaledown/actuation/drain_test.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/wrapper.go, cluster-autoscaler/core/scaledown/scaledown.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go, cluster-autoscaler/utils/kubernetes/listers.go
…r 1.25
/kind bug
Fixes #4285 
```release-note
```
```docs
```
=> switched policy for PodDisruptionBudget from v1beta1 to v1 in time for 1.25

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/cache_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/machine_types.go, cluster-autoscaler/cloudprovider/gce/machine_types_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
cluster-autoscaler (GCE provider)
/kind cleanup
Move fetching MachineType for MIG to MigInforProvider. This allows
more consistent error handling with other GCE API calls and wraps
information about machine in a new struct, removing the need to interact
directly with raw GCE client objects in most CA provider code.
Also removed caching errors for MachineType API in cache.go, since
it was never never used anyway and it's inconsistent with error handling
for other APIs.
No
=> GCE: move fetching MachineType to MigInfoProvider

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/static_autoscaler.go
/kind bug
This PR includes the initial work first introduced in #4211.  Feedback from that PR indicated that the original intent of determining the deleted nodes was incorrect, which led to the issues reported by other users.  The nodes tainted with ToBeDeleted were misidentified as Deleted instead of Ready/Unready, which caused a miscalculation of the node being included as Upcoming.  This caused problems described in #3949 and #4456.
Fixes #3949, #4456
NONE
=> Adding support for identifying nodes that have been deleted from cloud provider that are still registered within Kubernetes

cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
=> GCE: Always add boot disk annotations to templates

cluster-autoscaler/Dockerfile.amd64, cluster-autoscaler/Dockerfile.arm64
There is no need to use the root user. This allows the user to comply with pod security standards.
It turns out that the `nonroot` image has the `cwd` set to `/home/nonroot` whereas `latest` is rooted in `/` :shrug: . 
This is important because the helm chart uses `./cluster-autoscaler` as command. Keeping the same cwd seems like the safest option to me. 
/kind feature
This PR makes infosec happy :smiley: 
Fixes #3705
```release-note
```
```docs
```
=> feat: use non-root user for base-image

vertical-pod-autoscaler/README.md
/kind bug
This PR removes the Migration Doc word which appears 2 times in README. And Attach the **Vertical Pod Autoscaler Migration** link to it. For the better uniformity of the docs.
```
NONE
```
```
NONE
```
=> Deduplicate Migration Doc from README.

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/static_autoscaler.go
Reverts kubernetes/autoscaler#4896
This is to mitigate https://github.com/kubernetes/autoscaler/issues/5022. We should reapply the change once it can properly support NodeGroups that are not autoscaled.
=> Revert "Adding support for identifying nodes that have been deleted from cloud provider that are still registered within Kubernetes"

cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/machine_types.go, cluster-autoscaler/cloudprovider/gce/machine_types_test.go
IsCustomMachine didn't take machine types with family prefix
(e.g. n2-custom-2-2816) into account.
=> CA: GCE: implement GetMachineFamily, fix IsCustomMachine

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
Cluster autoscaler - cluster api.
This ensured that access to replicas during scale down operations were never stale by accessing the API server https://github.com/kubernetes/autoscaler/issues/3104.
This honoured that behaviour while moving to unstructured client https://github.com/kubernetes/autoscaler/pull/3312.
This regressed that behaviour while trying to reduce the API server load https://github.com/kubernetes/autoscaler/pull/4443.
This put back the never stale replicas behaviour at the cost of loading back the API server https://github.com/kubernetes/autoscaler/pull/4634.
Currently on e.g a 48 minutes cluster with no scaling activity it does 1.4k get request to the scale subresource.
This PR tries to satisfy both non stale replicas during scale down and prevent the API server from …
=> Get capi targetsize from cache

vertical-pod-autoscaler/builder/Dockerfile
/kind cleanup
Bump the Go version to the most recent 1.17 release, such that we can cut a new release
```release-note
NONE
```
=> Bump VPA builder Go version

cluster-autoscaler/cloudprovider/clusterapi/README.md
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>
Add a not on ClusterClass usage to the Cluster API docs for the Autoscaler. 
=> Add ClusterClass usage instructions to ClusterAPI docs

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
/kind feature
Adds a new error code `VM_EXTERNAL_IP_ACCESS_POLICY_CONSTRAINT` to GCE autoscaling client to provide better visibility into errors caused by the org policy misconfiguration.
N/A
-
```release-note
NONE
```
```docs
```
=> Add a new error code to GCE autoscaling client

cluster-autoscaler/FAQ.md
/kind cleanup
this change adds proper escaping to the min/max tags for the cores-total
flag entry in the FAQ, which makes it so that the markdown render will
print the proper formating for this flag.
=> fix FAQ entry for cores-total flag

cluster-autoscaler/expander/grpcplugin/example/fake_grpc_server.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
/kind cleanup
log.Fatalf is equivalent to Printf() followed by a call to os.Exit(1). So next line panic is not needed
Fixes #
```release-note
None
```
```docs
```
=> delete minor unreachable code caused by log.Fatal

cluster-autoscaler/cloudprovider/magnum/README.md
/kind bug
This PR added the hyperlink for the `node-group-auto-discovery` flag in [Autoscaler deployment](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/magnum#autoscaler-deployment) under  [OpenStack Magnum](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/magnum) cloud provider.
=> Added Hyperlink for node-group-auto-discovery flag.

cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml
fix cluster-autoscaler alicloud provider example format error
Fixes #
```release-note
```
```docs
```
=> fix: cluster-autoscaler alicloud provider example format error

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/proposals/metrics.md
/kind feature
This change adds a new metric, skipped_scale_events_count, which will
record the number of times that the CA has chosen to skip a scaling
event. The metric contains a label for the scaling direction (up or down)
and the reason.
This patch includes usages for the new metric based on CPU or Memory
limits being reached in eiter a scale up or down.
*User Story*
As a cluster autoscaler user, I would like to create alerts to inform me when my cluster is exceeding its resource limits. Having a Prometheus metric to measure this would allow me to create automated alerting.
n/a
none
```release-note
A new metric ("cluster_autoscaler_skipped_scale_events_count") has been added to monitor when CPU and memory resource limits have been exceeded.
```
```docs
```
=> add metric for skipped scaling events

cluster-autoscaler/cloudprovider/azure/README.md
I struggled for a long running issue arround GPU node scaling in a Rancher RKE Kubernetes Cluster using Azure VM Scale Set. The scale up process freeze after node count back to zero. After digging the source code I discover that label `accelerator` (hardcoded in azure cloud provider) should be setted on kubelet node to make cluster-autoscaler handle correctly GPU ressources.
I guess it would help further user to deal with it.
NONE
For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
```
```docs
```
=> Add note in Azure autoscaler documentation about adding accelerator node label on VMSS when GPU nodes are involved.

cluster-autoscaler/README.md, cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_scaleway.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/scaleway/OWNERS, cluster-autoscaler/cloudprovider/scaleway/README.md, cluster-autoscaler/cloudprovider/scaleway/scaleway_cloud_provider.go, cluster-autoscaler/cloudprovider/scaleway/scaleway_node_group.go, cluster-autoscaler/cloudprovider/scaleway/scaleway_node_group_test.go, cluster-autoscaler/cloudprovider/scaleway/scalewaygo/README.md, cluster-autoscaler/cloudprovider/scaleway/scalewaygo/scaleway_kapsule_api.go
/kind feature
this PR upstreams the implementation of the cluster-autoscaler used by the cloud provider Scaleway.
None
Do not hesitate to ping me on k8s slack channel #sig-autoscaling if anything =)
k8s users:
NONE
Kapsule users:
Scaleway users will have the choice of managing themselves the cluster-autoscaler pod therefore metrics will be scraped more easily.
[Kapsule Doc]: <https://developers.scaleway.com/en/products/k8s/api/>
I am happy to answer questions, let me know if you have any suggetions regarding the code.
The implementation has been tested in scaleway environment and is working as expected.
Louis
=> add: Scaleway Cloud Provider for k8s CA

cluster-autoscaler/cloudprovider/hetzner/README.md, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/certificate.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/client.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/datacenter.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/error.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/firewall.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/floating_ip.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/hcloud.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/iso.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/labels.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/load_balancer.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/load_balancer_type.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/location.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/metadata/client.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/network.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/placement_group.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/pricing.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/primary_ip.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/pricing.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/primary_ip.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/server.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/server.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/server_type.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/ssh_key.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/volume.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go, cluster-autoscaler/go.mod, cluster-autoscaler/vendor/modules.txt
/kind feature
It lets us use hetzner's new primary IP feature to disable the public IPv4/IPv6 addresses on the nodes
```release-note
Added Hetzner public IPv4 and IPv6 configuration.
```
=> Hetzner public IPv4 and IPv6 configuration

cluster-autoscaler/cloudprovider/hetzner/OWNERS
Signed-off-by: Lukas Kämmerling <lukas.kaemmerling@hetzner-cloud.de>
Hetzner Cloud Provider
This PR is based on the comment from https://github.com/kubernetes/autoscaler/pull/5001#issuecomment-1208175313 . This adds @4ND3R50N and me as reviewers and approvers. We both are currently in charge of our Open Source Integrations. (Like Terraform, hcloud-go, CSI-Driver & Autoscaler) 
Fixes #
```release-note
```
```docs
```
=> Hetzner Cloud Provider: Add Owners file

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_metrics.go
Provide metrics for Hetzner API calls; helps identifying slowness, throttling causes, and errors bursts.
Signed-off-by: Maksim Paskal <paskal.maksim@gmail.com>
=> Metrics for Hetzner API calls

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_server_type_cache.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_server_type_cache_test.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache_test.go
Hetzner Cloud has rate limiting to their API (3600 requests per hour), for large kubernetes clusters it makes difficult to correspond this rate limiting in cluster autoscaling.
As a proposal, make cached requests to `Servers` and `Server Type` in Hetzner Cloud API, cached layer make only one Hetzner API request to get all objects in cached period, filtration of results will be processed in this caching layer.
Cashing behavior:
1. `Server Type` cache TTL is 10 minute
2. `Servers` cache TTL is 1 minute
3. `Servers` cache will be force refreshed when server was added or removed
Cache layer significantly reduce requests to Hetzner Cloud API, it make autocaling more reliable
Signed-off-by: Maksim Paskal <paskal.maksim@gmail.com>
=> Cache requests to Hetzner Cloud API

cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-aks.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml, cluster-autoscaler/cloudprovider/oci/README.md, cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-config.yaml, cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-principals.yaml
- Fixes examples that are broken (not pointing to `k8s.gcr.io/autoscaling/cluster-autoscaler`).  I was following https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#vmss-deployment when I discovered this.
- Fixes whitespace to make pre-commit pass.
```release-note
NONE
```
Signed-off-by: Evan Freed <evan.freed@protonmail.ch>
=> fix: Wrong image path in Docs

cluster-autoscaler/cloudprovider/resource_limiter.go, cluster-autoscaler/core/scale_up.go
random little cleanup to make the code more readable / ideomatic
... what we are doing is joining string together, so use `strings.Join` instead of buffer math
=> use strings.Join to build list of names

cluster-autoscaler/processors/nodeinfosprovider/annotation_node_info_provider.go
/cluster-autoscaler
/kind bug
In case node group scaled down to 0, the NodeGroupForNode is returning nil NodeGroup and nil error.
=> CA: Iterate through existed node groups in AnnotationNodeInfoProvider

vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender_test.go
/kind bug
When iterating through a map of RecommendedPodResources, the order of the container names is not guaranteed, see: https://go.dev/blog/maps
This will cause the order of the slice of ContainerRecommendations in the VPA status to change on every call to GET the object.
The fix is to deliberately sort a list of the container names, and use the list to key over the map.
Fixes #4910 
```release-note
```
```docs
```
=> Sort the list of container resource recommendations in VPA status

cluster-autoscaler/README.md, cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_rancher.go, cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/cloudprovider/rancher/OWNERS, cluster-autoscaler/cloudprovider/rancher/README.md, cluster-autoscaler/cloudprovider/rancher/examples/config.yaml, cluster-autoscaler/cloudprovider/rancher/provisioning.cattle.io/v1/rke.go, cluster-autoscaler/cloudprovider/rancher/rancher_clusterapi.go, cluster-autoscaler/cloudprovider/rancher/rancher_config.go, cluster-autoscaler/cloudprovider/rancher/rancher_config_test.go, cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup.go, cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup_test.go, cluster-autoscaler/cloudprovider/rancher/rancher_provider.go, cluster-autoscaler/cloudprovider/rancher/rancher_provider_test.go
/kind feature
Adds cluster-autoscaler provider for [Rancher](https://github.com/rancher/rancher/) with RKE2. This has been tried [before](https://github.com/kubernetes/autoscaler/pull/4041) but as this was for RKE (1) clusters, it works in a completely different way as Rancher fully changed their APIs and provisioning for RKE2. This provider only supports RKE2, which is now GA as of Rancher v2.6.5.
RKE2 provisioning uses cluster-api under the hood, so there are some similarities to the cluster-api provider but not enough to be able to share code. Plus I assume that is probably not really desired anyway. Since the Rancher server manages the cluster-api objects, it's not possible to simply run the cluster-api autoscaler as these two controllers would fight over control, …
=> Add cloud provider for Rancher with RKE2

cluster-autoscaler/cloudprovider/azure/azure_agent_pool_test.go, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_instance.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_template.go
The skewer library's cache is re-created at every call, which causes pressure on Azure API, and slows down the cluster-autoscaler startup time by two minutes on a relatively small test cluster (120 nodes, 300 VMSS).
This was also hitting the API twice on cache miss to look for non-promo instance types, even when the instance name doesn't ends with "_Promo".
SKU API call rate before/after:
=> Azure: effectively cache instance-types SKUs

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
helm chart of the cluster-autoscaler
/kind feature
The cluster auto-scaler for Azure supports auto-discovery but the helm chart does not. Added basic support for discovering node groups when using Azure.
/
/
```release-note
Added support to auto discover node groups to the helm chart when using the  Azure cloudProvider.
```
```docs
```
=> Add support for azure autodiscovery with autoscaler helm chart.

.github/workflows/ci.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
`err` was always `nil` here, and the real error was not retained at all.
/kind bug
Fixes #
```release-note
Minor error logging improvement in GCE cloud provider.
```
```docs
```
=> Fix error logging when waiting for GCE operation

cluster-autoscaler/FAQ.md
Speeds up the time it takes to replace an overprovisioning pause pod with an application pod by 3-11 seconds
Fixes #
I have noticed when deploying pods that replace overprovisioning pause pods, adding this termination grace period will speed it up by 3-11 seconds, without any downsides that I know of. I suspect this is because k8s will send a SIGKILL instead of SIGTERM + poll for completion when `terminationGracePeriodSeconds` is set to `0`
```release-note
NONE
```
```docs
```
=> Improve overprovisioning pause pod termination time in FAQ

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_autodiscovery_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
/kind feature
This PR adds scale from zero capability to the clusterapi provider for cluster-autoscaler.
Fixes #3150 
The [cluster-api-provider-kubemark](https://github.com/kubernetes-sigs/cluster-api-provider-kubemark) has implemented the provider part of the opt-in API for scaling from zero. I recommend using this as a way to test with a live cluster.
```release-note
Added support for scaling to and from zero nodes for the cluster autoscaler's Cluster API provider. Enabling this feature will require changes by the user, for instruction please see the Cluster API (clusterapi) provider README file in the autoscaler repository.
```
- [CAEP]  https://github.com/kubernetes-sigs/cluster-api/blob/release-1.1/docs/proposals/20210310-opt-in-autoscaling-from-zero.md
Usage docs …
=> clusterapi scale from zero support

cluster-autoscaler/cloudprovider/gce/machine_types.go, cluster-autoscaler/cloudprovider/gce/machine_types_test.go
The previous implementation didn't handle machine types with the
"-ext" suffix, or E2 shared-core custom machine types.
=> CA: GCE: fix custom machine type parsing

cluster-autoscaler/FAQ.md
The current documentation uses an old version of cluster-proportional-autoscaler that no longer works in GKE - I suspect this is an issue in other environments as well. Updated documentation will help users start using this feature.
Fixes #
```release-note
NONE
```
```docs
```
=> Update cluster-proportional-autoscaler version in FAQ

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Cherry pick of #4810 on cluster-autoscaler-release-1.22.
#4810: Continue CA loop when unregistered nodes were removed
```release-note
```
=> [release-1.22] Automated cherry pick of #4810: Continue CA loop when unregistered nodes were removed

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Cherry pick of #4810 on cluster-autoscaler-release-1.23.
#4810: Continue CA loop when unregistered nodes were removed
```release-note
```
=> [release-1.23] Automated cherry pick of #4810: Continue CA loop when unregistered nodes were removed

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Cherry pick of #4810 on cluster-autoscaler-release-1.21.
#4810: Continue CA loop when unregistered nodes were removed
```release-note
```
=> [release-1.21] Automated cherry pick of #4810: Continue CA loop when unregistered nodes were removed

vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler_test.go
VPA admission-controller
/kind feature
`validateVPA` is a common function that can be used outside of the `admission-controller/resource/vpa/handler.go`
NONE
=> Export validateVPA to use in other places

cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups.go, cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups_test.go
/kind bug
this change adds labels that are used on Alibaba Cloud and IBM Cloud for
CSI and CCM.
Fixes #
```release-note
```
```docs
```
=> update clusterapi nodegroups processor

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/aws_util_test.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/azure/azure_config_test.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go, cluster-autoscaler/cloudprovider/exoscale/exoscale_cloud_provider_test.go, cluster-autoscaler/cloudprovider/ionoscloud/ionoscloud_manager_test.go
/kind cleanup
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
Reference: https://pkg.go.dev/testing#T.Setenv
```release-note
NONE
```
```docs
```
=> test: use `T.Setenv` to set env vars in tests

cluster-autoscaler/cloudprovider/aws/README.md
remove a duplicated permission in the docs (already in the first block, no need in the second block)
```release-note
NONE
```
=> cluster-autoscaler aws: remove duplicated permissions

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client_test_util.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go
There is no reason for the metric to be exported differently than other metrics
Hyphens in name of the metric caused prometheus errors
VPA recommmender
/kind bug
VPA recommender fails to initialize because we call MustRegister on a metric with an invalid name and the registration fails.
```release-note
NONE
```
=> Export metric_server_response like other VPA recommender metrics

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml, cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/examples/configmap-cloudconfig-example.yaml, cluster-autoscaler/cloudprovider/aws/examples/values-cloudconfig-example.yaml
helm charts
/kind feature
Allow AWS cloud provider to be configured with configuration file e.g endpoints
Fixes #
```release-note
NONE
```
```docs
```
=> helm chart - Allow cloud config path for AWS provider

vertical-pod-autoscaler/builder/Dockerfile
/kind cleanup
* Update go version to 1.18.5 to stay in sync with k8s 1.25: https://github.com/kubernetes/release/issues/2625
* Switch from `go get` to `go install`, as `go get` no longer installs binaries
```release-note
Bump go version to 1.18.5
```
=> Update go version to 1.18.5

vertical-pod-autoscaler/common/version.go
VPA 
Increase VPA versions
```release-note
NONE
```
=> VPA release 0.12.0

cluster-autoscaler/OWNERS
Per https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer:
- member for at least 3 months - **yup, many years now**
- Primary reviewer for at least 5 PRs to the codebase - **yup, 28 so far ([link](https://github.com/pulls?q=is%3Apr+archived%3Afalse+is%3Aclosed+assignee%3Ax13n+created%3A%3E2021-07-01+))**
- Reviewed or merged at least 20 substantial PRs to the codebase - **yup, in addition to the above authored 20 so far ([link](https://github.com/pulls?q=is%3Apr+archived%3Afalse+author%3Ax13n+created%3A%3E2021-07-01+is%3Aclosed))**
- Knowledgeable about the codebase - **yes, but no idea how to prove it here**
- Sponsored by a subproject approver
- With no objections from other approvers - **CC @feiskyer @aleksandra-malinowska @towca for comments**
- Done …
=> Add x13n to cluster autoscaler reviewers

vertical-pod-autoscaler/enhancements/4902-delete-oom-pods/README.md
=> [VPA] KEP-4902: Delete OOM Pods

vertical-pod-autoscaler/hack/run-e2e-tests.sh
With switch to ginkgo v2 timeout are counted differently[1]. With Ginkgo v1
timeout was per-test-suite. Now its for the whole test run. As a result
`actuation` [2] tests for `v1` API are timing out. They take a little more than
60 minutes. For example passing run [3] logs first '[v1]' at 19:30:23.701
and the last one at 20:33:44.510.
[1] https://onsi.github.io/ginkgo/MIGRATING_TO_V2#timeout-behavior
[2] https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#autoscaling-vpa-actuation
[3] https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1564683608667459584/build-log.txt
VPA
/kind bug
/kind cleanup
```release-note
NONE
```
```docs
```
=> Increase timeout for VPA `v1` e2e tests

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/servicemonitor.yaml, charts/cluster-autoscaler/values.yaml
Helm chart for cluster autoscaler
/kind feature
Add support for metricRelabelings in the service monitor in the helm chart, so we could drop metrics we don't care about - to reduce costs
Fixes #
```release-note
Added: support for metricRelabelings in the cluster autoscaler helm chart
```
```docs
```
=> feat: add support for metricRelabelings

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go
Azure VMSS tags allowed character set isn't the exact same as the Kubernetes labels' character set. In particular "/" aren't supported as VMSS tags, but are allowed for Kubernetes labels. To support reflecting label values containing "/" to VMSS tags, the cluster-autoscaler evaluates underscores ("_") in VMSS tags keys as slashes ("/") in nodes labels keys.
But due to that substitution, a node label containing "_" (also a valid character for a k8s label) can't be reflected to VMSS tags (as it will be mis-read as a "/").
This PR takes inspiration from rfc6901's JSON escaping (rather hideous, but possibly familiar as it's used by kubectl-patch), by using ("~2") as a replacement for "_".
The tilde (`~`) character isn't allowed in k8s labels (and taints) keys so there's no possible …
=> Azure: support node label keys having underscores

cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/eligibility/eligibility.go, cluster-autoscaler/core/scaledown/eligibility/eligibility_test.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/simulator/utilization/info.go, cluster-autoscaler/simulator/utilization/info_test.go, cluster-autoscaler/utils/klogx/defaults.go, cluster-autoscaler/utils/klogx/klogx.go
/kind cleanup
One more refactor of existing scale down code in order to make parallel scale down (https://github.com/kubernetes/autoscaler/issues/5079) possible.
Fixes #
```release-note
NONE
```
```docs
```
=> Extract scale down eligibility checking to a separate object

cluster-autoscaler/core/scaledown/eligibility/eligibility.go, cluster-autoscaler/core/scaledown/eligibility/eligibility_test.go
The fact that it only considers nodes as deleted only until a certain timeout is of no concern to the eligibility.Checker.
/kind cleanup
Follow up to comments on https://github.com/kubernetes/autoscaler/pull/5118
Fixes #
```release-note
NONE
```
```docs
```
=> Don't depend on IsNodeBeingDeleted implementation

cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/resource/limits.go, cluster-autoscaler/core/scaledown/resource/limits_test.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go
/kind cleanup
/kind feature
One more refactor of existing scale down code in order to make parallel scale down (https://github.com/kubernetes/autoscaler/issues/5079) possible.
Fixes #
This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5118. Only last 2 commits should be reviewed as a part of this PR. It will be on hold until the previous one is merged.
/hold
```release-note
NONE
```
```docs
```
/assign @MaciekPytel 
/assign @yaroslava-serdiuk
=> Allow simulator to persist changes in cluster snapshot

cluster-autoscaler/core/static_autoscaler.go
Modifying the startup logic to remove taints from all nodes, instead of only the ready nodes.
/kind bug
Removes taints from all nodes to allow for reevaluation during restarts.
Only partial fix of a larger effort to change how deleted cloud provider nodes are identified.
NONE
=> Remove taints from all nodes on startup

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
%v results in a list of numbers when byte array is passed
/kind bug
Fixes #
```release-note
NONE
```
```docs
```
=> Fix error formatting in GCE client

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/recommender/logic/recommender.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
/kind feature
Fixes #4786
```release-note
Add flags to specify recommender name and targetCPUPercentile via command line arguments.
```
```docs
```
=> Move targetCPUPercentile into a flag

vertical-pod-autoscaler/pkg/updater/logic/updater.go
/kind bug
/kind cleanup
The Updater still lists Pods in all namespaces, even when VPA is configured to deal with a single namespace only. Seems like this was missed in https://github.com/kubernetes/autoscaler/pull/3227?
```release-note
Fixed a bug which caused VPA Updater to list Pods in all namespaces, even when VPA was configured to watch a single namespace only.
```
=> Restrict Updater PodLister to namespace

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/hack/generate-crd-yaml.sh
/kind cleanup
Update controller-gen to 0.9.2 and install with `go install`, as `go get` doesn't install binaries anymore with go1.18
Fixes #
```release-note
NONE
```
=> Update controller-gen to 0.9.2

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
/kind cleanup
this change removes some unused values and adjusts the names in the unit tests to better reflect usage.
Fixes #
```release-note
NONE
```
```docs
```
=> cleanup unused constants in clusterapi provider

cluster-autoscaler/core/scaledown/actuation/actuator_test.go
Fix race condition in unit test
=> Fix race condition in scale down test

cluster-autoscaler/processors/customresources/gpu_processor.go, cluster-autoscaler/processors/customresources/gpu_processor_test.go, cluster-autoscaler/utils/gpu/gpu.go
Under Windows the handling for GPU does currently not support ScaleDown since the Node is not treated as Ready.
Other than on Linux the Resource is named `microsoft.com/directx`
/kind feature
Allows GPU accelerated windows nodes to scale down
=> Support for DirectX Devices

.github/workflows/ci.yaml
N/A
/kind bug
This PR fixed the golang version in [ci.yaml](https://github.com/kubernetes/autoscaler/blob/master/.github/workflows/ci.yaml) under GitHub workflows.
Fixes #5204
```
NONE
```
```
NONE
```
=> Updated the golang version for the GitHub workflows.

cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go
/kind bug
The disk size is converted to bytes and then this value is multiplied by the price for 1 GB, which makes the node price to have a wrong value.
=> Remove units for default boot disk size

vertical-pod-autoscaler/e2e/v1/admission_controller.go
VPA admission contoroller
/kind bug
Add E2E tests for behavior described in https://github.com/kubernetes/autoscaler/issues/3966. Fix should make  test cases with limit range behave the way tests without limit range do now.
```release-note
NONE
```
=> E2e test admission pod recommendation mismatch

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
cluster-autoscaler `gce` provider.
/kind bug
If the cluster autoscaler for some reason attempts to delete a cluster that is being deleted/abandoned/etc. the operation will fail. There may be a re-entry bug or maybe some external source has started deleting an instance.
The API will ignore these validation errors and allow the autoscaler to continue processing the other instances that need deletion/removal from the cluster.
Adds the following parameter to the GCP DeleteInstances call:
> skipInstancesOnValidationError
> Specifies whether the request should proceed despite the inclusion of instances that are not members of the group or that are already in the process of being deleted or abandoned. If this field is set to false and such an instance is specified in the request, the operation …
=> [gce]: skip instances on validation error

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
/kind feature
Update the AWS instance type list, adding mac2.metal,r6a Family and r6id Family of instances
Fixes #
I had to run the generator specifying a region (us-east-1) as a workaround for https://github.com/kubernetes/autoscaler/issues/4859.
```release-note
Updated AWS instance types adding support for Mac Metal and r6a and r6is Families
```
```docs
```
=> CA - AWS - Instance List Update 2022-09-16

cluster-autoscaler/cloudprovider/magnum/magnum_openstack_clients.go
We use self-signed certificates in the openstack for test purposes. It is not always easy to bring a CA certificate. And so we ran into the problem that there is no option to not check the validity of the certificate in the autoscaler.
This patch adds a new option for the magnum plugin: tls-insecure
Signed-off-by: Anton Kurbatov <Anton.Kurbatov@acronis.com>
Fixes #
```release-note
```
```docs
```
=> magnum: add an option to create insecure TLS connections

addon-resizer/healthcheck/healthcheck.go, addon-resizer/nanny/main/pod_nanny.go, addon-resizer/nanny/nanny_lib.go
addon-resizer
/kind feature
Adds a handler for HTTP-based health-check in Addon Resizer 1.8.
NOTE: The healthcheck.go is based on VPA code and simplified to fit Addon Resizer better.
By default the handler listens on port 8080, this can be changed with `healthcheck-address` flag (e.g. be setting it to `:8443`).
This allows to set up a liveness probe for the addon-resizer container, for example by adding following section to its yaml:
```
livenessProbe:
httpGet:
path: /health-check
port: 8080
initialDelaySeconds: 10
periodSeconds: 10
```
Should the binary get stuck (or at least 5 times slower than configured), it would be restarted by kubelet.
I'm not sure if this change should also be introduced on master - README says the recommended version is 1.8 but it seems a waste not to have this …
=> Add HTTP health-check to Addon Resizer 1.8

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go
/kind bug
https://github.com/kubernetes/autoscaler/pull/4233 introduced an option to use multiple expanders. However, whenever priority expander is used, but its ConfigMap is not defined or malformed, all subsequent expanders have no effect. This PR changes this behavior and allows subsequent expanders to be used as a fallback in case there are problems with priority expander ConfigMap.
Fixes #
```release-note
Priority expander no longer blocks scale up when its ConfigMap is missing or malformed.
```
```docs
```
=> Don't break scale up with priority expander config

vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go
/kind feature
This PR adds ability to count "replicas" in daemonsets, to prevent massive one-time pod restart  in daemonsets.
Fixes #
```release-note
Added support for counting replicas in deamonsets to limit how fast VPA evicts them.
```
NONE
```docs
```
=> added replicas count for daemonsets to prevent massive pod eviction

cluster-autoscaler/FAQ.md, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go
/kind feature
Extends existing option/feature `new-pod-scale-up-delay` that is global for all the pods and adds ability to specify custom delay per pod through annotation `cluster-autoscaler.kubernetes.io/pod-scale-up-delay`. This allows better control over scale up process in the situations when we are running a lot of batch jobs at the regular intervals, like _run this job every hour, but it is ok to wait 5 minutes to start_. 
There was a discussion on this issue and someone suggested this solution. I liked it, implemented it, and it worked well for what I needed.
https://github.com/kubernetes/autoscaler/issues/3916
```release-note
A new annotation `cluster-autoscaler.kubernetes.io/pod-scale-up-delay` has been added, which allows user to set `new-pod-scale-up-delay` …
```
=> Add podScaleUpDelay annotation support

OWNERS, addon-resizer/OWNERS, builder/OWNERS, cluster-autoscaler/OWNERS, hack/OWNERS, vertical-pod-autoscaler/OWNERS
Entire repository.
/kind cleanup
Inactive reviewers/approvers keep on being mentioned by k8s bot, which ends up discouraging external contributors trying to add improvements. This PR cleans up all OWNERS files according to [Kubernetes guideline](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#cleanup). The only exception is Cluster Autoscaler OWNERS for specific cloud providers: executing the guidlines now would mean removing all people from most of them completely and we are introducing a dedicated policy in https://github.com/kubernetes/autoscaler/pull/5198 already.
Fixes #
This is the list of removed people and their respective Developer Activity counts in kubernetes/autoscaler repository over last year (taken from [this …
=> Clean up stale OWNERS

vertical-pod-autoscaler/e2e/v1/admission_controller.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go, vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
The function should match containers to their recommendations directly instead of hoping thier order will match,
See [this comment](https://github.com/kubernetes/autoscaler/issues/3966#issuecomment-1262159504)
Fixes #3966
VPA admission controller
/kind bug
Fixes #3966
```release-note
Fix bug in VPA admission controller. When:
- List of containers in pod is different than list of container in recommendation (for example as a result of a recent change to pod definition in its controller) and
- Pod was in a namespace with a `LimitRange`
VPA could crash or set container requests incorrectly. Now it sets correct limits and requests.
```
```docs
```
=> Fix accessing index out of bonds

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/expander/factory/expander_factory.go
/kind cleanup
This PR refactors expander factory code to make it reusable. There are no functional changes.
Fixes #
```release-note
NONE
```
```docs
```
=> Make expander factory logic more pluggable

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
/kind cleanup
this change removes the code for the `Labels` and `Taints` interface functions of the clusterapi provider when scaling from zero. The body of these functions was added erronesouly and the Cluster API community is still deciding on how these values will be expose to the autoscaler.
also updates the tests and readme to be more clear about the usage of labels and taints when scaling from zero.
Fixes #
```release-note
```
```docs
```
=> remove unsupported functionality from cluster-api provider

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/drain.go, cluster-autoscaler/core/scaledown/actuation/drain_test.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go, cluster-autoscaler/utils/kubernetes/testlisters.go
/kind bug
This PR addresses a race condition between kube-scheduler and cluster-autoscaler that happens when scaling down nodes. The solution is to taint all the nodes, wait for a period of time and recheck that nodes can safely be drained and deleted. 
Fixes #3886
```release-note
Add `--node-delete-delay-after-taint` flag that controls how long it waits for after tainting a node, before rechecking and deleting the node.
```
=> Add option to wait for a period of time after node tainting/cordoning

cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/unneeded/nodes.go, cluster-autoscaler/core/scaledown/unneeded/nodes_test.go, cluster-autoscaler/simulator/tracker.go, cluster-autoscaler/simulator/tracker_test.go
/kind cleanup
One more refactor of existing scale down code in order to make parallel scale down (https://github.com/kubernetes/autoscaler/issues/5079) possible.
Fixes #
This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5133. Only last 2 commits should be reviewed as a part of this PR. It will be on hold until the previous one is merged.
```release-note
NONE
```
```docs
```
=> Extract criteria for removing unneded nodes to a separate package

cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go
/kind cleanup
Dead code removal.
Fixes #
This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5161. Only last commit should be reviewed as a part of this PR. It will be on hold until the previous one is merged.
```release-note
NONE
```
```docs
```
/hold
=> Remove dead code for handling simulation errors

cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
/kind feature
This PR adds support for extended resources in GCE MIG template. 
Today, the `cluster-autoscaler` on GCE only supports scaling decisions based the following resources: CPU, Memory, EphemeralStorage and GPU. However, Kubernetes allows defining an arbitrary number of resources through the [Extended Resource API](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/). This can be useful when your instances have special resources that you want to share between your pods. One example that I can think of is `network bandwidth`, which cannot be requested by pods except through extended resources.
Some other implementations of the `CloudProvider` interface, like AWS or Azure, already support scaling decisions based on extended resources.
This …
=> Add support for extended resource definition in GCE MIG template

cluster-autoscaler/core/scaledown/eligibility/eligibility.go, cluster-autoscaler/core/scaledown/eligibility/eligibility_test.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/utils/errors/errors.go
/kind feature
Core part of https://github.com/kubernetes/autoscaler/issues/5079 implementation.
Fixes #
This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5161. Only last commit should be reviewed as a part of this PR. It will be on hold until the previous one is merged.
```release-note
NONE
```
```docs
```
/hold
/assign @MaciekPytel @yaroslava-serdiuk
=> Base parallel scale down implementation

cluster-autoscaler/cloudprovider/kamatera/kamatera_api_client_rest.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_utils_test.go
cluster-autoscaler (kamatera cloudprovider)
/kind bug
it changes the dependency used to generate uuid to a more maintained and secure alternative which is already included in the dependencies (`google/uuid`)
Fixes #5218
```release-note
NONE
```
=> cluster autoscaler: kamatera cloud provider - change uuid dependency

cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider_test.go, cluster-autoscaler/cloudprovider/magnum/magnum_manager_impl.go
Addresses issue #5218, that the satori UUID package is unmaintained and has security vulnerabilities
affecting generating random UUIDs.
In the magnum cloud provider, this package was only used to check whether a string matches a UUIDv4 or not, so the vulnerability with generating UUIDs could not have been exploited. (Generating UUIDs is only done in the unit tests).
The gofrs/uuid package is currenly at version 4.0.0 in go.mod, well past point at which it was forked and the vulnerability was fixed. It is a drop in replacement for verifying a UUID, and only a small change was needed in the testing code to handle a new returned error when generating a random UUID.
Cluster autoscaler magnum cloud provider
/kind bug
Removes a dependency with vulnerabilities from the magnum cloud provider …
=> Magnum provider: switch UUID dependency from satori to gofrs

vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/hack/generate-crd-yaml.sh
/kind cleanup
This moves updater and recommender service accounts to the RBAC manifests where the admission controller's is.  That keeps the deployments separate from the RBAC needed for the deployments to work.  Also fixes a small harmless typo in the name of a role binding.
N/A
```release-note
The VPA ClusterRoleBinding `system:vpa-evictionter-binding` has been renamed `system:vpa-evictioner-binding`. After applying the new RBAC manifest, the old one can be removed with `kubectl delete clusterrolebinding system:vpa-evictionter-binding`
```
=> VPA: Fix typo, move service accounts to RBAC

cluster-autoscaler/cloudprovider/aws/OWNERS
Set all aws cloudprovider approvers as reviewers, so that aws-specific PRs can be handled without involving global CA reviewers.
/kind cleanup
Help even PR review load by directing aws-specific reviews to aws cloud provider owners.
Fixes #
```release-note
NONE
```
```docs
```
/assign @jaypipes @gjtempleton @drmorr0
=> Update aws OWNERS

cluster-autoscaler/FAQ.md, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/scaledown/resource/limits.go, cluster-autoscaler/core/scaleup/resource_manager.go, cluster-autoscaler/core/scaleup/resource_manager_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go
/kind feature
The node group size can be smaller than the minimum size configured in cluster-autoscaler, but cluster-autoscaler doesn't support scaling up the cluster to the desired state. Here are 2 common scenarios that could cause this issue.
*  The node group was configured with a smaller min size at the beginning. Later on, the min size was adjusted to a bigger number.
* The node was deleted directly from Kubernetes or the cloud provider.
To support scenarios above, we need this feature to scale up node groups that have less nodes than the configured node group min size.
Fixes #5162
Fixes #4942
This feature is disabled by default. It has been verified in unit tests. I'll also test it in a real cluster.
```release-note
Introduced a new flag …
```
=> Support scaling up node groups to the configured min size if needed

vertical-pod-autoscaler/deploy/vpa-rbac.yaml
Fixes #5298
Use namespace `kube-system` for VPA Service Accounts like it did before #5268
=> Fix VPA deployment

cluster-autoscaler/README.md
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
Adds a few missing supported cloud providers to the main cluster-autoscaler readme and orders them alphabetically for easier scanning.
Fixes #
```release-note
```
```docs
```
=> Add missing cloud providers to readme and sort alphabetically

cluster-autoscaler/cloudprovider/huaweicloud/examples/cluster-autoscaler-deployment.yaml, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager.go, cluster-autoscaler/cloudprovider/huaweicloud/huaweicloud_service_manager_test.go
Signed-off-by: jwcesign <jiangwei115@huawei.com>
/kind feature
huawei-cloudprovider: enable taints resolve for as, modify the example yaml to accelerate node scale-down
Fixes none
none
```release-note
NONE
```
```docs
none
```
=> huawei-cloudprovider: enable taints resolve for as, modify the example yaml to accelerate node scale-down

cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-svcaccount.yaml
Similar change was done in https://github.com/kubernetes/autoscaler/pull/4154
Without these RBAC permissions seeing below in the pod logs:
```
E1024 14:31:11.976758       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler-account" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
E1024 14:31:29.198925       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: csistoragecapacities.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler-account" cannot list …
```
=> Fix: add missing RBAC permissions to magnum examples

cluster-autoscaler/FAQ.md
this change adds a section about how to increase the logging verbosity and why you might want to do that.
Fixes #
```release-note
```
```docs
```
=> add logging information to FAQ

cluster-autoscaler/core/filteroutschedulable/filter_out_schedulable.go, cluster-autoscaler/core/filteroutschedulable/filter_out_schedulable_test.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/scaleup/resource_manager_test.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/scheduling/hinting_simulator.go, cluster-autoscaler/simulator/scheduling/hinting_simulator_test.go, cluster-autoscaler/simulator/scheduling/similar_pods.go, cluster-autoscaler/simulator/scheduling/similar_pods_test.go
/kind cleanup
This PR separates the binpacking logic from the filterOutSchedulablePodsListProcessor. This enables reausability of this code and allows other places in CA to use it.
NONE
=> Use scheduling package in filterOutSchedulable processor

cluster-autoscaler/processors/nodes/pre_filtering_processor.go
/kind cleanup
Minor logs improvement
Fixes #
```release-note
NONE
```
```docs
```
=> Log node group min and current size when skipping scale down

cluster-autoscaler/core/scaledown/planner/controller.go, cluster-autoscaler/core/scaledown/planner/controller_test.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go
Check owner reference in scale down planner to avoid double-counting already deleted and recreated pods.
/kind feature
This PR makes sure that in scale down planner we do not account twice for the pods that have been evicted and already recreated by its higher level controller.
```release-note
```
```docs
```
=> Check owner reference in scale down planner to avoid double-counting

cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/unneeded/nodes.go
/kind feature
Allows filtering of scale down candidates in scale down planner.
```release-note
```
```docs
```
=> Use ScaleDownSetProcessor.GetNodesToRemove in scale down planner to filter  NodesToDelete.

cluster-autoscaler/OWNERS
/kind cleanup
Remove the need to apply `cluster-autoscaler` label manually.
Fixes #
I have no idea how to test this, so decided to create PR, merge it and then verify (& roll back in the worst case).
```release-note
```
```docs
```
=> Automatically label cluster-autoscaler PRs

cluster-autoscaler/FAQ.md
Making a minor document link change in kubernetes autoscaler FAQ.md.
Issue is here: #5332
=> Fix for 'Link for cloud-controller-manager is not working'

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
VPA
/kind cleanup
Fixes #4969
```release-note
autoscaling v1beta2 API is now deprecated.
```
=> Deprecate v1beta1 2

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
The `hcloud-csi-driver` uses the label `csi.hetzner.cloud/location` for topology. This label was not added in the response to `n.TemplateNodeInfo()`, causing cluster-autoscaler to not consider any node group for scaling when a pre-existing volume was attached to the pending pod.
This is fixed by adding the appropriatly named label to the `NodeInfo`. In practice this label is added by the `hcloud-csi-driver`.
Further details on the bug are available in the original issue: https://github.com/hetznercloud/csi-driver/pull/302
```release-note
NONE
```
```docs
```
=> fix(cluster-autoscaler/hetzner): pre-existing volumes break scheduling

cluster-autoscaler/cloudprovider/clusterapi/README.md
cluster-autoscaler takes into consideration the time that a node takes to initialise a GPU resource on a node, as long as a particular label is in place.  This label differs from provider to provider, and is documented in some cases but not for CAPI.
This commit adds a note with the specific label that should be applied when a node is instantiated.
```release-note
NONE
```
=> Add note regarding GPU label for the CAPI provider

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/main.go
/kind feature
Stops node categorisation of nodes into needed/unneeded in scale down logic so that autoscaler loop finishes in timely manner (thus avoiding e.g. cluster-autoscaler being killed by a liveness probe)
Fixes #
```release-note
```
```docs
```
=> Break node categorization in scale down planner on timeout.

cluster-autoscaler/estimator/threshold_based_limiter.go
/kind bug
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Fix int formatting in threshold_based_limiter logs

cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache_test.go
/kind feature
Fixes # 
```release-note
YES. After this PR, when scaling an AWS ASG from 0, the ASG name could be used without any additional work as the NodeSelector.
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: eks.amazonaws.com/nodegroup
operator: In
values:
- XXXXXXX
```
```docs
```
=> aws: add nodegroup name to default labels

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go, vertical-pod-autoscaler/pkg/utils/metrics/admission/admission.go
Sometimes I see admissions that are slower than the rest. Logs indicate that `AdmissionServer.admit` doesn't get slow (it's only part with logging). I'd like to have a metric which will tell us what's slow so that we can maybe improve that.
I considered adding a label to existing metric but I think this approach is better:
- existing metric stays the same
- we get metric that's the same for all 3 VPA comonents
VPA Admission Controller
```release-note
Export execution_latency_seconds metric from VPA admission controller
```
=> Export execution_latency_seconds metric from VPA admission controller

cluster-autoscaler/FAQ.md
The real reason for this PR is to check whether https://github.com/kubernetes/autoscaler/pull/5348 will cause `cluster-autoscaler` label to be applied automatically.
Fixes #
```release-note
```
```docs
```
=> Add missing dot

cluster-autoscaler/core/podlistprocessor/currently_drained_nodes.go, cluster-autoscaler/core/podlistprocessor/currently_drained_nodes_test.go, cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go, cluster-autoscaler/core/podlistprocessor/filter_out_schedulable_test.go, cluster-autoscaler/core/podlistprocessor/pod_list_processor.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/pod/pod.go, cluster-autoscaler/utils/pod/pod_test.go, cluster-autoscaler/utils/test/test_utils.go
/kind feature
This PR adds pods from nodes undergoing scale-down to unschedulable pods. Thanks to that we can quickly detect if these pods can schedule on exisiting nodes in the cluster and trigger scale-up as needed.
This PR additionally removed similar logic from the scale-down to avoid pod duplication.
```release-note
NONE
```
=> Add pods from node undergoing scale-down to unschedulable pods

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/_helpers.tpl
Remove warning of policy/v1beta1 deprecation
```
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodSecurityPolicy
```
Reference:
- https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v116
=> Support policy/v1 for PodSecurityPolicy for v1.21+ 

cluster-autoscaler/cloudprovider/rancher/rancher_clusterapi.go, cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup.go, cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup_test.go, cluster-autoscaler/cloudprovider/rancher/rancher_provider.go, cluster-autoscaler/cloudprovider/rancher/rancher_provider_test.go
/kind bug
Previsouly the rancher provider tried to parse the node `spec.providerID` to extract the node group name. Instead, we now get the machines by the node name and then use a rancher specific label that should always be on the machine. This should work more reliably for all the different node drivers that rancher supports.
Fixes #5140
```release-note
NONE
```
```docs
```
=> rancher-cloudprovider: Improve node group discovery

cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/get_work_request_request_response.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/list_work_request_errors_request_response.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/list_work_request_logs_request_response.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/list_work_requests_request_response.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/work_request.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/work_request_error.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/work_request_log_entry.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/work_request_resource.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/work_request_summary.go, cluster-autoscaler/cloudprovider/oci/oci-go-sdk/v43/workrequests/workrequests_workrequest_client.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool_cache.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool_manager.go, cluster-autoscaler/cloudprovider/oci/oci_instance_pool_manager_test.go, cluster-autoscaler/cloudprovider/oci/oci_ref.go, cluster-autoscaler/cloudprovider/oci/oci_shape.go, cluster-autoscaler/cloudprovider/oci/oci_shape_test.go
cluster-autoscaler (OCI provider) 
/kind feature
This PR adds support to the [OCI provider for Instance Pools](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/oci/README.md#cluster-autoscaler-for-oracle-cloud-infrastructure-oci) to _fail fast_ (and potentially _recover_ fast) when an underlying instance-pool for a node-group has run out of quota / capacity.  
It accomplishes this by taking a similar approach to [this PR](https://github.com/kubernetes/autoscaler/pull/4489) where it monitors the cloud-providers [work request queue](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/workrequestoverview.htm) for errors relating to capacity/quota, and quickly fails any on-going scale-up operation if they are detected. Additionally, it creates …
=> oci provider: fail fast, recover fast, when instance-pool/node-group is out of capacity

cluster-autoscaler/cloudprovider/POLICY.md
This is an initial proposal for a policy on cloudprovider maintenance discussed in a recent sig-meeting.
The policy largely codifies what we've already been doing for years (including the requirements we've already imposed on new providers). It also introduces a new 'cloudprovider maintenance request' mechanism, following the general idea previously discussed in the sig-meeting.
```release-note
NONE
```
This policy is only relevant for CA / cloudprovider developers and not its users.
=> Introduce a formal policy for maintaining cloudproviders

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml
Autoscaler 1.25.0 adds "rancher" cloud provider support, it requires setting cloudConfigPath. If the user mounts this as a secret and sets this value appropriately, this change sets the argument required to point to the mounted secret. Previously, this was only set if cloud provider was magnum or aws.
cluster-autoscaler (helm chart)
/kind feature
adds support for the rancher cloud provider added in 1.25.0 to pass its config file
Fixes #
Not directly, just supports using an existing Helm value in the right place
```docs
```
=> feat(helm): add rancher cloud config support

cluster-autoscaler/OWNERS
I'm nominating @x13n as CA approver, folliwing the process outlined in https://github.com/kubernetes/community/blob/master/community-membership.md#approver. 
- https://github.com/kubernetes/autoscaler/pull/5354
- https://github.com/kubernetes/autoscaler/pull/5333
- https://github.com/kubernetes/autoscaler/pull/5330
- https://github.com/kubernetes/autoscaler/pull/5290
- https://github.com/kubernetes/autoscaler/pull/5284
- https://github.com/kubernetes/autoscaler/pull/5259
- https://github.com/kubernetes/autoscaler/pull/5235
- https://github.com/kubernetes/autoscaler/pull/5195
- https://github.com/kubernetes/autoscaler/pull/5115
- https://github.com/kubernetes/autoscaler/pull/4970
https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+commenter%3Ax13n+-author%3Ax13n+ shows 77 PRs right …
=> Add x13n to cluster autoscaler approvers

cluster-autoscaler/cloudprovider/POLICY.md
cluster-autoscaler 
This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5198, separating new policy proposal into a separate PR.
=> Introduce Cloudprovider Maintenance Request policy

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go
Signed-off-by: yasin.lachiny <yasin.lachiny@gmail.com>
bug
This PR will solve [#4703](https://github.com/kubernetes/autoscaler/issues/4703) ,  [#5250](https://github.com/kubernetes/autoscaler/issues/5250) , and  [#5305](https://github.com/kubernetes/autoscaler/issues/5305)
`cluster_autoscaler_max_nodes_count` is an env we can set it manually but we can calculate it dynamically by looping through all node groups and counting the `MaxSize` of each node group
Fixes [#4703](https://github.com/kubernetes/autoscaler/issues/4703)
Fixes  [#5305](https://github.com/kubernetes/autoscaler/issues/5305)
Fixes [#5250](https://github.com/kubernetes/autoscaler/issues/5250)
NONE
```release-note
```
```docs
```
=> set cluster_autoscaler_max_nodes_count dynamically

cluster-autoscaler/cloudprovider/aws/README.md
Cluster-autoscaler AWS cloudprovider IAM policy docs - adds an action from the minimal policy to the "all actions" policy. Note that this functionality actually fails silently if not added to the IAM permission so users may be unaware their CA is not using this functionality.
It's also pulled in some unrelated trailing whitespace trimming as I have the chart pre-commit hooks installed.
Fixes #
```release-note
NONE
```
```docs
```
=> CA - AWS - Update Docs all actions IAM policy

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/main.go
/kind bug
This PR moves the initialization of PredicateChecker before the processors initialization. It is needed because FilterOutSchedulable now depends on the PredicateChecker, resulting in seg faults
Fixes #5378
NONE
=> Move PredicateChecker initialization before processors initialization

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/aws_sdk_provider.go
/kind feature
atm aws fails after 3 retries since we use the default config, which leads to backoffs, which leads to clusters not scaling as requested
```release-note
- support AWS_MAX_ATTEMPTS to configure max retries
```
=> aws: allow setting max retries from AWS_MAX_ATTEMPTS env var

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go
/kind feature
```
CA Waited for 191.285161ms due to client-side throttling, not priority and fairness, request: POST:[https://172.29.4.1:443/api/v1/namespaces/kube-system/events
```
- we currently see lots of rate limiting from the kubernetes client of CA, we'd like to give it more QPS to avoid that
- users might want to reduce the number of queries that CA does against their cluster
```release-note
- add `--kube-client-burst` and `--kube-client-qps` to control how many requests CA can do against kubernetes
```
=> cluster-autoscaler: allow setting kuberentes client burst and qps to avoid rate limiting

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/main.go
Cherry pick of #5388 on cluster-autoscaler-release-1.26.
#5388: Move PredicateChecker initialization before processors
=> Automated cherry pick of #5388: Move PredicateChecker initialization before processors

cluster-autoscaler/version/version.go
Bump CA version for a new 1.26 patch release.
=> Cluster Autoscaler 1.26.1

vertical-pod-autoscaler/FAQ.md, vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/cpu_integer_post_processor.go, vertical-pod-autoscaler/pkg/recommender/routines/cpu_integer_post_processor_test.go
vertical-pod-autoscaler/recommender
/kind feature
It introduces a recommendation post processor that allows users to have a CPU integer as recommendation.
Thanks to that it is now possible to use VPA with applications using [CPU management with static policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy)
Fixes #5236
As discussed during the SIG meeting the user interface is based on an annotations. This could be structured in the spec of the VPA once the feature will have gained maturity.
The "cpu integer post-processor" can be enabled using flag `--cpu-integer-post-processor-enabled=true` when starting the VPA recommender.
The post-processor would round-up CPU recommendation for containers referenced by a VPA annotation with this format: …
=> recommendation post processor for integer CPU

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go, cluster-autoscaler/processors/nodegroupset/aws_nodegroups_test.go, cluster-autoscaler/processors/nodegroupset/azure_nodegroups.go, cluster-autoscaler/processors/nodegroupset/azure_nodegroups_test.go, cluster-autoscaler/processors/nodegroupset/balancing_processor_test.go, cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups.go, cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups_test.go, cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go, cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go, cluster-autoscaler/processors/nodegroupset/gce_nodegroups.go, cluster-autoscaler/processors/nodegroupset/nodegroup_set_processor.go, cluster-autoscaler/processors/processors.go
/kind feature
Allows us to adjust difference ratios and configure the balance of nodegroupsets.
Fixes #5381
```release-note
Adding 3 Flags to CA. 
maxCapacityMemoryDifferenceRatio   = flag.Float64("memory-difference-ratio", 0.015, "Maximum difference in memory capacity between two similar node groups to be considered for balancing. Value is a ratio of the smaller node group's memory capacity.")
maxFreeDifferenceRatio             = flag.Float64("max-free-difference-ratio", 0.05, "Maximum difference in free resources between two similar node groups to be considered for balancing. Value is a ratio of the smaller node group's free resource.")
maxAllocatableDifferenceRatio      = flag.Float64("max-allocatable-difference-ratio", 0.05, "Maximum difference in allocatable resources between two …
```
=> adding configurable difference ratios

vertical-pod-autoscaler/enhancements/4902-delete-oom-pods/README.md
/kind cleanup
/kind feature
Discussed on SIG meeting on 2022-11-21 and 2022-11-21, see [meeting notes](https://docs.google.com/document/d/1RvhQAEIrVLHbyNnuaT99-6u9ZUMp7BfkPupT2LAZK7w/edit#heading=h.bymi5lfbsup2).
=> Mark VPA KEP 4902 as deprecated in favor of using PDB feature

cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml
/kind bug
This PR added the missing RBAC permission in the [examples](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-standard.yaml) mentioned under the alicloud Cloud Provider.
Fixes #5413
NONE
```
NONE
```
=> Added the RBAC Permission to alicloud.

cluster-autoscaler/cloudprovider/aws/aws-sdk-go/private/protocol/host.go
/kind feature
This PR added the link for RFC3986 in [`host.go`](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws-sdk-go/private/protocol/host.go) code under  [`aws CloudProvider`](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws).
Fixes #5424
```
NONE
```
=> Added link for RFC3986 in host.go code.

cluster-autoscaler/core/scaledown/resource/limits.go, cluster-autoscaler/core/scaleup/resource_manager.go
/kind cleanup
Some error messages related to custom resources assumes that the custom resource is always GPU. Rephrasing these error messages to clear up any confusion.
```release-note
NONE
```
```docs
```
=> Rephrase error messages specific for GPUs.

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/utils/utils.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/utils/daemonset/daemonset.go, cluster-autoscaler/utils/daemonset/daemonset_test.go
/kind cleanup
Clean up unused logic in DS utils. This looks like an artifact from the previous implementation which simulated the DS pods scheduling.
```release-note
NONE
```
=> Clean up DS utils: remove unused cluster snapshot and predicate checker

cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-config.yaml, cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-principals.yaml
OCI OKE auto scaler requires an updated set of permissions. 
This PR changes the default permissions needed to run OCI OKE auto scaler examples.
=> OCI OKE autoscaller requires Updated Set of permissions. 

cluster-autoscaler/core/podlistprocessor/filter_out_daemon_sets.go, cluster-autoscaler/core/podlistprocessor/filter_out_daemon_sets_test.go, cluster-autoscaler/core/podlistprocessor/pod_list_processor.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go
/kind feature
This PR improves the way the CA handles unschedulable DS pods. These pods are unhelpable from the scale-upside, as each of them can only get scheduled on a specific existing node. Currently these pods are passed to scale-up logic, which increases the computational complexity, even though we know it is unnecessary.
This change filters out pending DS pods, which solves the described issue. It additionally refactors the defaultPodListProcessor to make it more readable. 
```release-note
Pending Daemon Set pods will no longer emit scale up events
```
=> Add filtering out DS pods from scale-up, refactor default pod list processor

vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go, vertical-pod-autoscaler/e2e/v1/full_vpa.go, vertical-pod-autoscaler/pkg/recommender/routines/vpa.go
/kind bug
Stop filtering `aggregatedContainerState`s with `TotalSampleCount==0`. These `aggregateContainerState`s *can* contain OOMSamples, which don't increase the `TotalSampleCount` but make it possible to give a better memory recommendation. This change also increases the timeout for the OOMKill e2e test as it takes ~10 minutes for the recommendations to reach the expected range.
Fixes #4981 
I'm not entirely sure if there is a good reason why `aggregateContainerStates` without PodMetric samples were ignored besides trying to optimize. Maybe someone else has context if there's an additional reason behind it why we shouldn't be removing this condition?
I looked at other options to solve this, but they seem much more complicated. 
The VPA is built with the …
=> Stop filtering aggregatedContainerStates without samples

vertical-pod-autoscaler/common/version.go
Increase VPA version for 0.13.0 release
#5355
=> VPA release 0.13.0

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml, cluster-autoscaler/cloudprovider/azure/azure_client.go, cluster-autoscaler/cloudprovider/azure/azure_config.go
/kind feature
It adds support for workload identity to the cluster autoscaler on azure
None
```release-note
Added support for workload identity on azure to the cluster autoscaler 
```
=> Added support for azure workload identity

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
/kind bug
Returns a temporary fake provider ID for Machines which have not been fulfilled by the backing cloud provider. Without an ID the nodes confuse the cluster autoscaler, it believes they can fit pods, but it does not account for the node as part of the nodegroup. This change allows the cluster state registry in the cluster autoscaler to correctly track these unprovisioned nodes and detect if they become "long unregistered" and back off the nodegroup.
Fixes #5417
N/A
```release-note
NONE
```
```docs
```
=> clusterapi: track upcoming unprovisioned machines with a temporary providerID to enable detection of exhausted nodegroups

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
/kind feature
Updates the clusterapi provider to support an additional capacity annotation for ephemeral disk capacity on MachineDeployments to supply information about the nodegroup shape.
Without an ephemeral disk capacity supplied, workloads that request ephemeral disk will not trigger a scale up of nodegroups with zero replicas as the ephemeral disk capacity defaults to zero bytes.
Fixes #
```release-note
Added support for supplying ephemeral disk capacity when scaling to and from zero nodes for the cluster autoscaler's Cluster API provider. Enabling this feature will require changes by the user, for instruction please see the Cluster API (clusterapi) provider README file in the autoscaler repository.
```
```docs
```
=> clusterapi: Add ephemeral disk capacity annotation for scale from zero

cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/scaleup/resource_manager_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodeinfosprovider/annotation_node_info_provider.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/processors/nodeinfosprovider/node_info_provider_processor.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/simulator/nodes.go, cluster-autoscaler/simulator/nodes_test.go
/kind feature
This PR adds an optional feature that force-schedules all Daemon Set pods on node group templates. That means that node groups which cannot schedule all the expected daemon sets (eg. because of small nodes) will no longer be chosen during scale-up. 
The change is disabled and guarded by a manifest flag, so it should not have any effect on the component yet.
=> Add force Daemon Sets option

.github/workflows/pr.yaml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
/kind feature
Update `pr.yaml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: |
changed=$(ct list-changed)
if [[ -n "$changed" ]]; then
echo "::set-output name=changed::true"
fi
```
**TO-BE**
```yml
run: |
changed=$(ct list-changed)
if [[ -n "$changed" ]]; then
echo "changed=true" >> …
```
=> Replace deprecated command with environment file

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper.go
There's a small time window between the moment the cluster's ASG list is refreshed (happens at main loop start, cached for 1mn), and the moment when expired (or new) per ASG instance-types cache entries are fetched again from ASG's LaunchConfigurations.
An ASG's LauchConfiguration might have been replaced during that window; in which case attempts to refresh that ASG instance-type would use the stale -possibly deleted- LC name we got when we last listed ASGs, which is probably acceptable as long as we're converging at next ASG refresh deadline (at most 1mn in the future).
AWS DescribeLaunchConfigurations API would not fail if some of the provided LaunchConfigurationNames are missing from the result set (eg. because it was replaced and deleted after we last refreshed ASGs definitions). …
=> AWS: don't cache empty instance-types from stale LC names

cluster-autoscaler/cloudprovider/brightbox/OWNERS, cluster-autoscaler/cloudprovider/brightbox/README.md, cluster-autoscaler/cloudprovider/brightbox/brightbox_cloud_provider.go, cluster-autoscaler/cloudprovider/brightbox/brightbox_node_group.go, cluster-autoscaler/cloudprovider/brightbox/brightbox_node_group_test.go
cluster-autoscaler/cloudprovider/brightbox
Allows autoscaled servers to be members of further server groups in addition to the default and the scaling group.
```release-note
The Brightbox provider now recognises an 'additional_groups' key in the configuration ConfigMap.
No changes are required by provider users unless they wish to take advantage of the additional
functionality. 
```
=> cluster-autoscaler: support additional Brightbox server groups

vertical-pod-autoscaler/builder/Dockerfile
=> Update go used to build VPA to 1.19.5

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/utils/utils.go, cluster-autoscaler/simulator/clustersnapshot/basic.go, cluster-autoscaler/simulator/clustersnapshot/clustersnapshot.go, cluster-autoscaler/simulator/clustersnapshot/delta.go
/kind bug
Stop scale-down from considering registered upcoming nodes as candidates.
```release-note
Fixed a bug where Cluster Autoscaler would sometimes delete recently created nodes while they were still booting up.
```
=> Stop scale-down from considering registered upcoming nodes as candidates

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/_helpers.tpl
/kind bug
For kube versions more recent than 1.21, when enabling PSP, the `apiVersion` generated is empty, resulting in an invalid `PodSecurityPolicy`
Fixes #5499 
```release-note
NONE
```
```docs
```
=> Fixes template for PSPs api version.

balancer/OWNERS
This will automatically apply labels to PRs which makes it easier to search for relevant PRs, without adding any toil
/kind cleanup
=> Automatically apply `balancer` label to balancer PRs

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/_helpers.tpl
/kind bug
Make sure to use `apiVersion: policy/v1beta1` for PodSecurityPolicy when kubernetes version is above 1.10. This fix will work (with a deprecation warning) for cluster version below 1.25 when psp is removed.
Fixes #5364
NONE
NONE
=> fix: issue with apiVersion not being set  for psp

cluster-autoscaler/core/scaledown/unneeded/nodes.go, cluster-autoscaler/core/scaledown/unneeded/nodes_test.go
/kind bug
For parallel scale down we might scale down below min size of the node group because RemovableAt() verify each node individually. This PR add verification for set of nodes.
=> Check min size of node group and resource limits for set of nodes

cluster-autoscaler/core/scaledown/unneeded/nodes.go
Decrease node group size only if the node pass resource check for scale down candidate.
/kind bug
=> Fix RemovableAt()

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
/kind cleanup
This change removes an `if` statement that was left behind after a refactor. The test in question has the same logic embedded into a previous conditional and the removed statement has no effect on the tests.
```release-note
NONE
```
=> remove dead code in clusterapi provider tests

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
/kind feature
Bump up CA chart image tag and appVersion to `1.24.0`.
CA Helm chart `9.24.0` was released, but the associated `image.tag`, `appVersion` are still `1.23.0`.
Fixes #5386
```release-note
Update CA Chart's `appVersion` and `image.tag` value from 1.23 to 1.24
```
```docs
```
=> Bump CA chart to 1.24

cluster-autoscaler/FAQ.md
/kind cleanup
- update FQA to add version in the pause container image due to the latest that is not valid
the tag `latest` for the `pause` container is outdated and in the k8s project we don't promote/create `latest tags`, this might be an old one.
update the doc to use the last release of the `pause` container.
/assign @maciekpytel @mwielgus 
cc @BenTheElder 
Fixes #
```release-note
NONE
```
```docs
```
=> update FAQ.md to add version in the pause container image due the latest that is not valid

cluster-autoscaler/core/scale_up.go, cluster-autoscaler/core/scale_up_test.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/utils/gpu/gpu.go
/kind feature
Add a resource_name field to scaled_up/down_gpu_nodes_total to differentiate between different types of GPU, which are represented by different custom resource. Credit to @hbostan for the implementation.
```release-note
Add breakdown by custom resource name to GPU-related metrics
```
```docs
```
=> Add "resource_name" to scaled_up_gpu_nodes_total and scaled_down_gpu_nodes_total metrics

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
/kind feature
Updates the clusterapi provider to use label or taint capacity annotations on MachineDeployments to supply information about the nodegroup shape when the nodegroup replicas are scaled to zero. 
Currently, the clusterapi provider does not support nodegroup shapes with labels or taints and scaling up from zero replicas, which can cause nodegroups to be skipped in evaluation and fail to scale up. This scenario occurs when a pod is created that tolerates the nodegroup's taints and has a node selector that can only be satisfied by those nodegroups. The cluster-autoscaler needs the taint and label information about a nodegroup to correctly match such a pod to the nodegroup.
Fixes #
```release-note
Added support for supplying labels and taints when scaling to and …
```
=> Use annotations to set labels and taints for clusterapi nodegroups

cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/legacy/wrapper.go, cluster-autoscaler/core/scaledown/pdb/basic.go, cluster-autoscaler/core/scaledown/pdb/basic_test.go, cluster-autoscaler/core/scaledown/pdb/pdb.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/scaledown/scaledown.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/simulator/drain.go
/kind cleanup
This PR adds PDBRemainingDisruptions struct to AutoscalingContext, enabling remaining PDB tracking throughout the CA.
```release-note
NONE
```
=> Track PDBRemainingDisruptions in AutoscalingContext

cluster-autoscaler/core/static_autoscaler.go
/kind bug
In #4926, @bpineau have fixed the panic issue in `deleteCreatedNodesWithErrors`, but CA is still not working until instance cache in clusterstateregistry is refreshed， which may up to 2min.
This PR sync up the instance cache with cloud provider.
Fixes #
```release-note
NONE
```
```docs
```
=> fix(*): refresh node instance cache when nodegroup not found in deleteCreatedNodesWithErrors

cluster-autoscaler/cloudprovider/cherryservers/examples/cluster-autoscaler-rbac.yaml, cluster-autoscaler/cloudprovider/cherryservers/examples/cluster-autoscaler-svcaccount.yaml
/kind bug
This PR added the missing RBAC permission in the [examples](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/cherryservers/examples) mentioned under the cherryservers Cloud Provider.
Fixes #5511
```
NONE
```
=> Added RBAC Permission to cherryservers.

cluster-autoscaler/core/podlistprocessor/currently_drained_nodes_test.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/legacy/wrapper.go, cluster-autoscaler/core/scaledown/scaledown.go, cluster-autoscaler/core/static_autoscaler.go
The `scaledown:nodedeletion` is improperly tracking the actual time required for scheduling node deletions. It's using the `currentTime` as a reference point for the duration, which is set at the start of `RunOnce`.  Long duration activities like a long cloud provider refresh result in this metric being skewed and essentially tracking similar quantiles to that of `main`.
This change moves the start time inside of `StartDeletion` (similar to how `TryScaleDown` tracked the metric in 1.24), so the metric now more directly tracks the duration of `StartDeletion`
The quantiles for `scaledown:nodedeletion` very closely track those of `main`
The quantiles for `scaledown:nodedeletion` are no longer skewed alongside `main` 
/kind bug
Fixes an issue where the `scaledown:nodedeletion` metric was …
=> Fix scaledown:nodedeletion metric calculation

vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
Seems like the example in `/vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml` copied `Deployment` name from `recommender-deployment-high.yaml`. It is referenced from `vertical-pod-autoscaler/README.md`.
```release-note
NONE
```
=> Fix multiple recommenders example: deployment name

cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/scaledown/unremovable/nodes.go, cluster-autoscaler/core/scaledown/unremovable/nodes_test.go, cluster-autoscaler/main.go
/kind bug
Added label for outer loop and break outer loop if the timer send signal. Before CA did nothing and didn't have any limit for scale down simulation. 
Also, I modified the default value for scaleDownSimulationTimeout flag, because 30 seconds is enough to process ~1000 non empty nodes and in the same time cluster snapshot is not too old comparing to the snapshot for 5 minutes timeout.
=> Fix RemovalSimulation for parallel scale down

cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go
This is an optimization to avoid spending too much time in scale down simulation. The main idea is that it doesn't make sense to add new unneeded nodes at a rate that is higher than the rate at which we can delete them afterwards.
Faster scale down in large clusters.
Fixes #
```release-note
NONE
```
```docs
```
=> Limit the rate of adding new uneeded nodes

cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/deletiontracker/nodedeletiontracker.go, cluster-autoscaler/core/scaledown/scaledown.go
/kind bug
Node deletions happens in separate go routine, so it's possible that node was removed during unneeded node verification. In such case we have updated number of ongoing deletions but outdated size of the node group, so CA will have wrong verification of min size of the node group.
=> Use snapshot of NodeDeletionTracker for ActuationStatus

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml, cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml
Hello,
Since some security parameters aren't configurable in [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#podsecuritycontext-v1-core) I introduced a new [container Security Context](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#securitycontext-v1-core) to add security best practices.
- container is now immutable (file integrity guaranteed): readOnlyRootFilesystem
- remove rights the application doesn't need: allowPrivilegeEscalation+capabilities
This follow the least privilege principle in security. Configuration recommanded by scanners such as [kubescape](https://github.com/armosec/kubescape).
Tested in my EKS 1.21 cluster with `cluster-autoscaler-autodiscover.yaml` using container image v1.22. I don't see anything wrong …
=> [CA] [AWS examples] Add container securityContext

cluster-autoscaler/cloudprovider/kubemark/kubemark_other.go
/kind bug
#5459 missed importing the `utils/gpu` package in the `kubermark_other.go` file even though it calls `gpu.GetNodeGPUFromCloudProvider(kubemark, node)`.
For me this causes `make test-unit` to fail locally with an import error. I'm not sure how it made it through CI and why it's not breaking others...
N/A
```release-note
NONE
```
=> cluster-autoscaler: add missing import to kubermark_other.go

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/templates/podsecuritypolicy.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
Adds the ability to configure the `hostNetwork` setting.
Fixes #
Some context about `hostNetwork` is taken from here: https://alesnosek.com/blog/2017/02/14/accessing-kubernetes-pods-from-outside-of-the-cluster/
```release-note
Adds `hostNetwork` parameter
```
```docs
```
=> Re-sort on root level, add `hostNetwork` parameter

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/eligibility/eligibility.go, cluster-autoscaler/core/scaledown/eligibility/eligibility_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/main.go, cluster-autoscaler/simulator/cluster.go
Add flag '--scale-down-unready-enabled' to enable or disable scale-down of unready nodes. Default value set to true for backwards compatibility (i.e., allow scale-down of unready nodes).
Cluster Autoscaler
/kind feature
This PR adds the option to disable scale down for unready nodes. 
There are cases where a user may not want the unready nodes to be removed from a cluster.
As an example, but not limited to, this might be useful in case a node is unreachable for a period of time and local data live there, the node shall remain in the cluster, and possibly an admin may want to take any actions for recovering it.
Fixes #4876.
```release-note
Set the --scale-down-unready-enabled flag to a false in order to disable scale-down for unready nodes. The default value is true for backwards …
```
=> cluster-autoscaler: Add option to disable scale down of unready nodes

vertical-pod-autoscaler/pkg/recommender/model/container.go
/kind cleanup
Cleans up two things in recommender/model/container.go
* remove unused constants, which is a leftover of making OOM Bump up configurable in #5275
* remove custom `truncate` method in favor of using the [built-in method which was introduced with go 1.9](https://pkg.go.dev/time#Duration.Truncate)
```release-note
NONE
```
```docs
```
=> Cleanup recommender model/container.go

cluster-autoscaler/main.go, cluster-autoscaler/processors/scaledowncandidates/emptycandidates/empty_candidates_sorting.go, cluster-autoscaler/processors/scaledowncandidates/emptycandidates/empty_candidates_sorting_test.go, cluster-autoscaler/processors/scaledowncandidates/previouscandidates/previous_candidates_sorting.go, cluster-autoscaler/processors/scaledowncandidates/previouscandidates/previous_candidates_sorting_test.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_sorting_processor.go, cluster-autoscaler/processors/scaledowncandidates/sorting_processor.go, cluster-autoscaler/processors/scaledowncandidates/sorting_processor_test.go
This is an optimisation for parallel scale down to check empty nodes first. Currently CA can simulate drain node by scheduling pods on empty nodes and so CA may prefer draining node over removing the empty one.
/kind feature
=> Add empty nodes sorting for scale down candidates

cluster-autoscaler/FAQ.md
Adds the flag required to enable the [debugging snapshotter](https://github.com/kubernetes/autoscaler/pull/4552/files) to the documented CLI flags. 
Fixes #
```release-note
NONE
```
```docs
```
=> CA - Document Debugging Snapshotter flag

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
Also export the GetErrorInfo function which maps
GCE response to correct error class.
/kind cleanup
/kind bug-fix
Simplifies the FetchMigInstances function and moves the error handling to a dedicated function. \
This makes writing of the custom GCE client easier. 
There is also a commit, which changes the handling of the situation, when there is an issue parsing instance url. \
Previously it resulted in the whole call failing (and by extension whole CA loop failure), now an error will be logged and the instance skipped.
If both changes are ok, I will squash the commit into one. 
Otherwise I can split the one that changes CA behaviour to another PR.
=> Simplify the GCE client FetchMigInstances function.

cluster-autoscaler/FAQ.md
https://github.com/kubernetes/autoscaler/blame/master/cluster-autoscaler/FAQ.md#L412 is wrong and confusing the default is -10 https://github.com/kubernetes/autoscaler/blob/63b334f81a8820511c835401e0133d242d84da08/cluster-autoscaler/main.go#L186 so no need for an extra step
```release-note
NONE
```
=> docs: fix faq around expendable-pods-priority-cutoff

cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_manager.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_manager_test.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_provider.go
/kind bug
Fixes a crash occurring in the ovhcloud provider code, due to a concurrent read/write access to a map.
This fix has already been released in production for the cluster-autoscaler instances running on the OVHcloud Managed Kubernetes product.
=> ovhcloud: Fix panic on concurrent map read/write

cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group.go
/kind bug
Adding a mutex on NodeGroup.DeleteNodes will prevent outdated/conflicting scale down payloads, which result in rejected calls.
This fix has already been released in production for the cluster-autoscaler instances running on the OVHcloud Managed Kubernetes product.
```release-note
- Fix deletion of multiple nodes at the same time
```
=> ovhcloud: Fix deletion of multiple nodes at the same time

cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group.go, cluster-autoscaler/cloudprovider/ovhcloud/ovh_cloud_node_group_test.go, cluster-autoscaler/cloudprovider/ovhcloud/sdk/nodepool.go
/kind feature
Allows the autoscaler to scale up an empty OVHCloud nodepool with specific templating (e.g. labels) that is needed to accommodate the Pending pods.
The templating was not taken into account when generating the node upscale simulation, which resulted in errors of the following kind:
```
Pod runner-t7kqpv4z-project-2-concurrent-0swpm6 can't be scheduled on gitlab-runner-pool-small, predicate checking error: node(s) didn't match Pod's node affinity/selector; predicateName=NodeAffinity; reasons: node(s) didn't match Pod's node affinity/selector
```
With this PR the simulation is closer to the truth and the node group is successfully scaled up by the autoscaler.
This fix has already been released in production for the cluster-autoscaler instances running on the OVHcloud Managed …
=> ovhcloud: Add support for nodepool templating

cluster-autoscaler/cloudprovider/azure/azure_client.go
/kind bug
This change provides correct endpoint/baseURI to the skuClient based on the cloud environment.
By default, endpoint always pointed to public cloud. If the environment was not cloud, sku Cache creation fails and CA pod crashes.
Fixes #
yes, CA pod will no longer crash.
```release-note
Cluster autoscaler will work correctly without crash in non-public clouds.
```
```docs
```
=> baseURI for skuClient based on cloud

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
/kind cleanup
Sets the `User-Agent` for requests made to the Hetzner Cloud API. This helps us find any misbehaving API clients.
```release-note
NONE
```
```docs
```
=> fix(ca/hetzner): specify application name & version

cluster-autoscaler/cloudprovider/azure/azure_client.go
/kind bug
cherry-pick #5603
This change provides correct endpoint/baseURI to the skuClient based on the cloud environment.
By default, endpoint always pointed to public cloud. If the environment was not cloud, sku Cache creation fails and CA pod crashes.
Fixes #
yes, CA pod will no longer crash.
```release-note
Cluster autoscaler will work correctly without crash in non-public clouds.
```
```docs
```
=> baseURI for skuClient based on cloud cherry-pick #5603

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
/kind cleanup
Cleans up code in the cluster-api cluster-autoscaler backend, in particular handling ignored errors. Also makes other small changes suggested by golangci-lint.
N/A
```release-note
NONE
```
=> [cluster-api] Handle ignored errors

cluster-autoscaler/cloudprovider/gce/machine_types.go, cluster-autoscaler/cloudprovider/gce/machine_types_test.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> GCE: Fallback f1 and g1 machine families to n1

cluster-autoscaler/FAQ.md, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
~**This PR is still WIP. I will mention the reviewers here once I am done. Although it might not be in the best shape as a WIP PR but if the reviewers have any feedback, I would love to have it. :pray:**~
/kind feature
- scale down [is blocked](https://github.com/kubernetes/autoscaler/blob/73d02f1d641a38314e93077d375d80e03468ad60/cluster-autoscaler/utils/drain/drain.go#L210-L211) on the pods where the controller reference is not understood by the CA ([CA as of now only understands controller refs for Daemonsets, ReplicaSets, Jobs, ReplicationControllers, Deployments and StatefulSets](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain.go#L124-L203)). This is because CA treats pods with non-understood …
=> feat: check only controller ref to decide if a pod is replicated

cluster-autoscaler/expander/priority/priority.go, cluster-autoscaler/expander/priority/priority_test.go
Cherry pick of #5246 on cluster-autoscaler-release-1.25.
#5246: Don't break scale up with priority expander config
=> Automated cherry pick of #5246: Don't break scale up with priority expander config

cluster-autoscaler/utils/drain/drain.go
/kind bug
Currently, pods with in-memory storage are considered as having local storage and are not evictable. This prevents cluster autoscaling to down-scale the node if such pods are present.
In-memory storage is widely used for organizing init or sidecar container communication and in the vast majority of cases should not contain critical data to be lost (see details explanation at https://github.com/kubernetes/autoscaler/issues/3984).
If the new default behavior is not desired then annotation could be added: `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` 
Fixes #3984, #2048
```release-note
Pods having `emptyDir` volumes with `medium: Memory` are not considered to have local storage and therefore are evictable
```
=> Consider pods with emptydir volume in memory be evictable

vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go, vertical-pod-autoscaler/e2e/v1/full_vpa.go
/kind flake
After #5326 the VPA test in "OOMing pods under VPA" in full_vpa.go became unstable when ran in GKE.
I debugged it a bit and I can see that in the set-up used by the test VPA is reacting to both OOMs and regular memory samples which kind of defeats the purpose of the test.
IIUC the whole idea of the test is based on how fast VPA would scale on average - multiple scale ups are required to reach 1.4 GB. This makes the test brittle as the VPA reaction time is not specified and could vary.
This PR attempts to create a more deterministic test:
* set memory limit to 1024 MiB,
* allocate 1025 MiB worth of memory in one go to significantly decrease a chance of a regular sample,
* expect a recommendation taking into account both the OOM bump (+20% by default) and the usual 15% margin, …
=> Make the "OOMing pods under VPA" test more robust.

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/vpa.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
I currently install a VPA for the cluster-autoscaler alongside the chart, but it would be nice to get it all from the same source.
```release-note
Add chart option to install VPA
```
=> chart: Add option to install VPA

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/scaleup/orchestrator/skippedreasons.go, cluster-autoscaler/core/scaleup/scaleup.go
/kind cleanup
Removes an unused interface that slipped in. It was an alternative to the initialize function of the orchestrator.
Fixes #
No
NA
=> Remove Factory interface since it is not used.

cluster-autoscaler/FAQ.md
Fixes the flag name for `--enforce-node-group-min-size` in list of all flags. It was still referencing the old flag that was changed during [code review](https://github.com/kubernetes/autoscaler/pull/5195#discussion_r993014504). The flag is correctly used in section _My cluster is below minimum / above maximum number of nodes, but CA did not fix that! Why?_ that explains its behaviour.
/
/
```release-note
NONE
```
```docs
```
=> docs: fix invalid flag name

addon-resizer/Makefile
/kind bug
/kind cleanup
Go1.16 has some security vulnerabilities and is no longer maintained - hence the upgrade to the latest stable golang version.
This PR also bumps TAG to already prepare for a new release with the update golang.
```release-note
NONE
```
```docs
Golang version used to build the images is updated from 1.16 to 1.20.2.
```
=> Bump golang version to address vulnerabilities in go1.16.

.github/dependabot.yml
Adds dependabot configuration for VPA. We can try to automate updates of the builder golang version and security fixes for the dependencies in go.mod. Recent examples where we did these update by hand are [bumping golang to 1.19.5](https://github.com/kubernetes/autoscaler/pull/5484) and updating [github.com/emicklei/go-restful/v3](https://github.com/kubernetes/autoscaler/pull/5482).
By setting `open-pull-requests-limit: 0`, you limit the dependabot updates to security fixes only – [these PRs are done with a separate pull-request-limit pool](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit)
Fixes #5341
As discussed in the last SIG meeting, let's see if this creates too much noise. We …
=> Add dependabot configuration for VPA

cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/processors/scaledowncandidates/emptycandidates/empty_candidates_sorting.go, cluster-autoscaler/processors/scaledowncandidates/emptycandidates/empty_candidates_sorting_test.go, cluster-autoscaler/simulator/cluster_test.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/utils/drain/drain.go
/kind fix
In drain logic the `isDaemonSet` variable is set outside of pod loop. It is not correctly changed when skipNodesWithCustomControllerPods=false, so if there is at least one DS pod on the node it can be drained. This is also non-deterministic as the slice of pods is passed in random order.
Additionally the NodeDeleteOptions were not set in all appropriate places. Because of this some parts of the logic like empty candidate sorting always worked on skipNodesWithCustomControllerPods=false.
Original change: #5507
=> Fix drain logic when skipNodesWithCustomControllerPods=false, set NodeDeleteOptions correctly

addon-resizer/Makefile
/kind cleanup
New tag to start a release process for the latest vulnerability fixes (fixed under #5669).
```release-note
NONE
```
=> Bump version to 1.8.18 to release #5669.

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
- this is a follow-up to https://github.com/kubernetes/autoscaler/pull/5054
- this might fix https://github.com/kubernetes/autoscaler/issues/4456
/kind bug
I think description of https://github.com/kubernetes/autoscaler/pull/5054#issue-1319989728 explains it well:
> ...original intent of determining the deleted nodes was incorrect, which led to the issues reported by other users. The nodes tainted with ToBeDeleted were misidentified as Deleted instead of Ready/Unready, which caused a miscalculation of the node being included as Upcoming. This caused problems described in https://github.com/kubernetes/autoscaler/issues/3949 and https://github.com/kubernetes/autoscaler/issues/4456.
https://github.com/kubernetes/autoscaler/pull/5054 exposed interface function `HasInstance` for cloud …
=> fix: implement function to identify if node is present in aws

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
Extend GCE Autoscaling client by adding a FetchReservations method.
This change is necessary, if we want to support Reservations, when making a scaling decisions.
```release-note
NONE
```
```docs
- [Other doc]: https://cloud.google.com/compute/docs/instances/reserving-zonal-resources
```
=> Add FetchReservations to GCE Autoscaling client

cluster-autoscaler/FAQ.md, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
- this is so that scale down is not blocked on local storage volume
- for pods where it is okay to ignore local storage volume
/kind feature
Some pods like istio sidecars have local storage which block node scale down. We would like to have the ability to ignore local storage volumes on certain pods provided the right annotation of the form `cluster-autoscaler.kubernetes.io/ignore-local-storage-volume: <volume-name>` is present on the pod. 
Fixes #3947 
```release-note
Added: cluster-autoscaler now supports a new pod annotation `cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes: "volume-1,volume-2"` to evict pods with local storage volumes (where `volume-1` and `volume-2` are safe to evict local storage volumes) during node …
```
=> feat: add annotation to ignore local storage volume during scale down

cluster-autoscaler/cloudprovider/externalgrpc/examples/external-grpc-cloud-provider-service/main.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go
/kind feature
This PR limits the number of GCE calls to fetch mig instances. After large scale down, when a lot of instances got removed, we perform a lot of redundant calls to GCE - we try to fetch already deleted instances, even though it was done moments ago for a different, already deleted instance. To avoid that this PR introduces rate (by default 5s) at which mig instances can be refetched.
NONE
```docs
```
=> Limit refresh rate of GCE MIG instances.

cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/clusterstate/max_node_provision_time_provider.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/config/const.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodegroupconfig/node_group_config_processor.go, cluster-autoscaler/processors/nodegroupconfig/node_group_config_processor_test.go
/kind cleanup
This PR enables setting `MaxNodeProvisionTime` per NodeGroup (it was previously set per cluster).
Fixes #
Please take a look.
```release-note
MaxNodeProvisionTime can now be defined per node group using 'maxnodeprovisiontime' key. The value of 'max-node-provision-time flag' is still used as the default for all node groups, so this change should have no visible impact on the behavior of Cluster Autoscaler.
```
NA
/assign @kisieland
=> Move MaxNodeProvisionTime to NodeGroupAutoscalingOptions

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind feature
The PR is to add VMSS Flex support to azure autoscaler
Fixes #5334
There are couple of changes in this PR.
1. Adding a feature flag "EnableVmssFlex" to turn on/off support for VMSS Flex scale set.
2. Refactor func instanceStatus in azure_scale_set to receive ProvisioningState instead of VM or VMSSVM so that it can be used in both type of scale sets (Uniform, Flexible) 
3. Retrieving VMs for Flex scale set using VM api instead of VMSSVM api.
```release-note
```
```docs
```
=> Adding VMSS Flex support in Azure AutoScaler

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_fakes.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
This PR is to cherry-pick changes of PR: https://github.com/kubernetes/autoscaler/pull/5602/ from main to release branch
Fixes https://github.com/kubernetes/autoscaler/issues/5334
```release-note
```
```docs
```
=> Cherry picking #5602 for cluster-autoscaler-release-1.27

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind feature
Adds a case to the Azure VMSS instance status check to cover an instance that failed provisioning. If the instance fails to provision (generally due to Azure being unable to provide capacity for the instance type), the error percolate to the cluster state registry and put the nodegroup into backoff (faster than if it had to wait `maxNodeProvisionTime`). 
This is inspired by the other cloudProviders that implement similar behavior, like https://github.com/kubernetes/autoscaler/pull/4489
An nodegroup using an instance type that was actively experiencing Azure capacity issues was selected.  A scale up was triggered for that nodegroup which promptly fails.  The nodegroup is put into backoff in ~20s, and another compatible nodegroup can be upscaled instead, without having to wait …
=> Azure: Fast nodegroup backoff on failed provisioning 

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
The joinStringMaps call in the `buildTemplateLabels` method of the clusterApi provider should not overwrite any custom labels with the generic ones returned by `buildGenericLabels()`
/kind bug
Currently, when the joinStringMaps is called and the `unstructuredScalableResource` already defines one of the labels also returned by the `buildGenericLabels` method (e.g., `kubernetes.io/arch: arm64`), the generic value returned by `buildGenericLabels` gets precedence over the user-defined one. This should be considered an unwanted behavior.
For example, the `buildGenericLabels` method sets the `kubernetes.io/arch` value to amd64. 
If the nodeGroup is for arm64 machines and the label `kubernetes.io/arch: arm64` is set in the annotation   `capacity.cluster-autoscaler.kubernetes.io/labels: …
=> Fix the buildTemplateLabels method for the ClusterApi provider

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/skippedreasons.go, cluster-autoscaler/core/scaleup/orchestrator/skippedreasons_test.go
This allows us to get the list of missing resources from the skipped reasons object, without computing it one more time.
/kind cleanup
It simplifies extracting the details about missing resources.
Fixes #
```release-note
NONE
```
```docs
```
=> Add a dedicated struct for the MaxResourceLimitReached Reasons

cluster-autoscaler/estimator/estimator.go, cluster-autoscaler/estimator/threshold_based_limiter.go, cluster-autoscaler/estimator/threshold_based_limiter_test.go
This method will allow CA to check if any the limiter blocked addition of any new Node.
/kind cleanup
Adds a new function to the EstimationLimiter and implements it for the ThresholdBasedEstimationLimiter.
ReachedLimit function allows CA to check if the Limiter blocked addition of a new Node.
```release-note
NONE
```
```docs
```
=> Add new method 'ReachedLimit' to EstimationLimiter

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/estimator/binpacking_estimator_test.go, cluster-autoscaler/estimator/decreasing_pod_orderer.go, cluster-autoscaler/estimator/decreasing_pod_orderer_test.go, cluster-autoscaler/estimator/estimator.go
Refactor the Binpacking estimator by making the pod sort extendable by moving the logic into pod_priority_processor.go Cleanup sorting logic/structs from binpacking_estimator.go
/kind feature
We would like to have to ability to customise pod order which is used while binpacking.
Fixes #
```release-note
```
```docs
```
=> Binpacking Estimator pod priority

cluster-autoscaler/estimator/estimator.go, cluster-autoscaler/estimator/threshold_based_limiter.go, cluster-autoscaler/estimator/threshold_based_limiter_test.go
This was meant to be used as a signal that the estimation did consider all of the pods, but @x13n pointed out that other k8s primitives may also limit it so the best option is to compare a list of estimated pods.
This reverts commit 3ad77e8341eecc038ce9d706d20c0231b5eb7954.
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
/assign x13n
=> Revert "Add new method 'ReachedLimit' to EstimationLimiter"

cluster-autoscaler/cloudprovider/vultr/OWNERS, cluster-autoscaler/cloudprovider/vultr/vultr_node_group.go
/kind bug
This PR resolves an issue we are seeing with node deletions for Vultr Kubernetes offering. 
I did not make an issue for this PR
The previous reviewer/owner for Vultr cloudprovider is no longer valid. I updated those values as well with the correct GH users. 
NONE 
```release-note
```
```docs
```
=> refactored vultr node delete

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client_test_util.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
/kind cleanup
Using factories in the main allow use to better initialise and share some resources between building blocks.
This also make some pieces like the sharedInformer, the controllerFetcher, .... available for other building blocks like the post-processing layer.
None 
Fixes #
Removing function that are marked deprecated, use factory instead. This will allow to share some interfaces with post processors that are also bootstrapped in the main.
NONE
=> [vpa] [recommender] use factories for recommender and clusterStateFeeder

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodeinfosprovider/asg_tag_resource_node_info_provider.go
/kind bug
Applies #5214 to 1.26 (since 1.27 seems like its a long way off from release).
Fixes #5164
```release-note
NONE
```
```docs
```
=> Fix/asg resource tags for 1.26.x

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache_test.go
/kind feature
This PR introduces a feature that allows handling of ephemeral storage and custom resources in a scale-from-zero scenario when using EKS nodegroups.
It does this via allowing tags in the form of `k8s.io/cluster-autoscaler/resources/<resource>: <quantity>` analogous to how they are allowed directly on an ASG.
As the EKS-managed ASGs in case of managed nodegroups don't support custom tags for those resources they will be read from the managed nodegroup and processed accordingly.
NONE
I have modeled this after the implementation for ASGs and tried to be as clean as possible, passing through the Tags in the managed node group cache. I don't expect anybody will find it unexpected that these specific annotations influence the node templates.
As for documentation regarding this I …
=> Add support for tags on AWS managed nodegroups to indicate resources

cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go
adding support for https://aws.amazon.com/ec2/instance-types/trn1/
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Added support for the AWS Trainium instance types 

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go
This reverts commit 8e724705457e056b756e1381d3be73a666da9c0f.
/kind bug
VPA e2e are failing after #5680. We're merging other PRs so we need to revert this. Otherwise we risk merging other breaking PRs and not noticing.
Fixes #5727
=> Revert "Add subresource status for vpa"

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodeinfosprovider/asg_tag_resource_node_info_provider.go
/kind bug
Applies https://github.com/kubernetes/autoscaler/pull/5214 to 1.24 for clusters that can't upgrade their k8s version yet.
Fixes https://github.com/kubernetes/autoscaler/issues/5164
Special notes for your reviewer:
NONE
=> Fix/asg resource tags for 1.24.x

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
We have many identical statefulsets in different namespaces, as a result, the pod name by itself is close to useless as an identifier. Add the namespace in the log.
Fixes #
```release-note
```
```docs
```
=> CA: Add pod namespace when logging why scaleup wasn't possible

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go, cluster-autoscaler/core/scaleup/orchestrator/executor_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go
/kind feature
/kind cleanup
This PR introduces an optional flag `--parallel-scale-up=true/false` that makes the scale-up process parallel. Thanks to this change, the scale-up action across multiple node groups is faster.
The default behavior is unchanged - node groups are scaled synchronously, one by one. 
- *Why it's a runtime flag and not a default behavior?* It's a runtime flag because there are some CloudProviders that are not thread-safe. It may become a default in the future.
- *Why is there no new/dedicated error to combine concurrent errors?* I wanted to keep the API simple without introducing big changes. Concurrent errors are preserved in the final error message, and each of them is logged separately, so information is preserved.
- *Why are there so many changes in test files?* …
=> Feature: parallel scale up

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/expander/expander.go
/king bug
The similar node group balancing is using the node group expansion options to determine which node group can be used to balance the scale-up. This does not work in some edge cases:
- Bin-packing has a timeout limit in case there are too many pending pods to compute. That means that identical node groups can get different expansion options, resulting in no balancing in such cases.
- If identical node groups have different `MaxSize-TargetSize` values (e.g node group `A` can fit 10 nodes, node group `B` can fit 5 nodes), then their expansion options will be different even though they are otherwise identical. These node groups would not be balanced because of that, which is really bad when they are close to the max size.
To fix this I've changed the logic to use `schedulablePods` …
=> Fix scale-up similar node group computation

vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
/kind bug
Switch to `docker buildx --platform` for building cross-platform images, such that the `Architecture` metadata is correctly set in the image manifest.
Fixes #5667
Tested this change by running
` ALL_ARCHITECTURES="amd64 arm64" REGISTRY=voelzmo TAG=v0.99.0-dev make release`
inspected the image with 
`docker image inspect voelzmo/vpa-admission-controller-amd64:v0.99.0-dev` and `docker image inspect voelzmo/vpa-admission-controller-arm64:v0.99.0-dev`
and saw that the `Architecture` metadata in the manifest was `amd64` and `arm64`, respectively.
```release-note
VPA images are now built using `docker buildx` to correctly set the `Architecture` metadata in the image manifest.
```
=> Switch to docker buildx for cross-platform builds

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodeinfosprovider/asg_tag_resource_node_info_provider.go
/kind bug
Applies #5214 to 1.25 for clusters that can't upgrade their k8s version.
Fixes #5164
Special notes for your reviewer:
NONE
=> Fix/asg resource tags for 1.25.x

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
/kind bug
We encountered an issue where the `curSize` cached value would be decremented every time an already terminating instance was signaled for termination again. This caused the desired size of the ASG to dwindle to min size and was made worse when we introduced a change that kept instances in a terminating state for longer than we previously did.
The cause of this it seems is because cluster-autoscaler doesn't take any heed of already terminating instances and blindly decrements the `curSize` value,
This PR addresses that by caching the lifecycle state of the instance.
Fixes https://github.com/kubernetes/autoscaler/issues/4095
```release-note
```
```docs
```
=> Track lifecycle and skip terminating already terminating instances

cluster-autoscaler/clusterstate/utils/status.go, cluster-autoscaler/clusterstate/utils/status_test.go
/kind bug
Fix nil pointer error if the status configmap is empty #5704.
Fixes #5704 
```release-note
NONE
```
```docs
```
=> fix: empty status configmap leads to nil ptr error

addon-resizer/Makefile
/kind bug
Bumps Golang version to `1.20.4` & pump release tag to `1.8.19`
Fixes 
- [GO-2023-1751](https://pkg.go.dev/vuln/GO-2023-1751)
- [GO-2023-1752](https://pkg.go.dev/vuln/GO-2023-1752)
- [GO-2023-1753](https://pkg.go.dev/vuln/GO-2023-1753)
```release-note
NONE
```
=> Bump golang version & release tag

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
This is a cherry-pick of https://github.com/kubernetes/autoscaler/pull/5632
/kind bug
Fixes #
```release-note
```
```docs
```
=> [cherry-pick to 1.26]: implement function to identify if node is present in aws

cluster-autoscaler/FAQ.md, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
This is a cherry-pick of https://github.com/kubernetes/autoscaler/pull/5594
/kind feature
Fixes #
```release-note
```
```docs
```
=> [cherry-pick to 1.25]: add annotation to ignore local storage volume during scale down

cluster-autoscaler/FAQ.md, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
This is a cherry-pick of https://github.com/kubernetes/autoscaler/pull/5594
/kind feature
Fixes #
```release-note
```
```docs
```
=> [cherry-pick to 1.24]: add annotation to ignore local storage volume during scale down

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
This is a cherry pick of https://github.com/kubernetes/autoscaler/pull/5632
/kind bug
Fixes #
```release-note
```
```docs
```
=> [cherry-pick to 1.25]: implement function to identify if node is present in aws

cluster-autoscaler/FAQ.md, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
Check https://github.com/kubernetes/autoscaler/pull/5594
This is a cherry-pick of https://github.com/kubernetes/autoscaler/pull/5594
/kind feature
Fixes #
```release-note
```
```docs
```
=> [cherry-pick to 1.26]: add annotation to ignore local storage volume during scale down

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go
This is a cherry-pick of https://github.com/kubernetes/autoscaler/pull/5632
/kind feature
Fixes #
```release-note
```
```docs
```
=> [cherry-pick to 1.24]: implement function to identify if node is present in aws

cluster-autoscaler/core/static_autoscaler.go
/kind bug
There is a race condition between node group size and deletion operation. Having  actuation status update done before cache refresh should change incorrect behavior from node group size going below min value to having adding loop for scale-down (in the worst case).
Follow-up to pull/5562
No
=> Snapshot actuation status before refreshing cache

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/clusterrole.yaml, charts/cluster-autoscaler/templates/role.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
This PR updates the official helm chart to include support for Cluster API machinepools, which requires the following:
1. Role and ClusterRole definitions need to be updated to include `machinepools` and `machinepools/scale`
2. cluster-autoscaler image version needs to be v1.27.1 so that the runtime itself delivers support for machinepools
- see https://github.com/kubernetes/autoscaler/pull/4676
Fixes #
```release-note
NONE
```
```docs
```
=> helm: enable Cluster API machinepool support

cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
/kind bug
Magnum still tries to fetch nodes that have the master node role, but since the role is now called control-plane, it cannot find the nodegroup for those nodes.
Fixes #5751
```release-note
NONE
```
=> [Cluster-Autoscaler] Change magnum to use control-plane role

balancer/proposals/balancer.md
Correct typo from 'Kuberentes' to 'Kubernetes'.
None
None
```release-note
None
```
```docs
```
=> Fix typo at balancer.md

cluster-autoscaler/simulator/utilization/info.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> Export `CalculateUtilizationOfResource` for cloudprovider usage.

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
This is a cherry-pick of #4926 
cc @bpineau 
/kind bug
Fixes #
also fix test issue in commit b8f79f8cf75efad471f35d14b956fe11883a9fd0 
```release-note
```
```docs
```
=> [cherry-pick to 1.24] Don't deref nil nodegroup in deleteCreatedNodesWithErrors

cluster-autoscaler/cloudprovider/linode/examples/cluster-autoscaler-autodiscover.yaml
/kind bug
This PR added the missing RBAC permission in the [examples](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/linode/examples/cluster-autoscaler-autodiscover.yaml) mentioned under the Linode Cloud Provider.
Fixes #5815
```release-note
NONE
```
```docs
```
=> Added the RBAC Permission to Linode.

cluster-autoscaler/cloudprovider/builder/builder_all.go
/kind cleanup
CA is failed to build with `BUILD_TAGS=volcengine`, this PR fix this issue:
```shell
$ BUILD_TAGS=volcengine make build
rm -f cluster-autoscaler-amd64
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cluster-autoscaler-amd64 --ldflags "-s" --tags volcengine
cloudprovider/builder/builder_volcengine.go:29:5: AvailableCloudProviders redeclared in this block
cloudprovider/builder/builder_all.go:56:5: other declaration of AvailableCloudProviders
cloudprovider/builder/builder_volcengine.go:34:7: DefaultCloudProvider redeclared in this block
cloudprovider/builder/builder_all.go:88:7: other declaration of DefaultCloudProvider
cloudprovider/builder/builder_volcengine.go:36:6: buildCloudProvider redeclared in this block
cloudprovider/builder/builder_all.go:90:6: other declaration of …
```
=> [volcengine] fix(volcengine): don't build all providers when volcengine tag exists

vertical-pod-autoscaler/README.md
/kind bug
This PR fixed the typo and removed the trailing whitespaces from the [VPA README](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md).
Fixes #
```release-note
None
```
```docs
```
=> Fixed Typo and Trailing-whitespace

cluster-autoscaler/core/static_autoscaler.go
This is a cherry-pick of #5521 
/kind bug
Fixes #
```release-note
```
```docs
```
=> [cherry-pick to 1.25] fix(*): refresh node instance cache when nodegroup not found in deleteCreatedNodesWithErrors

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
/kind bug
The non-existing similar node groups should not be checked on "safe to scale-up" criteria, similarly on how we don't check it for non-existing primary node groups.
=> Skip healthiness check for non-existing similar node groups

cluster-autoscaler/cloudprovider/civo/OWNERS
/kind cleanup
This PR adds owners for civo cloud provider
According to https://github.com/kubernetes/autoscaler/pull/5198 Adding owners for civo cloud provider
```release-note
NONE
```
```docs
NONE
```
=> Updated the owners of civo cloudprovider

vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md
/kind feature
Add Autoscaling Enhancement Proposal to add basic support for in place updates to VPA.
See also #5754 for changes I propose to eviction control enhancement proposal to work better with in place updates
#4016
@voelzmo @kgolab @pbetkier @wangchen615 please take a look
=> AEP for support of in-place updates for VPA

cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-config.yaml, cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-principals.yaml
/kind bug
The examples have wrong resources mentioned and due to which we are seeing below error in cluster-autoscaler logs - 
`E0609 10:54:00.178537       1 reflector.go:140] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope`
I noticed it today and thought of fixing the code directly rather than creating a issue.
```release-note
NONE
```
```docs
NONE
```
=> Fix: correcting RBAC permission in oci oke examples

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/values.yaml
/kind bug
This PR modified the VPA content for the CA under the [Charts](https://github.com/kubernetes/autoscaler/tree/master/charts) directory. It will give a better understanding of the usage of VPA  for the CA helm charts.
Fixes #5758
```
None
```
```docs
```
=> Modified the VPA content for the helm chart and Bump the CA image to 1.27.2

vertical-pod-autoscaler/hack/vpa-process-yamls.sh
/kind bug
This PR update the [vpa-process-yamls.sh](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/vpa-process-yamls.sh) script to print the VPA  V1 CRD data.
Fixes #5832
```release-note
None
```
```docs
```
=> Update VPA scripts to use v1.

cluster-autoscaler/utils/utils.go, cluster-autoscaler/utils/utils_test.go
/kind bug
CA groups pods based on their scheduling requirements. They are grouped based on pod spec and we assume that pods belonging to the same controller should have similar requirements. However, there are certain fields that differ between the pods controlled by the same controller. If we know that they do not affect scheduling we should drop those for grouping purposes.
One of such fields is projected volume mount. We drop them currently, but only for containers, while they can exist for init containers as well.
```release-note
NONE
```
=> When comparing PodSpec semantically, drop projected volumes for init containers

vertical-pod-autoscaler/common/version.go
/kind release
Part of the release process, as documented [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md).
Release tracker: #5851
=> Bump version to 0.14.0 as a preparation for release.

vertical-pod-autoscaler/RELEASE.md
The goal is twofold:
* clarify the release process for people who are not accustomed to it (like me, for example) - by saying where to run the scripts,
* make the process less error-prone by getting the `TAG` value automatically
=> Clarify and simplify the "build and stage images" step.

vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
/kind cleanup
This a release helper: currently it's hard to make sure what exactly was built during tests (e.g. here: https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#Summary).
In #5861 we got a bit lucky as the latest commit bumped golang version but in general it should much easier to know what was built.
After this merges and some tests are ran with the new Makefiles, I will update RELEASE.md with instructions on how to verify what was tested.
=> Execute git commands to show the state of local clone of the repo.

cluster-autoscaler/cloudprovider/gce/mig_info_provider.go
/kind bug
GKE autopilot clusters ```InstanceGroupManagers.List``` and ```InstanceGroupManagers.Get``` methods consistently serving errors in a single zone caused CA to functionally grind to a halt in a regional cluster. This PR modifies ```fillMigInfoCache()``` method in ```cloudprovider/gce/mig_info_provider.go``` to do the following changes as a fix.
- Still log all errors encountered
- Return an error if all zones returned errors, not when one zone did
- For each broken zone, iterate over all MIGs from ```registeredMigRefs``` and mark them missing by calling ```c.migLister.HandleMigIssue(migRef, err)```
Fixes #
NONE
```release-note
```
```docs
```
=> Fix zonal GCE outage breaking CA when only some of the zones are failed

vertical-pod-autoscaler/RELEASE.md
The promised follow-up to #5862, clarifies how to verify what state of the code repository was used as a basis for any given test run.
[Sample log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1669586547378229248/build-log.txt) looks like:
```
I0616 06:13:30.554] =============== last commit ===============
I0616 06:13:30.554] git log -1
I0616 06:13:30.554] commit 231868ead734ce91a3b5d87fd471c1946d6a92c6
I0616 06:13:30.555] Merge: d7fa2d9d8 1944c821c
I0616 06:13:30.555] Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
I0616 06:13:30.555] Date:   Thu Jun 15 12:00:22 2023 -0700
I0616 06:13:30.555] 
I0616 06:13:30.555]     Merge pull request #5862 from kgolab/makefile-status
I0616 06:13:30.555] …
```
=> Mention logs from #5862 in release instructions

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/processors/binpacking/binpacking_limiter.go, cluster-autoscaler/processors/processors.go
Addition of BinpackingLimiter interface.
The idea behind this is to stop computing expansion options if we have already found good enough expansion option/s.
Talking about why we need it?
Currently we iterate over all the unschedulable pods and for each pod we try to check if it could fit in that node. However, this computation can be improved if somehow we could analyse the current expansion options and stop the binpacking early.
Eg.  Suppose a cluster has 3 nodegroups as follows:
1. NG1 with 100 unit CPU and 100 unit memory.
2. NG2 with 10 unit CPU and 10 unit memory.
3. NG3 with 1000 unit CPU and 1000 unit memory.
Let's say the extra pod that we want to schedule requires 80 unit CPU and 80 unit memory.
Now we can see that the pod can easily fit on NG1 and NG3, however, the expansion …
=> Addition of BinpackingLimiter interface

vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
/kind bug
Explicitly create a `builder` to be used with `docker buildx` and configure it for use during the build. Previously, the build would take whichever builder was currently configured on the machine, which could lead to inconsistencies with the builder's `output` behavior. See [the discussion in the v0.14.0 release issue](https://github.com/kubernetes/autoscaler/issues/5851#issuecomment-1594502338) for more context.
The builder created here is of type `docker-container` and [needs and explicit `output` configured](https://docs.docker.com/engine/reference/commandline/buildx_create/#driver) – the flag [`--load` is a shorthand for `--output=type=docker`](https://docs.docker.com/engine/reference/commandline/buildx_build/#load).
Additional make target were created, such that we can …
=> Explicitly create and remove buildx builders for VPA components

vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
/kind bug
Cherry-picking fix from #5867 to release branch so it can be built from a clean state. We have a VPA release in progress (#5851) and I'd like to make sure that we follow the instructions precisely:
> Create a fresh clone of the repo and switch to the vpa-release-0.${minor} branch. This makes sure you have no local changes while building the images.
I verified already that with this c-p included everything builds fine and the images are pushed to GCR (my in this case).
=> Explicitly create and remove buildx builders

vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md
/kind cleanup
Apply comments from review of #5755 that I couldn't apply directly in the PR before it merged
If there are any other comments please leave them on either PR and I'll address them here.
#4016
=> Apply fixes to in place support VPA AEP

vertical-pod-autoscaler/RELEASE.md
/kind cleanup
Some minor updates to the instructions on how to release VPA, based on the process done under #5851:
* use registry.k8s.io rather than k8s.gcr.io,
* make the copy&paste easier (no need to remove `$` manually)
* add a note about `add-version.sh` script
=> Minor tweaks after preparing VPA 0.14.0 release.

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
/kind feature
this change adds some logging at verbosity levels 2 and 3 to help diagnose why the cluster-autoscaler does not consider 2 or more node groups to be similar.
Fixes #5834 
must enable `--balance-similar-node-groups` and `-v=3` to see the results of this change.
```release-note
When using the `--balance-similar-node-groups` flag of the Cluster Autoscaler, more logging is now available at verbosity levels 2 and 3 to help diagnose balancing failures.
```
```docs
```
=> Cluster Autoscaler: add more logging for balancing similar node groups

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/e2e/v1/common.go, vertical-pod-autoscaler/e2e/v1beta2/common.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go
Add status field in subresource on crd yaml and add new ClusterRole system:vpa-actor to patch /status subresource. 
The `metadata.generation` only increase on vpa spec update. 
Fix e2e test for patch and create vpa
/kind bug
Current vpa crd has empty subresource field, that leads to metadata.generation increase on vpa status update.
The controller-runtime has [GenerationChangedPredicate](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/predicate#GenerationChangedPredicate) to filter out update status event for cr, but it not work for vpa.
This PR add status field in subresource on crd yaml and add new ClusterRole system:vpa-actor to patch /status subresource.
The metadata.generation only increase on vpa spec update.
Fixes #5675 
Previous …
=> [VPA] Add subresource status for vpa with e2e fix

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go
/kind bug
/kind flake
The test `TestBinpackingLimiter` from #5810 was flaky. The test cloud provider iterates over a map to create a list of nodegroups. In this test, I'm trying to limit the expansion options but it turns out that the list is not ordered and hence the BinpackingLimiter stops generating options after processing 1 nodegroup.
How to reproduce the issue (before these changes):
```
func TestBinpackingLimiter1000(t *testing.T) {
loop := 100
for i := 1; i < loop; i++ {
TestBinpackingLimiter(t)
}
}
```
Fixes #
```release-note
None
```
```docs
```
=> Sort nodegroups in order of their ID

vertical-pod-autoscaler/e2e/v1/actuation.go, vertical-pod-autoscaler/e2e/v1beta2/actuation.go
/kind cleanup
Move the agnhost image in e2e tests from the staging repo to be pulled from `registry.k8s.io/e2e-test-images/agnhost:2.40` instead.
Fixes a code TODO.
```release-note
NONE
```
```docs
```
/assign @jbartosik
=> update agnhost image to pull from registry.k8s.io

vertical-pod-autoscaler/pkg/updater/logic/updater_test.go, vertical-pod-autoscaler/pkg/updater/priority/priority_processor_test.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go, vertical-pod-autoscaler/pkg/utils/test/test_utils.go, vertical-pod-autoscaler/pkg/utils/vpa/api_test.go, vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
/kind cleanup
Resolves a code TODO by replacing uses of `BuildTestContainer` with use of the builder directly.
Fixes code TODO
I was resolving the TODO and generally think it might have helped clean things up, but would like to get some feedback if we all agree this change makes sense.
I can see it both ways that having this helper made sense. If so we should just remove the TODO instead.
```release-note
NONE
```
```docs
```
/assign @jbartosik
=> Replace `BuildTestContainer` with use of builder

addon-resizer/Makefile
/king bug
Need to fix GO-2023-1840
The govulncheck reports that:
```
Standard library
Found in: runtime@go1.20.3
Fixed in: runtime@go1.20.5
```
I'm not bumping the tag since the one from #5778 was actually never released.
=> Bump golang to the latest version (1.20.5)

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go
/kind bug
There are 2 mechanisms used to fix the incorrect node group size:
- Unregistered nodes are removed after the default time of 15 minutes.
- Node group is resized to the number of registered nodes if this number is smaller than the target size after the default time of 15 minutes.
Both these mechanisms use the same time threshold, so there can occur race conditions between them. For example in the following situation:
Node group with:
- 1 registered node
- 1 unregistered node
- target size of 2
In this instance it is better to remove the unregistered node rather than resizing the node group. The issue with the second approach is that we don't have a guarantee which node will be removed - it can be either the unregistered one (desired) or the registered one (undesired).
To prevent …
=> Include short unregistered nodes in calculation of incorrect node group

cluster-autoscaler/OWNERS
I'm self-nominating myself for cluster-autoscaler approver.
Process outline: https://github.com/kubernetes/community/blob/master/community-membership.md#approver.
- I've became reviewer on February 14th: https://github.com/kubernetes/autoscaler/pull/5492
- https://github.com/kubernetes/autoscaler/pull/5459
- https://github.com/kubernetes/autoscaler/pull/5649
- https://github.com/kubernetes/autoscaler/pull/5689
- https://github.com/kubernetes/autoscaler/pull/5705
- https://github.com/kubernetes/autoscaler/pull/5753
- https://github.com/kubernetes/autoscaler/pull/5810
- https://github.com/kubernetes/autoscaler/pull/5711
- https://github.com/kubernetes/autoscaler/pull/5826
- https://github.com/kubernetes/autoscaler/pull/5883
- https://github.com/kubernetes/autoscaler/pull/5663
- …
=> Add BigDarkClown to Cluster Autoscaler approvers

vertical-pod-autoscaler/hack/generate-crd-yaml.sh
/kind bug
Add some quotes around the target directory parameter for `controller-gen`. Temporary folders can have all kinds of funny symbols in it, which can lead to unexpected results/errors. Here is what I got today when trying to re-generate the CRDs with `hack/generate-crd-yamls.sh`:
```
✗ ./hack/generate-crd-yaml.sh
Error: unable to parse option "output:crd:dir=/var/folders/4p/pbd3vmnj5_xfvcjh0pdxy8zw0000gn/T/tmp.eYi9W4D9v4": ['p' exponent requires hexadecimal mantissa (at <input>:1:14) exponent has no digits (at <input>:1:14)]
```
After adding the quotes, the script executed fine.
```release-note
NONE
```
=> Quote temp folder name parameter to avoid errors

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler.go, cluster-autoscaler/core/scaledown/budgets/budgets.go, cluster-autoscaler/core/scaledown/budgets/budgets_test.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/expander/expander.go, cluster-autoscaler/processors/nodes/post_filtering_processor.go
/kind feature
This PR adds a node group AtomicScaleUp option, that allows for all-or-nothing scale up of the node group.
N/A
```release-note
Add AtomicScaleUp option that allows all-or-nothing scale up of node groups.
In atomic scale-ups, the node group should be scaled up to max size (without partial scale-ups).
```
=> Add support for scaling up with ZeroToMaxNodesScaling option

cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
/kind bug
This PR is cherry-picked, which backports https://github.com/kubernetes/autoscaler/pull/5776 in CA-1.26
Part of https://github.com/kubernetes/autoscaler/issues/5888
```release-note
None
```
```docs
```
=> Backport #5776 [cluster-autoscaler] "Change magnum to use control-plane role" into CA1.26

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/metrics/metrics.go
/kind feature
This PR adds two metrics to observe where time is consumed in scale up.
When there are more than 10000+ pending pods in cluster and these pods have a complicated scheduling constraint, CA may take a long time to execute `main` function. In our environment it takes almost 2min+. The time is consumed in:
- filtering out schedulable pods
- building equivalence pod groups
- using binpacking algorithm to estimate how many nodes needed(yes we have limiter  which may cut short binpacking but I still think it's necessary to observe the time)
https://github.com/kubernetes/autoscaler/blob/9624e7d11f1d4eaac491fbaa530f75facaab1796/cluster-autoscaler/estimator/binpacking_estimator.go#L102-L106
So I add a metrics to expose these.
Here is the time functions take to complete:
Fixes # …
=> feat(metrics): add metrics to observe where time is consumed in scale up

vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/recommender/model/vpa.go, vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go, vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender_test.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
/kind cleanup
Change the tracking of APIVersion from a boolean
indicating if the VPA is v1beta1
to the version string
and make sure it gets exported
in metrics.
Add tests for the recommender metrics.
```release-note
* VPA API Versions reported in the `vpa_objects_count` metric now include `v1` VPAs
```
```docs
```
/cc @jbartosik
=> Record all vpa api versions in recommender metrics

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/e2e/v1/common.go, vertical-pod-autoscaler/e2e/v1beta2/common.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go
Add status field in subresource on crd yaml and add new ClusterRole system:vpa-actor to patch /status subresource. 
The `metadata.generation` only increase on vpa spec update. 
Fix e2e test for patch and create vpa
/kind bug
Current vpa crd has empty subresource field, that leads to metadata.generation increase on vpa status update.
The controller-runtime has [GenerationChangedPredicate](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/predicate#GenerationChangedPredicate) to filter out update status event for cr, but it not work for vpa.
This PR add status field in subresource on crd yaml and add new ClusterRole system:vpa-actor to patch /status subresource.
The metadata.generation only increase on vpa spec update.
Fixes #5675 
Previous …
=> Add subresource status for vpa
