cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
/kind bug
This PR is cherry-picked, which backports https://github.com/kubernetes/autoscaler/pull/5776 in CA-1.27
Part of https://github.com/kubernetes/autoscaler/issues/5888
```release-note
None
```
```docs
```
=> Backport #5776 [cluster-autoscaler] "Change magnum to use control-plane role" into CA1.27

cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
/kind bug
This PR is cherry-picked,  which backports #5776 in CA-1.24
Part of #5888
```release-note
None
```
```docs
```
=> Backport #5776 [cluster-autoscaler] "Change magnum to use control-plane role" into CA1.24

cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go
/kind bug
This PR is cherry-picked, which backports https://github.com/kubernetes/autoscaler/pull/5776 in CA-1.25
Part of https://github.com/kubernetes/autoscaler/issues/5888
```release-note
None
```
```docs
```
=> Backport #5776 [cluster-autoscaler] "Change magnum to use control-plane role" into CA1.25

cluster-autoscaler/core/static_autoscaler.go
/kind feature
Currently unneeded node groups are deleted only if scale down isn't in cooldown, so in particular if there was a scale up in a given loop, no unneeded node group will get deleted. There are certain scenarios in which that might turn out problematic - eg if scale up fails in every loop, the node groups won't be deleted for a long time. At the same time, unneeded node groups might affect scale up failures (e.g. quota issues).
Due to that, we can decouple unneeded node group deletion from the rest of scale down logic. 
```release-note
NONE
```
```docs
```
=> Remove unneeded node groups regardless of scale down being in cooldown.

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/estimator/binpacking_estimator_test.go, cluster-autoscaler/estimator/cluster_capacity_threshold.go, cluster-autoscaler/estimator/cluster_capacity_threshold_test.go, cluster-autoscaler/estimator/estimation_context.go, cluster-autoscaler/estimator/estimator.go, cluster-autoscaler/estimator/sng_capacity_threshold.go, cluster-autoscaler/estimator/sng_capacity_threshold_test.go, cluster-autoscaler/estimator/static_threshold.go, cluster-autoscaler/estimator/threshold.go, cluster-autoscaler/estimator/threshold_based_limiter.go, cluster-autoscaler/estimator/threshold_based_limiter_test.go, cluster-autoscaler/metrics/metrics.go
/kind feature
Introduce new binpacking limit (`Threshold`) interface for threshold based limiter.
Instead of static node cap, we can have an array of thresholds, that compute estimation limits based on parameters set both at construction and runtime. It will give us the ability to tune the performance of the binpacking in future.
This PR implements 3 thresholds:
1. Static maximum node & maximum duration
2. Static cluster-wide node number limit
3. Similar node groups capacity threshold
It is alternative implementation of #5883, but having orchestrator populating `EstimationContext` instead of constructing limits/thresholds, which gives us ability to inject thresholds outside of orchestrator if context has enough data for them.
@BigDarkClown @x13n
=> Implement configurable thresholds for threshold based estimator

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/clusterstate/providers/max_node_provision_time_provider.go, cluster-autoscaler/clusterstate/testutils.go, cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Due to the dependency of the MaxNodeProvisionTimeProvider on the context
the provider was extracted to a dedicated package and injected to the ClusterStateRegistry after context creation.
/kind cleanup
Adds ClusterStateRegistry to the AutoscalingContext, it will allow custom cloud providers to track the node group health.
```release-note
NONE
```
=> Add ClusterStateRegistry to the AutoscalingContext

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_util.go
/kind bug
In https://github.com/kubernetes/autoscaler/pull/5548, I had added support for faster backoff on a failed provisioning state. We recently found a bug where a many simultaneous updates to the network profiles of a running VMs in a VMSS could sometimes fail with a `ProvisioningState/failed/NetworkingInternalOperationError` error. This would be reflected in the `vm.ProvisioningState` (which represents the status of the _last_ provisioning operation on the VM), and would result in the VMSS size being decreased and the running VM instance being removed without first properly draining the running pods on the node.
This PR adds behavior to also consider the PowerState of the VM when determining if an OutOfResources error should be created -- it now only sets the OutOfResource error if …
=> Azure: Bugfix: Check PowerState before setting OutOfResources on instance 

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
- happens when CA tries to check if the unmanaged fargate node is a part of ASG (it isn't)
- and keeps on logging error
/kind bug
Fixes  #5842 (and adds tests)
* Scenario: EKS cluster running on fargate but uses CA to scale some non-fargate nodegroups
* Problem: CA reads all K8s nodes including fargate ones and checks if the instance is present in AWS (by calling [HasInstance](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L131)). This leads to error and causes log flooding (fargate is not a part of any ASG).
Fixes  #5842
```release-note
Fixed: CA tries to check if unmanaged fargate node exists in AWS and keeps on logging error message
```
```docs
```
=> fix: CA on fargate causing log flood

cluster-autoscaler/cloudprovider/aws/README.md, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/config/const.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/eligibility/eligibility.go, cluster-autoscaler/core/scaledown/eligibility/eligibility_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodegroupconfig/node_group_config_processor.go, cluster-autoscaler/processors/nodegroupconfig/node_group_config_processor_test.go, cluster-autoscaler/utils/test/test_utils.go
/kind feature
We want to support the ability to specify `IgnoreDaemonSetsUtilization` per nodegroup through ASG tags. Why? It is to cater for the following case (among other possible cases):
1. `IgnoreDaemonSetsUtilization` is set `false` globally because we want to consider daemonsets when calculating node resource utilization. This works well for ASGs/nodegroups which have large nodes and daemonsets utilization doesn't contribute much to node resource utilization. Due to this, we have no problem during node scale down. 
2. But, we also have some ASGs/nodegroups with small nodes where daemonsets utilization contributes a lot to the node resource utilization. Due to this, the nodes might not get scaled down because node resource utilization doesn't fall below …
=> feat: set `IgnoreDaemonSetsUtilization` per nodegroup for AWS

cluster-autoscaler/main.go
/kind bug
Cluster Autoscaler is in a migrating state where we make two decisions to filter down deletion candidates. We filter candidates in the Planner using the legacy maxEmptyBulkDelete flag, and we also filter down nodes in the cropNodesForDeletion function in the actuator that uses the maxScaleDownParallelism value. 
This leads to the following scenario
1) Neither MaxEmptyBulkDelete or MaxScaleDownParallelism is respected and the minimum of the two is taken, so if we aim to Delete 1000 nodes with MaxEmptyBulkDelete, but MaxScaleDownParallelism is set to 10(its default) then we only delete 10 Nodes, and the 1000 nodes are removed from the unneeded nodes map, causing them to have to wait the full unneeded time again before being canidates for deletion, and then we will only delete 10 …
=> fix: setting maxEmptyBulkDelete, and maxScaleDownParallelism to be the same value

cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go, cluster-autoscaler/core/scaledown/budgets/budgets.go
This PR fixes a bug where node deletions could sequentially even if parallelism is used. This changes AddNodes function from NodeDeletionBatcher to only add nodes synchronously, but continue with processing them in a goroutine.
Additionally the PR removes some dead code and changes map keys from NodeGroups to their IDs to make it less error prone for the future.
Shoutout to @krzysied who found this bug.
=> Re-introduce asynchronous node deletion and clean node deletion logic.

builder/Dockerfile
/kind bug
This change set golang:1.20.4 instead golang:1.20 as the base image. 1.20.5 and 1.20.6 are currently bad versions.
Fixes #5953
```release-note
NONE
```
=> Use fixed version of golang image

cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go
/kind flake
In the `TestBinpackingLimiter` test we assert the best option, despite the fact that it is undeterministic. This causes flake if the `ng2` is returned as a first node group.
=> Fix TestBinpackingLimiter flake

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/utils/node_instances_cache_test.go
/kind bug
CA doesn't handle well situation when instance is in error state (thus no pods can schedule on to it) and node pool is at min size, so it cannot scale down the faulty node.
In this situation the node is considered to be still upcoming, so CA still registers the fake "upcoming node" and CA doesn't trigger scale up immediately, only after 15 minutes (when the node passes the timeout for registration). In order to fix this, we should not inject the fake upcoming node, if we already detected it's in error state.
```release-note
NONE
```
=> Fix: Do not inject fakeNode for instance which has errors on create

cluster-autoscaler/utils/taints/taints.go, cluster-autoscaler/utils/taints/taints_test.go
- this taint leads to unexpected behavior
- users expect CA to consider the taint when autoscaling
/kind bug
Fixes #4097 
```release-note
Removed: `CriticalAddonsOnly` taint will not be cleaned from template nodes anymore. This is a *backwards incompatible* change. Check https://github.com/kubernetes/autoscaler/issues/4097 for more information. 
```
```docs
```
=> fix: don't clean `CriticalAddonsOnly` taint from template nodes

cluster-autoscaler/main.go
fix: setting maxEmptyBulkDelete, and maxScaleDownParallelism to be the same value
Fixes #
```release-note
```
```docs
```
=> cherry-pick: Merge pull request #5890 from Bryce-Soghigian/bsoghigian/respecting-bulk-delete

vertical-pod-autoscaler/README.md
Triggered by a [conversation on slack](https://kubernetes.slack.com/archives/C09R1LV8S/p1689102593778659): Adapt the limitations section to make clear that VPA doesn't scale individual Pods, but requires a controller. Previously it seemed that you would get initial recommendations, but just no evictions/updates. This may have been true in the times of `v1beta1`, when we still had a `selector` in the VPA CRD, but I don't think this is still possible.
```release-note
NONE
```
=> Adapt limitations for Pods without controller

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/config/const.go, cluster-autoscaler/config/test/config.go, cluster-autoscaler/main.go, cluster-autoscaler/simulator/predicatechecker/schedulerbased.go, cluster-autoscaler/simulator/predicatechecker/schedulerbased_test.go, cluster-autoscaler/simulator/predicatechecker/testchecker.go, cluster-autoscaler/utils/scheduler/scheduler.go, cluster-autoscaler/utils/scheduler/scheduler_test.go
/kind feature
**Problem**
1. We don't have a mechanism to to tweak configuration for default plugins acting on `PreFilter` and `Filter` extension points (which is used in predicate checker).
2. We don't have a way to support simulating custom scheduler logic without re-compiling the CA
This PR introduces `--scheduler-config-file` flag to 
1. tweak configuration for default plugins
~2. add support for [scheduler extenders](https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/scheduler_extender.md) so that the predicate checker can call an external filter URL.~ DECIDED AGAINST GOING FORWARD WITH EXTENDERS. Check https://github.com/kubernetes/autoscaler/pull/5708#issuecomment-1538647324 and …
=> feat: support custom scheduler config (without extenders)

cluster-autoscaler/main.go
/kind cleanup
/kind feature
Parallel drain is already working in GKE for a while and can safely be used as a default mode of operation. Additionally, there are currently two implementations of scale down logic, which affects maintainability. This is a step towards removing the legacy logic.
Fixes #5079
```release-note
Parallel drain of cluster nodes is now enabled by default.
```
```docs
```
=> Enable parallel drain by default.

cluster-autoscaler/cloudprovider/builder/builder_all.go
/kind bug
This PR updates the  `go:build` tag for missing cloud providers values in the [builder_all.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/builder/builder_all.go) file. 
Fixes #5942
```release-note
None
```
```docs
```
=> Update the `go:build` tag for missing cloud providers.

cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go
/kind bug
This PR fixed the `go:build` tags for ovhcloud in the [builder_ovhcloud.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go) file
Fixes #5940
```release-note
NONE
```
```docs
```
=> Fixed `go:build` tags for ovhcloud

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/estimator/binpacking_estimator_test.go, cluster-autoscaler/estimator/estimator.go
/kind refactor
Add PostPackingFunc, so the BinPackingEstimator can be extended easily.
```release-note
NONE
```
=> Add PostPackingFunc to be run at the end of the estimation logic

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go, cluster-autoscaler/metrics/metrics.go
Adds a metric to observe unexpected course of scale-down.
```release-note
NONE
```
=> Add a metric to observe nodes pending deletion after a finished scale-down phase

cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go
/kind bug
This PR is cherry-picked, which backports  in #5941 and #5943 CA1.25
Part of #5988
```release-note
None
```
```docs
```
=> Backport #5941 and #5943[CA]`Fixed go:build tags for ovhcloud` and `Update the go:build tag for missing cloud providers` into CA1.25

cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go
/kind bug
This PR is cherry-picked, which backports in #5941 and #5943 CA1.26
Part of #5988
```release-note
None
```
```docs
```
=> Backport #5941 and #5943[CA]`Fixed go:build tags for ovhcloud` and `Update the go:build tag for missing cloud providers` into CA1.26

cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go
/kind bug
This PR is cherry-picked, which backports in #5941 and #5943 CA1.27
Part of #5988
```release-note
None
```
```docs
```
=> Backport #5941 and #5943[CA]`Fixed go:build tags for ovhcloud` and `Update the go:build tag for missing cloud providers` into CA1.27

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
/kind feature
Adds more visibility to the GCE errors. Issues caused by invalid reservations will have a dedicated error code.
(Credit to @kawych for the code)
```release-note
NONE
```
=> Add error code for invalid reservations to GCE client

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Fixes a bug, where a regular scale-down for "ZeroOrMaxNodeScaling" node groups was performed as intended, but error cases were handled like all other node groups.
For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
Bugfix: ZeroOrMaxNodeScaling option is supported also for error scenarios (node creation timeout or errors).
```
-->
```docs
```
=> Support ZeroOrMaxNodeScaling node groups when cleaning up unregistered nodes

cluster-autoscaler/clusterstate/clusterstate.go
Fixes NPE when we pass nil as a node to GetGpuInfoForMetrics
```release-note
NONE
```
```docs
```
=> Don't pass nil nodes to GetGpuInfoForMetrics

balancer/deploy/controller.yaml
/kind bug
Fixes #
Prior to change:
```
I0718 02:32:46.477651       1 controller.go:144] Processing balancer kube-public/balancer-poc
W0718 02:32:46.489904       1 controller.go:194] Failed to update status of balancer kube-public/balancer-poc: balancers.balancer.x-k8s.io "balancer-poc" is forbidden: User "system:serviceaccount:kube-system:balancer-controller" cannot update resource "balancers/status" in API group "balancer.x-k8s.io" in the namespace "kube-public"
I0718 02:32:46.489999       1 event.go:294] "Event occurred" object="kube-public/balancer-poc" fieldPath="" kind="Balancer" apiVersion="balancer.x-k8s.io/v1alpha1" type="Warning" reason="StatusNotUpdated" message="balancers.balancer.x-k8s.io \"balancer-poc\" is forbidden: User …
```
=> fix: balancer RBAC permission to update balancer status

cluster-autoscaler/cloudprovider/builder/builder_all.go, cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go
/kind bug
This PR is cherry-picked, which backports  in #5941 and #5943 CA1.24
Part of #5988
```release-note
None
```
```docs
```
=> Backport #5941 and #5943[CA]`Fixed go:build tags for ovhcloud` and `Update the go:build tag for missing cloud providers` into CA1.24

vertical-pod-autoscaler/FAQ.md
As discussed in today's SIG meeting: Let's add the contract for VPA's support for Custom Resources more explicitly to the FAQ, as this question [keeps](https://github.com/kubernetes/autoscaler/issues/5836) [coming](https://github.com/kubernetes/autoscaler/issues/5925) [back](https://github.com/kubernetes/autoscaler/issues/3766).
```release-note
NONE
```
=> Add requirement for Custom Resources to VPA FAQ

cluster-autoscaler/FAQ.md
This tiny PR just fixes a broken hyperlink in the FAQ.
```release-note
None
```
=> Fix broken hyperlink

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
/kind feature
Implements KEP-4831: Control VPA eviction behavior based on scaling direction and resource
API for #4831
Implementation is done in #5599
```release-note
```
```docs
```
=> API for KEP-4831: Control VPA eviction behavior based on scaling direction and resource

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
Updates the description for `ResourcePolicy` and also `Limit control` README for how to disable VPA recommendations for individual containers.
Fixes # [5973](https://github.com/kubernetes/autoscaler/issues/5973)
```release-note
```
```docs
```
=> VPA: Update ResourcePolicy description and limit control README

cluster-autoscaler/cloudprovider/magnum/README.md
/kind bug
This PR fixed the hyperlink for `Node group auto discovery` in [README.md](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/magnum/README.md#autoscaler-deployment) under the Magnum Cloud Provider.
Fixes #
```release-note
None
```
```docs
```
=> Fixed the hyperlink for Node group auto discovery.

cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/budgets/budgets.go
For atomically scaled groups with both empty and drainable nodes, we need to wait for both sets of nodes before proceeding with deletion. Before this change, batch size was set separately for empty and drainable node sets.
1st commit: test case exposing error with batch size
2nd commit: fix for the error with batch size
3rd commit: some extra validation and fix for tests (test cases leak state)
4th commit: test case exposing error with atomic groups interfering with each other's scale down (fails with `-race`)
5th commit: fix for the error with atomic groups interfering with each other's scale down
Sent for review together because changes depend on the previous ones, happy to sqush/split based on review comments.
/kind bug
```release-note
Fixes issue where scale down of atomically scaled …
```
=> Set batch size to target size for atomically scaled groups

vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go, vertical-pod-autoscaler/pkg/recommender/main.go
/kind feature
Adds the basic auth for Prometheus provider in the VPA recommender, e.g adds the `username` and `password` options.
Fixes #5534.
I didn't find any document to update or any kind of tests to add. If you have any suggestions please feel free to ask.
```release-note
adds the `--username` and `--password` flags to ensure secure communication with Prometheus in the VPA recommender.
```
=> [VPA] feat: add prometheus basic auth in the VPA recommender

cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler.go, cluster-autoscaler/core/scaledown/budgets/budgets.go, cluster-autoscaler/processors/nodes/post_filtering_processor.go
/kind bug
Properly handle calls to `NodeGroup.GetOptions()` that return `cloudprovider.ErrNotImplemented` in the scale down path.
Previously scale down was broken for providers not implementing this method. I assume this was introduced in #5695 but did not do a bisect to figure out if this was actually the PR that broke it.
Fixes #6037
There were a few more calls to `NodeGroup.GetOptions()` that do not handle `cloudprovider.ErrNotImplemented` in `cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go` & `cluster-autoscaler/core/static_autoscaler.go`. I was not sure If these also need fixes, because the issue I was experiencing was related to scale down and went away with the changes in this PR.
```release-note
NONE
```
```docs
```
=> fix: scale down broken for providers not implementing NodeGroup.GetOptions()

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
GCE supports shared reservations where the reservation is in a different project than the project the cluster is in. Add GCE client method to get said reservations so logic can support shared reservations in the future. This change does not change autoscaling logic, just enables the ability to fetch reservations in other projects.
N/A
Fixes #
Added a new methods instead of changing an the existing one to be backwards compatible. The existing one is currently in use for GKE. 
```release-note
NONE
```
```docs
- [GCE Shared Reservation Docs]: https://cloud.google.com/compute/docs/instances/reservations-shared
```
=> Add fetch reservations in specific project

vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md
There are multiple aspects still to consider in the [VPA in-place updates AEP](https://github.com/kubernetes/autoscaler/edit/master/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md). This PR adds a section listing them so that we don't miss them before implementation starts.
```release-note
NONE
```
=> Add details to consider section to VPA in-place updates AEP

cluster-autoscaler/Dockerfile.s390x, cluster-autoscaler/Makefile
/kind feature
This PR can help build s390x auto scalar image
Fixes #
The PR against master for adding s390x support https://github.com/kubernetes/autoscaler/pull/6020
```release-note
NONE
```
```docs
```
=> cherry pick #6020- Adding support to s390x arch

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
This allows you to define a Secret that was created outside the Helm chart for the Azure (or AWS) cluster-autoscaler configuration so that the secret can be securely added to Kubernetes. A common method of this would be the [external-secrets-operator](https://external-secrets.io/) or [vault-secrets-operator](https://github.com/ricoberger/vault-secrets-operator).
Fixes # n/a
```release-note
Allow using an externally created secret instead of using the one the Helm chart creates
```
```docs
```
=> Allow using an externally created secret instead of using the one the Helm chart creates

cluster-autoscaler/FAQ.md, vertical-pod-autoscaler/RELEASE.md
Fix links to the testgrid dashboard
Upstream Issue [https://github.com/kubernetes/test-infra/issues/30370](https://github.com/kubernetes/test-infra/issues/30370)
```release-note
NONE
```
```docs
NONE
```
=> fix: Broken links to testgrid dashboard

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
/kind feature
The default is to send a new request every 500ms, this will instead use an exponential backoff while waiting for the server the create.
-
-
```release-note
NONE
```
```docs
```
=> feat(hetzner): use less requests while waiting for server create

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/clusterrole.yaml, charts/cluster-autoscaler/templates/role.yaml
/kind feature
This PR adjusts the RBAC for the CAPI mode in a way that only verbs that the API-Server knows are used for resources.
This is mostly helpful for people that auto generate their RBAC from the kube API-Server
```release-note
NONE
```
```docs
```
=> update RBAC to only use verbs that exist for the resources

cluster-autoscaler/.gitignore
Adds s390x binaries to the CA's gitignore after #6020 being merged.
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> CA - Git ignore s390x arch binaries

cluster-autoscaler/utils/kubernetes/listers.go
/kind bug
Pods in process of being deleted should be filtered out from being considered for scale up. This should be done before filter out schedulable, as the pod can "virtually" consume capacity of the cluster.
This being in line with schedule code (https://github.com/kubernetes/kubernetes/blob/cb56c4c627fc627b2eb1ba69a435cc3f205f7363/pkg/scheduler/schedule_one.go#L350-L354), which will no schedule pods that have a deletionTimestamp set.
This has further implications on scale down also, the pod can stay alive for their gracePeriod, however, they will stay pending and consume "virtual" capacity on the cluster, having impact on scale down decisions.
Fixes #
```release-note
```
```docs
```
=> Add support to filter out pods being deleted.

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
/kind bug
Fixes the cloudProvider.name reference for OCI, correct is `oci`, not `oci-oke`
This is found both in a comment and in a condition
Autoscaler crashes with `oci-oke`:
```
1 cloud_provider_builder.go:29] Building oci-oke cloud provider.
1 cloud_provider_builder.go:50] Unknown cloud provider: oci-oke
```
The examples are correct ([example 1](https://github.com/kubernetes/autoscaler/blob/574c534e4fe7e3f09466cf8dca9af9a3bb9e9c66/cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-config.yaml#L150), [example 2](https://github.com/kubernetes/autoscaler/blob/574c534e4fe7e3f09466cf8dca9af9a3bb9e9c66/cluster-autoscaler/cloudprovider/oci/examples/oci-ip-cluster-autoscaler-w-principals.yaml#L150), [example …
=> fix(chart): cloudProvider name reference for OCI

cluster-autoscaler/cloudprovider/cloudstack/examples/cluster-autoscaler-standard.yaml
/kind bug
This PR added the missing RBAC permission in the [examples](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloudstack/examples/cluster-autoscaler-standard.yaml) mentioned under the Cloudstack Cloud Provider.
Fixes #6070
```release-note
None
```
```docs
```
=> Added the RBAC Permission to Cloudstack

cluster-autoscaler/core/scaledown/budgets/budgets_test.go
/kind cleanup
Tests were missing cases where the empty and drain nodes are from the same atomic group.
This is a follow-up pr addressing this comment: https://github.com/kubernetes/autoscaler/pull/6034/files#r1291199619
```release-note
NONE
```
```docs
```
=> Add additional test cases to scale down budget tests.

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go, vertical-pod-autoscaler/pkg/utils/test/test_recommendation.go, vertical-pod-autoscaler/pkg/utils/test/test_utils.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go, vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go
vertical-pod-autoscaler/admission-controller
/kind bug
Using external recommender that was coming with a bug, we ended up with a VPA object that was presenting a recommendation for a resource that has an empty name:
```
resources:
limits:
cpu: "1"
memory: 3Gi
requests:
"": "0"              <== empty key
cpu: "1"
ephemeral-storage: 10Gi
memory: 3Gi
```
In this PR we are proposing to sanitise the recommendation by removing any resource key that would be empty so that the admission is not pushing "garbage" to the pods.
Possible extension: instead of purging empty key, we could have a list of allowed resourceName given as input parameter of the admission. This would also allow us to purge unknown resource or the one coming with typo.
If a recommendation comes with a resource key that is …
=> David.benque/prevent empty resource propagation upstream 2

cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go
/kind bug
Fixes #6025 
```release-note
NONE
```
```docs
```
=> Fix index out of range when fail to get instance types

cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
/kind feature
By processing this annotation first, pods that would match also other, subsequent rules (e.g. pods without a controller), will generate the `NotSafeToEvictAnnotation` instead of e.g. `NotReplicated`.
This allows marking pods as not safe to evict to change the warning to one that can be more effectively ignored, e.g. for ephemeral build pods that are known to not be backed by a controller, and should not be evicted.
Fixes #5434
Unsure if this counts, please advise :) 
```release-note
```
```docs
```
=> Process annotation marking pod as not safe to evict first

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
It's [`recommender-name`](https://github.com/kubernetes/autoscaler/blob/cd5ed0be530e2313f762e30042cb324b768507f6/vertical-pod-autoscaler/pkg/recommender/main.go#L48C40-L48C56) not `name`. Documentation added in #5231
fixes #5451
=> Fix flag name in documentation

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind bug
Fixes #3845
While touching the code I also removed the use of the deprecated constant `apiv1.LabelZoneRegionStable` in a test
```release-note
Scale up from 0 now working with existing AWS EBS CSI PersistentVolume without having to add tag to ASG
```
=> fix: add aws csi zone label to node template

cluster-autoscaler/proposals/provisioning-request.md
/kind feature
This PR adds a new AEP to support a new CRD in cluster autoscaler. \
This novel API will allow users to specify a dependency between a group of pods.
```release-note
NONE
```
N/A
=> Introduce AEP with Provisioning Request CRD

cluster-autoscaler/main.go
Disable ```dynamic-node-delete-delay-after-taint-enabled``` by default
/kind bug
Dynamic-node-delete-delay-after-taint is a newly implemented fix for a race condition between scheduler and CA and it is guarded by a flag. Therefore the default value of the flag should be ```false``` and it can be enabled by a flag in the manifest.
Fixes #
NONE
```release-note
```
```docs
```
=> Disable dynamic-node-delete-delay-after-taint-enabled by default

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go
/kind feature
Adds more error codes related to the reservations increasing the visibility of GCE Errors.
```release-note
NONE
```
=> Add additional error codes for invalid reservations to GCE client

cluster-autoscaler/core/test/common.go, cluster-autoscaler/processors/nodes/scale_down_set_processor.go, cluster-autoscaler/processors/processors.go
Split ScaleDownSet processor into two processors doing their individual tasks. This allows more flexibility when overriding these processors, such as adding another targeted processor to the pipeline, or removing one of the processors if it's not needed.
CC @towca 
```release-note
NONE
```
=> Refactor ScaleDownSet processor into a composite processor

cluster-autoscaler/core/test/common.go, cluster-autoscaler/processors/nodes/scale_down_set_processor.go
Addresses post-submission comments on #6103
CC @towca
=> Fix processors order in tests and add a comment explaining this order

cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler_test.go
/kind cleanup
Multiple atomic node groups with slightly different names were being created because the test cases *change the state* of the node group. This pr refactors the tests and now for each test we create its own node group, isolating the test cases.
This is a follow-up pr addressing this comment: https://github.com/kubernetes/autoscaler/pull/6034#discussion_r1291183138
```release-note
NONE
```
```docs
```
=> Refactor `getStartDeletionTestCases` function so that each test case operates on its own node group.

cluster-autoscaler/cloudprovider/externalgrpc/examples/external-grpc-cloud-provider-service/wrapper/wrapper.go, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_cloud_provider.go, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_cloud_provider_test.go, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_node_group.go, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_node_group_test.go, cluster-autoscaler/cloudprovider/externalgrpc/protos/externalgrpc.proto, cluster-autoscaler/cloudprovider/externalgrpc/protos/externalgrpc_grpc.pb.go
/kind bug
/kind feature
Some `CloudProvider` and `nodeGroup` methods are optional: if a cloud provider does not implemented an optional method, it should return the `cloudprovider.ErrNotImplemented` error, this error is expected and the CA gracefully handles it.
Currently there is no way to pass this specific error from a grpc based cloud provider: The protobuf definition incorrectly states that an rpc is optional or a grpc error will result in using defaults, but this is not correct at the moment: in case of grpc errors, the client passes a generic error that is not correctly handled by the CA, so currently all rpc must be implemented.
This PR allows grpc cloud providers to not implement optional methods: a not implemented method should pass the grpc error code 12 `Unimplemented`, if so, …
=> fix(cloudprovider/exteranlgrpc): properly handle unimplemented methods

cluster-autoscaler/main.go
/kind bug
Currently, setting up the autoscaler pod with --elect-leader flags causes 
unknown flag: elect-leader error.
The current main function leaves out the elect leader flag from the flag initialization. 
This PR will fix that.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: add elect-leader flag to the pflag

vertical-pod-autoscaler/common/version.go
/kind feature
Updates the version of VPA to 1.0.0 as agreed in SIG-autoscaling.
Precursor to cutting the next release of VPA.
Part of the release process, as documented [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md).
Part of release process #6113
=> Bump VPA version to 1.0.0 in preparation for 1.28 release

cluster-autoscaler/main.go
/kind bug
Previously, SharedInformerFactory.Start was called before core.NewAutoscaler. That had the effect that any new informer created as part of core.NewAutoscaler, in particular in kubernetes.NewListerRegistryWithDefaultListers, never got started.
One of them was the DaemonSet informer. This had the effect that the DaemonSet lister had an empty cache and scale down failed with:
I0920 11:06:36.046889   31805 cluster.go:164] node gke-cluster-pohly-default-pool-c9f60a43-5rvz cannot be removed: daemonset for kube-system/pdcsi-node-7hnmc is not present, err: daemonset.apps "pdcsi-node" not found
This was on a GKE cluster with cluster-autoscaler running outside of the cluster on a development machine. I have no idea which "real" deployments of cluster-autoscaler might be affected by this. …
=> fix incomplete startup of informers + broken scale down

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6090 into CA1.26
Part of #6136
```release-note
None
```
```docs
```
=> Backport #6090 [CA] Add aws csi zone label to node template into CA1.26

vertical-pod-autoscaler/hack/vpa-process-yamls.sh
Fix vpa-up.sh script by removing duplicate recommender from the vpa-process-yamls.sh. Tweak that script so that it can accept recommender-externalmetrics as an argument if someone wants to run that separately by having the script look in both the `deploy` and `e2e` directories.
Having both recommenders in this list breaks vpa-up.sh, see #6141.
/kind bug
This fixes a small bug when running `vpa-up.sh`, which is a step in the VPA release process.
See #6141 for full details.
Fixes #6141 
I've taken a look at [the PR](https://github.com/kubernetes/autoscaler/pull/5576) that introduced this change and I *don't think* this should break anything but would love to confirm with @lallydd.
```release-note
NONE
```
```docs
NONE
```
=> Fix vpa-up.sh script by removing duplicate recommender

cluster-autoscaler/cloudprovider/oci/nodepools/consts/annotations.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/kubernetes/ready.go, cluster-autoscaler/utils/taints/taints.go, cluster-autoscaler/utils/taints/taints_test.go
/kind bug
/kind cleanup
Following up on PR #5659,
- `startup-taint` flag is added and combined with `ignore-taint` flag so both will have the same effect
- Prefix `startup-taint.cluster-autoscaler.kubernetes.io/` is added to be similar to `ignore-taint.cluster-autoscaler.kubernetes.io/` and behaves the same
- `status-taint` flag is added and passed to autoscaling options
- Prefix `status-taint.cluster-autoscaler.kubernetes.io/` is added to ignore nodes with taints starting with it when scaling up.
- Updates `TaintConfig` to have prefixes list instead of relying on constant hardcoded values
> Updates `ToBeDeletedByClusterAutoscaler` & `NodeNotReadyReason.IgnoreTaint` might have side effects which affect third party providers which rely on these taints
Allows status-taints to be specified …
=> Adds support for startup taints and extends support for status taints

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6090 into CA1.24
Part of #6136
```release-note
None
```
```docs
```
=> Backport #6090 [CA] Add aws csi zone label to node template into CA1.24

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6090 into CA1.245
Part of #6136
```release-note
None
```
```docs
```
=> Backport #6090 [CA] Add aws csi zone label to node template into CA1.25

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6090 into CA1.27
Part of #6136
```release-note
None
```
```docs
```
=> Backport #6090 [CA] Add aws csi zone label to node template into CA1.27

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6090 into CA1.28
Part of #6136
```release-note
None
```
```docs
```
=> Backport #6090 [CA] Add aws csi zone label to node template into CA1.28

cluster-autoscaler/main.go
/kind bug
InitLogs unconditionally disables contextual logging, while ValidateAndApply checks the feature gate for that. InitLogs must come first, otherwise
--feature-gates=ContextualLogging=true
doesn't work.
```release-note
Fixed support for --feature-gates=ContextualLogging=true.
```
=> fix log initialization

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/drain.go, cluster-autoscaler/core/scaledown/legacy/legacy.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/scaledowncandidates/emptycandidates/empty_candidates_sorting.go, cluster-autoscaler/processors/scaledowncandidates/emptycandidates/empty_candidates_sorting_test.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/cluster_test.go, cluster-autoscaler/simulator/drain.go, cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/simulator/drainability/context.go, cluster-autoscaler/simulator/drainability/rules/mirror/rule.go, cluster-autoscaler/simulator/drainability/rules/mirror/rule_test.go, cluster-autoscaler/simulator/drainability/rules/rules.go, cluster-autoscaler/simulator/drainability/status.go, cluster-autoscaler/simulator/options/nodedelete.go
/kind feature
This is one of several CLs to move all drain conditions to drainability rules. Once complete, clients implementing custom drainability rules will have full control over the scale-down of nodes.
Notable changes:
- Split out drainability rules into separate packages. `simulation/drainability:Rule.Drainable()` function now takes a `DrainContext`. This function can assume that `DrainContext` is not nil.
- Refactor NodeDeleteOptions for reuse in the drainability package. `simulation:NodeDeleteOptions` has been split into two structs: `simulation/options:NodeDeleteOptions` and `drainability/rules:Rules`. Consumers of this struct have been updated accordingly.
```release-note
None
```
=> Refactor scale-down for better integration with drainability rules

cluster-autoscaler/cloudprovider/aws/CA_with_AWS_IAM_OIDC.md
Fixes the documentation to point to the correct documentation for auto-discovery for cluster-autoscaler
Fixes #6171
The AWS documentation referenced in the current doc does not exist anymore and the official AWS docs were updated to point to this repo a while ago.
```release-note
NONE
```
```docs
```
=> Fixing clutter-autoscaler docs to point to correct tutorial for auto-discovery

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
**What type of PR is this?**
/kind bug
**What this PR does / why we need it:**
It's possible that an EC2 instance is in the Terminated state for multiple autoscaler loops, so to avoid trying to terminate it more than once and causing the bug seen for this initial fix, we include this check as well.
Also, make the log more verbose and write out what state we found the instance in.
This builds upon this change: https://github.com/kubernetes/autoscaler/pull/5411
=> aws: check for all possible Terminated states

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/hack/vpa-process-yaml.sh
(See #6153 for same PR in master)
/kind feature
Updates the various versions of VPA throughout the codebase. Part of the [release process](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md#finalize-release).
#6113
```release-note
NONE
```
```docs
NONE
```
=> Bump default VPA version to 1.0.0 in vpa-release-1.0 branch

vertical-pod-autoscaler/hack/vpa-process-yamls.sh
/kind feature
This PR is cherry-picked, which backports #6151 into the VPA 1.0 release branch. See the [comment](https://github.com/kubernetes/autoscaler/issues/6113#issuecomment-1738562106) for the information.
Fixes #
```release-note
None
```
```docs
```
=> Cherry pick #6151 to VPA release 1.0 branch

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/hack/vpa-process-yaml.sh
(See #6152 for same PR for release branch)
/kind feature
Updates the various versions of VPA throughout the codebase. Part of the [release process](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md#finalize-release).
#6113
```release-note
NONE
```
```docs
NONE
```
=> Bump default VPA version to 1.0.0 in master

vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh
/kind bug
The autoscaler/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh script fails with the following error:
```
Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
req: Skipping unknown subject name attribute "/CN"
Error adding extensions defined via -addext
40C7A2C93F7F0000:error:0580008C:x509 certificate routines:X509at_add1_attr:duplicate attribute:../crypto/x509/x509_att.c:86:
```
This is because https://github.com/kubernetes/autoscaler/blob/cf8c507d2421e7ed8b8d6f9ae44e9a624e221c43/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh#L54 adds a `-addext` argument that duplicates what is already added in https://github.com/kubernetes/autoscaler/blob/cf8c507d2421e7ed8b8d6f9ae44e9a624e221c43/vertical-pod-autoscaler/pkg/admission-controller/gencert …
=> Fix duplicate -addext when generating certificates with admission-controller/gencerts.sh

vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh
This PR is to cherrypick #6149 into the release branch.
/kind bug
The autoscaler/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh script fails with the following error:
```
Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
req: Skipping unknown subject name attribute "/CN"
Error adding extensions defined via -addext
40C7A2C93F7F0000:error:0580008C:x509 certificate routines:X509at_add1_attr:duplicate attribute:../crypto/x509/x509_att.c:86:
```
This is because https://github.com/kubernetes/autoscaler/blob/cf8c507d2421e7ed8b8d6f9ae44e9a624e221c43/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh#L54 adds a `-addext` argument that duplicates what is already added in https://github.com/kubernetes/autoscaler/blob/cf8c507d2421e7ed8b8d6f9ae44e9a624e221c43/ …
=> fix duplicate -addext when generating certificates

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/processors/binpacking/binpacking_limiter.go
/kind cleanup
Extends the BinpackingLimiter interface with a method called after binpacking finishes. This can be used to analyse the final binpacking state as well as cleanup the internal binpacking state.
=> Extend BinpackingLimiter interface

cluster-autoscaler/simulator/cluster.go
/kind cleanup
This PR helps improve supportability by improving the clarity of an informational logging statement that adds context for the log's reader.  The message will go from:
```
I1003 18:48:06.916732       1 cluster.go:155] ip-10-0-41-141.ec2.internal for removal
```
to:
```
I1003 18:48:06.916732       1 cluster.go:155] Simulating node ip-10-0-41-141.ec2.internal for removal
```
Previously, it was difficult to determine the _for removal_ action.  Also, prefixing the node's name with `node` is consistent with other node-named log statements.
Fixes #6170
=> Clarify simulation for removal log statement

cluster-autoscaler/cloudprovider/aws/README.md
This PR is cherry-picked, which backports #5373 into CA1.25
Part of #6138
```release-note
None
```
```docs
```
=> Backport #5373 [CA] AWS - Update Docs all actions IAM policy into CA1.25

cluster-autoscaler/cloudprovider/clusterapi/README.md
Adds the 'watch' verb to the RBAC example. If the 'get' and 'list' verbs are present, but the 'watch' verb is absent, the autoscaler reports an error. For example:
```log
cluster-autoscaler-b8949d8b9-76vcd E1006 22:11:43.056176       1 reflector.go:148] k8s.io/client-go/dynamic/dynamicinformer/informer.go:108: Failed to watch infrastructure.cluster.x-k8s.io/v1beta2, Resource=vcdmachinetemplates: unknown
```
Fixes #
```release-note
```
```docs
```
=> clusterapi: Add 'watch' verb to scale-from-zero example

cluster-autoscaler/estimator/binpacking_estimator.go
/kind bug
When PermissionToAddNode gets called without actually adding a new node, the node counter in the thresholdBasedEstimationLimiter gets out of sync with the actual number of new nodes. This can happen when the "is the last node empty" check triggers.
The solution used here is to rearrange the checks so that PermissionToAddNode is followed by adding a new node. Alternatively, it might also be possible to pass the current number of nodes as parameter.
Found while investigating scale up scenarios with dynamic resource allocation support, see https://kubernetes.slack.com/archives/C09R1LV8S/p1695991972759879.
```release-note
CA might have created less nodes than desired with a message about "Capping binpacking after exceeding threshold of 4 nodes" even though it then didn't actually …
```
=> autoscaler: fix premature end of binpacking

addon-resizer/Makefile
/kind feature
Bumps addon-resizer release tag from 1.8.19 to 1.8.20 to release #5993
```release-note
NONE
```
=> Bump addon-resizer version 1.8.20 to release #5993

cluster-autoscaler/cloudprovider/externalgrpc/OWNERS
Add one of the following kinds:
/kind cleanup
This PR adds owners for externalgrpc cloud provider
According to https://github.com/kubernetes/autoscaler/pull/5198 Adding owners for externalgrpc cloud provider
```
NONE
```
```
```
=> Updated the owners of externalgrpc cloudprovider

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
/kind cleanup
This PR explicitly overrides the `$AZURE_TENANT_ID` and `$AZURE_CLIENT_ID` environment variables in the `AzureManager` unit tests, to allow test cases to pass in the event that the local test environment already includes values for those env vars.
Fixes #
```release-note
NONE
```
```docs
```
=> Azure: add ENV coverage to UT

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go
/kind feature
Adds a new function to `ClusterStateRegistry` called `HasNodeGroupStartedScaleUp()` which returns whether the node group has a scale up request without checking if there are any upcoming nodes in the node group.
```release-note
NONE
```
```docs
```
=> Add HasNodeGroupStartedScaleUp to cluster state registry.

addon-resizer/OWNERS, vertical-pod-autoscaler/OWNERS
jbartosik et al are transitioning off of workload autoscalers (incl vpa and addon-resizer). kwiesmueller is on the new team and has agreed to take on reviewer/approver responsibilities.
/kind cleanup
```release-note
NONE
```
=> Add kwiesmueller to OWNERS

cluster-autoscaler/proposals/provisioning-request.md
Expands the CAP with one more annotation that needs to be set on the Pods.
This will allow CA to have more information about the expected ProvReq.
Fixes #
```release-note
```
```docs
```
=> Add information about provisioning-class-name annotation.

vertical-pod-autoscaler/pkg/utils/limitrange/limit_range_calculator.go
/kind bug
Suppress warn logs `The sharedIndexInformer has started, run more than once is not allowed` appear at every admission-controller startup
Fixes #6156
```release-note
NONE
```
```docs
```
=> Fix multiple run of informers created in fetcher.go

cluster-autoscaler/simulator/drain_test.go, cluster-autoscaler/simulator/drainability/rules/daemonset/rule.go, cluster-autoscaler/simulator/drainability/rules/daemonset/rule_test.go, cluster-autoscaler/simulator/drainability/rules/localstorage/rule.go, cluster-autoscaler/simulator/drainability/rules/longterminating/rule.go, cluster-autoscaler/simulator/drainability/rules/longterminating/rule_test.go, cluster-autoscaler/simulator/drainability/rules/mirror/rule.go, cluster-autoscaler/simulator/drainability/rules/mirror/rule_test.go, cluster-autoscaler/simulator/drainability/rules/notsafetoevict/rule.go, cluster-autoscaler/simulator/drainability/rules/pdb/rule.go, cluster-autoscaler/simulator/drainability/rules/pdb/rule_test.go, cluster-autoscaler/simulator/drainability/rules/replicacount/rule.go, cluster-autoscaler/simulator/drainability/rules/replicated/rule.go, cluster-autoscaler/simulator/drainability/rules/rules.go, cluster-autoscaler/simulator/drainability/rules/rules_test.go, cluster-autoscaler/simulator/drainability/rules/safetoevict/rule.go, cluster-autoscaler/simulator/drainability/rules/safetoevict/rule_test.go, cluster-autoscaler/simulator/drainability/rules/system/rule.go, cluster-autoscaler/simulator/drainability/rules/terminal/rule.go, cluster-autoscaler/simulator/drainability/rules/terminal/rule_test.go, cluster-autoscaler/simulator/drainability/status.go
/kind feature
Adds a mechanism for one rule to selectively override other rules. This allows for custom rules that override some outcomes (e.g. BlockDrain -> DrainOk) while not overriding others (e.g. SkipDrain).
```release-note
NONE
```
=> Add mechanism to override drainability status

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
/kind bug
The architecture label in the build generic labels method of the Cluster API provider is now populated using the `cpu.GetDefaultScaleFromZeroArchitecture().Name()` method.
The method allows users deploying the cluster-autoscaler to define the default architecture to be used by the cluster-autoscaler for scale up from zero via the `--scale-up-from-zero-default-arch` flag. `Amd64` is kept as a fallback for historical reasons and to maintain compatibility with current providers.
The `SystemArchitecture` type and the functions for parsing architecture names are copied over from the GCE implementation, to be generic across all the defined cloud providers.
However, the GCE implementation and the other cloud providers are currently left untouched.
The introduced changes will not take …
=> The autoscaler does not scale node groups on non-amd64 clusters when pods explicitly require non-amd64 nodes in node affinity

cluster-autoscaler/cloudprovider/hetzner/README.md, cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind feature
Currently the Hetzner provider is very lacking and the autoscaler does not know beforehand which custom taints/labels the provided node pools have.
This PR adds support for a each nodepool to have their own initconfig (currently breaking change, but will see if I have the time to make it backwards compatible). It also supports multi arch node pools. I have been running this a month or so~ build my own image
```release-note
Currently this PR introduces a breaking change. However if required I can refactor it so it is backwards compatible
```
=> feat: each node pool can now have different init configs

addon-resizer/nanny/nanny_lib.go, addon-resizer/nanny/nanny_lib_test.go
https://github.com/kubernetes/autoscaler/pull/5993 added a 'scalingMode' but reversed it's sense (so if you specified 'containers' it would scale on nodes, and vice versa).
/kind bug
```release-note
NONE
```
=> Fix scalingMode

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/utils/taints/taints.go, cluster-autoscaler/utils/taints/taints_test.go
/kind feature
Adds and implements node taints count metric.
```release-note
Adds and implements node taints count metric.
```
=> Adds and implements node taints count metric.

addon-resizer/Makefile
=> Bump go version from 1.20.5 to 1.20.10 (current)

.github/workflows/ci.yaml, cluster-autoscaler/cloudprovider/brightbox/brightbox_node_group.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/budgets/budgets.go, cluster-autoscaler/go.mod, cluster-autoscaler/go.sum
/kind cleanup
Bump cluster-autoscaler golang version to 1.21.
The Docker build was already using `golang:1.21.3` - it's only the CI and go.mod that was lacking behind.
K/K is already on 1.21.3 as well: https://github.com/kubernetes/kubernetes/blob/master/.go-version
With upgrade, I've removed min/max functions, which are now build-in: https://tip.golang.org/ref/spec#Min_and_max
```release-note
NONE
```
=> Bump CA golang to 1.21

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache_test.go
/kind feature
This PR is cherry-picked, which backports https://github.com/kubernetes/autoscaler/pull/5596 into CA 1.26
```release-note
Allow k8s.io/cluster-autoscaler/resources/<resource>:<quantity> tags on AWS managed nodegroups (in addition to ASGs) to indicate availability of custom resources or ephemeral storage in a scale-from-zero scenario
```
```docs
```
=> Backport #5596 [CA] AWS - Add support for tags on AWS managed nodegroups to indicate resources into CA 1.26

cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache_test.go
/kind feature
This PR is cherry-picked, which backports https://github.com/kubernetes/autoscaler/pull/5596 into CA 1.27
```release-note
Allow k8s.io/cluster-autoscaler/resources/<resource>:<quantity> tags on AWS managed nodegroups (in addition to ASGs) to indicate availability of custom resources or ephemeral storage in a scale-from-zero scenario
```
```docs
```
=> Backport #5596 [CA] AWS - Add support for tags on AWS managed nodegroups to indicate resources into CA 1.27

vertical-pod-autoscaler/README.md
This pull request addresses the need to update the Custom Resource Definition (CRD) and Role-Based Access Control (RBAC) configuration to support Vertical Pod Autoscaler (VPA) versions 0.15.0 and above. Additionally, it provides guidance on rolling back to version (<=0.14.0) if necessary.
Fixes #5921 
```release-note
```
```docs
```
=> add note for CRD and RBAC handling for VPA (>=1.0.0)

addon-resizer/Dockerfile
running on non-root user
/kind feature
for security
```docs
[root@xxx ~]# docker ps -a | grep -m1 addon-resizer
3d1e321b83e6   c34e5cebf87d                    "/pod_nanny --contai…"   20 hours ago   Up 20 hours                           k8s_addon-resizer_kube-state-metrics-57b5dfb58d-x4ks8_kube-system_3abe5325-2b42-407f-b955-efe311254c3c_0
[root@xxx~]# docker top 3d1e
UID            PID          PPID           C      STIME         TTY           TIME                CMD
nfsnobo+       6068         6049           0      Nov02         ?              00:01:09            /pod_nanny --container=kube-state-metrics --healthcheck-address=:8082 --cpu=100m --extra-cpu=1m --memory=100Mi --extra-memory=2Mi --threshold=5 --deployment=kube-state-metrics
```
=> update addon-resizer non-root running

cluster-autoscaler/core/scaledown/eligibility/eligibility.go
/kind feature
Improves user experience as described in https://github.com/kubernetes/autoscaler/issues/6222
https://github.com/kubernetes/autoscaler/issues/6222
I would also change the `%f` to `%.2f` in the messages to remove the extra significant digits that provide no added value from the output. Please let me know in the comments if it's a good idea, I'll update my commit if needed.
```release-note
Disambiguated wording in the log messages related to node removal ineligibility caused by high resource allocation
```
```docs
```
=> Disambiguate the resource usage node removal eligibility messages

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/main.go
/kind cleanup
There are two parts to this change:
1) Remove kube-client RateLimiting - replay on APF for apiserver protection. Details: https://github.com/kubernetes/kubernetes/issues/111880
2) Remove dedicated client for events, for the same reasons
```release-note
NONE
```
/assign @x13n
=> Cleanup: Remove separate client for k8s events

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl
=> Update README.md: Link to Cluster-API

cluster-autoscaler/cloudprovider/aws/README.md
Fixes #
```release-note
```
```docs
```
=> Removed node drainer, kept node termination handler

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
/kind cleanup
`func (o *ScaleUpOrchestrator) ScaleUp(` has code to dead with "No unschedulable pods"
but that can never happen because it is only called from static_autoscaler.go after checking that there are pods
`if len(unschedulablePodsToHelp) == 0 { ... else`
so this code is unnecessary and adds confusion and should be removed.
```release-note
NONE
```
=> ScaleUp is only ever called when there are unscheduled pods

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/_helpers.tpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/templates/secret.yaml
/kind feature
This allows templating of the `autoDiscovery.clusterName` parameter in the Helm chart so that you can do more dynamic processing of the cluster's name.
Fixes # n/a
```release-note
Template the autoDiscovery.clusterName variable in the Helm chart
```
=> Template the autoDiscovery.clusterName variable in the Helm chart

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
Allows overriding the `revisionHistoryLimit` on the cluster autoscaler deployment. The default value is 10 which is the implicit Kubernetes default.
#5701 was previously opened to add this but the submitter cancelled the PR.
```release-note
NONE
```
```docs
```
=> fix: Add revisionHistoryLimit override to cluster-autoscaler

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
/kind bug
allows users to mark nodes for "do not spam me about missing aws instance"
fixes https://github.com/kubernetes/autoscaler/issues/6096
not ready to be merged, just for discussion
```release-note
TODO
```
=> allow users to avoid aws instance not found spam

cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup.go
/kind bug
Fixes #5656
```release-note
NONE
```
```docs
```
=> fix: handle error when listing machines

cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup.go
/kind bug
Cherry pick https://github.com/kubernetes/autoscaler/commit/4c53c2063c82859170396fecb5d3ce5451d87ffb
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #6298 fix: handle error when listing machines into 1.27

cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup.go
/kind bug
Cherry pick https://github.com/kubernetes/autoscaler/commit/4c53c2063c82859170396fecb5d3ce5451d87ffb
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #6298 fix: handle error when listing machines into 1.26

cluster-autoscaler/cloudprovider/rancher/rancher_nodegroup.go
/kind bug
Cherry pick https://github.com/kubernetes/autoscaler/commit/4c53c2063c82859170396fecb5d3ce5451d87ffb
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #6298 fix: handle error when listing machines into 1.28

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go
/kind cleanup
Always enable the ephemeral-storage feature
```release-note
Flag --gce-expander-ephemeral-storage-support is now Deprecated. The ephemeral-storage support is always enabled and the flag itself would be ignored.
```
/assign @x13n
=> Remove gce-expander-ephemeral-storage-support flag

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_url.go, cluster-autoscaler/cloudprovider/gce/gce_url_test.go, cluster-autoscaler/config/autoscaling_options.go
/kind feature
This PR allows overriding Domain Suffix in calls made to GCE cloud provider. If it's not specified the default domain suffix is used.
=> Allow overriding domain suffix in GCE cloud provider.

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/enhancements/4831-control-eviction-behavior/README.md, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
/kind bug
Fix '.spec.updatePolicy.evictionRequirements.resources' to be plural in yaml. Seems like this slipped through the cracks in #5599. We didn't release the CRD yet, so changing it shouldn't be an issue?
=> Fix '.spec.updatePolicy.evictionRequirements.resources' to be plural in yaml

builder/Dockerfile, cluster-autoscaler/go.mod
Looks like specifying the Go patch version in go.mod might've been a mistake: https://github.com/kubernetes/kubernetes/pull/121808.
=> Set Go versions to the same settings kubernetes/kubernetes uses

cluster-autoscaler/provisioningrequest/provreqwrapper/wrapper.go, cluster-autoscaler/provisioningrequest/provreqwrapper/wrapper_test.go, cluster-autoscaler/provisioningrequest/service/service.go, cluster-autoscaler/provisioningrequest/service/v1beta1client/client.go, cluster-autoscaler/provisioningrequest/service/v1beta1client/client_test.go, cluster-autoscaler/provisioningrequest/service/v1beta1client/testutils.go
/kind feature
Implementing ProvisioningRequest service that is required for further implementation of ProvisioningRequest CRD proposal.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md
=> Implement ProvisioningRequest service

cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/action.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/certificate.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/client.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/datacenter.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/error.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/firewall.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/floating_ip.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/hcloud.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/image.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/internal/instrumentation/metrics.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/iso.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/load_balancer.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/load_balancer_type.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/location.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/metadata/client.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/network.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/placement_group.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/primary_ip.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/iso.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/server.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/server_type.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/volume.go
/kind bug
There was a bug in `hcloud-go` that causes Rate Limiting issues for customers of the Hetzner Provider: https://github.com/hetznercloud/hcloud-go/pull/322
Generated by:
```shell
UPSTREAM_REF=v2.4.0 hack/update-vendor.sh
```
```release-note
Fixed a bug where too many requests are sent to the Hetzner Cloud API, causing Rate Limit issues 
```
```docs
```
=> chore(deps): update vendored hcloud-go to 2.4.0

cluster-autoscaler/cloudprovider/civo/README.md, cluster-autoscaler/cloudprovider/civo/civo_manager.go, cluster-autoscaler/cloudprovider/civo/civo_node_group.go, cluster-autoscaler/cloudprovider/civo/civo_node_group_test.go, cluster-autoscaler/cloudprovider/civo/examples/cluster-autoscaler-node-pool.yaml
/kind feature
Implement `TemplateNodeInfo()` method for civo cloudprovider
Observe that civo cloudprovider doesn't support scale node group zero because `TemplateNodeInfo()` was not implemented
NONE
```release-note
Scale up node group from zero to max
```
=> Implement TemplateNodeInfo for civo cloudprovider

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_cloud_provider.go, cluster-autoscaler/cloudprovider/oci/instancepools/oci_cloud_provider.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/kubernetes/client.go
/kind cleanup
This is a follow-up to the closed PR: https://github.com/kubernetes/autoscaler/pull/6180 (<- check this PR for more info on the current PR)
No issue exists for this. Can create one if needed. 
Fixes #
```release-note
NONE
```
```docs
```
=> refactor(*): move getKubeClient to utils/kubernetes

cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling.go, cluster-autoscaler/cloudprovider/alicloud/alicloud_auto_scaling_test.go
/kind bug
I noticed an issue in the implementation of the NodeGroupForNode function in the alicloud provider of the cluster-autoscaler project. This issue results in the function sometimes returning nil for nodes in a specific nodeGroup.
Currently, the implementation regenerates the cache data and calls Alibaba Cloud to query all instances when a specified instance is not found. However, the DescribeScalingInstances function has default values of pageSize=10 and pageNumber=1, which only returns a subset of the data.
To address this issue, I have made the following modifications:
Modify the code logic to perform multiple queries based on the TotalCount of response information, ensuring the complete set of instances in the nodeGroup is returned.
I am a frequent user of cluster-autoscaler …
=> fix: alicloud the function NodeGroupForNode return nil

cluster-autoscaler/main.go
/kind bug
Cherry pick of https://github.com/kubernetes/autoscaler/pull/6115
Fixes #
```release-note
none
```
```docs
```
=> Backport of #6115 fix: add elect-leader flag to the pflag into 1.26

cluster-autoscaler/main.go
/kind bug
Cherry pick of https://github.com/kubernetes/autoscaler/pull/6115
Fixes #
```release-note
none
```
```docs
```
=> Backport of #6115 fix: add elect-leader flag to the pflag into 1.27

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
/kind feature
Bump cluster-autoscaler version.
Actually, my autoscaler is stuck with:
```
static_autoscaler.go:354] Failed to get node infos for groups: ASG "eksctl-xyz" uses the unknown EC2 instance type "m7i.2xlarge"
```
```release-note
Update CA Chart's `appVersion` and `image.tag` value from 1.27.2 to 1.28.1
```
=> Helm: update cluster-autoscaler to 1.28

vertical-pod-autoscaler/pkg/admission-controller/Dockerfile, vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Dockerfile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Dockerfile, vertical-pod-autoscaler/pkg/updater/Makefile
/kind cleanup
Switch to multistage Dockerfiles to build the multi-platform binaries with `docker buildx`. The previous setup with multiple `make` targets was quite complicated and isn't necessary to achieve what we're trying to do. In particular, this change does:
* remove some make targets, as they are no longer needed: `build-binary-with-vendor`, `build-binary-with-vendor-*`, `sub-push`, `docker-builder`, `build-in-docker`, `build-in-docker-*`
* remove the second `docker-build` execution from the `docker-push` make target, so we only build the image once 
* Move the logic from `build-in-docker` to a build stage in the Dockerfile for each component
* Making use of the [built-in variables for desired build platform](https://docs.docker.com/engine/reference/builder/#automatic-platform-args- …
=> Switch to multistage build Dockerfiles for VPA

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
The Hetzner Cloud API returns "Actions" for anything asynchronous that happens inside the backend. When creating a new server multiple actions are returned: `create_server`, `start_server`, `attach_to_network` (if set).
Our current code waits for the `create_server` and if it fails, it makes sure to delete the server so cluster-autoscaler can create a new one immediately to provide the required capacity. If one of the "follow up" actions fails though, we do not handle this. This causes issues when the server for whatever reason did not start properly on the first try, as then the customer has a shutdown server, is paying for it, but does not receive the additional capacity for their Kubernetes cluster.
This commit fixes the bug, by awaiting all actions returned by the create …
=> fix(hetzner): insufficient nodes when boot fails

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
Backport of https://github.com/kubernetes/autoscaler/pull/6364 to `v1.26`.
Fixes #
```release-note
Fixed a bug where failed servers are kept for longer than necessary
```
```docs
```
=> [v1.26] fix(hetzner): insufficient nodes when boot fails

builder/Dockerfile
/kind cleanup
- update golang to the latest release available for 1.20 in the builder dockerfile
/assign @feiskyer
Fixes #
```release-note
update golang to the latest release available for 1.20 in the builder dockerfile
```
```docs
```
=> [cluster-autoscaler-1.28] update golang to the latest release available for 1.20 in the builder dockerfile

builder/Dockerfile
/kind cleanup
- update golang to the latest release available for 1.19 in the builder dockerfile
/assign @feiskyer
Fixes #
```release-note
update golang to the latest release available for 1.19 in the builder dockerfile
```
```docs
```
=> [cluster-autoscaler-1.26] update golang to the latest release available for 1.19 in the builder dockerfile

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
/kind bug
https://github.com/kubernetes/autoscaler/pull/6265 introduced the ability for users to apply an annotation to cluster Nodes that are not managed by the autoscaler, reducing the amount of "spam" messages logged by the controller.
However, the chosen annotation key `k8s.io/cluster-autoscaler/enabled` is not a valid identifier - https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set - which expects only a _single_ DNS prefix.
Attempting to manually add this annotation to an existing node will fail -
```
```
Note that the use of the `k8s.io/cluster-autoscaler/enabled` _tag_ is valid within AWS.
This PR uses a valid identifier `k8s.io/cluster-autoscaler-enabled`
Fixes #6300
```release-note
NONE
```
```docs
```
=> fix: update node annotation used to limit log spam with valid key

cluster-autoscaler/cloudprovider/hetzner/README.md, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
This provides a better way of letting someone know that it's also possible to use the id of a network, firewall or ssh key instead of only the name as before mentioned on the readme.
=> fix: updated readme for hetzner cloud provider

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/utils/backoff/backoff.go, cluster-autoscaler/utils/backoff/exponential_backoff.go, cluster-autoscaler/utils/backoff/exponential_backoff_test.go
/kind feature
This PR adds more detailed error information to backoff interface & implementation. 
This is needed as it will allow getting this info easily to show them as a reason for backoff.
#6318 
NONE
=> Add error details to autoscaling backoff.

cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/utils/backoff/backoff.go, cluster-autoscaler/utils/backoff/exponential_backoff.go, cluster-autoscaler/utils/backoff/exponential_backoff_test.go
Change-Id: I1f812d4d6f42db97670ef7304fc0e895c837a13b
/kind cleanup
In Backoff() method in backoff interface, we already accept ErrorInfo as non-pointer, so no need to make it pointer to make the code simpler.
#6318
```release-note
NONE
```
=> Make backoff.Status.ErrorInfo non-pointer.

cluster-autoscaler/main.go
…d-node-group-count flags
/kind bug
deprecating unused flags
Fixes # 
#6228 
```release-note
NONE
```
```docs
```
=> Deprecate unused node-autoprovisioning-enabled and max-autoprovisioned-node-group-count flags

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go, cluster-autoscaler/utils/test/test_utils.go
/kind feature
This makes Cluster Autoscaler work with MIGs that have pagination enabled. Without this change, a subset of instances may be never listed.
Fixes #
```release-note
[GCE] Support for paginated MIG instance listing.
```
```docs
```
=> [GCE] Support paginated instance listing

cluster-autoscaler/cloudprovider/externalgrpc/README.md, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_cloud_provider.go, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_cloud_provider_test.go, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_node_group.go, cluster-autoscaler/cloudprovider/externalgrpc/externalgrpc_node_group_test.go
/kind feature
Introduce a optional field to config timeout of grpc calls. / The grpc provider impl may call other api which operates longer than 5s, resulted in `context deadline exceeded`.
Fixes #
No.
```release-note
externalgrpc: timeout of grpc calls could be specified through `cloud-config`
```
```docs
```
=> allow specifing grpc timeout rather than hardcoded 5 seconds

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
/kind bug
This PR fixes some chart errata introduced in https://github.com/kubernetes/autoscaler/pull/6186 (mea culpa). Specifically:
- PR https://github.com/kubernetes/autoscaler/pull/6186 removed the "AKS" vmType configuration, and so we don't to default the `azureVMType` chart value to be "AKS"
- PR https://github.com/kubernetes/autoscaler/pull/6186 removed the Azure provider "clusterName" configuration, so we don't want a reference to that as a required value in the chart deployment spec
- PR https://github.com/kubernetes/autoscaler/pull/6186 removed the Azure provider "nodeResourceGroup" configuration, so we don't want a reference to that as a required value in the chart deployment spec
Here is a representative example in PR https://github.com/kubernetes/autoscaler/pull/6186 of the …
=> azure: fix chart bugs after AKS vmType deprecation

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/drain.go, cluster-autoscaler/core/scaledown/actuation/drain_test.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler_test.go, cluster-autoscaler/core/scaledown/actuation/priority.go, cluster-autoscaler/core/scaledown/actuation/priority_test.go, cluster-autoscaler/core/scaledown/eligibility/eligibility_test.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go, cluster-autoscaler/utils/test/test_utils.go
/kind bug
This PR implements a priority based evictor for pod eviction in scale down. This evictor can be used to enforce non-critical pods get evicted before critical pods. When this evictor is used it groups pods by priority and evicts group by group from lowest priority to highest.
Fixes #
This PR introduces a new evictor that can be enabled and configured by ```scale-down-drain-node-priority-and-grace-periods``` flag. Setting and empty string will disable the feature and use the default unordered evictor.
A new flag (```--drain-priority-config```) is introduced which allows users to configure drain behavior during scale-down based on pod priority. The new flag is mutually exclusive with ```--max-graceful-termination-sec```. ```--max-graceful-termination-sec``` can still be used if the …
=> Implement priority based evictor

vertical-pod-autoscaler/RELEASE.md
VPA's latest release was a major one. This PR update the release documentation to reference 1.X VPA versions instead of 0.X, since that's no longer applicable.
NONE
=> Update VPA release README to reference 1.X VPA versions.

cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml
Deprecation and fix
1. Adding RBAC permissions to watch, list and get `MachinePools`
```
E1227 10:17:59.322411       1 reflector.go:147] k8s.io/client-go/dynamic/dynamicinformer/informer.go:108: Failed to watch cluster.x-k8s.io/v1beta1, Resource=machinepools: failed to list cluster.x-k8s.io/v1beta1, Resource=machinepools: machinepools.cluster.x-k8s.io is forbidden: User "system:serviceaccount:test-cluster:cluster-autoscaler" cannot list resource "machinepools" in API group "cluster.x-k8s.io" at the cluster scope
```
2. As of Kubernetes version 1.24, the control plane (formerly master) nodes no longer have the deprecated node-role.kubernetes.io/master label.
=> Fix:Adding missing RBAC + Update Deployment tolerations

cluster-autoscaler/cloudprovider/civo/civo_manager.go, cluster-autoscaler/cloudprovider/civo/civo_node_group.go, cluster-autoscaler/cloudprovider/civo/civo_node_group_test.go
Add Gpu count to node template
/kind feature
Add Gpu count to node template
NONE
```release-note
```
```docs
```
=> [civo] Add Gpu count to node template

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go, cluster-autoscaler/utils/kubernetes/client.go
Partially undo #6274. I noticed that with this change CA get rate limited and slows down significantly (especially during large scale downs).
/kind bug
Fix a regression - I noticed that CA is significantly slower (especially during large scale downs) because of rate limiting.
=> Restore flags for setting QPS limit in CA

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
/kind bug
Passes the kubeClientBurst and kubeClientQPS flags to the clusterapi provider k8s clients to allow tuning of client and avoid excessive client-side throttling. 
Fixes https://github.com/kubernetes/autoscaler/issues/6333
```release-note
kubeClientBurst and kubeClientQPS flags are now passed to the clusterapi provider k8s clients
```
```docs
```
=> Pass Burst and QPS client params to clusterapi k8s clients

cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
/kind feature
Skip non azure nodes (providerID) to support on-premise kubernetes nodes.
Fixes #
If kubernetes cluster has non azure node, node-autoscaller wouldn't start.
Azure Cloud is highly compatible with hybrid cloud environments,
This feature facilitates the seamless integration of on-premise infrastructure with Azure Cloud.
```release-note
```
```docs
```
=> Azure: skip non azure nodes

cluster-autoscaler/FAQ.md, cluster-autoscaler/main.go
Specify the maximum value in the CA scale-down rule
To clarify which criteria is currently used to scale down a node.
=> Clarify Scale down rule in the documentation (FAQ.md)

cluster-autoscaler/clusterstate/utils/status_test.go
Change-Id: Ie6a2301f4ab8673b9ad2f8f7de1faa166ac295b4
/kind cleanup
Refactors tests in `cluster-autoscaler/clusterstate/utils/status_test.go`.
The tests are currently poorly structured and contains a lot of duplication, so this PR converts them to table tests.
```release-note
NONE
```
=> Refactors status_test.go to use table tests

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
/kind bug
Passes the kubeClientBurst and kubeClientQPS flags to the clusterapi provider k8s clients to allow tuning of client and avoid excessive client-side throttling. 
Fixes https://github.com/kubernetes/autoscaler/issues/6333
```release-note
kubeClientBurst and kubeClientQPS flags are now passed to the clusterapi provider k8s clients
```
```docs
```
Cherry pick of https://github.com/kubernetes/autoscaler/pull/6416
=> Pass Burst and QPS client params to capi k8s clients 1.28

cluster-autoscaler/utils/taints/taints.go, cluster-autoscaler/utils/taints/taints_test.go
/kind cleanup
Update the taint methods to take multiple taints as arguments instead of one. This can be used to optimize the number of API calls needed to add/delete more than one taint at the time.
```release-note
NA
```
=> Taint utils taking multiple taints

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/config/const.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch_test.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/observers/nodegroupchange/scale_state_observer.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_delay_processor.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_delay_processor_test.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_processor.go
/kind feature
We want to support `--scale-down-delay-after-*` per nodegroup so that if nodegroup A scales up, it doesn't block nodegroup B from scaling down (which is the case now). For details, check https://github.com/kubernetes/autoscaler/issues/3071
Fixes #3071
~This PR is still in WIP and PoC phase. The plan is to get an okay from the community before proceeding with the approach in this PR. If you have any feedback on the PR, I would love to have it.~ https://github.com/kubernetes/autoscaler/pull/5729#discussion_r1211156439 
```release-note
```
```docs
```
I had originally intended to support only `--scale-down-delay-after-add` and hence the name of the PR branch `vadasambar:feat/3071/scale-down-after-add-per-ng-poc`. But I have …
=> feat: support `--scale-down-delay-after-*` per nodegroup

cluster-autoscaler/metrics/metrics.go
/kind feature
Existing bucketing is inconsistent. Specifically, the second to last bucket is [100, 1000), which is huge and doesn't allow to differentiate between something that took 2m (120s) and something that took 15m (900s).
Fixes #
```release-note
function_duration_seconds metric is now more fine grained, using exponential bucketing.
```
```docs
```
=> Use exponential buckets for function_duration_seconds

cluster-autoscaler/cloudprovider/builder/builder_kwok.go, cluster-autoscaler/cloudprovider/kwok/kwok_helpers.go, cluster-autoscaler/cloudprovider/kwok/kwok_nodegroups.go, cluster-autoscaler/cloudprovider/kwok/kwok_provider.go, cluster-autoscaler/cloudprovider/kwok/kwok_provider_test.go, cluster-autoscaler/cloudprovider/kwok/kwok_types.go
/kind bug
When using the Kwok provider, CA quits when scaling down a node group because the Kwok provider cannot retrieve the node group name from a fake node. This PR primarily aims to fix this issue.
Additionally, I have fixed the target size when scaling up and down the node group.
<details>
<summary>kwok-provider-config</summary>
```yaml
apiVersion: v1
data:
config: |-
apiVersion: v1alpha1
readNodesFrom: configmap
nodegroups:
fromNodeLabelKey: "kwok-nodegroup"
nodes:
configmap:
name: kwok-provider-templates
kwok:
install: false
kind: ConfigMap
metadata:
name: kwok-provider-config
namespace: default
```
</details>
<details>
<summary>kwok-provider-templates</summary>
```yaml
apiVersion: v1
data:
templates: |-
apiVersion: v1
items:
- apiVersion: v1
kind: Node
metadata:
annotations: …
```
=> fix(kwok): prevent quitting when scaling down node group

vertical-pod-autoscaler/e2e/v1/full_vpa.go, vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/test/test_vpa.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
/kind bug
Fixes failing e2e tests for VPA. After the refactorings done in #5599, the tests started failing – but nobody realized this until now: #6389
This PR fixes the tests by doing two things:
* The way the new builder pattern for VPA test objects was introduced in the e2e tests had a problem with how recommendations are created. For the first container, a recommendation is created implicitly when you call `Build()` on the VPA object. This interferes with the pattern of `AppendRecommendation()`, which lead to a second entry in the `containerRecommendations` section, where one of those entries was empty.
* During the refactorings mentioned above, the test for the named recommender were broken and we didn't realize it. This PR brings back the recommender name for the VPA object created …
=> Fix VPA e2e test failures

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
/kind bug
Passes the kubeClientBurst and kubeClientQPS flags to the clusterapi provider k8s clients to allow tuning of client and avoid excessive client-side throttling. 
Fixes https://github.com/kubernetes/autoscaler/issues/6333
```release-note
kubeClientBurst and kubeClientQPS flags are now passed to the clusterapi provider k8s clients
```
```docs
```
Cherry pick of https://github.com/kubernetes/autoscaler/pull/6416
=> Pass Burst and QPS client params to capi k8s clients 1.29

cluster-autoscaler/simulator/drainability/rules/replicacount/rule.go, cluster-autoscaler/simulator/drainability/rules/replicacount/rule_test.go
/kind bug
The issue is described in #5977
Fixes #5977
Suppresses #6328
This PR is a continuation from #6328. Made the changes as requested by @x13n 
NONE
=> Allow draining when DaemonSet kind has custom API Group

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go, cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
Allows access to numeric instance id in GCE Cloud Provider implementation.
NONE
=> Introduce GceInstance that extends cloudprovider.Instance with NumericId

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/wrapper_orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/wrapper_orchestrator_test.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/provisioning_request_processors.go, cluster-autoscaler/processors/provreq/provisioning_request_processors_test.go, cluster-autoscaler/processors/status/scale_up_status_processor.go, cluster-autoscaler/provisioningrequest/apis/autoscaling.x-k8s.io/v1beta1/types.go, cluster-autoscaler/provisioningrequest/checkcapacity/condition.go, cluster-autoscaler/provisioningrequest/checkcapacity/condition_test.go, cluster-autoscaler/provisioningrequest/checkcapacity/orchestrator.go, cluster-autoscaler/provisioningrequest/checkcapacity/orchestrator_test.go, cluster-autoscaler/provisioningrequest/pods/pods.go, cluster-autoscaler/provisioningrequest/pods/pods_test.go, cluster-autoscaler/provisioningrequest/provreqclient/client_test.go, cluster-autoscaler/provisioningrequest/provreqclient/testutils.go, cluster-autoscaler/provisioningrequest/provreqwrapper/testutils.go, cluster-autoscaler/utils/kubernetes/client.go
/kind feature
part of implementation https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md
The full implementation of check-capacity is not completed yet, pods from ProvisioningRequest will be injected and processed in the following PRs. When the implementation is completed I'll add release-notes.
=> ScaleUp for check-capacity ProvisioningRequestClass

cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go
/kind bug
`unneededNodesLimit()` stops considering scale down nodes when this limit is reached.  However, if a nodepool which has nodes > this limit and only allowed for atomic scaledown will always starve.
Eg. Consider a nodepool with 1000 nodes in a cluster and `unneededNodesLimit()` = 500. Let's consider that this nodepool is only allowed to scale down atomically. The nodepool will always starve for scale down as the limit is 500 but we cannot scaledown 500 nodes, we can only scale down 1000 nodes.
Fixes #
```release-note
```
```docs
```
=> Consider atomic nodes

cluster-autoscaler/cloudprovider/oci/README.md
Update the doc on setting up cluster-autoscaler on Oracle platform with a security in mind.
The current documentation gives a wrong security sense by using the word `minimal`. I also remove that in my patch.
```release-note
```
```docs
```
=> doc: cluster-autoscaler: Oracle provider: Add small security note

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
/kind feature
Bump the Chart version to 9.35.0 and the CA image to 1.29.0
Fixes #
```release-note
Bump the Chart version to 9.35.0 and the CA image to 1.29.0
```
```docs
```
=> Bump CA Chart image to v1.29

cluster-autoscaler/OWNERS
From https://github.com/kubernetes/community/blob/4aac5c07b006acf242b9fddea7f67c7781e1eef7/community-membership.md#reviewer 
- member for at least 3 months **I have been a member for more than a year ([first PR](https://github.com/kubernetes/autoscaler/pull/5507))**
- Primary reviewer for at least 5 PRs to the codebase **[8 of them](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Avadasambar+is%3Amerged) merged ([rest](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Avadasambar))**
- Reviewed or merged at least 20 substantial PRs to the codebase **20+ of them ([12 merged](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Avadas …
=> chore:  add vadasambar to cluster-autoscaler reviewers

cluster-autoscaler/cloudprovider/equinixmetal/examples/cluster-autoscaler-svcaccount.yaml
/kind bug
This PR added the missing RBAC permission in the [example](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/equinixmetal/examples/cluster-autoscaler-svcaccount.yaml) mentioned under the equinixmetal Cloud Provider.
Fixes #6436
```release-note
NONE
```
```docs
```
=> Added the RBAC Permission to equinixmetal Cloud Provider.

cluster-autoscaler/core/static_autoscaler.go
/kind feature
This PR is cherry-picked, which backports #5901 into CA 1.26
Part of #6467
```release-note
None
```
```docs
```
=> Backport #5901 [CA] Remove unneeded node groups regardless of scale down being in cooldown into CA1.26

cluster-autoscaler/core/static_autoscaler.go
/kind feature
This PR is cherry-picked, which backports #5901 into CA 1.27
Part of #6467
```release-note
None
```
```docs
```
=> Backport #5901 [CA] Remove unneeded node groups regardless of scale down being in cooldown into CA1.27

cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/scaleup/orchestrator/wrapper_orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/wrapper_orchestrator_test.go, cluster-autoscaler/core/scaleup/scaleup.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/provisioningrequest/checkcapacity/orchestrator.go
/kind cleanup
The Estimator def: "Estimator calculates the number of nodes of given type needed to schedule pods.". It's part of expander and by definition is needed for ScaleUp only. Therefore it's REQUIRED on scaleup.Orchestrator and NOT NEEDED at all for "global" autoscaling context or options.
```release-note
"NONE"
```
/assign @x13n 
/cc @towca
/cc @MaciekPytel
=> Move estimatorBuilder from AutoscalingContext to Orchestrator Init

.github/workflows/ci.yaml, builder/Dockerfile
/kind bug
This PR fixed the Go version in [ci.yaml](https://github.com/kubernetes/autoscaler/blob/master/.github/workflows/ci.yaml) under GitHub workflows and [Dockerfile](https://github.com/kubernetes/autoscaler/blob/master/builder/Dockerfile) under builder directory.
Part #6521
```release-note
None
```
```docs
```
=> Bump go version.

cluster-autoscaler/processors/nodes/scale_down_set_processor.go, cluster-autoscaler/utils/klogx/defaults.go
Also, introduce default per-node logging quotas. For now, identical to the per-pod ones.
/kind cleanup
Reduces log spam.
Fixes #
```release-note
NONE
```
```docs
```
=> Reduce log spam in AtomicResizeFilteringProcessor

vertical-pod-autoscaler/e2e/v1/admission_controller.go, vertical-pod-autoscaler/e2e/v1/recommender.go, vertical-pod-autoscaler/e2e/vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/test/test_vpa.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go
/kind bug
Fixing the e2e test setup issues created by the helper refactorings in https://github.com/kubernetes/autoscaler/pull/5599
PR https://github.com/kubernetes/autoscaler/pull/6391 helped but some other issues were masked beyond these errors.
Fixes #6510 
```release-note
NONE
```
=> Fix e2e test setup

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/kube_env.go, cluster-autoscaler/cloudprovider/gce/kube_env_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go
/kind cleanup
Caching of kube-env for instance templates. The change greatly improves the CPU usage for idle clusters, as ~80% of the main loop time is spend on repetitive unmarshalling of kube-env.
The improvement is drastic for idle clusters even with only 3 MIGs. In my testing the loop time decreased from 1.25s to 0.25s.
=> GCE: Implement kube-env caching

cluster-autoscaler/cloudprovider/externalgrpc/examples/external-grpc-cloud-provider-service/main.go, cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go, cluster-autoscaler/cloudprovider/gce/localssdsize/local_ssd_size_provider.go, cluster-autoscaler/cloudprovider/gce/templates.go, cluster-autoscaler/cloudprovider/gce/templates_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go
/kind feature
Introduces `LocalSSDSizeProvider` interface to GCE cloud provider to be used to calculate local ssd disk size instead of using a plain constant.
Also introduces `SimpleLocalSSDProvider` struct implementing `LocalSSDSizeProvider` which returns a constant value `375GiB` to maintain original behaviour
```release-note
NONE
```
=> Introduce LocalSSDSizeProvider interface for GCE

cluster-autoscaler/clusterstate/clusterstate.go
Fix for https://github.com/kubernetes/autoscaler/issues/6524
=> Fix expectedToRegister to respect instances with nil status

cluster-autoscaler/go.mod, cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/provisioning_request_injector.go, cluster-autoscaler/processors/provreq/provisioning_request_injector_test.go, cluster-autoscaler/provisioningrequest/apis/autoscaling.x-k8s.io/v1beta1/types.go, cluster-autoscaler/provisioningrequest/checkcapacity/orchestrator.go, cluster-autoscaler/provisioningrequest/checkcapacity/processor.go, cluster-autoscaler/provisioningrequest/checkcapacity/processor_test.go, cluster-autoscaler/provisioningrequest/conditions/condition_test.go, cluster-autoscaler/provisioningrequest/conditions/conditions.go
/kind feature
Inject pods from ProvisioningRequest to unschedulable pods, so CA will try to run ScaleUp.
Part of implementation https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md
```release-note
Support for Check-capacity ProvisioningClass is added. To enable the feature set --enable-provisioning-requests=true. If there is capacity in the cluster for ProvisioningRequest of Check-capacity ProvisioniningClass, the Provisioned=True condition will be set and the capacity will be reserved from scheduling other ProvisioningRequest for 10 minutes. 
Note: ClusterAutoscaler doesn't block other pods to be scheduled on reserved capacity; ClusterAutoscaler can scale down reserved capacity.
```
=> Add ProvisioningRequest injector

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
This fixed requests for pods with ephemeral storage requests being denied due to insufficient ephemeral storage for the Hetzner provider.
=> [Hetzner] Fix missing ephemeral storage definition

cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-autodiscover.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-standard-msi.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-control-plane.yaml, cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml, cluster-autoscaler/cloudprovider/cherryservers/examples/cluster-autoscaler-deployment.yaml, cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml, cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment-control-plane.yaml, cluster-autoscaler/cloudprovider/magnum/examples/values-autodiscovery.yaml, cluster-autoscaler/cloudprovider/magnum/examples/values-example.yaml, cluster-autoscaler/cloudprovider/tencentcloud/README.md
Refactor references to taints & tolerations, replacing `master` key with `control-plane` across all the example YAMLs.
/kind cleanup
Fixes # https://github.com/kubernetes/autoscaler/issues/6561
NO
```docs
```
=> docs: update outdated/deprecated taints in the examples

cluster-autoscaler/Makefile
/kind cleanup
We're starting the process of moving away from the auto-scaler vendor directory to adopt Go modules. 
The pull request https://github.com/kubernetes/autoscaler/pull/6572 to remove the vendor directory will be paused for two months to ensure the community
has enough time to update their dependent systems. In parallel I will send an email to the SIG list to give
heads up. 
Fixes partially # https://github.com/kubernetes/autoscaler/issues/4878
```release-note
```
```docs
```
=> Add warning about vendor removal to Makefile build target

cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler_test.go
Fixes an issue where a failure of atomic (ZeroOrMaxNodeScaling) scale-down could affect subsequent scale-downs for the same node group. This bug doesn't affect non-atomic scale-downs.
```release-note
NONE
```
=> Fix a bug where atomic scale-down failure could affect subsequent atomic scale-downs

cluster-autoscaler/utils/test/test_utils.go
/kind cleanup
Adding a way to create test node with allocatable. Currently the existing method only supports specifying capacity.
```release-note
None
```
```docs
```
=> Add BuildTestNodeWithAllocatable test utility method.

cluster-autoscaler/cloudprovider/builder/builder_clusterapi.go
/kind bug
This change adds the informer factory as an argument to the `buildCloudProvider` function for clusterapi so that building with tags will work properly.
Fixes #6489 
this is the command i ran to confirm the build
```
go build --tags clusterapi -o ./cluster-autoscaler-amd64 
```
```release-note
NONE
```
```docs
```
=> add informer argument to clusterapi provider builder

cluster-autoscaler/cloudprovider/builder/builder_alicloud.go, cluster-autoscaler/cloudprovider/builder/builder_aws.go, cluster-autoscaler/cloudprovider/builder/builder_azure.go, cluster-autoscaler/cloudprovider/builder/builder_baiducloud.go, cluster-autoscaler/cloudprovider/builder/builder_bizflycloud.go, cluster-autoscaler/cloudprovider/builder/builder_brightbox.go, cluster-autoscaler/cloudprovider/builder/builder_cherry.go, cluster-autoscaler/cloudprovider/builder/builder_civo.go, cluster-autoscaler/cloudprovider/builder/builder_cloudstack.go, cluster-autoscaler/cloudprovider/builder/builder_digitalocean.go, cluster-autoscaler/cloudprovider/builder/builder_exoscale.go, cluster-autoscaler/cloudprovider/builder/builder_externalgrpc.go, cluster-autoscaler/cloudprovider/builder/builder_gce.go, cluster-autoscaler/cloudprovider/builder/builder_hetzner.go, cluster-autoscaler/cloudprovider/builder/builder_huaweicloud.go, cluster-autoscaler/cloudprovider/builder/builder_ionoscloud.go, cluster-autoscaler/cloudprovider/builder/builder_kamatera.go, cluster-autoscaler/cloudprovider/builder/builder_kubemark.go, cluster-autoscaler/cloudprovider/builder/builder_linode.go, cluster-autoscaler/cloudprovider/builder/builder_magnum.go, cluster-autoscaler/cloudprovider/builder/builder_oci.go, cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go, cluster-autoscaler/cloudprovider/builder/builder_packet.go, cluster-autoscaler/cloudprovider/builder/builder_rancher.go, cluster-autoscaler/cloudprovider/builder/builder_scaleway.go, cluster-autoscaler/cloudprovider/builder/builder_tencentcloud.go, cluster-autoscaler/cloudprovider/builder/builder_volcengine.go, cluster-autoscaler/cloudprovider/builder/builder_vultr.go
/kind bug
This PR adds the` informer factory` as an argument to the `buildCloudProvider` function in all the Cloud Providers builders (Where it is missing) so that building the Cluster Autoscaler with tags will work correctly.
Part of #6492
```release-note
None
```
```docs
```
=> Add informer argument to the CloudProviders builder.

cluster-autoscaler/cloudprovider/aws/README.md
Cluster autoscaler supports more expansion options than it used to
=> Update expander options for the AWS cloud provider README

cluster-autoscaler/cloudprovider/builder/builder_alicloud.go, cluster-autoscaler/cloudprovider/builder/builder_aws.go, cluster-autoscaler/cloudprovider/builder/builder_azure.go, cluster-autoscaler/cloudprovider/builder/builder_baiducloud.go, cluster-autoscaler/cloudprovider/builder/builder_bizflycloud.go, cluster-autoscaler/cloudprovider/builder/builder_brightbox.go, cluster-autoscaler/cloudprovider/builder/builder_cherry.go, cluster-autoscaler/cloudprovider/builder/builder_civo.go, cluster-autoscaler/cloudprovider/builder/builder_cloudstack.go, cluster-autoscaler/cloudprovider/builder/builder_clusterapi.go, cluster-autoscaler/cloudprovider/builder/builder_digitalocean.go, cluster-autoscaler/cloudprovider/builder/builder_exoscale.go, cluster-autoscaler/cloudprovider/builder/builder_externalgrpc.go, cluster-autoscaler/cloudprovider/builder/builder_gce.go, cluster-autoscaler/cloudprovider/builder/builder_hetzner.go, cluster-autoscaler/cloudprovider/builder/builder_huaweicloud.go, cluster-autoscaler/cloudprovider/builder/builder_ionoscloud.go, cluster-autoscaler/cloudprovider/builder/builder_kamatera.go, cluster-autoscaler/cloudprovider/builder/builder_kubemark.go, cluster-autoscaler/cloudprovider/builder/builder_linode.go, cluster-autoscaler/cloudprovider/builder/builder_magnum.go, cluster-autoscaler/cloudprovider/builder/builder_oci.go, cluster-autoscaler/cloudprovider/builder/builder_ovhcloud.go, cluster-autoscaler/cloudprovider/builder/builder_packet.go, cluster-autoscaler/cloudprovider/builder/builder_rancher.go, cluster-autoscaler/cloudprovider/builder/builder_scaleway.go, cluster-autoscaler/cloudprovider/builder/builder_tencentcloud.go, cluster-autoscaler/cloudprovider/builder/builder_volcengine.go, cluster-autoscaler/cloudprovider/builder/builder_vultr.go
/kind bug
This PR is cherry-picked, which backports #6491 and #6494 into CA 1.29
Part of #6492
```release-note
None
```
```docs
```
=> Backport #6491 and #6494 [CA] Add informer argument to the Cloud Providers builder into CA1.29

OWNERS
/kind cleanup
We don't currently have the same repo root OWNERS file as the default branch of the repo, meaning that approval is required from the addon-resizer OWNERS file, even for trivial changes such as #6400 
Adds a new repo root level OWNERS file with the same contents as [currently in the repo's default branch](https://github.com/kubernetes/autoscaler/blob/master/OWNERS). I haven't touched/updated the OWNERS file for the addon-resizer though we should also update that in the near future.
N/A
```release-note
```
```docs
```
=> Addon-resizer-release-1.8 branch: Add repo root OWNERS file

cluster-autoscaler/README.md
Add 1.29 to CA version compatibility matrix.
None
NONE
=> CA - Add 1.29 to version compatibility matrix

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6245 into CA 1.28
Part of #6620
```release-note
NONE
```
```docs
```
=> Backport #6245 [CA] AWS: cache instance requirements into CA 1.28

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6245 into CA 1.27
Part of #6620
```release-note
NONE
```
```docs
```
=> Backport #6245 [CA] AWS: cache instance requirements into CA 1.27

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_manager.go, cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
/kind feature
This PR is cherry-picked, which backports #6245 into CA 1.26
Part of #6620
```release-note
NONE
```
```docs
```
=> Backport #6245 [CA] AWS: cache instance requirements into CA 1.26

cluster-autoscaler/cloudprovider/gce/gce_price_info.go, cluster-autoscaler/cloudprovider/gce/gce_price_model_test.go
/kind bug
Fix/Update the default disk type.
Change in k/k: https://github.com/kubernetes/kubernetes/pull/123863
```release-note
Change the default disk type for the legacy GCE storage provider; the default type is now `pd-balanced`.
```
```docs
- [Other doc]: https://cloud.google.com/kubernetes-engine/docs/how-to/custom-boot-disks#specify
```
=> Set "pd-balanced" as DefaultBootDiskType

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/cache_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
It adds listManagedInstancesResults to GceCache. It allows to avoid extra calls to GCE when determining max node group size during scale up.
```release-note
NONE
```
```docs
```
=> Add listManagedInstancesResults to GceCache.

vertical-pod-autoscaler/README.md
Clarifies whether it's possible to use VPA together with HPA on separate resource metrics
Fixes #6247
```release-note
NONE
```
=> Clarify VPA and HPA limitations when scaling on resource metrics

cluster-autoscaler/metrics/metrics.go
/kind feature
It allows us to differentiate between standard and queued-provisioning node groups that are getting auto-provisioned.
```release-note
NONE
```
```docs
```
=> Track auto-provisioned queued provisioning node groups.

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
[GCE CloudProvider](cluster-autoscaler/cloudprovider/gce) is currently using polling as a primary method for awaiting async operations. GCE now provides [method for server side wait](https://cloud.google.com/compute/docs/reference/rest/v1/zoneOperations/wait), which will decrease RPS compared to polling approach. 
1. WaitForOperation method becomes part of public interface to allow further extension of interface without reimplementing await logic once again;
2. In case we are sure that timeouts more than 2 minutes are required we may combine wait method with polling as the last resort.
```release-note
NONE
```
=> Migrate GCE client to server-side wait

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/gce_url.go, cluster-autoscaler/cloudprovider/gce/gce_url_test.go, cluster-autoscaler/cloudprovider/gce/kube_env.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
Need to support Regional Instance Templates. TWithout this change, whenever FetchMIGTemplate gets called, it will fail to find the instance template that is attached to the MIG, as it will call the global GCE API instead of regional one. 
Fixes #
NONE
```release-note
```
```docs
```
=> Regional instance

cluster-autoscaler/cloudprovider/rancher/README.md, cluster-autoscaler/cloudprovider/rancher/rancher_config.go, cluster-autoscaler/cloudprovider/rancher/rancher_config_test.go
/kind feature
Currently it is only possible to set provider settings over yaml file.
This commit introduces env variables to override URL, token and cluster name.
If particular environment variable is set it overrides value supplied in yaml file.
```release-note
Allow to override rancher provider setting via environment variables (`RANCHER_TOKEN`, `RANCHER_URL`, `RANCHER_CLUSTER_NAME`)
```
```docs
```
=> Allow to override rancher provider settings

.github/workflows/ci.yaml, builder/Dockerfile
/kind bug
This PR is cherry-picked, which backports #6522 into CA 1.29
Part of #6521
```release-note
None
```
```docs
```
=> Backport #6522 [CA] Bump go version into CA1.29

cluster-autoscaler/core/static_autoscaler.go
/kind bug
This PR removes shadowed ```err``` variable in ```deleteCreatedNodesWithErrors()``` in ```static_autoscaler.go```. Previously the returned error from ```nodeGroup.DeleteNodes()``` was assigned to a shadowed ```err``` variable. Because of that the original variable remains ```nil``` even when node deletion failed and that original variable is used to determine whether there was a successful node deletion. If there was a successful node deletion the current CA loop will skip. Because of this shadowed variable, CA can get stuck in an infinite loop when there are created nodes with errors and node deletion fails for those nodes.
NONE
=> Remove shadow err variable in deleteCreatedNodesWithErros func

cluster-autoscaler/core/scaledown/deletiontracker/nodedeletiontracker.go
/kind bug
Fix memory leak in `NodeDeleteTracker`.
Fixes  https://github.com/kubernetes/autoscaler/issues/6543
`scaleDownActuator` has a NodeDeleteTracker, it add pods by `RegisterEviction`. But it never clear pods.
```release-note
NONE
```
```docs
```
=> fix memory leak in NodeDeleteTracker

cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/loop/run.go, cluster-autoscaler/loop/trigger.go, cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go
Trigger new autoscaling iterations based on two additional criteria:
1. There are new unschedulable pods - reduces autoscaling latency slightly
2. Last iteration was productive (there was a scale-up or scale-down) - increases autoscaling throughput in cases where there are multiple heterogeneous workloads, each requiring a separate iteration.
This also avoids burning CPU unnecessarily, which would happen if we just reduced scanInterval to some value close to zero.
This functionality is flag-guarded, disabled by default.
```release-note
NONE
```
=> Add an option to trigger iterations more frequently

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind feature
Fixes #
```release-note
Azure: add support for edge zones
```
```docs
```
=> Azure: add support for edge zones

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
Adds support for the Hetzner cloud provider in the cluster-autoscaler Helm chart.
n/a
n/a
NONE
n/a
=> feature: Support Hetzner cloud provider in Helm chart

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/config/const.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch_test.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/observers/nodegroupchange/scale_state_observer.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_delay_processor.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_delay_processor_test.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_processor.go
/kind cherry-pick 
cherry-picks https://github.com/kubernetes/autoscaler/pull/5729 to 1.29
Fixes #
```release-note
Added: `--scale-down-delay-type-local` flag. It specifies if `--scale-down-delay-after-*` flags should be applied locally per nodegroup or globally across all nodegroups)
```
```docs
```
=> chore: cherry-pick scale-down-delay-* per nodegroup to 1.29

cluster-autoscaler/core/podlistprocessor/currently_drained_nodes_test.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/deletiontracker/nodedeletiontracker.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaledown/legacy/wrapper.go, cluster-autoscaler/core/scaledown/scaledown.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
/cleanup
This PR does 2 things:
* Removes responsibility from Actuator.StartDeletion to create full ScaleDownStatus object. It allows us to remove some semantically incorrect usage patterns like [this](https://github.com/kubernetes/autoscaler/compare/master...mtrqq:feat/periodic-scaledown-status-calls?expand=1#diff-a7aace3350322c394f2546d1c4f098372716d343f4883ded0e3aaed75c820cfcL1283) and [this](https://github.com/kubernetes/autoscaler/compare/master...mtrqq:feat/periodic-scaledown-status-calls?expand=1#diff-b1ecfd03ab78ce8627f09152ca317b1feaf5003297f00fbac5ff77710af6be66L99) and instead query for status object explicitly via Actuator.ScaleDownStatus call
* Enforces periodic checks of ScaleDownStatusProcessor, because as of right now - it can be called twice in case of cooldown period due …
=> Refactor StartDeletion usage patterns and enforce periodic scaledown

vertical-pod-autoscaler/pkg/admission-controller/README.md, vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/main.go
/kind feature
This PR allows the VPA admission-controller to have an adjustable minimum TLS version and ciphersuites.  This will help people using VPA to be more secure as you can now set a minimum TLS version of 1.3 or only allow strong ciphers.
Fixes #6624
I don't know the best way to create a mapping of ciphers/tls_versions to convert the string from the flag to the accepted uint16 accepted by the server params.  If there is a better/cleaner solution I would be very much open to changing the code.
```release-note
NONE
```
```docs
```
=> Updated VPA admission-controller to have adjustable minimum TLS version and TLS ciphers

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
/kind bug
Fixes Cluster API Machine name normalization issue that break auto-scaling of Azure VMSS MachinePool resources.
Fixes #6397
```release-note
NONE
```
```docs
```
=> Don't normalize azure vmss

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
/kind feature
Fixes #6549 
```release-note
None
```
=> [clusterapi] Do not skip nodegroups with minSize=maxSize

cluster-autoscaler/cloudprovider/linode/README.md
The Linode provider for CA has been redundant for years now and should be deprecated (and eventually removed).
Fixes #6495
```release-note
The Linode Cluster Autoscaler provider is removed.
```
None
=> Deprecate the Linode Cluster Autoscaler provider

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
This fixed requests for pods with ephemeral storage requests being denied due to insufficient ephemeral storage for the Hetzner provider.
Backport of #6574 to `v1.28` branch.
Fixes #6563
```release-note
Fixed an issue where ephemeral storage was not considered for Hetzner servers.
```
```docs
```
=> [v1.28][Hetzner] Fix missing ephemeral storage definition

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
This fixed requests for pods with ephemeral storage requests being denied due to insufficient ephemeral storage for the Hetzner provider.
Backport of #6574 to `v1.29` branch.
Fixes #6563
```release-note
Fixed an issue where ephemeral storage was not considered for Hetzner servers.
```
```docs
```
=> [v1.29][Hetzner] Fix missing ephemeral storage definition

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
This fixed requests for pods with ephemeral storage requests being denied due to insufficient ephemeral storage for the Hetzner provider.
Backport of #6574 to `v1.27` branch.
Fixes #6563
```release-note
Fixed an issue where ephemeral storage was not considered for Hetzner servers.
```
```docs
```
=> [v1.27][Hetzner] Fix missing ephemeral storage definition

addon-resizer/Makefile, addon-resizer/go.mod, addon-resizer/go.sum, addon-resizer/nanny/kubernetes_client.go
/kind bug
Fixes #6681
1. Go version is bumped since building with `1.20` is failing:
```zsh
➜  addon-resizer git:(addon-resizer-release-1.8) ✗ make all
docker run --rm -it -v `pwd`:/go/src/k8s.io/autoscaler/addon-resizer/:Z \
golang:1.20.10 \
/bin/bash -c "\
cd /go/src/k8s.io/autoscaler/addon-resizer/ && \
go test ./nanny -v"
vendor/github.com/prometheus/common/model/labelset.go:20:2: package slices is not in GOROOT (/usr/local/go/src/slices)
note: imported by a module that requires go 1.21
make: *** [test] Error 1
```
2. There was no need as such to bump `github.com/prometheus/common` but I did along with the fix for `expfmt.FmtText`.
3. The fix for `expfmt.FmtText`:
The `FmtText` constant is not longer exported by `github.com/prometheus/common/expfmt`. Thus, I copied it …
=> fix(build): bump Go version and fix broken deps

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/estimator/binpacking_estimator_test.go, cluster-autoscaler/estimator/decreasing_pod_orderer.go, cluster-autoscaler/estimator/decreasing_pod_orderer_test.go, cluster-autoscaler/estimator/estimator.go, cluster-autoscaler/estimator/threshold_based_limiter.go, cluster-autoscaler/estimator/threshold_based_limiter_test.go, cluster-autoscaler/utils/test/test_utils.go
/kind feature
Introduces optimization to the binpacking estimator, which changes the time complexity from O(pods * nodes) to O(pods) in cases of homogeneous pods.
The PR also introduces a benchmark that shows 5x improvement:
The previous version took ~25s:
```
goos: linux
goarch: amd64
pkg: k8s.io/autoscaler/cluster-autoscaler/estimator
cpu: AMD EPYC 7B12
BenchmarkBinpackingEstimate-48    	       1	25418848308 ns/op	15018690016 B/op	144793817 allocs/op
PASS
ok  	k8s.io/autoscaler/cluster-autoscaler/estimator	25.488s
```
The new version takes less than 5s:
```
goos: linux
goarch: amd64
pkg: k8s.io/autoscaler/cluster-autoscaler/estimator
cpu: AMD EPYC 7B12
BenchmarkBinpackingEstimate-48    	       1	4805105872 ns/op	2023739088 B/op	 3574976 allocs/op
PASS
ok …
```
=> Refactor estimation

cluster-autoscaler/cloudprovider/aws/README.md
On the same page where I made my changes for this PR is the following instruction written:
_"In this example, only the second block of actions should be updated to restrict the resources/add conditionals:"_
If you then add a common condition like its often mentioned here in the issues or also recommended in the [EKS Best Practices Guides](https://aws.github.io/aws-eks-best-practices/cluster-autoscaling/#employ-least-privileged-access-to-the-iam-role) which looks like: 
```json
"Condition": {
"StringEquals": {
"aws:ResourceTag/k8s.io/cluster-autoscaler/enabled": "true",
"aws:ResourceTag/k8s.io/cluster-autoscaler/<my-cluster>": "owned"
}
}
```
It's important to note that applying such conditions togehter with the example IAM policy often lead to an issue where the …
=> docs: precise AWS IAM policy example

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/hack/vpa-process-yaml.sh
Changes in the master branch are in #6655
/kind feature
This is the last part of the 1.1.0 release: https://github.com/kubernetes/autoscaler/issues/6388
=> Bump default VPA version to 1.1.0 in vpa-release-1.1 branch

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/hack/vpa-process-yaml.sh
/kind feature
This is the last part of the 1.1.0 release: #6388
=> Bump default VPA version to 1.1.0

cluster-autoscaler/cloudprovider/gce/templates.go
/kind cleanup
When `kube-env` doesn't have osDistro or arch labels set, the CA spam errors (on every loop).
The system works perfectly fine with defaults, so it's not as critical.
```release-note
NONE
```
=> Lower errors verbosity for kube-env label missing

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go, cluster-autoscaler/cloudprovider/azure/azure_manager.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool_test.go
/kind feature
Use Azure cache to track VMs pools. As of today, CAS can only be used for single type of agentpool - either vmss or standard. We need to support vms pool and mixed agentpool types (vmss + vms). During the cache generation, we will fetch all resources regardless of the vmType, and also track the vms pools using a set (implemented with golang map) so we can distinguish between vmss vm instances and vms instances. 
Fixes #
Right now the file `azure_vms_pool.go` is just a place holder without real implementation.
```release-note
```
```docs
```
=> [Azure VMs Pool] Support mixed agentpool types in Azure Cache

cluster-autoscaler/processors/provreq/provisioning_request_injector.go, cluster-autoscaler/processors/provreq/provisioning_request_injector_test.go, cluster-autoscaler/provisioningrequest/checkcapacity/orchestrator.go, cluster-autoscaler/provisioningrequest/checkcapacity/processor.go, cluster-autoscaler/provisioningrequest/checkcapacity/processor_test.go, cluster-autoscaler/provisioningrequest/conditions/condition_test.go, cluster-autoscaler/provisioningrequest/conditions/conditions.go, cluster-autoscaler/provisioningrequest/pods/pods.go, cluster-autoscaler/provisioningrequest/pods/pods_test.go, cluster-autoscaler/provisioningrequest/provreqclient/client.go, cluster-autoscaler/provisioningrequest/provreqclient/client_test.go, cluster-autoscaler/provisioningrequest/provreqclient/testutils.go, cluster-autoscaler/provisioningrequest/provreqwrapper/testutils.go, cluster-autoscaler/provisioningrequest/provreqwrapper/wrapper.go, cluster-autoscaler/provisioningrequest/provreqwrapper/wrapper_test.go
/kind cleanup
```release-note
NONE
```
=> Cleanup ProvReq wrapper

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache_test.go
/kind bug
Fixes #6716 
This change fixes a bug that arises when the user's cluster includes worker nodes not from Hetzner Cloud, such as a Hetzner Dedicated server or any server resource other than Hetzner. It also corrects the behavior when a server has been physically deleted from Hetzner Cloud.
```release-note
Fixed an issue where the Hetzner provider breaks when nodes from other providers are present
```
=> Fix Autoscaling for worker nodes with invalid ProviderID

vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher_test.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go, vertical-pod-autoscaler/pkg/utils/vpa/api_test.go
/kind bug
The method `ctrlFetcher.FindTopMostWellKnownOrScalable` returns `nil` without an additional `error`, when there is no owner that is either scalable (implementing the `/scale` subresource) or is well-known. In this case, just skip the current Pod, as it cannot be controlled by a VPA.
Fixes #6709 
This PR adds two tests to make sure this cannot regress:
* `vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher_test.go` gets the new testcase `custom resource with no scale subresource` which ensures that for a Pod, which is not under VPA control and has an `ownerRef` to a custom resource that doesn't implement `/scale`, the method `FindTopMostWellKnownOrScalable` returns `nil`, `nil`
* `vertical-pod-autoscaler/pkg/utils/vpa/api_test.go` gets an additional test …
=> Fix NPE in vpa-updater when Pod owner isn't scalable

cluster-autoscaler/cloudprovider/azure/azure_manager.go
added retry for forceRefresh in case of throttled requests
feature
added retry for forceRefresh in case of throttled requests
Fixes #
```release-note
Azure manager will refresh automatically refreshed on failure due to throttled requests.
```
```docs
```
=> Add retry for creatingAzureManager in case of throttled requests

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache_test.go
/kind bug
This change fixes a bug that arises when the user's cluster includes worker nodes not from Hetzner Cloud, such as a Hetzner Dedicated server or any server resource other than Hetzner. It also corrects the behavior when a server has been physically deleted from Hetzner Cloud.
Backport of #6717 to `v1.29` branch.
Fixes #6716
```release-note
Fixed an issue where the Hetzner provider breaks when nodes from other providers are present
```
```docs
```
=> [v1.29][Hetzner] Fix Autoscaling for worker nodes with invalid ProviderID

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache_test.go
/kind bug
This change fixes a bug that arises when the user's cluster includes worker nodes not from Hetzner Cloud, such as a Hetzner Dedicated server or any server resource other than Hetzner. It also corrects the behavior when a server has been physically deleted from Hetzner Cloud.
Backport of #6717 to `v1.27` branch.
Fixes #6716
```release-note
Fixed an issue where the Hetzner provider breaks when nodes from other providers are present
```
```docs
```
=> [v1.27][Hetzner] Fix Autoscaling for worker nodes with invalid ProviderID

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache_test.go
/kind bug
This change fixes a bug that arises when the user's cluster includes worker nodes not from Hetzner Cloud, such as a Hetzner Dedicated server or any server resource other than Hetzner. It also corrects the behavior when a server has been physically deleted from Hetzner Cloud.
Backport of #6717 to `v1.28` branch.
Fixes #6716
```release-note
Fixed an issue where the Hetzner provider breaks when nodes from other providers are present
```
```docs
```
=> [v1.28][Hetzner] Fix Autoscaling for worker nodes with invalid ProviderID

vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher_test.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go, vertical-pod-autoscaler/pkg/utils/vpa/api_test.go
Cherry-pick of #6712 on vpa-release-1.1
```release-note
Fix: NPE in vpa-updater when Pods have an `ownerReference` to a Custom Resource which doesn't implement the `/scale` subresource
```
=> [vpa-release-1.1] Cherry-pick of #6712: Fix NPE in vpa-updater when Pod owner isn't scalable

builder/Dockerfile, cluster-autoscaler/go.mod
Ref: https://github.com/kubernetes/kubernetes/pull/124196
=> Bump Go version used for building to 1.22.2 to match k/k

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
- this is a follow-up to https://github.com/kubernetes/autoscaler/pull/5054
- this might fix CA fails to scale-up or cancel in-progress scale down when there are un-schedulable pods  #4456
- this implements the same functionality, which was implemented it https://github.com/kubernetes/autoscaler/pull/5632 for aws provider
/kind bug
The same as in #5632, but for cluster-api provider
> I think description of https://github.com/kubernetes/autoscaler/pull/5054#issue-1319989728 explains it well:
>  ...original intent of determining the deleted nodes was incorrect, which led to the issues reported by other users. The nodes tainted with ToBeDeleted were misidentified as Deleted instead of Ready/Unready, which caused a miscalculation of the node being included as Upcoming. This caused problems …
=> fix: implement function to identify if node is present in cluster-api

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
```release-note
```
```docs
```
=> fix(hetzner): hostname label is not considered

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
Backport of https://github.com/kubernetes/autoscaler/pull/6740 to v1.30 branch.
```release-note
```
```docs
```
=> [v1.30] fix(hetzner): hostname label is not considered

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
Backport of https://github.com/kubernetes/autoscaler/pull/6740 to v1.29 branch.
```release-note
```
```docs
```
=> [v1.29] fix(hetzner): hostname label is not considered

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
Backport of https://github.com/kubernetes/autoscaler/pull/6740 to v1.27 branch.
```release-note
```
```docs
```
=> [v1.27] fix(hetzner): hostname label is not considered

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
Backport of https://github.com/kubernetes/autoscaler/pull/6740 to v1.28 branch.
```release-note
```
```docs
```
=> [v1.28] fix(hetzner): hostname label is not considered

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/static_autoscaler.go
/kind bug
Properly handle calls to `NodeGroup.GetOptions()` that return `cloudprovider.ErrNotImplemented` in the scale up path.
Fixes #6676
All call sites check for `options != nil` right after the error check.
```release-note
Fixed scaling up node groups for Hetzner Provider
```
I have only confirmed that this was actually affecting the Hetzner Provider, there are other providers that also return `ErrNotImplemented`, but I did not verify if there was user visible breakage for them.
```docs
```
=> fix: scale up broken for providers not implementing NodeGroup.GetOptions()

cluster-autoscaler/core/static_autoscaler.go
Cherry-pick of #6596 to Cluster Autoscaler 1.28 branch
=> [CA 1.28 #6596 cherry-pick] Remove shadow err variable in deleteCreatedNodesWithErros func

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/static_autoscaler.go
Properly handle calls to `NodeGroup.GetOptions()` that return `cloudprovider.ErrNotImplemented` in the scale up path.
Cherry-pick of #6677 to Cluster Autoscaler 1.30 branch
=> [CA 1.30 #6677 cherry-pick] fix: scale up broken for providers not implementing NodeGroup.GetOptions()

cluster-autoscaler/core/static_autoscaler.go
Cherry-pick of #6596 to Cluster Autoscaler 1.29 branch
=> [CA 1.29 #6596 cherry-pick] Remove shadow err variable in deleteCreatedNodesWithErros func

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/static_autoscaler.go
Properly handle calls to `NodeGroup.GetOptions()` that return `cloudprovider.ErrNotImplemented` in the scale up path.
Cherry-pick of #6677 to Cluster Autoscaler 1.28 branch
=> [CA 1.28 #6677 cherry-pick] fix: scale up broken for providers not implementing NodeGroup.GetOptions()

cluster-autoscaler/cloudprovider/cloud_provider.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/static_autoscaler.go
Properly handle calls to `NodeGroup.GetOptions()` that return `cloudprovider.ErrNotImplemented` in the scale up path.
Cherry-pick of #6677 to Cluster Autoscaler 1.29 branch
=> [CA 1.29 #6677 cherry-pick] fix: scale up broken for providers not implementing NodeGroup.GetOptions()

vertical-pod-autoscaler/common/version.go
Bump version for 1.1.1 release
Part of https://github.com/kubernetes/autoscaler/issues/6765
=> Bump VPA version to 1.1.1

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/hack/vpa-process-yaml.sh
/kind cleanup
Update VPA default version to 1.1.1 such that people don't install the broken 1.1.0 version.
```release-note
NONE
```
=> Update VPA default version to 1.1.1

cluster-autoscaler/core/podlistprocessor/currently_drained_nodes.go, cluster-autoscaler/core/podlistprocessor/currently_drained_nodes_test.go, cluster-autoscaler/utils/test/test_utils.go
/kind bug
Shouldn't put pods that have deletionTimestamp set on the draining node to the unshedulable pods list.
The issue has more detailed analysis. Thanks!!!
Fixes #6718
=> filter out pods that have deletion timestamp set in currentlyDrainedPods

cluster-autoscaler/FAQ.md, cluster-autoscaler/expander/expander.go, cluster-autoscaler/expander/factory/expander_factory.go, cluster-autoscaler/expander/leastnodes/leastnodes.go, cluster-autoscaler/expander/leastnodes/leastnodes_test.go
Adds a new `least-nodes` expander 🎉 
No related issues
```release-note
Added a new `least-nodes` expander
```
```docs
```
=> add least-nodes expander to cluster-autoscaler

cluster-autoscaler/utils/drain/drain.go, cluster-autoscaler/utils/drain/drain_test.go
Without this the enum is output as its int value, which is not readable
/kind cleanup
=> Format BlockingPodReason in human readbale way with %v

cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go, cluster-autoscaler/provisioningrequest/provreqwrapper/testutils.go
Cleanup unit tests a bit before implementing atomic scale-up support for Provisioning Requests: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md
/kind cleanup
```release-note
NONE
```
=> Refactor Provisioning Request orchestrator unit tests

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml, cluster-autoscaler/README.md
/kind feature
Bump the Chart version to 9.37.0 and the CA image to 1.30.0
Fixes #
```release-note
Bump the Chart version to 9.37.0 and the CA image to 1.30.0
```
```docs
```
=> Bump CA Chart image to v1.30

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider_test.go
/kind bug
/kind cleanup
Autoscaler only chooses and scales up a nodegroup each run. Meaning that if you have multiple unschedulable pods targeting different groups each of them (e.g. via nodeSelector), autoscaler would only be able to find a place for them sequentially, therefore having a penalty time (that keeps degrading as the number of pods/nodegroups increases) for the latest pods in "the queue". When having ~90 scalable resources with capi provider this results in long times to provision nodes for latests pods in the "queue" (>40min).
The `func (p *provider) NodeGroups() []cloudprovider.NodeGroup {` is called around 16 times every runOnce loop. Currently it takes ~20 seconds with ~90 MachineSets. This avoids expensive loop and copy pointers resulting in ~5 seconds each NodeGroups …
=> Avoid expesive pointer copy in capi nodegroup

cluster-autoscaler/FAQ.md
This PR fixed the hyperlink of the "TLS bootstrapping process" in cluster-autoscaler's FAQ.md.
Fixes #
#6805 
```release-note
NONE
```
```docs
```
=> docs:fix broken hyperlink in cluster-autoscaler FAQ.md

.github/dependabot.yml
/kind cleanup
Some time back we changed the labels to be correctly prefixed with `area/`. Dependabot still had the old labels configured, which resulted in errors like this: https://github.com/kubernetes/autoscaler/pull/6799#issuecomment-2099022655
```release-note
NONE
```
=> Update VPA dependabot labels

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/test/common.go
Small refactor prior to the implementation of atomic scale-up support for Provisioning Requests: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md 
Apply resource limits to scale-up plan before creating a new node group. Note that this is independent of the steps that happen immediately before and after - `newNodes` aren't used until we balance similar node groups, and non-existent node groups already have to expose node resources (otherwise scale-up simulations wouldn't be possible). 
There's already a check in place for skipping a node group if adding even one node would exceed resource limits, so it's not technically a bug right now, and so this PR doesn't change current behavior. However, for the atomic scale up support for …
=> Refactor scale-up to apply resource limits before creating a node group

cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/provisioning_request_injector.go, cluster-autoscaler/processors/provreq/provisioning_request_processor.go, cluster-autoscaler/provisioningrequest/checkcapacity/processor.go, cluster-autoscaler/provisioningrequest/checkcapacity/processor_test.go, cluster-autoscaler/provisioningrequest/checkcapacity/provisioningclass.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator.go, cluster-autoscaler/provisioningrequest/provreqclient/client.go
/kind bug
Implementation of ProvisioningRequest missed the real update of the object.
=> Fix ProvisioningRequest update

vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
/kind cleanup
Clearer Readability by removing unused build-args
=> Remove unnecessary build-args

vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission.go, vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission_test.go
/kind bug
See https://github.com/kubernetes/autoscaler/issues/6808
Fixes #
6808
```release-note
```
```docs
```
=> Fix nil pointer panic in eviction admission

cluster-autoscaler/cloudprovider/azure/README.md
escape \~ md characters that are used literally, otherwise readable text is rendered ~strikethrough~
Improves readability
Fixes #
NONE
=> Update README.md, escape md characters

cluster-autoscaler/main.go
/kind feature
Fixes #6814
Check-capacity was tested manually. The following scenarious were tested: 
- 1 ProvReq, cluster doesn’t have capacity, verify Provisioned=False
- 1 ProvReq, cluster has capacity which is used by real pods, verify Provisioned=False
- 1 ProvReq, cluster has capacity, verify Provisioned=True
- 1 ProvReq, multiple pod templates, only 1 pod template could fit, verify Provisioned=False
- 2 ProvReqs, each ProvReq could fit, but not both of them. Verify only 1 ProvReq has Provisioned=True, when BookingExpired=True, second ProvReq has Provisioned=True.
=> Add --enable-provisioning-requests flag

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
Add `FetchAvailableDiskTypes` method to GCE client.
```release-note
NONE
```
=> Add FetchAvailableDiskTypes to GCE Client

cluster-autoscaler/cloudprovider/gce/machine_types.go, cluster-autoscaler/cloudprovider/gce/machine_types_test.go
/kind feature
Add MaximumPersistentDisksSizeGb info from GCE API into MachineType and gce cache.
This value is machie-type specific, e.g. "Shared-core machine types are limited to 16 Persistent Disk volumes and 3 TiB of total Persistent Disk space."
ref: https://cloud.google.com/compute/docs/disks#pdnumberlimits
```release-note
NONE
```
=> Extend gce MachineType with MaxDiskSizeGb

cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1beta1/types.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go
/kind bug
Changes the name of provisioning class from `atomic-scale-up.kubernetes.io` to `best-effort-atomic-scale-up.kubernetes.io` as agreed in #6849
Fixes #6849
```release-note
Changed the name of provisioning class from `atomic-scale-up.kubernetes.io` to `best-effort-atomic-scale-up.kubernetes.io` in v1beta1. Note that this API is in draft stage and not yet supported in any release.
```
```docs
- [KEP] https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md
```
/cc @yaroslava @kisieland
=> Update ProvisioningRequest API with the new name of scale-up provisioning class

cluster-autoscaler/cloudprovider/hetzner/README.md, cluster-autoscaler/cloudprovider/hetzner/hetzner_debug_writer.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
/kind feature
It shows api calls toward Hetzner from log level 5 onward. 
Fixes #6860
```release-note
NONE
```
```
=> Show requests/responses made towards Hetzner cloud for high log levels

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/provisioningrequest/besteffortatomic/provisioning_class.go, cluster-autoscaler/provisioningrequest/conditions/conditions.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go
/kind feature
Implements provisioning class for  `best-effort-atomic-scale-up..x-k8s.io` ProvisioningRequests: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md
Issue #6815
```release-note
Added support for `best-effort-atomic-scale-up..x-k8s.io` ProvisioningRequests
```
```docs
- [KEP]: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md
```
/cc @yaroslava-serdiuk @kisieland @towca
=> Implement ProvisioningClass for best-effort-atomic-scale-up.kubernetes.io ProvisioningRequests

.github/workflows/ci.yaml
/kind cleanup
Bump the go version under GitHub workflow to 1.22.2, as [Dockerfile](https://github.com/kubernetes/autoscaler/blob/master/builder/Dockerfile) and [go.mod](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/go.mod) uses go version 1.22.2
Fixes #
```release-note
NONE
```
```docs
```
=> Bump the go version for the GitHub workflows.

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go
This PR adds more precise logging for VPA recommendations.
* Logs the exact `processedRecommendation` from the VPA Updater, specifically, the capped and uncapped target resources (CPU/mem).
Helps to debug #6705
```release-note
The VPA Updater logs the processed recommendations, specifically, the target and uncapped target CPU/memory.
```
```docs
```
=> Add more precise logging for VPA resource recommendations

cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment-control-plane.yaml, cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment.yaml, cluster-autoscaler/cloudprovider/magnum/examples/values-autodiscovery.yaml, cluster-autoscaler/cloudprovider/magnum/examples/values-example.yaml
/kind bug
This PR upgraded `openstackmagnum/cluster-autoscaler` image version to v1.28.0.
Fixes #6878
```release-note
NONE
```
```docs
```
=> Bump openstackmagnum/cluster-autoscaler image version.

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go
/kind bug
At the moment GCE manager is using 30 seconds timeouts for all http calls which breaks logic of long polling [WAIT calls for GCE API](https://cloud.google.com/compute/docs/reference/rest/v1/zoneOperations/wait) as in the worst case scenario they require 2 minutes. 
This PR increases http timeout to be 3 minutes (2 minutes + buffer time) and adds timeouts control over some operations in order to avoid performance degradation in the case of not responding API. Not all the methods can be patched, as with pagination we are not sure what would be the exact number of calls and current GCE API doesn't provide a way to control per call timeouts.
* This PR also changes deprecated method `gce.New` to use `gce.NewService` 
* Wait operation doesn't have an extra handling …
=> Fix GCE client long polling timeouts.

cluster-autoscaler/go.mod
The current CA master depends on the newest version of the APIs module, but it's not expressed in its go.mod.
=> Bump the cluster-autoscaler/apis dependency in CA go.mod after recent changes

cluster-autoscaler/clusterstate/clusterstate.go
/kind bug
This PR is cherry-picked, which backports #6528 into CA 1.28
Fixes #
```release-note
None
```
```docs
```
=> Backport #6528 [CA] Fix expectedToRegister to respect instances with nil status into CA1.29

cluster-autoscaler/processors/nodegroupset/azure_nodegroups.go, cluster-autoscaler/processors/nodegroupset/azure_nodegroups_test.go
feature - skip a few azure specific labels in nodegroupset
This PR add a few azure specific labels that needs to be skipped when checking for nodegroup similarity.
This change doesn't include moving azure specific lables under /azure directory - that chore will be covered in another change
Fixes #
```release-note
Skips Azure-specific node labels that might mistakenly categorize nodegroups as different when, in reality, they are similar.
```
```docs
```
=> azure labels to skip in nodegroupset

cluster-autoscaler/cloudprovider/aws/aws_wrapper.go, cluster-autoscaler/cloudprovider/aws/aws_wrapper_test.go, cluster-autoscaler/cloudprovider/aws/managed_nodegroup_cache_test.go
/kind bug
This PR fixes a bug between AWS EKS API understanding of Kubernetes taints and normal Kubernetes understanding of taints by introducing a translation method. Since the AWS API response when calling DescribeNodegroup have taints in the format of NO_SCHEDULE instead of NoSchedule as an example.
Fixes #6481
```release-note
```
```docs
```
=> Fixed bug with missing taint translation layer between AWS EKS format and Kubernetes format

cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/update_latency_tracker.go
Update dynamic-node-delete-delay-after-taint to use max latency observed during the last hour
/kind bug
The current implementation was too aggressive for some users and the delay was alternating between two latency levels enabling an opportunity for a race condition between CA and scheduler.
This PR updates the logic that dynamically adjusting the ```nodeDeleteDelayAfterTaint```. Instead of setting the ```nodeDeleteDelayAfterTaint``` based on the recent latency observation, now ```nodeDeleteDelayAfterTaint``` is set using the maximum latency observed during the last hour.
Fixes #
NONE
```docs
```
=> Update dynamic-node-delete-delay-after-taint to use max latency observed during the last hour

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/binpacking/binpacking_limiter.go, cluster-autoscaler/processors/binpacking/combined_limiter.go, cluster-autoscaler/processors/binpacking/time_limiter.go, cluster-autoscaler/processors/processors.go
/kind feature
This PR implements two new ```BinpackingLimiter``` 
```TimeLimitter``` will limit total time spent on bin packing.
With this new limiter bin packing will cut short after exceeding the ```maxBinpackingDuration```.
The ```maxBinpackingDuration``` is set using ```--max-binpacking-time```.
```CombinedLimiter``` which is the other limiter combines multiple limiters and limit bin packing when at least one limiter meets a stop condition.
```release-note
Bin packing will be cut short after exceeding "maxBinpackingDuration".
The "maxBinpackingDuration" is set using an new flag "--max-binpacking-time".
```
=> implement time limiter for binpacking

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go, cluster-autoscaler/cloudprovider/gce/gce_url.go, cluster-autoscaler/cloudprovider/gce/gce_url_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind feature
This PR extends ```AutoscalingGceClient interface``` to add a method for listing Instances in a project in a particular zone.
NONE
=> Add Instances.List method to AutoscalingGceClient

addon-resizer/README.md
Explains how to activate the new Prometheus endpoint added in https://github.com/kubernetes/autoscaler/pull/6916.
NONE
=> Update README.md with details about Prometheus endpoint

vertical-pod-autoscaler/README.md
/kind bug
/kind cleanup
Update the VPA default version to v1.1.2 under the [README.md docs](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md).
Fixes #
```release-note
None
```
```docs
```
=> Update the VPA Version to v1.1.2

vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/config_test.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
/kind bug
I'm working on another PR
(https://github.com/kubernetes/autoscaler/pull/6788) and realised that those changes will be touching code that is untested.
I decided to go back and add some tests before continuing work in that PR.
N/A
I'm unsure if these tests match the current style of tests in the VPA. I'm happy to change if needed.
```release-note
NONE
```
```docs
```
=> VPA: Add tests for selfRegistration() and filterVPAs()

cluster-autoscaler/FAQ.md
=> Add documentation for check-capacity Provisioning class

vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
/kind bug
Currently vpa logs for eviction look like:
```
I0607 09:56:37.171710       1 updater.go:220] evicting pod etcd-main-2
I0607 09:57:37.177733       1 updater.go:220] evicting pod etcd-main-0
I0607 09:58:37.059142       1 updater.go:220] evicting pod etcd-main-1
I0607 09:59:37.225718       1 updater.go:220] evicting pod etcd-events-2
I0607 10:00:37.083830       1 updater.go:220] evicting pod etcd-events-1
```
It is not possible to deduce which is the namespace of these Pods because it is simply not logged. We have hundreds of namespaces deploying StatefulSet Pods which at the end have the same name.
This PR logs the namespace as well so that log readers can locate the affected Pods unambiguously.
N/A
N/A
```release-note
vpa-updater logging is now improved. In many cases it now logs …
```
=> vpa-updater: Log the Pod namespace when evicting a Pod

cluster-autoscaler/cloudprovider/oci/instancepools/oci_cloud_provider.go
/kind bug
In OKE,  nodepools being created in a dev environment (integ) have the term nodepoolinteg instead of just nodepool . This is causing issues with CA. Our current logic in CA is to split the nodepool ocid by .  as the separator and move the control to OKE's implementation if the string in the 1st index of the array is nodepool , else we move the control to Instance Pool's implementation. Since it is now nodepoolinteg , it is moving to Instance Pool's implementation. This PRs fixes the logic.
No
=> Modify logic to look for ocid type prefix in OCI cloud provider builder

cluster-autoscaler/cloudprovider/azure/test/Makefile, cluster-autoscaler/cloudprovider/azure/test/templates/cluster-template-prow-aks-aso-cluster-autoscaler.yaml
/kind feature
This PR adds some initial prereqs to enable running some yet-to-be-added Azure e2e tests for cluster-autoscaler.
Fixes #
```release-note
NONE
```
```docs
```
=> Add initial setup for cluster-autoscaler Azure e2e tests

cluster-autoscaler/OWNERS
OWNERS file update.
Adds back @aleksandra-malinowska to approvers for Cluster Autoscaler (see [emeritus approver policy](https://github.com/kubernetes/community/blob/1acc36024cb1423f1ebbcd6901830a437c32ce7b/contributors/guide/owners.md#emeritus)).
N/A
```release-note
NONE
```
```docs
```
=> CA - Restore aleksandra-malinowska as approver

cluster-autoscaler/cloudprovider/clusterapi/README.md, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
/kind feature
Implements overrding of autoscaling options per NodeGroup (MachineDeployment/Set/Pool). This allows us to improve scale up/down behavior depending on the node groups configuration.
Fixes #6742
The annotation prefix is intentionally does not contain `cluster-api-autoscaler-node-group-` after the slash because the annotation key must be less than 63 chars long.
```release-note
Added configurable autoscaling options to clusterapi provider allowing users to configure e.g. `--scale-down-unneeded-time` on a per node group level.
```
=> feat(clusterapi): per nodeGroup autoscaling options

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go
/kind bug
Similar to https://github.com/kubernetes/autoscaler/pull/6903 but for the vpa-admission-controller. The Pod/VPA resources are namespaced and logging only the name does not allow these objections to be unambiguously identified in the cluster.
N/A
N/A
```release-note
vpa-admission-controller logging is now improved. In many cases it now logs the objects' namespaces as well.
```
```docs
```
=> vpa-admission-controller: Log object's namespace

vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
/area vertical-pod-autoscaler
/kind bug
Cherry pick of #6903 on vpa-release-1.1.
#6903: vpa-updater: Log the Pod namespace when evicting a Pod
**Release Notes:**
```release-note
vpa-updater logging is now improved. In many cases it now logs the objects' namespaces as well.
```
=> [vpa-release-1.1] Automated cherry pick of #6903: vpa-updater: Log the Pod namespace when evicting a Pod

cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1beta1/types.go, cluster-autoscaler/go.mod, cluster-autoscaler/processors/provreq/pods_filter.go, cluster-autoscaler/processors/provreq/pods_filter_test.go, cluster-autoscaler/proposals/provisioning-request.md, cluster-autoscaler/provisioningrequest/orchestrator/wrapper_orchestrator.go, cluster-autoscaler/provisioningrequest/orchestrator/wrapper_orchestrator_test.go, cluster-autoscaler/provisioningrequest/pods/pods.go, cluster-autoscaler/provisioningrequest/pods/pods_test.go
Use autoscaling.x-k8s.io rather than cluster-autoscaler.kubernetes.io
/kind cleanup
As part of https://github.com/kubernetes/autoscaler/pull/6759 new annotation scheme was suggested
=> Update ProvReq annotations to new prefix

cluster-autoscaler/cloudprovider/azure/test/templates/cluster-template-prow-aks-aso-cluster-autoscaler.yaml
/kind bug
This change adds a Secret stub to the CAPZ cluster template for cluster-autoscaler e2e tests on Azure to play nice with the changes made in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4946
Fixes #
```release-note
NONE
```
```docs
```
=> Update Azure cluster-autoscaler e2e cluster template

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_source.go, vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/routines/capping_post_processor.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
/kind bug
Similar to https://github.com/kubernetes/autoscaler/pull/6903 but for the vpa-recommender. The Pod/VPA resources are namespaced and logging only the name does not allow these objections to be unambiguously identified in the cluster.
N/A
N/A
```release-note
vpa-recommender logging is now improved. In many cases it now logs the objects' namespaces as well.
```
```docs
```
=> vpa-recommender: Log object's namespace

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
/kind bug
Remove `--reload-cert` from the admission-controller deployment, as this references image version 1.1.2, which doesn't support this parameter yet. It will be available from version 1.2.0 onwards.
Fixes #6977
=> Remove not yet supported parameter from admission-controller deployment

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go, cluster-autoscaler/cloudprovider/gce/fixtures/diskTypes_aggregatedList.json
/kind bug
The `FetchAvailableDiskTypes` method has wrong assumptions about `gce.DiskTypeAggregatedList` response format.
1. The `resp.Items[].Zone` field is a URL, not a zone name.
2. It would include regional (aggregated) data into output, whereas only zone level is needed
There were no issues, as this method was recently added and was not used, yet.
```release-note
NONE
```
=> Fix: GCE FetchAvailableDiskTypes zones parsing

cluster-autoscaler/cloudprovider/azure/test/.gitignore, cluster-autoscaler/cloudprovider/azure/test/Makefile, cluster-autoscaler/cloudprovider/azure/test/e2e/azure_test.go, cluster-autoscaler/cloudprovider/azure/test/e2e/e2e_suite_test.go
/kind bug
This PR makes some changes to spruce up the output of the cluster-autoscaler Azure test.
- Generate junit report
- Remove debug log statement
- Wait for NotReady Nodes not to exist at the end of the test
Fixes #
```release-note
NONE
```
```docs
```
=> Update Azure cluster-autoscaler e2e test

cluster-autoscaler/processors/nodeinfosprovider/annotation_node_info_provider.go
/kind feature
GCE AnnotationNodeInfoProvider used concrete `MixedTemplateNodeInfoProvider` type instead of generic `TemplateNodeInfoProvider` interface.
```release-note
NONE
```
=> Change GCE AnnotationNodeInfoProvider nested provider to interface instead of concrete type

cluster-autoscaler/provisioningrequest/besteffortatomic/provisioning_class.go, cluster-autoscaler/provisioningrequest/checkcapacity/provisioningclass.go, cluster-autoscaler/provisioningrequest/provreqclient/client.go, cluster-autoscaler/provisioningrequest/provreqclient/client_test.go
=> Do not fail if multiple ProvReqs are injected

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
There is no Node Group/Autoscaling Group in Hetzner Cloud API, so the Hetzner provider implemented this by manually creating as many servers as needed.
The current code did not return any of the errors that could have happened. Without any returned errors, cluster-autoscaler assumed that everything was fine with the Node Group.
In cases where there is a temporary issue with one of the node groups (ie. Location is unavailable, no leftover capacity for the requested server type), cluster-autoscaler should consider this and try to scale up a different Node Group. This will automatically happen once we return an error, as cluster-autoscaler backs off from scaling Node Groups that have recently returned errors.
Fixes #6240
```release-note
Fixed exhausted node groups not backing off …
```
=> fix(hetzner): missing error return in scale up/down

cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go
refactor gce.RegenerateMigInstancesCache() to use Instance.List API
/kind feature
This PR refactor the RegenerateMigInstancesCache() to use Instance.List API when fetching MIG instances.
Fixes #
```release-note
With this change GCE cloud provider will use Instance.List api to list mig instances.
IGM.ListManagedInstances api will be used as a fall back mechanism and for listing instances for migs that have instances in creating or deleting states.
```
```docs
```
=> refactor gce.RegenerateMigInstancesCache() to use Instance.List 

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
/kind bug
This PR updates project field of ```GceRef``` returned by ```createIgmRef()``` in ```autoscaling_gce_client.go``` to use project name instead of project number. ```created-by``` field in instances returned by ```Instances.List()``` have project id but CA use project names in MIG refs.
Fixes #
NONE
```release-note
```
```docs
```
=> Use project name instead of project number in createIgmRef()

cluster-autoscaler/hack/list-owners.py
Simplify finding people to notify about project wide announcements.
Fixes #
```release-note
NONE
```
```docs
```
=> Script for finding Cluster Autoscaler OWNERS

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
PR#6911 Backport for 1.28: Fix/aws asg unsafe decommission #5829
This merge resolves an issue in the Kubernetes Cluster Autoscaler where actual instances within AWS Auto Scaling Groups (ASGs) were incorrectly decommissioned instead of placeholders. The updates ensure that placeholders are exclusively targeted for scaling down under conditions where recent scaling activities have failed. This prevents the accidental termination of active nodes and enhances the reliability of the autoscaler in AWS environments.
/kind bug
This PR prevents the Kubernetes Cluster Autoscaler from erroneously decommissioning actual nodes during scale-down operations in AWS environments, which could lead to unintended service disruptions.
Which issue(s) …
=> PR#6911 Backport for 1.28: Fix/aws asg unsafe decommission #5829

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
This PR is cherry-picked, which backports #6750 into CA 1.28
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #6750 [CA] fix(hetzner): missing error return in scale up/down into CA 1.28

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
This PR is cherry-picked, which backports #6750 into CA 1.29
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #6750 [CA] fix(hetzner): missing error return in scale up/down into CA 1.29

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
This PR is cherry-picked, which backports #6750 into CA 1.30
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #6750 [CA] fix(hetzner): missing error return in scale up/down into CA 1.30

cluster-autoscaler/cloudprovider/oci/common/oci_shape.go, cluster-autoscaler/cloudprovider/oci/common/oci_shape_test.go
/kind bug
Currently if workload contains a `nodeSelector` such as 
```
"nodeSelector": {
"node.kubernetes.io/instance-type": "VM.Standard.E4.Flex"
},
```
then scale from zero does not work as `shape.Name` is not initialized during the templateNode creation.
This should be backported / cherry picked for all supported OKE versions such as 1.30 (upcoming), 1.29, 1.28
```release-note
NONE
```
```docs
NONE
```
=> OCI: Fixing scale from zero if the nodeSelector of workload contains 'node.kubernetes.io/instance-type'

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
PR#6911 Backport for 1.29: Fix/aws asg unsafe decommission https://github.com/kubernetes/autoscaler/issues/5829
This merge resolves an issue in the Kubernetes Cluster Autoscaler where actual instances within AWS Auto Scaling Groups (ASGs) were incorrectly decommissioned instead of placeholders. The updates ensure that placeholders are exclusively targeted for scaling down under conditions where recent scaling activities have failed. This prevents the accidental termination of active nodes and enhances the reliability of the autoscaler in AWS environments.
/kind bug
This PR prevents the Kubernetes Cluster Autoscaler from erroneously decommissioning actual nodes during scale-down operations in AWS environments, which could lead to …
=> PR#6911 Backport for 1.29: Fix/aws asg unsafe decommission #5829

cluster-autoscaler/provisioningrequest/pods/pods.go, cluster-autoscaler/provisioningrequest/pods/pods_test.go
In case PodTemplate has not specified requests, Kubernetes will apply defaulting and set requests=limits, however CA doesn't apply defaulting and will result in wrong scale up.
/kind bug
/hold
=> Add defaulting for provreq pods

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
PR#6911 Backport for 1.30: Fix/aws asg unsafe decommission https://github.com/kubernetes/autoscaler/issues/5829
This merge resolves an issue in the Kubernetes Cluster Autoscaler where actual instances within AWS Auto Scaling Groups (ASGs) were incorrectly decommissioned instead of placeholders. The updates ensure that placeholders are exclusively targeted for scaling down under conditions where recent scaling activities have failed. This prevents the accidental termination of active nodes and enhances the reliability of the autoscaler in AWS environments.
/kind bug
This PR prevents the Kubernetes Cluster Autoscaler from erroneously decommissioning actual nodes during scale-down operations in AWS environments, which could lead to …
=> PR#6911 Backport for 1.30: Fix/aws asg unsafe decommission #5829

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_manager_test.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/cloudprovider/gce/mig_info_provider_test.go
/kind cleanup
This PR renames ```migInstancesState``` to ```migInstancesStateCount``` in gce cache
Fixes #
NONE
```release-note
```
```docs
```
=> Rename migInstancesState to migInstancesStateCount in gce cache

cluster-autoscaler/cloudprovider/gce/mig_info_provider.go, cluster-autoscaler/metrics/metrics.go
/kind feature
This PR emits function duration metrics for listing all mig instances and listing instances using ```igm.ListManagedInstances()```, when bulk listing gce instances is enabled.
And also emits inconsistent mig count for the number of migs which have a difference in instance count based on actionsSummary and result from bulk listing instances.
Fixes #
NONE
```release-note
```
```docs
```
=> add metrics for function duration for listing gce instances and metrics for inconsistent mig count when gce bulk instance listing is enabled

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
/kind cleanup
This change simplifies scale-up logic in ScaleUpOrchestrator by exracting two steps from main logi to dedicated functions.
```release-note
NONE
```
/assign @x13n
=> Extract few steps from ScaleUpOrchestrator main logic

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
/kind bug
fixes lookup of Machines in MachineInformer store for the `HasInstance` case
Fixes #6774
It would be good to verify this with other kind of clusters and/or flags (I'm testing on a CAPZ cluster) to make sure the lookup works in all cases.
```release-note
NONE
```
=> fix(clusterapi): HasInstance with namespace prefix

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/processor.go, cluster-autoscaler/processors/provreq/processor_test.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go
/kind feature
This is needed to prevent ScaleDown for ProvisioningRequest during booking time.
Fixes #6517
Complete implementation for #6815
=> BookCapacity for ProvisioningRequest pods

cluster-autoscaler/cloudprovider/azure/azure_util.go
/kind feature
This PR allows for customizing the HTTP user agent header for cluster-autoscaler's Azure provider using an environment variable. 
Installing the Helm chart with this:
```
--set extraEnv.AZURE_CLUSTER_AUTOSCALER_USER_AGENT_SUFFIX=-my-user-agent
```
Results in a user agent like this:
```
Go/go1.22.5 (amd64-linux) go-autorest/v14.2.1 cluster-autoscaler-my-user-agent/v1.31.0-alpha.2
```
Fixes #
```release-note
The `AZURE_CLUSTER_AUTOSCALER_USER_AGENT_SUFFIX` variable can be used to customize the user agent for the Azure provider of cluster-autoscaler. Setting this to `-my-user-agent` results in a user agent like `Go/go1.22.5 (amd64-linux) go-autorest/v14.2.1 cluster-autoscaler-my-user-agent/v1.31.0-alpha.2`.
```
```docs
```
=> allow customizing user agent for Azure cluster-autoscaler provider

cluster-autoscaler/cloudprovider/azure/test/Makefile, cluster-autoscaler/cloudprovider/azure/test/templates/cluster-template-prow-aks-aso-cluster-autoscaler.yaml
/kind bug
Adds `metadata.namespace` to a couple of lingering resources in the CAPZ template used for cluster-autoscaler e2e tests where it wasn't already defined.
Fixes #
```release-note
NONE
```
```docs
```
=> CAS azure e2e: add namespace to all resources in CAPZ template

cluster-autoscaler/core/podlistprocessor/filter_out_schedulable.go, cluster-autoscaler/core/podlistprocessor/filter_out_schedulable_test.go, cluster-autoscaler/core/podlistprocessor/pod_list_processor.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go
This will allow users to filter-out some of the nodes when filtering out pods potentially schedulable.
/kind feature
Allows users to pass custom node filtering function to processor filtering out schedulable pods.
No
=> Add option to pass custom filter funtion for nodes

cluster-autoscaler/cloudprovider/gce/mig_info_provider.go
/kind cleanup
This PR removes unnecessary warning when ```inconsistentInstancesMigsCount``` is 0
Fixes #
NONE
```release-note
```
```docs
```
=> Log number of inconsistent instances mig count only when it is positive

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
/kind cleanup
In order to simplify the deleteNodesWithErrors code, return nodeGroupID as well as nodes with create errors. That way we avoid the additional node group matching code.
```release-note
NONE
```
```docs
```
=> Return nodes with create errors mapped to node group id

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/hack/vpa-up.sh
This PR decouples the way that we provide for installing VPA directly from this repository (via `./hack/vpa-up.sh`) from the e2e tests. Currently, both take their payload directly from `master`: this makes sense for e2e tests, as they should continuously make sure that the master is still nice and green, but leads to problems, when we introduce change like new parameters for the components (e.g. #6665) or modify the CRD (e.g. #5911).
In those cases, `./hack/vpa-up.sh` _also_ gets the new CRDs or Deployment yaml files, which don't work well with the last released versions – because they don't contain the necessary code changes. This leads to problems like #6977 and https://github.com/kubernetes/autoscaler/issues/5982#issuecomment-1651663433 
With this PR, we switch to the latest release …
=> Decouple test and install script

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go
/kind bug
After deleting some instances from a mig, invalidate the mig instances cache so that the deleted instances are refreshed accordingly.
```release-note
NONE
```
```docs
```
=> [GCE cloudprovider] Invalidate mig instances cache after node deletion

vertical-pod-autoscaler/common/version.go
Version bump for VPA 1.2.0 release
#7098
=> Update version.go for VPA 1.2.0 release

cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager_test.go
/kind bug
What this PR does :
Cluster Autoscaler only handles deleting of cloud-provider instances that do not join the cluster within the max-node-provision-time only if the state of the cloud-provider instance is set to InstanceCreating. [[Code Link](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/clusterstate/clusterstate.go#L1180)]
This PR is set to the state of cloud-provider instance which have failed to InstanceCreating.
=> Set State to InstanceCreating for nodes that failed to join cluster

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
Extract logic for overriding nodes to delete when deleting nodes from a ZeroOrMaxNodeScaling node group.
Simplifies the code and removes code duplication.
/kind cleanup
-->
Extract logic for overriding nodes to delete when deleting nodes from a ZeroOrMaxNodeScaling node group.
Simplifies the code and removes code duplication.
```release-note
NONE
```
```docs
```
=> Extract getting nodes to delete for atomic node groups

cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go
This PR will prevent error once cluster-autoscaler is scaling the multi-zone nodepool from zero.
This is necessary because currently when we are trying to create a node template from the multi-zone nodepool, we create the zone-labels "[topology.kubernetes.io/zone](http://topology.kubernetes.io/zone)  " where the label is "eastus-1__eastus-2__eastus3".
However, this label is not recognized by some affinities.
With this PR, Cluster Autoscaler will create node templates using any random zone that the VMSS contains. However, this zone isn't the zone VMSS assigns VMs with. The VMSS will decide separately#### Which issue(s) this PR fixes:
Fixes #
```release-note
NONE
```
```docs
```
=> Adding temporary multizone-nodepool support for CAS

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go
/kind feature
This pr cherry picks HasInstance into 1.28 https://github.com/kubernetes/autoscaler/pull/6956
Fixes #
```release-note
```
```docs
```
=> cherry-pick(1.28): HasInstance implementation

cluster-autoscaler/cloudprovider/azure/OWNERS
/kind cherry-pick
https://github.com/kubernetes/autoscaler/pull/7100/commits
Fixes #
```release-note
```
```docs
```
=> cherry-pick: adding bryce soghigian to owners for azure (1.28)

cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_force_delete_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind cleanup
"Refactor" as a part of fork-upstream (managed-selfhosted) realignment. Should not have any breaking changes.
This codebases realignment will simplify the logistics between the two, cutting a significant portion of maintenance cost.
This PR specifically focus on instance caching.
There will be a separate effort focusing on improve code quality, rather than realigning codebase.
Fixes #
Most changes are merely refactor. Also include small fixes to refresh instance cache in more cases that should be required. Also include support for currently managed-exclusive flags (e.g., `EnableDetailedCSEMessage`).
There are similar PRs out on version release branches as well. Should be near identical.
```release-note
- Azure: fix some cases where instance cache is outdated but not getting …
```
=> refactor: upstream Azure managed instance cache refactor

cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
/kind feature
Instead of breaking the loop after deleting failed scale up nodes, clean up the state and continue. Most importantly, update the target for the affected node group, so that the deleted nodes are not considered upcoming.
This PR speeds up handling of failed scale ups, useful especially with multiple quota or stockout errors across the cluster.
The PR consists of 3 commits. The actual change is in commit `#3` while commits `#1` and `#2` are refactors necessary for the actual change.
```release-note
Faster handling of failed scale ups, useful especially with multiple quota or stockout errors across the cluster.
```
```docs
```
=> Faster handling of failed scale ups

vertical-pod-autoscaler/README.md
#7098
Tested in `1.27.14-gke.1059002` which is currently the lowest version available in GKE.
=> Update README.md to include VPA 1.2.0 release

cluster-autoscaler/cloudprovider/cloud_provider.go
=> Correct comment for AtomicIncreaseSize method

vertical-pod-autoscaler/OWNERS
I have met all requirements to join as reviewer:
- Member since [early May](https://github.com/kubernetes/org/issues/4935)
- [21 PRs authored and closed](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+author%3Araywainman+) - though many of them are fairly trivial release-related PRs.
- [19 PRs reviewed and closed](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+assignee%3Araywainman+)
- Familiar with codebase as I interact with it on a daily basis.
- Also active on Slack answering questions and in SIG meetings.
=> Add raywainman as reviewer of VPA

cluster-autoscaler/cloudprovider/oci/nodepools/cache.go
/kind bug
This PR fixes an issue with the [Oracle Cloud provider](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/oci) where node-group details stored in the internal cache-map can be unintentionally overwritten with the details of a different node group. 
This can occur because the node-group variable `resp` is declared _outside_ the loop that adds the next node-group value to the cache-map. The end result is the cache-map contains only the the _last_ NodePool in the list, which is referenced by different node-pool-ids / keys.
Fixes #
```release-note
```
```docs
```
=> Move GetNodePoolResponse variable inside for loop 

cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go, cluster-autoscaler/vendor/modules.txt
/kind feature
This PR is a cherry-pick for https://github.com/kubernetes/autoscaler/pull/7013
Fixes #
```release-note
NONE
```
```docs
```
=> Cherry pick: Adding temporary multizone-nodepool support for CAS

cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go
/kind feature
This is a cherry-pick for https://github.com/kubernetes/autoscaler/pull/7013
Fixes #
```release-note
NONE
```
```docs
```
=> 1.28 Adding temporary multizone-nodepool support for CAS

cluster-autoscaler/cloudprovider/oci/nodepools/cache.go
…ted.
Backport of PR [7186](https://github.com/kubernetes/autoscaler/pull/7186)
This PR fixes an issue with the [Oracle Cloud provider](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/oci) where node-group details stored in the internal cache-map can be unintentionally overwritten with the details of a different node group. 
This can occur because the node-group variable `resp` is declared _outside_ the loop that adds the next node-group value to the cache-map. The end result is the cache-map contains only the the _last_ NodePool in the list, which is referenced by different node-pool-ids / keys.
Fixes #
```release-note
```
```docs
```
=> PR#7186 Backport for 1.30: Move response variable inside for loop

cluster-autoscaler/FAQ.md
Adding more observed requirements to use the `ProvisioningRequest` feature.
Updating docs so that others can use `ProvisioningRequests`
Chatted with @yaroslava-serdiuk about these changes in [Slack](https://kubernetes.slack.com/archives/C09R1LV8S/p1720805795604139?thread_ts=1720506646.971539&cid=C09R1LV8S).
```release-note
```
```docs
```
=> Update FAQ.md to add steps for self-hosted provreq

cluster-autoscaler/FAQ.md, cluster-autoscaler/expander/expander.go, cluster-autoscaler/expander/factory/expander_factory.go, cluster-autoscaler/expander/leastnodes/leastnodes.go, cluster-autoscaler/expander/leastnodes/leastnodes_test.go
/kind feature
Cherry-picks https://github.com/kubernetes/autoscaler/pull/6792 into the 1.30 release.
Fixes #
```release-note
Added a new `least-nodes` expander
```
```docs
```
=> cherry-pick least-nodes expander from #6792 into 1.30

cluster-autoscaler/FAQ.md, cluster-autoscaler/expander/expander.go, cluster-autoscaler/expander/factory/expander_factory.go, cluster-autoscaler/expander/leastnodes/leastnodes.go, cluster-autoscaler/expander/leastnodes/leastnodes_test.go
/kind feature
Cherry-picks https://github.com/kubernetes/autoscaler/pull/6792 into the 1.29 release.
Fixes #
```release-note
Added a new `least-nodes` expander
```
```docs
```
=> cherry-pick least-nodes expander from #6792 into 1.29

cluster-autoscaler/FAQ.md, cluster-autoscaler/expander/expander.go, cluster-autoscaler/expander/factory/expander_factory.go, cluster-autoscaler/expander/leastnodes/leastnodes.go, cluster-autoscaler/expander/leastnodes/leastnodes_test.go
/kind feature
Cherry-picks https://github.com/kubernetes/autoscaler/pull/6792 into the 1.28 release.
Fixes #
```release-note
Added a new `least-nodes` expander
```
```docs
```
=> cherry-pick least-nodes expander from #6792 into 1.28

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/legacy/legacy_test.go, cluster-autoscaler/core/scaleup/orchestrator/async_initializer.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodegroups/asyncnodegroups/async_nodegroup_state_checker.go, cluster-autoscaler/processors/nodegroups/nodegroup_manager.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go
/kind feature
Built on top of [the closed PR](https://github.com/kubernetes/autoscaler/pull/7034)
Currently cluster-autoscaler is mostly synchronous. It creates node-groups and waits until creation is fully finished before scaling it up or running another scale-up iteration. Because node-group creation is a slow operation and AI workloads require scale-ups using a large number of node-groups, there is a need to introduce an asynchronous node-group creation to increase the throughput.
This PR introduces an additive api change for cloud providers to optionally implement asynchronous node-group creation.
A new "async-node-groups" experimental flag, that enables …
=> Async node group creation

vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/config_test.go, vertical-pod-autoscaler/pkg/admission-controller/main.go
/kind feature
Allows a user to set the failurePolicy of the VPA webhook
Fixes #7180
```release-note
Add --webhook-failure-policy-fail flag to admission-controller to allow web hook failurePolicy to be set to Fail
```
```docs
```
=> VPA: Add option to set the webhook failurePolicy to Fail

cluster-autoscaler/cloudprovider/azure/README.md
This PR documents the Azure provider's plan to migrate to a new label used to identify GPU Nodes in order to align with the labels used by AKS: https://learn.microsoft.com/en-us/azure/aks/use-labels#deprecated-labels
The rough plan is to:
- document that users need to set BOTH the current and new labels on GPU Nodes (this PR)
- wait for at least one minor version release cycle to allow users time to add the new label (until at least cluster-autoscaler 1.32)
- change the Azure provider from identifying GPU Nodes based on the old label to the new one
Fixes #
```release-note
ACTION REQUIRED: VMSS GPU Nodes must now also include the `kubernetes.azure.com/accelerator` label in addition to `accelerator`.
```
```docs
```
=> azure: document migration to new GPU Node label

cluster-autoscaler/main.go, cluster-autoscaler/processors/podinjection/backoff/backoff_registry.go, cluster-autoscaler/processors/podinjection/backoff/backoff_registry_test.go, cluster-autoscaler/processors/podinjection/enforce_injected_pods_limit_processor.go, cluster-autoscaler/processors/podinjection/enforce_injected_pods_limit_processor_test.go, cluster-autoscaler/processors/podinjection/job_controller.go, cluster-autoscaler/processors/podinjection/job_controller_test.go, cluster-autoscaler/processors/podinjection/pod_group.go, cluster-autoscaler/processors/podinjection/pod_injection_processor.go, cluster-autoscaler/processors/podinjection/pod_injection_processor_test.go, cluster-autoscaler/processors/podinjection/replicaset_controller.go, cluster-autoscaler/processors/podinjection/scale_up_status_processor.go, cluster-autoscaler/processors/podinjection/scale_up_status_processor_test.go, cluster-autoscaler/processors/podinjection/statefulset_controller.go
/kind feature
Introduce proactive scale up, to proactively scale up nodes based on replica count by injecting fake pods that triggers scale up logic which eliminates the need for waiting for the real pod to be marked as not scheduled then act and scale up
Cluster Autoscaler can now trigger large scale ups before all pending pods are created. This behavior is disabled by default and can be enabled with `--enable-proactive-scaleup` flag.
enable-proactive-scaleup  : To enable the new feature 
pod-injection-limit : Limits the total number of injected pods
=> Add proactive scaleup

cluster-autoscaler/FAQ.md
Fixes incorrect wording would in an FAQ. The correct phrasing should be "above the maximum" which then goes on to explain how the CA handles scaling down a nodepool that is currently above the maxNodes value
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> Fix incorrect wording in FAQ.md

cluster-autoscaler/utils/utils.go, cluster-autoscaler/utils/utils_test.go
/kind feature
Sanitize ENV from podSpec to improve scheduling simulation performance.
Cluster Autoscaler groups pods by their scheduling requirements for performance reasons. Group equality is determined by comparing pod specs, after sanitizing parts of the spec that are unique to specific pods, and that have no bearing on scheduling.
Currently ENV in containers of podSpec is not sanitized which in some cases make each pod in its own group affecting performance of scheduling simulation performance in Cluster Autoscaler.
It has triggered alert from 'overflowing_controllers_count' metric.
Fixes #
```release-note
NONE
```
=> Sanitize ENV from podSpec to improve scheduling simulation performance.

vertical-pod-autoscaler/hack/vpa-up.sh
/kind cleanup
/kind feature
This PR changes the recommended VPA install method to use `kubectl apply` instead of `kubectl create` under the hood to allow for rolling updates of VPA.
NONE
=> VPA: Use kubectl apply to upsert VPA resource instead of create.

cluster-autoscaler/apis/config/crd/autoscaling.x-k8s.io_provisioningrequests.yaml, cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1/types.go
/kind bug
In #7195 ProvisioningRequest API was bumped to v1, but CRD wasn't upgraded. CA 1.31 won't work without upgraded CRD.
```release-note
Adds CRD for ProvisioningRequest v1
```
/cc @MaciekPytel @mwielgus
=> Regenerate ProvisioningRequest CRD for  v1

cluster-autoscaler/processors/nodegroups/nodegroup_manager.go
/kind bug
This fix wrong nil pointer check in nodegroup_manager.go
```release-note
None
```
=> Fix nil pointer check in nodegroup_manager.go

vertical-pod-autoscaler/pkg/admission-controller/logic/server.go, vertical-pod-autoscaler/pkg/admission-controller/resource/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler_test.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher_test.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/recommender/model/cluster.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher_fake.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher_test.go, vertical-pod-autoscaler/pkg/target/fetcher.go, vertical-pod-autoscaler/pkg/target/mock/fetcher_mock.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go, vertical-pod-autoscaler/pkg/utils/vpa/api_test.go
/kind bug
This PR wires contexts in the vpa-admission-controller so that it does no longer process admission requests after the requests is canceled client-side (kube-apiserver side) already.
Fixes https://github.com/kubernetes/autoscaler/issues/6891
```release-note
Contexts in the vpa-admission-controller are now wired. The vpa-admission-controller will no longer continue to process requests once the HTTP request's context in canceled client-side (kube-apiserver side). Previously, in some client-side throttling cases the vpa-admission-controller was continuing to wait for the client-side throttling (> 50m) while the kube-apiserver request was canceled after 10s.
```
```docs
```
=> vpa-admission-controller: Wire contexts

cluster-autoscaler/cloudprovider/azure/README.md, cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go
/kind cleanup
This PR follows up from #7203 to migrate the Azure provider from using the `accelerator` label to identify GPU Nodes to the `kubernetes.azure.com/accelerator`. #7203 documented that users must set \*both\* labels in 1.31, so this change should not break users following that instruction.
Fixes #
```release-note
ACTION REQUIRED: VMSS GPU Nodes are now identified by the `kubernetes.azure.com/accelerator` label instead of `accelerator`.
```
```docs
```
=> azure: use new label to identity GPU Nodes

addon-resizer/OWNERS
I have reviewed and contributed several PRs for this component:
https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+addon-resizer+raywainman
#7241 adds this to master branch.
=> Add raywainman to reviewers in addon-resizer in addon-resizer-release-1.8 branch

cluster-autoscaler/cloudprovider/azure/test/Makefile, cluster-autoscaler/cloudprovider/azure/test/e2e/azure_test.go, cluster-autoscaler/cloudprovider/azure/test/e2e/e2e_suite_test.go, cluster-autoscaler/cloudprovider/azure/test/templates/cluster-template-prow-aks-aso-cluster-autoscaler.yaml
/kind cleanup
This PR forward-ports(?) some small changes made on release branches to enable Azure e2e tests to the master branch.
Fixes #
```release-note
NONE
```
```docs
```
=> align Azure e2e tests with backports

cluster-autoscaler/processors/provreq/injector_test.go, cluster-autoscaler/provisioningrequest/provreqwrapper/testutils.go
/kind cleanup
Added new unit test to ensure that un-schedulable pods list is not overwritten when the pod list injector's process method is called
Fixes #
```release-note
NONE
```
```docs
```
cc: @aleksandra-malinowska @kawych
=> Add unit test to ensure un-schedulable pods slice is not overwritten by injector

cluster-autoscaler/cloudprovider/aws/aws_nodegroups.go, cluster-autoscaler/cloudprovider/aws/aws_nodegroups_test.go, cluster-autoscaler/cloudprovider/azure/azure_nodegroups.go, cluster-autoscaler/cloudprovider/azure/azure_nodegroups_test.go, cluster-autoscaler/cloudprovider/gce/gce_nodegroups.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodegroupset/balancing_processor_test.go, cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go, cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test_helpers.go, cluster-autoscaler/processors/nodegroupset/label_nodegroups_test.go
/kind cleanup
This PR moves the cloudprovider-specific implementations of nodegroupset into cloudprovider-managed code areas so that they can be more easily maintained without involving core cluster-autoscaler maintainers.
This should not have any impact on compilation outcomes, the idea is to simply re-organize code.
Fixes #
```release-note
NONE
```
```docs
```
=> CAS: cloudprovider-specific nodegroupset

vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go
/kind bug
Optionally add one or more of the following kinds if applicable:
regression introduced by this [PR](https://github.com/kubernetes/autoscaler/commit/4b459a200989c6dff752ce346253e1f41e401c10)
if `gk, err := key.groupKind()` returns error, `gk` will be empty struct, the if condition will never become true
=> fix VPA controller_fetcher node validation

vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
/kind bug
In https://github.com/kubernetes/autoscaler/pull/6899/files#diff-5c44f22eb0f35931ab799838d2584dd10037916c74f114124e6904af48fcd608R157, I wrongly passed a context that is specific only to the `MaintainCheckpoints` step to 2 other steps: `LoadVPAs` and `GarbageCollect `.
This PR reverts to the old behaviour where the context with timeout of 1min by default was used only for the `MaintainCheckpoints` step.
**Which issue(s) this PR fixes**:
N/A
**Special notes for your reviewer**:
N/A
**Release note**:
```other operator
NONE
```
=> vpa-recommender: Use the MaintainCheckpoints context only for that step

cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
/kind feature
This PR adds support to the HCLOUD_ENDPOINT environment variable, following what's used by other projects like https://github.com/hetznercloud/hcloud-cloud-controller-manager and https://github.com/hetznercloud/csi-driver.
Fixes #7284
[We](https://github.com/altinity) have developed a soon-to-be-open-source proxy that forces specific labels in order to provide scoped API access. This support is required to make full use of it inside a Kubernetes cluster.
```release-note
The HCLOUD_ENDPOINT environment variable is now supported to set a custom endpoint for Hetzner usage is cluster-autoscaler.
```
```docs
```
=> Support custom HCLOUD_ENDPOINT in cluster-autoscaler Hetzner manager

vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/logic/updater_test.go, vertical-pod-autoscaler/pkg/utils/status/status_object.go, vertical-pod-autoscaler/pkg/utils/status/status_object_test.go, vertical-pod-autoscaler/pkg/utils/status/status_updater.go
/kind bug
For details, see #6884.
Fixes #6884
```release-note
vpa-admission-controller: The lease updates that the vpa-admission-controller performs (that are later on checked by the vpa-updater for healthiness of the vpa-admission-controller) are now executed with a timeout of 10s. 
```
```docs
```
=> vpa-admission-controller: Contextify status updates. Add timeout of 10s

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
/kind cleanup
The `cx11` server type was deprecated on 2024-06-06 and will be removed from the API on 2024-09-06. Once it is removed, the cluster-autoscaler provider hetzner will fail every main loop with with the following error messages:
mixed_nodeinfos_processor.go:160] Unable to build proper template node for draining-node-pool: failed to create resource list for node group draining-node-pool error: failed to get machine type cx11 info error: server type not found
static_autoscaler.go:387] Failed to get node infos for groups: failed to create resource list for node group draining-node-pool error: failed to get machine type cx11 info error: server type not found
The server type is hardcoded in the `draining-node-pool`, which was used in the OG PR #3640 but unused in the …
=> fix(hetzner): deprecated server type will break on 2024-09-06

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
/kind cleanup
The `cx11` server type was deprecated on 2024-06-06 and will be removed from the API on 2024-09-06. Once it is removed, the cluster-autoscaler provider hetzner will not start anymore with the following error message:
Failed to get node infos for groups: failed to create resource list for node group draining-node-pool error: failed to get machine type cx11 info error: server type not found
As the node pool `draining-node-pool` is not being used anywhere, this commit removes it and the hard coded reference to the deprecated server type.
Backport of #7211 to `1.31` branch.
Related to #7210
```release-note
Fix Hetzner Provider not starting after 2024-09-07
```
```docs
- [Hetzner Cloud Changelog](https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-share …
```
=> [v1.31] fix(hetzner): deprecated server type will break on 2024-09-06

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
/kind cleanup
The `cx11` server type was deprecated on 2024-06-06 and will be removed from the API on 2024-09-06. Once it is removed, the cluster-autoscaler provider hetzner will not start anymore with the following error message:
Failed to get node infos for groups: failed to create resource list for node group draining-node-pool error: failed to get machine type cx11 info error: server type not found
As the node pool `draining-node-pool` is not being used anywhere, this commit removes it and the hard coded reference to the deprecated server type.
Backport of #7211 to `1.30` branch.
Related to #7210
```release-note
Fix Hetzner Provider not starting after 2024-09-07
```
```docs
- [Hetzner Cloud Changelog](https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-share …
```
=> [v1.30] fix(hetzner): deprecated server type will break on 2024-09-06

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind bug
/kind cleanup
The `cx11` server type was deprecated on 2024-06-06 and will be removed from the API on 2024-09-06. Once it is removed, the cluster-autoscaler provider hetzner will not start anymore with the following error message:
Failed to get node infos for groups: failed to create resource list for node group draining-node-pool error: failed to get machine type cx11 info error: server type not found
As the node pool `draining-node-pool` is not being used anywhere, this commit removes it and the hard coded reference to the deprecated server type.
Backport of #7211 to `1.29` branch.
Related to #7210
```release-note
Fix Hetzner Provider not starting after 2024-09-07
```
```docs
- [Hetzner Cloud Changelog](https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-share …
```
=> [v1.29] fix(hetzner): deprecated server type will break on 2024-09-06

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
/kind bug
/kind cleanup
The `cx11` server type was deprecated on 2024-06-06 and will be removed from the API on 2024-09-06. Once it is removed, the cluster-autoscaler provider hetzner will not start anymore with the following error message:
Failed to get node infos for groups: failed to create resource list for node group draining-node-pool error: failed to get machine type cx11 info error: server type not found
As the node pool `draining-node-pool` is not being used anywhere, this commit removes it and the hard coded reference to the deprecated server type.
Backport of #7211 to `1.28` branch.
Related to #7210
```release-note
Fix Hetzner Provider not starting after 2024-09-07
```
```docs
- [Hetzner Cloud Changelog](https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-share …
```
=> [v1.28] fix(hetzner): deprecated server type will break on 2024-09-06

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/injector.go, cluster-autoscaler/processors/provreq/injector_test.go
=> Add backoff mechanism for ProvReq retry

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
Not all the reservations-related error messages coming from GCE are categorized correctly which may cause issues while handling them
```release-note
```
```docs
```
=> Register new GCE reservations error message regexp to correctly categorize error.

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml, cluster-autoscaler/README.md
/kind feature
Bump the Chart version to 9.38.0 and the CA image to 1.31.0
Fixes #
```release-note
Bump the Chart version to 9.38.0 and the CA image to 1.31.0
```
```docs
```
=> Bump CA Chart image to v1.31

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/extra-manifests.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
Add the ability to specify K8s extra objects
Fixes #5633
```release-note
Added the ability to specify K8s extra objects.
```
```docs
```
=> feat(chart): added the ability to specify K8s extra objects

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
In the scope of this commit new error mappings were added to the autoscaling GCE client, to cover the following errors on the GCE side:
- Reservation out of resources,
- Reservation does not exist (extended INVALID_RESERVATION),
- Unsupported TPU configuration.
Additionally removed the code smell in two functions, to which a parameter, errorCode, was unnecessarily passed (wasn't used by the functions).
/kind feature
see #7302 
Fixes #7302 
```release-note
NONE
```
=> Add new error mappings to autoscaling GCE client

vertical-pod-autoscaler/hack/vpa-process-yamls.sh
/kind bug
Fixes https://github.com/kubernetes/autoscaler/issues/7270
The gencert.sh is run with a `|| true`, so it doesn't matter if it fails: https://github.com/kubernetes/autoscaler/blob/59aba2b4063ad195075636e371345c2f75c7522a/vertical-pod-autoscaler/hack/vpa-process-yamls.sh#L67
And gencert uses `kubectl create` (see
https://github.com/kubernetes/autoscaler/blob/59aba2b4063ad195075636e371345c2f75c7522a/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh#L58-L65) so if it were run multiple times, it would fail.
Fixes https://github.com/kubernetes/autoscaler/issues/7270
```release-note
NONE
```
```docs
```
=> fix: Generate certs for VPA on kubectl apply or create

vertical-pod-autoscaler/pkg/admission-controller/certs.go, vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go
/kind cleanup
To align the logging with the best practices and guidelines established within the Kubernetes ecosystem.
As part of https://github.com/kubernetes/autoscaler/issues/6905, I'm splitting this into multiple PRs rather than submitting a single large PR.
```release-note
NONE
```
```docs
NONE
```
=> Refactor logging statements in admission controller

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/values.yaml, cluster-autoscaler/cloudprovider/exoscale/README.md, cluster-autoscaler/cloudprovider/exoscale/exoscale_cloud_provider.go, cluster-autoscaler/cloudprovider/exoscale/exoscale_cloud_provider_test.go, cluster-autoscaler/cloudprovider/exoscale/exoscale_manager.go, cluster-autoscaler/cloudprovider/exoscale/exoscale_manager_test.go, cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_sks_nodepool.go, cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_sks_nodepool_test.go
/kind feature
**cluster-autoscaler/exoscale:** This PR adds support for configuration of minimum and maximum size of specified node groups via the `--nodes=<min>:<max>:<nodepool-name>` flag.
Fixes #
```release-note
NONE
```
```docs
```
=> feat(cluster-autoscaler/exoscale): add support for --nodes

cluster-autoscaler/cloudprovider/kwok/README.md
- It adds the definite article "the" where necessary in the documentation.
- It adds an indefinite article "a" where necessary in the documentation.
- It replaces the plural "hostnames" with the singular word "hostname" to describe that only one hostname node label key `kubernetes/hostname` exists. 
- It adds "with" to indicate what is being interacted with.
- It uses a lowercase for the word "using" because the word is not a noun, and neither does it start the sentence.
=> Update README.md (KWOK)

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/servicemonitor.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
Prometheus service discovery meta-labels `__meta_kubernetes_*` labels are not necessarily still attached to a metric when the metric_relabel_configs step is reached. Consequently, it is not possible to configure a label on pod as a metric tag using the chart solely. Adding the `relabelings` value to the ServiceMonitor will allow this use case. 
```release-note
Added relabelings config for the ServiceMonitor to the Helm chart
```
=> feat: Add relabelings config to ServiceMonitor resource

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
It adds the ability to run init (and sidecar) containers within the cluster-autoscaler deployment when installing via helm. A lot of providers depend on configuration options and files depending on their cloud provider. A init container or sidecar container would allow to execute any logic in order to get or create the autoscaler provider configuration dynamically. 
Fixes #
Not existing yet
Example and test usage:
```bash
helm template -f myvalue.yaml -s templates/deployment.yaml
```
```yaml
initContainers:
- name: get-cloud-conf
image: alpine:latest
command: ["sh", "-c", "curl -sl https://my-cloud-conf.com/user-data -o /opt/user-data/scale.conf"]
volumeMounts:
- name: user-data
mountPath: /opt/user-data
extraVolumeMounts:
- name: user-data
mountPath: /opt/user-data …
```
=> feat: allow setting init containers for cluster-autoscaler

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/templates/servicemonitor.yaml
/kind cleanup
This PR applies the same logic used in other `templates/` to the annotations of the ServiceMonitor.
While this is good general cleanup, this also has a side-effect of improving [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) integration. Without this, if you leave the annotations default (empty) and deploy with ArgoCD, it will *always* detect a noop diff
```release-note
NONE
```
=> Only render ServiceMonitor annotations if not empty

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
/kind feature
Handle errors related to exceeded capacity in reservation separately in order to give a better visibility to the user
```release-note
NONE
```
=> Handle reservation capacity exceeded error separately

cluster-autoscaler/cloudprovider/azure/azure_config.go
/kind cleanup
This PR will allow CAS to set `azure.Config.EnableDetailedCSEMessage` based on the value of a `AZURE_ENABLE_DETAILED_CSE_MESSAGE` environment variable.
Fixes #
```release-note
NONE
```
```docs
```
=> azure: use AZURE_ENABLE_DETAILED_CSE_MESSAGE environment variable

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client_test.go
/kind feature
Add more granular reservation errors to improve visibility
```release-note
NONE
```
=> Make reservation errors more granular

cluster-autoscaler/cloudprovider/externalgrpc/examples/external-grpc-cloud-provider-service/wrapper/wrapper.go
/kind bug
Improves checking for empty cloudprovider.NodeGroup results. Uses reflect.ValueOf().IsNil() to catch both nil interfaces and interfaces holding nil values.
Fixes #7209
```release-note
None
```
```docs
None
```
=> Fix nil handling in NodeGroupForNode wrapper

cluster-autoscaler/processors/podinjection/enforce_injected_pods_limit_processor.go
/kind bug
Makes sure that injected pods metric includes only the number of pods that were injected after enforcing the pod limit.
(i.e. If 10 pods were injected but 3 got removed because we've gone over the pod limit, 7 should be the reported metric not 10)
Fixes #
```release-note
NONE
```
```docs
```
=> Report only injected pods after enforcing pod limit

cluster-autoscaler/cloudprovider/azure/test/Makefile
/kind cleanup
This PR adjusts builds for cluster-autoscaler in Azure e2e tests to only build with the `azure` provider. This should reduce build times and give slightly more overall test coverage for building for specific providers.
Fixes #
```release-note
NONE
```
```docs
```
=> build for azure e2e tests with only azure provider

.github/dependabot.yml
/kind bug
This PR configures the `ignore` option in depandabot.yaml so that Depandadabot ignores Golang rc versions.
Fixes #7029
```release-note
None
```
```docs
```
=> Added Ignore option in depandabot.yaml to ignore golang rc versions.

cluster-autoscaler/processors/podinjection/enforce_injected_pods_limit_processor.go
/kind bug
This PR is cherry-picked, which backports  #7335 and #7338 into CA 1.31
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #7335 and #7338[CA]Adds injection metrics for fake pod injection and Report only injected pods after enforcing pod limit into CA1.31

cluster-autoscaler/FAQ.md
- instructions were missing the crd
- was unclear who needs to api flag
- had no examples how the request actually works
```release-note
NONE
```
cc @yaroslava-serdiuk
=> expand docs for ProvisioningRequest

cluster-autoscaler/cloudprovider/oci/nodepools/cache.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager.go
bug
When a nodepool was deleted and no more exists in OCI, cluster autoscaler wouldn't work as expected until nodepoolid was removed from config and pod was restarted. We need this code change to ensure cluster autoscaler would still work even with a wrong nodepoolid was provided. In such a scenario, cluster autoscaler will remove the nodepoolid from the list and write logs. It will still work as expected with the remaining nodepools in the list. 
Fixes #
Tests are done on a OCI cluster. If nodepool doesn't exist, it prints a log and removes it from the nodepool list. Below is the cluster autoscaler pod logs from the test.
```
gkazanci@gkazanci-mac clusterAutoscaler % kubectl logs cluster-autoscaler-85b78cfc45-pvl66  -n kube-system
I0913 09:25:38.536420       1 leaderelection.go:250] …
```
=> allow CA working even with a wrong oci nodepoolid provided

cluster-autoscaler/expander/grpcplugin/grpc_client.go, cluster-autoscaler/expander/grpcplugin/grpc_client_test.go
/kind bug
When trying to filter out all options from the gRPC expander side, I noticed that the gRPC expander client on cluster autoscaler would return all the expansion options, rather than none of them.
This is a problem because in some cases I want to filter out all options on the gRPC expander server side, however the cluster-autoscaler client is unfiltering the options when the server returns nothing. 
I would expect that if the gRPC expander server returns no best options, CA should fail its scaleup since it has no options available.
In the case of nil best options returned from the gRPC expander, the gRPC client returns all original options https://github.com/kubernetes/autoscaler/blob/721ea01f7f284484fa491ae89e08bded434bcd46/cluster-autoscaler/expander/grpcplugin/grpc_client.go#L95 …
=> Handle intentionally empty grpc BestOptions

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
/kind cleanup
this change fixes the import order so that the goimports tool does not complain about the ordering.
Fixes #
```release-note
NONE
```
```docs
```
=> cleanup clusterapi imports

cluster-autoscaler/loop/trigger.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/injector.go, cluster-autoscaler/processors/provreq/injector_test.go
/kind feature
Created lastProvisioningRequestSeenTime which gets updated whenever a provisioningrequest is encountered in an iteration, which is used when frequent loops is enabled to start next iteration without delay.
Fixes #
```release-note
Support for frequent loops when ProvisioiningRequest is encountered in last loop.
```
```docs
```
cc: @yaroslava-serdiuk @aleksandra-malinowska @kawych
=> Add support for frequent loops when provisioningrequest is encountered in last iteration

vertical-pod-autoscaler/pkg/admission-controller/Dockerfile, vertical-pod-autoscaler/pkg/recommender/Dockerfile, vertical-pod-autoscaler/pkg/updater/Dockerfile
/kind cleanup
Updated Dockerfiles to replace deprecated MAINTAINER instructions with LABEL.
Fixes #
```release-note
None
```
```docs
None
```
=> Replace deprecated MAINTAINER with LABEL

cluster-autoscaler/clusterstate/clusterstate.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go
/kind cleanup
This PR filters out upcoming node groups in clusterstate and scale-up executor to limit the number of generated warning logs. It does not effectively change the logic.
N/A
cc: @x13n 
```release-note
NONE
```
=> Filter upcoming nodes in clusterstate and scale-up executor

cluster-autoscaler/core/scaleup/orchestrator/async_initializer.go, cluster-autoscaler/processors/nodegroups/nodegroup_manager.go
/kind cleanup
Synchronizes access to target sizes stored in AsyncNodeGroupInitializer. AsyncNodeGroupInitializer is designed to be used from different goroutines so synchronization is required. I'm marking this PR as a cleanup (not a bug), as this mechanism is not used ATM.
N/A
cc: @x13n 
```release-note
NONE
```
=> Synchronize access to scale-ups in AsyncNodeGroupInitializer

vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
/kind bug
When generating OpenAPI schemas from the go types using kube-openapi the process fails with an error in the validation phase because the type is not consistently annotated.
There's a mismatch between the json tags and the missing +patchStrategy comment.
This PR fixes the problem by adding the required comment.
n/a
NONE
=> fix: add missing +patchStrategy comment tag

vertical-pod-autoscaler/hack/vpa-process-yamls.sh
I made a typo in https://github.com/kubernetes/autoscaler/pull/7306, the input should be `apply` and not `update`, since `update` isn't a valid kubectl command
/kind bug
Fixes https://github.com/kubernetes/autoscaler/issues/7270
https://github.com/kubernetes/autoscaler/pull/7306 had a typo in it and didn't correctly fix 7270.
Fixes https://github.com/kubernetes/autoscaler/issues/7270
```release-note
```
```docs
```
=> fix: VPA use apply rather than update

cluster-autoscaler/loop/trigger.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/injector.go, cluster-autoscaler/processors/provreq/injector_test.go
Reverts kubernetes/autoscaler#7271
=> Revert "Add support for frequent loops when provisioningrequest is encountered in last iteration"

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
/kind bug
This PR fixed the External IPs link under the CA Chart [README.md](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/README.md).
Fixes #
```release-note
None
```
```docs
```
=> Fixed External IPs service link.

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_source.go, vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go, vertical-pod-autoscaler/pkg/recommender/model/container.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
/kind cleanup
To align the logging with the best practices and guidelines established within the Kubernetes ecosystem.
As part of https://github.com/kubernetes/autoscaler/issues/6905, I'm splitting this into multiple PRs rather than submitting a single large PR.
```release-note
NONE
```
```docs
NONE
```
=> Refactor logging statements in recommender:checkpoint,input

addon-resizer/healthcheck/healthcheck.go, addon-resizer/nanny/nanny_lib.go
/kind feature
Health check in non-leader pods will fail when running in leader election mode as non-leader pods don't update lastActivity timestamp. This PR adds a condition so that only leader pod will check lastActivity field.
None
```release-note
None
```
```docs
```
=> Support health check for non-leader pods

vertical-pod-autoscaler/pkg/admission-controller/README.md, vertical-pod-autoscaler/pkg/admission-controller/config.go, vertical-pod-autoscaler/pkg/admission-controller/config_test.go, vertical-pod-autoscaler/pkg/admission-controller/main.go
/kind feature
feat: add webhook labels flag to add labels in VPA admission controller webhook
In AKS, VPA can't admit pods in kube-system namespace. Reference to [Can admission controller webhooks impact kube-system and internal AKS namespaces?](https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces-), VPA can add Label: "admissions.enforcer/disabled": "true" in admission controller webhook to impact kube-system namespace. Add a flag to add webhook labels.
Fixes #https://github.com/kubernetes/autoscaler/issues/7392
```release-note
The --webhook-labels flag is added. Users can use webhook-labels flag in admission controller to add labels in vpa-webhook
```
```docs
```
=> feat: add webhook labels flag to add labels in VPA admission controller webhook

cluster-autoscaler/provisioningrequest/provreqclient/client.go
/kind cleanup
Empty ProvReq Spec in Update() method caused flakiness in unit test for https://github.com/kubernetes/autoscaler/pull/7283
The empty spec was added when podTemplate was embedded in ProvReq and since now the podTemplate is referenced in ProvReq, we can safely get rid of it.
=> Remove redundant copy in UpdateProvisioningRequest() method

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/testutils.go, cluster-autoscaler/provisioningrequest/checkcapacity/provisioningclass.go, cluster-autoscaler/provisioningrequest/checkcapacity/provisioningclass_test.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go, cluster-autoscaler/provisioningrequest/provreqclient/client.go, cluster-autoscaler/provisioningrequest/provreqclient/testutils.go, cluster-autoscaler/provisioningrequest/provreqwrapper/wrapper.go
/kind feature
Implements batch processing such that user can configure CA to process multiple CheckCapacity ProvisioningRequests in a single autoscaling iteration.
Fixes #
```release-note
Allows CheckCapacity ProvisioningRequests to be processed in batch mode with configurable max batch size and batch timebox enabled by feature flags.
```
```docs
```
cc: @yaroslava-serdiuk @aleksandra-malinowska @kawych
=> Implemented batch processing for check capacity provisioning class

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind feature
Hetzner introduced a new node label to distinguish between dedicated servers and cloud VMs. This is primarily used to workround the scheduler limitation for CSI volumes. This PR adds the label to `TemplateNodeInfo`.
Further information:
- https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/764
- https://github.com/hetznercloud/csi-driver/pull/743
```release-note
Hetzner: Consider label `instance.hetzner.cloud/provided-by` for scheduling
```
```docs
```
=> feat(hetzner): autoscaler includes new provided-by label

cluster-autoscaler/core/scaledown/planner/planner.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/scaledown/unneeded/nodes.go, cluster-autoscaler/core/scaledown/unneeded/nodes_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/scaleup/resource/manager_test.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/core/test/common.go, cluster-autoscaler/processors/nodes/scale_down_context.go, cluster-autoscaler/processors/nodes/scale_down_set_processor.go, cluster-autoscaler/processors/nodes/scale_down_set_processor_test.go, cluster-autoscaler/processors/nodes/types.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/processors/test/common.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go, cluster-autoscaler/simulator/cluster.go
/kind bug
/kind cleanup
Modify scale down set processor to add reasons to unremovable nodes so that planner can have these nodes excluded as unremovable nodes with reasons
1. Moved NewTestProcessors to be under processors/test to avoid the following circular dependency : nodes (ScaleDownSetProcessor)-> ScaleDownContext-> resource -> test (core/test/common)-> nodes (ScaleDownSetProcessor)
2. On adding unit tests for planner I noticed that MaxNodesProcessor is being called before AtomicResizeFilteringProcessor which might cause filtering removable nodes on both calls ending up with less nodes to be deleted than we should be deleting, created an issue for it https://github.com/kubernetes/autoscaler/issues/7342
NONE
=> Modify scale down set processor to add reasons to unremovable nodes

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
/kind cleanup
This PR is cherry-picked, which backports #7388 into CA 1.30
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #7388 [CA] cleanup clusterapi imports into CA 1.30

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
/kind cleanup
This PR is cherry-picked, which backports #7388 into CA 1.31
Fixes #
```release-note
NONE
```
```docs
```
=> Backport #7388 [CA] cleanup clusterapi imports into CA 1.31

vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher_test.go, vertical-pod-autoscaler/pkg/target/fetcher.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go, vertical-pod-autoscaler/pkg/utils/vpa/api_test.go
/kind bug
As outlined in https://github.com/kubernetes/autoscaler/issues/6925, right now the logic in the vpa-admission-controller to find the matching VPA for a Pod is expensive/ineffective. In a summary, no matter the given Pod is scaled by VPA or not, the vpa-admission-controller gets all VPAs in the namespace and fetches the selector for every VPA. Fetching the selector for a VPA is an expensive operation when the VPA's targetRef is a custom resource. For such cases, the `/scale` subresource is being fetched. Note that the used `selectorFetcher` does not have a cache client-side and it always does a GET request for the `/scale` subresource: https://github.com/kubernetes/autoscaler/blob/c79bdaf76210eb9ed9952da579196b87afb5665c/vertical-pod-autoscaler/pkg/target/fetcher.go#L130
This PR …
=> vpa-admission-controller: Improve finding the matching VPA for Pod

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
/kind cleanup
This PR added the `service.clusterIP` to the values.yaml.
Fixes #6631
```release-note
NONE
```
```docs
```
=> Improvement: Added service.clusterIP

vertical-pod-autoscaler/FAQ.md, vertical-pod-autoscaler/README.md, vertical-pod-autoscaler/pkg/recommender/main.go
Updates documentation to warn and inform users about how to properly use leader election in GKE when deploying their own VPA recommender.
#7461
=> Small documentation changes to warn users about deploying VPA with leader election on GKE.

vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/logic/updater_test.go, vertical-pod-autoscaler/pkg/utils/test/test_utils.go
/kind feature
A user asked for the VPA to emit an event that is related to the VPA object, in addition to the event related to the Pod object.
This makes sense, I see it as a "log" of sorts of what a particular VPA is up to.
Fixes #7149
```release-note
Create VPA Event (in addition to a Pod event) when a Pod is evicted
```
```docs
```
=> VPA: Create event for VPA object when Pod is evicted

vertical-pod-autoscaler/pkg/recommender/logic/recommender.go, vertical-pod-autoscaler/pkg/recommender/model/types.go, vertical-pod-autoscaler/pkg/recommender/model/types_test.go
/kind feature
Improves resource reporting by converting raw memory values (bytes) into human-readable binary units (KiB, MiB, GiB, TiB). Allowing users to quickly understand memory quantities without interpreting large byte numbers.
Fixes #7417
```release-note
Additional flag to recommender --humanize-memory
```
```docs
NONE
```
=> feat: humanize memory quantities using binary SI units

cluster-autoscaler/FAQ.md
Adds information about usage of batch processing for check capacity in FAQ
Fixes #
```release-note
NONE
```
```docs
```
cc: @aleksandra-malinowska  @kawych
=> Add information about usage of batch processing for check capacity in FAQ

cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go
/kind bug
Fixes https://github.com/kubernetes/autoscaler/issues/7102
This PR reduces the number of unneeded `DescribeLaunchTemplateVersions` API calls. Previously there was a PR that only looked for instance requirements when needed https://github.com/kubernetes/autoscaler/pull/5550. However this PR https://github.com/kubernetes/autoscaler/pull/6245 introduced a regression where now it looks for instance requirements all the time.
However in the [original fix PR](https://github.com/kubernetes/autoscaler/pull/5550) it was stated:
> But retrieving InstanceRequirements should only be useful when the LT overrides don't already specify an InstanceType, as both are mutually exclusive. The [api reference doc](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_LaunchTemp …
=> AWS: only cache instance requirements when needed

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
/kind bug
This PR adds a `StrictCacheUpdates` configuration for the Azure cluster-autoscaler provider (triggered by the `AZURE_STRICT_CACHE_UPDATES` runtime environment variable) that enables a modified Azure VMSS delete flow so that the local CA cache representation of node pool replica count is only updated upon a successful delete.
The current predictive cache update implementation was originally implemented here:
- https://github.com/kubernetes/autoscaler/pull/3036
The above works in most cases, but in situations where VMSS delete operations repeatedly fail, we see the the local CA cache gradually decrementing itself during each subsequent delete operation, which has the side-effect of eventually sending a VMSS replica update with a significantly reduced replica count when Azure API …
=> azure: StrictCacheUpdates to disable proactive vmss cache updates

cluster-autoscaler/cloudprovider/ionoscloud/ionoscloud_cloud_provider.go, cluster-autoscaler/cloudprovider/ionoscloud/ionoscloud_cloud_provider_test.go
/kind bug
This check is already done in https://github.com/kubernetes/autoscaler/blob/92c182feda0a08a7ff594bff17f457713294f61b/cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go#L437-L447 so we don't have to do it again.
```release-note
NONE
```
```docs
```
=> Remove obsolete upper bound check

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind cleanup
Fixes #
```release-note
```
=> [release-1.31] Add flag to enable fast delete of failed VMSS

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind cleanup
Fixes #
```release-note
```
=> [release-1.28] Add flag to enable fast delete of failed VMSS

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind cleanup
Fixes #
```release-note
```
=> [release-1.29] Add flag to enable fast delete of failed VMSS

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind cleanup
Fixes #
```release-note
```
=> [release-1.30] Add flag to enable fast delete of failed VMSS

cluster-autoscaler/cloudprovider/gce/gce_price_model.go
Change log level  and type of boot dist type and size defaulting in gce_price
/kind cleanup
This PR updates log level  and type of boot dist type and size defaulting in gce_price
Fixes #
NONE
```release-note
```
```docs
```
=> Change log level of boot dist type and size defaulting in gce_price

cluster-autoscaler/cloudprovider/oci/common/oci_ref.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_cloud_provider.go
/kind bug
When a mixture of self-managed-nodes and nodepools are created in a cluster, it breaks the cluster-autoscaler because self-managed-nodes don't have a nodepoolid, but oci-cloud provider tries to find and match nodes by nodepoolids. This PR fixes the issue as it marks the self-managed-nodes by **oci.oraclecloud.com/node.info.byon** label and excludes it from being processed.
NA
Before change cluster-autoscaler was failing with these error logs.
```
E1101 11:30:17.654871       1 static_autoscaler.go:995] Failed to get a node group node node: node pool not found for node in cache
E1101 11:30:17.655449       1 static_autoscaler.go:380] Failed to get node infos for groups: node pool not found for node in cache
```
After fix, it started to work as expected and see that it can scale up …
=> exclude self-managed nodes from being processed

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
/kind feature
This PR adds support for specifying a placement group for a node pool using the `HCLOUD_CLUSTER_CONFIG` JSON. This is a nice feature to have because it allows you to spread a node pool's VMs over different physical hardware, increasing the overall resilience of the pool.
Fixes #5919 
This is the first go code that I have written, so I apologize if it's a total mess. Also, I'm not sure how to setup a dev/testing environment for this project, so I was not able to actually run this code to test it.
```release-note
Add support for specifying node pool placement groups when using HCLOUD_CLUSTER_CONFIG
```
```docs
To specify a placement group, use JSON like this:
{
"nodeConfigs": {
"pool-1": {
"placementGroup": "name or ID here"
}
}
```
=> Add support for node pool placement group config

cluster-autoscaler/core/podlistprocessor/filter_out_expendable.go, cluster-autoscaler/core/podlistprocessor/filter_out_expendable_test.go, cluster-autoscaler/core/podlistprocessor/filter_out_schedulable_test.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/drain_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/estimator/binpacking_estimator_test.go, cluster-autoscaler/processors/podinjection/pod_injection_processor_test.go, cluster-autoscaler/simulator/cluster.go, cluster-autoscaler/simulator/clustersnapshot/basic.go, cluster-autoscaler/simulator/clustersnapshot/clustersnapshot.go, cluster-autoscaler/simulator/clustersnapshot/clustersnapshot_benchmark_test.go, cluster-autoscaler/simulator/clustersnapshot/clustersnapshot_test.go, cluster-autoscaler/simulator/clustersnapshot/delta.go, cluster-autoscaler/simulator/clustersnapshot/test_utils.go, cluster-autoscaler/simulator/predicatechecker/schedulerbased_test.go, cluster-autoscaler/simulator/scheduling/hinting_simulator.go
/kind cleanup
This is a part of Dynamic Resource Allocation (DRA) support in Cluster Autoscaler. The `ClusterSnapshot` interface is cleaned up to facilitate later changes needed for DRA:
* There were multiple methods for adding Nodes to the snapshot. This causes redundancy in `ClusterSnapshot` implementations for no clear reason. Instead of adding DRA handling to all these methods, they're replaced with `AddNodeInfo` which is DRA-aware already.
* `RemoveNode` is renamed to `RemoveNodeInfo` for consistency with `AddNodeInfo`.
* `AddPod` and `RemovePod` are renamed to `SchedulePod` and `UnschedulePod`. These names are more in-line with the method behavior when DRA is considered (a pod is not "removed" from the snapshot altogether, since we have to keep tracking its DRA objects).
* An …
=> CA: refactor ClusterSnapshot methods

cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config.go, cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config_test.go, cluster-autoscaler/cloudprovider/alicloud/examples/cluster-autoscaler-rrsa-standard.yaml
/kind feature
This PR adds support for the newly declared official environment variable names by Alibaba Cloud for [RRSA to authorize pods to access different cloud services](https://www.alibabacloud.com/help/en/container-service-for-kubernetes/latest/use-rrsa-to-enforce-access-control). This change enables compatibility with both the existing and new ENV variable names, ensuring seamless authorization for pods accessing various Alibaba Cloud services.
This update is essential for users transitioning to the updated naming conventions while maintaining support for legacy configurations.
Fixes #7435
no
```release-note
NONE
```
=> 7435 Support New Alibaba Cloud ENV Variables names for RRSA Authorization

vertical-pod-autoscaler/e2e/utils/webhook.go, vertical-pod-autoscaler/e2e/v1/actuation.go, vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go, vertical-pod-autoscaler/e2e/v1/common.go, vertical-pod-autoscaler/e2e/v1/e2e.go, vertical-pod-autoscaler/e2e/v1/full_vpa.go
/kind cleanup
Deprecates `wait.Poll` and `wait.PollImmediate` in favor of `wait.PollUntilContextTimeout`.
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> VPA: Poll/PollImmediate PollUntilContextTimeout in v1 e2e tests

vertical-pod-autoscaler/pkg/recommender/model/types_test.go
/kind cleanup
Adds unit tests for resource conversion utilities in the VPA recommender
Fixes #7434 
```release-note
NONE
```
```docs
NONE
```
=> chore(VPA): add comprehensive test coverage for types.go

balancer/Dockerfile, builder/Dockerfile, cluster-autoscaler/Dockerfile.amd64, cluster-autoscaler/Dockerfile.arm64, cluster-autoscaler/Dockerfile.s390x, vertical-pod-autoscaler/pkg/admission-controller/Dockerfile, vertical-pod-autoscaler/pkg/recommender/Dockerfile, vertical-pod-autoscaler/pkg/updater/Dockerfile
/kind cleanup
Removes the maintainer label from all our Dockerfiles, these values just get stale and can be misleading. They are [optional labels](https://docs.docker.com/reference/dockerfile/#label) added to the built images.
=> Remove maintainer labels in Dockerfiles since they just get stale

addon-resizer/OWNERS
/kind cleanup
Adds me to the list of approvers in addon-resizer.
Addon-resizer is pretty stable and seldomly touched at this point but continues to need maintenance.
I was involved in all the recent work in addon-resizer (https://github.com/kubernetes/autoscaler/commits/addon-resizer-release-1.8/addon-resizer) and was added as a reviewer in September 2024 in https://github.com/kubernetes/autoscaler/pull/7242. I have a good grasp of the codebase and would like to offer my help to ensure there is no single-point of failure for this repository as currently there is only a single active approver.
=> Add raywainman to addon-resizer owners

cluster-autoscaler/provisioningrequest/checkcapacity/provisioningclass.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go, cluster-autoscaler/provisioningrequest/provreqwrapper/testutils.go, cluster-autoscaler/provisioningrequest/provreqwrapper/wrapper.go
/kind feature
Introduces a new Parameter for checkcapacity ProvisioningRequests that limits retry mechanism in ClusterAutoscaler.
If the capacity can't be found then the ProvisioningRequest is marked as `Failed=True` instead of `Provisioned=False`
Fixes #7495 
```release-note
New Parameter for checkcapacity ProvisioningRequests that limits retry mechanism
```
```docs
```
=> Introduce noRetry Parameter for checkcapacity ProvisioningRequest

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind cleanup
Fixes #
```release-note
```
=> Add flag to enable fast delete of failed VMSS

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go, vertical-pod-autoscaler/pkg/utils/metrics/quality/quality.go
/kind bug
This PR adds keys to the structured logging statements where they were missing. I did this by searching for all occurrences of `ErrorS` and `InfoS`.
With [my incorrect suggestions](https://github.com/kubernetes/autoscaler/pull/7294#discussion_r1806104565) in PRs we introduced incorrect log statements, looking like this
```
I1127 08:48:02.749761       1 pods_eviction_restriction.go:228] "Too few replicas" kind="ReplicaSet" default/hamster-7d67d5c79f="livePods" %!s(int=1)="requiredPods" %!s(int=2)="globalMinReplicas" %!s(int=2)="(MISSING)"
```
Those PRs haven't been released yet, so no need for hotfixes or explicit release notes.
```release-note
NONE
```
=> Fix invalid log keys

vertical-pod-autoscaler/deploy/vpa-rbac.yaml, vertical-pod-autoscaler/pkg/recommender/main.go
/kind bug
Changes the default lease name for the vpa-recommender to `vpa-recommender-lease` as this can sometimes conflict with managed deployments of HPA and VPA. See #7461.
Though changing the default here is possibly disruptive during upgrade, we believe it is the right path forward to avoid future outages. See the discussion in #7461 where we also discuss the possible scenarios during upgrade where there could temporarily be two leaders.
#7461
```release-note
- Changes the default vpa-recommender leader election lease name to `vpa-recommender-lease`. This CAN result in a situation where VPA would temporarily have two leaders during an upgrade operation. This should be harmless as the two VPA leaders would theoretically be writing the same recommendations. See #7461.
```
=> Change default lease name for vpa-recommender to "vpa-recommender-lease"

vertical-pod-autoscaler/OWNERS
/kind cleanup
I would like to propose joining the list of folks who can approve PRs in the vertical-pod-autoscaler subdirectory. I meet [all requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#approver):
- Added as reviewer on August 19th (https://github.com/kubernetes/autoscaler/pull/7183).
- [25 PRs authored](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+author%3Araywainman+label%3Aarea%2Fvertical-pod-autoscaler)
- [30 PRs reviewed](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+assignee%3Araywainman+label%3Aarea%2Fvertical-pod-autoscaler)
- Familiar with codebase as I interact with it on a daily basis.
- Also active on Slack answering questions and in SIG meetings.
=> Add raywainman to vpa approvers

vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go, vertical-pod-autoscaler/pkg/utils/status/status_object.go
/kind cleanup
This PR addresses several linting issues identified in the codebase, as follows:
```
 ~/Desktop/PersonlRepos/autoscaler/vertical-pod-autoscaler/ [master] golangci-lint run          
pkg/updater/eviction/pods_eviction_restriction_test.go:645:18: Error return value of `eviction.Evict` is not checked (errcheck)
eviction.Evict(p.pod, testCase.vpa, mockRecorder)
^
pkg/updater/priority/update_priority_calculator.go:196:56: SA1019: sets.String is deprecated: use generic Set instead. new ways: s1 := Set[string]{} s2 := New[string]() (staticcheck)
func parseVpaObservedContainers(pod *apiv1.Pod) (bool, sets.String) {
^
pkg/utils/status/status_object.go:177:10: SA1019: netError.Temporary has been deprecated since Go 1.18 because it shouldn't be used: Temporary errors are not …
```
=> Chore: fixed lints errors

vertical-pod-autoscaler/pkg/recommender/main.go
/kind cleanup
Right now, it is clear where the prometheus and external-metrics flags start but it is not clear where they end.
For example, `--memory-saver` is not a prometheus history provider related flag but it appears so.
This PR uses the already existing pattern of grouping flags into dedicated var blocks (see the rest of the flags; there are other groups like aggregation configuration flags and post processor flags).
N/A
```release-note
NONE
```
```docs
```
=> vpa-recommender: Group prometheus and external-metrics flags to dedicated var blocks

vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go
/kind cleanup
Adds error checking to pod eviction tests in VPA, makes sure we detect when pod eviction fails properly.
Fixes #7544
```release-note
NONE
```
```docs
NONE
```
=> VPA: add error checking to pods eviction test

cluster-autoscaler/processors/provreq/injector.go, cluster-autoscaler/provisioningrequest/checkcapacity/provisioningclass.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go
/kind cleanup
/kind feature
We mark accepted condition the same time we mark failed/provisioned. Additionally, we issue these requests in parallel. This increases CheckCapacity throughput
```release-note
Mark ProvisioningRequest CheckCapacity conditions in parallel to increase throughput
```
=> [CheckCapacity] Update Conditions in Parallel

vertical-pod-autoscaler/pkg/updater/logic/updater.go
/kind cleanup
https://github.com/kubernetes/autoscaler/pull/7294 introduces the following issue logging issue for the vpa-updater:
```
% ks logs vpa-updater-85656ccf77-dwjgx | grep event
I1204 15:16:00.947776       1 event.go:298] "Event(%#v): type: '%v' reason: '%v' %v" {Pod default hamster-7d67d5c79f-lzz5p 0329496d-b2b4-455f-90af-06ce50f75725 v1 43391 }="Normal" EvictedByVPA="Pod was evicted by VPA Updater to apply resource recommendation."
I1204 15:16:00.947812       1 event.go:298] "Event(%#v): type: '%v' reason: '%v' %v" {VerticalPodAutoscaler default hamster-vpa c929ac55-07b8-48c9-8cdb-77a42007ca69 autoscaling.k8s.io/v1 43397 }="Normal" EvictedPod="VPA Updater evicted Pod hamster-7d67d5c79f-lzz5p to apply resource recommendation."
I1204 15:17:00.945908       1 event.go:298] …
```
=> vpa-updater: Fix logging of events

cluster-autoscaler/simulator/framework/handle.go
/kind bug
Multiple tests can call `NewHandle()` concurrently, because of `t.Parallel()`. `NewHandle` calls `schedulermetrics.InitMetrics()` which modifies global variables, so there's a race.
Wrapped the `schedulermetrics.InitMetrics()` call in a` sync.Once.Do()` so that it's only done once, in a thread-safe manner.
```release-note
NONE
```
```docs
```
/assign @jackfrancis
=> CA: Fix a data race in framework.NewHandle

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go, vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator_test.go
/kind bug
Originally reported by @adrianmoisey, this PR fixes a logging issue in the VPA updater where multi-line log entries were causing structured log output to be split and harder to read. When logging pod recommendations, newline characters were causing the output to span multiple lines:
```
"Pod accepted for update" pod="vertical-pod-autoscaling-7847/hamster-795f8c8794-7p52p" updatePriority=1.3449756180899484 processedRecommendations=
hamster: target: 587805k 247m; uncappedTarget: 587805k 247m;
>
```
The fix modifies the recommendation formatting to keep everything on a single line for better readability:
```
"Pod accepted for update" pod="vertical-pod-autoscaling-7847/hamster-795f8c8794-7p52p" updatePriority=1.3449756180899484 processedRecommendations="hamster: target: 587805k …
```
=> fix: remove newlines from VPA recommendations

cluster-autoscaler/cloudprovider/oci/nodepools/cache.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager_test.go
/kind bug
When Out Of Host Capacity error is encountered during node creation, a node instance is still part of the nodepool and visible to ClusterAutoscaler but it doesn't have a compute instance id (ocid). 
When ClusterAutoscaler tries to delete the node, it gets an api error because the delete request is made without an instance id. This PR aims to avoid making delete api calls if there is no instance id and print out the **node name** in the log to provide more visibility on the issue. 
```release-note
NONE
```
```docs
```
=> Avoid making delete api calls for nodes that don't have an instance id

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
/kind bug
Correctly set the default refresh period for VMSS size (used for Spot instances)
Fixes https://github.com/kubernetes/autoscaler/issues/7373
```release-note
```
```docs
```
=> fix: correctly set the default refresh period for VMSS size (used for Spot instances)

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
/kind bug
Cherry-pick of https://github.com/kubernetes/autoscaler/pull/7579. Automated cherry-pick has failed due to cross-version code difference from a new feature.
Fixes #
```release-note
```
```docs
```
=> [cluster-autoscaler-release-1.28] fix: correctly set the default refresh period for VMSS size (used for Spot instances)

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
/kind bug
Cherry-pick of https://github.com/kubernetes/autoscaler/pull/7579. Automated cherry-pick has failed due to cross-version code difference from a new feature.
Fixes #
```release-note
```
```docs
```
=> [cluster-autoscaler-release-1.30] fix: correctly set the default refresh period for VMSS size (used for Spot instances)

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
/kind bug
Cherry-pick of https://github.com/kubernetes/autoscaler/pull/7579. Automated cherry-pick has failed due to cross-version code difference from a new feature.
Fixes #
```release-note
```
```docs
```
=> [cluster-autoscaler-release-1.29] fix: correctly set the default refresh period for VMSS size (used for Spot instances)

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
/kind bug
Cherry-pick of https://github.com/kubernetes/autoscaler/pull/7579. Automated cherry-pick has failed due to cross-version code difference from a new feature.
Fixes #
```release-note
```
```docs
```
=> [cluster-autoscaler-release-1.27] fix: correctly set the default refresh period for VMSS size (used for Spot instances)

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/autoscaler.go, cluster-autoscaler/core/podlistprocessor/filter_out_expendable_test.go, cluster-autoscaler/core/podlistprocessor/filter_out_schedulable_test.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/eligibility/eligibility.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/scaleup/resource/manager_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/simulator/clustersnapshot/clustersnapshot.go, cluster-autoscaler/simulator/clustersnapshot/predicate/plugin_runner.go, cluster-autoscaler/simulator/clustersnapshot/predicate/plugin_runner_test.go, cluster-autoscaler/simulator/clustersnapshot/predicate/predicate_snapshot.go, cluster-autoscaler/simulator/clustersnapshot/predicate/predicate_snapshot_benchmark_test.go, cluster-autoscaler/simulator/clustersnapshot/predicate/predicate_snapshot_test.go, cluster-autoscaler/simulator/clustersnapshot/store/basic.go, cluster-autoscaler/simulator/clustersnapshot/store/delta.go, cluster-autoscaler/simulator/clustersnapshot/store/delta_benchmark_test.go, cluster-autoscaler/simulator/clustersnapshot/test_utils.go, cluster-autoscaler/simulator/clustersnapshot/testsnapshot/test_snapshot.go, cluster-autoscaler/simulator/dynamicresources/snapshot/snapshot.go, cluster-autoscaler/simulator/framework/delegating_shared_lister.go, cluster-autoscaler/simulator/framework/handle.go, cluster-autoscaler/simulator/framework/infos.go, cluster-autoscaler/simulator/framework/infos_test.go, cluster-autoscaler/simulator/framework/test_utils.go, cluster-autoscaler/simulator/node_info_utils.go
/kind cleanup
This is a part of Dynamic Resource Allocation (DRA) support in Cluster Autoscaler.
This PR implements the first bits of the DRA integration in CA:
* A DRA flag guard is added to help with preserving old behavior until we're confident in the new logic.
* The scheduler framework integration is extended to cover the new `SharedDRAManager` interface introduced in https://github.com/kubernetes/kubernetes/pull/127904.
* The `ClusterSnapshot` interface is extended to cover DRA objects.
* `SchedulerPluginRunner` is extended so that it can run the `Reserve` phase of the framework.
The CA/DRA integration is tracked in https://github.com/kubernetes/kubernetes/issues/118612, this is just part of the implementation.
This is mostly a refactor and some preparations for the actual DRA logic …
=> CA: prepare for DRA integration

vertical-pod-autoscaler/docs/examples.md
This PR modifies the expression in the examples for how the recommender computes an increased memory recommendation after an OOM event to match the behavior of the code and the following documentation. The expression is written as `used + max(minimum bump, used * bump up ratio)`, when it should be `max(used + minimum bump, used * bump up ratio)`: https://github.com/kubernetes/autoscaler/blob/c44d4f00334f2d76410c237d4675eba7c49bd3df/vertical-pod-autoscaler/pkg/recommender/model/container.go#L194-L196
I proofread the remaining examples and did not find any other obvious errors, grammar issues, broken links, etc. 
None, will file tracking issue if necessary :shrug: 
This is a trivial typo fix, should be a quick review
```release-note
NONE
```
N/A
=> Fix typo in custom memory bump-up documentation

cluster-autoscaler/simulator/scheduling/hinting_simulator.go, cluster-autoscaler/simulator/scheduling/hinting_simulator_test.go
/kind bug
If a hinted Node is no longer in the cluster snapshot (e.g. it was a fake upcoming Node and the real one appeared).
This was introduced in the recent PredicateChecker->PredicateSnapshot refactor. Previously, PredicateChecker.CheckPredicates() would return an error if the hinted Node was gone, and HintingSimulator treated this error the same as failing predicates - it would move on to the non-hinting logic. After the refactor, HintingSimulator explicitly errors out if it can't retrieve the hinted Node from the snapshot, so the behavior changed.
I checked other CheckPredicates()/SchedulePod() callsites, and this is the only one when ignoring the missing Node makes sense. For the others, the Node is added to the snapshot just before the call, so it being missing should cause an …
=> CA: don't error out in HintingSimulator if a hinted Node is gone

cluster-autoscaler/FAQ.md
=> Add note for --max-nodes-per-scaleup flag for best-effort-atomic

cluster-autoscaler/main.go, cluster-autoscaler/metrics/metrics.go
- Set initial count to zero for various autoscaler error types (e.g., CloudProviderError, ApiCallError)
- Define failed scale-up reasons and initialize metrics (e.g., CloudProviderError, APIError)
- Initialize pod eviction result counters for success and failure cases
- Initialize skipped scale events for CPU and memory resource limits in both scale-up and scale-down directions
/kind bug
This PR initializes the failedScaleUpCount and other key metrics at startup, setting their values to zero so they appear in Prometheus even if no events have occurred. By pre-defining these metrics, we ensure comprehensive monitoring and avoid gaps in visibility, particularly for scale-up and scale-down events, error types, and pod evictions.
Fixes #7448
Certain node metrics have not been initialized in …
=> 🐛(metrics) Initialize metrics for autoscaler errors, scale events, and pod evictions

cluster-autoscaler/simulator/framework/infos.go, cluster-autoscaler/simulator/framework/infos_test.go
/kind bug
If the NodeInfo is created via WrapSchedulerNodeInfo with nil podExtraInfos, subsequent AddPod() calls panic on trying to add extra info for the pod.
```release-note
NONE
```
```docs
```
=> CA: fix a nil map write in NodeInfo.AddPod()

cluster-autoscaler/cloudprovider/hetzner/hetzner_cloud_provider.go
/kind cleanup
Optionally add one or more of the following kinds if applicable:
We have received some external contributions, which we want to clean up a little.
```release-note
NONE
```
=> refactor(hetzner): refactored placement group code

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/hack/generate-crd-yaml.sh, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
/kind feature
CRDs using the `*.k8s.io` group require the `api-approved.kubernetes.io` annotation to be present on the CRD.
Previously, it was not possible to provide this annotation with kubebuilder (see https://github.com/kubernetes-sigs/controller-tools/issues/656), that's why we have a workaround logic on VPA CRD generation to add this annotation via `kustomize`: https://github.com/kubernetes/autoscaler/blob/95ec5f3f1e43ad57fc7b7847846c7c382e605e38/vertical-pod-autoscaler/hack/generate-crd-yaml.sh#L47-L56
This PR:
- Updates sigs.k8s.io/controller-tools/cmd/controller-gen from v0.9.2 to v0.16.5. I decided to update because using go1.22 with controller-gen < 0.14 panics - see https://github.com/kubernetes-sigs/controller-tools/issues/888#issuecomment-2046073715
- Adds the …
=> VPA: Add the `api-approved.kubernetes.io` annotation via kubebuilder tag

addon-resizer/cloudbuild.yaml
/kind feature
This is the first step from the [onboarding process](https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md) to integrate automatic continuous builds.
I am using addon-resizer as a first candidate for the process to become familiar with it so that I can also apply it to VPA and CA.
The next step will be to setup the prow job in the https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing directory to kick off this process automatically.
Ref #7615
```release-note
NONE
```
=> Add cloudbuild.yaml for addon-resizer

cluster-autoscaler/main.go, cluster-autoscaler/processors/provreq/injector.go, cluster-autoscaler/processors/provreq/injector_test.go
/kind feature
When `checkCapacityBatchProcessing` is enabled, provisioning requests are marked as accepted when processing them. It's not needed to duplicate the API calls in `GetPodsFromNextRequest` before processing. 
Fixes #
```release-note
```
```docs
```
=> Don't accept ProvisioningRequest twice when checkCapacityBatchProcessing enabled

cluster-autoscaler/cloudprovider/gce/autoscaling_gce_client.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go, cluster-autoscaler/core/scaledown/actuation/drain.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler.go, cluster-autoscaler/core/scaleup/orchestrator/executor.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/resource/manager.go, cluster-autoscaler/expander/factory/expander_factory.go, cluster-autoscaler/processors/nodegroupset/balancing_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/provisioningrequest/besteffortatomic/provisioning_class.go, cluster-autoscaler/provisioningrequest/checkcapacity/provisioningclass.go, cluster-autoscaler/utils/errors/errors.go
/kind cleanup
Refactor NewAutoscalerError function.
We will have two functions instead of one:
1. One that doesn't do formatting, like klog.Error
2. One that accepts formating, like klog.Errorf
The main reason behind this is to avoid go vet errors and have clear interfaces to catch accidental bugs and rely on go vet to catch those accidental bugs (or go test in go 1.24, as those are treated as errors).
```release-note
None
```
=> Refactor NewAutoscalerError function.

vertical-pod-autoscaler/hack/generate-crd-yaml.sh
/kind cleanup
While inspecting my changes in https://github.com/kubernetes/autoscaler/pull/7605, I noticed that the `cd ${WORKSPACE}` invocation in https://github.com/kubernetes/autoscaler/pull/7605/files#diff-bff56f4f4c6437e70a970d361f1b5aa99bb218b03adda6f3c5226e029a716c22R47 can be removed.
Previously, `cd ${WORKSPACE}` was required because `kubectl kustomize` was used and the generated files were referenced by relative path.
After https://github.com/kubernetes/autoscaler/pull/7605, we no longer reference using relative path.
Follow-up after https://github.com/kubernetes/autoscaler/pull/7605
N/A
```release-note
NONE
```
```docs
```
=> VPA: Clean up unused `cd` invocation in the `generate-crd-yaml.sh` script

addon-resizer/Makefile
/kind cleanup
Automatic builds are broken:
```
docker buildx inspect img-builder > /dev/null || docker buildx create --name img-builder --use
ERROR: no builder "img-builder" found
img-builder
cp -r * /tmp/tmp.LlaJKl
cd /tmp/tmp.LlaJKl && sed -i 's|BASEIMAGE|gcr.io/distroless/static:latest|g' Dockerfile
docker run --rm -it -v /tmp/tmp.LlaJKl:/tmp/tmp.LlaJKl:Z -v `pwd`:/go/src/k8s.io/autoscaler/addon-resizer/:Z \
golang:1.22 \
/bin/bash -c "\
cd /go/src/k8s.io/autoscaler/addon-resizer/ && \
CGO_ENABLED=0 GOARM=7 GOARCH=amd64 go build -a -installsuffix cgo --ldflags '-w -X k8s.io/autoscaler/addon-resizer/nanny.AddonResizerVersion=1.8.22' -o /tmp/tmp.LlaJKl/pod_nanny nanny/main/pod_nanny.go"
the input device is not a TTY
```
I confirmed that builds still work by running `make container` …
=> Minor tweaks to addon-resizer Makefile to enable automatic builds

cluster-autoscaler/core/static_autoscaler.go
/kind cleanup
Improve "Max total nodes in cluster reached" log, by adding the current number of ready nodes and the max total nodes.
```release-note
NONE
```
=> Improve "Max total nodes in cluster reached" log.

vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission.go, vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission_test.go
/kind bug
This PR treats Pods which have at least one container without a recommendation correctly when evaluating `EvictionRequirements` in the updater.
Previously, a Pod that had at least one Container without a recommendation was admitted for eviction, which is incorrect.
This occurs, when users set `.containerPolicy.mode: off` for a Container, which means VPA should ignore this Container entirely. The correct behavior for checking `EvictionRequirements` therefore is to ignore this container and evaluate against the other Containers of this Pod.
Fixes #
```release-note
Fixed a bug which lead to Pods that had a Container without recommendations to be evicted despite having an EvictionRequirement configured that was evaluated to `false`.
```
=> Ignore Containers without recommendations for EvictionRequirements

vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher_fake.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go, vertical-pod-autoscaler/pkg/utils/vpa/api_test.go
/kind cleanup
With https://github.com/kubernetes/autoscaler/pull/6460/files#diff-51c34291d2c70f6960e18f955f2a33928e8f5ac58d2d94fe0b7a8f4735f3eca3R151 we introduced as a side-effect a high amount of error logs into the vpa-updater and vpa-admission-controller. Those two components are fetching all Pods and try to find out if they are controlled via a VPA object. As part of this process, they go up the chain of `ownerRef`s.
The method `controllerFetcher#getOwnerForScaleResource` is also used during validating if a `targetRef` defined in an VPA object is valid. It correctly throws an error if a Pod `ownerRef` is of `Kind: Node`, because static Pods cannot be managed under VPA.
This PR handles the error thrown by `controllerFetcher#getOwnerForScaleResource` such that vpa-updater and …
=> Handle Error for Pods with `ownerRef: Node`

cluster-autoscaler/core/static_autoscaler.go
/kind cleanup
This adds one new log message which shows the `config.AutoscalingOptions` used to initialize a new `StaticAutoscaler` to aid in debugging. 
Fixes #
```release-note
NONE
```
```docs
```
=> add log when creating new static autoscaler

cluster-autoscaler/cloudprovider/rancher/README.md
Clarify that a cluster-autoscaler instance can target a single RKE2 cluster.
Fixes #7148
```release-note
NONE
```
```docs
```
=> docs(rancher): clarify single RKE2 target

cluster-autoscaler/core/static_autoscaler.go
/kind cleanup
Improve logging for when custom schedulers are used in the cluster.
Fixes #
```release-note
Misc logging improvements.
```
```docs
```
=> Refactor & improve logging for pod listing

cluster-autoscaler/config/autoscaling_options.go, cluster-autoscaler/core/podlistprocessor/filter_out_schedulable_test.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/podinjection/pod_injection_processor_test.go, cluster-autoscaler/simulator/clustersnapshot/predicate/predicate_snapshot_test.go, cluster-autoscaler/simulator/clustersnapshot/store/delta.go, cluster-autoscaler/simulator/clustersnapshot/store/delta_benchmark_test.go
/kind feature
Creating cluster snapshots using `SetClusterState` can take a long time, especially in large clusters with plenty of pods. Fortunately, we can parallelize the work done per each node. This PR does it by calling `workqueue.ParallelizeUntil` capped at 16 workers.
I verified the performance and it gives me near 7 times faster execution for 1k nodes, 40k pods scenario, but it depends on the machine's CPU.
In the future, basic store used for scale down can be also changed similarly.
```release-note
Adding pods when creating a cluster snapshot for scale up is now parallelized, improving performance. Parallelization can be adjusted or disabled by setting the cluster-snapshot-parallelization flag.
```
```docs
```
=> Parallelize creating cluster snapshot

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml, cluster-autoscaler/README.md
/kind feature
Bump the Chart version to 9.45.0 and the CA image to 1.32.0
Fixes #
```release-note
Bump the Chart version to 9.45.0 and the CA image to 1.32.0
```
```docs
```
=> Bump CA Chart image to v1.32

.pre-commit-config.yaml, cluster-autoscaler/FAQ.md, cluster-autoscaler/hack/update-faq-flags.sh
/kind feature
Fxies #6981
```release-note
NONE
```
```docs
```
=> Add script to update cluster-autoscaler flags doc

vertical-pod-autoscaler/pkg/utils/vpa/api.go
/kind cleanup
In this PR: [kubernetes/autoscaler#7294](https://github.com/kubernetes/autoscaler/pull/7294/files#diff-51c34291d2c70f6960e18f955f2a33928e8f5ac58d2d94fe0b7a8f4735f3eca3L92), we migrated to structured logging. This PR ensures consistent behavior for Fatalf, which now terminates the program immediately.
ref: [kubernetes/klog#416](https://github.com/kubernetes/klog/issues/416#issuecomment-2564462438).
Fixes #
Do we wish to migrate all `klog.Fatalf` to `klog.ErrorS` + `os.Exit(255)`?
```release-note
NONE
```
```docs
NONE
```
=> Align `Fatalf` Behavior with Immediate Exit

vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_source.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/target/fetcher.go, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/main.go, vertical-pod-autoscaler/pkg/utils/metrics/healthcheck.go, vertical-pod-autoscaler/pkg/utils/server/server.go
/kind cleanup
As part of migrating to structured logging this is the right replacement for `klog.Fatalf`.
Ref: https://github.com/kubernetes/klog/issues/416#issuecomment-2564462438 
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> Converting klog.Fatalf to structured logging equivalent

vertical-pod-autoscaler/e2e/v1/common.go, vertical-pod-autoscaler/e2e/v1beta2/common.go, vertical-pod-autoscaler/examples/hamster-deprecated.yaml, vertical-pod-autoscaler/examples/hamster.yaml
/kind cleanup
Docker Schema 1 images are deprecated and support is [removed in containerd 2.0](https://containerd.io/releases/#deprecated-features). These workloads need updating in order to continue working.
Verified image schemas via:
```sh
$ crane manifest registry.k8s.io/ubuntu-slim:0.1 | jq .schemaVersion
1
$ crane manifest registry.k8s.io/ubuntu-slim:0.14 | jq .schemaVersion
2
```
```release-note
NONE
```
=> Update ubuntu-slim with Docker Schema 2 image

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go
/kind bug
Fixes potential resource leaks and improves shutdown handling in VPA components by properly propagating stop channels. Previously, some components were creating their own stop channels which could lead to improper cleanup during shutdown. Adds proper cache synchronization checks.
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> fix: Propagate stop channel to prevent resource leaks in VPA components

cluster-autoscaler/cloudprovider/oci/README.md, cluster-autoscaler/cloudprovider/oci/common/oci_ref.go, cluster-autoscaler/cloudprovider/oci/common/oci_util.go, cluster-autoscaler/cloudprovider/oci/instancepools/oci_cloud_provider.go, cluster-autoscaler/cloudprovider/oci/nodepools/cache.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_cloud_provider.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager_test.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_node_pool.go
/kind bug
/kind feature
This PR includes a bunch of PRs cherry-picked to cluster-autoscaler-release-1.31 branch so that next version would include them.
These were already merged to master branch.
1. https://github.com/kubernetes/autoscaler/pull/7346
2. https://github.com/kubernetes/autoscaler/pull/7403
3. https://github.com/kubernetes/autoscaler/pull/7453
4. https://github.com/kubernetes/autoscaler/pull/7557
Fixes #
```release-note
Added OCI support for **node-group-auto-discovery** parameter. 
```
```docs
- [Usage]: **node-group-auto-discovery** parameter should have a value in the pattern;
- `clusterId:<clusterId>,compartmentId:<compartmentId>,nodepoolTags:<tagKey1>=<tagValue1>&<tagKey2>=<tagValue2>,min:<min>,max:<max>`
```
=> OCI Cloudprovider fixes and features Backport for 1.31

cluster-autoscaler/cloudprovider/oci/README.md, cluster-autoscaler/cloudprovider/oci/common/oci_ref.go, cluster-autoscaler/cloudprovider/oci/common/oci_util.go, cluster-autoscaler/cloudprovider/oci/instancepools/oci_cloud_provider.go, cluster-autoscaler/cloudprovider/oci/nodepools/cache.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_cloud_provider.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager_test.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_node_pool.go
/kind bug
/kind feature
This PR includes a bunch of PRs cherry-picked to cluster-autoscaler-release-1.30 branch so that next version would include them. 
These were already merged to master branch.
1. https://github.com/kubernetes/autoscaler/pull/6918
2. https://github.com/kubernetes/autoscaler/pull/7154
3. https://github.com/kubernetes/autoscaler/pull/7346
4. https://github.com/kubernetes/autoscaler/pull/7403
5. https://github.com/kubernetes/autoscaler/pull/7453
6. https://github.com/kubernetes/autoscaler/pull/7557
Fixes #
```release-note
Added OCI support for **node-group-auto-discovery** parameter. 
```
```docs
- [Usage]: **node-group-auto-discovery** parameter should have a value in the pattern;
- `clusterId:<clusterId>,compartmentId:<compartmentId>,nodepoolTags:<tagKey1>=<tagValue1>&< …
```
=> OCI Cloudprovider fixes and features Backport for 1.30

cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/test/common.go
/kind cleanup
Related to https://github.com/kubernetes/autoscaler/pull/6926
It was suggested that first I add a test that will ensure that by default the similar nodegroup recomputation works. And then in my other PR I can add a test to ensure that if the `SkipSimilarNodeGroupRecomputation` field is true, then we will not recompute similar nodegroups
This adds no new functionality, just a test. It is almost identical to the existing test [here](https://github.com/kubernetes/autoscaler/blob/4896bd81877ef4a171ca56cc7fc954a06b2a1dd9/cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go#L1429-L1503). My new test just changes the expander strategy so that it returns a best option with no similar nodegroups. This will test to make sure [this …
=> Add test for recomputing similar nodegroups

cluster-autoscaler/simulator/cluster.go
/kind cleanup
From [sig-instrumentation's Logging guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md): "Start from a capital letter."
Right now some log entries start with a capital letter, other don't:
```
2025-01-07 14:12:37	{"log":"Simulating node foo removal","pid":"1","severity":"INFO","source":"cluster.go:156"}
2025-01-07 14:12:37	{"log":"Node foo - cpu requested is 6.1809% of allocatable","pid":"1","severity":"INFO","source":"klogx.go:87"}
2025-01-07 14:12:37	{"log":"Node foo is underutilized: cpu requested (6.1809% of allocatable) is below the scale-down utilization threshold","pid":"1","severity":"INFO","source":"eligibility.go:167"}
2025-01-07 14:12:27	{"log":"node foo may be …
```
=> logging: Start from a capital letter

vertical-pod-autoscaler/pkg/recommender/main.go
/kind bug
While looking at the namespace flags in the context of https://github.com/kubernetes/autoscaler/issues/7697 I realized that with PR https://github.com/kubernetes/autoscaler/commit/d51bcc70079b021067297fa3220632cfdc883258#diff-bc201689c0c988297d4f93cf844937aa4f4755bfdc5bc912746148eaeed3bb64L203 we switched from the list of namespaces to include (`vpaObjectNamespace`) to the list of ignored namespaces (`ignoredVPANamespaces`).
This hasn't been released yet, so no need for a backport or release notes.
```release-note
NONE
```
=> Make informer use correct namespace flag

vertical-pod-autoscaler/hack/vpa-process-yamls.sh, vertical-pod-autoscaler/hack/vpa-up.sh
/kind bug
This PR fixes the problem people currently experience when running `hack/vpa-up.sh` from `master`, as seen in https://github.com/kubernetes/autoscaler/issues/7270 and very recently again in https://github.com/kubernetes/autoscaler/issues/4775#issuecomment-2579663219
This is necessary, because we did https://github.com/kubernetes/autoscaler/pull/7365 only on `master`, but `hack/vpa-up.sh` checks out the release branch before running `hack/vpa-process-yamls.sh`.
Fixes #4775 
Fixes #7270
```release-note
Fixed cert generation issues when installing VPA with `hack/vpa-up.sh`. No need to run `pkg/admission-controller/gencerts.sh` manually anymore.
```
=> Fix cert generation for VPA 1.2.2 when running vpa-up.sh

cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/doc.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/requests.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/results.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/testing/doc.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/testing/fixtures.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/testing/requests_test.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/openstack/compute/v2/flavors/urls.go, cluster-autoscaler/cloudprovider/magnum/gophercloud/testhelper/client/fake.go, cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go, cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider_test.go, cluster-autoscaler/cloudprovider/magnum/magnum_manager.go, cluster-autoscaler/cloudprovider/magnum/magnum_manager_impl.go, cluster-autoscaler/cloudprovider/magnum/magnum_nodegroup.go, cluster-autoscaler/cloudprovider/magnum/magnum_nodegroup_test.go, cluster-autoscaler/cloudprovider/magnum/magnum_openstack_clients.go
/kind feature
Implement TempalteNodeInfo() for the cluster-autoscaler magnum cloud provider 
Haven't found any. 
Scaling up a nodegroup from zero didn't work because TemplateNodeInfo was not implemented.
NONE
=> Implement TemplateNodeInfo for magnum cloudprovider

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_manager_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go
/kind bug
Clone of https://github.com/kubernetes/autoscaler/pull/6672 with an additional fix on printing format.
> #### Testing
> * One unit test in `azure_manager_test.go` that acts as an acceptance test.
> * One e2e test (in-progress)
> 
> #### What this PR does / why we need it:
> We currently crash CAS if there are no nodes or if VMSS (Azure `NodeGroup` implementation) is not present. Ideally, we'd like to avoid crashing in most situations and instead log.
> 
> **Main problem was in BuildAzure (call path shown below)**:
> 
> * [cloudprovider.BuildAzure](https://github.com/kubernetes/autoscaler/blob/9b41b9dc5bf431a4ad657c044e809b15cc28a7e2/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go#L206) --> `klog.Fatalf("Failed to create Azure Manager: %v", err`
> * …
=> fix: don't crash when vmss not present or has no nodes

cluster-autoscaler/cloudprovider/kwok/kwok_nodegroups.go, cluster-autoscaler/cloudprovider/kwok/kwok_nodegroups_test.go
/kind feature
In order for kwok to correctly simulate metrics usage the following annotation must be set on the nodes:
```
metrics.k8s.io/resource-metrics-path: /metrics/nodes/<node name>/metrics/resource
```
This only used if:
- kwok is configured to simulate resource usage of pods.
- the cluster is running metrics-server version >= 0.7.0,
Otherwise adding this annotation is a noop.
```release-note
cluster-autoscaler kwok cloudprovider automatically annotates nodes with metrics-server path
```
```docs
- [Other doc] https://github.com/kubernetes-sigs/metrics-server/pull/1253: metrics-server support for the path annotation.
- [Other Doc] https://kwok.sigs.k8s.io/docs/user/resource-usage-configuration: kwok documentation on overriding the path to collect resource usage.
```
=> Add metrics-server annotation for kwok-provider managed nodes

vertical-pod-autoscaler/docs/sidecar-containers.md
Document VPA behavior for sidecar containers and how to change it
Fixes #7641
```release-note
NONE
```
```docs
NONE
```
=> Document VPA behavior for sidecar containers and how to change it

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
/kind flake
Environment variables sometimes intervene with unit testing, at least in this area. This PR ensure that they are cleaned up and restore before-after each test.
Fixes #
```release-note
NONE
```
```docs
```
=> test: clean up environments properly before/after each unit test in azure_manager_test.go

cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind cleanup
Add additional assertion in the unit test for the feature of dynamic SKU.
Fixes #
```release-note
NONE
```
```docs
```
=> test: add additional assertion for dynamic SKU list test

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/templates/secret.yaml, charts/cluster-autoscaler/values.yaml
/kind feature
This PR adds support for the Civo Cloud provider to the helm chart.
N/A
```release-note
Support for civo provider added to helm chart
```
```docs
```
=> feat(chart): Add support for civo provider

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
/kind cleanup
Cherry-pick of https://github.com/kubernetes/autoscaler/pull/7735.
Automated one doesn't work due to new functions in 1.31 and beyond.
Fixes #
```release-note
NONE
```
```docs
```
=> [cluster-autoscaler-release-1.30] test: clean up environments properly before/after each unit test in azure_manager_test.go

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
/kind cleanup
Cherry-pick of https://github.com/kubernetes/autoscaler/pull/7735.
Automated one doesn't work due to new functions in 1.31 and beyond.
Fixes #
```release-note
NONE
```
```docs
```
=> [cluster-autoscaler-release-1.29] test: clean up environments properly before/after each unit test in azure_manager_test.go

cluster-autoscaler/cloudprovider/azure/azure_manager_test.go
/kind cleanup
Cherry-pick of https://github.com/kubernetes/autoscaler/pull/7735.
Automated one doesn't work due to new functions in 1.31 and beyond.
Fixes #
```release-note
NONE
```
```docs
```
=> [cluster-autoscaler-release-1.28] test: clean up environments properly before/after each unit test in azure_manager_test.go

cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_instance_cache_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go
/kind bug
Comparing to the prior behavior, it looks like https://github.com/kubernetes/autoscaler/commit/ef3b63c1cab91c184afe84fe42f1e328743624f2 have accidentally created a caveat where `provisioningStateFailed` + `enableFastDeleteOnFailedProvisioning == false` leads to `status.State` not being assigned, leading to the undefined status. This PR fixes it and add a set of unit tests for that.
The `provisioningStateFailed` case is generally rare. And _as of now_, it is likely harmless, as `InstanceRunning` gives the same result as undefined state.
A lot of further improvements could be made in this space (e.g., reunifying two near-identical methods, more test cases), but shall be revisited in a different scope.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: undefined instance state on provisioning state failed

cluster-autoscaler/main.go
/kind feature
In a single iteration of the autoscaler, only one of the activities can occur alternately: scaling up or processing ProvisioningRequests. If the activity is productive (scale up attempt was successful or ProvisioningRequest was processed), the next iteration is started immediately. Unfortunately, if there is only successful processing of ProvisioningRequests without scaling up activity (so if there are only unschedulable pods that CA scale up won't help), the autoscaler will be put to sleep unnecessarily. This PR changes the logic slightly to compare not with the start of the last iteration, but with the previous to the last, to support alternate activities well.
For example, before this PR:
successful provreq processing -> immediate next loop (because provreq was processed) …
=> Improve frequent loops when only one of activities is productive

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/main.go, cluster-autoscaler/processors/pods/scaleup_enforcer.go, cluster-autoscaler/processors/pods/scaleup_enforcer_test.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/processors/provreq/pods_filter.go, cluster-autoscaler/processors/provreq/scaleup_enforcer.go, cluster-autoscaler/processors/provreq/scaleup_enforcer_test.go, cluster-autoscaler/processors/test/common.go
/kind feature
Successful processing of ProvisioningRequests can happen when `len(readyNodes) >= a.MaxNodesTotal`. Moreover, ProvisioningRequests' pods may have been incorrectly filtered by `allPodsAreNew` (those pods exists virtually and shouldn't be taken into consideration). This PR adds a new processor: `ScaleUpEnforcer`, which, depending on unschedulablePods, decides whether the scaleUp action should be forced, bypassing two mentioned checks. 
```release-note
ProvisioningRequests can now be processed without delay if they have just been created.
```
```docs
```
=> Enforce provisioning requests processing even if all pods are new

cluster-autoscaler/main.go
Like @aleksandra-malinowska mentioned in #7668, the bug described in that issue has occurred more than once. It might be good to add a comment to indicate that the binding of the leader election flags must be called before all flags are parsed in `kube_flag.InitFlags()`.
```release-note
NONE
```
```docs
NONE
```
=> docs: add comment to prevent leader-election flag binding to be moved after flag parsing

cluster-autoscaler/main.go
/kind bug
Manual cherry-pick of #7761
Fixes #7668 on `cluster-autoscaler-release-1.32`
This also includes adding a comment to hopefully prevent bug from happening again (#7763)
```release-note
Bugfix: --leader-elect flags can be specified again. Removed --lease-resource-name flag that was redundant with --leader-elect-resource-name.
```
```docs
NONE
```
=> [cluster-autoscaler-release-1.32] fix: add --leader-elect flags back by reverting https://github.com/kubernetes/autoscaler/pull/7233

cluster-autoscaler/core/static_autoscaler.go
Clarifies what is the intention of the method, which is to simply calculate the total amount of resources for CPU/Memory from the cluster nodes.
Fixes the misleading interpretation that it is being checked resource **usage** based on metrics. 
NONE
=> Fixed verbiage of the method calculateCoresMemoryTotal

vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml, vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml, vertical-pod-autoscaler/deploy/recommender-deployment.yaml, vertical-pod-autoscaler/deploy/updater-deployment.yaml, vertical-pod-autoscaler/docs/installation.md, vertical-pod-autoscaler/hack/vpa-process-yaml.sh, vertical-pod-autoscaler/hack/vpa-up.sh
Updates docs, deployments, scripts for the VPA 1.3.0 release.
Marks VPA 1.3.0 as compatible with Kubernetes 1.28+ (verified by running "hack/run-e2e-tests.sh full-vpa" with GKE 1.28.15-gke.1342000).
/kind feature
Finalizes the VPA release 1.3.0, see
[#7731](https://github.com/kubernetes/autoscaler/issues/7731)
=> Finalize VPA release 1.3.0.

vertical-pod-autoscaler/MIGRATE.md, vertical-pod-autoscaler/examples/redis.yaml
Catching up on some extra documentation after the removal of v1beta2 in https://github.com/kubernetes/autoscaler/pull/7629.
Supplement to https://github.com/kubernetes/autoscaler/issues/5922.
```release-note
None
```
=> VPA: Small documentation changes to supplement removal of v1beta2

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/utils/vpa/api.go
/kind cleanup
`NewIndexerInformer` is deprecated, this PR replace it by using `NewInformerWithOptions` instead
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> chore: replace deprecated NewIndexerInformer

vertical-pod-autoscaler/docs/features.md, vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/pkg/recommender/logic/recommender.go, vertical-pod-autoscaler/pkg/recommender/model/types.go, vertical-pod-autoscaler/pkg/recommender/model/types_test.go
/kind feature
Adds the `--round-cpu-millicores` flag to the VPA recommender, enabling user-configurable rounding of CPU recommendations. 
Fixes #7678
```release-note
`--round-cpu-millicores` flag to the VPA recommender
```
```docs
Documentation updated to include the `--round-cpu-millicores` flag in the recommender feature set.  
```
=> feat(recommender): add round cpu millicores

vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go
/kind cleanup
Small refactor to improve the efficiency of formatting one of the logs for VPA Updater.
Follow up to https://github.com/kubernetes/autoscaler/pull/6723
```release-note
```
```docs
```
=> Refactor to format VPA Updater log more efficiently

cluster-autoscaler/FAQ.md, cluster-autoscaler/main.go
/kind bug
With the previous default of random, this could lead to start very expansives nodes that the cluster autoscaler does not manage to remove as long as another smaller node is started.
None
```release-note
The default cluster-autoscaler expander as been changed from random to least-waste to prevent misused expensive nodes.
```
```docs
```
=> change default cluster-autoscaler to least-waste

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go
/kind bug
The panic occurs when VPA is set to control only the resource Requests (rather than the default of both Requests and Limits).
No issue filed.
n/a
```release-note
NONE
```
n/a
=> Fix a panic in GetContainersResources()

cluster-autoscaler/cloudprovider/digitalocean/OWNERS
/kind cleanup
We have an outdated owners file here. This PR updates the owners file to reflect the current DO employee who owns this area of cluster autoscaler.
@gottwald is the current DO employee who needs to have approver/reviewer rights for the DO cluster autoscaler.
```release-note
NONE
```
=> Removes stale owners from DO cluster autoscaler owners file and updates to current DO employee

vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer_test.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state_test.go, vertical-pod-autoscaler/pkg/recommender/model/cluster_test.go, vertical-pod-autoscaler/pkg/recommender/model/container.go, vertical-pod-autoscaler/pkg/recommender/model/container_test.go
/kind cleanup
As a follow-up to https://github.com/kubernetes/autoscaler/pull/7819, this PR removes the request property from `ContainerUsageSample`, as it is no longer used.
```release-note
NONE
```
=> Remove Request property from ContainerUsageSample

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/processors/status/scale_up_status_processor.go
- add autoscaling status to reflect that
- change the log severity to warning as this means that autoscaler will not be fully functional (in praticular scaling up will not work)
Note: the newly introduced status will be set only if there are no prov requests (and therefore there is no forced scale up). Otherwise the forced scaleup will override it. 
/kind cleanup
Expose more descriptive scale up status and log with higher severity when cluster reaches max total nodes.
```release-note
Introduce new scale up status when cluster reaches max nodes total limit.
```
=> Improve logging when the cluster reaches max nodes total.

cluster-autoscaler/simulator/clustersnapshot/predicate/predicate_snapshot_test.go, cluster-autoscaler/simulator/dynamicresources/snapshot/snapshot_test.go, cluster-autoscaler/simulator/framework/infos_test.go
/kind bug
New unexported field is added in Scheduler -  https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/types.go#L424. Theses tests would start failing / panic due to this. Added `cmpopts.IgnoreUnexported(schedulerframework.PodInfo{})` to ignore this field in test.
Fixes #
```release-note
```
```docs
```
=> Ignore new unexported fields in the tests

vertical-pod-autoscaler/hack/vpa-process-yamls.sh, vertical-pod-autoscaler/pkg/admission-controller/delete-webhook.sh, vertical-pod-autoscaler/pkg/admission-controller/rmcerts.sh
/kind cleanup
/kind feature
While doing `./hack/vpa-down.sh` cleanup before deploy/re-deploy, there would have some error output as there's no resource to delete, by adding `--ignore-not-found` could greatly reduce those unnecessary output.
Fixes n/a
NONE
For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
```release-note
Reduce error output on "kubectl delete" by adding "--ignore-not-found"
```
=> Reduce error output on "kubectl delete" by adding "--ignore-not-found"

vertical-pod-autoscaler/pkg/updater/Dockerfile
Re raise this PR: https://github.com/kubernetes/autoscaler/pull/7834 due to flake test
=> Bumps golang from 1.23.6 to 1.24.0.

vertical-pod-autoscaler/pkg/recommender/logic/estimator_test.go
/kind cleanup
Revert ConfidenceMultiplier tests to the previous approach of adding samples and verifying that the computed confidence multiplier matches the expected value.
Fixes #7810
NONE
n/a
=> VPA: Revert ConfidenceMultiplier tests

cluster-autoscaler/core/podlistprocessor/currently_drained_nodes_test.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/drain.go, cluster-autoscaler/core/scaledown/actuation/drain_test.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler.go, cluster-autoscaler/core/scaledown/scaledown.go
/kind feature
This PR enables forceful node deletion, bypassing Pod Disruption Budgets (PDBs) when necessary for critical operations like emergency backups of node machine families.
Fixes #
Since we filter nodes for blocking pods before scaling down, and this change only applies to those filtered nodes that are explicitly allowed to be drained, the operation should be safe.
```release-note
```
```docs
```
=> Actuator force delete

cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/utils/taints/taints.go, cluster-autoscaler/utils/taints/taints_test.go
/kind bug
There's an inconsistency in `AddTaints` behavior. `AddTaints` makes a copy of the node, the taints are added to the spec of the copy, but not to the original spec. Meanwhile `HasTaints` checks if the taint is present in the spec of the node. Therefore, the changes made by AddTaints won't be present in the snapshot until the next autoscaler loop.
This PR ensures that the new taints are also added to the spec of the node in the snapshot. I also had to fix static autoscaler test, as it was configured improperly. As k8s API client was mocked, in the previous implementation marking the node as deleted was no-op in this test. Therefore, the unschedulable pod was scheduled to the removed node, which would not happen in the real scenario, as the node would refresh its taints in the …
=> Ensure added taints are present on the node in the snapshot

vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/pkg/recommender/logic/estimator.go, vertical-pod-autoscaler/pkg/recommender/logic/estimator_test.go, vertical-pod-autoscaler/pkg/recommender/logic/recommender.go
/kind feature
Add confidence intervals as configuration for histograms. When the other parameters like `{cpu,memory}-histogram-decay-half-life` are tuned or VPA operators want to influence how fast the upper and lower bounds converge, this configuration setting is useful.
Generating the flags brought in more changes as I thought. Apparently the generated flags weren't up-to-date with master.
```release-note
Introduce new recommender parameters `--confidence-interval-CPU` and `--confidence-interval-memory` to tune how fast the upper and lower bounds converge.
```
=> Add confidence intervals as configuration for histograms

addon-resizer/Dockerfile, addon-resizer/Makefile
/kind cleanup
To support automated builds, see #7615.
This moves the Go build step directly into the Dockerfile, simplifying the structure of the Makefile. This is needed to support automated builds.
Tested locally via `make container` and in a Cloud Build instance inside my GCP project using `$ gcloud builds submit --region=us-central1 --config cloudbuild.yaml`
```release-note
NONE
```
=> [Addon-Resizer] Move go build step into DOCKERFILE to support automated builds

addon-resizer/Makefile, addon-resizer/cloudbuild.yaml
/kind cleanup
Small fixes for automated builds as part of #7615:
- Make sure injected tag makes it all the way through to the Dockerfile.
- Increase timeout.
```release-note
NONE
```
=> [Addon Resizer] Small fixes for automated builds

cluster-autoscaler/cloudprovider/oci/common/oci_shape.go, cluster-autoscaler/cloudprovider/oci/common/oci_shape_test.go
/kind bug
See https://github.com/kubernetes/autoscaler/pull/6993.
```release-note
```
```docs
```
=> fix(oci): scale from zero with instance type selector (backport to 1.30)

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
/kind cleanup
Take out the `errors.Wrapf` call introduced by #7716.
The package `github.com/pkg/errors` has been archived, and it doesn't look like there is any requirement here for its unique features. Instead, wrap the error using extended error feature added in Go 1.13.
Background info at https://stackoverflow.com/a/61955455/448734
It appears that @voelzmo requested this function, so perhaps would like to comment.
```release-note
NONE
```
=> VPA: wrap clusterStateFeeder error idiomatically

vertical-pod-autoscaler/OWNERS
/kind cleanup
Cleans up 2 inactive approvers/reviewers from VPA Owners and moves to emeritus status - highlighted via the [maintainers](https://github.com/kubernetes-sigs/maintainers) tool:
```bash
maintainers prune --repository-devstats kubernetes/autoscaler --repository-github kubernetes/autoscaler
```
cc: @kgolab and @krzysied 
N/A
```release-note
```
```docs
```
=> VPA - Cleanup OWNERS

vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> VPA: when PodEvictionAdmission calls cleanup, clean up the memory

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl
The documentation can not be applied cleanly and results in errors, the code claims to expect `…/instanceGroups/` in the URL but the documentation specifies `…/instanceGroupManagers/`:
```
I1211 11:40:11.612854       1 gce_manager.go:176] GCE projectId=foobar-... location=europe-...
F1211 11:40:11.613108       1 gce_cloud_provider.go:388] Failed to create GCE Manager:
failed to fetch MIGs:
failed to parse mig URL:
https://content.googleapis.com/compute/v1/projects/foobar-.../zones/europe-.../instanceGroupManagers/kubernetes-...
got error: wrong URL:
expected format https://.*/projects/<project-id>/zones/<zone>/instanceGroups/<name>,
got https://content.googleapis.com/compute/v1/projects/foobar-.../zones/europe-.../instanceGroupManagers/kubernetes-...
```
No …
=> doc(gce): Update manual MIG specification URL

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/processors/status/eventing_scale_up_processor.go, cluster-autoscaler/processors/status/eventing_scale_up_processor_test.go
- log cluster wide event - previous event would never get fired because the estimators would already cap the options they generate and additionally it would fire once and events are kept only for some time
- log per pod event explaining why the scale up is not triggered (previously it would either get no scale up because no matching group or it would not get an event at all)
/kind bug
Improve pod events so that they log actual information why they did not trigger scale up.
```release-note
Add events for pods that are not triggering scale up because of reaching total max nodes.
```
=> Improve events when max total nodes of the cluster is reached.

cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch.go, cluster-autoscaler/core/scaledown/actuation/softtaint.go, cluster-autoscaler/utils/taints/taints.go, cluster-autoscaler/utils/taints/taints_test.go
/kind bug
Changes done in https://github.com/kubernetes/autoscaler/pull/7820 turned out to be thread unsafe, which was detected by the race detector, since `AddTaints` and `CleanTaints` are used in some goroutines. After multiple attempts to fix that (https://github.com/kubernetes/autoscaler/pull/7868, https://github.com/kubernetes/autoscaler/pull/7864) new failed tests were still emerging. Instead it was decided to make those functions not mutating the original node, but return an updated copy instead, so they can be safely executed by multiple goroutines.
```release-note
NONE
```
=> Make AddTaints and CleanTaints thread safe

vertical-pod-autoscaler/.gitignore
/kind cleanup
Adds a file to `.gitignore` which is a yaml file that's generated by  the script `deploy-for-e2e-locally.sh`. This is generated when trying to run the e2e kind tests locally and is annoying since it shows up in git: https://github.com/maxcao13/autoscaler/blob/ignore-file/vertical-pod-autoscaler/hack/deploy-for-e2e-locally.sh#L71
Another way to fix this is to either redirect the patch to a tmp file or remove the file after the script ends, but I'm not sure if people may be using that file in any way afterwards.
Fixes #
```release-note
NONE
```
=> Ignore VPA rbac file generated from local e2e installation

cluster-autoscaler/cloudprovider/azure/azure_agent_pool_test.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set_test.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool_test.go
/kind cleanup
This PR increases UT coverage for the CAS azure "azure_vms_pool" code surface area.
Fixes #
```release-note
NONE
```
```docs
```
=> azure: increase UT coverage in azure_vms_pool

cluster-autoscaler/cloudprovider/kamatera/README.md, cluster-autoscaler/cloudprovider/kamatera/kamatera_api_client.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_api_client_rest.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_api_client_rest_test.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_cloud_config.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_manager.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_manager_test.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_node_group_test.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_request.go, cluster-autoscaler/cloudprovider/kamatera/kamatera_utils_test.go
/kind bug
Fixes for Kamatera cluster autoscaler:
* added global/filter-name-prefix - optionally allowing to limit the servers considered by the autoscaler
* added retry mechanism to some of the rest api calls
* fixes for tags handling to match latest kamatera rest api responses
* shorten the server uuid suffix to prevent cases of too long server names
```release-note
Bug fixes and improvements for Kamatera cluster autoscaler to align with latest Kamatera platform changes
```
=> Kamatera cluster autoscaler fixes

hack/verify-vpa-flags.sh, vertical-pod-autoscaler/hack/verify-vpa-flags.sh
/area vertical-pod-autoscaler
/kind cleanup
Adds a CI check to enforce that VPA flag documentation remains up-to-date by failing if modifications are detected.
Fixes #7844 
```release-note
NONE
```
```docs
```
=> VPA: Enforce flag documentation check in CI

cluster-autoscaler/core/scaleup/orchestrator/async_initializer.go, cluster-autoscaler/core/scaleup/orchestrator/async_initializer_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
/kind bug
Initial scale-up failure, after async node group creation, should result in a FailedScaleUp event.
```release-note
NONE
```
```docs
```
=> Emit error event on failed async scale-up

hack/OWNERS
Add @x13n and @towca to OWNERS in autoscaler/hack.
Fixes #
```release-note
```
```docs
```
=> add more owners to autoscaler/hack

cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/simulator/node_info_utils.go, cluster-autoscaler/simulator/node_info_utils_test.go, cluster-autoscaler/utils/labels/labels.go
/kind bug
For `--force-ds=false` flag, cluster-autoscaler does not account for pending daemon-sets when creating node group templates. It sometimes leads to a cycle of node group recreations:
- User pod consuming most resources of a selected node triggers a scale-up
- System daemon-sets are started on the node
- User pod triggering the scale-up does not fit the node anymore
- Node is removed
- Back to step 1
To fix this scenario (without flipping `--force-ds` flag) two changes were implemented:
- Always account for preempting `system-node-critical` daemon-sets - those DSes will preempt other pods so it's safe to account for them in scale-up simulations. This should solve most of the problems seen in practice
- Do not pick half drained nodes as node group templates - it looks like a bug. …
=> Force system-node-critical daemon-sets in node group templates

cluster-autoscaler/main.go
/kind bug
This change would prevent cluster autoscaler from starting without having at least stale caches in informer object storages. This helps to avoid situations like following:
1. Kube API server is overloaded or unresponsive
2. New cluster autoscaler replicas were restarted (for whatever reason) and are just coming up
3. While initializing static autoscaler it's not waiting for caches to get populated which gives us no guarantees that resources were EVER fetched
4. When listing pods as part of the loop cluster autoscaler requests list of pods from informer and it outputs an empty array of pods while cluster contains an unknown amount
5. Autoscaler categorizes this as all the nodes being unused which results in scale-down with the biggest steps it can afford based on …
=> Block cluster autoscaler until API resource caches are synced.

vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md
/kind cleanup
Reduces the scope of "partial updates" from the AEP-4016 plan.
This is because, VPA accepts whole pods for updates if [at least 1 container is considered "out of recommendation bounds"](https://github.com/kubernetes/autoscaler/blob/4307e441d5d0fc70484e128cf40d9e0602426240/vertical-pod-autoscaler/pkg/updater/priority/priority_processor.go#L75), it doesn't care about which one(s). If at least one container is out of bounds, the updater will try to in-place resize the entire pod and update all containers with the most current recs. For now, we shouldn't need to introduce new logic to apply resizes only to the containers that actually have recommendations out of bounds. Instead of fitting it in this AEP, this can be introduced as a feature request or future …
=> AEP-4016: reduce scope of 'partial updates' feature

cluster-autoscaler/estimator/binpacking_estimator.go, cluster-autoscaler/loop/trigger.go
The .*f variants should only ever be called with arguments to format.
/kind bug
/kind cleanup
Cleanup the code to properly use logging functions without formatting.
Fixes #
```release-note
NONE
```
```docs
```
=> Fix incorrect usage of klog .*f functions

cluster-autoscaler/processors/actionablecluster/actionable_cluster_processor.go
The .*f variants should only ever be called with arguments to format. This should've really been a part of
https://github.com/kubernetes/autoscaler/pull/7917
/kind bug
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Fix incorrect usage of klog Warningf function

vertical-pod-autoscaler/docs/faq.md
We already have the flags [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/docs/flags.md) which generated automatically. this section is redundant.
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> Removed flags docs from faq

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
/kind bug
this change ensures that when DecreaseTargetSize is counting the nodes that it does not include any instances which are considered to be pending (i.e. not having a node ref), deleting, or are failed. this change will allow the core autoscaler to then decrease the size of the node group accordingly, instead of raising an error.
This change also add some code to the unit tests to make detection of this condition easier.
Fixes #7928 
```release-note
the log messages related to the DecreaseTargetSize function have been updated to better reflect the names of the values.
```
```docs
```
=> make DecreaseTargetSize more accurate for clusterapi

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
/kind cleanup
Following along from #7950 and #7929:
1. adding a `isProviderIDNormalized` func to aid human readability in the nodegroup accounting execution flow
2. backfilling `createPendingMachineProviderID` into the set of existing convenience functions so that we have one for every CAPI-opinionated providerID string mutation
Fixes #
```release-note
NONE
```
```docs
```
=> capi: node and provider ID accounting funcs

vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml, vertical-pod-autoscaler/docs/api.md, vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
This just addes the UpdateModeInPlaceOrRecreate mode to the types so we can use it.
We need the new API to allow users to specify the new `InPlaceOrRecreate` mode as part of [AEP-4016](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support).
This PR is part of the larger feature PR in https://github.com/kubernetes/autoscaler/pull/7673
```docs
[AEP-4016](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support)
```
=> VPA: Add UpdateModeInPlaceOrRecreate to types

vertical-pod-autoscaler/RELEASE.md, vertical-pod-autoscaler/common/version.go, vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/features/features.go, vertical-pod-autoscaler/pkg/features/versioned_features.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/updater/main.go
/kind feature
Introduces VPA feature gates. In order to enable a feature-gated feature, you must pass
`--feature-gates=YOUR_FEATURE=true` to each required component.
This PR also introduces the `InPlaceOrRecreate` feature gate on its own. 
This PR is part of the larger feature PR in https://github.com/kubernetes/autoscaler/pull/7673
Related to: https://github.com/kubernetes/autoscaler/pull/7901
```release-note
Introduces "feature gates" to the VPA.
```
=> VPA: Introduce VPA feature gates, add `InPlaceOrRecreate` feature gate

vertical-pod-autoscaler/enhancements/7862-cpu-startup-boost/README.md, vertical-pod-autoscaler/enhancements/cpu-startup-boost/README.md
/kind feature
Autoscaling Enhancement Proposal to add basic support for boosting CPU of workloads in VPA, leveraging in-place pod resizes. 
Would love your thoughts on this feature. This can be a great addition on top of [AEP-4016](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md)
#7862
=> AEP-7862: Support CPU Startup Boost in VPA

cluster-autoscaler/core/static_autoscaler.go
/kind bug
CA sets soft taint `DeletionCandidateOfClusterAutoscaler ` before proceeding to scale down by some time, if during this time the nodes with these taints are excluded from being a candidates and length of scale down candidates became 0 then scale-down enters cool down and never executes `UpdateSoftDeletionTaints` that removes these unneeded taints.
=> Fix cool down status condition to trigger scale down

vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md
`PodResizing` pod condition has recently been renamed to `PodResizeInProgress:` https://github.com/kubernetes/kubernetes/blob/62555cadc741a8aef31acab05e9ed60f897edb1b/pkg/apis/core/types.go#L2954-L2964
=> Replace PodResizing with PodResizeInProgress pod condition in AEP-4016

addon-resizer/Dockerfile
/kind cleanup
- Currently the addon-resizer build uses emulation which is very slow and leads to issues with the automatic builds (see https://github.com/kubernetes/test-infra/pull/34380).
https://github.com/kubernetes/autoscaler/issues/7615
- See notes from https://github.com/kubernetes/test-infra/pull/34380.
- Tested locally with no issues.
```release-note
NONE
```
=> [addon-resizer] Cross compile addon-resizer for efficiency

vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler_test.go
/kind feature
Only allow VPA objects with `InPlaceOrRecreate` update mode to be created if `InPlaceOrRecreate` feature gate is enabled. If a VPA object already exists with this mode on, and the feature gate is disabled, this prevents further objects to be created with `InPlaceOrRecreate` , but this does not prevent the existing `InPlaceOrRecreate`  VPA objects with from being modified.
Part of [AEP-4016](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support) (InPlaceVerticalScaling/InPlaceOrRecreate)
This PR is part of the larger feature PR in https://github.com/kubernetes/autoscaler/pull/7673
Depends on: https://github.com/kubernetes/autoscaler/pull/7934
```docs
[AEP-4016]: …
```
=> VPA: (InPlaceOrRecreate) Allow admission-controller to validate in-place spec

cluster-autoscaler/cloudprovider/azure/azure_client.go, cluster-autoscaler/go.mod, cluster-autoscaler/go.sum
/kind cleanup
Updates a dependency version: https://github.com/Azure/skewer/releases/tag/v0.0.19
Already done for 1.27-1.31 release branches. **Will follow this up with cherry-pick bot for 1.32**
* 1.27: https://github.com/kubernetes/autoscaler/pull/7278
* 1.28: skipped, because it already had the correct version ([link](https://github.com/kubernetes/autoscaler/blob/57c72c70c75ff42bb8661390ec7c2284f3298098/cluster-autoscaler/go.mod#L17))
* 1.29: https://github.com/kubernetes/autoscaler/pull/7286
* 1.30: https://github.com/kubernetes/autoscaler/pull/7288
* 1.31: https://github.com/kubernetes/autoscaler/pull/7289
```release-note
NONE
```
```docs
```
=> Update skewer version to v0.0.19 (master)

vertical-pod-autoscaler/pkg/recommender/util/histogram.go, vertical-pod-autoscaler/pkg/recommender/util/histogram_test.go
/kind bug
This PR makes it so that the min and max buckets of the histogram are updated after the histogram is loaded from a checkpoint. This is necessary in cases where the weights in the histogram are very close to (equal or a bit above) [`epsilon`](https://github.com/kubernetes/autoscaler/blob/02e3d1944990496497387e1274404242003d1ea3/vertical-pod-autoscaler/pkg/recommender/model/aggregations_config.go#L65) before being saved to a checkpoint and become less than [`epsilon`](https://github.com/kubernetes/autoscaler/blob/02e3d1944990496497387e1274404242003d1ea3/vertical-pod-autoscaler/pkg/recommender/model/aggregations_config.go#L65) after being loaded from the checkpoint due to rounding errors.
Fixes #7726 
I tried adding a full e2e test, but couldn't get it to work. This issue only …
=> Fixes histograms becoming empty after loaded from checkpoints

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
/kind bug
this change refactors the function so that it each distinct machine state can be filtered more easily. the unit tests have been supplemented, but not changed to ensure that the functionality continues to work as expected. these changes are to help better detect edge cases where machines can be transiting through pending phase and might be removed by the autoscaler.
Fixes #7976 
```release-note
NONE
```
```docs
```
=> refactor findScalableResourceProviderIDs in clusterapi

cluster-autoscaler/core/scaleup/orchestrator/async_initializer.go, cluster-autoscaler/core/scaleup/orchestrator/async_initializer_test.go
/kind bug
We need to emit an event about successful asynchronous scale-up during node pool initialization for visibility. It important to notify about the success and it's also used to match pod names to failed asynchronous scale-ups. Without this change it's possible to have a failed scale-up without a pod level `FailedScaleUp` event. 
```release-note
NONE
```
```docs
```
=> Emit event on successful async scale-up

vertical-pod-autoscaler/hack/generate-api-docs.sh
PR updates the generate-api-docs script for VPA.
/kind cleanup
Executing the generate scripts locally fails as the reference to crd-ref-docs is not provided in the script
N/A
```release-note
NONE
```
=> chore(vpa): update api-docs script

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml
/kind bug
The region should be specified explicitly. Having a default might be dangerous as cluster-autoscaler might find matching autoscaling groups in other regions that belong to a different cluster and wipe all nodes in them as it doesn't recognize these as belonging to its own cluster.
We ran into this problem when we migrated from an older custom cluster-autoscaler Helm chart (back from the times when there was no official chart) to this upstream chart. We passed in the region as Helm value `region` before and forgot to update this to `awsRegion`. This caused cluster-autoscaler in all of our non-us-east-1 clusters to target autoscaling groups in us-east-1 (as this is the default), effectively wiping all nodes in the us-east-1 cluster.
Fixes #
```release-note
```
```docs
```
=> fix: remove default value for `awsRegion` value in cluster-autoscaler Helm chart to avoid accidental misconfigurations

vertical-pod-autoscaler/OWNERS
/kind cleanup
I would like to propose joining the list of folks who can approve PRs in the vertical-pod-autoscaler subdirectory. I meet [all requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#approver):
- Added as reviewer on Jan 3th, 2025 (#7643)
- PRs authored: [PRs](https://github.com/kubernetes/autoscaler/pulls?q=is:pr+author:omerap12+label:area/vertical-pod-autoscaler+)
- PRs reviewed: [PRs](https://github.com/kubernetes/autoscaler/pulls?q=is:pr+assignee:omerap12+label:area/vertical-pod-autoscaler+)
- Issues authored: [Issues](https://github.com/kubernetes/autoscaler/issues?q=is:issue%20author:omerap12)
Familiar with codebase as I interact with it on a daily basis.
Also active on Slack answering questions and in SIG meetings.
/assign …
=> Add omerap12 to VPA approvers

vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md
Introduce two new flags, `--in-place-deferred-resize-timeout` and `--in-place-resize-timeout`, to replace the hardcoded 5-minute and 1-hour timeouts used in in-place pod resizing operations.
The hardcoded values were picked arbitrarily, but VPA users should have the option to configure them. 
For example, in place resizes can[ have a ](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources#container-resize-policy)Deferred[ condition](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources#container-resize-policy) when "the proposed resize is feasible in theory (it fits on this node) but is not possible right now; it will be regularly reevaluated."
VPA users should have the …
=> Parametrize pod resize timeouts in AEP-4016 beta

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl, charts/cluster-autoscaler/templates/deployment.yaml, charts/cluster-autoscaler/templates/serviceaccount.yaml
/kind feature
This PR allows DRY common configuration metadata that pops up in many places like `serviceAccount.annotations` or autoscaling group tags, prefixes, etc. Imagine centralized configuration keys like aws account ids, regions, gcp project ids, cluster names, etc, etc. Without this PR you have to set the same value override files over and over again which when multiple (> 10) clusters and multiple clouds are used becomes a maintaince pain having to repeat the same config allover the place.
I implemented the same feature for ExternalDNS: https://github.com/kubernetes-sigs/external-dns/pull/4958 and Cert-Manager: 
https://github.com/cert-manager/cert-manager/pull/7501
Feature impairment: currently autodiscovery tags are rendered using `tpl` function and I believe the autoscaling …
=> allow `tpl` on common metadata to DRY

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go, vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client_test.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
/kind cleanup
Refactors the recommender controller to explicitly pass `context.Context` instead of using `context.TODO()`. This follows Go best practices, improves context propagation, and future-proofs for timeouts/cancellations.
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> Refactor recommender to use context

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
/kind cleanup
Fixes:
```bash
pkg/recommender/input/cluster_feeder.go:1: : # k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input [k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input.test]
pkg/recommender/input/cluster_feeder_test.go:639:19: cannot use fakeMetricsClient{…} (value of struct type fakeMetricsClient) as "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/metrics".MetricsClient value in struct literal: fakeMetricsClient does not implement "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/metrics".MetricsClient (wrong type for method GetContainersMetrics)
have GetContainersMetrics() ([]*"k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/metrics".ContainerMetricsSnapshot, error)
want …
```
=> fix lint: update tests with context

cluster-autoscaler/cloudprovider/oci/common/oci_shape.go, cluster-autoscaler/cloudprovider/oci/common/oci_shape_test.go, cluster-autoscaler/cloudprovider/oci/nodepools/cache.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager_test.go
/kind bug
This PR fixes 2 bugs with the Oracle Cloud integration:
* When fetching information about node shapes to determine if a node pool with 0 nodes can be scaled up, it only fetches the first 100 results. The code specifies `Limit: 500`, but the max value of the limit on the backend is 100. This prevents nodes not on the first page of results from scaling up from 0.
* It's possible when attempting to scale up that the request fails due to a lack of capacity in the region. In this case OCI will show a node in the pool, but won't assign an ID to the node. This means that any attempts to scale down the node fail. To fix this, we just don't tell the autoscaler about nodes that have no ID.
```release-note
NONE
```
```docs
```
=> Fix 2 bugs in the OCI integration

cluster-autoscaler/core/static_autoscaler_test.go
/kind cleanup
Following up on [pull/7954](https://github.com/kubernetes/autoscaler/pull/7954), Adding this unit test to test that we remove the deletion soft taints while in scale down cool down.
=> Add unit test for cleaning deletion soft taint in scale down cool down

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates_test.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go, vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go, vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go, vertical-pod-autoscaler/pkg/updater/priority/priority_processor.go, vertical-pod-autoscaler/pkg/updater/priority/priority_processor_test.go, vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission.go, vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission_test.go, vertical-pod-autoscaler/pkg/utils/resources/resourcehelpers.go, vertical-pod-autoscaler/pkg/utils/resources/resourcehelpers_test.go, vertical-pod-autoscaler/pkg/utils/test/test_containerstatus.go, vertical-pod-autoscaler/pkg/utils/test/test_pod.go
/kind feature
This PR adds a new helper package to read container resources in VPA and updates most usages to avoid reading the resources directly from `Pod.Spec.Containers[i].Resources`. 
This is needed because with [In-Place Update of Pod Resources feature](https://github.com/kubernetes/enhancements/issues/1287) (see [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources) for details), `Pod.Spec.Containers[i].Resources` may not contain the actual resources held by the pod and its containers (see https://github.com/kubernetes/autoscaler/issues/7971 for details).
There are still some places that need to be updated to use the new utility function. They also need to consider init containers. I'll fix them in a follow up PR.
Yes …
=> Also consider containerStatus.resources when handling container resources

cluster-autoscaler/simulator/drainability/rules/replicacount/rule.go, cluster-autoscaler/simulator/drainability/rules/replicacount/rule_test.go
/kind bug
Related to 
https://github.com/kubernetes/autoscaler/issues/5977
https://github.com/kubernetes/autoscaler/pull/6412
https://github.com/kubernetes/autoscaler/pull/8006
Our fleet running on AKS uses lots of [OpenKruise's Advanced StatefulSet](https://openkruise.io/docs/user-manuals/advancedstatefulset). The check here was blocking thousands of nodes being scaled down, with the following error message:
```
statefulset for my-namespace/my-app-0 is not available: err: statefulset.apps "my-app" not found
```
This PR added an additional check to unblock third party statefulset being drained
Fixes #
```release-note
Fixed a bug that prevents third party statefulset from being drained by cluster auto scaler
```
```docs
```
=> Allow draining when StatefulSet kind has custom API Group

vertical-pod-autoscaler/e2e/v1/recommender.go
/kind bug
Running `recommender`'s `doesn't drop lower/upper after recommender's restart` e2e tests against an existing cluster, that has `VPA` resources created in advance, causes a failure as it's internal observer `controller` considers all namespaces when watching for resource events.
https://github.com/kubernetes/autoscaler/blob/25ad4c2c26f10451a1a6d2047884e9a31913c5da/vertical-pod-autoscaler/e2e/v1/recommender.go#L106-L112
As the primary goal of the test is to validate the `hamster` deployment that it creates, validating recommendations for resources outside of its scope introduces nondeterministic behaviour with failing `Expect` assertions.
With the change introduced in this PR, we are limiting the internal observer `controller` scope to `VPA` resources within the `namespace` …
=> e2e(recommender): Restrict the internal `VPA` controller scope to test namespace

cluster-autoscaler/core/scaledown/status/status.go, cluster-autoscaler/core/static_autoscaler.go
/kind bug
Update scale `scaleDownInCooldown` definition to skip considering zero candidates as a reason to be in `scaleDownInCooldown` state
Emit scale down metric even when there is no scale down candidates.
Fixes #
```release-note
Update scale `scaleDownInCooldown` definition to skip considering zero candidates as a reason to be in `scaleDownInCooldown` state
```
```docs
```
=> Emit scale down metric even when there is no scale down candidates.

cluster-autoscaler/core/static_autoscaler_test.go
When both #7997 and #7995 were merged - this led to isScaleDownInCooldown interface incompatibility which causes tests to fail. This PR patches the test to no longer depend on isScaleDownInCooldown as tainting logic was transferred straight to `RunOnce` method
Fixes #
```release-note
NONE
```
```docs
```
=> Patch TestCleaningSoftTaintsInScaleDown to be compatible with new isScaleDownInCooldown signature

vertical-pod-autoscaler/cloudbuild.yaml, vertical-pod-autoscaler/pkg/admission-controller/Makefile, vertical-pod-autoscaler/pkg/recommender/Makefile, vertical-pod-autoscaler/pkg/updater/Makefile
/kind cleanup
This is the first step in automating builds for VPA. This configures the Cloud Build flow for building all 3 VPA binaries and uploading them to the staging repository.
Step 1 in #7902
Tested locally (and passed) using the following command in my GCP project from the `vertical-pod-autoscaler` directory. I also modified the registry location in my Makefiles locally to write to my own repository for testing.
```
$ gcloud builds submit --region=us-central1 --config=cloudbuild.yaml
```
```release-note
NONE
```
=> Create cloudbuild.yaml for VPA binaries to automate builds

cluster-autoscaler/cloudprovider/equinixmetal/price_model.go, cluster-autoscaler/cloudprovider/gce/gce_price_model.go, cluster-autoscaler/estimator/decreasing_pod_orderer.go, cluster-autoscaler/expander/waste/waste.go, cluster-autoscaler/simulator/utilization/info.go, cluster-autoscaler/utils/gpu/gpu.go, cluster-autoscaler/utils/labels/labels.go, cluster-autoscaler/utils/pod/pod.go
Replaces all (hopefully) Pod resource calculations with `k8s.io/component-helpers/resource.PodRequests`. This helper is the source of truth how to calculate resource requests. It's used by the scheduler among others and captures developments like e.g. [KEP-1287: In-place Update of Pod Resources](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources) (beta in 1.33) and [KEP-2837: Pod Level Resource Specifications](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2837-pod-level-resource-spec/README.md) (beta in 1.34).
**Important note**: as a side-effect it means Cluster Autoscaler will start considering init containers as well for it's resource calculations. Init containers with restart policy of …
=> Use k8s.io/component-helpers/resource for pod request calculations

vertical-pod-autoscaler/pkg/utils/vpa/capping.go, vertical-pod-autoscaler/pkg/utils/vpa/capping_test.go
/kind feature
Read container resources from `containerStatus` in the capping processor in VPA, if available. If not, VPA will fallback to the container resources defined in `Pod.Spec.Containers[i].Resources`. 
This is needed because with [In-Place Update of Pod Resources feature](https://github.com/kubernetes/enhancements/issues/1287) (see [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources) for details), `Pod.Spec.Containers[i].Resources` may not contain the actual resources held by the pod and its containers (see https://github.com/kubernetes/autoscaler/issues/7971 for details).
Yes 
```release-note
Also consider containerStatus.resources when handling container resources in VPA's Capping processor:  first try to read the …
```
=> Read container resources from containerStatus in the capping processor

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go
/kind bug
This PR fixes a nil pointer exception that was introduced with https://github.com/kubernetes/autoscaler/pull/7891 that can happen if `memory-saver=true`. 
The reason this happens is that `feeder.metricsClient.GetContainersMetrics` loads metrics for all pods in the cluster whereas when `memory-saver=true` only pods for which there are VPAs are added to the `feeder.clusterState.Pods()` map
I also added a test that breaks without this change.
Fixes #
I have left `NONE` in the release not as I think there isn't a release yet that contains the nil pointer exception.
```release-note
NONE
```
```docs
```
=> VPA: Fix nil ptr when loading metrics and `memory-saver=true`

cluster-autoscaler/Makefile, cluster-autoscaler/cloudbuild.yaml
/kind cleanup
Modifies the cloudbuild.yaml file, containing the instructions to build cluster-autoscaler from Cloud Build in automated builds.
The old content here was a previous attempt at doing this but was abandoned, as far as I can tell it is all dead code.
Tested locally by running:
```
$ gcloud builds submit --region=us-central1 --config=cloudbuild.yaml
```
Part of #8032.
```release-note
NONE
```
=> cloudbuild.yaml file for cluster-autoscaler for automated builds

vertical-pod-autoscaler/pkg/recommender/input/spec/spec_client.go, vertical-pod-autoscaler/pkg/recommender/input/spec/spec_client_test.go, vertical-pod-autoscaler/pkg/recommender/input/spec/spec_client_test_util.go, vertical-pod-autoscaler/pkg/utils/resources/resourcehelpers.go, vertical-pod-autoscaler/pkg/utils/resources/resourcehelpers_test.go, vertical-pod-autoscaler/pkg/utils/test/test_pod.go
/kind feature
Read container resources from `containerStatus` and `initContainerStatus` in the spec client in VPA, if available. If not, VPA will fallback to the container resources defined in `Pod.Spec.Containers[i].Resources` or the equivalent for `initContainers`.  
This is needed because with [In-Place Update of Pod Resources feature](https://github.com/kubernetes/enhancements/issues/1287) (see [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources) for details), `Pod.Spec.Containers[i].Resources` may not contain the actual resources held by the pod and its containers (see https://github.com/kubernetes/autoscaler/issues/7971 for details).
Yes 
```release-note
Also consider (init)containerStatus.resources when handling container …
```
=> Read container resources from containerStatus in the spec client

vertical-pod-autoscaler/common/version.go
/kind feature
For VPA release #8073.
```release-note
NONE
```
=> Bump VPA version in 1.3 branch

vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/utils/metrics/resources/resources.go, vertical-pod-autoscaler/pkg/utils/resources/resourcehelpers.go
/kind feature
VPA may read container resources from either `containerStatus` (if available) or `Pod.Spec.Containers[i].Resources` (fallback). 
In clusters with  [In-Place Update of Pod Resources feature](https://github.com/kubernetes/enhancements/issues/1287) (see [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources), it's expected that `containerStatus` hold the actual value of resources, while `Pod.Spec.Containers[i].Resources` is purely a declaration of the desired state of pod resources. 
We're adding a metric that tracks the data source ((init)containerStatus or pod.Spec.(init)Containers.Resources) that was read by VPA.  This can be useful to track how many times we are falling back to reading resources from the pod spec in …
=> Add metric to track calls to get container/pod resources

cluster-autoscaler/cloudprovider/hetzner/README.md, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
/kind feature
Picking up from [this issue](https://github.com/kubernetes/autoscaler/issues/7652) it allows to set the the Hetzer Cloud Cluster Config via a file instead of an environment variable. 
As mentioned in the issue the cluster config can become too long for an env var (happened to me today). 
Fixes #7652
```release-note
- allow setting Hetzner Cloud Cluster Config by providing a json config file, set via `HCLOUD_CLUSTER_CONFIG_FILE`
```
=> added possibility to retrieve hcloud cluster config from file

vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling.go, vertical-pod-autoscaler/pkg/utils/vpa/limit_and_request_scaling_test.go
/kind cleanup
Improves visibility when limit is not set by vertical pod autoscaler returning the reason why the limit is not set.
Fixes #7884
=> chore: improve logging for missing limit assignments

cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go, cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go
Fixes #8045
The AWSCloudProvider only supports aws://zone/name ProviderIDs. It should ignore ProviderIDs it does not recognize. Prior to this fix, an unrecognized ProviderID, such as eks-hybrid://zone/cluster/my-node which is used by EKS Hybrid Nodes, will break the Autoscaler loop.
This fix returns logs a warning, and returns nil, nil instead of returning the error.
/kind bug
The launch of Amazon EKS Hybrid Nodes introduced a new ProviderID of `eks-hybrid://zone/cluster/name`. This new ProviderID causes the AWSCloudProvider to break out of it's reconciliation loop because it returns an error when encountering this new ID.
The AWSCloudProvider only supports aws://zone/name ProviderIDs, it should ignore any alternatives (just like it does for a blank iD). This prevents another fix if AWS …
=> fix: AWSCloudProvider should ignore unrecognized provider IDs

addon-resizer/Dockerfile, addon-resizer/Makefile, addon-resizer/go.mod
/kind bug
The addon-resizer automated build is broken (https://testgrid.k8s.io/sig-autoscaling-addon-resizer#post-autoscaler-push-addon-resizer-images) with the following error:
```
#11 0.151 go: k8s.io/api in vendor/modules.txt requires go >= 1.24.0 (running go 1.23.8; GOTOOLCHAIN=local)
```
```release-note
NONE
```
=> Update golang version to 1.24 for addon-resizer to fix build

vertical-pod-autoscaler/deploy/vpa-rbac.yaml
/kind bug
After updating to VPA 1.3.0, our vpa-updater logs are full with:
```
E0505 11:18:10.361238       1 event.go:359] "Server rejected event (will not retry!)" err="events \"bar.183c9d4d7cff8f87\" is forbidden: User \"system:serviceaccount:kube-system:vpa-updater\" cannot patch resource \"events\" in API group \"\" in the namespace \"foo\"" event="&Event{ObjectMeta:{bar.183c9d4d7cff8f87  foo   242426133 0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},InvolvedObject:ObjectReference{Kind:VerticalPodAutoscaler,Namespace:foo,Name:bar,UID:8dd98ac4-0aa7-463b-8a13-547ae29c0d5c,APIVersion:autoscaling.k8s.io/v1,ResourceVersion:9896005394,FieldPath:,},Reason:EvictedPod,Message:VPA Updater evicted Pod bar-0 to apply resource …
```
=> vpa-updater: Allow patch and update for events

cluster-autoscaler/simulator/clustersnapshot/predicate/plugin_runner.go, cluster-autoscaler/simulator/clustersnapshot/predicate/plugin_runner_test.go, cluster-autoscaler/utils/test/test_utils.go
/kind bug
When a pod has node affinity set for a non-existing node, `RunFiltersOnNode` causes nil dereference panic, as it tries to dereference `preFilterStatus`, which will be nil in that situation. With this change, `preFilterStatus` will not be dereferenced in the affected branch, and instead, we will pass to the error message the names of plugins that filtered out some nodes.
b/415163100
```release-note
NONE
```
=> Prevent nil dereference of preFilterStatus

cluster-autoscaler/context/autoscaling_context.go, cluster-autoscaler/core/scaledown/actuation/actuator.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
/kind cleanup
There's no need to pass `draProvider` as a separate variable outside the autoscaling context.
Fixes #
```release-note
```
```docs
```
=> Move DRA provider to autoscaling context.

vertical-pod-autoscaler/RELEASE.md
Update the release instructions to make use of the automatically built images as part of #7902.
```release-note
NONE
```
=> VPA - Update release instructions for automatically built images

cluster-autoscaler/expander/priority/readme.md
Corrects 2 things:
- priority expander ConfigMap is no longer required for the autoscaler to startup, since the behavior was changed to fallback to the next expander option in https://github.com/kubernetes/autoscaler/pull/5246
- the statement that the expander ConfigMap must be in the same namespace as the autoscaler pod isn't, strictly speaking, correct: if the autoscaler runs outside the workload cluster and uses the `--kubeconfig` flag to point to the workload cluster, then the autoscaler pod and the expander configmap may even live in different clusters (and different namespaces)
Fixes #
```release-note
NONE
```
```docs
```
=> correct documentation on cluster-autoscaler priority expander configmap

cluster-autoscaler/cloudprovider/gce/cache.go, cluster-autoscaler/cloudprovider/gce/gce_manager.go
/kind bug
This PR prevents instance templates and instance template names cache from leaking. Currently those caches aren't cleaned at all which causes issues for clusters with MIGs churn. This change is are adding cleaning for those caches to `RegenerateMigInstancesCache` which is called each hour worst case and cleans up caches only for the MIGs which are untracked.
```release-note
Fixed memory leak for GCE instance templates fetching
```
```docs
```
=> Fix memory leak while fetching GCE instance templates.

vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go
/kind cleanup
I was looking over a recently merged https://github.com/kubernetes/autoscaler/pull/8115 and found a few typos in the metric names.
Fixes #
```release-note
NONE
```
```docs
[AEP] https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support
Depends on: 
[KEP] https://github.com/kubernetes/enhancements/tree/25e53c93e4730146e4ae2f22d0599124d52d02e7/keps/sig-node/1287-in-place-update-pod-resources
```
=> Fix typos in the metric name for VPA In-Place update

cluster-autoscaler/simulator/dynamicresources/snapshot/snapshot.go, cluster-autoscaler/simulator/dynamicresources/utils/resource_claims.go, cluster-autoscaler/simulator/dynamicresources/utils/resource_claims_test.go
/kind cleanup
migrate claimReservedForPod to use upstream upstream IsReservedForPod 
part of #7788
```release-note
NONE
```
```docs
NONE
```
=> migrate claimReservedForPod to use upstream IsReservedForPod

cluster-autoscaler/cloudprovider/clusterapi/README.md
this change is adding an extra note to the readme to help users understand how the autoscaler works when it is outside the minimum and mamximum limits. it is being added to help inform users and also because the readme is embedded in clusterapi documentation.
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8217
(not specifically an autoscaler issue, but this was raised from the cluster-api community)
```release-note
NONE
```
```docs
```
=> update clusterapi readme with node group limit info

vertical-pod-autoscaler/docs/features.md, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go
/kind cleanup
Add metrics for failed in-place update attempt
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> Add metric for failed in-place update attempt

vertical-pod-autoscaler/common/flags.go, vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer.go, vertical-pod-autoscaler/pkg/recommender/checkpoint/checkpoint_writer_test.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/recommender/routines/recommender.go
/kind feature
Introduce a worker pool for updates to VPA status and VPACheckpoints, such that vpa-recommender can deal with large-scale systems. In the current implementation updates are executed sequentially, which means that at some point the latency from vpa-recommender to kubernetes-apiserver will become the limiting factor for updates per second.
This PR introduces a new parameter, `--update-worker-count`, defaulting to `10`, which determines the size of the worker pool. This can be used to control the load on the kubernetes-apiserver.
Closes #7951
Inspired by https://github.com/kubernetes/autoscaler/compare/master...tkukushkin:autoscaler:parallel-updates
Thanks @tkukushkin!
```release-note
BREAKING: deprecated recommender flag `min-checkpoints`, progress is now ensured by the new …
```
=> Make VPA and Checkpoint updates concurrent

vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/hack/generate-flags.sh
This PR enhances the `generate-flags.sh` script to handle flags with multi-line descriptions, specifically to address the case of `--feature-gates`.
Previously, such flags were either incorrectly parsed or excluded from the generated `flags.md` documentation due to their multi-line nature. This led to incomplete CLI documentation, which can cause confusion for users, especially when dealing with important features like in-place updates that are behind feature gates.
With this update the script now properly captures and formats multi-line flag descriptions.
This ensures that all flags—including complex ones like --feature-gates—are accurately represented in the VPA component documentation.
Fixes #8139 
```release-note
```
```docs
```
=> updating the script to handle multi-line flag descriptions

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/clusterstate/clusterstate_test.go, cluster-autoscaler/clusterstate/utils/node_instances_cache_test.go, cluster-autoscaler/core/scaledown/actuation/actuator_test.go, cluster-autoscaler/core/scaledown/actuation/delete_in_batch_test.go, cluster-autoscaler/core/scaledown/actuation/drain_test.go, cluster-autoscaler/core/scaledown/actuation/group_deletion_scheduler_test.go, cluster-autoscaler/core/scaledown/actuation/softtaint_test.go, cluster-autoscaler/core/scaledown/budgets/budgets_test.go, cluster-autoscaler/core/scaledown/eligibility/eligibility_test.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/scaledown/unneeded/nodes_test.go, cluster-autoscaler/core/scaleup/orchestrator/async_initializer_test.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go, cluster-autoscaler/core/scaleup/resource/manager_test.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/estimator/sng_capacity_threshold_test.go, cluster-autoscaler/expander/price/price_test.go, cluster-autoscaler/processors/customresources/gpu_processor_test.go, cluster-autoscaler/processors/nodegroupset/azure_nodegroups_test.go, cluster-autoscaler/processors/nodegroupset/balancing_processor_test.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go, cluster-autoscaler/processors/nodes/pre_filtering_processor_test.go, cluster-autoscaler/processors/nodes/scale_down_set_processor_test.go, cluster-autoscaler/processors/scaledowncandidates/scale_down_candidates_delay_processor_test.go, cluster-autoscaler/provisioningrequest/orchestrator/orchestrator_test.go, cluster-autoscaler/utils/backoff/exponential_backoff_test.go
/kind cleanup
The TestCloudProvider is used widely in our codebase, but it is passing all its config via arguments on constuction. I've rewritten it to use builder pattern, to make it both easier to use and to read.
=> Rewrite TestCloudProvider to use builder pattern

vertical-pod-autoscaler/go.mod
/kind bug
This PR sets correct version of k8s.io/client-go in the go.mod file. The dependecies shall follow the versioning recommendation described in the package documentation: [https://pkg.go.dev/k8s.io/client-go](https://pkg.go.dev/k8s.io/client-go)
The correct version is `v0.33.0` and not `v1.5.2`
Version `v1.5.2` breaks other go modules referencing `vertical-pod-autoscaler` as it is not compatible with the `k8s.io/client-go` version used in the main Kubernetes repository.
```release-note
Set k8s.io/client-go version to v0.33.0.
```
=> Set correct k8s/client-go version in go.mod

vertical-pod-autoscaler/e2e/go.mod
/kind bug
Similar to https://github.com/kubernetes/autoscaler/pull/8165 but for the e2e module of VPA.
N/A
```release-note
NONE
```
```docs
```
=> e2e: Use correct version of k8s.io/client-go

vertical-pod-autoscaler/deploy/kustomization.yaml
/kind bug
Adds the Admission Controller service to the Kustomization file. The VPA webhook is broken today, see #8173
Fixes #8173
```release-note
Includes the Admission Controller service to the Kustomization file.
```
=> Add admission controller service to kustomization

vertical-pod-autoscaler/common/version.go
/kind feature
Bump VPA version to 1.4.1 in preparation for release (https://github.com/kubernetes/autoscaler/issues/8189)
```release-note
NONE
```
=> Bump VPA version to 1.4.1

cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go
**What type of PR is this?** (bug, cleanup, documentation, feature) bug
**What this PR does / why we need it?**:
Add the missing labels and taints to the VM pool. Previously, we relied solely on the NodeLabel and NodeTaints properties from the versioned AP to build the node template for scale-from-zero scenarios. However, some critical system labels and taints are added by AgentBaker and stored in the unversioned AP data model. These are essential for proper scale-up behavior. The values will now be passed to CAS via the ConfigMap under the nodeGroup spec..
**Does this PR introduce a user-facing change?**
No
**WorkItem**
**Testing**
<details>
<summary>Cherry-pick details</summary>
**Is this a cherry-picked PR?**
```
```
```
```
**Is this PR getting merged on …
=> [AKS VMs Pool] Add the missing labels/taints for VMs pool 1.31

cluster-autoscaler/cloudprovider/azure/azure_agent_pool_test.go
This PR addresses failing UT which landed in https://github.com/kubernetes/autoscaler/pull/8078
Fixes #
```release-note
NONE
```
```docs
```
=> azure: fix azure_agent_pool UT

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go
include pod namespace when logging updates. Useful to differentiate between Pods with the same name in different namespaces.
Fixes #
```release-note
include pod namespace when logging updates.
```
```docs
```
=> include pod namespace when logging updates

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_dra_test.go, cluster-autoscaler/processors/customresources/custom_resources_processor.go, cluster-autoscaler/processors/customresources/default_custom_processor.go, cluster-autoscaler/processors/customresources/default_custom_processor_test.go, cluster-autoscaler/processors/customresources/dra_processor.go, cluster-autoscaler/processors/customresources/dra_processor_test.go, cluster-autoscaler/processors/customresources/gpu_processor.go, cluster-autoscaler/processors/customresources/gpu_processor_test.go, cluster-autoscaler/processors/processors.go, cluster-autoscaler/processors/test/common.go
/kind feature
Adds a custom resource processor that marks node with unready DRA reasources as unready node so that CA doesn't create another unnecessary scale-ups for the pods that wouldn't get scheduled on nodes with unready resources.
Fixes #7780
```release-note
NONE
```
```docs
```
=> Handle node readiness for DRA after a scale-up

cluster-autoscaler/cloudprovider/clusterapi/README.md
/kind cleanup
Fixes #
```release-note
```
```docs
```
=> Remove redundant warning in the autoscaler Cluster API documentation

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go
/kind bug
Node group to be created may have different id than the created node group. Newly created node group was not propagated to scale up status `ConsideredNodeGroups` field causing warnings.
```release-note
NONE
```
```docs
```
=> Add created node group to considered node groups during scale-up

cluster-autoscaler/cloudprovider/clusterapi/examples/deployment.yaml
Add "volumeattachments".  See similar changes in https://github.com/kubernetes/autoscaler/commit/e79b5b86356ef5ec2fc5099824e876530f0e2d73
Add `volumeattachments` permission to clusterapi example.yaml
=> Update deployment.yaml to add volumeattachments permission

vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go
/kind bug
The in-place metric constructors in the vpa-updater used an incorrect `GaugeVec` during initialization, which caused the metrics not to be exported.
If you check them using the `curl` command, you will notice that the metrics are missing:
```sh
$ curl -s http://127.0.0.1:8943/metrics | grep in_place
$ echo $?
1
$ curl -s http://127.0.0.1:8943/metrics | grep in_place | wc -l
0
```
After the patch, this command will return the result:
```sh
$ curl -s http://127.0.0.1:8943/metrics  | grep in_place
vpa_updater_in_place_Updatable_pods_total{vpa_size_log2="0"} 0
vpa_updater_in_place_Updatable_pods_total{vpa_size_log2="1"} 0
vpa_updater_in_place_Updatable_pods_total{vpa_size_log2="10"} 0
vpa_updater_in_place_Updatable_pods_total{vpa_size_log2="11"} 0 …
```
=> Fix(VPA): updater in-place metrics initialization

vertical-pod-autoscaler/pkg/admission-controller/certs.go, vertical-pod-autoscaler/pkg/admission-controller/main.go
/kind bug
This disable the update of CA in the *MutatingWebhookConfiguration* by the admission controller when the `registerWebhook` option is not enabled and the CA file changed.
Fixes #8248
```release-note
Vertical Pod Autoscaler Admission Controller will not try to update the `vpa-webhook-config` MutatingWebhookConfiguration when `registerWebhook` is disabled.
```
```docs
```
=> fix(VPA): Do not update webhook CA when registerWebhook is disabled

vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/recommender/main.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go, vertical-pod-autoscaler/pkg/target/fetcher.go, vertical-pod-autoscaler/pkg/updater/main.go, vertical-pod-autoscaler/pkg/utils/limitrange/limit_range_calculator.go, vertical-pod-autoscaler/pkg/utils/limitrange/limit_range_calculator_test.go
/kind bug
VPA controllers initialize a few informers, but the informers in `targetSelectorFetcher` and `controllerFetcher` are duplicated. If we start them one by one, it leads to a warning message because the caches are already synchronized.  
We can use the factory (it was made for this purpose) that was used to create these informers to start them and wait for all caches to sync.
Then caches will be populated without any warning messages.
```
I0621 01:27:41.171294   84656 reflector.go:430] "Caches populated" type="*v1.CronJob" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.171294   84656 reflector.go:430] "Caches populated" type="*v1.Job" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.171385   84656 …
```
=> [VPA] Use factory start to fill caches instead of separate informers

cluster-autoscaler/cloudprovider/oci/nodepools/cache.go
/kind bug
This change addresses an issue in the OCI (OKE) provider where a `HTTP 404 Error Code: NotAuthorizedOrNotFound` response from the [OCI Delete Node API call](https://docs.oracle.com/en-us/iaas/api/#/en/containerengine/20180222/NodePool/DeleteNode) is misinterpreted and reported as a _successful_ node deletion..
As the OCI provider error message above indicates, the `404` is just as likely to be caused by the user lacking the necessary permissions to delete the node (i.e. `NotAuthorizedOrNotFound`). The provider also adds its own _hard_ taint `ignore-taint.cluster-autoscaler.kubernetes.io/oke-impending-node-termination` to the node (that is _already drained_), which unlike the CA's own `ToBeDeletedByClusterAutoscaler` taint, is not released when a scale down fails.  
The result is …
=> OCI provider: Avoid interpreting HTTP 404 as success on delete

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/endpoints/location_resolver.go
/kind bug
Fixes #8168
There is an endpoint resolution failure due to a changed JSON schema, causing scaling groups not to be discovered. Because of this, the autoscaler doesn't work at all.
`failed to unmarshal endpoint response, error: json: cannot unmarshal array into Go struct field EndpointObj.Endpoints.Endpoint.Protocols of type string`
The Protocols is not at use at all.
no
```release-note
NONE
```
=> fix bug 8168 GetEndpoint resolving fail

cluster-autoscaler/config/flags/flags.go
/kind feature
Sets the default for `--cordon-node-before-terminating` to `True`.
Fixes https://github.com/kubernetes/autoscaler/issues/8176
```release-note
Feature: the --cordon-node-before-terminating flag is set to True by default, to turn off the flag, use --cordon-node-before-terminating=false
```
```docs
```
=> feat: cordon node before terminate by default

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go, cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
/kind cleanup
this change adds debug logs at level 5 to aid in triaging failed node balancing. It adds logs to help determine why two node groups are not considered as similar. These logs can be quite noisy so the logging level has been set to 5 by default.
Fixes #
```release-note
When the balance similar node groups flag is enabled, and log verbosity is set to 5 or greater, the cluster autoscaler will emit logs detailing why node groups are not considered as similar.
```
```docs
```
=> cluster-autoscaler: add logging for failed node balancing

vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go, vertical-pod-autoscaler/pkg/recommender/input/history/history_provider_test.go, vertical-pod-autoscaler/pkg/recommender/main.go
/kind feature
This PR adds several flags for the Prometheus historical provider:
- `prometheus-insecure` – Skip TLS verification. Prometheus may use a TLS certificate, and accessing it over https:// could result in an unknown CA certificate error if the certificate is self-signed or untrusted.
- `prometheus-bearer-token` – Use a bearer token for authentication.
- `prometheus-bearer-token-file` – Read the bearer token from a file. This is useful when using [kube-rbac-proxy ](https://github.com/brancz/kube-rbac-proxy)and a service account token is mounted into the pod.
Bearer token authentication and basic authentication are mutually exclusive, as both use the Authorization header. Only one of the following combinations should be set: username + password, bearer-token, or bearer-token-file. …
=> [VPA] Add prometheus bearer auth support

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/values.yaml, cluster-autoscaler/README.md
/kind feature
Bump the Chart version to 9.47.0 and the CA image to 1.33.0
https://github.com/kubernetes/autoscaler/issues/8264
N/D
Not actually upgrade; just add a new chart version that uses the latest Cluster Autoscaler version.
N/D
=> chore: bump CA chart image to v1.33

cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
/kind cleanup
Reverts #8289 . I missed the fact that similar behavior can be achieved with `nodegroupset.NodeGroupSetProcessor`.
Fixes #
```release-note
NONE
```
```docs
```
=> Revert filter out non-existing node-groups before scale-up balancing

cluster-autoscaler/core/scaledown/actuation/drain.go, cluster-autoscaler/core/scaledown/actuation/drain_test.go, cluster-autoscaler/processors/podinjection/enforce_injected_pods_limit_processor.go, cluster-autoscaler/processors/podinjection/enforce_injected_pods_limit_processor_test.go, cluster-autoscaler/processors/podinjection/pod_injection_processor.go, cluster-autoscaler/processors/podinjection/pod_injection_processor_test.go, cluster-autoscaler/processors/podinjection/scale_up_status_processor.go, cluster-autoscaler/processors/podinjection/scale_up_status_processor_test.go, cluster-autoscaler/simulator/fake/pod.go, cluster-autoscaler/simulator/fake/pod_test.go
/kind bug
When using fake (virtual) pods, Cluster Autoscaler tries to evict them during a scale-down, triggering NotFound error. Fake pods should be omitted during eviction.
NONE
```release-note
```
=> Omit fake pods during eviction

cluster-autoscaler/cloudprovider/externalgrpc/examples/certmanager-manifests/ca.yaml
This PR adds the duration field to the self-signed CA certificate examples for the external gRPC cloud provider.
Both cluster-autoscaler-grpc-client-cert and cluster-autoscaler-grpc-server-cert are set to use a duration of 87600h.
If users apply these example manifests as-is, they may encounter errors like the following:
```
externalgrpc_cloud_provider.go:79] Error on gRPC call NodeGroups: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-07-03T12:20:01Z is after 2025-06-25T08:36:59Z"
```
N/A
```release-note
NONE
```
```docs
NONE
```
=> feat: improve external gPRC ca example

vertical-pod-autoscaler/docs/features.md, vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/pkg/recommender/logic/recommender.go, vertical-pod-autoscaler/pkg/recommender/model/types.go, vertical-pod-autoscaler/pkg/recommender/model/types_test.go
/kind feature
Adds `--round-memory-bytes` flag to the VPA recommender, enabling user-configurable rounding of Memory recommendations.
Fixes #8290 
```release-note
`--round-memory-bytes` flag to the VPA recommender
```
```docs
Documentation updated to include the `--round-memory-bytes` flag in the recommender feature set.  
```
=> feat(recommender): add round memory bytes

vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/updater/logic/updater_test.go
/kind bug
As discussed in #8288, when InPlaceUpdate (resize) fail we fallback to eviction.
part of #8288
```release-note
Fallback to eviction when InPlaceUpdate fail 
```
```docs
NONE
```
=> Fallback to eviction when InPlaceUpdate fail

.github/dependabot.yml, .github/workflows/pr.yaml
/kind feature
Adds Dependabot configuration for automatic GitHub Actions updates and updates several actions to their latest versions. This ensures CI workflows stay up-to-date with security patches and new features automatically.
Fixes #
```release-note
NONE
```
=> ci: Add Dependabot for GitHub Actions and update action versions

vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider.go
Cherry pick of #8204 on vpa-release-1.2.
#8204: include pod namespace when logging updates
=> [vpa-release-1.2] Automated cherry pick of #8204: include pod namespace when logging updates

cluster-autoscaler/cloudprovider/clusterapi/README.md
It is currently slightly confusing if you skim through the documentation.
For instance, see the discussion here:
https://github.com/kubernetes/autoscaler/pull/7974
I hope that by adding these 2 Important section the reader would be warned about the key difference, and need for these 2 options.
=> docs(autoscaler): add details about flags

cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_scale_set.go, cluster-autoscaler/cloudprovider/azure/azure_template.go, cluster-autoscaler/cloudprovider/azure/azure_template_test.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go
/kind bug /kind flake
Added a new environment variable for label prediction, allowing self-hosted users to operate without relying entirely on input labels.
Conflicts labeling upstream.
Fixes #
```release-note
Adding this label modifies the behavior of scaling from zero nodes. By default, this functionality is enabled, but it can be overridden if needed—primarily to avoid conflicts with existing AKS labels. To use label prediction instead of relying solely on input labels, self-hosted users can configure the EnableLabelPredictionsOnTemplate setting, which remains the recommended approach.
```
```docs
```
=> adding env variable EnableLabelPrediction

cluster-autoscaler/expander/grpcplugin/README.md
This PR fixes the README.md for the grpcplugin expander with the correct flags for configuring the autoscaler to use it.
```release-note
NONE
```
NONE 
```docs
NONE
```
=> Fix typo in expander/grpcplugin/README.md

cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_manager_test.go, cluster-autoscaler/cloudprovider/oci/nodepools/oci_node_pool.go
/kind bug
OCI (nodepools) implementation of cluster-autoscaler does not handle the scenarios where a node does not have a compute  instance well. This can occur in the case of Limits Exceeded, Quota Exceeded or Out of Host Capacity in the region.
The autoscaler can end up in a bad state during these scenarios as the node without the compute instance can remain without being deleted and retries to delete this node continue to occur infinitely.
This PR fixes this issue, the node without the compute instance does get deleted.
```release-note
NONE
```
```
```
=> Handle Out of host capacity scenario in OCI nodepools

vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go, vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder_test.go, vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go
This PR improves the info given when met with an "unknown error" during `validateTargetRef` since there have been multiple occasions where I've seen the following error and there are multiple paths in the code that could possibly lead to it:
```
Unknown error during checking if target is a topmost well-known or scalable controller: %!s(<nil>) with reason VerticalPodAutoscalerUnhealthy
```
Up until now there's a possibility to print a nil err, which doesn't really help with debugging the actual problem.
N/A
/cc @ialidzhikov 
```release-note
NONE
```
```docs
NONE
```
=> Improve error message for unknown error in `validateTargetRef`

cluster-autoscaler/version/version.go
/kind cleanup
This PR updates the version.go in preparation for 1.31.3 release of CA
Fixes #
```release-note
NONE
```
```docs
```
=> [cluster-autoscaler-release-1.31]: prep version.go for 1.31.3

cluster-autoscaler/version/version.go
/kind cleanup
This PR updates the version.go in preparation for 1.32.2 release of CA
Fixes #
```release-note
NONE
```
```docs
```
=> [cluster-autoscaler-release-1.32]: prep version.go for 1.32.2

cluster-autoscaler/cloudprovider/hetzner/README.md, cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go, cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group_test.go
/kind feature
Allows setting nodepool-specific image IDs instead of sharing a global default across all nodepools.
- https://github.com/kubernetes/autoscaler/issues/7537#issuecomment-2801958894
- https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1628#issuecomment-3038886417
Yes 
```release-note
- Added the option to specify nodepool-specific image IDs
```
=> Hetzner(feat): add option to set nodepool-specific image IDs

vertical-pod-autoscaler/go.mod, vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater_test.go
/kind feature
Enhances VPA updater's metrics by introducing an `update_mode` label. This allows for more granular monitoring of VPA-managed pods by distinguishing metrics based on the VPA's update mode (e.g., `Auto`, `Recreate`, `InPlaceOrRecreate`). This provides better insight into how the VPA updater behaves with different update strategies.
We're not modifying the inPlaceOrRecreate-specific metrics because they're only applicable to `InPlaceOrRecreate` `updateMode`. 
```release-note
The VPA updater metrics `vpa_updater_controlled_pods_total`, `vpa_updater_evictable_pods_total`, `vpa_updater_vpas_with_evictable_pods_total`, `vpa_updater_vpas_with_evicted_pods_total` and `vpa_updater_evicted_pods_total` now include an `update_mode` label to differentiate metrics based on the VPA's …
```
=> Add update_mode label to VPA updater metrics

cluster-autoscaler/core/autoscaler.go
/kind cleanup
/sig autoscaling
This PR fixes a typo in the comment of the `Autoscaler` interface.  
The comment for the method `LastScaleDownDeleteTime()` was incorrectly copied from `LastScaleUpTime()` and referenced "scale up" instead of "scale down".
NONE
Just a minor cleanup to improve comment correctness and readability.
```release-note
NONE
=> chore(autoscaler): fix typo in Autoscaler interface comment

cluster-autoscaler/hack/update-deps.sh
/kind cleanup
Adds macOS-compatible sed in-place update syntax.
Should be compatible w/ other sed environments as well.
Fixes #
```release-note
NONE
```
```docs
```
=> CI: make update-deps.sh macOS compatible

cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go, cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor_test.go
/kind bug
As of today:
- The core loop has been calling provider to construct node template for each NodeGroup (through `NodeGroup.TemplateNodeInfo()`)
- These templates will be used when scaling up from zero without prior cache
- In `MixedTemplateNodeInfoProvider` specifically, one NodeGroup failing this call would result in the core loop failing, halting all other operations.
- This is an issue. Failure from one NodeGroup should not be as fatal as it is today.
This change:
- Instead of failing and returning error, the NodeGroup will be skipped instead.
- Other NodeGroups can continue to be templated, and other CAS operations can continue as usual
Fixes #
```release-note
* Fix an issue where CAS does not operate when NodeGroups fails to be templated by cloud provider
```
```docs
```
=> fix: not failing the main loop when one NodeGroup fails on TemplateNodeInfo()

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go, cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
Signed-off-by: Stefan Büringer buringerst@vmware.com
/kind bug
Without this PR scale to 0 doesn't work (since https://github.com/kubernetes/autoscaler/pull/7908)
Fixes https://github.com/kubernetes/autoscaler/pull/7908#discussion_r2216687925
The unit test addition proves that scale to 0 didn't work with the previous implementation
This should be backported into v1.33.x
```release-note
NONE
```
```docs
```
=> Fix scale to 0 for Cluster API NodePool

vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater_test.go
/kind feature
This PR features a new `failed_eviction_attempts_total` [counter](evicted_pods_total) metric in the `vpa-updater` so that we can track both the successful _Pod_(s) evictions, via `evicted_pods_total` and the _failed_ attempts. Having this additional metric will allow us to calculate the _success_/_failure_ rates of the evictions.
The implementation approach follows the already existing pattern of the _in-place_ resource updates [metrics](https://github.com/kubernetes/autoscaler/blob/9b8558e24cf29fbe4806d24ea8308fb2d6a898aa/vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go#L87-L125), where we have a 
- [in_place_updated_pods_total](https://github.com/kubernetes/autoscaler/blob/9b8558e24cf29fbe4806d24ea8308fb2d6a898aa/vertical-pod-autoscaler/pkg/utils/metrics/updater …
=> feat(vpa/updater): Add a new counter metric to measure the total number of failed Pods evictions attempts

charts/cluster-autoscaler/Chart.yaml, charts/cluster-autoscaler/README.md, charts/cluster-autoscaler/README.md.gotmpl
The `helm install` code script for GCE cluster is bugged because of a typo (`Prefi` instead of `Prefix`).
This PR fixes the typo.
There is no extra change.
BTW : I updated only the `README.md.gotmpl` as I suppose it generates the `README.md`.
```release-note
NONE
```
=> fix: typo in GCE chart README code script

vertical-pod-autoscaler/pkg/updater/logic/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go, vertical-pod-autoscaler/pkg/utils/metrics/updater/updater_test.go
/kind feature
This PR introduces two additional labels (since `vpa` resources are _namespaced_ we need to include both fields):
- `vpa_name`: the __name__ of the __VPA resource that manages the Pod__ that gets updated
- `vpa_namespace`: the __namespace__ of the __VPA resource that manages the Pod__ that gets updated
for the `vpa-updater` _success_ and _fail_ resource update operations metrics:
- [evicted_pods_total](https://github.com/kubernetes/autoscaler/blob/a9cb59fdd2dd888529af74929313f3f55c73e7c9/vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go#L63-L69) total __successful__ evictions
- [failed_eviction_attempts_total](https://github.com/kubernetes/autoscaler/blob/a9cb59fdd2dd888529af74929313f3f55c73e7c9/vertical-pod-autoscaler/pkg/utils/metrics/updater/updater.go#L87-L93) …
=> feat(vpa/updater): Add `VPA` resource `name` and `namespace` to success and fail resource updates counter metrics

.github/dependabot.yml
/kind cleanup
Ensure we have (1) area, (2) release-note-none, and (3) ok-to-test labels on all dependabot PRs to master branch so we don't have to do that manually before merging
Fixes #
```release-note
NONE
```
```docs
```
=> correct labels for dependabot PRs to master

cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go
/kind feature
Static Autoscaler has been exiting `RunOnce` method early in case of scale-up, either successful or unsuccessful. This made scale-down not run in loops were scaling up was attempted.
This can cause issues with persistently failing scale-ups blocking scale-down in the cluster. I don't believe there are any reasons why we would need to keep this early-exit logic.
Please advice if you have any intuition on what could potentially break after this change. I believe the snapshot logic should be able to maintain consistent cluster state after attempting scale-up, so I don't see a reason why scale-down could fail after that.
```release-note
Remove early-exit from control loop after scale-up attempt, enabling scale-up and scale-down to be performed in a single loop
```
=> Remove exit after scale-up is performed

cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go
apiv1.LabelInstanceType is the beta.kubernetes.io label, so we should consider both that and the stable node.kubernetes.io label in the template.
/kind bug
none
```release-note
cloudprovider/hetzner now includes `node.kubernetes.io/instance-type` in the node template, not only `beta.kubernetes.io/instance-type`
```
```docs
```
=> hetzner: add node.kubernetes.io/instance-type label to template

cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/auth/signers/signer_oidc.go, cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/utils/utils.go, cluster-autoscaler/cloudprovider/alicloud/alibaba-cloud-sdk-go/sdk/utils/utils_test.go, cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config.go, cluster-autoscaler/cloudprovider/alicloud/alicloud_cloud_config_test.go
/kind bug
Fixes #8170
Fixing a bug that support for both the old "ALICLOUD_OIDC_TOKEN_FILE_PATH" and the new "ALIBABA_CLOUD_OIDC_TOKEN_FILE" env variables for RRSA isn't working.
no
-->
```release-note
NONE
```
=> Cherry pick 8171 to 1.32

cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/client.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/deprecation.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/error.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/actionutil/actions.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/ctxutil/ctxutil.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/doc.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/kit/envutil/env.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/kit/randutil/id.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/kit/sshutil/ssh_key.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/labelutil/selector.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/exp/mockutil/http.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/firewall.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/hcloud.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/load_balancer.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/pricing.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/firewall.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/load_balancer.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/primary_ip.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/server.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/schema/server_type.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/server.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/server_type.go, cluster-autoscaler/cloudprovider/hetzner/hcloud-go/hcloud/zz_schema.go
/kind cleanup
Update hcloud-go from v2.21.1 to v2.24.0
[Changelog](https://github.com/hetznercloud/hcloud-go/blob/main/CHANGELOG.md)
[Diff](https://github.com/hetznercloud/hcloud-go/compare/v2.21.1...v2.24.0)
Preparing for an upcoming PR that will add the ability to add an optional subnet configuration per pool. (Update to hcloud-go v2.24.0 adds the ability to do this) 
References about this:
https://github.com/kubernetes/autoscaler/pull/8334
https://github.com/kubernetes/autoscaler/issues/5263
https://github.com/hetznercloud/terraform-provider-hcloud/issues/672
https://github.com/hetznercloud/terraform-provider-hcloud/issues/844
https://github.com/hetznercloud/hcloud-go/pull/723
Generated by:
```
UPSTREAM_REF=v2.24.0 hack/update-vendor.sh
```
```release-note
NONE …
```
=> deps(hetzner): update vendored hcloud-go to v2.24.0

cluster-autoscaler/apis/config/crd/autoscaling.x-k8s.io_provisioningrequests.yaml, cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1beta1/types.go
/kind cleanup
v1 ProvisioningRequest has already been available for over a year and should be deprecated as per https://kubernetes.io/docs/reference/using-api/deprecation-policy/ 
Users will now see `v1beta1 ProvisioningRequest is deprecated` message when using v1beta1 ProvisioningRequest.
```release-note
Deprecate ProvisioningRequest v1beta1
```
=> Deprecate ProvisioningRequest v1beta1

cluster-autoscaler/main.go
Cherry-pick [Fix capacity buffers injector order in pod list processor](https://github.com/kubernetes/autoscaler/commit/ee760e6cf86dc634014cb30debc934c7650cd517)
=> Fix capacity buffers injector order in pod list processor

cluster-autoscaler/core/scaledown/unneeded/nodes_test.go
/kind bug
`TestNodeLoadFromExistingTaints` creates a `currentTime` variable set to `time.Now()`, and a bunch of test objects with time values offset from that variable. This is all standard practice, but then the test iterates over test cases, calls `t.Parallel()`, and overwrites `currentTime` with `time.Now()` again. This makes `go test -race` fail, because multiple goroutines are writing `currentTime` at once. It also doesn't seem to make sense in the context of the test, because the other test objects are still offset from the original value.
Removing the second write to `currentTime` seems to be the correct fix here. Also renamed one import because it collided with a local variable name used throughout this test file.
```release-note
NONE
```
=> Fix a race condition in TestNodeLoadFromExistingTaints

cluster-autoscaler/cloudprovider/test/test_cloud_provider.go, cluster-autoscaler/core/scaledown/budgets/budgets.go, cluster-autoscaler/core/scaledown/budgets/budgets_test.go, cluster-autoscaler/core/scaledown/planner/planner_test.go, cluster-autoscaler/core/static_autoscaler.go, cluster-autoscaler/core/static_autoscaler_test.go, cluster-autoscaler/processors/nodes/scale_down_set_processor.go, cluster-autoscaler/processors/nodes/scale_down_set_processor_test.go, cluster-autoscaler/utils/annotations/annotations.go
/kind bug
After introduction of `AllowNonAtomicScaleUpToMax` autoscaling option scale down does not work for zero-or-max node pools which have fewer nodes than pool's target size (e.g. due to node creation errors). CA scales such pools down only if the number of underutilized nodes is equal to pool's target size. This PR changes the scale down behavior, that is, onwards **cluster-autoscaler will also allow scale down of atomic node pools if number of underutilized nodes is equal to the number of currently registered nodes of the node pool (e.g. equal to number of healthy instances).
PR was tested manually on GKE cluster using zero-or-max scaling node pool.
```release-note
NONE
```
```docs
NONE
```
=> Allow atomic scale down of partially healthy node groups

cluster-autoscaler/main.go
/kind bug
The DRA scheduler plugin is enabled by default since 1.34. We have to hack it to be disabled if the CA DRA logic is disabled via the flag. Without this, the DRA scheduler plugin is enabled but not set up properly, and panics.
```release-note
Cluster Autoscaler no longer panics when the DRA flag is false but there are pending Pods referencing ResourceClaims in the cluster.
```
=> Fix DRA enablement logic

vertical-pod-autoscaler/docs/flags.md, vertical-pod-autoscaler/pkg/admission-controller/main.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates.go, vertical-pod-autoscaler/pkg/admission-controller/resource/pod/patch/resource_updates_test.go, vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go, vertical-pod-autoscaler/pkg/utils/annotations/vpa_cpu_boost.go, vertical-pod-autoscaler/pkg/utils/annotations/vpa_cpu_boost_test.go, vertical-pod-autoscaler/pkg/utils/test/test_vpa.go, vertical-pod-autoscaler/pkg/utils/vpa/capping.go
/kind feature
Introduces changes in the admission-controller component to apply cpu startup boost if its set in the vpa spec.
Also the original cpu request is added in annotation to verify if the updater correctly reverts back to original state.
```
Users can now configure a startupBoost policy in the VPA spec. 
```
```
- [KEP]: (https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/7862-cpu-startup-boost#aep-7862-cpu-startup-boost)
```
```release-note
Apply CPU startup boost in admission controller if its set
```
=> Apply CPU startup boost in admission controller if its set

vertical-pod-autoscaler/enhancements/7862-cpu-startup-boost/README.md
```
Fixed: Documentation for VPA StartupBoost.CPU.Type field to correctly indicate it is a required field, not optional. The field has no default value and must be explicitly set to either "Factor" or "Quantity".
Action Required: If you are using VPA StartupBoost feature, ensure your VPA configurations include the required `type` field under `startupBoost.cpu`.
Documentation: https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/7862-cpu-startup-boost#api-changes
```
Fixed #8608
The StartupBoost.CPU.Type field is required in the VPA configuration, but the documentation incorrectly marked it as optional and some examples were missing the field entirely. This PR updates the documentation to reflect the actual implementation.
Changes:
- Updated …
=> docs: update `StartupBoost.CPU.Type` to be required and fix examples

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go
/kind feature, cherry-pick https://github.com/kubernetes/autoscaler/pull/8596
Fixes #
```release-note
azure: Add support for hosted-on-behalf-of systempool autoscaling
```
```docs
```
=> [AKS HOBO][1.33 release] Add support for hosted-on-behalf-of systempool autoscaling

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go
/kind feature, cherry-pick https://github.com/kubernetes/autoscaler/pull/8596
Fixes #
```release-note
azure: Add support for hosted-on-behalf-of systempool autoscaling
```
```docs
```
=> [AKS HOBO][1.32 release] Add support for hosted-on-behalf-of systempool autoscaling

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go
/kind feature, cherry-pick https://github.com/kubernetes/autoscaler/pull/8596
Fixes #
```release-note
azure: Add support for hosted-on-behalf-of systempool autoscaling
```
```docs
```
=> [AKS HOBO][1.31 release] Add support for hosted-on-behalf-of systempool autoscaling

cluster-autoscaler/cloudprovider/azure/azure_cache.go, cluster-autoscaler/cloudprovider/azure/azure_config.go, cluster-autoscaler/cloudprovider/azure/azure_vms_pool.go
/kind feature, cherry-pick https://github.com/kubernetes/autoscaler/pull/8596
Fixes #
```release-note
azure: Add support for hosted-on-behalf-of systempool autoscaling
```
```docs
```
=> [AKS HOBO][1.34 release] Add support for hosted-on-behalf-of systempool autoscaling
